window.COURSE_MODULE = {
  "title": "Secure Serialization Foundations",
  "graphicAlt": "Bullet summary graphic for Secure Serialization Foundations.",
  "narration": "Serialization is the process of turning application objects into a data format that can be transported, stored, cached, logged, displayed, or handed to another system. In .NET applications, serialization appears in API responses, request bodies, queue messages, distributed caches, cookies, session values, configuration files, imports, exports, logs, telemetry, and integrations. Because it is so common, it can start to feel invisible. Secure engineering begins by making it visible again.\n\nDeserialization is the reverse path: the application turns external data back into an object it can use. That object may look familiar, strongly typed, and convenient, but the data did not become trustworthy simply because a serializer created a .NET object. If the data crossed a browser, API, queue, file system, database, cache, partner system, administrator tool, or support workflow, the application still needs to treat it as untrusted until it has been validated for the current decision.\n\nSecure serialization is about preserving intent at boundaries. A serialized ExampleOrderMessage should contain only the fields the consumer is supposed to receive. An ExampleCustomerDto should represent a deliberate contract, not a full domain object that happens to be easy to serialize. An ExampleApiResponse should reveal what the caller needs, not every property the server happens to know.\n\nConvenience features can hide important behavior. A serializer may populate setters, apply default values, convert types, ignore unknown data, include fields that were not meant for an external audience, or use type information in ways that deserve review. None of those features are automatically wrong, but they should be understood before they become production assumptions.\n\nThe practical goal is not to avoid serialization. Modern .NET systems need it. The goal is to design serialization paths as part of normal engineering: identify trust boundaries, use explicit contracts, validate deserialized data, protect sensitive output, review special serializer features, test malformed and incompatible data, and keep legacy patterns on a remediation plan.",
  "narrationPoints": [
    "In .NET applications, serialization appears in API responses, request bodies, queue messages, distributed caches, cookies, session values, configuration files, imports, exports, logs, telemetry, and integrations.",
    "Deserialization is the reverse path: the application turns external data back into an object it can use.",
    "An ExampleCustomerDto should represent a deliberate contract, not a full domain object that happens to be easy to serialize.",
    "None of those features are automatically wrong, but they should be understood before they become production assumptions.",
    "The practical goal is not to avoid serialization."
  ]
};
