window.COURSE_MODULE = {
  "title": "Data Formats, Boundaries, and Trust Decisions",
  "graphicAlt": "Bullet summary graphic for Data Formats, Boundaries, and Trust Decisions.",
  "narration": "A .NET application may handle JSON, XML, binary formats, form data, configuration files, queue messages, event messages, cache entries, cookies, session values, import files, and API responses in the same overall workflow. Each format has different tooling, operational expectations, compatibility concerns, and security review points. The important question is not only what format is used. It is where the data came from, who controls it, and what the application will do after reading it.\n\nTrust boundaries exist between users, browsers, APIs, services, background jobs, databases, caches, queues, file systems, administrators, and third-party systems. A value can cross more than one boundary over its lifetime. An ExampleEventMessage might be created by a service, stored in a queue, retried later by a worker, archived for audit, and then read by a support tool. Each step can change who can influence the data and what assumptions are safe.\n\nInternal data is not automatically trusted data. A cache entry may have been produced by older code. A database row may contain imported content. A queue message may be replayed after a deployment changed the object model. A configuration file may be edited by a different operational process. If serialized data affects business decisions, authorization decisions, state changes, or sensitive output, it should be validated for that use, even when it is read from an internal system.\n\nFormat choice should be deliberate. JSON is often suitable for web APIs and service messages because it is widely supported and readable. XML may be needed for established integrations or document-oriented workflows. Binary formats may be appropriate in controlled internal systems, but they often require stronger ownership and migration discipline. Custom formats should be rare because they increase maintenance cost and make review harder.\n\nContracts help teams avoid ambiguity. A message contract should define required fields, optional fields, ownership, expected producer, expected consumer, versioning rules, and whether the data may be replayed or imported later. Without that documentation, teams end up relying on tribal knowledge and serializer defaults. That makes code review harder and turns simple changes into compatibility surprises.\n\nReview who can create, modify, replay, import, or consume serialized data. A user-created ExampleImportFile should receive different treatment from a server-created ExampleSessionValue. A partner-supplied document should not inherit the trust level of the internal workflow that receives it. Secure serialization depends on clear ownership and realistic trust decisions.",
  "narrationPoints": [
    "A .NET application may handle JSON, XML, binary formats, form data, configuration files, queue messages, event messages, cache entries, cookies, session values, import files, and API responses in the same overall workflow.",
    "Trust boundaries exist between users, browsers, APIs, services, background jobs, databases, caches, queues, file systems, administrators, and third-party systems.",
    "A queue message may be replayed after a deployment changed the object model.",
    "JSON is often suitable for web APIs and service messages because it is widely supported and readable.",
    "A message contract should define required fields, optional fields, ownership, expected producer, expected consumer, versioning rules, and whether the data may be replayed or imported later."
  ]
};
