window.COURSE_MODULE = {
  "title": "Safe JSON Handling with System.Text.Json",
  "graphicAlt": "Bullet summary graphic for Safe JSON Handling with System.Text.Json.",
  "narration": "System.Text.Json is a common framework-supported serializer for modern .NET applications. It is used for ASP.NET Core APIs, background services, message processing, import and export flows, configuration-like data, and service-to-service contracts. Its presence in the platform is helpful because teams can rely on maintained behavior and familiar options. But safe use still depends on how the application shapes data at the boundary.\n\nDTOs should be intentional contracts. An ExampleCustomerDto, ExampleOrderMessage, or ExampleApiResponse should contain the fields that belong at that boundary and no more. Directly serializing broad domain objects can expose internal state, lifecycle flags, authorization-related fields, tenant markers, notes, or implementation details that were never meant for the caller. Directly deserializing broad domain objects can also populate properties the operation should not accept.\n\nAfter JSON deserialization, server-side validation is still required. The serializer can create an object with the right .NET type, but it does not know whether the ExampleTenantId belongs to the current user, whether a field is allowed for this workflow, whether a date range is business-valid, or whether an optional field is acceptable in this context. Validation should happen before business decisions, authorization-sensitive decisions, persistence, or downstream processing.\n\nRequired fields, optional fields, defaults, unknown properties, naming policies, and type conversion assumptions deserve review. A missing value might be acceptable in one version of a contract and unacceptable in another. A default value might be safe for display but unsafe for state changes. Unknown fields may be ignored by design, but teams should understand what that means for compatibility and diagnostics.\n\nAvoid overbroad object population. An update endpoint should not accept every property that exists on the server model just because JSON binding can populate it. For example, fields that affect ownership, approval state, price, role, tenant, or administrative behavior should usually be assigned by server-side logic, not accepted from a general request DTO. Use narrow DTOs for narrow operations.\n\nCustom converters are powerful and deserve higher review. A converter can change how values are read, written, normalized, interpreted, or rejected. It can also create behavior that is not obvious from the DTO itself. Review custom converters for scope, error handling, compatibility, validation assumptions, and whether they preserve the boundary contract rather than undermine it.",
  "narrationPoints": [
    "But safe use still depends on how the application shapes data at the boundary.",
    "After JSON deserialization, server-side validation is still required.",
    "A default value might be safe for display but unsafe for state changes.",
    "An update endpoint should not accept every property that exists on the server model just because JSON binding can populate it.",
    "Review custom converters for scope, error handling, compatibility, validation assumptions, and whether they preserve the boundary contract rather than undermine it."
  ]
};
