window.COURSE_MODULE = {
  "title": "Polymorphism, Type Metadata, and Legacy Serializers",
  "graphicAlt": "Bullet summary graphic for Polymorphism, Type Metadata, and Legacy Serializers.",
  "narration": "Polymorphic serialization and deserialization deserve higher review because they introduce decisions about which concrete type should be created. That may be reasonable for a controlled set of event contracts, message types, plugin models, or document variants. It becomes risky when the boundary is vague, the set of possible types is broad, or the application lets external data influence runtime type selection without a narrow contract.\n\nType metadata is sensitive because it can influence object construction and application behavior. A design that includes type names, discriminators, or contract identifiers should make the allowed set explicit and reviewable. The safer pattern is to define known contract types and map incoming data to those types intentionally. The less safe pattern is to let untrusted data choose from a wide runtime surface.\n\nWhen polymorphism is required, prefer explicit allow-lists of known contract types. For example, an ExampleEventMessage family may include a small set of approved message kinds, each with its own DTO, validation rules, and owner. The discriminator should select from that approved list, not from arbitrary runtime types. The consumer should still validate the resulting object before making decisions.\n\nLegacy serializers and older compatibility patterns should be treated as migration priorities, especially when they handle untrusted input, long-lived stored data, session state, queues, distributed caches, plugins, import tools, or integration messages. Some patterns were designed for trusted in-process or tightly controlled environments and may not match modern service boundaries. Inventory matters because teams cannot remediate what they cannot find.\n\nAvoid broad compatibility shortcuts that make object graphs hard to reason about. A shortcut that accepts many shapes, many versions, or many concrete types may feel convenient during a migration, but it can make validation and ownership unclear. Compatibility should be designed around explicit contracts, migration steps, and measured risk rather than broad acceptance.\n\nReview distributed caches, job queues, plugin systems, session state, import tools, support tools, and legacy integrations for serializer settings and assumptions. Ask who writes the data, who reads it, how long it lives, which version produced it, whether it contains sensitive fields, and whether there is a plan to retire unsafe or poorly understood patterns.",
  "narrationPoints": [
    "Polymorphic serialization and deserialization deserve higher review because they introduce decisions about which concrete type should be created.",
    "A design that includes type names, discriminators, or contract identifiers should make the allowed set explicit and reviewable.",
    "When polymorphism is required, prefer explicit allow-lists of known contract types.",
    "Some patterns were designed for trusted in-process or tightly controlled environments and may not match modern service boundaries.",
    "Review distributed caches, job queues, plugin systems, session state, import tools, support tools, and legacy integrations for serializer settings and assumptions."
  ]
};
