window.COURSE_MODULE = {
  "title": "XML, External Data, and Parser Configuration",
  "graphicAlt": "Bullet summary graphic for XML, External Data, and Parser Configuration.",
  "narration": "XML remains useful in many .NET environments, especially for established enterprise integrations, document exchange, configuration-like data, and partner workflows. Its structure can be valuable, but XML processing should be treated as boundary handling. Documents from users, partners, services, file shares, imports, and administrative tools should be considered untrusted until parsed, validated, and approved for the specific workflow.\n\nParser configuration matters. Teams should understand which XML APIs are used, how large documents are handled, whether depth or size limits are enforced, how long parsing is allowed to run, and how resource consumption is controlled. The goal is to keep parsing predictable under malformed, unexpected, or oversized documents without turning every operational issue into an outage.\n\nAvoid unnecessary external resource behavior. Many XML workflows only need to read the document that was supplied and validate its expected structure and business meaning. If a parser or document-processing library can reach outside the document, resolve additional resources, or apply behavior that the business process does not require, that configuration deserves review and usually should be narrowed.\n\nValidation should cover both structure and meaning. A document can be well-formed and still wrong for the business process. An ExampleImportFile may have the expected elements but reference an unsupported tenant, omit required ownership context, contain incompatible version information, or include values that are not valid for the current workflow. Parsing success is not the same as acceptance.\n\nSafe error handling is important. Unsupported or malformed XML should produce a controlled failure path, a safe diagnostic event, and a limited response for the caller or operator. Avoid exposing detailed parser internals, file paths, dependency information, or sensitive document content in user-facing messages. Keep detailed diagnostics protected and useful for authorized teams.\n\nDependencies that process XML and documents should be part of application security review. That includes XML readers, schema validators, transformation libraries, document libraries, import frameworks, and compatibility packages. Review their configuration, update status, operational limits, and whether they are still the right fit for the data being processed.",
  "narrationPoints": [
    "XML remains useful in many .NET environments, especially for established enterprise integrations, document exchange, configuration-like data, and partner workflows.",
    "Teams should understand which XML APIs are used, how large documents are handled, whether depth or size limits are enforced, how long parsing is allowed to run, and how resource consumption is controlled.",
    "Many XML workflows only need to read the document that was supplied and validate its expected structure and business meaning.",
    "Unsupported or malformed XML should produce a controlled failure path, a safe diagnostic event, and a limited response for the caller or operator.",
    "Dependencies that process XML and documents should be part of application security review."
  ]
};
