window.COURSE_MODULE = {
  "title": "Review, Testing, Dependencies, and Legacy Remediation",
  "graphicAlt": "Bullet summary graphic for Review, Testing, Dependencies, and Legacy Remediation.",
  "narration": "Secure serialization review should be concrete. Look for custom converters, raw object serialization, broad model binding, polymorphic settings, type metadata, legacy binary serializers, XML parser settings, caches, queues, import and export tools, diagnostic object dumps, and support utilities. These areas often hold the assumptions that ordinary feature review can miss.\n\nDependency review matters because serializers and parsers are code that process boundary data. Review System.Text.Json options, XML libraries, document-processing components, messaging libraries, compatibility packages, cache serializers, and third-party converters. Ask whether the dependency is maintained, whether its configuration is understood, whether it processes untrusted data, and whether it has access to sensitive fields.\n\nTesting should include malformed input, oversized input, missing fields, unknown fields, incompatible versions, invalid states, authorization boundaries, and sensitive field exposure. These tests do not need unsafe examples to be useful. Defensive test data can be ordinary but unexpected: a missing ExampleTenantId, an unsupported message version, an empty required field, an overly large document, or a field that should never appear in an API response.\n\nLegacy remediation starts with inventory. Find where serialized data enters, where it leaves, where it is stored, which formats are used, who owns each contract, and which flows involve sensitive output or untrusted input. Prioritize the highest-risk paths first: external inputs, long-lived stored data, broad type handling, sensitive outputs, and components with unclear ownership.\n\nRemediation usually combines several changes. Introduce DTOs, narrow contracts, add validation, document ownership, replace unsafe or poorly understood serializers, configure parsers, reduce sensitive output, add compatibility tests, and plan migrations. Avoid trying to solve every legacy path in one large rewrite unless the organization can support it. Incremental, owned remediation often works better.\n\nMonitoring helps teams see whether serialization controls are working. Track deserialization failures, unsupported versions, message rejection patterns, import errors, repeated malformed input, and unusual message volume at a defensive level. These signals can reveal operational drift, broken clients, stale producers, or workflows that need better validation and documentation.",
  "narrationPoints": [
    "Look for custom converters, raw object serialization, broad model binding, polymorphic settings, type metadata, legacy binary serializers, XML parser settings, caches, queues, import and export tools, diagnostic object dumps, and support utilities.",
    "Dependency review matters because serializers and parsers are code that process boundary data.",
    "Testing should include malformed input, oversized input, missing fields, unknown fields, incompatible versions, invalid states, authorization boundaries, and sensitive field exposure.",
    "Avoid trying to solve every legacy path in one large rewrite unless the organization can support it.",
    "Track deserialization failures, unsupported versions, message rejection patterns, import errors, repeated malformed input, and unusual message volume at a defensive level."
  ]
};
