window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Safe Reads, Writes, Temporary Files, and Race Conditions through distinct, reviewable JavaScript security boundaries.",
  "codeExamples": [
    {
      "title": "Create a private temporary file exclusively",
      "language": "javascript",
      "blurb": "A verified application-owned directory handle and descriptor-relative no-follow adapter keep generated exclusive files inside the approved directory object.",
      "code": "import { randomBytes } from \"node:crypto\";\n\nfunction safeErrorCode(error) {\n  try { return typeof error?.code === \"string\" ? error.code : undefined; }\n  catch { return undefined; }\n}\n\nexport async function createPrivateTemp(directoryHandle, openExclusiveAt) {\n  if (!directoryHandle || typeof openExclusiveAt !== \"function\") {\n    throw new TypeError(\"verified directory handle and relative opener required\");\n  }\n  for (let attempt = 0; attempt < 5; attempt += 1) {\n    const name = randomBytes(20).toString(\"hex\") + \".tmp\";\n    let close;\n    try {\n      const handle = await openExclusiveAt(directoryHandle, name, {\n        read: true, write: true, exclusive: true, noFollow: true, mode: 0o600\n      });\n      const rawClose = handle?.close;\n      close = typeof rawClose === \"function\" ? rawClose.bind(handle) : null;\n      const rawStatCapability = handle?.stat;\n      const stat = typeof rawStatCapability === \"function\"\n        ? rawStatCapability.bind(handle)\n        : null;\n      if (!stat || !close) throw new TypeError(\"temporary file handle contract invalid\");\n      const metadata = await stat();\n      const rawIsFileCapability = metadata?.isFile;\n      const isFile = typeof rawIsFileCapability === \"function\"\n        ? rawIsFileCapability.bind(metadata)\n        : null;\n      const mode = metadata?.mode;\n      if (!isFile || isFile() !== true || !Number.isSafeInteger(mode) || (mode & 0o077) !== 0) {\n        throw new Error(\"private regular temporary file required\");\n      }\n      return Object.freeze({ name, handle });\n    } catch (error) {\n      let closeError;\n      if (close) {\n        try { await close(); } catch (failure) { closeError = failure; }\n      }\n      if (closeError) {\n        throw new AggregateError([error, closeError], \"temporary creation and cleanup failed\");\n      }\n      if (safeErrorCode(error) !== \"EEXIST\") throw error;\n    }\n  }\n  throw new Error(\"temporary file allocation failed\");\n}\n"
    },
    {
      "title": "Verify descriptor identity around a sensitive read",
      "language": "javascript",
      "blurb": "The operation rejects links before opening and compares device and inode metadata after opening so observed replacement causes a fail-closed result.",
      "code": "import { lstat, open } from \"node:fs/promises\";\nimport { constants } from \"node:fs\";\n\nexport async function openObservedRegularFile(filePath) {\n  const before = await lstat(filePath);\n  if (before.isSymbolicLink() || !before.isFile() || !constants.O_NOFOLLOW) {\n    throw new Error(\"protected open unavailable\");\n  }\n  const handle = await open(filePath, constants.O_RDONLY | constants.O_NOFOLLOW);\n  let rawStat; let rawClose;\n  const inspectionErrors = [];\n  try { rawClose = handle?.close; }\n  catch (error) { inspectionErrors.push(error); }\n  try { rawStat = handle?.stat; }\n  catch (error) { inspectionErrors.push(error); }\n  const stat = typeof rawStat === \"function\" ? rawStat.bind(handle) : null;\n  const close = typeof rawClose === \"function\" ? rawClose.bind(handle) : null;\n  if (inspectionErrors.length || !stat || !close) {\n    const contractError = new TypeError(\"file handle contract invalid\");\n    const errors = [contractError, ...inspectionErrors];\n    if (close) {\n      try { await close(); }\n      catch (closeError) { errors.push(closeError); }\n    }\n    if (errors.length > 1) {\n      throw new AggregateError(errors, \"descriptor identity check and close failed\");\n    }\n    throw contractError;\n  }\n  try {\n    const after = await stat();\n    const rawIsFile = after?.isFile;\n    if (typeof rawIsFile !== \"function\" || before.dev !== after.dev ||\n        before.ino !== after.ino || !rawIsFile.call(after)) {\n      throw new Error(\"file identity changed\");\n    }\n    return handle;\n  } catch (error) {\n    try { await close(); }\n    catch (closeError) {\n      throw new AggregateError([error, closeError], \"descriptor identity check and close failed\");\n    }\n    throw error;\n  }\n}\n"
    }
  ]
};
