window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Permissions, Storage Isolation, and Secrets through distinct, reviewable JavaScript security boundaries.",
  "codeExamples": [
    {
      "title": "Enforce restrictive permissions on an application file",
      "language": "javascript",
      "blurb": "The descriptor is checked and chmod is applied through the open handle, avoiding a separate pathname-based permission change after validation.",
      "code": "export async function restrictPrivateFile(handle) {\n  let stat; let chmod;\n  try {\n    const rawStat = handle?.stat;\n    const rawChmod = handle?.chmod;\n    stat = typeof rawStat === \"function\" ? rawStat.bind(handle) : null;\n    chmod = typeof rawChmod === \"function\" ? rawChmod.bind(handle) : null;\n  } catch {\n    throw new TypeError(\"open file handle required\");\n  }\n  if (!stat || !chmod) throw new TypeError(\"open file handle required\");\n  const metadata = await stat();\n  const rawIsFile = metadata?.isFile;\n  const isFile = typeof rawIsFile === \"function\" ? rawIsFile.bind(metadata) : null;\n  if (!isFile || isFile() !== true) throw new Error(\"regular file required\");\n  await chmod(0o600);\n  const verified = await stat();\n  const verifiedMode = verified?.mode;\n  if (!Number.isInteger(verifiedMode) || (verifiedMode & 0o077) !== 0) {\n    throw new Error(\"private mode not enforced\");\n  }\n  return Object.freeze({ mode: verifiedMode & 0o777 });\n}\n"
    },
    {
      "title": "Create files through a verified private directory handle",
      "language": "javascript",
      "blurb": "A platform adapter supplies an application-owned directory handle opened without following any path component; validation and exclusive private-file creation then remain relative to that same handle.",
      "code": "const privateName = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;\n\nexport async function privateStorageFromHandle(\n  directoryHandle, expectedUid = process.getuid?.()\n) {\n  let rawStat; let rawCreate; let rawClose;\n  const inspectionErrors = [];\n  try { rawStat = directoryHandle?.stat; }\n  catch (error) { inspectionErrors.push(error); }\n  try { rawCreate = directoryHandle?.createExclusiveFile; }\n  catch (error) { inspectionErrors.push(error); }\n  try { rawClose = directoryHandle?.close; }\n  catch (error) { inspectionErrors.push(error); }\n  const stat = typeof rawStat === \"function\" ? rawStat.bind(directoryHandle) : null;\n  const createExclusiveFile = typeof rawCreate === \"function\"\n    ? rawCreate.bind(directoryHandle) : null;\n  const closeDirectory = typeof rawClose === \"function\"\n    ? rawClose.bind(directoryHandle) : null;\n  if (inspectionErrors.length || !stat || !createExclusiveFile || !closeDirectory) {\n    const contractError = new TypeError(\n      \"application-owned directory handle required\",\n      { cause: inspectionErrors[0] }\n    );\n    if (closeDirectory) {\n      try { await closeDirectory(); }\n      catch (closeError) {\n        throw new AggregateError(\n          [contractError, closeError], \"directory validation and close failed\"\n        );\n      }\n    }\n    throw contractError;\n  }\n  let validationError;\n  try {\n    const metadata = await stat();\n    const rawIsDirectory = metadata?.isDirectory;\n    const uid = metadata?.uid;\n    const mode = metadata?.mode;\n    if (typeof rawIsDirectory !== \"function\" ||\n        rawIsDirectory.call(metadata) !== true) {\n      throw new Error(\"storage directory handle required\");\n    }\n    if (expectedUid !== undefined && uid !== expectedUid) {\n      throw new Error(\"storage owner mismatch\");\n    }\n    if (!Number.isInteger(mode) || (mode & 0o077) !== 0) {\n      throw new Error(\"storage permissions too broad\");\n    }\n  } catch (error) {\n    validationError = error;\n  }\n  if (validationError) {\n    try { await closeDirectory(); }\n    catch (closeError) {\n      throw new AggregateError(\n        [validationError, closeError], \"directory validation and close failed\"\n      );\n    }\n    throw validationError;\n  }\n\n  return Object.freeze({\n    async createPrivateFile(name) {\n      if (typeof name !== \"string\" || !privateName.test(name) ||\n          name === \".\" || name === \"..\") {\n        throw new TypeError(\"private file name invalid\");\n      }\n      return createExclusiveFile(name, Object.freeze({\n        mode: 0o600, noFollow: true, closeOnExec: true\n      }));\n    },\n    close() { return closeDirectory(); }\n  });\n}\n"
    }
  ]
};
