window.COURSE_MODULE = {
  "title": "Scope Object Retrieval to the Authorized Subject",
  "narration": "One strong implementation pattern is to make the data query express the caller's allowed scope. Instead of loading an arbitrary project by ID and hoping a later branch remembers the tenant check, query for the project whose ID matches and whose tenant ID comes from trusted authentication context. A missing result then means the application has no accessible object for that subject and scope. Exact ORM method names vary, but the security property is stable: client-controlled identity does not choose the authorization boundary.\n\nThis pattern is especially useful for ownership and tenant isolation. Repository methods can require both the object identifier and an authorization scope, or accept a predicate derived from policy. Avoid generic findById helpers in sensitive services when they erase the security context. If unrestricted lookup is genuinely required for an administrative workflow, give it a distinct, narrowly used name and require the stronger policy explicitly. The code review should make the exceptional path obvious.\n\nQuery scoping also belongs on mutations. An update or delete constrained only by object ID can become a write-oriented BOLA even when the preceding read was scoped correctly. Prefer a transaction or mutation predicate that includes the same tenant, owner, membership, or version constraints. Check the affected-row result and avoid performing a second unscoped lookup that changes which record is acted upon.\n\nNot every authorization rule fits into one database predicate. Delegation, field-level views, state transitions, and relationships spanning services may require loading a scoped candidate and then evaluating an explicit policy. The safe sequence is still deliberate: establish the broadest enforceable scope during selection, obtain the specific object, apply any richer action policy, and perform the operation without losing those constraints. Query scoping is not a substitute for policy; it is a way to make common authorization omissions harder to express and to reduce the amount of unauthorized data that enters application memory.",
  "narrationPoints": [
    "Include trusted owner or tenant scope in object-selection predicates.",
    "Avoid generic findById helpers that discard authorization context.",
    "Apply equivalent scope to update and delete operations, not only reads.",
    "Use explicit policy after scoped retrieval when relationships or state require richer decisions."
  ]
};
