window.COURSE_MODULE = {
  "title": "Carrying Size Information Correctly",
  "graphicAlt": "Bullet summary graphic for Carrying Size Information Correctly.",
  "narration": "Bounds-safe C depends on carrying size information correctly. A pointer alone usually does not tell a function how many elements are valid, how much capacity remains, or whether the data is meant to be a byte region, an element array, or a C string. The size contract must travel with the pointer.\n\nWhen a function reads from a buffer, it needs to know how many elements or bytes are valid to read. When a function writes to a buffer, it needs to know the destination capacity. When a function appends, it needs both the current count and total capacity. These are different facts, and merging them into one vague parameter makes review harder.\n\nCount and capacity should stay separate. Count describes how much meaningful data is currently present. Capacity describes how much storage is available. A buffer can have capacity for one thousand bytes while currently holding only a short message. Append logic needs both numbers, and failure behavior should update neither unless the operation succeeds in a documented way.\n\nUnits matter. A length in bytes is not the same as a count of int elements, structure elements, or characters in a multibyte encoding. Function names, parameter names, and documentation should make the unit clear. A code review should not require guessing whether a value named size means bytes, elements, capacity, or current count.\n\nAvoid APIs that accept a raw pointer but not a valid length when the function needs bounds knowledge. For simple internal helpers, passing pointer plus count may be enough. For repeated patterns, a small structured buffer type can keep pointer, count, and capacity together so they are updated consistently and reviewed as one object.\n\nGood size propagation also supports maintainability. When the next developer changes a parser, extends a record, or moves a copy into a helper function, the needed bounds information should already be present. The safest API is often the one that makes the correct data flow natural and the incorrect data flow awkward.",
  "narrationPoints": [
    "Bounds-safe C depends on carrying size information correctly.",
    "Append logic needs both numbers, and failure behavior should update neither unless the operation succeeds in a documented way.",
    "A code review should not require guessing whether a value named size means bytes, elements, capacity, or current count.",
    "For repeated patterns, a small structured buffer type can keep pointer, count.",
    "When the next developer changes a parser, extends a record, or moves a copy into a helper function."
  ]
};
