window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Testing, Logging, Monitoring, and Incident Response through concrete, reviewable Python controls. Tested contract: Python 3.11, Psycopg 3.3.4, psycopg_pool 3.3.1, SQLAlchemy 2.0.51, and PostgreSQL/libpq 17 or newer.",
  "codeExamples": [
    {
      "title": "Record database connection outcomes without secrets",
      "language": "python",
      "blurb": "Finite values and an application-owned endpoint keep secrets out of telemetry. Each sink is isolated, and a separate best-effort drop signal records unavailable telemetry without replacing the database outcome.",
      "code": "DATABASE_EVENTS = frozenset({\n    \"connected\", \"timeout\", \"certificate_rejected\", \"pool_exhausted\",\n})\n\ndef _emit_without_raising(emit, record_drop, sink: str) -> None:\n    try:\n        emit()\n    except Exception:\n        try:\n            record_drop(sink)\n        except Exception:\n            pass\n\ndef record_database_event(logger, metrics, record_drop, event: object, elapsed_ms: object) -> None:\n    category = event if type(event) is str and event in DATABASE_EVENTS else \"other\"\n    bounded_elapsed = (\n        min(max(elapsed_ms, 0), 30_000)\n        if type(elapsed_ms) is int\n        else 0\n    )\n    _emit_without_raising(\n        lambda: logger.info(\n            \"database_connection_event\",\n            extra={\n                \"endpoint_id\": \"orders-primary\",\n                \"event\": category,\n                \"elapsed_ms\": bounded_elapsed,\n            },\n        ),\n        record_drop,\n        \"logger\",\n    )\n    _emit_without_raising(\n        lambda: metrics.increment(\n            \"database_connections\",\n            tags={\"endpoint\": \"orders-primary\", \"event\": category},\n        ),\n        record_drop,\n        \"metrics\",\n    )\n"
    },
    {
      "title": "Classify results from the shared bounded health probe",
      "language": "python",
      "blurb": "The application-owned probe is built on the shared capacity-limited supervisor from module 6, so this monitoring layer creates no processes or connections. It requires an exact boolean result and converts only explicit capacity, deadline, cancellation, and connection outcomes into bounded health data; invalid collaborator results and programming defects propagate to the application error boundary.",
      "code": "from dataclasses import dataclass\nfrom time import monotonic\nfrom typing import Protocol\nimport re\n\nSQLSTATE = re.compile(r\"[0-9A-Z]{5}\")\n\n@dataclass(frozen=True)\nclass DatabaseHealth:\n    healthy: bool\n    category: str\n    elapsed_ms: int\n\nclass DatabaseProbeCapacityExceeded(TimeoutError):\n    pass\n\nclass DatabaseProbeDeadlineExceeded(TimeoutError):\n    pass\n\nclass DatabaseProbeContractError(RuntimeError):\n    pass\n\nclass DatabaseProbeConnectionFailure(RuntimeError):\n    def __init__(self, sqlstate: str | None):\n        if sqlstate is not None and (\n            type(sqlstate) is not str or SQLSTATE.fullmatch(sqlstate) is None\n        ):\n            raise ValueError(\"database SQLSTATE rejected\")\n        super().__init__(\"database health probe failed\")\n        self.sqlstate = sqlstate\n\nclass BoundedDatabaseHealthProbe(Protocol):\n    # The trusted implementation uses the shared module 6 supervisor, a fixed\n    # query, bounded JSON-byte results, and no per-call worker pool of its own.\n    def __call__(self) -> bool: ...\n\ndef build_database_health_checker(run_probe: BoundedDatabaseHealthProbe):\n    def check_database_health() -> DatabaseHealth:\n        started = monotonic()\n        try:\n            healthy = run_probe()\n            if type(healthy) is not bool:\n                raise DatabaseProbeContractError(\n                    \"database health probe result rejected\"\n                )\n            category = \"ready\" if healthy else \"unexpected_result\"\n        except DatabaseProbeCapacityExceeded:\n            healthy, category = False, \"worker_capacity\"\n        except DatabaseProbeDeadlineExceeded:\n            healthy, category = False, \"client_deadline\"\n        except DatabaseProbeConnectionFailure as error:\n            healthy = False\n            category = (\n                \"query_canceled\"\n                if error.sqlstate == \"57014\"\n                else \"connection_failure\"\n            )\n        elapsed_ms = min(int((monotonic() - started) * 1000), 10_000)\n        return DatabaseHealth(healthy, category, elapsed_ms)\n\n    return check_database_health\n"
    }
  ]
};
