window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Testing, Logging, Monitoring, and Incident Response through concrete, reviewable Python controls. Tested contract: Python 3.11, Psycopg 3.3.4, psycopg_pool 3.3.1, SQLAlchemy 2.0.51, and PostgreSQL/libpq 17 or newer.",
  "codeExamples": [
    {
      "title": "Record database connection outcomes without secrets",
      "language": "python",
      "blurb": "Finite values and an application-owned endpoint keep secrets out of telemetry. Each sink is isolated, and a separate best-effort drop signal records unavailable telemetry without replacing the database outcome.",
      "code": "DATABASE_EVENTS = frozenset({\n    \"connected\", \"timeout\", \"certificate_rejected\", \"pool_exhausted\",\n})\n\ndef _emit_without_raising(emit, record_drop, sink: str) -> None:\n    try:\n        emit()\n    except Exception:\n        try:\n            record_drop(sink)\n        except Exception:\n            pass\n\ndef record_database_event(logger, metrics, record_drop, event: object, elapsed_ms: object) -> None:\n    category = event if type(event) is str and event in DATABASE_EVENTS else \"other\"\n    bounded_elapsed = (\n        min(max(elapsed_ms, 0), 30_000)\n        if type(elapsed_ms) is int\n        else 0\n    )\n    _emit_without_raising(\n        lambda: logger.info(\n            \"database_connection_event\",\n            extra={\n                \"endpoint_id\": \"orders-primary\",\n                \"event\": category,\n                \"elapsed_ms\": bounded_elapsed,\n            },\n        ),\n        record_drop,\n        \"logger\",\n    )\n    _emit_without_raising(\n        lambda: metrics.increment(\n            \"database_connections\",\n            tags={\"endpoint\": \"orders-primary\", \"event\": category},\n        ),\n        record_drop,\n        \"metrics\",\n    )\n"
    },
    {
      "title": "Classify shared supervisor health outcomes",
      "language": "python",
      "blurb": "The application-owned probe uses the shared module 6 supervisor and propagates its actual domain exceptions. This checker requires an exact boolean, converts only the shared capacity, deadline, cancellation, and connection failures into bounded health data, and lets malformed worker results and programming defects reach the application error boundary.",
      "code": "from dataclasses import dataclass\nfrom time import monotonic\nfrom typing import Protocol\n\nfrom orders_service.database_workers import (\n    DatabaseConnectionFailed,\n    DatabaseDeadlineExceeded,\n    DatabaseWorkerCapacityExceeded,\n)\n\n@dataclass(frozen=True)\nclass DatabaseHealth:\n    healthy: bool\n    category: str\n    elapsed_ms: int\n\nclass DatabaseProbeContractError(RuntimeError):\n    pass\n\nclass BoundedDatabaseHealthProbe(Protocol):\n    # The implementation uses the shared module 6 supervisor, a fixed query,\n    # bounded JSON-byte results, and no per-call worker pool of its own.\n    def __call__(self) -> bool: ...\n\ndef build_database_health_checker(run_probe: BoundedDatabaseHealthProbe):\n    def check_database_health() -> DatabaseHealth:\n        started = monotonic()\n        try:\n            healthy = run_probe()\n            if type(healthy) is not bool:\n                raise DatabaseProbeContractError(\n                    \"database health probe result rejected\"\n                )\n            category = \"ready\" if healthy else \"unexpected_result\"\n        except DatabaseWorkerCapacityExceeded:\n            healthy, category = False, \"worker_capacity\"\n        except DatabaseDeadlineExceeded:\n            healthy, category = False, \"client_deadline\"\n        except DatabaseConnectionFailed as error:\n            healthy = False\n            category = (\n                \"query_canceled\"\n                if error.sqlstate == \"57014\"\n                else \"connection_failure\"\n            )\n        elapsed_ms = min(int((monotonic() - started) * 1000), 10_000)\n        return DatabaseHealth(healthy, category, elapsed_ms)\n\n    return check_database_health\n"
    }
  ]
};
