window.COURSE_MODULE = {
  "title": "Connection Strings, Credentials, and Secret Handling",
  "graphicAlt": "A password-free connection descriptor points to a database endpoint while a separate arrow retrieves the password from a managed vault; repositories, images, logs, and backups are outside the secret path.",
  "narration": "Connection strings and DSNs describe how a Python application should reach a database. They may include hostnames, ports, database names, usernames, passwords, tokens, certificate paths, private key references, driver options, timeout values, pool settings, and TLS behavior. Even when a connection string does not contain the password directly, it may reveal internal endpoints or reference access-enabling material. Treat connection configuration as sensitive unless there is a clear reason not to.\n\nHardcoded credentials are a durable source of risk because code moves. It moves through repositories, forks, package artifacts, container images, logs, code review tools, backups, laptops, CI systems, and examples. Once a database password or private key is committed, removal from the latest file is not enough. Teams may need revocation, rotation, artifact cleanup, and incident review. The better pattern is to centralize secret access so application code reads configuration from controlled sources without embedding long-lived secrets.\n\nEnvironment variables are common and can be reasonable, but they are not magic. They may appear in process listings, crash reports, debug pages, shell history, deployment metadata, CI logs, notebooks, or container inspection output depending on the platform and practices. Managed secret stores can improve access control, rotation workflows, auditing, and separation between configuration and code, but they still require good permissions, safe retrieval, caching discipline, and clear failure behavior.\n\nSecure secret handling should be boring in the best way: centralized, reviewable, easy to rotate, and hard to accidentally leak. Applications should fail closed when required secrets are missing or malformed. Logs and exceptions should never print passwords, tokens, private keys, or full sensitive connection strings. Development credentials should be clearly separated from production, and test fixtures should avoid teaching developers that fake-looking secrets belong in source code.",
  "narrationPoints": [
    "Connection strings and DSNs describe how a Python application should reach a database.",
    "The better pattern is to centralize secret access so application code reads configuration from controlled sources without embedding long-lived secrets.",
    "Environment variables are common and can be reasonable, but they are not magic.",
    "Logs and exceptions should never print passwords, tokens, private keys, or full sensitive connection strings.",
    "Treat connection configuration as sensitive unless there is a clear reason not to.",
    "Even when a connection string does not contain the password directly, it may reveal internal endpoints or reference access-enabling material."
  ]
};
