window.COURSE_MODULE = {
  "title": "Least Privilege and Environment Separation",
  "graphicAlt": "Runtime, reporting, and migration accounts appear as three keys with progressively different grants; the web service key cannot open schema-change or administrative locks.",
  "narration": "Least privilege means a database account has only the access needed for its approved purpose. A public web application may need to read and write specific tables, but it usually should not create schemas, manage users, change permissions, disable audit settings, or read unrelated data sets. A reporting process may need read-only access. A migration job may need schema-change privileges for a short operational window. Administrative credentials should not live inside normal application runtimes.\n\nSeparate accounts make intent visible. Read-only, read-write, migration, reporting, maintenance, and administrative identities should not be treated as cosmetic labels on the same broad access. Their privileges should reflect what the workload is allowed to do, and their use should be observable in logs. When an application account performs an unexpected schema change, connects from an unexpected environment, or touches data outside its purpose, that should stand out rather than blend into normal administrator activity.\n\nEnvironment separation is equally important. Development, staging, and production should use different credentials, different databases or schemas as appropriate, and different access policies. A local script should not accidentally point at production because a copied environment file had a real endpoint. CI jobs should not inherit developer credentials. Staging data should not create privacy risk simply because it feels less important than production. Separation reduces blast radius and makes mistakes easier to detect.\n\nModern platforms may also support workload identity, short-lived tokens, or managed service accounts. Those patterns can reduce the need for long-lived static passwords, but they do not remove the need for database permissions, environment boundaries, and rotation planning. The principle is stable: the connection identity should match the application purpose, carry only necessary privileges, and be revocable without guessing which systems will break.",
  "narrationPoints": [
    "Least privilege means a database account has only the access needed for its approved purpose.",
    "Their privileges should reflect what the workload is allowed to do, and their use should be observable in logs.",
    "Staging data should not create privacy risk simply because it feels less important than production.",
    "Modern platforms may also support workload identity, short-lived tokens, or managed service accounts.",
    "Development, staging, and production should use different credentials, different databases or schemas as appropriate, and different access policies.",
    "A local script should not accidentally point at production because a copied environment file had a real endpoint."
  ]
};
