window.COURSE_MODULE = {
  "title": "Frameworks, ORMs, Migrations, and Background Jobs",
  "graphicAlt": "Framework request, ORM session, background task, and migration runner enter the data layer through separate lifecycle boxes, all converging on the same secret, TLS, role, and timeout policy.",
  "narration": "Python database access often sits behind a framework or ORM. Django centralizes many database settings, SQLAlchemy-style engines collect driver and pool configuration, and Flask or FastAPI applications commonly assemble a data layer with dependency injection, sessions, or request lifecycle hooks. Those abstractions are helpful, but they do not guarantee secure configuration. Reviewers should still confirm how secrets are loaded, whether TLS expectations are enforced, which account is used, and how connections are opened and closed.\n\nORMs can make common workflows safer and more maintainable, yet they also provide escape hatches. Raw SQL, dynamic filters, custom connection options, and multiple engine definitions may bypass the assumptions used in the rest of the application. A secure connection standard should apply consistently whether code uses a high-level model, a migration tool, an async driver, a reporting query, or a lower-level database cursor.\n\nMigrations need special handling because they often require privileges normal runtime code should not have. Schema changes, index creation, data backfills, and administrative maintenance can require broader authority and longer execution windows. That does not mean the web application should run forever with those powers. Migration credentials, deployment jobs, approval processes, and audit logs should make privileged database changes intentional, time-bounded, and attributable.\n\nBackground jobs, scheduled tasks, notebooks, and data scripts frequently become exceptions to secure patterns. They may be written quickly, run with copied connection strings, skip TLS options, log full errors, or use production data casually. Treat every code path that connects to the database as part of the security boundary. The same expectations for secret handling, environment separation, least privilege, logging hygiene, and safe failure behavior should follow the data wherever it is accessed.",
  "narrationPoints": [
    "Python database access often sits behind a framework or ORM.",
    "ORMs can make common workflows safer and more maintainable, yet they also provide escape hatches.",
    "Migrations need special handling because they often require privileges normal runtime code should not have.",
    "Treat every code path that connects to the database as part of the security boundary.",
    "Schema changes, index creation, data backfills, and administrative maintenance can require broader authority and longer execution windows.",
    "Migration credentials, deployment jobs, approval processes, and audit logs should make privileged database changes intentional, time-bounded, and attributable."
  ]
};
