window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Databases, Files, Caches, Queues, and Backups' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Persist encrypted customer data with typed parameters",
      "language": "csharp",
      "blurb": "The command accepts only canonical tenant and record identifiers plus bounded encrypted bytes, uses one fixed SQL literal, binds explicit parameter types and sizes, copies the ciphertext for provider ownership, and disposes partial state on failure.",
      "code": "using System.Data;\nusing System.Data.Common;\n\npublic static class EncryptedCustomerInsert\n{\n    public static DbCommand Create(\n        DbConnection connection,\n        string tenantId,\n        string recordId,\n        ReadOnlySpan<byte> encryptedEmail)\n    {\n        ArgumentNullException.ThrowIfNull(connection);\n        if (!IsIdentifier(tenantId) || !IsIdentifier(recordId))\n            throw new ArgumentException(\"Record identity rejected.\");\n        if (encryptedEmail.Length is < 28 or > 64 * 1024)\n            throw new ArgumentException(\"Encrypted field size rejected.\", nameof(encryptedEmail));\n\n        var command = connection.CreateCommand();\n        try\n        {\n            command.CommandText =\n                \"INSERT INTO CustomerSecrets (TenantId, RecordId, EncryptedEmail) \" +\n                \"VALUES (@tenant, @record, @encryptedEmail)\";\n            Add(command, \"@tenant\", DbType.String, tenantId, 64);\n            Add(command, \"@record\", DbType.String, recordId, 64);\n            Add(command, \"@encryptedEmail\", DbType.Binary, encryptedEmail.ToArray(), 64 * 1024);\n            return command;\n        }\n        catch (Exception operationError)\n        {\n            try\n            {\n                command.Dispose();\n            }\n            catch (Exception cleanupError)\n            {\n                throw new AggregateException(\n                    \"Command construction and cleanup both failed.\",\n                    operationError,\n                    cleanupError);\n            }\n            throw;\n        }\n    }\n\n    private static void Add(DbCommand command, string name, DbType type, object value, int size)\n    {\n        var parameter = command.CreateParameter();\n        parameter.ParameterName = name;\n        parameter.DbType = type;\n        parameter.Size = size;\n        parameter.Value = value;\n        command.Parameters.Add(parameter);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    },
    {
      "title": "Cache only bounded authenticated ciphertext for a short lifetime",
      "language": "csharp",
      "blurb": "The cache value copies ciphertext into owned storage, requires enough bytes for nonce and authentication tag, rejects excessive data, obtains time from a trusted clock, caps lifetime at fifteen minutes, and returns copies to callers.",
      "code": "public sealed class ProtectedCacheEntry\n{\n    private readonly byte[] _ciphertext;\n\n    private ProtectedCacheEntry(byte[] ciphertext, DateTimeOffset expiresUtc)\n    {\n        _ciphertext = ciphertext;\n        ExpiresUtc = expiresUtc;\n    }\n\n    public DateTimeOffset ExpiresUtc { get; }\n\n    public static ProtectedCacheEntry Create(\n        ReadOnlySpan<byte> authenticatedCiphertext,\n        DateTimeOffset expiresUtc,\n        TimeProvider clock)\n    {\n        ArgumentNullException.ThrowIfNull(clock);\n        if (authenticatedCiphertext.Length is < 28 or > 64 * 1024)\n            throw new ArgumentException(\"Cached ciphertext size rejected.\", nameof(authenticatedCiphertext));\n        var now = clock.GetUtcNow();\n        if (expiresUtc <= now || expiresUtc - now > TimeSpan.FromMinutes(15))\n            throw new ArgumentOutOfRangeException(nameof(expiresUtc));\n        return new ProtectedCacheEntry(authenticatedCiphertext.ToArray(), expiresUtc);\n    }\n\n    public byte[] CopyCiphertext() => (byte[])_ciphertext.Clone();\n}\n"
    }
  ]
};
