window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'APIs, Serialization, DTOs, and Client Exposure' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Map protected customer storage into a minimal public DTO",
      "language": "csharp",
      "blurb": "The storage factory validates bounded public fields and ciphertext evidence, retains only whether protected email exists, and the mapper exposes identity, display name, and that Boolean with no property through which ciphertext or key metadata can escape.",
      "code": "using System.Text;\n\npublic sealed class ProtectedCustomerRecord\n{\n    private ProtectedCustomerRecord(string id, string displayName, bool hasEncryptedEmail)\n    {\n        Id = id;\n        DisplayName = displayName;\n        HasEncryptedEmail = hasEncryptedEmail;\n    }\n\n    public string Id { get; }\n    public string DisplayName { get; }\n    public bool HasEncryptedEmail { get; }\n\n    public static ProtectedCustomerRecord FromStorage(\n        string id,\n        string displayName,\n        ReadOnlySpan<byte> encryptedEmail)\n    {\n        if (!IsIdentifier(id) || !IsDisplayName(displayName) ||\n            encryptedEmail.Length is < 28 or > 64 * 1024)\n        {\n            throw new ArgumentException(\"Protected customer record rejected.\");\n        }\n        return new ProtectedCustomerRecord(id, displayName, hasEncryptedEmail: true);\n    }\n\n    public static ProtectedCustomerRecord WithoutEmail(string id, string displayName)\n    {\n        if (!IsIdentifier(id) || !IsDisplayName(displayName))\n            throw new ArgumentException(\"Protected customer record rejected.\");\n        return new ProtectedCustomerRecord(id, displayName, hasEncryptedEmail: false);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n\n    private static bool IsDisplayName(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 80 &&\n        Encoding.UTF8.GetByteCount(value) <= 160 && !value.Any(char.IsControl) &&\n        string.Equals(value, value.Trim(), StringComparison.Ordinal);\n}\n\npublic sealed record PublicCustomerResponse(\n    string Id,\n    string DisplayName,\n    bool HasEmail);\n\npublic static class PublicCustomerMapper\n{\n    public static PublicCustomerResponse Map(ProtectedCustomerRecord record)\n    {\n        ArgumentNullException.ThrowIfNull(record);\n        return new PublicCustomerResponse(\n            record.Id,\n            record.DisplayName,\n            record.HasEncryptedEmail);\n    }\n}\n"
    },
    {
      "title": "Parse a strict support-note command with no secret fields",
      "language": "csharp",
      "blurb": "The parser enforces a physical UTF-8 ceiling, shallow object shape, exact case-sensitive members, duplicate rejection, and bounded control-free text; unknown fields such as password, token, or connectionString fail closed.",
      "code": "using System.Text;\nusing System.Text.Json;\n\npublic sealed class SupportNoteCommand\n{\n    private SupportNoteCommand(string caseId, string note)\n    {\n        CaseId = caseId;\n        Note = note;\n    }\n\n    public string CaseId { get; }\n    public string Note { get; }\n\n    public static SupportNoteCommand Parse(ReadOnlyMemory<byte> utf8Json)\n    {\n        if (utf8Json.Length is 0 or > 8 * 1024)\n            throw new JsonException(\"Support note size rejected.\");\n        using var document = JsonDocument.Parse(utf8Json, new JsonDocumentOptions\n        {\n            AllowTrailingCommas = false,\n            CommentHandling = JsonCommentHandling.Disallow,\n            MaxDepth = 2\n        });\n        if (document.RootElement.ValueKind != JsonValueKind.Object)\n            throw new JsonException(\"Support note must be an object.\");\n\n        string? caseId = null;\n        string? note = null;\n        var names = new HashSet<string>(StringComparer.Ordinal);\n        foreach (var property in document.RootElement.EnumerateObject())\n        {\n            if (!names.Add(property.Name))\n                throw new JsonException(\"Duplicate support-note member rejected.\");\n            switch (property.Name)\n            {\n                case \"caseId\":\n                    caseId = ReadString(property.Value);\n                    break;\n                case \"note\":\n                    note = ReadString(property.Value);\n                    break;\n                default:\n                    throw new JsonException(\"Unknown support-note member rejected.\");\n            }\n        }\n        if (!IsIdentifier(caseId) || !IsNote(note))\n            throw new JsonException(\"Support-note value rejected.\");\n        return new SupportNoteCommand(caseId!, note!);\n    }\n\n    private static string ReadString(JsonElement value) =>\n        value.ValueKind == JsonValueKind.String && value.GetString() is string text\n            ? text\n            : throw new JsonException(\"Support-note field must be a string.\");\n\n    private static bool IsIdentifier(string? value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n\n    private static bool IsNote(string? value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 1_000 &&\n        Encoding.UTF8.GetByteCount(value) <= 2_000 && !value.Any(char.IsControl);\n}\n"
    }
  ]
};
