window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Encryption, Data Protection, and Key Management' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Encrypt one sensitive field with AES-256-GCM and bound metadata",
      "language": "csharp",
      "blurb": "The producer validates a 256-bit key, canonical key and record identifiers, and a physical plaintext ceiling; generates a fresh nonce; authenticates the record identifier as associated data; and returns canonical owned envelope strings.",
      "code": "using System.Security.Cryptography;\nusing System.Text;\nusing Microsoft.AspNetCore.WebUtilities;\n\npublic sealed record EncryptedField(\n    string Algorithm,\n    string KeyId,\n    string Nonce,\n    string Ciphertext,\n    string Tag);\n\npublic static class SensitiveFieldEncryption\n{\n    public static EncryptedField Encrypt(\n        ReadOnlySpan<byte> plaintext,\n        ReadOnlySpan<byte> key,\n        string keyId,\n        string recordId)\n    {\n        if (key.Length != 32)\n            throw new ArgumentException(\"A 256-bit key is required.\", nameof(key));\n        if (plaintext.Length is 0 or > 64 * 1024)\n            throw new ArgumentException(\"Plaintext size rejected.\", nameof(plaintext));\n        if (!IsIdentifier(keyId) || !IsIdentifier(recordId))\n            throw new ArgumentException(\"Encryption metadata rejected.\");\n\n        var nonce = RandomNumberGenerator.GetBytes(12);\n        var ciphertext = new byte[plaintext.Length];\n        var tag = new byte[16];\n        var associatedData = Encoding.UTF8.GetBytes(recordId);\n        try\n        {\n            using var aes = new AesGcm(key, tag.Length);\n            aes.Encrypt(nonce, plaintext, ciphertext, tag, associatedData);\n            return new EncryptedField(\n                \"A256GCM\",\n                keyId,\n                WebEncoders.Base64UrlEncode(nonce),\n                WebEncoders.Base64UrlEncode(ciphertext),\n                WebEncoders.Base64UrlEncode(tag));\n        }\n        finally\n        {\n            CryptographicOperations.ZeroMemory(associatedData);\n        }\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    },
    {
      "title": "Plan a monotonic encryption-key rotation from validated metadata",
      "language": "csharp",
      "blurb": "The factories create immutable UTC version metadata and a privately constructed rotation plan only when both keys are active, the next version is exactly monotonic, neither creation timestamp is in the future, and activation stays within the seven-day policy.",
      "code": "public enum EncryptionKeyState\n{\n    Active,\n    DecryptOnly\n}\n\npublic sealed class EncryptionKeyVersion\n{\n    private EncryptionKeyVersion(\n        string keyId,\n        int version,\n        EncryptionKeyState state,\n        DateTimeOffset createdUtc)\n    {\n        KeyId = keyId;\n        Version = version;\n        State = state;\n        CreatedUtc = createdUtc;\n    }\n\n    public string KeyId { get; }\n    public int Version { get; }\n    public EncryptionKeyState State { get; }\n    public DateTimeOffset CreatedUtc { get; }\n\n    public static EncryptionKeyVersion Create(\n        string keyId,\n        int version,\n        EncryptionKeyState state,\n        DateTimeOffset createdUtc)\n    {\n        if (!IsIdentifier(keyId) || version is < 1 or > 1_000_000 || !Enum.IsDefined(state) ||\n            createdUtc.Offset != TimeSpan.Zero || createdUtc.Year is < 2020 or > 2200)\n            throw new ArgumentException(\"Key metadata rejected.\");\n        return new EncryptionKeyVersion(keyId, version, state, createdUtc);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n\npublic sealed class EncryptionKeyRotationPlan\n{\n    private EncryptionKeyRotationPlan(\n        EncryptionKeyVersion current,\n        EncryptionKeyVersion next,\n        DateTimeOffset activateUtc)\n    {\n        Current = current;\n        Next = next;\n        ActivateUtc = activateUtc;\n    }\n\n    public EncryptionKeyVersion Current { get; }\n    public EncryptionKeyVersion Next { get; }\n    public DateTimeOffset ActivateUtc { get; }\n\n    public static EncryptionKeyRotationPlan Create(\n        EncryptionKeyVersion current,\n        EncryptionKeyVersion next,\n        DateTimeOffset activateUtc,\n        TimeProvider clock)\n    {\n        ArgumentNullException.ThrowIfNull(current);\n        ArgumentNullException.ThrowIfNull(next);\n        ArgumentNullException.ThrowIfNull(clock);\n        var now = clock.GetUtcNow();\n        if (current.State != EncryptionKeyState.Active ||\n            next.State != EncryptionKeyState.Active ||\n            !string.Equals(current.KeyId, next.KeyId, StringComparison.Ordinal) ||\n            current.Version == int.MaxValue || next.Version != current.Version + 1 ||\n            next.CreatedUtc < current.CreatedUtc || next.CreatedUtc > now ||\n            activateUtc.Offset != TimeSpan.Zero ||\n            activateUtc < now || activateUtc - now > TimeSpan.FromDays(7))\n        {\n            throw new InvalidOperationException(\"Key rotation policy rejected.\");\n        }\n        return new EncryptionKeyRotationPlan(current, next, activateUtc);\n    }\n}\n"
    }
  ]
};
