window.COURSE_MODULE = {
  "title": "Secure Django Template Rendering",
  "graphicAlt": "A Django view selects accounts/detail.html and passes ordinary strings to autoescaping; a format_html helper escapes label and class values without applying mark_safe to concatenated content.",
  "narration": "Django templates provide security-oriented defaults that help reduce common rendering mistakes. Template variables are normally handled through the template engine rather than concatenated into raw strings. Filters, inclusion tags, form rendering, reusable components, admin customization, and error templates all give teams productive ways to build pages. The secure path is to keep Django's normal escaping behavior intact unless there is a reviewed reason to do otherwise.\n\nFilters and tags deserve attention because they can transform data before it reaches the browser. Some filters are safe for ordinary display. Others can change how escaping works or return content that is treated differently by the template engine. Marking content safe or turning autoescaping off changes a template from data rendering into a much more sensitive operation. That choice should be visible, reviewed, and tied to trusted input or vetted sanitization.\n\nDjango admin and error templates are easy to overlook. Admin pages may display user-generated fields, imported records, support messages, filenames, and diagnostic information to privileged users. Error templates may include request details or messages from lower layers. These users often have powerful sessions and access to sensitive workflows, so internal pages still need careful rendering and response minimization.\n\nDjango protections should be used consistently rather than bypassed for convenience. If a project needs rich content, it should define a policy and sanitization approach. If a reusable component accepts markup, it should document exactly what is trusted. If a template shows translated text or third-party data, that path should still respect the output context. Strong Django rendering keeps framework defaults, component design, and review aligned.",
  "narrationPoints": [
    "Template variables are normally handled through the template engine rather than concatenated into raw strings.",
    "Filters and tags deserve attention because they can transform data before it reaches the browser.",
    "Admin pages may display user-generated fields, imported records, support messages, filenames, and diagnostic information to privileged users.",
    "Django protections should be used consistently rather than bypassed for convenience.",
    "Others can change how escaping works or return content that is treated differently by the template engine.",
    "Marking content safe or turning autoescaping off changes a template from data rendering into a much more sensitive operation."
  ]
};
