window.COURSE_MODULE = {
  "title": "Secure Jinja and Flask Template Rendering",
  "graphicAlt": "Flask maps a symbolic view name to two installed templates, and Jinja embeds structured page data through tojson with a CSP nonce rather than interpolated JavaScript text.",
  "narration": "Jinja templates are widely used in Flask and other Python web applications. Like other template engines, Jinja can support autoescaping in appropriate contexts, filters, macros, includes, and helper functions. These features make applications easier to build, but they also create places where data can be transformed, marked safe, or inserted into a context the developer did not fully consider. Secure use starts with normal template files and safe variable rendering.\n\nRendering trusted template files is different from treating untrusted input as template source. A template file written by the application team is intended code-like presentation logic. A user-submitted string, partner value, or database field should be data, not a template. When applications allow dynamic templates or render strings as templates, they are creating a much more sensitive boundary that needs strong justification and careful controls.\n\nFlask applications also render messages, flashed content, error pages, redirects, and internal dashboards. Those paths often feel minor, but they may display request data, user names, filenames, form errors, or operational messages. Helper functions that build markup or URLs should be reviewed because they can centralize either a safe pattern or an unsafe one. Template flexibility is useful only when the trust boundary remains clear.\n\nA good Jinja and Flask rendering practice favors reviewed templates, autoescaping, context-aware output, and narrow helper functions. It avoids untrusted template source, broad globals, unsafe filters, and markup-returning helpers unless the content source and output context are well controlled. The goal is to make template behavior predictable enough that reviewers can tell which values are data and which values are trusted presentation logic.",
  "narrationPoints": [
    "Like other template engines, Jinja can support autoescaping in appropriate contexts, filters, macros, includes, and helper functions.",
    "A user-submitted string, partner value, or database field should be data, not a template.",
    "Flask applications also render messages, flashed content, error pages, redirects, and internal dashboards.",
    "A good Jinja and Flask rendering practice favors reviewed templates, autoescaping, context-aware output, and narrow helper functions.",
    "Rendering trusted template files is different from treating untrusted input as template source.",
    "A template file written by the application team is intended code-like presentation logic."
  ]
};
