window.COURSE_MODULE = {
  "title": "Testing, Review, Logging, and Remediation",
  "graphicAlt": "A regression matrix places payloads in text, quoted attributes, URLs, JSON data, email templates, and reusable components; finite logs identify template and failure category without rendered content.",
  "narration": "Template review should follow untrusted data into output contexts. Reviewers can ask which templates render user-controlled fields, which helpers return markup, which filters affect escaping, and which pages display logs, translated text, rich content, emails, reports, or admin data. Searching for disabled escaping, unsafe filters, raw HTML insertion, untrusted template strings, risky helpers, and unclear rich-content handling can reveal the most important review targets.\n\nTests should verify that known risky fields and reusable components continue to escape, sanitize, or reject untrusted content correctly. Regression tests are valuable for stored content because a value saved months ago can become unsafe when a template changes. Teams should test emails, error pages, admin pages, reports, and reusable components, not only the main customer-facing page. Rendering safety belongs to every output path.\n\nLogging should support investigation without creating new exposure. Logs should avoid secrets, credentials, tokens, session values, and unnecessary sensitive rendered content. Monitoring client-side errors and suspicious rendering failures can help identify broken templates or unexpected content. At the same time, reports and logs may contain user-controlled fields, so operational tools must render them safely too.\n\nRemediation should fix the underlying rendering path. That may mean restoring autoescaping, replacing raw insertion, narrowing helper behavior, sanitizing rich content with a reviewed policy, re-sanitizing stored content, reducing response fields, updating tests, or reviewing related templates that share the same component. Template security requires continuous review as features, content types, and frontend behavior evolve.",
  "narrationPoints": [
    "Template review should follow untrusted data into output contexts.",
    "Teams should test emails, error pages, admin pages, reports, and reusable components, not only the main customer-facing page.",
    "Monitoring client-side errors and suspicious rendering failures can help identify broken templates or unexpected content.",
    "Template security requires continuous review as features, content types, and frontend behavior evolve.",
    "Tests should verify that known risky fields and reusable components continue to escape, sanitize, or reject untrusted content correctly.",
    "Logs should avoid secrets, credentials, tokens, session values, and unnecessary sensitive rendered content."
  ]
};
