window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Replay Resistance, Freshness, and Idempotency through concrete, reviewable Python controls.",
  "codeExamples": [
    {
      "title": "Track replay state through retryable processing",
      "language": "python",
      "blurb": "An atomic store key includes integration and event identity; processing, applied, retryable-failure, and permanently-rejected states distinguish concurrent replay from a legitimate retry.",
      "code": "from dataclasses import dataclass\nfrom enum import Enum\nimport re\n\nEVENT_ID = re.compile(r\"evt_[A-Za-z0-9_-]{16,80}\")\nINTEGRATION_ID = re.compile(r\"int_[A-Za-z0-9_-]{8,40}\")\nLEASE_TOKEN = re.compile(r\"[A-Za-z0-9_-]{16,128}\")\n\nclass ReplayState(Enum):\n    PROCESSING = \"processing\"\n    APPLIED = \"applied\"\n    RETRYABLE_FAILURE = \"retryable_failure\"\n    PERMANENTLY_REJECTED = \"permanently_rejected\"\n\n@dataclass(frozen=True)\nclass ReplayLease:\n    key: str\n    token: str\n\n    def __post_init__(self) -> None:\n        if (\n            type(self.key) is not str\n            or not 1 <= len(self.key) <= 256\n            or type(self.token) is not str\n            or LEASE_TOKEN.fullmatch(self.token) is None\n        ):\n            raise ValueError(\"webhook replay lease rejected\")\n\ndef begin_webhook_event(\n    store,\n    integration_id: str,\n    event_id: str,\n    timestamp: int,\n) -> ReplayLease:\n    if (\n        type(integration_id) is not str\n        or INTEGRATION_ID.fullmatch(integration_id) is None\n        or type(event_id) is not str\n        or EVENT_ID.fullmatch(event_id) is None\n    ):\n        raise ValueError(\"webhook replay identity rejected\")\n    if type(timestamp) is not int or not 0 <= timestamp <= 4_102_444_800:\n        raise ValueError(\"webhook timestamp rejected\")\n    key = f\"webhook-replay:{integration_id}:{event_id}\"\n    result = store.begin_or_resume(\n        key=key,\n        authenticated_timestamp=timestamp,\n        initial_state=ReplayState.PROCESSING.value,\n        resume_from={ReplayState.RETRYABLE_FAILURE.value},\n        expires_in_seconds=24 * 60 * 60,\n    )\n    try:\n        status = result.status\n        token = result.lease_token\n    except Exception:\n        raise RuntimeError(\"webhook replay store result rejected\") from None\n    if type(status) is not str or status not in {\"reserved\", \"resumed\"}:\n        raise PermissionError(\"concurrent or completed webhook replay rejected\")\n    if type(token) is not str or LEASE_TOKEN.fullmatch(token) is None:\n        raise RuntimeError(\"webhook replay store result rejected\")\n    return ReplayLease(key, token)\n\ndef finish_webhook_event(\n    store,\n    lease: ReplayLease,\n    outcome: ReplayState,\n) -> None:\n    if type(lease) is not ReplayLease:\n        raise TypeError(\"validated replay lease required\")\n    if outcome not in {\n        ReplayState.APPLIED,\n        ReplayState.RETRYABLE_FAILURE,\n        ReplayState.PERMANENTLY_REJECTED,\n    }:\n        raise ValueError(\"terminal webhook replay state rejected\")\n    store.transition(\n        key=lease.key,\n        lease_token=lease.token,\n        expected_state=ReplayState.PROCESSING.value,\n        new_state=outcome.value,\n    )\n"
    },
    {
      "title": "Make webhook application idempotent in one transaction",
      "language": "python",
      "blurb": "A unique event insert and the business state change commit together, so retries report the prior result instead of applying the effect twice.",
      "code": "import re\n\nEVENT_ID = re.compile(r\"evt_[A-Za-z0-9_-]{16,80}\")\nPAYMENT_ID = re.compile(r\"pay_[A-Za-z0-9]{16,40}\")\n\ndef apply_payment_event(\n    connection,\n    event_id: str,\n    payment_id: str,\n    status: str,\n) -> str:\n    if type(event_id) is not str or EVENT_ID.fullmatch(event_id) is None:\n        raise ValueError(\"event identifier rejected\")\n    if type(payment_id) is not str or PAYMENT_ID.fullmatch(payment_id) is None:\n        raise ValueError(\"payment identifier rejected\")\n    if type(status) is not str or status not in {\"settled\", \"failed\"}:\n        raise ValueError(\"payment status rejected\")\n    with connection.transaction():\n        inserted = connection.execute(\n            \"insert into processed_webhook (event_id) values (%s) \"\n            \"on conflict do nothing returning event_id\",\n            (event_id,),\n        ).fetchone()\n        if inserted is None:\n            return \"already_processed\"\n        if (\n            type(inserted) not in {tuple, list}\n            or len(inserted) != 1\n            or inserted[0] != event_id\n        ):\n            raise RuntimeError(\"webhook idempotency result rejected\")\n        updated = connection.execute(\n            \"update payments set status = %s \"\n            \"where public_id = %s and status = 'pending'\",\n            (status, payment_id),\n        )\n        if type(updated.rowcount) is not int or updated.rowcount != 1:\n            raise ValueError(\"payment transition rejected\")\n    return \"applied\"\n"
    }
  ]
};
