window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Processing Patterns, Queues, and Reliability through concrete, reviewable Python controls.",
  "codeExamples": [
    {
      "title": "Publish authenticated webhooks to a durable queue",
      "language": "python",
      "blurb": "The endpoint acknowledges only after a bounded, persistent queue publish succeeds, and the message contains validated identifiers rather than the signature or secret.",
      "code": "from dataclasses import dataclass\nimport re\n\nEVENT_ID = re.compile(r\"evt_[A-Za-z0-9_-]{16,80}\")\nINTEGRATION_ID = re.compile(r\"int_[A-Za-z0-9_-]{8,40}\")\nEVENT_TYPES = {\"payment.settled\", \"payment.failed\"}\n\n@dataclass(frozen=True)\nclass WebhookJob:\n    event_id: str\n    event_type: str\n    integration_id: str\n\ndef enqueue_webhook(\n    queue,\n    event: dict[str, object],\n    integration_id: str,\n) -> tuple[str, int]:\n    if (\n        not isinstance(event, dict)\n        or set(event) != {\"version\", \"event_id\", \"type\", \"data\"}\n    ):\n        raise ValueError(\"validated webhook event required\")\n    event_id = event[\"event_id\"]\n    event_type = event[\"type\"]\n    if type(event_id) is not str or EVENT_ID.fullmatch(event_id) is None:\n        raise ValueError(\"event identifier rejected\")\n    if type(event_type) is not str or event_type not in EVENT_TYPES:\n        raise ValueError(\"event type rejected\")\n    if (\n        type(integration_id) is not str\n        or INTEGRATION_ID.fullmatch(integration_id) is None\n    ):\n        raise ValueError(\"integration identifier rejected\")\n    job = WebhookJob(event_id, event_type, integration_id)\n    receipt = queue.publish(job, persistent=True, timeout=2.0)\n    try:\n        confirmed = receipt.confirmed\n    except Exception:\n        raise RuntimeError(\"durable webhook receipt rejected\") from None\n    if confirmed is not True:\n        raise RuntimeError(\"durable webhook publish unconfirmed\")\n    return \"accepted\", 202\n"
    },
    {
      "title": "Claim and retry webhook jobs transactionally",
      "language": "python",
      "blurb": "A worker acquires one due job with a database lock, records bounded attempts, and moves exhausted work to a dead-letter state without concurrent double processing.",
      "code": "import re\n\nWORKER_ID = re.compile(r\"wrk_[A-Za-z0-9_-]{8,64}\")\nJOB_ID = re.compile(r\"job_[A-Za-z0-9_-]{8,80}\")\n\ndef claim_webhook_job(connection, worker_id: str):\n    if type(worker_id) is not str or WORKER_ID.fullmatch(worker_id) is None:\n        raise ValueError(\"webhook worker identifier rejected\")\n    with connection.transaction():\n        job = connection.execute(\n            \"select id, attempt from webhook_jobs \"\n            \"where status = 'queued' and available_at <= now() \"\n            \"order by available_at for update skip locked limit 1\"\n        ).fetchone()\n        if job is None:\n            return None\n        if type(job) not in {tuple, list} or len(job) != 2:\n            raise RuntimeError(\"webhook job result rejected\")\n        job_id, attempt = job\n        if type(job_id) is not str or JOB_ID.fullmatch(job_id) is None:\n            raise RuntimeError(\"webhook job identifier rejected\")\n        if type(attempt) is not int or not 0 <= attempt <= 5:\n            raise RuntimeError(\"webhook attempt count rejected\")\n        next_status = \"dead_letter\" if attempt >= 5 else \"processing\"\n        updated = connection.execute(\n            \"update webhook_jobs set status = %s, worker_id = %s, \"\n            \"attempt = attempt + 1 where id = %s\",\n            (next_status, worker_id, job_id),\n        )\n        if type(updated.rowcount) is not int or updated.rowcount != 1:\n            raise RuntimeError(\"webhook job claim rejected\")\n        return job_id, next_status\n"
    }
  ]
};
