window.COURSE_MODULE = {
  "title": "Secret Rotation and Lifecycle Management",
  "graphicAlt": "Boundary map for Secret Rotation and Lifecycle Management, showing Python workload identity, managed secret store, short-lived credential, cache, rotation controller, and audit event; labeled arrows identify secret delivery, use, and revocation paths and the point where unsafe input or behavior is rejected.",
  "narration": "A secret has a lifecycle: creation, distribution, activation, use, expiration, rotation, revocation, retirement, and emergency replacement. Managing that lifecycle is what separates mature secrets management from merely storing a value somewhere. Every important secret should have an owner, a purpose, an environment, a storage location, consumers, rotation expectations, and an incident response path.\n\nRotation changes or replaces a secret according to time, risk, exposure, or operational policy. Rotation must be planned because secrets connect systems together. A database password, signing key, webhook secret, or API credential may be used by multiple services, scheduled jobs, deployment tools, and support processes. Changing it without coordination can cause avoidable outages. Not changing it after exposure can extend compromise.\n\nDual-secret or staged rotation concepts can reduce downtime. For example, a service may temporarily accept both old and new credentials while clients update, or a provider may allow two active keys during a transition. The exact mechanism depends on the system, but the stable principle is to design rotation before an emergency. Service restart and reload behavior should be understood so new secrets take effect predictably.\n\nRevocation and retirement are as important as creation. When a secret is exposed, retired, no longer needed, or associated with a departed vendor, employee, service, or environment, it should be disabled or removed according to risk. Documentation and inventory help teams know what to rotate, who depends on it, and how to recover. Rotation should improve security without surprising the people who keep the application running.",
  "narrationPoints": [
    "A secret has a lifecycle: creation, distribution, activation, use, expiration, rotation, revocation, retirement, and emergency replacement.",
    "Rotation changes or replaces a secret according to time, risk, exposure, or operational policy.",
    "A database password, signing key, webhook secret, or API credential may be used by multiple services, scheduled jobs, deployment tools, and support processes.",
    "Dual-secret or staged rotation concepts can reduce downtime.",
    "Service restart and reload behavior should be understood so new secrets take effect predictably.",
    "Rotation should improve security without surprising the people who keep the application running."
  ]
};
