window.COURSE_MODULE = {
  "title": "What DDoS Mitigation Means",
  "graphicAlt": "Conceptual visual of availability protection across users, edge services, applications, and operations teams.",
  "narration": "A distributed denial-of-service event is an availability problem first. The immediate symptom is that a public service becomes slow, unstable, or unreachable because some part of its path is under pressure. That pressure might be network capacity at the edge, connection or state handling in an infrastructure component, or expensive behavior inside the application itself. In this course we keep those categories defensive and high level. The goal is not to study how hostile traffic is created. The goal is to understand what defenders need to keep real services operating when traffic is abnormal, intense, or intentionally disruptive.\n\nDDoS mitigation is the set of preparation and response capabilities that help a team absorb, filter, redirect, rate limit, cache, or gracefully degrade under that pressure. It is not one product and it is not one checkbox. A CDN may help for web traffic, a WAF may help with application requests, a DNS provider may protect name resolution, an Anycast edge may distribute load, and a scrubbing provider or upstream provider may filter large traffic before it reaches the origin. Those tools matter, but only when the architecture, routing, contacts, telemetry, and runbooks are ready before the incident begins.\n\nThe preparation is often more important than the emergency button. Teams need an inventory of public services, dependencies, owners, provider contracts, emergency contacts, and change procedures. They need baselines that show what normal traffic looks like, dashboards that support fast classification, and escalation paths that do not depend on one person being awake. They also need clear assumptions: which services must remain available, which paths can degrade, and which emergency controls are acceptable for the business.\n\nDuring an event, a good runbook reduces confusion. It gives responders a sequence: confirm the signal, classify the pressure, protect critical paths, engage providers, apply scoped controls, communicate clearly, preserve evidence, and recover carefully. The better the preparation, the less the team has to invent under pressure. DDoS mitigation is availability engineering with security context, operational discipline, and calm communication built in.",
  "narrationPoints": [
    "DDoS mitigation protects availability.",
    "Attacks can overwhelm capacity, state, or application behavior.",
    "Mitigation must be planned before an incident.",
    "Architecture and providers are part of the defense.",
    "A good runbook reduces confusion during pressure."
  ]
};
