window.COURSE_MODULE = {
  "title": "DDoS Categories and Defensive Thinking",
  "graphicAlt": "Conceptual visual comparing volumetric, protocol, and application-layer DDoS pressure at a defensive level.",
  "narration": "Defenders usually describe DDoS events in three broad categories because each category points to different signals, owners, and controls. Volumetric events are about scale against capacity. They attempt to consume available bandwidth, edge throughput, or provider-facing capacity. From a defensive perspective, the important question is whether traffic is saturating the path before it reaches the application. If the pipe, edge, or provider handoff is overwhelmed, local server tuning may not matter. The response usually requires upstream visibility, edge protection, or provider assistance.\n\nProtocol or state exhaustion events target the ability of infrastructure to track and process traffic. The affected component might be a firewall, load balancer, connection table, proxy, or other stateful device. The defensive question is whether connection rates, half-open sessions, table pressure, or device saturation are limiting service. Controls in this category must be careful because they can affect legitimate users, monitoring, partner systems, and recovery paths. The right control is usually scoped, observable, and reversible.\n\nApplication-layer events are different because the traffic may look closer to ordinary web or API use. The pressure appears in expensive routes, login flows, search features, dynamic pages, payment paths, or APIs that require database, cache, or downstream work. The network may not look saturated, but latency, errors, queue depth, CPU, memory, database load, or thread pools can climb. Application-layer defense often needs security, SRE, platform, and application teams together because the best control may be a WAF rule, a cache change, a quota, a circuit breaker, or a temporary degraded mode.\n\nClassification is not about assigning a dramatic label. It is about choosing the right next move. A volumetric event may need provider escalation. A state exhaustion event may need connection and upstream controls. An application-layer event may need route-specific protection and business prioritization. Good defenders avoid overclaiming. They describe what they can observe, state the confidence level, and keep the response focused on availability, recovery, and evidence.",
  "narrationPoints": [
    "Volumetric events target bandwidth or edge capacity.",
    "Protocol events strain connection or state handling.",
    "Application-layer events stress expensive request paths.",
    "Classification helps choose defensive controls.",
    "Defensive thinking focuses on availability and recovery."
  ]
};
