window.COURSE_MODULE = {
  "title": "Application-Layer Resilience",
  "graphicAlt": "Conceptual visual of application resilience with caching, quotas, circuit breakers, and degraded modes.",
  "narration": "Application-layer pressure is difficult because the requests may resemble normal user activity. The problem is not always raw volume. It may be that certain routes are expensive, certain queries miss cache, certain login or search flows trigger heavy downstream work, or certain API patterns create queues that consume worker capacity. From the user's perspective the service is slow or unavailable. From the defender's perspective, the response needs application context as much as security context.\n\nThe first defensive step is to identify expensive endpoints and critical paths before an incident. Which pages must remain available? Which APIs support core business functions? Which routes are safe to cache? Which operations should have quotas? Which features can degrade temporarily? Which requests touch databases, search clusters, identity providers, payment systems, or third-party services? The answers help the team prioritize protection rather than treating every request path as equal.\n\nUseful application-layer controls include caching, request limits, API quotas, queueing, bot controls, WAF rules, authentication hardening, circuit breakers, feature flags, and degraded modes. A cache can reduce repeated origin work. A quota can protect shared resources. A circuit breaker can stop one failing dependency from consuming the whole application. A degraded mode can preserve the most important user journey while less critical features are paused. These are resilience patterns, not magic switches.\n\nCoordination is essential. Security may see suspicious request patterns. SRE may see saturation and error budgets. Application engineers may know which path is expensive and which configuration can safely change. Product or business owners may need to approve a degraded mode. During an event, the strongest control may be code, configuration, edge policy, cache strategy, or a temporary business decision. Afterward, expensive paths should be reviewed and redesigned where possible so the next event is easier to absorb.",
  "narrationPoints": [
    "Application-layer events can resemble normal traffic.",
    "Expensive endpoints need special attention.",
    "Caching and quotas can reduce application load.",
    "Circuit breakers and degraded modes preserve availability.",
    "Security, SRE, and application teams must coordinate."
  ]
};
