window.COURSE_MODULE = {
  "title": "Building a Zero Trust Journey",
  "graphicAlt": "Zero Trust maturity roadmap progressing through visibility, identity, device posture, least privilege, policy integration, monitoring, and improvement.",
  "narration": "Organizations typically implement Zero Trust as a gradual journey rather than a single transformation event. Existing systems, business priorities, workforce needs, technical debt, contracts, and resources all influence the path.\n\nA practical starting point is understanding important resources and access relationships. Teams need inventories of applications, data, identities, devices, dependencies, owners, and current controls before they can improve policy deliberately.\n\nRisk helps set priorities. High-value services, sensitive data, privileged access, remote administration, or environments with weak visibility may offer stronger early benefits than attempting to redesign every system at once.\n\nEarly initiatives can establish reusable capabilities such as stronger identity assurance, better device inventory, clearer access ownership, improved logging, or more consistent policy. Pilots should produce lessons that inform broader adoption.\n\nIntegration matters as the program grows. Identity, device, application, network, data, and monitoring systems need shared context and coordinated lifecycle processes so policy remains consistent across changing environments.\n\nProgress should be measurable. Organizations can track coverage of important resources, strength of authentication, device visibility, excessive privilege, access-review completion, policy exceptions, logging quality, and response to risk changes.\n\nExceptions should be visible and governed. Legacy technology or operational constraints may prevent an ideal control, but the residual risk, compensating safeguards, owner, expiration, and improvement plan should be explicit.\n\nContinuous improvement keeps the journey aligned with reality. Incidents, audit findings, user feedback, technology changes, new business services, and monitoring results should all influence priorities and policy refinement.\n\nThe strongest Zero Trust programs improve security and clarity together. Users understand how to obtain appropriate access, owners understand their responsibilities, and leaders can see where risk is being reduced or accepted.\n\nZero Trust is ultimately a strategy for informed access: verify identity and device context, protect specific resources, apply least privilege, maintain visibility, and adapt decisions as conditions change.",
  "narrationPoints": [
    "Organizations typically implement Zero Trust as a gradual journey rather than a single transformation event.",
    "A practical starting point is understanding important resources and access relationships.",
    "Risk helps set priorities.",
    "Early initiatives can establish reusable capabilities such as stronger identity assurance, better device inventory, clearer access ownership,...",
    "Integration matters as the program grows."
  ]
};
