window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Authorization, Tenant Isolation, and Field Exposure with concrete, reviewable Node.js boundaries.",
  "codeExamples": [
    {
      "title": "Create a read-only tenant-bound document repository",
      "language": "javascript",
      "blurb": "The read-only repository captures tenant context and selects ownership fields for the companion object-authorization check; protected mutations use a separate authorized service.",
      "code": "const IDENTIFIER = /^[A-Za-z0-9](?:[A-Za-z0-9_-]{0,126}[A-Za-z0-9])?$/;\n\nfunction validIdentifier(value) {\n  return typeof value === \"string\" && IDENTIFIER.test(value);\n}\n\nexport function tenantDocumentRepository(Document, tenantId) {\n  const rawFindOneCapability = Document?.findOne;\n  const findOne = typeof rawFindOneCapability === \"function\"\n    ? rawFindOneCapability.bind(Document)\n    : null;\n  if (!findOne || !validIdentifier(tenantId)) {\n    throw new TypeError(\"validated repository configuration required\");\n  }\n  return Object.freeze({\n    find: (id) => {\n      if (!validIdentifier(id)) throw new TypeError(\"document id invalid\");\n      return findOne({ where: { id, tenantId }, attributes: [\"id\", \"ownerId\", \"title\", \"body\"] });\n    }\n  });\n}\n"
    },
    {
      "title": "Check subject ownership above tenant scope",
      "language": "javascript",
      "blurb": "A tenant match narrows the database lookup, then subject ownership or a specific override permission decides access.",
      "code": "function validIdentity(value) {\n  return typeof value === \"string\" && value.length > 0 && value.length <= 256 &&\n    value.trim() === value && !/[\\u0000-\\u001f\\u007f]/.test(value);\n}\n\nfunction validatedPermissions(value) {\n  if (!Array.isArray(value)) {\n    throw new TypeError(\"validated permission array required\");\n  }\n  const length = value.length;\n  if (!Number.isSafeInteger(length) || length > 128) {\n    throw new TypeError(\"validated permission array required\");\n  }\n  const permissions = Array.from({ length }, (_, index) => value[index]);\n  if (new Set(permissions).size !== permissions.length ||\n      permissions.some((permission) => typeof permission !== \"string\" ||\n        !/^[a-z][a-z0-9-]*(?::[a-z][a-z0-9-]*){1,3}$/.test(permission))) {\n    throw new TypeError(\"validated permission array required\");\n  }\n  return new Set(permissions);\n}\n\nexport async function authorizePrivateDocument(repository, documentId, auth) {\n  const subjectId = auth?.subjectId;\n  const permissionValues = auth?.permissions;\n  const rawFindCapability = repository?.find;\n  const find = typeof rawFindCapability === \"function\"\n    ? rawFindCapability.bind(repository)\n    : null;\n  if (!validIdentity(subjectId)) throw new Error(\"unauthenticated\");\n  if (!validIdentity(documentId)) throw new TypeError(\"document id invalid\");\n  if (!find) throw new TypeError(\"document repository required\");\n  const permissions = validatedPermissions(permissionValues);\n  const document = await find(documentId);\n  if (!document) return null;\n  const ownerId = document.ownerId;\n  const id = document.id;\n  const title = document.title;\n  const body = document.body;\n  if (!validIdentity(ownerId) || !validIdentity(id) ||\n      typeof title !== \"string\" || title.length < 1 ||\n      Buffer.byteLength(title, \"utf8\") > 200 ||\n      typeof body !== \"string\" || Buffer.byteLength(body, \"utf8\") > 1024 * 1024) {\n    return null;\n  }\n  const owner = ownerId === subjectId;\n  const override = permissions.has(\"document:read:any\");\n  if (!owner && !override) return null;\n  return Object.freeze({ id, title, body });\n}\n"
    }
  ]
};
