window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Injection Prevention, Raw SQL, and Unsafe Query Boundaries with concrete, reviewable Node.js boundaries.",
  "codeExamples": [
    {
      "title": "Use an ORM parameter API at the raw-query boundary",
      "language": "javascript",
      "blurb": "The SQL text is static and values travel through named replacements; request input never becomes SQL syntax.",
      "code": "export async function rawRecentEvents(orm, tenantId, since) {\n  const rawQuery = orm?.query;\n  const queryTypes = orm?.QueryTypes;\n  const selectType = queryTypes?.SELECT;\n  const sinceMilliseconds = since instanceof Date ? since.getTime() : Number.NaN;\n  if (typeof tenantId !== \"string\" || !/^[A-Za-z0-9_-]{1,128}$/.test(tenantId) ||\n      !Number.isFinite(sinceMilliseconds) || typeof rawQuery !== \"function\" ||\n      selectType === undefined) {\n    throw new TypeError(\"invalid audit query\");\n  }\n  const query = rawQuery.bind(orm);\n  return query(\n    \"SELECT id, action, created_at FROM audit_events WHERE tenant_id = :tenantId AND created_at >= :since ORDER BY created_at DESC LIMIT 100\",\n    { replacements: { tenantId, since: new Date(sinceMilliseconds) }, type: selectType }\n  );\n}\n"
    },
    {
      "title": "Gate unavoidable raw SQL behind a narrow adapter",
      "language": "javascript",
      "blurb": "The adapter exposes one fixed operation, validates the tenant identifier, and parses the database count as a canonical nonnegative integer within an application-owned maximum.",
      "code": "const MAXIMUM_AUDIT_EVENT_COUNT = 1_000_000_000;\n\nfunction validatedAuditCount(value) {\n  let count;\n  if (Number.isSafeInteger(value) && value >= 0) {\n    count = value;\n  } else if (typeof value === \"string\" && /^(?:0|[1-9]\\d*)$/.test(value)) {\n    const parsed = BigInt(value);\n    if (parsed > BigInt(MAXIMUM_AUDIT_EVENT_COUNT)) {\n      throw new RangeError(\"audit count exceeds application maximum\");\n    }\n    count = Number(parsed);\n  } else {\n    throw new TypeError(\"database count invalid\");\n  }\n  if (count > MAXIMUM_AUDIT_EVENT_COUNT) {\n    throw new RangeError(\"audit count exceeds application maximum\");\n  }\n  return count;\n}\n\nexport function createAuditSqlAdapter(database) {\n  const rawExecuteCapability = database?.execute;\n  const execute = typeof rawExecuteCapability === \"function\"\n    ? rawExecuteCapability.bind(database)\n    : null;\n  if (!execute) throw new TypeError(\"database adapter required\");\n  return Object.freeze({\n    countByTenant: async (tenantId) => {\n      if (typeof tenantId !== \"string\" || !/^[a-f0-9-]{16,64}$/i.test(tenantId)) {\n        throw new TypeError(\"invalid tenant id\");\n      }\n      const result = await execute(\n        \"SELECT COUNT(*) AS count FROM audit_events WHERE tenant_id = ?\", [tenantId]);\n      if (!Array.isArray(result)) throw new TypeError(\"database count row invalid\");\n      const rowCount = result.length;\n      const row = rowCount === 1 ? result[0] : null;\n      if (!Number.isSafeInteger(rowCount) || rowCount !== 1 ||\n          !row || typeof row !== \"object\" || Array.isArray(row) ||\n          ![Object.prototype, null].includes(Object.getPrototypeOf(row))) {\n        throw new TypeError(\"database count row invalid\");\n      }\n      const descriptors = Object.getOwnPropertyDescriptors(row);\n      const keys = Reflect.ownKeys(descriptors);\n      if (keys.length !== 1 || keys[0] !== \"count\" ||\n          !descriptors.count.enumerable || !(\"value\" in descriptors.count)) {\n        throw new TypeError(\"database count row invalid\");\n      }\n      const count = descriptors.count.value;\n      return validatedAuditCount(count);\n    }\n  });\n}\n"
    }
  ]
};
