window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Mass Assignment, Safe Mutations, and Transaction Integrity with concrete, reviewable Node.js boundaries.",
  "codeExamples": [
    {
      "title": "Map a safe ORM profile mutation",
      "language": "javascript",
      "blurb": "The mutation DTO rejects extra properties and prevents tenant, role, ownership, and balance fields from reaching the model update.",
      "code": "function validatedDisplayName(value) {\n  if (typeof value !== \"string\" || value.length < 1 || value.trim() !== value ||\n      value !== value.normalize(\"NFC\") || Buffer.byteLength(value, \"utf8\") > 100 ||\n      /[\\u0000-\\u001f\\u007f]/.test(value)) {\n    throw new TypeError(\"display name invalid\");\n  }\n  return value;\n}\n\nexport function profileChanges(input) {\n  const allowed = new Set([\"displayName\", \"locale\"]);\n  if (!input || typeof input !== \"object\" || Array.isArray(input) ||\n      ![Object.prototype, null].includes(Object.getPrototypeOf(input))) {\n    throw new TypeError(\"profile field rejected\");\n  }\n  const descriptors = Object.getOwnPropertyDescriptors(input);\n  const keys = Reflect.ownKeys(descriptors);\n  if (keys.length < 1 || keys.length > allowed.size || keys.some((key) =>\n      typeof key !== \"string\" || !allowed.has(key) ||\n      !descriptors[key].enumerable || !(\"value\" in descriptors[key]))) {\n    throw new TypeError(\"profile field rejected\");\n  }\n  const hasDisplayName = Object.hasOwn(descriptors, \"displayName\");\n  const hasLocale = Object.hasOwn(descriptors, \"locale\");\n  const displayName = hasDisplayName ? descriptors.displayName.value : undefined;\n  const locale = hasLocale ? descriptors.locale.value : undefined;\n  const changes = {};\n  if (hasDisplayName) changes.displayName = validatedDisplayName(displayName);\n  if (hasLocale) {\n    if (![\"en\", \"es\", \"fr\"].includes(locale)) throw new TypeError(\"locale invalid\");\n    changes.locale = locale;\n  }\n  if (!Object.keys(changes).length) throw new TypeError(\"empty profile change\");\n  return Object.freeze(changes);\n}\n"
    },
    {
      "title": "Keep a transfer in an ORM transaction",
      "language": "javascript",
      "blurb": "Validated tenant and wallet IDs are locked in deterministic order, then mapped back to debit and credit roles inside one transaction.",
      "code": "export async function transferBalance(orm, tenantId, fromId, toId, cents) {\n  const idPattern = /^[A-Za-z0-9_-]{1,64}$/;\n  const validId = (value) => typeof value === \"string\" && idPattern.test(value);\n  const transactionMethod = orm?.transaction;\n  if (!validId(tenantId) || !validId(fromId) || !validId(toId) || fromId === toId ||\n      typeof transactionMethod !== \"function\") {\n    throw new TypeError(\"distinct tenant wallet ids and ORM transaction required\");\n  }\n  if (!Number.isSafeInteger(cents) || cents < 1) throw new RangeError(\"invalid transfer\");\n  const transaction = transactionMethod.bind(orm);\n  return transaction(async (tx) => {\n    const wallet = tx?.Wallet;\n    const lockUpdate = tx?.LOCK?.UPDATE;\n    const findMethod = wallet?.findOne;\n    if (typeof findMethod !== \"function\" || lockUpdate === undefined) {\n      throw new TypeError(\"wallet transaction contract invalid\");\n    }\n    const findWallet = findMethod.bind(wallet);\n    const [firstId, secondId] = [fromId, toId].sort();\n    const first = await findWallet({ where: { id: firstId, tenantId }, lock: lockUpdate });\n    const second = await findWallet({ where: { id: secondId, tenantId }, lock: lockUpdate });\n    const from = firstId === fromId ? first : second;\n    const to = firstId === fromId ? second : first;\n    const fromBalance = from?.balanceCents;\n    const toBalance = to?.balanceCents;\n    const debitMethod = from?.update;\n    const creditMethod = to?.update;\n    if (!Number.isSafeInteger(fromBalance) || !Number.isSafeInteger(toBalance) ||\n        fromBalance < cents || typeof debitMethod !== \"function\" ||\n        typeof creditMethod !== \"function\") {\n      throw new Error(\"transfer rejected\");\n    }\n    const destinationBalance = toBalance + cents;\n    if (!Number.isSafeInteger(destinationBalance)) throw new RangeError(\"destination balance overflow\");\n    const debit = debitMethod.bind(from);\n    const credit = creditMethod.bind(to);\n    await debit({ balanceCents: fromBalance - cents }, { transaction: tx });\n    await credit({ balanceCents: destinationBalance }, { transaction: tx });\n    return Object.freeze({ transferred: cents });\n  });\n}\n"
    }
  ]
};
