window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Redirects, Proxies, and Cross-Boundary Behavior through concrete, reviewable Python controls.",
  "codeExamples": [
    {
      "title": "Revalidate every redirect authority",
      "language": "python",
      "blurb": "Each redirect hop rejects raw and Unicode control/separator characters, credentials, alternate ports, fragments, and unapproved hosts before another request is sent.",
      "code": "import unicodedata\nfrom urllib.parse import urljoin, urlsplit\n\nAPPROVED_API_HOSTS = {\"api.example.com\", \"api-backup.example.com\"}\n\ndef has_disallowed_url_character(value: str) -> bool:\n    for character in value:\n        category = unicodedata.category(character)\n        if category in {\"Cc\", \"Cf\", \"Zl\", \"Zp\"}:\n            return True\n    return False\n\ndef approved_redirect_target(url: object):\n    if not isinstance(url, str) or not 1 <= len(url) <= 2048 or has_disallowed_url_character(url):\n        raise ValueError(\"redirect destination rejected\")\n    target = urlsplit(url)\n    try:\n        port = target.port\n    except ValueError:\n        raise ValueError(\"invalid redirect authority\") from None\n    if (\n        target.scheme != \"https\" or target.hostname not in APPROVED_API_HOSTS\n        or target.username is not None or target.password is not None\n        or port not in {None, 443} or target.fragment\n    ):\n        raise ValueError(\"redirect destination rejected\")\n    return target\n\ndef close_quietly(response) -> None:\n    try:\n        response.close()\n    except Exception:\n        pass\n\ndef get_approved_redirects(session, url: str):\n    for _ in range(4):\n        approved_redirect_target(url)\n        response = None\n        is_redirect = False\n        try:\n            response = session.get(url, allow_redirects=False, timeout=(3, 8))\n        except Exception:\n            raise RuntimeError(\"redirect request failed\") from None\n        try:\n            try:\n                is_redirect = bool(response.is_redirect)\n            except Exception:\n                raise ValueError(\"redirect response rejected\") from None\n            if not is_redirect:\n                return response\n            try:\n                location = response.headers[\"Location\"]\n            except Exception:\n                raise ValueError(\"redirect location rejected\") from None\n            if not isinstance(location, str) or not 1 <= len(location) <= 2048 or has_disallowed_url_character(location):\n                raise ValueError(\"redirect location rejected\")\n            try:\n                url = urljoin(url, location)\n            except Exception:\n                raise ValueError(\"redirect location rejected\") from None\n        finally:\n            if is_redirect and response is not None:\n                close_quietly(response)\n    raise RuntimeError(\"redirect limit exceeded\")\n"
    },
    {
      "title": "Disable ambient proxy inheritance for a direct API client",
      "language": "python",
      "blurb": "The session ignores process proxy variables and accepts no caller-selected proxy, keeping the production route under application policy.",
      "code": "import requests\n\nclass DirectAPIError(RuntimeError):\n    pass\n\ndef direct_api_session() -> requests.Session:\n    session = requests.Session()\n    session.trust_env = False\n    session.proxies.clear()\n    session.headers.update({\"Accept\": \"application/json\", \"User-Agent\": \"orders-service/1\"})\n    return session\n\ndef fetch_direct(session: requests.Session, path: str):\n    approved_paths = {\"health\": \"/v1/health\", \"status\": \"/v1/status\"}\n    if not isinstance(path, str) or path not in approved_paths:\n        raise ValueError(\"API operation rejected\")\n    try:\n        return session.get(\n            \"https://api.example.com\" + approved_paths[path],\n            allow_redirects=False,\n            timeout=(2, 5),\n            proxies={\"http\": None, \"https\": None},\n        )\n    except Exception:\n        raise DirectAPIError(\"direct API request failed\") from None\n"
    }
  ]
};
