window.COURSE_MODULE = {
  "title": "Outbound Trust Boundaries and Destination Control",
  "graphicAlt": "Caller input stops at a destination-policy gate while application-owned host, port, path, and DNS rules select one approved external API beyond the network boundary.",
  "narration": "Every outbound HTTP request crosses a trust boundary. The Python application chooses a destination, resolves a name, opens a connection, sends headers and data, and accepts a response from another system. That destination may be a configured internal service, a partner API, an identity provider, a storage endpoint, or a user-selected callback. The security question is who can influence the destination and whether the application is allowed to reach it.\n\nUntrusted input should not freely choose network destinations. User-supplied URLs, callback addresses, file fetch targets, webhook destinations, or database-stored endpoint fields may appear legitimate while still sending the server toward an unintended public, private, or sensitive location. A safer pattern is to map user choices to approved destination records, allowlisted hosts, expected schemes, known ports, and reviewed service configuration.\n\nDestination checks need to account for name resolution, redirects, proxies, and environment behavior at a high level. A host name may resolve differently over time. A proxy may change the route. A redirect may move the request to a different host or scheme. Private and public address spaces may carry different risk. The application should define what is allowed before a request starts and verify that automatic behavior does not silently cross boundaries.\n\nOutbound request control reduces accidental exposure of internal services and credentials. It also improves observability. When a Python service is expected to contact only known systems, logs and alerts can identify unusual destinations more easily. Destination control is not about disabling integration. It is about making integration explicit, reviewable, and aligned with the business purpose of the feature.",
  "narrationPoints": [
    "The security question is who can influence the destination and whether the application is allowed to reach it.",
    "A safer pattern is to map user choices to approved destination records, allowlisted hosts, expected schemes, known ports, and reviewed service configuration.",
    "Destination checks need to account for name resolution, redirects, proxies, and environment behavior at a high level.",
    "Outbound request control reduces accidental exposure of internal services and credentials.",
    "A redirect may move the request to a different host or scheme.",
    "The application should define what is allowed before a request starts and verify that automatic behavior does not silently cross boundaries."
  ]
};
