window.COURSE_MODULE = {
  "title": "TLS, Certificates, and Transport Validation",
  "graphicAlt": "A configured SSL context is visibly attached to the HTTP transport; the CA chain and hostname check lead to the approved API while an unused context beside a request is marked ineffective.",
  "narration": "HTTPS and TLS help protect HTTP traffic in transit when configured correctly. For Python HTTP clients, transport protection can help prevent certain forms of interception or tampering between the application and the remote endpoint. But encryption is only one part of the story. The client also needs to verify that it is communicating with the expected trusted endpoint rather than simply encrypting traffic to whoever answered.\n\nCertificate validation and hostname validation provide that identity check. The client should verify that the server certificate chains to an appropriate trusted authority and matches the expected service identity. Disabling verification may make a broken integration appear to work, but it removes a core trust decision. In production, disabled verification can create false confidence: traffic may be encrypted, while endpoint identity is no longer trustworthy.\n\nLocal development and production settings should be separated clearly. A developer may use test endpoints, local certificates, or temporary trust configuration. Those exceptions should not travel into production settings or shared application helpers. Sensitive production calls should have explicit transport expectations that are easy to review. If an integration handles credentials, personal data, administrative actions, or business-critical workflows, TLS configuration should not be left to vague assumptions.\n\nCertificate errors and rotation should be planned. A certificate validation failure should not cause the client to fall back to insecure behavior or to expose internal details to users. Normal certificate rotation should be supported through appropriate trust management and deployment coordination. Strong transport validation means encryption, endpoint identity validation, safe error handling, and operational readiness when certificates change.",
  "narrationPoints": [
    "HTTPS and TLS help protect HTTP traffic in transit when configured correctly.",
    "Disabling verification may make a broken integration appear to work, but it removes a core trust decision.",
    "Sensitive production calls should have explicit transport expectations that are easy to review.",
    "Strong transport validation means encryption, endpoint identity validation, safe error handling, and operational readiness when certificates change.",
    "In production, disabled verification can create false confidence: traffic may be encrypted, while endpoint identity is no longer trustworthy.",
    "Normal certificate rotation should be supported through appropriate trust management and deployment coordination."
  ]
};
