window.COURSE_MODULE = {
  "title": "Resilience, Logging, Testing, and Monitoring",
  "graphicAlt": "A retry timeline shows bounded GET attempts with backoff and a total deadline, while POST replay, unlimited response capture, raw URLs, and credential-bearing logs take rejection branches.",
  "narration": "HTTP client resilience begins with timeouts. Connection timeouts prevent a client from waiting indefinitely to establish a connection. Read timeouts prevent a client from hanging while a remote service stalls. Retries can help with transient failures, but they need limits, backoff, and an understanding of idempotency. A retry that repeats a state-changing operation can create duplicate work, incorrect charges, repeated notifications, or inconsistent records.\n\nSafe logging should make outbound behavior observable without leaking sensitive data. Logs can include dependency name, operation name, status category, duration, timeout status, retry count, correlation ID, and safe error category. They should avoid tokens, credentials, authorization headers, full sensitive URLs, private payloads, unnecessary response bodies, and raw downstream error content. Redaction should apply consistently to logs, traces, alerts, and support bundles.\n\nTesting should cover more than happy paths. Good tests exercise destination validation, TLS failure handling at a high level, redirect policy, proxy assumptions where relevant, timeouts, unavailable services, malformed responses, oversized responses, unexpected content types, authentication failures, safe parsing, and logging redaction. Controlled test doubles or fake endpoints can make these behaviors reliable to verify without depending on fragile external systems.\n\nMonitoring should surface unusual destinations, authentication failures, error spikes, latency changes, retry storms, certificate errors, redirect anomalies, and unexpected response sizes. If credentials, requests, or responses are exposed, incident response should assess what leaked, rotate or revoke secrets when appropriate, contain affected integrations, review logs, fix the client behavior, and add regression tests. HTTP client security has to remain observable without becoming noisy or leaky.",
  "narrationPoints": [
    "Retries can help with transient failures, but they need limits, backoff, and an understanding of idempotency.",
    "Logs can include dependency name, operation name, status category, duration, timeout status, retry count, correlation ID, and safe error category.",
    "Controlled test doubles or fake endpoints can make these behaviors reliable to verify without depending on fragile external systems.",
    "HTTP client security has to remain observable without becoming noisy or leaky.",
    "A retry that repeats a state-changing operation can create duplicate work, incorrect charges, repeated notifications, or inconsistent records.",
    "Connection timeouts prevent a client from waiting indefinitely to establish a connection."
  ]
};
