window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Environment Separation and Deployment Profiles' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Bind one deployment profile to the actual host environment",
      "language": "csharp",
      "blurb": "The immutable profile snapshots host and configuration values once, requires their environment names to match exactly, admits a closed tier and region set, and prevents detailed errors from being enabled in production.",
      "code": "using Microsoft.Extensions.Configuration;\nusing Microsoft.Extensions.Hosting;\n\npublic enum DeploymentTier\n{\n    Development,\n    Staging,\n    Production\n}\n\npublic sealed class DeploymentProfile\n{\n    private DeploymentProfile(DeploymentTier tier, string region, bool detailedErrors)\n    {\n        Tier = tier;\n        Region = region;\n        DetailedErrors = detailedErrors;\n    }\n\n    public DeploymentTier Tier { get; }\n    public string Region { get; }\n    public bool DetailedErrors { get; }\n\n    public static DeploymentProfile Load(\n        IConfiguration configuration,\n        IHostEnvironment environment)\n    {\n        ArgumentNullException.ThrowIfNull(configuration);\n        ArgumentNullException.ThrowIfNull(environment);\n        var hostName = environment.EnvironmentName;\n        var configuredName = configuration[\"Deployment:Environment\"];\n        var region = configuration[\"Deployment:Region\"];\n        var detailedText = configuration[\"Deployment:DetailedErrors\"];\n        if (!string.Equals(hostName, configuredName, StringComparison.Ordinal))\n            throw new InvalidOperationException(\"Deployment environment mismatch.\");\n\n        var tier = hostName switch\n        {\n            \"Development\" => DeploymentTier.Development,\n            \"Staging\" => DeploymentTier.Staging,\n            \"Production\" => DeploymentTier.Production,\n            _ => throw new InvalidOperationException(\"Deployment environment rejected.\")\n        };\n        if (region is not (\"us-east-1\" or \"us-west-2\" or \"eu-west-1\") ||\n            detailedText is not (\"true\" or \"false\"))\n        {\n            throw new InvalidOperationException(\"Deployment profile rejected.\");\n        }\n        var detailedErrors = detailedText == \"true\";\n        if (tier == DeploymentTier.Production && detailedErrors)\n            throw new InvalidOperationException(\"Detailed production errors are disabled.\");\n        return new DeploymentProfile(tier, region, detailedErrors);\n    }\n}\n"
    },
    {
      "title": "Accept an exact deployment environment-variable schema",
      "language": "csharp",
      "blurb": "The parser requires exactly three application-owned names with ordinal spelling, validates canonical values and a positive configuration version, rejects unknown variables instead of copying the ambient environment, and returns immutable primitive state.",
      "code": "using System.Globalization;\n\npublic sealed class DeploymentEnvironmentInput\n{\n    private DeploymentEnvironmentInput(string environment, string region, int configurationVersion)\n    {\n        Environment = environment;\n        Region = region;\n        ConfigurationVersion = configurationVersion;\n    }\n\n    public string Environment { get; }\n    public string Region { get; }\n    public int ConfigurationVersion { get; }\n\n    public static DeploymentEnvironmentInput Parse(\n        IReadOnlyDictionary<string, string?> variables)\n    {\n        ArgumentNullException.ThrowIfNull(variables);\n        var allowed = new HashSet<string>(StringComparer.Ordinal)\n        {\n            \"DOTNET_ENVIRONMENT\", \"ORDERS_REGION\", \"ORDERS_CONFIG_VERSION\"\n        };\n        if (variables.Count != allowed.Count || variables.Keys.Any(key => !allowed.Contains(key)))\n            throw new ArgumentException(\"Deployment variable schema rejected.\", nameof(variables));\n\n        var environment = variables[\"DOTNET_ENVIRONMENT\"];\n        var region = variables[\"ORDERS_REGION\"];\n        var versionText = variables[\"ORDERS_CONFIG_VERSION\"];\n        if (environment is not (\"Development\" or \"Staging\" or \"Production\") ||\n            region is not (\"us-east-1\" or \"us-west-2\" or \"eu-west-1\") ||\n            !int.TryParse(versionText, NumberStyles.None, CultureInfo.InvariantCulture, out var version) ||\n            version is < 1 or > 1_000_000 ||\n            !string.Equals(versionText, version.ToString(CultureInfo.InvariantCulture), StringComparison.Ordinal))\n        {\n            throw new ArgumentException(\"Deployment variable value rejected.\", nameof(variables));\n        }\n        return new DeploymentEnvironmentInput(environment, region, version);\n    }\n}\n"
    }
  ]
};
