window.COURSE_MODULE = {
  "title": "Concurrency Exists Wherever Operations Interleave",
  "graphicAlt": "Two request timelines show Request B running while Request A waits at await. API, worker, and admin writers converge on one database where the shared invariant must be enforced.",
  "narration": "Ordinary JavaScript running on one Node.js event loop executes synchronous sections sequentially. That does not make an HTTP request, asynchronous function, or business operation indivisible. An Express service can have many requests waiting for database results while timers, callbacks, and message handlers continue making progress.\n\nAn await boundary suspends one continuation; it does not reserve the state that continuation previously observed. Another request can change an account between loading its balance and attempting a debit. Await is not inherently unsafe. The defect is the assumption that a condition remains true while separate operations act on shared state.\n\nConcurrency also crosses runtime boundaries. Other Node.js processes, containers, serverless invocations, queue consumers, administrative tools, and external services can modify the same records. Worker threads can execute JavaScript in parallel and may share memory explicitly. Asynchronous interleaving does not require simultaneous CPU execution, while parallel execution adds another way for operations to overlap.\n\nBegin with an invariant: a condition that every permitted state transition must preserve. Inventory must not become negative. A coupon may have only one successful redemption. An approval may leave the pending state only once. A withdrawal must satisfy its balance constraint, and an edit must not silently erase another writer's change. Naming the invariant makes the correctness requirement more precise than simply requesting a lock.\n\nThen locate the authoritative state and enumerate its writers. Lost updates, duplicate execution, oversubscription, stale decisions, and conflicting transitions are different failures that require different controls. TypeScript can model states and results, but types do not coordinate runtime operations. Promise.all can observe concurrently started work; it does not turn that work into an atomic operation. If correctness depends on a condition remaining true while shared state changes, the check and protected transition must meet at the layer that owns that state.",
  "narrationPoints": [
    "Sequential event-loop execution does not serialize whole requests.",
    "Await permits interleaving; shared-state assumptions create the race.",
    "Define the invariant and identify every writer.",
    "Coordinate where the authoritative state is owned."
  ]
};
