window.COURSE_MODULE = {
  "title": "Use Transactions and Locking When Operations Span Multiple Steps",
  "graphicAlt": "Reserving stock and recording its reservation share one transaction: both commit or both remain unchanged after rollback. Correct isolation, short locks, and bounded retries matter; external email is outside rollback.",
  "narration": "Some invariants span multiple writes. Reserving inventory and recording its reservation may need to succeed or fail together. A database transaction groups participating changes so a successful commit makes the unit durable, while rollback discards those uncommitted changes. Every participating statement must actually use the same transaction context.\n\nAtomicity does not mean that all transactions run one at a time. Isolation determines which concurrent effects a transaction can observe and which conflicts the database prevents or rejects. Placing ordinary reads and writes inside a transaction does not automatically protect every business predicate. Two transactions may make incompatible decisions from snapshots, including decisions involving different rows. Verify the database's isolation guarantees and the actual queries used.\n\nPessimistic locking can protect a known resource before evaluating and modifying it. Conflicting writers then wait or fail according to the database's behavior. Lock the resource whose state determines the decision, and hold protection until commit or rollback. A row lock does not automatically protect missing rows, arbitrary ranges, related tables, or an external service. Broader predicates may require constraints, another coordination record, or serializable isolation.\n\nLocks introduce contention and deadlocks. Acquire required locks in a consistent order where possible, keep transactions focused, and set sensible deadlines. Avoid slow external network calls while locks are held. A rollback in the database cannot undo a payment or email already accepted by another system; those boundaries need a separate reliable workflow.\n\nSome databases reject conflicting serializable transactions or choose a deadlock victim. Handle documented retryable failures by rerunning the complete transaction from fresh reads, with bounded attempts and backoff. Ensure repeated transaction execution cannot duplicate effects outside that transaction. A process-local mutex is not a substitute for these guarantees when other service instances can write the same data. Correctness comes from the selected database semantics and all participating writers, not the presence of a transaction function call.",
  "narrationPoints": [
    "Group related changes in the same transaction context.",
    "Isolation and query structure determine concurrency guarantees.",
    "Lock the exact state or predicate that needs protection.",
    "Keep transactions short and retry documented conflicts safely."
  ]
};
