window.COURSE_MODULE = {
  "title": "Make Retries and Duplicate Requests Idempotent",
  "graphicAlt": "Repeated requests for Operation A converge on one atomic claim, business effect, and stored result inside one database transaction. Repeats retrieve the saved result; a different payload conflicts. External effects require their own idempotency contract.",
  "narration": "A timeout does not reveal whether an operation committed. The server may have completed an order or credit before its response was lost. Clients, proxies, queue systems, and workers can retry; users can submit twice. Treat duplicate attempts as normal input to the design.\n\nIdempotency recognizes repeated attempts at the same logical operation and reuses its established result or state. Use a stable operation identifier across retries. Scope the identifier to the authenticated caller or tenant and operation type, and bind it to the request's meaning. Reject reuse with incompatible input rather than returning an unrelated result. Define retention, because forgetting a key can permit a later duplicate.\n\nThe idempotency mechanism must itself withstand concurrency. Two replicas cannot both check an in-memory map and then execute. Use an authoritative unique constraint or transactional claim so only one operation wins. Define how concurrent callers observe in-progress work and how completed callers receive the prior outcome. A unique key alone does not resolve crashes between a claim and an unrecorded side effect.\n\nFor effects entirely within one database, commit the deduplication record, business mutation, and reusable result in the same transaction. A queue consumer can record a message identifier together with its business change, then acknowledge after commit. Redelivery finds the recorded result instead of applying the change again.\n\nExternal effects require another boundary. A local transaction cannot atomically commit a remote charge. Use the remote provider's supported idempotency contract with the same stable operation identity, or a durable workflow with reconciliation. A transactional outbox records the intent alongside local changes; delivery can still repeat, so the destination needs duplicate protection too.\n\nIdempotency does not mean ignoring every duplicate, nor does it mean mutual exclusion. A lock separates overlapping attempts while held; it does not identify a retry arriving after release. Protect the logical outcome across concurrent attempts, crashes, and ambiguous responses, and test each recovery path.",
  "narrationPoints": [
    "Reuse one logical operation identity across retries.",
    "Atomically coordinate the claim, local effect, and result.",
    "Define in-progress, conflicting-input, and retention behavior.",
    "External effects need their own idempotency or recovery contract."
  ]
};
