window.COURSE_MODULE = {
  "title": "Choosing Safer Serialization Formats",
  "graphicAlt": "Layered architecture diagram for Choosing Safer Serialization Formats, showing untrusted bytes, bounded parser, schema validator, typed data, and rejected object-construction path; labeled arrows identify parse, validation, and trust transitions and the point where unsafe input or behavior is rejected.",
  "narration": "Format selection is a security decision because formats make different behavior easy. JSON is widely used for APIs and interoperable data exchange. YAML is often used for human-readable configuration. XML appears in document-oriented systems and integrations. CSV is common for tabular exchange. Binary and schema-based formats can support compact messages and strong contracts. Object serialization formats can preserve Python-specific structures, but they are usually a poor fit for untrusted input.\n\nSafer design often favors simple data formats over automatic object reconstruction. A plain data format encourages the application to parse values, validate a schema, and explicitly decide how those values map into program behavior. Object serialization can blur that boundary by combining input data with class loading, object construction, and hidden behavior. That may be acceptable for controlled internal persistence, but it should not be the default for external data.\n\nEvery format has tradeoffs. Readability helps humans review configuration. Interoperability helps different systems exchange data. Strictness reduces ambiguity. Performance matters for large systems. Schema support improves validation. Security depends on safe parser settings, bounded input, minimal features, and explicit expectations. There is no universally perfect format; the right choice depends on source trust, use case, and operational constraints.\n\nWhen in doubt, choose the least powerful format that meets the need. If the application only needs records or configuration values, do not choose a format that reconstructs application objects. If the application only needs a narrow set of fields, reject broad dynamic structures. Format choice should make the safe path easy: parse ordinary data, validate it, normalize it, authorize its use, and handle errors predictably.",
  "narrationPoints": [
    "Format selection is a security decision because formats make different behavior easy.",
    "Safer design often favors simple data formats over automatic object reconstruction.",
    "There is no universally perfect format; the right choice depends on source trust, use case, and operational constraints.",
    "Format choice should make the safe path easy: parse ordinary data, validate it, normalize it, authorize its use, and handle errors predictably.",
    "Every format has tradeoffs.",
    "Schema support improves validation."
  ]
};
