window.COURSE_MODULE = {
  "title": "Storage, Logging, Privacy, and Testing",
  "graphicAlt": "Operational lifecycle diagram for Storage, Logging, Privacy, and Testing, showing untrusted bytes, bounded parser, schema validator, typed data, and rejected object-construction path; labeled arrows identify parse, validation, and trust transitions and the point where unsafe input or behavior is rejected.",
  "narration": "Serialized data often lives longer and travels farther than developers expect. It may be stored in files, databases, caches, queues, object storage, logs, backups, artifacts, and support bundles. Before serializing, ask whether each field is needed. Data minimization reduces exposure by avoiding unnecessary secrets, tokens, credentials, personal data, regulated data, and business confidential data.\n\nPrivacy-aware logging is especially important. Logs are searchable, copied, retained, and sometimes accessible to more people than production databases. Safe audit events should capture meaningful security and operational activity without dumping entire serialized payloads. When errors occur, messages should identify the validation problem without exposing sensitive content or parser internals to users.\n\nRetention and deletion rules should include serialized copies. A sensitive field removed from the primary database may still exist in queues, caches, logs, backups, analytics exports, and debugging artifacts. Safe serialization design includes where data is stored, how long it remains, who can read it, whether it is encrypted or access-controlled, and how deletion or expiration is handled.\n\nTesting and review make serialization controls durable. Useful tests include malformed input, oversized input, unknown fields, wrong types, stale versions, rejected advanced features, privacy checks, and deserialization regression tests. Code review should ask where the data came from, what parser settings are used, what schema is enforced, what is logged, and whether object reconstruction is truly necessary.",
  "narrationPoints": [
    "Serialized data often lives longer and travels farther than developers expect.",
    "Data minimization reduces exposure by avoiding unnecessary secrets, tokens, credentials, personal data, regulated data, and business confidential data.",
    "Safe audit events should capture meaningful security and operational activity without dumping entire serialized payloads.",
    "Retention and deletion rules should include serialized copies.",
    "Useful tests include malformed input, oversized input, unknown fields, wrong types, stale versions, rejected advanced features, privacy checks, and deserialization regression tests.",
    "Testing and review make serialization controls durable."
  ]
};
