window.COURSE_MODULE = {
  "title": "Why Secure Randomness Matters",
  "graphicAlt": "Security diagram for Secure Random Numbers in Node.js, Why Secure Randomness Matters, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "A Node.js application rarely begins with randomness as a formal security topic. It starts with simple identifiers, a reset link, a temporary invite code, or a quick session token. Then the system grows. It adds API keys, OAuth state values, CSRF tokens, signed webhooks, encrypted fields, unique filenames, distributed workers, and services that need to coordinate without exposing secrets. Suddenly random values are no longer small implementation details. They are part of the trust model.\n\nRandom values become security controls when an attacker must not be able to predict them, guess them, reuse them, or influence them. A strong authentication flow can be undermined by weak session IDs. A good account recovery design can fail if reset tokens are short or predictable. Encryption can be damaged by nonce or IV reuse. Authorization can be weakened when private links are treated as proof of access rather than one part of a larger control.\n\nPurpose matters. A randomized UI animation, a shuffled test fixture, a public correlation ID, and a password reset token do not need the same kind of randomness. Some values only need uniqueness. Some need unpredictability. Some must never repeat for a given key. Some are public by design, while others are bearer secrets that grant access to an action or account. Treating them all as the same category leads to brittle systems.\n\nThis course is about defensive engineering choices. The goal is to choose random-generation patterns that are unpredictable where secrecy is required, correctly sized for the threat model, encoded safely for the transport path, and handled carefully after generation. Secure randomness is not solved by using a random function. It requires the right API, enough entropy, purpose-specific design, lifecycle controls, logging discipline, testing, and review.",
  "narrationPoints": [
    "It adds API keys, OAuth state values, CSRF tokens, signed webhooks, encrypted fields, unique filenames, distributed workers, and services that need to coordinate without exposing secrets.",
    "Random values become security controls when an attacker must not be able to predict them, guess them, reuse them, or influence them.",
    "A randomized UI animation, a shuffled test fixture, a public correlation ID, and a password reset token do not need the same kind of randomness.",
    "Secure randomness is not solved by using a random function.",
    "Encryption can be damaged by nonce or IV reuse.",
    "A good account recovery design can fail if reset tokens are short or predictable."
  ]
};
