window.COURSE_MODULE = {
  "title": "Performance, Testing, Logging, and Code Review",
  "graphicAlt": "Security diagram for Secure Random Numbers in Node.js, Performance, Testing, Logging, and Code Review, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "Cryptographic random generation has operational behavior, especially in high-throughput services. Small token generations are usually routine, but large randomBytes requests or repeated synchronous calls inside hot request paths should be reviewed. Startup tasks, key generation workflows, request handlers, background jobs, and serverless functions may have different performance and reliability needs. The goal is to use secure randomness deliberately, not to avoid it.\n\nTesting can accidentally weaken production. Tests often need predictable behavior, but production security-sensitive randomness should not be replaced with predictable randomness for convenience. If testability is needed, inject a safe seam that cannot be enabled accidentally in production. Tests should verify length, encoding, expiration behavior, uniqueness expectations, storage behavior, and redaction without depending on a fixed production token.\n\nLogging deserves special attention because logs are long lived, searchable, copied into support tools, and often visible to more people than application databases. Logs should not expose generated secrets, session IDs, reset tokens, API keys, OAuth state values, CSRF tokens, private URLs, cookies, authorization headers, or cryptographic keys. Redaction should be deliberate, tested, and applied before values reach centralized logging, traces, error reports, or analytics events.\n\nA practical review checklist asks what random API is used, why it matches the purpose, how much entropy is generated, how the value is encoded, where it is stored, whether it expires, whether it can be revoked, and whether logs expose it. Monitoring should detect repeated verification failures, reset-token abuse, invite-code guessing, unusual API key failures, and high error rates. Incident response should include revocation, rotation, log review, and proof that exposed values no longer work.",
  "narrationPoints": [
    "Startup tasks, key generation workflows, request handlers, background jobs, and serverless functions may have different performance and reliability needs.",
    "Tests should verify length, encoding, expiration behavior, uniqueness expectations, storage behavior, and redaction without depending on a fixed production token.",
    "Logs should not expose generated secrets, session IDs, reset tokens, API keys, OAuth state values, CSRF tokens, private URLs, cookies, authorization headers, or cryptographic keys.",
    "Monitoring should detect repeated verification failures, reset-token abuse, invite-code guessing, unusual API key failures, and high error rates.",
    "Incident response should include revocation, rotation, log review, and proof that exposed values no longer work.",
    "Redaction should be deliberate, tested, and applied before values reach centralized logging, traces, error reports, or analytics events."
  ]
};
