window.COURSE_MODULE = {
  "title": "Course Summary and Practical Checklist",
  "graphicAlt": "Security diagram for Secure Random Numbers in Node.js, Course Summary and Practical Checklist, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "Start with the purpose of the random value. Is the application creating a bearer secret, a public identifier, a salt, a nonce, an IV, a key, a bounded integer, or a human-entered code? The right API and lifecycle depend on that answer. Secure random values should be unpredictable when secrecy matters, unique when uniqueness matters, correctly sized, correctly encoded, and handled according to their role.\n\nUse cryptographically secure APIs for security-sensitive values. crypto.randomBytes fits raw secret bytes, tokens, salts, and keys. crypto.randomInt fits bounded secure integers. crypto.randomUUID fits UUID-shaped identifier use cases. Web Crypto APIs may fit standards-aligned or cross-platform work. Do not use Math.random for secrets, tokens, reset links, CSRF values, OAuth state, nonces, salts, keys, invite codes, or security-sensitive identifiers.\n\nAvoid shortcuts such as modulo mapping, rounding, truncation, timestamp-based token generation, predictable seeds, hardcoded IVs, nonce reuse, or short low-entropy secrets without controls. Treat salts, nonces, and IVs according to algorithm requirements. Do not rely on unguessable IDs as a replacement for authentication, authorization, expiration, auditing, or rate limiting.\n\nA practical first-week plan is simple. Search for Math.random. Inventory token generation. Review reset links, invite links, API keys, session IDs, CSRF tokens, and OAuth state values. Check numeric code entropy and rate limits. Inspect IV and nonce handling. Verify log redaction. Add code review rules for security-sensitive randomness, and make monitoring and incident response part of the token lifecycle.",
  "narrationPoints": [
    "Is the application creating a bearer secret, a public identifier, a salt, a nonce, an IV, a key, a bounded integer, or a human-entered code?",
    "Use cryptographically secure APIs for security-sensitive values.",
    "Avoid shortcuts such as modulo mapping, rounding, truncation, timestamp-based token generation, predictable seeds, hardcoded IVs, nonce reuse, or short low-entropy secrets without controls.",
    "Add code review rules for security-sensitive randomness, and make monitoring and incident response part of the token lifecycle.",
    "random for secrets, tokens, reset links, CSRF values, OAuth state, nonces, salts, keys, invite codes, or security-sensitive identifiers.",
    "Secure random values should be unpredictable when secrecy matters, unique when uniqueness matters, correctly sized, correctly encoded, and handled according to their role."
  ]
};
