window.COURSE_MODULE = {
  "title": "Apply the Pattern Across Downloads, Uploads, Archives, and Reviews",
  "graphicAlt": "Four-panel infographic applying filesystem boundaries to downloads, uploads, archives, and reviews. Downloads authorize, map, check, and open. Uploads separate display names from server-named storage. Each archive entry receives destination checks and policy enforcement with entry and expanded-size limits. Review coverage includes root equality, shared prefixes, links, cross-tenant requests, alternate routes, and writes or deletes.",
  "narration": "A download endpoint should accept an authorized object ID, load tenant-scoped storage metadata, select the configured root, and derive the target. It verifies lexical containment and, when links are in scope, real-target containment before opening. The response uses approved display metadata rather than exposing the storage path. Every alternate download or preview route must apply the same object authorization; a path inside the root may still belong to another tenant.\n\nFor uploads, generate the temporary and final storage names on the server. Preserve the original filename only as untrusted metadata, and validate file type, size, and content under the upload policy. Keep staging separate from served or executable locations. Static assets, templates, and generated reports should use logical resource mappings or closed categories instead of combining request text with directory structure. These designs reduce how much path syntax must be validated.\n\nArchive extraction creates many output paths from entry metadata. For every entry, reject unsupported entry types, derive the destination beneath one controlled extraction root, and verify containment before writing. Account for link entries, preexisting links in the destination, entry count, expanded size, and replacement behavior. Use a library mode that exposes enough entry information to enforce the policy. Do not assume that validating the archive's outer filename controls the paths embedded inside it.\n\nCode review should inventory readFile, writeFile, unlink, rm, rename, copyFile, streams, file-serving helpers, upload handlers, and archive extractors. Trace each path component to its source. Identify the authorized root, decoding representation, lexical containment check, real-filesystem assumptions, user and tenant authorization, and service-account permissions. Examine whether another route reaches the object through a weaker mapping and whether concurrent actors can change directories. Tests should cover root equality, siblings with shared prefixes, parent escapes, absolute inputs, unsupported separators for the deployment, links, invalid identifiers, cross-tenant objects, writes, deletes, and archive entries without becoming an exploit catalog.",
  "narrationPoints": [
    "Downloads combine object authorization, controlled mapping, containment, and safe opening.",
    "Uploads use server-generated storage names and separate staging from served content.",
    "Archive extraction validates every output target and resource boundary.",
    "Review all filesystem APIs, path provenance, alternate routes, permissions, and races."
  ]
};
