window.COURSE_MODULE = {
  "title": "Course Summary: Authorize the Resolved Filesystem Target",
  "graphicAlt": "Summary infographic showing one protected flow from object ID through authorization, a server-controlled map, trusted root, lexical containment, real target or parent checks, and controlled opening. Supporting controls are narrow input, link and race design, least privilege, and strict write policies. Root escapes and cross-tenant requests are rejected; normalization is not authorization.",
  "narration": "Design the API to avoid arbitrary paths whenever possible. Accept an object identifier, authorize it for the user and tenant, and map trusted storage metadata to a fixed operation-specific root. Generate internal upload names on the server and preserve original filenames only as untrusted display metadata. Opaque identifiers reduce exposed path syntax, but they never replace access control.\n\nWhen relative path input is necessary, understand its decoded representation, resolve it against an absolute trusted root, and verify lexical containment with path.relative rather than a naive string prefix or a search for two dots. Handle parent escapes, cross-root absolute results, and root equality according to the operation. Normalization and resolution transform path syntax; they do not grant authorization. Use Node's platform-aware path behavior and test Windows and POSIX deployments that the application supports.\n\nLexical containment is not real filesystem containment. For relevant existing objects, compare canonical paths obtained with fs.realpath. For creation, validate the existing parent, generate the child name, and protect that directory. Symlinks, junctions, reparse points, links, mounts, and concurrent replacement require deployment-specific design. Reduce check-then-use gaps, operate on opened handles where practical, and use restricted service accounts and filesystem permissions to limit damage.\n\nApply stricter contracts to writes, deletes, recursive operations, and archive extraction. Centralize well-documented helpers without hiding operation-specific policy, and test path boundaries, links, authorization, and alternate routes. The security decision belongs to the authorized storage boundary and the filesystem target actually accessed, not to whether the original string looked harmless. That principle keeps path validation, object authorization, canonical resolution, and filesystem privilege in their correct roles.",
  "narrationPoints": [
    "Prefer authorized object IDs and server-controlled storage mappings.",
    "Verify lexical containment with path semantics, not substring tests.",
    "Account separately for canonical targets, links, and check-then-use races.",
    "Apply stricter contracts to destructive, recursive, and archive operations."
  ]
};
