window.COURSE_MODULE = {
  "title": "High-Impact Actions, Azure Policy, and Change Guardrails",
  "graphicAlt": "Azure Policy surrounds a workflow that still validates scope, uses supported what-if or preview checks, reviews and approves changes, and plans recovery before applying them.",
  "narration": "Some Azure CLI actions are higher impact because they can quickly change security posture, data exposure, availability, or recovery options. RBAC assignments, network rules, storage access, encryption settings, compute configuration, Key Vault access, logging settings, and data-access changes deserve stronger guardrails than ordinary read-only queries. The script should make those actions explicit.\n\nAzure Policy and governance controls can provide important guardrails, but scripts should not treat policy as a reason to skip validation. Where Azure services and deployment workflows support what-if behavior, previews, dry-run concepts, policy evaluation, diffs, or staged deployment, use those mechanisms as defensive review points. They help reviewers understand the effective change before a high-impact operation reaches production.\n\nDeletion, overwrite, public exposure, permission expansion, and encryption changes deserve extra care. A helper should require target validation, release context, approval gates, operator confirmation, or change tickets when the operation can affect production or sensitive resources. Ambiguous resource selection should fail closed rather than let a broad command act on unintended resources.\n\nGuardrails should support idempotent behavior, rollback thinking, and safe failure. A script should be designed so repeated runs do not create uncontrolled side effects. Recovery paths should be considered before the change begins, especially for identity, storage, data, and networking changes. Secure Azure CLI automation makes high-impact changes visible, reviewed, bounded, and recoverable where recovery is possible.",
  "narrationPoints": [
    "Some Azure CLI actions are higher impact because they can quickly change security posture, data exposure, availability, or recovery options.",
    "Azure Policy and governance controls can provide important guardrails, but scripts should not treat policy as a reason to skip validation.",
    "Deletion, overwrite, public exposure, permission expansion, and encryption changes deserve extra care.",
    "Guardrails should support idempotent behavior, rollback thinking, and safe failure."
  ]
};
