window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Framing, Embedding, and Clickjacking Resistance with reviewable Python controls.",
  "codeExamples": [
    {
      "title": "Control framing by route sensitivity",
      "language": "python",
      "blurb": "The framing helper updates only the frame-ancestors directive so route-specific embedding policy does not erase the rest of the central CSP.",
      "code": "MAX_CSP_BYTES = 8_192\n\ndef set_frame_ancestors(policy: str, value: str) -> str:\n    if not isinstance(policy, str) or len(policy.encode(\"utf-8\")) > MAX_CSP_BYTES:\n        raise ValueError(\"existing CSP rejected\")\n    if value not in {\"'none'\", \"https://portal.partner.example\"}:\n        raise ValueError(\"frame-ancestor policy rejected\")\n    directives = []\n    for raw_directive in policy.split(\";\"):\n        directive = raw_directive.strip()\n        if not directive:\n            continue\n        directive_name = directive.split(None, 1)[0].casefold()\n        if directive_name != \"frame-ancestors\":\n            directives.append(directive)\n    directives.append(f\"frame-ancestors {value}\")\n    result = \"; \".join(directives)\n    if len(result.encode(\"utf-8\")) > MAX_CSP_BYTES:\n        raise ValueError(\"resulting CSP exceeds its byte limit\")\n    return result\n\ndef apply_frame_policy(response, route_name: str):\n    if not isinstance(route_name, str):\n        raise TypeError(\"route name must be a string\")\n    if route_name == \"partner_widget\":\n        ancestors = \"https://portal.partner.example\"\n        response.headers.pop(\"X-Frame-Options\", None)\n    else:\n        ancestors = \"'none'\"\n        response.headers[\"X-Frame-Options\"] = \"DENY\"\n    response.headers[\"Content-Security-Policy\"] = set_frame_ancestors(\n        response.headers.get(\"Content-Security-Policy\", \"\"),\n        ancestors,\n    )\n    return response\n"
    },
    {
      "title": "Protect a state-changing page from embedding",
      "language": "python",
      "blurb": "The response composes framing policy with existing CSP directives and adds a SameSite cookie so clickjacking defenses do not depend on one header alone.",
      "code": "import re\n\nSESSION_ID = re.compile(r\"[A-Za-z0-9_-]{32,128}\\Z\")\nMAX_CSP_BYTES = 8_192\n\ndef set_frame_ancestors_none(policy: str) -> str:\n    if not isinstance(policy, str) or len(policy.encode(\"utf-8\")) > MAX_CSP_BYTES:\n        raise ValueError(\"existing CSP rejected\")\n    directives = []\n    for raw_directive in policy.split(\";\"):\n        directive = raw_directive.strip()\n        if not directive:\n            continue\n        directive_name = directive.split(None, 1)[0].casefold()\n        if directive_name != \"frame-ancestors\":\n            directives.append(directive)\n    directives.append(\"frame-ancestors 'none'\")\n    result = \"; \".join(directives)\n    if len(result.encode(\"utf-8\")) > MAX_CSP_BYTES:\n        raise ValueError(\"resulting CSP exceeds its byte limit\")\n    return result\n\ndef protect_account_response(response, session_id: str):\n    if not isinstance(session_id, str) or SESSION_ID.fullmatch(session_id) is None:\n        raise ValueError(\"session identifier rejected\")\n    response.headers[\"Content-Security-Policy\"] = set_frame_ancestors_none(\n        response.headers.get(\"Content-Security-Policy\", \"\")\n    )\n    response.headers[\"X-Frame-Options\"] = \"DENY\"\n    response.set_cookie(\n        \"session\", session_id, secure=True, httponly=True, samesite=\"Lax\", path=\"/\"\n    )\n    return response\n"
    }
  ]
};
