window.COURSE_MODULE = {
  "title": "HTTPS, HSTS, and Transport Assumptions",
  "graphicAlt": "Layered architecture diagram for HTTPS, HSTS, and Transport Assumptions, showing Python response pipeline, reverse proxy, browser, document, iframe, cache, and cookie jar; labeled arrows identify where browser security policies are enforced and the point where unsafe input or behavior is rejected.",
  "narration": "HTTPS is the foundation for browser transport protection. It helps protect data in transit and gives the browser a basis for stronger security expectations. Many other controls assume secure transport: Secure cookies, trusted redirects, service worker behavior, modern browser APIs, and sensitive form submissions all depend on the application being served over a properly configured secure channel. Headers can support this model, but they do not replace TLS itself.\n\nStrict-Transport-Security, commonly called HSTS, tells browsers to use HTTPS for a site under defined rules after the browser has seen the policy. That can help reduce accidental downgrade behavior and mixed transport assumptions. HSTS needs careful rollout because browsers remember the policy for the configured time. Subdomain coverage and preload concepts can broaden the effect, so teams should understand domain ownership, legacy hosts, and operational readiness before using aggressive settings.\n\nLocal development, staging, and production often have different transport realities. Developers may test with local HTTP while production uses TLS behind a reverse proxy. The Python application may see a proxied request and need to understand forwarded protocol information correctly. If the application and proxy disagree about whether a request is secure, cookies, redirects, generated links, and origin checks can behave incorrectly. Transport assumptions should be documented and validated in production-like environments.\n\nTransport-related headers do not replace authentication, authorization, or input validation. HTTPS protects the channel; it does not decide whether the user may perform an action. HSTS encourages secure transport; it does not fix unsafe templates or exposed secrets. Secure cookies align session behavior with HTTPS; they do not make session contents safe by themselves. Transport controls are essential, but they are one layer in a broader design.",
  "narrationPoints": [
    "HTTPS is the foundation for browser transport protection.",
    "HSTS needs careful rollout because browsers remember the policy for the configured time.",
    "Developers may test with local HTTP while production uses TLS behind a reverse proxy.",
    "If the application and proxy disagree about whether a request is secure, cookies, redirects, generated links, and origin checks can behave incorrectly.",
    "HTTPS protects the channel; it does not decide whether the user may perform an action.",
    "Transport controls are essential, but they are one layer in a broader design."
  ]
};
