window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Connection Strings, Secrets, and Configuration Sources through distinct, reviewable JavaScript security boundaries.",
  "codeExamples": [
    {
      "title": "Parse a PostgreSQL connection reference safely",
      "language": "javascript",
      "blurb": "Startup bounds the connection text; enforces the connector scheme, exact approved host, port, deployment metadata, database name, credential syntax, and absence of query or fragment overrides.",
      "code": "const MAXIMUM_POSTGRES_URL_BYTES = 8192;\nconst DEPLOYMENT_NAME = /^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/;\n\nfunction validateCredentialComponent(value, name, maximumBytes) {\n  let decoded;\n  try { decoded = decodeURIComponent(value); }\n  catch { throw new TypeError(name + \" encoding invalid\"); }\n  if (!decoded || Buffer.byteLength(decoded, \"utf8\") > maximumBytes ||\n      /[\\u0000-\\u001f\\u007f]/.test(decoded)) {\n    throw new TypeError(name + \" invalid\");\n  }\n}\n\nexport function validatePostgresUrl(text, approvedHosts) {\n  if (typeof text !== \"string\" || text.trim() !== text ||\n      Buffer.byteLength(text, \"utf8\") > MAXIMUM_POSTGRES_URL_BYTES ||\n      !(approvedHosts instanceof Map)) {\n    throw new TypeError(\"PostgreSQL URL and host policy required\");\n  }\n  const url = new URL(text);\n  if (![\"postgres:\", \"postgresql:\"].includes(url.protocol) ||\n      !Map.prototype.has.call(approvedHosts, url.hostname)) {\n    throw new Error(\"approved PostgreSQL endpoint required\");\n  }\n  if ((url.port && url.port !== \"5432\") || url.search || url.hash) {\n    throw new Error(\"PostgreSQL connection overrides rejected\");\n  }\n  if (!url.username || !url.password || !/^\\/[a-z0-9_-]+$/i.test(url.pathname)) {\n    throw new Error(\"database identity incomplete\");\n  }\n  validateCredentialComponent(url.username, \"database username\", 128);\n  validateCredentialComponent(url.password, \"database password\", 4096);\n  const deployment = Map.prototype.get.call(approvedHosts, url.hostname);\n  if (typeof deployment !== \"string\" || !DEPLOYMENT_NAME.test(deployment)) {\n    throw new Error(\"approved deployment metadata required\");\n  }\n  return Object.freeze({\n    deployment, database: url.pathname.slice(1), credentialPresent: true\n  });\n}\n"
    },
    {
      "title": "Resolve database credentials from a versioned secret",
      "language": "javascript",
      "blurb": "Configuration carries an opaque secret reference; the manager response must match its exact version and bounded credential contract, and the helper avoids returning a reusable connection URL.",
      "code": "const databaseSecretReference = /^secrets\\/[a-z0-9_-]{1,128}\\/versions\\/(\\d{1,20})$/i;\n\nfunction validDatabaseUsername(value) {\n  return typeof value === \"string\" && value.length >= 1 && value.length <= 128 &&\n    value.trim() === value && !/[\\u0000-\\u001f\\u007f]/.test(value);\n}\n\nfunction validDatabasePassword(value) {\n  return typeof value === \"string\" && Buffer.byteLength(value, \"utf8\") >= 1 &&\n    Buffer.byteLength(value, \"utf8\") <= 4096;\n}\n\nexport async function databaseCredential(manager, reference) {\n  const match = typeof reference === \"string\" ? reference.match(databaseSecretReference) : null;\n  const rawAccessCapability = manager?.access;\n  const access = typeof rawAccessCapability === \"function\"\n    ? rawAccessCapability.bind(manager)\n    : null;\n  if (!match || !access) {\n    throw new TypeError(\"versioned database secret reference required\");\n  }\n  const requestedVersion = match[1];\n  const result = await access(reference);\n  const returnedReference = result?.reference;\n  const returnedVersion = result?.version;\n  const value = result?.value;\n  const username = value?.username;\n  const password = value?.password;\n  if (returnedReference !== reference || returnedVersion !== requestedVersion ||\n      !validDatabaseUsername(username) || !validDatabasePassword(password)) {\n    throw new Error(\"database credential invalid\");\n  }\n  return Object.freeze({ username, password, version: requestedVersion });\n}\n"
    }
  ]
};
