window.COURSE_MODULE = {
  "title": "Connection Pools, Lifecycle, Timeouts, and Availability",
  "graphicAlt": "Control-and-evidence diagram for Connection Pools, Lifecycle, Timeouts, and Availability in Secure Database Connections in Node.js, linking each security decision to the protected asset, the enforcing component, the failure state, and the observable verification signal.",
  "narration": "Connection security includes availability. A connection can be authenticated, encrypted, and least-privileged, yet still harm the system if connection lifecycle is unmanaged. Connection pools reuse database connections and improve performance, but misconfigured pools can exhaust database capacity, amplify outages, or create cascading failures. Creating a new client or pool per request is often inefficient and can turn ordinary traffic into a connection storm.\n\nPool size should be chosen from the whole deployment view, not one process in isolation. Consider application concurrency, database limits, number of containers or processes, worker counts, serverless scaling, background jobs, reporting workloads, and administrative scripts. Serverless and short-lived environments need special attention because concurrency can grow quickly and connection reuse may behave differently than in a long-running Express server or worker process.\n\nConfigure connection timeouts, idle timeouts, query timeouts, retry behavior, and server selection behavior intentionally. Avoid infinite retries that overload a recovering database or hide real failures. Release borrowed connections back to the pool and clean up connections during shutdown when the runtime model requires it. Monitor pool exhaustion, connection errors, slow queries, retry spikes, connection establishment delays, and sudden connection growth. Predictable connection behavior makes incidents easier to detect, contain, and recover from.",
  "narrationPoints": [
      "Connection pools reuse database connections and improve performance, but misconfigured pools can exhaust database capacity, amplify outages, or create cascading failures.",
      "Serverless and short-lived environments need special attention because concurrency can grow quickly and connection reuse may behave differently than in a long-running Express server or worker process.",
      "Monitor pool exhaustion, connection errors, slow queries, retry spikes, connection establishment delays, and sudden connection growth.",
      "Configure connection timeouts, idle timeouts, query timeouts, retry behavior, and server selection behavior intentionally.",
      "A connection can be authenticated, encrypted, and least-privileged, yet still harm the system if connection lifecycle is unmanaged.",
      "Consider application concurrency, database limits, number of containers or processes, worker counts, serverless scaling, background jobs, reporting workloads, and administrative scripts."
  ]
};
