window.COURSE_MODULE = {
  "title": "Network Exposure, Deployment Context, and Environment Separation",
  "graphicAlt": "Left-to-right security workflow for Network Exposure, Deployment Context, and Environment Separation in Secure Database Connections in Node.js: untrusted input crosses a labeled boundary, a validating component enforces policy, and only a verified result reaches the protected resource.",
  "narration": "The safest credential still creates risk if the database is reachable from too many places. A production database should be available through deliberate and minimal paths, not broadly reachable from the internet or every build environment. Use private networking, firewalls, security groups, IP allowlists, service mesh policy, VPC controls, or equivalent platform controls according to the deployment. Database admin consoles, dashboards, backups, replicas, and restore environments need network and access controls too.\n\nSeparate local, test, staging, preview, production, disaster recovery, and analytics connection paths. Avoid exposing production databases to untrusted preview builds, forked pull requests, broad CI jobs, or temporary test environments. Containers and serverless platforms need careful secret injection, outbound network restrictions, runtime identity design, and dependency on platform networking behavior. Local development access should be intentionally limited and auditable, not a copy of production access with a different name.\n\nDevelopment shortcuts should not become production patterns. Local tunnels, open firewall rules, shared credentials, public test databases, and emergency allowlists are often created to solve immediate problems, then forgotten. Rollback and disaster recovery plans should account for both code and connection configuration changes. A broken network rule, expired certificate, or wrong endpoint can be as disruptive as a broken release. Network architecture is part of the database connection security boundary.",
  "narrationPoints": [
      "A production database should be available through deliberate and minimal paths, not broadly reachable from the internet or every build environment.",
      "Containers and serverless platforms need careful secret injection, outbound network restrictions, runtime identity design, and dependency on platform networking behavior.",
      "Network architecture is part of the database connection security boundary.",
      "Database admin consoles, dashboards, backups, replicas, and restore environments need network and access controls too.",
      "Separate local, test, staging, preview, production, disaster recovery, and analytics connection paths.",
      "Rollback and disaster recovery plans should account for both code and connection configuration changes."
  ]
};
