window.COURSE_MODULE = {
  "title": "Security Architecture for Go Services",
  "graphicAlt": "A Go service exposes reviewable control points for callers, input, data, dependencies and operations, supported by explicit assumptions and testable behavior.",
  "narration": "Security architecture for Go services is the set of engineering decisions that shapes how a service protects data, actions, dependencies, and runtime behavior. It is not only a diagram or a review checklist. It is the way a team decides where trust begins, where trust ends, which controls are required, and how those controls remain understandable as the service changes.\n\nGo gives service teams useful advantages. The language is small, the standard library has strong server patterns, binaries are straightforward to deploy, and concurrency can be expressed clearly when the design is disciplined. Those strengths help, but they do not automatically create secure outcomes. A Go service still needs deliberate choices around identity, validation, data exposure, dependency management, failure behavior, and operations.\n\nA secure service should have clear boundaries. Engineers should be able to identify who can call it, what inputs it accepts, what outputs it returns, what dependencies it trusts, and what assumptions must hold for each operation. Inputs and outputs should be controlled, sensitive data should have visible handling rules, and security-relevant behavior should be observable in logs, metrics, traces, and audit events.\n\nArchitecture also prevents fragile security by convention. If authorization checks are scattered randomly, if validation happens only in some handlers, or if secret handling depends on individual memory, the service becomes hard to maintain safely. Architecture should make secure behavior the normal path, not a heroic effort by the most experienced engineer on the team.\n\nThe goal is a Go service that is understandable, maintainable, testable, and safe to operate under real-world conditions. Good architecture supports feature work, incident response, code review, onboarding, and production operations. It makes important assumptions explicit so teams can reason about risk before a failure, not only after one.",
  "narrationPoints": [
    "Security architecture for Go services is the set of engineering decisions that shapes how a service protects data, actions, dependencies, and...",
    "Go gives service teams useful advantages.",
    "A secure service should have clear boundaries.",
    "Architecture also prevents fragile security by convention.",
    "The goal is a Go service that is understandable, maintainable, testable, and safe to operate under real-world conditions."
  ]
};
