window.COURSE_MODULE = {
  "title": "Service Boundaries and Trust Zones",
  "graphicAlt": "External and internal callers, files, messages and configuration cross checked boundaries; private-network location does not grant permission.",
  "narration": "A Go service usually sits between many systems. It may receive calls from clients, gateways, internal services, background jobs, administrative tools, or webhooks. It may call databases, caches, queues, identity providers, logging platforms, object stores, cloud APIs, and third-party services. Each connection is a boundary where assumptions can break.\n\nA boundary is not only a network edge. A message queue is a boundary. A file import is a boundary. A configuration value is a boundary. A database record written by an older version of the service can also behave like a boundary because its shape and meaning may not match current code. Boundaries are where data and authority move between contexts.\n\nInternal traffic should not automatically be treated as fully trusted. Internal callers can be misconfigured, outdated, over-permissioned, or compromised through ordinary operational failure. A secure architecture avoids assuming that private network location alone proves safety. It still validates inputs, authenticates callers where appropriate, and enforces authorization for protected actions.\n\nTrust zones help engineers decide where controls belong. At one boundary, the service may need request validation and rate limits. At another, it may need service identity, scoped credentials, or careful output filtering. At another, it may need audit events because administrative actions or sensitive records are involved. The control should match the trust relationship and the risk of the operation.\n\nA good architecture makes boundaries visible in code structure, configuration, deployment, and operational documentation. Handlers, middleware, service layers, repository layers, and background workers should make it clear where input is accepted, where it is normalized, where permissions are checked, and where side effects happen.\n\nClear boundaries reduce confusion during maintenance, incident response, and future feature work. When a team can quickly identify which boundary failed or which assumption changed, it can fix the design instead of patching symptoms in unrelated code.",
  "narrationPoints": [
    "A Go service usually sits between many systems.",
    "A boundary is not only a network edge.",
    "Internal traffic should not automatically be treated as fully trusted.",
    "Trust zones help engineers decide where controls belong.",
    "A good architecture makes boundaries visible in code structure, configuration, deployment, and operational documentation."
  ]
};
