window.COURSE_MODULE = {
  "title": "Secure Data Handling in Go Services",
  "graphicAlt": "Data classification and ownership guide validated configuration, secret protection, minimal responses, redacted logs, and separate transit and storage protections.",
  "narration": "Secure architecture starts by knowing what data the service handles and why that data matters. A Go service may process public records, internal business data, personal information, credentials, tokens, session identifiers, configuration values, and operational metadata. Each category deserves a handling rule that engineers can understand and apply.\n\nSecrets, tokens, keys, session identifiers, personal data, and business-sensitive records should not be treated like ordinary strings. They may need restricted logging, limited serialization, narrow access, careful storage, and explicit ownership. The code should make sensitive data paths visible instead of relying on every developer to remember hidden rules.\n\nConfiguration should separate safe defaults from sensitive values. A timeout default or feature flag default is different from a signing key, database password, or service credential. Required configuration should be validated before the service starts handling traffic, so missing or malformed values fail clearly during startup rather than during a user workflow.\n\nLogging is a common data-handling risk. Logs should support operations and investigations, but they should not leak secrets, credentials, tokens, personal data, or sensitive payloads. Useful logs often include stable identifiers, event categories, request correlation, dependency names, and failure reasons without recording entire raw objects.\n\nEncryption responsibilities should also be clear. The architecture should identify what is protected in transit, what is protected at rest, and which platform, database, service mesh, load balancer, or application component owns each control. If the responsibility is assumed but not documented, teams can miss gaps during migration or incident response.\n\nData handling rules should be visible in code review, deployment, and operational runbooks. Reviewers should know when sensitive fields are introduced. Operators should know where secrets come from and how they rotate. Developers should know which response models are safe to expose. Secure data handling is a lifecycle practice, not a single library call.",
  "narrationPoints": [
    "Secure architecture starts by knowing what data the service handles and why that data matters.",
    "Secrets, tokens, keys, session identifiers, personal data, and business-sensitive records should not be treated like ordinary strings.",
    "Configuration should separate safe defaults from sensitive values.",
    "Logging is a common data-handling risk.",
    "Encryption responsibilities should also be clear."
  ]
};
