window.COURSE_MODULE = {
  "title": "Dependency, Supply Chain, and Build Architecture",
  "graphicAlt": "Source commits, modules, maintained base images, build tools and configuration pass through a controlled build into traceable artifacts and running services.",
  "narration": "Every dependency becomes part of a service's security and reliability story. In Go services, dependencies may include Go modules, generated code, container base images, build tools, CI actions, operating system packages, and runtime sidecars. Each one can affect what code runs, how it is built, and how it behaves in production.\n\nGo modules and version information help teams make dependency decisions repeatable. They are valuable, but they do not replace review and maintenance. A pinned version can still contain a defect, and an updated version can still change behavior. Defensive architecture treats dependency updates as controlled engineering changes with visible review.\n\nPrefer small, well-understood dependency sets over unnecessary packages for routine tasks. This does not mean avoiding libraries entirely. It means considering whether a package is needed, who maintains it, how widely it is used, what transitive dependencies it brings, and whether the standard library already provides a clear solution.\n\nBuild and release architecture should make it clear what source, version, configuration, and artifact are being deployed. Teams should be able to trace a running service back to a commit, build pipeline, module set, image, and configuration profile. Repeatability matters because incident response and rollback depend on knowing what changed.\n\nContainer images and runtime packages should be kept minimal and maintained. A smaller runtime surface can reduce operational complexity and make scanning results easier to act on. Base images, certificates, time zone data, and system packages should have an ownership and update path, not a one-time setup.\n\nDefensive supply-chain architecture focuses on visibility, repeatability, review, and controlled change. The goal is not to freeze the service forever. The goal is to make changes intentional, observable, and reversible enough that teams can improve security without losing confidence in what they are deploying.",
  "narrationPoints": [
    "Every dependency becomes part of a service's security and reliability story.",
    "Go modules and version information help teams make dependency decisions repeatable.",
    "Prefer small, well-understood dependency sets over unnecessary packages for routine tasks.",
    "Build and release architecture should make it clear what source, version, configuration, and artifact are being deployed.",
    "Container images and runtime packages should be kept minimal and maintained."
  ]
};
