window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Upload and Download Safety with reviewable Python controls.",
  "codeExamples": [
    {
      "title": "Stream an upload into application-controlled storage",
      "language": "python",
      "blurb": "The server bounds actual bytes and removes its partial destination whenever reading, validation, or writing fails before completion.",
      "code": "from hashlib import sha256\nimport os\nimport stat\nfrom uuid import uuid4\n\nMAX_UPLOAD_BYTES = 10_000_000\n\ndef store_upload(\n    stream,\n    directory_fd: int,\n    maximum: int = 5_000_000,\n) -> tuple[str, str]:\n    if type(directory_fd) is not int or directory_fd < 0:\n        raise ValueError(\"upload directory descriptor rejected\")\n    if type(maximum) is not int or not 1 <= maximum <= MAX_UPLOAD_BYTES:\n        raise ValueError(\"upload byte limit rejected\")\n    if not hasattr(os, \"O_NOFOLLOW\"):\n        raise NotImplementedError(\"secure upload creation requires O_NOFOLLOW\")\n    directory_info = os.fstat(directory_fd)\n    if not stat.S_ISDIR(directory_info.st_mode):\n        raise ValueError(\"upload directory descriptor rejected\")\n\n    stored_name = uuid4().hex\n    descriptor = os.open(\n        stored_name,\n        os.O_WRONLY\n        | os.O_CREAT\n        | os.O_EXCL\n        | os.O_NOFOLLOW\n        | getattr(os, \"O_CLOEXEC\", 0),\n        0o600,\n        dir_fd=directory_fd,\n    )\n    digest = sha256()\n    total = 0\n    try:\n        with os.fdopen(descriptor, \"wb\") as output:\n            descriptor = -1\n            while True:\n                chunk = stream.read(64 * 1024)\n                if not chunk:\n                    break\n                if type(chunk) is not bytes:\n                    raise ValueError(\"upload stream returned invalid data\")\n                if len(chunk) > maximum - total:\n                    raise ValueError(\"upload exceeds the byte limit\")\n                total += len(chunk)\n                digest.update(chunk)\n                output.write(chunk)\n        return stored_name, digest.hexdigest()\n    except BaseException as error:\n        cleanup_errors: list[Exception] = []\n        if descriptor >= 0:\n            try:\n                os.close(descriptor)\n            except Exception as cleanup_error:\n                cleanup_errors.append(cleanup_error)\n        try:\n            os.unlink(stored_name, dir_fd=directory_fd)\n        except FileNotFoundError:\n            pass\n        except Exception as cleanup_error:\n            cleanup_errors.append(cleanup_error)\n        if cleanup_errors:\n            raise BaseExceptionGroup(\n                \"upload storage and cleanup failed\",\n                [error, *cleanup_errors],\n            )\n        raise\n"
    },
    {
      "title": "Authorize before opening a download",
      "language": "python",
      "blurb": "The repository evaluates validated tenant, subject, and object identifiers first; the returned storage key is then revalidated before a bound storage capability opens it.",
      "code": "import re\nfrom uuid import UUID\n\nOPAQUE_ID = re.compile(r\"[A-Za-z0-9][A-Za-z0-9_-]{0,63}\\Z\")\nSTORAGE_KEY = re.compile(r\"[a-f0-9]{32}\\Z\")\n\ndef validated_identity(value: object, field_name: str) -> str:\n    if not isinstance(value, str) or OPAQUE_ID.fullmatch(value) is None:\n        raise ValueError(f\"{field_name} rejected\")\n    return value\n\ndef open_authorized_download(repository, storage, tenant_id: str, subject_id: str, file_id: str):\n    tenant = validated_identity(tenant_id, \"tenant identifier\")\n    subject = validated_identity(subject_id, \"subject identifier\")\n    try:\n        object_id = str(UUID(file_id))\n    except (AttributeError, TypeError, ValueError):\n        raise ValueError(\"file identifier rejected\") from None\n    get_authorized_file = repository.get_authorized_file\n    open_read = storage.open_read\n    if not callable(get_authorized_file) or not callable(open_read):\n        raise TypeError(\"download adapter contract rejected\")\n    record = get_authorized_file(\n        tenant_id=tenant,\n        subject_id=subject,\n        file_id=object_id,\n        permission=\"download\",\n    )\n    if record is None:\n        raise FileNotFoundError(\"file not found\")\n    storage_key = getattr(record, \"storage_key\", None)\n    if not isinstance(storage_key, str) or STORAGE_KEY.fullmatch(storage_key) is None:\n        raise RuntimeError(\"authorized storage key rejected\")\n    return open_read(storage_key)\n"
    }
  ]
};
