window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Archives, Symlinks, Temporary Files, and Race Conditions with reviewable Python controls.",
  "codeExamples": [
    {
      "title": "Approve portable ZIP member names before extraction",
      "language": "python",
      "blurb": "The validator interprets every name with POSIX and Windows rules, rejects drives, absolute paths, traversal, links, reserved device names, alternate-stream syntax, trailing dots or spaces, and normalized collisions.",
      "code": "from pathlib import Path, PurePosixPath, PureWindowsPath\nfrom zipfile import ZipFile\nimport re\nimport stat\n\nSAFE_MEMBER_PART = re.compile(r\"[A-Za-z0-9][A-Za-z0-9._-]{0,127}\\Z\")\nWINDOWS_RESERVED = {\n    \"CON\", \"PRN\", \"AUX\", \"NUL\",\n    *(f\"COM{number}\" for number in range(1, 10)),\n    *(f\"LPT{number}\" for number in range(1, 10)),\n}\n\ndef portable_member_part(part: str) -> bool:\n    if not SAFE_MEMBER_PART.fullmatch(part) or part[-1] in {\".\", \" \"}:\n        return False\n    return part.split(\".\", 1)[0].upper() not in WINDOWS_RESERVED\n\ndef approved_zip_members(archive: ZipFile, maximum_bytes: int = 50_000_000):\n    members = archive.infolist()\n    if len(members) > 500 or sum(item.file_size for item in members) > maximum_bytes:\n        raise ValueError(\"archive resource limits exceeded\")\n    seen_files = set()\n    for item in members:\n        raw_name = item.filename\n        posix_path = PurePosixPath(raw_name)\n        windows_path = PureWindowsPath(raw_name)\n        mode = item.external_attr >> 16\n        unsafe = (\n            not raw_name\n            or \"\\\\\" in raw_name\n            or \":\" in raw_name\n            or posix_path.is_absolute()\n            or windows_path.is_absolute()\n            or bool(windows_path.drive)\n            or stat.S_ISLNK(mode)\n            or any(part in {\"\", \".\", \"..\"} or not portable_member_part(part) for part in posix_path.parts)\n        )\n        if unsafe:\n            raise ValueError(\"unsafe archive member\")\n        if item.is_dir():\n            continue\n        normalized = tuple(part.casefold() for part in posix_path.parts)\n        if normalized in seen_files:\n            raise ValueError(\"duplicate archive member\")\n        seen_files.add(normalized)\n        yield item, Path(*posix_path.parts)\n"
    },
    {
      "title": "Create a temporary file beside its commit target",
      "language": "python",
      "blurb": "A trusted reports directory and one approved report name choose the commit target before a unique same-filesystem temporary file is flushed, synchronized, and atomically moved into place.",
      "code": "from pathlib import Path, PurePosixPath, PureWindowsPath\nimport os\nimport re\nimport tempfile\n\nSAFE_REPORT_NAME = re.compile(r\"[A-Za-z0-9][A-Za-z0-9._-]{0,127}\\Z\")\nWINDOWS_RESERVED = {\n    \"CON\", \"PRN\", \"AUX\", \"NUL\",\n    *(f\"COM{number}\" for number in range(1, 10)),\n    *(f\"LPT{number}\" for number in range(1, 10)),\n}\n\ndef checked_report_name(name: str) -> str:\n    if not isinstance(name, str):\n        raise ValueError(\"invalid report name\")\n    posix_path = PurePosixPath(name)\n    windows_path = PureWindowsPath(name)\n    if (\n        not SAFE_REPORT_NAME.fullmatch(name)\n        or name in {\".\", \"..\"}\n        or \"\\x00\" in name\n        or \":\" in name\n        or \"/\" in name\n        or \"\\\\\" in name\n        or posix_path.is_absolute()\n        or windows_path.is_absolute()\n        or bool(windows_path.drive)\n        or name[-1] in {\".\", \" \"}\n        or name.split(\".\", 1)[0].upper() in WINDOWS_RESERVED\n    ):\n        raise ValueError(\"invalid report name\")\n    return name\n\ndef replace_report(report_root: Path, report_name: str, content: bytes) -> None:\n    trusted_root = report_root.resolve(strict=True)\n    if not trusted_root.is_dir():\n        raise ValueError(\"report root must be a directory\")\n    destination = trusted_root / checked_report_name(report_name)\n    descriptor, temporary = tempfile.mkstemp(prefix=f\".{destination.name}.\", dir=trusted_root)\n    try:\n        with os.fdopen(descriptor, \"wb\") as output:\n            output.write(content)\n            output.flush()\n            os.fsync(output.fileno())\n        os.replace(temporary, destination)\n    except BaseException:\n        try:\n            os.unlink(temporary)\n        except FileNotFoundError:\n            pass\n        raise\n"
    }
  ]
};
