window.COURSE_MODULE = {
  "title": "Upload and Download Safety",
  "graphicAlt": "Decision diagram for Upload and Download Safety, showing untrusted path input, identifier map, trusted storage root, open file descriptor, and denied escape path; labeled arrows identify filesystem containment and authorization checks and the point where unsafe input or behavior is rejected.",
  "narration": "Upload workflows should control where files are stored from the beginning. The application should choose the destination, generate or approve the storage name, apply size limits, capture safe metadata, and avoid trusting the user-provided filename as a path. Content type and extension checks can support policy, but they should not be the only control. Upload handling should assume filenames and metadata are untrusted even when the user is authenticated.\n\nDownload endpoints require authorization before file access. The application should verify the current subject, action, resource, and context before opening or serving content. A route that accepts a file identifier should confirm that the file exists, belongs to the expected tenant or organization, is in a downloadable state, and is available to the caller. Hiding links in the user interface does not replace server-side object-level access control.\n\nTenant and organization boundaries are central to file safety. In multi-tenant systems, a correct path operation can still be a security failure if it returns another tenant?s file. Storage records should include ownership or tenancy information, and access checks should use that information close to the file operation. Background jobs, exports, previews, thumbnails, and generated reports should follow the same boundary rules as direct downloads.\n\nFile serving should use framework or storage helpers deliberately when they match the use case. Helpers can handle common response behavior, headers, streaming, range requests, and safe storage integration, but they do not automatically solve authorization or storage design. Avoid exposing internal paths in responses, logs, or error messages. A safe download tells the user what they are allowed to receive, not how the server is laid out.",
  "narrationPoints": [
    "Upload workflows should control where files are stored from the beginning.",
    "The application should verify the current subject, action, resource, and context before opening or serving content.",
    "Tenant and organization boundaries are central to file safety.",
    "Background jobs, exports, previews, thumbnails, and generated reports should follow the same boundary rules as direct downloads.",
    "Helpers can handle common response behavior, headers, streaming, range requests, and safe storage integration, but they do not automatically solve authorization or storage design.",
    "Download endpoints require authorization before file access."
  ]
};
