window.COURSE_MODULE = {
  "title": "Archives, Symlinks, Temporary Files, and Race Conditions",
  "graphicAlt": "Boundary map for Archives, Symlinks, Temporary Files, and Race Conditions, showing untrusted path input, identifier map, trusted storage root, open file descriptor, and denied escape path; labeled arrows identify filesystem containment and authorization checks and the point where unsafe input or behavior is rejected.",
  "narration": "Archive handling deserves special review because an archive is a collection of file-related instructions. Entries may include names, directories, metadata, permissions, or link-like behavior depending on the format and tool. Safe extraction should validate each entry, choose a trusted extraction destination, enforce containment, avoid unexpected overwrite behavior, and treat extracted content as untrusted until it has passed the rest of the application?s policy.\n\nSymbolic links, shortcuts, hard links, and mounted paths can affect where a file operation ultimately points. The details vary by platform and deployment, but the design concern is stable: a path that looked safe during validation may refer somewhere else when used. Teams should understand whether their APIs follow links, whether storage directories can contain links, and whether untrusted users can create or influence link-like objects inside locations the application processes.\n\nTemporary files are security-relevant because they often handle uploads, generated reports, exports, conversions, or intermediate data. Predictable names, shared directories, broad permissions, incomplete cleanup, and accidental reuse can create exposure. Safer patterns use framework or platform helpers that create unpredictable names with appropriate permissions, keep temporary data in approved locations, and clean up consistently after success or failure.\n\nTime-of-check and time-of-use concerns appear when validation and use are separated. A file may be replaced, moved, linked, deleted, or modified between the moment code checks it and the moment code opens or serves it. Concurrent workers can make this more likely. Sensitive file workflows should minimize gaps, control permissions, avoid trusting mutable paths, and prefer stable storage records or handles where possible. Sequencing matters as much as the check itself.",
  "narrationPoints": [
    "Archive handling deserves special review because an archive is a collection of file-related instructions.",
    "Symbolic links, shortcuts, hard links, and mounted paths can affect where a file operation ultimately points.",
    "Predictable names, shared directories, broad permissions, incomplete cleanup, and accidental reuse can create exposure.",
    "Time-of-check and time-of-use concerns appear when validation and use are separated.",
    "Sensitive file workflows should minimize gaps, control permissions, avoid trusting mutable paths, and prefer stable storage records or handles where possible.",
    "Concurrent workers can make this more likely."
  ]
};
