window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Image Scanning, SBOMs, Registries, and CI/CD Controls through distinct, reviewable JavaScript security boundaries.",
  "codeExamples": [
    {
      "title": "Gate a container image on scan and signature evidence",
      "language": "javascript",
      "blurb": "An application-owned verifier measures and authenticates the supplied artifact before release policy checks its bound digest, approved signer identity, vulnerability threshold, and fresh scan timestamp.",
      "code": "const approvedImageSigners = new Set([\"spiffe://example.internal/ci/container-release\"]);\nconst imageReleasePolicy = Object.freeze({ maximumHighFindings: 0 });\n\nexport function createImageReleaseValidator(verifyArtifact, clock = () => Date.now()) {\n  if (typeof verifyArtifact !== \"function\") {\n    throw new TypeError(\"trusted artifact verifier required\");\n  }\n  if (typeof clock !== \"function\") throw new TypeError(\"trusted release clock required\");\n  return async function validateImageRelease(artifact) {\n    const evidence = await verifyArtifact(artifact);\n    const digest = evidence?.digest;\n    const signatureVerified = evidence?.signatureVerified;\n    const signerIdentity = evidence?.signerIdentity;\n    const findings = evidence?.findings;\n    const critical = findings?.critical;\n    const high = findings?.high;\n    const scannedAtText = evidence?.scannedAt;\n    const now = clock();\n    if (!Number.isSafeInteger(now) || now < 0) throw new TypeError(\"release clock invalid\");\n    if (typeof digest !== \"string\" || !/^sha256:[a-f0-9]{64}$/.test(digest) ||\n        signatureVerified !== true || !approvedImageSigners.has(signerIdentity)) {\n      throw new Error(\"image identity unverified\");\n    }\n    if (!Number.isSafeInteger(critical) || critical < 0 ||\n        !Number.isSafeInteger(high) || high < 0) {\n      throw new Error(\"image vulnerability counts invalid\");\n    }\n    if (critical > 0 || high > imageReleasePolicy.maximumHighFindings) {\n      throw new Error(\"image vulnerability policy failed\");\n    }\n    const scannedAt = typeof scannedAtText === \"string\"\n      ? Date.parse(scannedAtText)\n      : Number.NaN;\n    if (!Number.isFinite(scannedAt) ||\n        new Date(scannedAt).toISOString() !== scannedAtText || scannedAt > now ||\n        now - scannedAt > 24 * 60 * 60 * 1000) {\n      throw new Error(\"valid fresh image scan required\");\n    }\n    return true;\n  };\n}\n"
    },
    {
      "title": "Associate a container SBOM with the final image digest",
      "language": "javascript",
      "blurb": "A trusted measurement adapter binds the approved OCI repository, canonical image digest, SBOM, and verified provenance to the supplied artifact before an immutable release record is returned.",
      "code": "const sha256 = /^[a-f0-9]{64}$/;\nconst imageDigest = /^sha256:[a-f0-9]{64}$/;\nconst approvedImageRepositories = new Set([\n  \"registry.example.com/orders/api\",\n  \"registry.example.com/orders/worker\"\n]);\n\nfunction validatedSupplyChainRecord(evidence) {\n  const image = evidence?.image;\n  const sbom = evidence?.sbom;\n  const provenance = evidence?.provenance;\n  const digest = image?.digest;\n  const reference = image?.reference;\n  const sbomSubject = sbom?.subjectDigest;\n  const includesBuildStage = sbom?.includesBuildStage;\n  const sbomSha256 = sbom?.sha256;\n  const provenanceSubject = provenance?.subjectDigest;\n  const provenanceVerified = provenance?.verified;\n  const provenanceSha256 = provenance?.sha256;\n  if (typeof digest !== \"string\" || !imageDigest.test(digest) ||\n      !approvedImageRepositories.has(reference)) {\n    throw new Error(\"final image identity invalid\");\n  }\n  if (digest !== sbomSubject || digest !== provenanceSubject) {\n    throw new Error(\"supply-chain subject mismatch\");\n  }\n  if (includesBuildStage !== false || provenanceVerified !== true ||\n      typeof sbomSha256 !== \"string\" || !sha256.test(sbomSha256) ||\n      typeof provenanceSha256 !== \"string\" || !sha256.test(provenanceSha256)) {\n    throw new Error(\"release evidence invalid\");\n  }\n  return Object.freeze({\n    image: reference + \"@\" + digest,\n    sbomDigest: sbomSha256,\n    provenanceDigest: provenanceSha256\n  });\n}\n\nexport function createContainerSupplyChainRecorder(measureSupplyChain) {\n  if (typeof measureSupplyChain !== \"function\") {\n    throw new TypeError(\"trusted supply-chain measurement adapter required\");\n  }\n  return async function containerSupplyChainRecord(artifact) {\n    const evidence = await measureSupplyChain(artifact);\n    return validatedSupplyChainRecord(evidence);\n  };\n}\n"
    }
  ]
};
