window.COURSE_MODULE = {
  "title": "Why Dockerized Node.js Security Matters",
  "graphicAlt": "Layered architecture view of Why Dockerized Node.js Security Matters for Secure Dockerized Node.js Applications, placing the protected asset at the center and surrounding it with identity, validation, resource, lifecycle, and monitoring controls.",
  "narration": "A Node.js service often starts with a simple goal: make it run the same way everywhere. A developer writes a Dockerfile, copies the application into an image, installs dependencies, exposes a port, and the result becomes the artifact that moves through staging and production. That convenience is real, but it also means the Dockerfile, base image, package-lock.json, environment variables, startup command, and runtime flags are now part of the security design.\n\nContainers package more than application code. They include the Node.js runtime, npm dependencies, operating system packages, image layers, metadata, startup behavior, and configuration assumptions. A Docker image can reduce environment drift, but it can also preserve vulnerable packages, include secrets by mistake, run with excessive privilege, expose unnecessary ports, or ship development defaults into production. The image becomes a supply chain object, not just a deployment wrapper.\n\nContainers are isolated, but they are not perfect security boundaries. Host configuration, runtime options, orchestrator policy, network exposure, secrets delivery, logging, and image contents still matter. The goal of secure Dockerized Node.js delivery is to make the build and runtime environment predictable, minimal, least-privileged, observable, and recoverable. Security is not one Dockerfile instruction or one scanner result. It is the lifecycle around how images are built, stored, deployed, run, monitored, and updated.",
  "narrationPoints": [
      "That convenience is real, but it also means the Dockerfile, base image, package-lock.json, environment variables, startup command, and runtime flags are now part of the security design.",
      "A Docker image can reduce environment drift, but it can also preserve vulnerable packages, include secrets by mistake, run with excessive privilege, expose unnecessary ports, or ship development defaults into production.",
      "The goal of secure Dockerized Node.js delivery is to make the build and runtime environment predictable, minimal, least-privileged, observable, and recoverable.",
      "They include the Node.js runtime, npm dependencies, operating system packages, image layers, metadata, startup behavior, and configuration assumptions.",
      "Host configuration, runtime options, orchestrator policy, network exposure, secrets delivery, logging, and image contents still matter.",
      "Containers are isolated, but they are not perfect security boundaries."
  ]
};
