window.COURSE_MODULE = {
  "title": "Secrets, Environment Variables, and Build-Time Exposure",
  "graphicAlt": "Left-to-right security workflow for Secrets, Environment Variables, and Build-Time Exposure in Secure Dockerized Node.js Applications: untrusted input crosses a labeled boundary, a validating component enforces policy, and only a verified result reaches the protected resource.",
  "narration": "Secrets in Dockerized Node.js applications include database credentials, API keys, OAuth client secrets, JWT signing keys, session secrets, webhook secrets, cloud credentials, npm tokens, private keys, and deployment credentials. These values should not be baked into Dockerfiles, committed .env files, image layers, build arguments, frontend bundles, logs, or tickets. If a secret enters the image during build, it may remain recoverable from a layer or build artifact even if a later Dockerfile step deletes it.\n\nBuild-time secrets and runtime secrets have different purposes. A token used to install a private npm package during image build should not appear in the final image. A database password needed by the running application should be delivered securely at runtime through an approved mechanism, such as an orchestrator secret, secret manager, or protected deployment configuration. Environment variables are commonly used for delivery, but they are not a complete secrets management strategy by themselves.\n\nRuntime handling still matters after delivery. Applications should not print secrets during startup, include them in crash output, expose them through debug endpoints, or send them to external logging systems. Containers can also be inspected by tools and platforms with sufficient permission, so access to runtime configuration must be controlled. The safest pattern is to keep secrets out of images, minimize who can read them, limit their privileges, rotate them when needed, and monitor for unexpected use.",
  "narrationPoints": [
      "Secrets in Dockerized Node.js applications include database credentials, API keys, OAuth client secrets, JWT signing keys, session secrets, webhook secrets, cloud credentials, npm tokens, private keys, and deployment credentials.",
      "A database password needed by the running application should be delivered securely at runtime through an approved mechanism, such as an orchestrator secret, secret manager, or protected deployment configuration.",
      "The safest pattern is to keep secrets out of images, minimize who can read them, limit their privileges, rotate them when needed, and monitor for unexpected use.",
      "Build-time secrets and runtime secrets have different purposes.",
      "Applications should not print secrets during startup, include them in crash output, expose them through debug endpoints, or send them to external logging systems.",
      "Environment variables are commonly used for delivery, but they are not a complete secrets management strategy by themselves."
  ]
};
