window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Logging, Monitoring, Privacy, and Retention' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Emit privacy-preserving upload diagnostics",
      "language": "csharp",
      "blurb": "The event admits closed stages, outcomes, and content kinds, validates bounded correlation, byte, and duration evidence, and excludes original filenames, subjects, tenant identifiers, storage keys, hashes, scanner output, and document contents.",
      "code": "public enum UploadStage { Receive, TypeCheck, Scan, Promote, Download }\npublic enum UploadOutcome { Succeeded, Rejected, TimedOut, Failed }\npublic enum UploadKind { Pdf, Png, Unknown }\n\npublic sealed class UploadDiagnosticEvent\n{\n    private UploadDiagnosticEvent(\n        UploadStage stage,\n        UploadOutcome outcome,\n        UploadKind kind,\n        string correlationId,\n        long byteLength,\n        int durationBucketMilliseconds)\n    {\n        Stage = stage;\n        Outcome = outcome;\n        Kind = kind;\n        CorrelationId = correlationId;\n        ByteLength = byteLength;\n        DurationBucketMilliseconds = durationBucketMilliseconds;\n    }\n\n    public UploadStage Stage { get; }\n    public UploadOutcome Outcome { get; }\n    public UploadKind Kind { get; }\n    public string CorrelationId { get; }\n    public long ByteLength { get; }\n    public int DurationBucketMilliseconds { get; }\n\n    public static UploadDiagnosticEvent Create(\n        UploadStage stage,\n        UploadOutcome outcome,\n        UploadKind kind,\n        string correlationId,\n        long byteLength,\n        TimeSpan elapsed)\n    {\n        if (!Enum.IsDefined(stage) || !Enum.IsDefined(outcome) || !Enum.IsDefined(kind) ||\n            !IsIdentifier(correlationId) || byteLength is < 0 or > 20 * 1024 * 1024 ||\n            elapsed < TimeSpan.Zero || elapsed > TimeSpan.FromMinutes(1))\n        {\n            throw new ArgumentException(\"Upload diagnostic rejected.\");\n        }\n        var bucket = elapsed <= TimeSpan.FromMilliseconds(10) ? 10 :\n            elapsed <= TimeSpan.FromMilliseconds(100) ? 100 :\n            elapsed <= TimeSpan.FromSeconds(1) ? 1_000 : 60_000;\n        return new UploadDiagnosticEvent(stage, outcome, kind, correlationId, byteLength, bucket);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length is >= 8 and <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    },
    {
      "title": "Calculate a fixed upload retention decision",
      "language": "csharp",
      "blurb": "The policy requires a UTC upload timestamp in the supported range, applies an application-owned thirty-day retention period, and represents legal hold explicitly as no deletion deadline rather than accepting a caller-selected retention duration.",
      "code": "public sealed class UploadRetentionDecision\n{\n    private UploadRetentionDecision(\n        DateTimeOffset uploadedUtc,\n        bool legalHold,\n        DateTimeOffset? deleteAfterUtc)\n    {\n        UploadedUtc = uploadedUtc;\n        LegalHold = legalHold;\n        DeleteAfterUtc = deleteAfterUtc;\n    }\n\n    public DateTimeOffset UploadedUtc { get; }\n    public bool LegalHold { get; }\n    public DateTimeOffset? DeleteAfterUtc { get; }\n\n    public static UploadRetentionDecision Create(DateTimeOffset uploadedUtc, bool legalHold)\n    {\n        if (uploadedUtc.Offset != TimeSpan.Zero || uploadedUtc.Year is < 2020 or > 2100)\n            throw new ArgumentException(\"Upload timestamp rejected.\", nameof(uploadedUtc));\n        return new UploadRetentionDecision(\n            uploadedUtc,\n            legalHold,\n            legalHold ? null : uploadedUtc.AddDays(30));\n    }\n}\n"
    }
  ]
};
