window.COURSE_MODULE = {
  "title": "Malware Scanning, Quarantine, and Processing Pipelines",
  "graphicAlt": "Bullet summary graphic for Malware Scanning, Quarantine, and Processing Pipelines.",
  "narration": "Malware scanning is one layer in a broader defensive workflow. It can help identify known risky content, but it should not be treated as the only upload control. Limits, storage isolation, file type validation, authorization, least privilege, logging, and safe processing all remain important.\n\nQuarantine is a useful state for files that have been uploaded but are not yet cleared for normal use. A quarantined support attachment, invoice, image, or report may be stored in a restricted location, hidden from normal download paths, and available only to controlled processing or review workflows.\n\nAsynchronous processing is often better when immediate decisions are not safe or practical. The web endpoint can receive the file, assign an internal identifier, store it in a restricted state, and let background workers perform scanning, validation, thumbnailing, import parsing, or review. The user interface can then show pending, accepted, rejected, or needs-review status.\n\nScanner failures and unavailable services need safe behavior. If a scanner times out, returns an inconclusive result, or cannot be reached, the application should not silently promote the file to normal use. The workflow should define retry rules, failure states, operator visibility, and user-facing messages that are clear without exposing sensitive internals.\n\nHigher-risk workflows may need approval or review queues. For example, partner-submitted documents, public-facing content, or files that affect business records may require a human or automated review step before publishing or processing. Review should be tied to file state, ownership, audit records, and access rules.\n\nRecord file state transitions for audit and troubleshooting. Uploaded, quarantined, scanning, cleared, rejected, processed, published, downloaded, deleted, and expired states can all matter. Clear state records help operators understand what happened without relying on file names, storage paths, or scattered logs.",
  "narrationPoints": [
    "Quarantine is a useful state for files that have been uploaded but are not yet cleared for normal use.",
    "The user interface can then show pending, accepted, rejected, or needs-review status.",
    "The workflow should define retry rules, failure states, operator visibility, and user-facing messages that are clear without exposing sensitive internals.",
    "Review should be tied to file state, ownership, audit records, and access rules.",
    "Clear state records help operators understand what happened without relying on file names, storage paths, or scattered logs."
  ]
};
