window.COURSE_MODULE = {
  "title": "Image, Document, and Archive Handling Risks",
  "graphicAlt": "Bullet summary graphic for Image, Document, and Archive Handling Risks.",
  "narration": "Different file categories require different handling rules. Images, PDFs, office documents, CSV files, spreadsheets, archives, logs, and plain text files have different processing needs and different operational risks. A single upload policy rarely fits every workflow well.\n\nImage processing should use maintained libraries, clear limits, and predictable output. Resizing, thumbnail generation, metadata stripping, format conversion, and dimension checks all consume resources and may behave differently across file types. The application should bound CPU, memory, disk, and processing time instead of assuming images are small and simple.\n\nDocument preview, conversion, and indexing are higher-review operations. They often invoke complex parsers or conversion services and may generate derivatives such as previews, text extracts, or searchable metadata. Those derivatives need their own storage, access rules, retention expectations, and failure handling.\n\nArchive handling needs careful limits at a conceptual level. Review file count, extracted size, nesting depth, paths inside the archive, destination storage, and cleanup behavior. The application should decide whether archives are allowed at all and should process them only through a controlled workflow with resource limits.\n\nCSV and spreadsheet uploads are data ingestion workflows, not just file storage. They require schema validation, field-level validation, authorization checks, import previews, error reporting, and rollback or correction plans. A valid-looking spreadsheet can still contain rows the user is not allowed to import or values that do not fit the business process.\n\nDependencies matter. Image libraries, document libraries, archive libraries, compression tools, storage SDKs, scanning integrations, and conversion services should be reviewed for maintenance, configuration, resource controls, and update paths. File processing safety depends heavily on the quality and configuration of the tools that handle the content.",
  "narrationPoints": [
    "Image processing should use maintained libraries, clear limits, and predictable output.",
    "Document preview, conversion, and indexing are higher-review operations.",
    "Review file count, extracted size, nesting depth, paths inside the archive, destination storage, and cleanup behavior.",
    "A valid-looking spreadsheet can still contain rows the user is not allowed to import or values that do not fit the business process.",
    "Image libraries, document libraries, archive libraries, compression tools, storage SDKs, scanning integrations, and conversion services should be reviewed for maintenance, configuration, resource controls, and update paths."
  ]
};
