window.COURSE_MODULE = {
  "title": "Authorization, Ownership, and Secure Downloads",
  "graphicAlt": "Bullet summary graphic for Authorization, Ownership, and Secure Downloads.",
  "narration": "Upload authorization answers who is allowed to submit which file for which purpose. A user may be allowed to upload a profile photo but not attach documents to another account. A partner may submit invoices for one tenant but not reports for another. The upload workflow should enforce purpose, ownership, tenant, and role rules on the server.\n\nObject-level authorization is just as important for downloads. A file has an owner, tenant, case, record, or workflow context. Before serving the file, the application should verify that the current user or service is allowed to access that specific object, not merely that they are logged in or have access to a general feature.\n\nPrivate files and public files need different access rules. A private support attachment should not become public because it shares a storage service with product images. A public product image may be safe to cache and serve broadly, while a private document may require authenticated access, audit records, and short-lived delivery.\n\nAvoid exposing internal storage paths, bucket paths, server file paths, or implementation details to users. Public identifiers, opaque file IDs, or controlled download routes are usually better than leaking how storage is organized. Internal paths can create coupling and reveal operational information even when the file itself is protected.\n\nDownload authorization should happen before content is served. This applies to direct application responses, redirect-style delivery, temporary access links, object storage downloads, previews, thumbnails, and processed derivatives. Derivative files should not bypass the access rules of their source content.\n\nTemporary access links need expiration, revocation expectations, least privilege, and clear scope. Administrative and support access should receive extra scrutiny because those workflows often combine broad visibility with operational urgency. Secure downloads are part of the upload workflow, not a separate afterthought.",
  "narrationPoints": [
    "The upload workflow should enforce purpose, ownership, tenant, and role rules on the server.",
    "Before serving the file, the application should verify that the current user or service is allowed to access that specific object, not merely that they are logged in or have access to a general feature.",
    "A public product image may be safe to cache and serve broadly, while a private document may require authenticated access, audit records, and short-lived delivery.",
    "Avoid exposing internal storage paths, bucket paths, server file paths, or implementation details to users.",
    "Temporary access links need expiration, revocation expectations, least privilege, and clear scope."
  ]
};
