window.COURSE_MODULE = {
  "title": "Logging, Monitoring, Privacy, and Retention",
  "graphicAlt": "Bullet summary graphic for Logging, Monitoring, Privacy, and Retention.",
  "narration": "Security-relevant upload events should be logged intentionally. Accepted files, rejected files, validation failures, scanning results, quarantine transitions, processing failures, downloads, deletes, publication events, and administrative actions can all help operators understand what happened during an investigation.\n\nCorrelation IDs or request identifiers connect related events. A single upload may pass through an ASP.NET Core request, temporary storage, a scan job, a metadata validation step, a thumbnail worker, a database state update, and a later download. Correlation lets the team follow that chain without recording sensitive file contents in logs.\n\nLogs should capture useful metadata without becoming a second copy of the file. File contents, document text, private descriptions, personal data, and sensitive titles should not be written into ordinary logs. Safer metadata may include internal identifiers, sanitized state transitions, size category, file category, user or tenant reference, and processing outcome according to policy.\n\nPrivacy-aware logging matters because file names, document titles, user identifiers, and descriptions can reveal sensitive information. Even when the file content is not logged, metadata can still be private. Log access, retention, exports, and support bundles should be controlled accordingly.\n\nMonitoring should focus on defensive signals: unusual upload sizes, repeated validation failures, unexpected file categories, scanner timeouts, processing errors, download spikes, cleanup failures, and administrative actions. These signals support operations and security review without turning monitoring into an unsafe content store.\n\nRetention and cleanup policies should cover temporary files, quarantined files, rejected files, processed files, public derivatives, private originals, and logs. Cleanup jobs need monitoring too; stale temporary files and forgotten quarantine stores can become long-term privacy and storage problems.",
  "narrationPoints": [
    "A single upload may pass through an ASP.NET Core request, temporary storage, a scan job, a metadata validation step, a thumbnail worker, a database state update, and a later download.",
    "File contents, document text, private descriptions, personal data, and sensitive titles should not be written into ordinary logs.",
    "Log access, retention, exports, and support bundles should be controlled accordingly.",
    "Monitoring should focus on defensive signals: unusual upload sizes, repeated validation failures, unexpected file categories, scanner timeouts, processing errors, download spikes, cleanup failures, and administrative actions.",
    "Cleanup jobs need monitoring too; stale temporary files and forgotten quarantine stores can become long-term privacy and storage problems."
  ]
};
