window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'XML Denial of Service and Resource Limits' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Read a stream under a physical XML byte ceiling",
      "language": "csharp",
      "blurb": "The asynchronous reader validates an application-owned byte limit, requests at most the remaining bytes plus one, honors cancellation, rejects overflow before parsing, and then applies DTD, resolver, entity, and character limits to the owned snapshot.",
      "code": "using System.Buffers;\nusing System.Xml;\nusing System.Xml.Linq;\n\npublic static class BoundedXmlInput\n{\n    public static async Task<XDocument> ParseAsync(\n        Stream input,\n        int maximumBytes,\n        CancellationToken cancellationToken)\n    {\n        ArgumentNullException.ThrowIfNull(input);\n        if (!input.CanRead || maximumBytes is < 1 or > 1024 * 1024)\n            throw new ArgumentException(\"XML stream policy rejected.\");\n        var rented = ArrayPool<byte>.Shared.Rent(Math.Min(maximumBytes + 1, 64 * 1024));\n        try\n        {\n            using var owned = new MemoryStream(Math.Min(maximumBytes, 64 * 1024));\n            while (owned.Length <= maximumBytes)\n            {\n                var remaining = maximumBytes + 1 - checked((int)owned.Length);\n                var count = await input.ReadAsync(\n                    rented.AsMemory(0, Math.Min(rented.Length, remaining)), cancellationToken)\n                    .ConfigureAwait(false);\n                if (count == 0) break;\n                await owned.WriteAsync(rented.AsMemory(0, count), cancellationToken)\n                    .ConfigureAwait(false);\n            }\n            if (owned.Length is 0 || owned.Length > maximumBytes)\n                throw new XmlException(\"XML byte limit exceeded.\");\n            owned.Position = 0;\n            var settings = new XmlReaderSettings\n            {\n                DtdProcessing = DtdProcessing.Prohibit,\n                XmlResolver = null,\n                MaxCharactersInDocument = maximumBytes,\n                MaxCharactersFromEntities = 0,\n                Async = true,\n                CloseInput = false\n            };\n            using var reader = XmlReader.Create(owned, settings);\n            return await XDocument.LoadAsync(reader, LoadOptions.None, cancellationToken)\n                .ConfigureAwait(false);\n        }\n        finally\n        {\n            ArrayPool<byte>.Shared.Return(rented, clearArray: true);\n        }\n    }\n}\n"
    },
    {
      "title": "Bound XML depth and repeated order elements",
      "language": "csharp",
      "blurb": "The parser combines a byte and character ceiling with a manual depth limit and at most one hundred order elements, validates each identifier and amount, and rejects any attribute, namespace, text, or element outside the small contract.",
      "code": "using System.Globalization;\nusing System.Xml;\n\npublic sealed record BatchOrderXml(string Id, long TotalCents);\n\npublic static class OrderBatchXml\n{\n    public static IReadOnlyList<BatchOrderXml> Parse(ReadOnlyMemory<byte> utf8Xml)\n    {\n        if (utf8Xml.Length is 0 or > 64 * 1024) throw new XmlException(\"Order batch size rejected.\");\n        var settings = new XmlReaderSettings\n        {\n            DtdProcessing = DtdProcessing.Prohibit,\n            XmlResolver = null,\n            MaxCharactersInDocument = 64 * 1024,\n            MaxCharactersFromEntities = 0,\n            IgnoreWhitespace = true,\n            CloseInput = true\n        };\n        using var stream = new MemoryStream(utf8Xml.ToArray(), writable: false);\n        using var reader = XmlReader.Create(stream, settings);\n        reader.MoveToContent();\n        if (reader.Name != \"orders\" || reader.NamespaceURI.Length != 0 || reader.HasAttributes)\n            throw new XmlException(\"Order batch root rejected.\");\n        var result = new List<BatchOrderXml>();\n        reader.ReadStartElement(\"orders\");\n        while (reader.MoveToContent() == XmlNodeType.Element)\n        {\n            if (result.Count == 100 || reader.Name != \"order\" || reader.Depth != 1 ||\n                reader.NamespaceURI.Length != 0 || !reader.HasAttributes || reader.AttributeCount != 2)\n            {\n                throw new XmlException(\"Order batch shape rejected.\");\n            }\n            var id = reader.GetAttribute(\"id\");\n            var totalText = reader.GetAttribute(\"totalCents\");\n            if (!IsIdentifier(id) ||\n                !long.TryParse(totalText, NumberStyles.None, CultureInfo.InvariantCulture, out var total) ||\n                total is < 0 or > 100_000_000_000L ||\n                totalText != total.ToString(CultureInfo.InvariantCulture) || !reader.IsEmptyElement)\n            {\n                throw new XmlException(\"Order batch value rejected.\");\n            }\n            result.Add(new BatchOrderXml(id!, total));\n            reader.ReadStartElement(\"order\");\n        }\n        reader.ReadEndElement();\n        if (result.Count == 0 || reader.MoveToContent() != XmlNodeType.None)\n            throw new XmlException(\"Order batch rejected.\");\n        return result.AsReadOnly();\n    }\n\n    private static bool IsIdentifier(string? value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    }
  ]
};
