window.COURSE_MODULE = {
  "title": "XML as a Security Surface",
  "graphicAlt": "Bullet summary graphic for XML as a Security Surface.",
  "narration": "XML is still common in production .NET systems. It appears in APIs, uploaded files, configuration, SOAP and legacy service integrations, document formats, partner exchanges, feeds, identity workflows, and queue-based processing. Even when a new application is mostly JSON-based, XML often remains in the edges of the environment where old systems, vendors, and document workflows connect.\n\nThe security issue is that XML is not just a string format. XML processors can support DTD processing, external references, schema validation, XPath queries, XSLT transformations, digital signatures, namespaces, encodings, and rich error reporting. Those features are useful in the right context, but they also mean XML processing is an application behavior that deserves design review.\n\nThe actual risk depends on several conditions working together. Where did the XML come from. Which parser is used. Which features are enabled. Can the parser read external resources. Can the input influence query expressions, schema locations, or transformation behavior. What happens when parsing fails. What does the application trust after parsing completes. These questions matter more than the file extension.\n\nA practical default is to treat XML from users, partners, vendors, uploads, queues, email, object storage, and external services as untrusted unless there is a strong, verified reason to do otherwise. Signed or authenticated transport may identify a sender, but the document still needs parser controls, structure validation, and business validation before the application relies on it.\n\nA secure XML baseline makes the processing path explicit. It defines parser settings, resource limits, trusted schema sources, safe query patterns, restricted transformation behavior, careful signature handling, safe error handling, and operational logging. The goal is not to fear XML. The goal is to make XML behavior visible, constrained, and reviewable.",
  "narrationPoints": [
    "Even when a new application is mostly JSON-based, XML often remains in the edges of the environment where old systems, vendors, and document workflows connect.",
    "The security issue is that XML is not just a string format.",
    "What does the application trust after parsing completes.",
    "A practical default is to treat XML from users, partners, vendors, uploads, queues, email, object storage, and external services as untrusted unless there is a strong, verified reason to do otherwise.",
    "A secure XML baseline makes the processing path explicit."
  ]
};
