window.COURSE_MODULE = {
  "title": "Safe XML Parsing in .NET",
  "graphicAlt": "Bullet summary graphic for Safe XML Parsing in .NET.",
  "narration": "Safe XML handling starts with the parser decision. In .NET, teams may use XmlReader, XmlDocument, XDocument, serializers, validation APIs, or framework components that parse XML internally. Each choice has different memory behavior, configuration points, and review visibility. A parser that is convenient for a small trusted configuration file may be the wrong shape for a large partner upload.\n\nXmlReader with explicit XmlReaderSettings is often easier to review because the settings travel with the parser construction. The team can see how DTD behavior, resolver behavior, validation, and processing limits are intended to work. That explicitness is valuable in code review, threat modeling, support troubleshooting, and compliance evidence because decisions are documented in code instead of left to uncertain defaults.\n\nStreaming parsers can reduce memory pressure because the application reads the document forward instead of loading the entire structure at once. Streaming is especially useful when XML can be large, when only part of the document is needed, or when the workflow needs to reject input early. It does not remove the need for limits, but it gives the application a better foundation for controlled processing.\n\nXmlDocument and XDocument can still be appropriate for trusted or bounded data, for transformations, or for workflows that need an in-memory document model. The important point is to define the assumptions. How large can the document be. Who supplies it. Are external resources disabled. Does the application validate structure before using values. What happens if the document is unexpected.\n\nFor security-sensitive XML, avoid relying on broad defaults or scattered parser construction. A centralized parsing helper can be useful when it stays small, application-specific, and easy to inspect. The helper should express the baseline choices clearly, and exceptions should be rare, documented, and reviewed. The outcome should be predictable parser behavior rather than a collection of one-off parsing decisions.",
  "narrationPoints": [
    "Each choice has different memory behavior, configuration points, and review visibility.",
    "The team can see how DTD behavior, resolver behavior, validation, and processing limits are intended to work.",
    "Streaming is especially useful when XML can be large, when only part of the document is needed, or when the workflow needs to reject input early.",
    "Does the application validate structure before using values.",
    "For security-sensitive XML, avoid relying on broad defaults or scattered parser construction."
  ]
};
