window.COURSE_MODULE = {
  "title": "Schema Validation and Trusted Contracts",
  "graphicAlt": "Bullet summary graphic for Schema Validation and Trusted Contracts.",
  "narration": "Schema validation helps a .NET application enforce an expected XML contract. It can confirm required elements, data types, order, occurrence rules, and structural expectations before business logic consumes the document. That makes validation useful, especially for partner integrations and file-based workflows where format drift can create operational risk.\n\nThe schema itself is part of the trust boundary. A safe design uses schemas from trusted, controlled sources that the application owner manages or explicitly approves. The application should not accept arbitrary schema locations from an untrusted document and then use those locations to drive validation behavior.\n\nImports, includes, and schema location hints need review. They can be helpful in complex XML ecosystems, but they should not become a path for untrusted input to influence where the application retrieves validation material. Keep schema files versioned, reviewed, and deployed through the same governance path as application configuration or code.\n\nValidation does not replace authorization, authentication, parser configuration, or business rules. A document can be structurally valid and still represent an unauthorized action, an impossible state, a duplicate request, a stale partner version, or a value the business process should reject. Schema validation is one layer, not the final trust decision.\n\nSchema validation errors need safe handling. Detailed messages can expose internal file paths, schema names, source locations, document structure, and sometimes sensitive values. Production responses should be concise, while logs should capture enough safe context for troubleshooting without recording raw sensitive XML or internal implementation detail unnecessarily.\n\nSchema lifecycle matters over time. Teams should know who owns a schema, how versions are introduced, how compatibility is tested, how partner changes are approved, and how old versions are retired. Trusted contracts are not only parser inputs; they are operational agreements that need maintenance.",
  "narrationPoints": [
    "Schema validation helps a .NET application enforce an expected XML contract.",
    "A safe design uses schemas from trusted, controlled sources that the application owner manages or explicitly approves.",
    "Keep schema files versioned, reviewed, and deployed through the same governance path as application configuration or code.",
    "Validation does not replace authorization, authentication, parser configuration, or business rules.",
    "Teams should know who owns a schema, how versions are introduced, how compatibility is tested, how partner changes are approved, and how old versions are retired."
  ]
};
