window.COURSE_MODULE = {
  "title": "Logging, Errors, Uploads, and Production Review",
  "graphicAlt": "Bullet summary graphic for Logging, Errors, Uploads, and Production Review.",
  "narration": "Production XML workflows need operational visibility without exposing the data they process. XML documents can contain credentials, tokens, personal data, partner identifiers, internal routing values, private configuration, or signed business records. Logging and diagnostics should help engineers operate the system without turning logs into a second copy of sensitive data.\n\nUploads need explicit controls. Define size limits, type expectations, storage rules, retention rules, malware scanning where applicable, review workflow, quarantine behavior, and deletion behavior. Do not trust file names, content types, extensions, or metadata by themselves. Treat those values as hints that may be wrong, stale, or supplied by the sender.\n\nLogs should capture safe context such as workflow name, correlation ID, partner or tenant identifier where appropriate, parser result, validation result, file size category, failure category, and processing stage. Avoid routine logging of raw XML, credentials, tokens, private keys, connection strings, local file paths, internal URLs, or full exception details without a redaction review.\n\nDevelopment diagnostics should not silently become production behavior. A verbose parser exception that is useful during development may be inappropriate in a user response or shared log stream. Production behavior should separate user-facing messages, operator logs, secure debug captures, and incident response evidence.\n\nA production review should cover parser settings, DTD behavior, resolver behavior, schema sources, XPath patterns, XSLT settings, signature verification, uploads, logging, monitoring, dependency versions, and incident response. That review should include both successful processing and failure modes.\n\nMonitoring is part of the control system. Repeated parser failures, oversized uploads, validation drift, transformation failures, signature verification failures, and unusual XML volume can all indicate broken integrations or reliability pressure. Safe XML operations depend on signals that engineers can see and act on.",
  "narrationPoints": [
    "Logging and diagnostics should help engineers operate the system without turning logs into a second copy of sensitive data.",
    "Avoid routine logging of raw XML, credentials, tokens, private keys, connection strings, local file paths, internal URLs, or full exception details without a redaction review.",
    "Production behavior should separate user-facing messages, operator logs, secure debug captures, and incident response evidence.",
    "A production review should cover parser settings, DTD behavior, resolver behavior, schema sources, XPath patterns, XSLT settings, signature verification, uploads, logging, monitoring, dependency versions, and incident response.",
    "Repeated parser failures, oversized uploads, validation drift, transformation failures, signature verification failures, and unusual XML volume can all indicate broken integrations or reliability pressure."
  ]
};
