window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Access Control, Auditing, and Incident Readiness' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Authorize one service to retrieve one named secret",
      "language": "csharp",
      "blurb": "The decision requires an authenticated workload, one canonical service and environment claim, a production environment, a canonical requested secret, and an exact secret-specific scope token rather than a broad caller-selected role.",
      "code": "using System.Security.Claims;\n\npublic static class SecretRetrievalAccess\n{\n    public static bool CanRetrieve(ClaimsPrincipal principal, string secretName)\n    {\n        ArgumentNullException.ThrowIfNull(principal);\n        if (principal.Identity?.IsAuthenticated != true || !IsIdentifier(secretName))\n            return false;\n\n        var services = principal.FindAll(\"service_id\").Select(claim => claim.Value).Take(2).ToArray();\n        var environments = principal.FindAll(\"environment\").Select(claim => claim.Value).Take(2).ToArray();\n        var scopes = principal.FindAll(\"scope\").Select(claim => claim.Value).Take(9).ToArray();\n        if (services.Length != 1 || environments.Length != 1 ||\n            !IsIdentifier(services[0]) ||\n            !string.Equals(environments[0], \"production\", StringComparison.Ordinal) ||\n            scopes.Length > 8 || scopes.Any(value => value.Length > 1024))\n        {\n            return false;\n        }\n\n        var requiredScope = \"secret.read:\" + secretName;\n        return scopes\n            .SelectMany(value => value.Split(' ', StringSplitOptions.RemoveEmptyEntries))\n            .Any(value => string.Equals(value, requiredScope, StringComparison.Ordinal));\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    },
    {
      "title": "Prepare an immutable secret-exposure incident plan",
      "language": "csharp",
      "blurb": "The plan factory validates a canonical incident and approval, binds the affected secret version, owns a duplicate-free bounded consumer snapshot, and exposes only operational metadata and fixed next actions without accepting the leaked value.",
      "code": "using System.Collections.ObjectModel;\n\npublic sealed class SecretExposureIncidentPlan\n{\n    private static readonly ReadOnlyCollection<string> FixedActions = Array.AsReadOnly(new[]\n    {\n        \"disable-compromised-version\",\n        \"activate-reviewed-replacement\",\n        \"restart-affected-consumers\",\n        \"review-access-audit\"\n    });\n\n    private readonly ReadOnlyCollection<string> _consumers;\n\n    private SecretExposureIncidentPlan(\n        string incidentId,\n        string approvalId,\n        string secretName,\n        int version,\n        string[] consumers)\n    {\n        IncidentId = incidentId;\n        ApprovalId = approvalId;\n        SecretName = secretName;\n        Version = version;\n        _consumers = Array.AsReadOnly(consumers);\n    }\n\n    public string IncidentId { get; }\n    public string ApprovalId { get; }\n    public string SecretName { get; }\n    public int Version { get; }\n    public IReadOnlyList<string> Consumers => _consumers;\n    public static IReadOnlyList<string> Actions => FixedActions;\n\n    public static SecretExposureIncidentPlan Create(\n        string incidentId,\n        string approvalId,\n        string secretName,\n        int version,\n        IEnumerable<string> consumers)\n    {\n        ArgumentNullException.ThrowIfNull(consumers);\n        if (!IsIdentifier(incidentId) || !IsIdentifier(approvalId) ||\n            !IsIdentifier(secretName) || version is < 1 or > 1_000_000)\n        {\n            throw new ArgumentException(\"Secret incident metadata rejected.\");\n        }\n        var snapshot = consumers.Take(21).ToArray();\n        if (snapshot.Length is < 1 or > 20 || snapshot.Any(value => !IsIdentifier(value)) ||\n            snapshot.Distinct(StringComparer.Ordinal).Count() != snapshot.Length)\n        {\n            throw new ArgumentException(\"Secret incident consumers rejected.\", nameof(consumers));\n        }\n        return new SecretExposureIncidentPlan(\n            incidentId, approvalId, secretName, version, snapshot);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    }
  ]
};
