window.COURSE_MODULE = {
  "title": "Secrets Management Foundations for .NET",
  "graphicAlt": "Bullet summary graphic for Secrets Management Foundations for .NET.",
  "narration": "Secrets are high-risk application dependencies. A .NET application may depend on a value such as ExampleApiKey, ExampleConnectionString, ExampleCertificateName, ExampleSigningKeyName, ExampleWebhookSecret, or ExampleServiceIdentity to reach a database, call an API, sign data, decrypt protected content, publish messages, or authenticate to storage. If that value is exposed or misused, the application can lose control over important trust relationships.\n\nSecrets management belongs to design, development, deployment, and operations. Architects decide which systems need to trust each other. Developers decide how configuration is read. DevOps teams decide how values reach runtime. Operators monitor access and rotate credentials. A secret is not safe because one team handled one step correctly; it is safe when the whole lifecycle is controlled.\n\nSecrets influence database access, API integrations, storage, signing, encryption, messaging, webhooks, service-to-service communication, and operational tooling. They often sit quietly in configuration, but they determine whether a system can read data, modify records, publish messages, or prove identity to another service.\n\nIt is useful to separate configuration values, sensitive configuration, and secrets. Some settings are ordinary behavior. Some are sensitive because they reveal internal design or change security posture. Secrets are values that can directly grant access or prove trust. All three categories deserve clarity, but secrets require the strongest controls.\n\nDurable secrets management connects least privilege, rotation, monitoring, incident response, privacy, and reliability. Least privilege limits what a secret can do. Rotation and revocation reduce exposure over time. Monitoring and auditing show how secrets are used. Incident readiness lets the team respond without guessing during pressure.",
  "narrationPoints": [
    "If that value is exposed or misused, the application can lose control over important trust relationships.",
    "A secret is not safe because one team handled one step correctly; it is safe when the whole lifecycle is controlled.",
    "Secrets influence database access, API integrations, storage, signing, encryption, messaging, webhooks, service-to-service communication, and operational tooling.",
    "Some are sensitive because they reveal internal design or change security posture.",
    "Durable secrets management connects least privilege, rotation, monitoring, incident response, privacy, and reliability."
  ]
};
