window.COURSE_MODULE = {
  "title": "Local Development and Developer Workflows",
  "graphicAlt": "Bullet summary graphic for Local Development and Developer Workflows.",
  "narration": "Local development needs convenience, but it should not depend on production secrets. Developers may need to run an ASP.NET Core app, connect to a local database, exercise an integration, or debug a background worker. Those workflows should use development-scoped credentials and safe sample values rather than production access.\n\n.NET user secrets are useful for local development, especially when a developer needs values outside source-controlled appsettings files. They are not a production secret store. They do not replace a managed secret system, access review, runtime identity, or deployment control. Treat them as a developer convenience with a narrow purpose.\n\nLocal environment variables and local configuration files still require care. They can leak through shell history, terminal screenshots, scripts, logs, or copied project folders. Development values should be clearly separated from production values, and documentation should explain where developers are expected to put local-only settings.\n\nSample projects, demos, training code, and automated tests should use harmless placeholders such as ExampleApiKey, ExampleConnectionString, or ExampleWebhookSecret. Real production secrets should never be required to run examples. Test credentials should be scoped to test systems and easy to rotate or revoke.\n\nDeveloper onboarding and offboarding are part of secret hygiene. New developers should receive access through approved groups or systems, not through copied secrets in chat. Departing developers should lose access through identity and group changes rather than forcing teams to hunt for scattered credentials.\n\nAccidental commits can be reduced through ignore files, review habits, secret scanning, pre-commit checks, clear templates, and team documentation. Prevention works best when the safe path is obvious and the unsafe path is noisy.",
  "narrationPoints": [
    "Developers may need to run an ASP.NET Core app, connect to a local database, exercise an integration, or debug a background worker.",
    ".NET user secrets are useful for local development, especially when a developer needs values outside source-controlled appsettings files.",
    "Local environment variables and local configuration files still require care.",
    "Departing developers should lose access through identity and group changes rather than forcing teams to hunt for scattered credentials.",
    "Prevention works best when the safe path is obvious and the unsafe path is noisy."
  ]
};
