window.COURSE_MODULE = {
  "title": "Secret Stores and Runtime Retrieval",
  "graphicAlt": "Bullet summary graphic for Secret Stores and Runtime Retrieval.",
  "narration": "External secret stores and platform-managed secret systems centralize protection, access control, auditing, and rotation. They give teams a better place to store values than source code, ordinary configuration files, deployment notes, or build logs. The goal is not just to move a secret; the goal is to control its lifecycle.\n\nRuntime identity patterns reduce the need to distribute static credentials. Managed identities, workload identities, service principals, and platform identity features can let a running application prove who it is and request only the secrets it is allowed to use. This keeps the trust relationship closer to the runtime environment and away from copied values.\n\nA .NET application should retrieve secrets without hardcoding values into source code or ordinary appsettings files. Configuration can reference the name of a secret, the logical purpose of a secret, or the provider to use, while the actual value remains in a protected store. For example, the application might reference ExampleSigningKeyName without exposing the signing key itself.\n\nSecret caching needs design. Caching can reduce latency and dependency pressure, but it affects freshness, rotation behavior, and availability. A long cache may keep using an old value after rotation. A short cache may increase dependency on the secret store. The right choice depends on risk, performance, and operational expectations.\n\nFail-safe behavior matters when a required secret is missing or inaccessible. If the application cannot retrieve a required database credential, signing key reference, or integration secret, it should fail clearly rather than silently switching to an unsafe default. Startup validation can confirm required references without printing secret values.\n\nSecret retrieval logic should be centralized and reviewable. Scattered calls to secret stores make it hard to understand access patterns, caching, error handling, and audit expectations. A clear abstraction or configuration layer helps developers use approved patterns consistently.",
  "narrationPoints": [
    "External secret stores and platform-managed secret systems centralize protection, access control, auditing, and rotation.",
    "Configuration can reference the name of a secret, the logical purpose of a secret, or the provider to use, while the actual value remains in a protected store.",
    "Caching can reduce latency and dependency pressure, but it affects freshness, rotation behavior, and availability.",
    "If the application cannot retrieve a required database credential, signing key reference, or integration secret, it should fail clearly rather than silently switching to an unsafe default.",
    "Scattered calls to secret stores make it hard to understand access patterns, caching, error handling, and audit expectations."
  ]
};
