window.COURSE_MODULE = {
  "title": "ORMs, Query Builders, and Stored Procedures",
  "graphicAlt": "ORMs, builders, generated queries and stored procedures preserve known structure and separate values; raw SQL escape hatches and procedure bodies require review.",
  "narration": "Many Go teams use an ORM, a query builder, generated query code, or stored procedures instead of writing every SQL statement by hand. These tools can reduce repetitive string handling and can make safer patterns easier to follow. They are still tools, not guarantees. Developers need to understand how each abstraction separates values from structure and where the abstraction exposes lower-level features.\n\nAn ORM may parameterize common lookups by default, but it may also provide raw query functions for advanced cases. A query builder may keep arguments separate when used normally, but it may also allow custom fragments. Generated query code can make fixed query shapes easy to review, but the generated layer still depends on how query definitions are written and maintained.\n\nThe safest use of these abstractions keeps the same principle as direct database/sql code. Runtime values belong in argument positions. Dynamic structure should come from known options. Raw SQL entry points should be rare, reviewed, and documented so the team understands why the lower-level path was necessary and how values are protected.\n\nStored procedures can centralize database behavior and reduce repeated query logic in application code. They can also hide unsafe string assembly inside the database layer if teams treat them as automatically safe. Review should include the procedure implementation, the permissions used to run it, and the way application values reach it.\n\nThe safest abstraction is the one the team understands well enough to use consistently. Conventions, examples, linting, and code review should guide developers toward the safer path. When a library offers several ways to express a query, the team should document which patterns are preferred and which require extra review.",
  "narrationPoints": [
    "Many Go teams use an ORM, a query builder, generated query code, or stored procedures instead of writing every SQL statement by hand.",
    "An ORM may parameterize common lookups by default, but it may also provide raw query functions for advanced cases.",
    "The safest use of these abstractions keeps the same principle as direct database/sql code.",
    "Stored procedures can centralize database behavior and reduce repeated query logic in application code.",
    "The safest abstraction is the one the team understands well enough to use consistently."
  ]
};
