window.COURSE_MODULE = {
  "title": "Database Permissions and Damage Reduction",
  "graphicAlt": "Runtime, reporting and worker roles have limited database access, while schema migration uses separate elevated credentials as a containment measure.",
  "narration": "Safe query construction is the first line of defense, but it should be paired with damage reduction. Software changes, configuration changes, and unusual feature paths can introduce mistakes later. Least privilege makes those mistakes less costly by limiting what the application account can do inside the database.\n\nA runtime service account should have only the permissions needed for the service's normal work. A read-only reporting endpoint should not use credentials that can modify unrelated tables. A background worker that updates a small set of records should not need broad administrative privileges. When roles match responsibilities, an unsafe query path has fewer opportunities to affect data outside its legitimate scope.\n\nMigration roles, maintenance roles, support roles, analytics roles, and runtime application roles should be separated where practical. The account that creates tables or changes schema should not be the same account used by a public request handler. Production roles should also be distinct from development and test roles, because convenience permissions often grow during local work.\n\nPermissions are not a replacement for parameterized queries or allowlisted structure. They are a containment layer. They also improve operations: unusual permission errors can reveal that a code path is trying to do something outside its expected responsibility. When teams design database permissions intentionally, they create another reviewable boundary around the application.\n\nDamage reduction is most useful when it is documented. Developers should know which role a service uses, which tables it can read or write, and which operational tasks require elevated access. Clear ownership keeps least privilege from becoming a mystery that slows down maintenance.",
  "narrationPoints": [
    "Safe query construction is the first line of defense, but it should be paired with damage reduction.",
    "A runtime service account should have only the permissions needed for the service's normal work.",
    "Migration roles, maintenance roles, support roles, analytics roles, and runtime application roles should be separated where practical.",
    "Permissions are not a replacement for parameterized queries or allowlisted structure.",
    "Damage reduction is most useful when it is documented."
  ]
};
