window.COURSE_MODULE = {
  "title": "Core CSP Directives",
  "graphicAlt": "CSP uses resource-specific rules for scripts, connections, images, styles, frames, and form destinations rather than a single universal allowlist.",
  "narration": "CSP is built from directives, and each directive controls a category of resource or behavior. default-src provides a fallback source policy when a more specific directive is not present. script-src controls script sources and script execution patterns. style-src controls style sheets and style-related behavior. img-src controls image sources. connect-src controls destinations for fetch, XHR, WebSocket, and similar connections. font-src controls font loading.\n\nOther directives address important browser behaviors. frame-src controls where frames can be loaded from. object-src controls plugin-like object resources and is often locked down tightly in modern policies. base-uri restricts where a base element can point, which helps prevent surprising URL resolution behavior. form-action limits where forms can submit. These directives reduce the risk that injected markup or unexpected page behavior can redirect data or load active content from places the application did not intend.\n\nDirective meaning depends on resource type and browser behavior. A source expression that is appropriate for images may be too broad for scripts. A policy that seems strict may still allow behavior through a fallback directive if a specific directive is missing. Teams should read policies as resource-specific rules, not as a single universal allowlist. The safest policies are explicit about high-risk resource types, especially scripts, frames, forms, and object content.",
  "narrationPoints": [
    "CSP is built from directives, and each directive controls a category of resource or behavior. default-src provides a fallback source policy when a more specific directive is not present. script-src controls script sources and script execution patterns. style-src controls style sheets and style-related behavior. img-src controls image sources. connect-src controls destinations for fetch, XHR, WebSocket, and similar connections. font-src controls font loading.",
    "Other directives address important browser behaviors. frame-src controls where frames can be loaded from. object-src controls plugin-like object resources and is often locked down tightly in modern policies. base-uri restricts where a base element can point, which helps prevent surprising URL resolution behavior. form-action limits where forms can submit.",
    "Directive meaning depends on resource type and browser behavior."
  ]
};
