window.COURSE_MODULE = {
  "title": "Script Controls, Nonces, and Hashes",
  "graphicAlt": "A fresh unpredictable response nonce or a hash matching exact trusted content can authorize specific scripts; broad unsafe-inline and unsafe-eval allowances should be reduced.",
  "narration": "Script control is one of the most important parts of CSP because script execution is often the high-impact outcome of browser injection. Inline scripts are risky because injected markup may try to create script execution directly in the page. A policy that allows unsafe-inline weakens CSP protection because it permits inline script execution more broadly. A mature policy usually works toward reducing or eliminating dangerous script allowances rather than adding them permanently for convenience.\n\nNonces and hashes provide ways to allow specific trusted inline scripts. A nonce is a unique value generated for a particular response. The server places that value in the policy and on the trusted script elements for that response. A hash allows specific inline script or style content that matches an expected cryptographic hash. Both approaches require careful implementation. Nonces must be unpredictable and fresh per response. Hashes must match the exact trusted content and be updated when that content changes.\n\nunsafe-eval and broad script source allowlists also deserve caution. Some frameworks or build settings may rely on evaluation-like behavior in development but not in production. strict-dynamic, at a high level, can let trusted nonce-bearing scripts load additional scripts in supported browsers, changing how source allowlists are interpreted. Teams should use well-documented framework guidance, reduce dangerous script allowances over time, and treat script policy as an architecture decision rather than a header pasted in at the end.",
  "narrationPoints": [
    "Script control is one of the most important parts of CSP because script execution is often the high-impact outcome of browser injection.",
    "Nonces and hashes provide ways to allow specific trusted inline scripts.",
    "unsafe-eval and broad script source allowlists also deserve caution."
  ]
};
