window.COURSE_MODULE = {
  "title": "Course Summary and Key Takeaways",
  "graphicAlt": "An intentional CSP program combines secure rendering, report-only observation, policy tightening, enforcement, maintenance, third-party control, and review of frontend changes.",
  "narration": "Content Security Policy helps browsers enforce resource-loading rules and reduce the impact of some injection flaws. It can restrict script sources, style sources, image sources, frames, fonts, connections, form destinations, and other browser behavior. CSP is not a replacement for secure coding. It is most useful when the application already uses output encoding, safe rendering patterns, secure framework practices, dependency management, and careful frontend design.\n\nStrong CSP design usually starts in report-only mode, then moves toward enforcement as the team understands legitimate resource needs. Risky allowances such as unsafe-inline, unsafe-eval, broad wildcards, and unnecessary third-party sources should be reduced over time. Nonces and hashes can support trusted inline content when appropriate. Reporting and monitoring help teams improve policies, understand frontend drift, and catch unexpected resource loads.\n\nThe best CSP programs are maintained, owned, and documented. They treat the policy as part of application architecture rather than a one-time header. Developers review templates and script usage, test important pages, track third-party origins, and update policies as features change. The goal is a browser-enforced boundary that supports the application?s real design while making unexpected code and content harder to run unnoticed.\n\nOperationally, CSP works best when changes are treated like application changes. New scripts, widgets, analytics tools, frame targets, API endpoints, and style patterns should be reviewed before they are added to the policy. That review keeps the header from becoming a broad compatibility list and helps teams preserve the security value they worked to create during rollout.",
  "narrationPoints": [
    "Content Security Policy helps browsers enforce resource-loading rules and reduce the impact of some injection flaws.",
    "Strong CSP design usually starts in report-only mode, then moves toward enforcement as the team understands legitimate resource needs.",
    "The best CSP programs are maintained, owned, and documented.",
    "Operationally, CSP works best when changes are treated like application changes."
  ]
};
