window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "Requires Python 3.10+ and SQLAlchemy 2.x with an appropriate DBAPI driver. These examples apply Authorization-Aware ORM Access with reviewable Python controls.",
  "codeExamples": [
    {
      "title": "Enforce tenant and object authorization in one repository query",
      "language": "python",
      "blurb": "A composition-root builder captures the document model and trusted principal provider so callers supply only a validated document identifier.",
      "code": "from sqlalchemy import select\n\nMAX_IDENTIFIER_LENGTH = 64\n\ndef build_authorized_document_reader(Document, current_authenticated_principal):\n    \"\"\"Called once by the trusted composition root, not per request.\"\"\"\n\n    if not callable(current_authenticated_principal):\n        raise TypeError(\"authenticated-principal provider is required\")\n\n    def authorized_document(session, *, document_id: object):\n        principal = current_authenticated_principal()\n        tenant_id = getattr(principal, \"tenant_id\", None)\n        subject_id = getattr(principal, \"subject_id\", None)\n        if any(\n            type(value) is not str or not 1 <= len(value) <= MAX_IDENTIFIER_LENGTH\n            for value in (tenant_id, subject_id)\n        ):\n            raise PermissionError(\"authenticated principal is invalid\")\n        if type(document_id) is not str or not 1 <= len(document_id) <= MAX_IDENTIFIER_LENGTH:\n            raise ValueError(\"document_id is invalid\")\n\n        statement = select(Document).where(\n            Document.id == document_id,\n            Document.tenant_id == tenant_id,\n            Document.owner_id == subject_id,\n            Document.deleted_at.is_(None),\n        )\n        return session.execute(statement).scalar_one_or_none()\n\n    return authorized_document\n"
    },
    {
      "title": "Scope list queries before pagination",
      "language": "python",
      "blurb": "The trusted principal supplies tenant and subject identifiers, and the membership predicate binds both sides of the relationship to that tenant. The reader fetches one extra project internally, then returns a 50-item page with an explicit continuation signal and cursor.",
      "code": "from dataclasses import dataclass\n\nfrom sqlalchemy import exists, select\n\nMAX_IDENTIFIER_LENGTH = 64\nPROJECT_PAGE_SIZE = 50\n\n@dataclass(frozen=True, slots=True)\nclass ProjectPage:\n    projects: tuple[object, ...]\n    has_more: bool\n    next_after_id: str | None\n\ndef build_visible_projects_reader(Project, Membership, current_authenticated_principal):\n    \"\"\"Called once by the trusted composition root, not per request.\"\"\"\n\n    if not callable(current_authenticated_principal):\n        raise TypeError(\"authenticated-principal provider is required\")\n\n    def visible_projects(session, *, after_id: object = None) -> ProjectPage:\n        principal = current_authenticated_principal()\n        tenant_id = getattr(principal, \"tenant_id\", None)\n        subject_id = getattr(principal, \"subject_id\", None)\n        if any(\n            type(value) is not str or not 1 <= len(value) <= MAX_IDENTIFIER_LENGTH\n            for value in (tenant_id, subject_id)\n        ):\n            raise PermissionError(\"authenticated principal is invalid\")\n        if after_id is not None and (\n            type(after_id) is not str or not 1 <= len(after_id) <= MAX_IDENTIFIER_LENGTH\n        ):\n            raise ValueError(\"after_id is invalid\")\n\n        # Also enforce a composite (tenant_id, project_id) foreign key in the schema.\n        membership_exists = exists().where(\n            Membership.tenant_id == tenant_id,\n            Membership.tenant_id == Project.tenant_id,\n            Membership.project_id == Project.id,\n            Membership.subject_id == subject_id,\n        )\n        statement = (\n            select(Project)\n            .where(Project.tenant_id == tenant_id, membership_exists)\n            .order_by(Project.id)\n            .limit(PROJECT_PAGE_SIZE + 1)\n        )\n        if after_id is not None:\n            statement = statement.where(Project.id > after_id)\n\n        fetched = tuple(session.scalars(statement))\n        projects = fetched[:PROJECT_PAGE_SIZE]\n        has_more = len(fetched) > PROJECT_PAGE_SIZE\n        next_after_id = None\n        if has_more:\n            next_after_id = getattr(projects[-1], \"id\", None)\n            if (\n                type(next_after_id) is not str\n                or not 1 <= len(next_after_id) <= MAX_IDENTIFIER_LENGTH\n            ):\n                raise RuntimeError(\"project identifier invariant was violated\")\n        return ProjectPage(\n            projects=projects,\n            has_more=has_more,\n            next_after_id=next_after_id,\n        )\n\n    return visible_projects\n"
    }
  ]
};
