window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "Requires Python 3.10+ and SQLAlchemy 2.x with an appropriate DBAPI driver. These examples apply Dynamic Filters, Sorting, and Search with reviewable Python controls.",
  "codeExamples": [
    {
      "title": "Map sort choices to model attributes",
      "language": "python",
      "blurb": "A composition-root builder captures the application-owned account model. Request code can supply only a friendly token that maps to one of the reviewed ORDER BY expressions.",
      "code": "from sqlalchemy import asc, desc\n\ndef build_order_expression(Account):\n    \"\"\"Called once by the trusted composition root, not per request.\"\"\"\n\n    choices = {\n        \"name\": asc(Account.display_name),\n        \"-name\": desc(Account.display_name),\n        \"created\": asc(Account.created_at),\n        \"-created\": desc(Account.created_at),\n    }\n\n    def order_expression(requested: object):\n        if type(requested) is not str or not 1 <= len(requested) <= 16:\n            raise ValueError(\"sort field is not supported\")\n        try:\n            return choices[requested]\n        except KeyError:\n            raise ValueError(\"sort field is not supported\") from None\n\n    return order_expression\n"
    },
    {
      "title": "Build filters from an explicit search model",
      "language": "python",
      "blurb": "A trusted builder captures the account model and authenticated-principal provider. The facade requires account:search permission, derives the tenant from that principal, excludes soft-deleted accounts, and executes the uniquely ordered limited statement itself so callers cannot remove its authorization, lifecycle, limit, or ordering controls.",
      "code": "from dataclasses import dataclass\nfrom sqlalchemy import select\n\nALLOWED_STATES = frozenset({\"active\", \"disabled\"})\nACCOUNT_SEARCH_PERMISSION = \"account:search\"\nMAX_IDENTIFIER_LENGTH = 64\nMAX_PERMISSION_COUNT = 128\n\n@dataclass(frozen=True, slots=True)\nclass AccountSearch:\n    state: str | None = None\n    prefix: str | None = None\n\n    def __post_init__(self) -> None:\n        if self.state is not None and (\n            type(self.state) is not str or self.state not in ALLOWED_STATES\n        ):\n            raise ValueError(\"invalid state\")\n        if self.prefix is not None and (\n            type(self.prefix) is not str\n            or not 1 <= len(self.prefix) <= 40\n        ):\n            raise ValueError(\"invalid prefix\")\n\ndef build_account_search(Account, current_authenticated_principal):\n    \"\"\"Called once by the trusted composition root, not per request.\"\"\"\n\n    if not callable(current_authenticated_principal):\n        raise TypeError(\"authenticated-principal provider is required\")\n\n    def search_accounts(session, search: object):\n        if type(search) is not AccountSearch:\n            raise TypeError(\"search must be a validated AccountSearch\")\n\n        principal = current_authenticated_principal()\n        tenant_id = getattr(principal, \"tenant_id\", None)\n        subject_id = getattr(principal, \"subject_id\", None)\n        permissions = getattr(principal, \"permissions\", None)\n        if any(\n            type(value) is not str or not 1 <= len(value) <= MAX_IDENTIFIER_LENGTH\n            for value in (tenant_id, subject_id)\n        ):\n            raise PermissionError(\"authenticated principal is invalid\")\n        if (\n            type(permissions) is not frozenset\n            or len(permissions) > MAX_PERMISSION_COUNT\n            or any(\n                type(permission) is not str\n                or not 1 <= len(permission) <= MAX_IDENTIFIER_LENGTH\n                for permission in permissions\n            )\n            or ACCOUNT_SEARCH_PERMISSION not in permissions\n        ):\n            raise PermissionError(\"account search is not permitted\")\n\n        statement = select(Account).where(\n            Account.tenant_id == tenant_id,\n            Account.deleted_at.is_(None),\n        )\n        if search.state is not None:\n            statement = statement.where(Account.state == search.state)\n        if search.prefix is not None:\n            statement = statement.where(\n                Account.display_name.startswith(search.prefix, autoescape=True)\n            )\n        statement = statement.order_by(Account.display_name, Account.id).limit(100)\n        return tuple(session.scalars(statement))\n\n    return search_accounts\n"
    }
  ]
};
