window.COURSE_MODULE = {
  "title": "Mass Assignment, Serialization, and Data Exposure",
  "graphicAlt": "Boundary map for Mass Assignment, Serialization, and Data Exposure, showing request DTO, authorization-aware repository, ORM session, tenant filter, database, and minimized response model; labeled arrows identify query and object-authorization boundaries and the point where unsafe input or behavior is rejected.",
  "narration": "Mass assignment, also called over-posting, happens when request data is allowed to populate model fields more broadly than intended. A client may submit fields such as role, owner, tenant, price, status, approval flag, or audit metadata that should be controlled by server-side logic. If create or update paths blindly copy request dictionaries into model instances, the application can lose control over sensitive attributes.\n\nThe safest create and update paths use explicit allowlists of writable fields. Read-only fields, derived fields, ownership fields, workflow fields, and administrative fields should be set by trusted server-side logic rather than client input. Different actions may have different writable fields. A profile update, admin edit, account recovery flow, and import job should not automatically share the same field permissions just because they use the same model.\n\nSerialization can expose sensitive data when it mirrors model structure too closely. Generic serializers, debug views, nested relationships, and automatic API responses may return fields the caller does not need or should not see. Response minimization is a security control. Serializers should be designed around use cases, caller permissions, and audience, not only around what fields exist in the database.\n\nNested relationships deserve special attention. Returning a project may accidentally include owner details, billing records, tokens, internal notes, or cross-tenant relationships if serialization is too broad. Create, update, and serialize paths should be intentionally designed and reviewed. The ORM model is not the public contract. It is an internal representation that must be mediated before data crosses a trust boundary.",
  "narrationPoints": [
    "Mass assignment, also called over-posting, happens when request data is allowed to populate model fields more broadly than intended.",
    "The safest create and update paths use explicit allowlists of writable fields.",
    "Serialization can expose sensitive data when it mirrors model structure too closely.",
    "Returning a project may accidentally include owner details, billing records, tokens, internal notes, or cross-tenant relationships if serialization is too broad.",
    "The ORM model is not the public contract.",
    "Nested relationships deserve special attention."
  ]
};
