window.COURSE_MODULE = {
  "title": "Raw SQL, Migrations, and Advanced ORM Features",
  "graphicAlt": "Control-flow diagram for Raw SQL, Migrations, and Advanced ORM Features, showing request DTO, authorization-aware repository, ORM session, tenant filter, database, and minimized response model; labeled arrows identify query and object-authorization boundaries and the point where unsafe input or behavior is rejected.",
  "narration": "ORMs provide raw SQL escape hatches because real applications sometimes need database-specific behavior, complex reporting, performance tuning, or migration support. Raw SQL can be used safely, but it must be reviewed carefully. Values should be parameterized. Dynamic structure should be allowlisted. Authorization filters should not disappear just because the code moved out of a normal query API. Raw SQL is a power tool, not a shortcut around security rules.\n\nStored procedures and database functions deserve the same review. They may centralize useful logic, but they can also build dynamic SQL, bypass application-level assumptions, or run with broader privileges than expected. Teams should know which layer enforces validation, authorization, tenant boundaries, and audit behavior. Moving logic into the database can be appropriate, but it should not make security decisions invisible.\n\nMigrations and schema changes are security-relevant. A migration can add a sensitive field, change a default, loosen a constraint, backfill data incorrectly, remove an index used for isolation, or alter a relationship that authorization depends on. Data migrations can touch large amounts of sensitive data. Migration review should consider integrity, confidentiality, rollback behavior, and whether application code and database schema change together safely.\n\nTransactions, locking concepts, and async ORM usage also require discipline. Related database changes should succeed or fail consistently. Bulk updates and async workflows can bypass ordinary per-object handling or change timing assumptions. Advanced features are not unsafe by definition, but they can bypass ordinary model and query safety assumptions. Review should increase as the feature moves closer to database structure, concurrency, privilege, or broad data movement.",
  "narrationPoints": [
    "ORMs provide raw SQL escape hatches because real applications sometimes need database-specific behavior, complex reporting, performance tuning, or migration support.",
    "Raw SQL is a power tool, not a shortcut around security rules.",
    "Moving logic into the database can be appropriate, but it should not make security decisions invisible.",
    "Related database changes should succeed or fail consistently.",
    "Review should increase as the feature moves closer to database structure, concurrency, privilege, or broad data movement.",
    "Migrations and schema changes are security-relevant."
  ]
};
