window.COURSE_MODULE = {
  "title": "Data Flow, Trust Boundaries, and Untrusted Content",
  "graphicAlt": "Bullet summary graphic for Data Flow, Trust Boundaries, and Untrusted Content.",
  "narration": "Untrusted content enters an ASP.NET Core application through many paths: form fields, route values, query strings, headers, API requests, file imports, CMS authoring tools, support tickets, logs, databases, message queues, and third-party integrations. Some values arrive directly from a browser. Others arrive through a trusted-looking internal system. Either way, the rendering decision still matters when the value is later displayed.\n\nStored content deserves special attention. A product description, profile field, support note, audit message, or imported record may be written today and rendered weeks later in a different page, component, export, or administrative view. Storage does not make content safe. It only changes when and where the rendering decision will happen.\n\nTrust boundaries exist between browser clients, server-side views, APIs, databases, administrators, CMS systems, partner systems, and operational tools. Content can cross those boundaries more than once. A value may begin in a public form, move into a moderation queue, appear in an administrator dashboard, feed an email template, and later surface in a customer-facing page. Each rendering point needs an appropriate decision.\n\nAdministrative screens and internal tools are not exempt. They often display raw operational content, imported records, user messages, or diagnostic details. If an internal tool renders untrusted text as markup, it can put privileged users and high-impact workflows at risk. Internal does not automatically mean safe rendering.\n\nA practical review technique is to map untrusted data flow from entry to rendering. Identify where data enters, where it is stored, how it is transformed, where it is displayed, where it is exported, and which reusable helpers or components are involved. This map helps reviewers find the exact places where output context and encoding decisions happen.\n\nData flow review also improves maintainability. When developers know where content changes trust level or display context, they can choose clearer DTOs, safer view models, approved rendering helpers, and better tests. The result is not only fewer XSS risks, but a codebase that is easier to reason about when rendering behavior changes.",
  "narrationPoints": [
    "Untrusted content enters an ASP.NET Core application through many paths: form fields, route values, query strings, headers, API requests, file imports, CMS authoring tools, support tickets, logs, databases, message queues, and third-party integrations.",
    "Trust boundaries exist between browser clients, server-side views, APIs, databases, administrators, CMS systems, partner systems, and operational tools.",
    "If an internal tool renders untrusted text as markup, it can put privileged users and high-impact workflows at risk.",
    "A practical review technique is to map untrusted data flow from entry to rendering.",
    "When developers know where content changes trust level or display context, they can choose clearer DTOs, safer view models, approved rendering helpers, and better tests."
  ]
};
