window.COURSE_MODULE = {
  "title": "Validation, Sanitization, and Encoding: Different Jobs",
  "graphicAlt": "Bullet summary graphic for Validation, Sanitization, and Encoding: Different Jobs.",
  "narration": "Validation, sanitization, and encoding are related controls, but they do different jobs. Confusing them creates fragile designs. Input validation decides whether data is acceptable for a business purpose. Output encoding prepares data for a specific rendering context. Sanitization transforms rich content by applying an allow-list policy. Each control belongs in a different part of the workflow.\n\nInput validation should answer questions such as: is this field present when required, within the expected length, in an allowed format, within a valid range, and meaningful for the current operation. Validation improves data quality and prevents inappropriate states, but valid business data can still be unsafe if it is rendered in the wrong output context.\n\nOutput encoding is tied to where the data is displayed. Text shown in an HTML body, an attribute, a URL component, a client-side data structure, or another browser-interpreted destination may require different handling. Encoding should happen close to rendering, because the destination context is clearest there.\n\nSanitization is specialized. It is used when the application intentionally permits some markup or rich structure. The sanitizer's job is to allow only approved structures and remove or transform everything else according to policy. Sanitization should be based on mature, reviewed tooling and should not be treated as a universal substitute for context-aware encoding.\n\nCanonicalization and normalization support consistent decisions. Before comparing identifiers, names, paths, or state values, the application may need a consistent representation. That helps validation and authorization decisions, but it still does not replace safe rendering when the value is displayed.\n\nBlocking suspicious input alone is fragile because dangerous interpretation depends on context and because applications reuse content in multiple places. A clear design assigns responsibilities: validate data for business use, store it with known meaning, sanitize only when rich content is intentionally allowed, and encode for the rendering context where the value appears.",
  "narrationPoints": [
    "Validation, sanitization, and encoding are related controls, but they do different jobs.",
    "Input validation should answer questions such as: is this field present when required, within the expected length, in an allowed format, within a valid range, and meaningful for the current operation.",
    "Encoding should happen close to rendering, because the destination context is clearest there.",
    "Sanitization should be based on mature, reviewed tooling and should not be treated as a universal substitute for context-aware encoding.",
    "A clear design assigns responsibilities: validate data for business use, store it with known meaning, sanitize only when rich content is intentionally allowed, and encode for the rendering context where the value appears."
  ]
};
