window.COURSE_MODULE = {
  "title": "Android Architecture for Investigators",
  "graphicAlt": "Blank white placeholder image for module 2, Android Architecture for Investigators.",
  "narration": "At a high level, Android is a mobile operating system built on a Linux foundation. That foundation shapes users, processes, files, permissions, and isolation. Android adds its own application framework, services, security model, device management features, Google services in many deployments, and vendor-specific customization. For investigators, the architecture explains why evidence may be stored in different places and why access can vary by device.\n\nApps operate within a permission and sandboxing model. Each application is generally isolated from other applications, with its own data areas and permissions. This matters because artifacts are often tied to a specific app package, version, account, and permission set. A messaging app, browser, map app, or corporate client may store useful local data, but another app should not normally be able to read that data directly.\n\nStorage is layered. Internal storage can include app-private directories, shared media areas, downloads, documents, caches, system data, and databases. Some devices or environments may also include removable storage. Notifications and logs may contain useful context, but availability depends on Android version, settings, collection method, and whether the data has been overwritten or protected.\n\nGoogle services and original equipment manufacturer customizations add another layer. A device may use Google accounts, backup, cloud sync, Play services, device management, vendor apps, and customized system features. Two Android devices can behave differently even when they appear similar to a user. Version, patch level, vendor configuration, encryption state, and management controls all affect forensic access and interpretation.\n\nThe practical takeaway is that Android artifacts should always be interpreted in architectural context. Ask which app or system component created the data, where it was stored, what permissions or sync features were involved, and whether the version or device vendor changes the expected behavior.",
  "narrationPoints": [
    "At a high level, Android is a mobile operating system built on a Linux foundation. That foundation shapes users, processes, files, permissions, and isolation. Android adds its own application framework, services, security model, device management features, Google services in many deployments, and vendor-specific customization. For investigators, the architecture explains why evidence may be stored in different places and why access can vary by device.",
    "Apps operate within a permission and sandboxing model. Each application is generally isolated from other applications, with its own data areas and permissions. This matters because artifacts are often tied to a specific app package, version, account, and permission set. A messaging app, browser, map app, or corporate client may store useful local data, but another app should not normally be able to read that data directly.",
    "Storage is layered. Internal storage can include app-private directories, shared media areas, downloads, documents, caches, system data, and databases. Some devices or environments may also include removable storage. Notifications and logs may contain useful context, but availability depends on Android version, settings, collection method, and whether the data has been overwritten or protected.",
    "Google services and original equipment manufacturer customizations add another layer. A device may use Google accounts, backup, cloud sync, Play services, device management, vendor apps, and customized system features. Two Android devices can behave differently even when they appear similar to a user. Version, patch level, vendor configuration, encryption state, and management controls all affect forensic access and interpretation.",
    "The practical takeaway is that Android artifacts should always be interpreted in architectural context. Ask which app or system component created the data, where it was stored, what permissions or sync features were involved, and whether the version or device vendor changes the expected behavior."
  ]
};
