window.COURSE_MODULE = {
  "title": "Analysis, Timelines, and Reporting",
  "graphicAlt": "Blank white placeholder image for module 8, Analysis, Timelines, and Reporting.",
  "narration": "Analysis turns artifacts into a defensible explanation. Android activity timelines combine device data, app data, cloud data, messages, media, location, network logs, endpoint telemetry, and witness statements where available. The goal is not to dump every artifact into chronological order. The goal is to show the relevant sequence of events with enough context that another qualified person can understand the reasoning.\n\nTimestamp handling is one of the most important analysis skills. Different artifacts may use different formats, time zones, precision levels, and meanings. A created time, modified time, database insertion time, last accessed time, server time, and sync time may all point to different events. Analysts should normalize carefully and preserve the original values where appropriate.\n\nDeleted data has limits. Some artifacts may remain in databases, caches, thumbnails, backups, or cloud records, while other data may be gone or inaccessible. Investigators should avoid implying that absence proves nonexistence unless the acquisition and artifact behavior support that conclusion. A defensible report explains what the evidence can show and what it cannot show.\n\nTool output must be validated. Forensic tools can parse artifacts differently, omit context, display derived fields, or make assumptions about timestamps and app behavior. Validation can include reviewing source files, comparing multiple artifacts, checking known formats, correlating with external logs, and documenting tool versions and methods. The tool is an aid to analysis, not the authority by itself.\n\nGood reports separate observations from conclusions. An observation might say a record exists in a specific database with a specific timestamp and field value. A conclusion explains what that likely means, with caveats and correlation. Privacy-aware reporting includes relevant evidence, avoids unnecessary personal data, documents methods and assumptions, and states uncertainty plainly.",
  "narrationPoints": [
    "Analysis turns artifacts into a defensible explanation. Android activity timelines combine device data, app data, cloud data, messages, media, location, network logs, endpoint telemetry, and witness statements where available. The goal is not to dump every artifact into chronological order. The goal is to show the relevant sequence of events with enough context that another qualified person can understand the reasoning.",
    "Timestamp handling is one of the most important analysis skills. Different artifacts may use different formats, time zones, precision levels, and meanings. A created time, modified time, database insertion time, last accessed time, server time, and sync time may all point to different events. Analysts should normalize carefully and preserve the original values where appropriate.",
    "Deleted data has limits. Some artifacts may remain in databases, caches, thumbnails, backups, or cloud records, while other data may be gone or inaccessible. Investigators should avoid implying that absence proves nonexistence unless the acquisition and artifact behavior support that conclusion. A defensible report explains what the evidence can show and what it cannot show.",
    "Tool output must be validated. Forensic tools can parse artifacts differently, omit context, display derived fields, or make assumptions about timestamps and app behavior. Validation can include reviewing source files, comparing multiple artifacts, checking known formats, correlating with external logs, and documenting tool versions and methods. The tool is an aid to analysis, not the authority by itself.",
    "Good reports separate observations from conclusions. An observation might say a record exists in a specific database with a specific timestamp and field value. A conclusion explains what that likely means, with caveats and correlation. Privacy-aware reporting includes relevant evidence, avoids unnecessary personal data, documents methods and assumptions, and states uncertainty plainly."
  ]
};
