window.COURSE_MODULE = {
  "title": "Prompting for Code Review",
  "graphicAlt": "A focused prompt combines bounded code, its purpose, trust boundary, and specific concern; observed behavior is separated from hypotheses and downstream uses are verified.",
  "narration": "Good prompts make AI-assisted review more precise. Instead of asking whether a file is secure, ask a focused question: identify external inputs in this handler, check whether this authorization decision protects object ownership, explain how this parser handles malformed input, or list assumptions required for this remediation to be safe. Small sections of code with clear context usually produce better output than broad prompts over an entire project.\n\nA strong review prompt provides the purpose of the code, the relevant framework, the trust boundary, and the specific concern. It can ask the AI to separate confirmed observations from hypotheses, cite the exact code behavior that supports each claim, and state what additional evidence would be needed. This forces the output into a structure the reviewer can test. It also helps prevent vague advice that sounds reasonable but cannot be tied to the application.\n\nPrompting is also part of the review record. Capture important assumptions, decisions, and rejected hypotheses. If the AI suggests a risk that is not valid because of middleware, configuration, or a business rule, document why it was rejected. If it identifies a plausible issue, document the evidence that confirmed it. Avoid prompts that ask for unauthorized testing, exploitation, evasion, or out-of-scope behavior. The review should remain defensive, authorized, and evidence-driven.\n\nA practical numeric review also asks how the value will be used after parsing. A value that is acceptable as text may still be unsafe as an allocation size, loop bound, timeout, offset, or array index. Ask the AI to identify each downstream use, then verify the constraints in code. The safest fix usually validates at the boundary and preserves a typed, range-checked value for later operations instead of reparsing the same string in several places.",
  "narrationPoints": [
    "Good prompts make AI-assisted review more precise.",
    "A strong review prompt provides the purpose of the code, the relevant framework, the trust boundary, and the specific concern.",
    "Prompting is also part of the review record.",
    "A practical numeric review also asks how the value will be used after parsing."
  ]
};
