window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Development Secrets and Local Workflows' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Build a local SQL Server connection string structurally",
      "language": "csharp",
      "blurb": "The development-only builder validates host, database, user, and password bounds, uses DbConnectionStringBuilder to quote values rather than concatenating text, requires encryption, rejects certificate bypass, and disables persistence of credential information.",
      "code": "using System.Data.Common;\n\npublic static class DevelopmentSqlConnectionString\n{\n    public static string Build(\n        string server,\n        string database,\n        string userId,\n        string password)\n    {\n        if (server != \"localhost,1433\" || database != \"orders_dev\" ||\n            !IsIdentifier(userId) || string.IsNullOrEmpty(password) ||\n            password.Length > 256 || password.Contains('\\0', StringComparison.Ordinal))\n        {\n            throw new ArgumentException(\"Development database setting rejected.\");\n        }\n\n        var builder = new DbConnectionStringBuilder\n        {\n            [\"Server\"] = server,\n            [\"Database\"] = database,\n            [\"User ID\"] = userId,\n            [\"Password\"] = password,\n            [\"Encrypt\"] = true,\n            [\"Trust Server Certificate\"] = false,\n            [\"Persist Security Info\"] = false,\n            [\"Connect Timeout\"] = 5\n        };\n        return builder.ConnectionString;\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    },
    {
      "title": "Accept a reference-only local database configuration",
      "language": "csharp",
      "blurb": "The parser requires an exact configuration schema, fixes the development endpoint, validates a versioned user-secrets reference, rejects whole connection strings and raw passwords as unknown fields, and returns immutable nonsecret settings.",
      "code": "using System.Globalization;\n\npublic sealed class LocalDatabaseConfiguration\n{\n    private LocalDatabaseConfiguration(string server, string database, string passwordReference)\n    {\n        Server = server;\n        Database = database;\n        PasswordReference = passwordReference;\n    }\n\n    public string Server { get; }\n    public string Database { get; }\n    public string PasswordReference { get; }\n\n    public static LocalDatabaseConfiguration Parse(\n        IReadOnlyDictionary<string, string?> values)\n    {\n        ArgumentNullException.ThrowIfNull(values);\n        var allowed = new HashSet<string>(StringComparer.Ordinal)\n        {\n            \"Database:Server\", \"Database:Name\", \"Database:PasswordReference\"\n        };\n        if (values.Count != allowed.Count || values.Keys.Any(key => !allowed.Contains(key)))\n            throw new ArgumentException(\"Local database schema rejected.\", nameof(values));\n\n        var server = values[\"Database:Server\"];\n        var database = values[\"Database:Name\"];\n        var reference = values[\"Database:PasswordReference\"];\n        if (server != \"localhost,1433\" || database != \"orders_dev\" || !IsReference(reference))\n            throw new ArgumentException(\"Local database value rejected.\", nameof(values));\n        return new LocalDatabaseConfiguration(server, database, reference!);\n    }\n\n    private static bool IsReference(string? value)\n    {\n        const string prefix = \"user-secrets://orders/\";\n        if (value is null || value.Length > 160 || !value.StartsWith(prefix, StringComparison.Ordinal))\n            return false;\n        var parts = value[prefix.Length..].Split('/', StringSplitOptions.None);\n        return parts.Length == 3 && IsIdentifier(parts[0]) && parts[1] == \"versions\" &&\n               int.TryParse(parts[2], NumberStyles.None, CultureInfo.InvariantCulture, out var version) &&\n               version is >= 1 and <= 1_000_000 &&\n               parts[2] == version.ToString(CultureInfo.InvariantCulture);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        value.Length is >= 3 and <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    }
  ]
};
