window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Rotation, Revocation, Inventory, and Incident Response' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Inventory versioned database credentials without values",
      "language": "csharp",
      "blurb": "The immutable inventory entry validates a fixed database alias, canonical secret name, positive version, owner, and future expiry from a trusted clock, while its schema deliberately has no field for the credential or connection string.",
      "code": "public sealed class DatabaseCredentialInventoryEntry\n{\n    private DatabaseCredentialInventoryEntry(\n        string databaseAlias,\n        string secretName,\n        int version,\n        string owner,\n        DateTimeOffset expiresUtc)\n    {\n        DatabaseAlias = databaseAlias;\n        SecretName = secretName;\n        Version = version;\n        Owner = owner;\n        ExpiresUtc = expiresUtc;\n    }\n\n    public string DatabaseAlias { get; }\n    public string SecretName { get; }\n    public int Version { get; }\n    public string Owner { get; }\n    public DateTimeOffset ExpiresUtc { get; }\n\n    public static DatabaseCredentialInventoryEntry Create(\n        string databaseAlias,\n        string secretName,\n        int version,\n        string owner,\n        DateTimeOffset expiresUtc,\n        TimeProvider clock)\n    {\n        ArgumentNullException.ThrowIfNull(clock);\n        var now = clock.GetUtcNow();\n        if (databaseAlias is not (\"orders-primary\" or \"orders-replica\") ||\n            !IsIdentifier(secretName) || !IsIdentifier(owner) || version is < 1 or > 1_000_000 ||\n            expiresUtc <= now || expiresUtc - now > TimeSpan.FromDays(90))\n        {\n            throw new ArgumentException(\"Credential inventory entry rejected.\");\n        }\n        return new DatabaseCredentialInventoryEntry(\n            databaseAlias, secretName, version, owner, expiresUtc);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    },
    {
      "title": "Plan a monotonic database credential cutover",
      "language": "csharp",
      "blurb": "The closed plan requires one canonical approval, the next exact credential version, a future cutover within seven days, and an old-version revocation after cutover but within a one-hour overlap, preventing rollback metadata and revocation order from being ambiguous.",
      "code": "public sealed class DatabaseCredentialRotationPlan\n{\n    private DatabaseCredentialRotationPlan(\n        int currentVersion,\n        int nextVersion,\n        string approvalId,\n        DateTimeOffset cutoverUtc,\n        DateTimeOffset revokeOldUtc)\n    {\n        CurrentVersion = currentVersion;\n        NextVersion = nextVersion;\n        ApprovalId = approvalId;\n        CutoverUtc = cutoverUtc;\n        RevokeOldUtc = revokeOldUtc;\n    }\n\n    public int CurrentVersion { get; }\n    public int NextVersion { get; }\n    public string ApprovalId { get; }\n    public DateTimeOffset CutoverUtc { get; }\n    public DateTimeOffset RevokeOldUtc { get; }\n\n    public static DatabaseCredentialRotationPlan Create(\n        int currentVersion,\n        int nextVersion,\n        string approvalId,\n        DateTimeOffset cutoverUtc,\n        DateTimeOffset revokeOldUtc,\n        TimeProvider clock)\n    {\n        ArgumentNullException.ThrowIfNull(clock);\n        var now = clock.GetUtcNow();\n        if (currentVersion is < 1 or >= 1_000_000 || nextVersion != currentVersion + 1 ||\n            !IsIdentifier(approvalId) || cutoverUtc <= now || cutoverUtc - now > TimeSpan.FromDays(7) ||\n            revokeOldUtc < cutoverUtc || revokeOldUtc - cutoverUtc > TimeSpan.FromHours(1))\n        {\n            throw new ArgumentException(\"Database credential rotation rejected.\");\n        }\n        return new DatabaseCredentialRotationPlan(\n            currentVersion, nextVersion, approvalId, cutoverUtc, revokeOldUtc);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    }
  ]
};
