window.COURSE_MODULE = {
  "title": "Configuration Sources in .NET and ASP.NET Core",
  "graphicAlt": "Bullet summary graphic for Configuration Sources in .NET and ASP.NET Core.",
  "narration": ".NET and ASP.NET Core use a configuration system that can combine values from multiple sources. Configuration files, environment variables, development user secrets, app platform settings, command-line inputs, and secret stores can all influence runtime behavior depending on how the application is built and hosted.\n\nConnection strings are commonly placed under a ConnectionStrings section and read through configuration APIs. That convention is useful, but it is not a protection mechanism. A value under that section is still only as safe as the source that supplied it, the people and systems that can read it, and the logs and tools that may display it.\n\nDevelopers should understand which source wins when the same key appears in more than one place. Configuration order matters. A value from one source may override a file value, and a deployment setting may override a local default. Review should include the expected source for each environment, not only the key name used in code.\n\nEnvironment-specific configuration should separate development, testing, staging, and production values. The goal is to make it difficult to run a local build against production data, deploy a test connection to production, or copy a shared secret across environments without review.\n\nSample configuration files should use placeholders rather than sensitive values. Onboarding docs, examples, local setup scripts, and checked-in templates should teach the shape of the configuration without publishing usable credentials or internal details.\n\nA secure configuration review asks where the connection string comes from, which source has precedence, who can change that source, where the value may be displayed, and how the application proves it is using the intended environment at runtime.",
  "narrationPoints": [
    ".NET and ASP.NET Core use a configuration system that can combine values from multiple sources.",
    "Connection strings are commonly placed under a ConnectionStrings section and read through configuration APIs.",
    "Review should include the expected source for each environment, not only the key name used in code.",
    "Environment-specific configuration should separate development, testing, staging, and production values.",
    "A secure configuration review asks where the connection string comes from, which source has precedence, who can change that source, where the value may be displayed, and how the application proves it is using the intended environment at runtime."
  ]
};
