window.COURSE_MODULE = {
  "title": "Production Secret Storage and Deployment Platforms",
  "graphicAlt": "Bullet summary graphic for Production Secret Storage and Deployment Platforms.",
  "narration": "Production connection strings should come from controlled runtime configuration, not source code. The exact platform may vary, but the principle is stable: production secrets need access control, ownership, auditability where available, availability planning, rotation support, and response procedures.\n\nCloud secret stores, Azure Key Vault, managed app settings, container secrets, orchestrator secrets, CI/CD protected variables, and platform-specific mechanisms can all play a role. The right choice depends on hosting model, operational maturity, startup requirements, rotation needs, and the teams that own the environment.\n\nAccess to production connection strings should be limited to app identities and operators that need it. Broad read access increases exposure and makes response harder. Platform permissions should be reviewed like application permissions, because the people and workloads that can read secrets can influence production behavior.\n\nDeployment pipelines should inject secrets securely without writing them to artifacts, logs, package output, or build summaries. A pipeline that handles production configuration is part of the trusted system. Its variables, logs, permissions, approvals, and rollback steps all deserve review.\n\nKey Vault references and configuration providers can reduce secret sprawl when configured and governed correctly. They can centralize secret storage and reduce copying, but they still require permission design, availability planning, cache behavior, versioning strategy, and incident response expectations.\n\nSecret storage choices should consider startup behavior, caching, rotation, rollback, and failure modes. If the secret store is temporarily unavailable, teams should understand whether the application starts, fails closed, uses cached configuration, or requires operator action. That behavior should be a design decision rather than a surprise.",
  "narrationPoints": [
    "Production connection strings should come from controlled runtime configuration, not source code.",
    "Cloud secret stores, Azure Key Vault, managed app settings, container secrets, orchestrator secrets, CI/CD protected variables, and platform-specific mechanisms can all play a role.",
    "Deployment pipelines should inject secrets securely without writing them to artifacts, logs, package output, or build summaries.",
    "Key Vault references and configuration providers can reduce secret sprawl when configured and governed correctly.",
    "Secret storage choices should consider startup behavior, caching, rotation, rollback, and failure modes."
  ]
};
