window.COURSE_MODULE = {
  "title": "Least Privilege, Provider Options, and Database Access",
  "graphicAlt": "Bullet summary graphic for Least Privilege, Provider Options, and Database Access.",
  "narration": "A secure connection string strategy includes database authorization, not only secret storage. Protecting a connection string is important, but the permissions behind that connection also determine impact. If a credential is exposed or misused, least privilege limits what it can do.\n\nApplication runtime accounts should have the minimum database permissions needed for normal behavior. A web application that only reads and writes application tables should not casually use an account with broad administrative capability. Reporting, background jobs, runtime operations, migrations, and administration may each need different identities.\n\nMigration credentials may need more privilege than runtime credentials. That does not mean the runtime app should always carry migration privileges. Separating migration, administration, read-only, and runtime identities can make both day-to-day operations and incident response safer.\n\nTenant-aware systems should not rely only on connection string secrecy to protect data boundaries. Tenant filters, row-level controls where appropriate, resource checks, and application authorization should work together. A connection string should not be the only thing separating one tenant's data from another.\n\nProvider options can affect security. Encryption settings, certificate or server trust behavior, integrated authentication mode, pooling, timeout behavior, and application name can all influence confidentiality, reliability, troubleshooting, and audit records. Provider options deserve the same review as credentials.\n\nAvoid disabling certificate validation or using trust settings casually to make connection errors disappear. A temporary connection fix can weaken service identity checks. If a trust setting is needed in a controlled environment, document the scope and keep it out of production paths that require strong validation.\n\nConnection pooling and long-lived application processes may affect credential rotation timing. A rotated password or identity setting may not take effect immediately if existing pooled connections continue. Rotation plans should account for process restarts, pool clearing, deployment waves, and background services.",
  "narrationPoints": [
    "A secure connection string strategy includes database authorization, not only secret storage.",
    "A connection string should not be the only thing separating one tenant's data from another.",
    "Encryption settings, certificate or server trust behavior, integrated authentication mode, pooling, timeout behavior, and application name can all influence confidentiality, reliability, troubleshooting, and audit records.",
    "Avoid disabling certificate validation or using trust settings casually to make connection errors disappear.",
    "Rotation plans should account for process restarts, pool clearing, deployment waves, and background services."
  ]
};
