window.COURSE_MODULE = {
  "title": "Logging, Diagnostics, Exceptions, and Redaction",
  "graphicAlt": "Bullet summary graphic for Logging, Diagnostics, Exceptions, and Redaction.",
  "narration": "Connection strings often leak through operational surfaces rather than through obvious source code. Logs, exception messages, telemetry, distributed traces, crash dumps, SQL diagnostics, health checks, debug pages, configuration dumps, CI output, support screenshots, and ticket attachments all need review.\n\nDo not log full connection strings, passwords, access tokens, shared keys, SAS tokens, credential-bearing URLs, or raw configuration objects. Structured logging can make it easy to record entire objects by accident. Redaction should be deliberate and tested in the places where logs are produced and shipped.\n\nRedaction should preserve enough context for troubleshooting. Operators may need a connection name, provider, environment, safe endpoint label, database role category, or correlation ID. They do not need the credential-bearing value. Good redaction keeps the diagnostic signal while removing the secret.\n\nError messages shown to users or clients should not reveal database hosts, usernames, provider details, internal network structure, or connection configuration. A public error should explain the user-facing problem, while protected logs capture safe operational categories for the support team.\n\nSupport and incident workflows should include secret-redaction expectations. Screenshots, copied terminal output, health check payloads, and support bundles should be reviewed before sharing. A well-meaning support process can expose more than the application itself.\n\nA practical redaction review follows the connection string through the system: configuration load, dependency injection, database provider, exception handling, telemetry, pipeline logs, support tools, and incident records. Each surface should have an answer for what is safe to record.",
  "narrationPoints": [
    "Do not log full connection strings, passwords, access tokens, shared keys, SAS tokens, credential-bearing URLs, or raw configuration objects.",
    "Operators may need a connection name, provider, environment, safe endpoint label, database role category, or correlation ID.",
    "Error messages shown to users or clients should not reveal database hosts, usernames, provider details, internal network structure, or connection configuration.",
    "Screenshots, copied terminal output, health check payloads, and support bundles should be reviewed before sharing.",
    "A practical redaction review follows the connection string through the system: configuration load, dependency injection, database provider, exception handling, telemetry, pipeline logs, support tools, and incident records."
  ]
};
