window.COURSE_MODULE = {
  "title": "Secure Storage and Secret Managers",
  "graphicAlt": "Conceptual visual of a secret manager protecting stored secrets with policy, encryption, audit logs, and versioning.",
  "narration": "Secrets should not be hardcoded into source code or stored in plaintext configuration files that are broadly copied, backed up, and shared. Hardcoded secrets are difficult to rotate, easy to duplicate, and easy to expose through source control, code review, build artifacts, and screenshots. Plaintext configuration may feel convenient, but convenience without lifecycle control creates operational debt.\n\nSecret managers and vaults provide a central place to store, protect, retrieve, audit, and rotate sensitive values. Depending on the environment, this may be a dedicated vault product, a cloud secret manager, a platform key management service, an HSM-backed service, or a managed identity pattern that reduces the need for static secrets. The important idea is that secret access moves from scattered files and informal copying into a controlled service with policy and telemetry.\n\nA useful secret storage system provides encryption at rest, secure transport, access policies, namespacing or project separation, versioning, audit logs, and operational controls. Versioning helps applications roll forward or recover during rotation. Audit logs show who or what accessed a secret and when. Namespaces help separate development, staging, and production so a development workload does not accidentally receive production credentials. Policy controls allow teams to grant read access to a specific workload instead of a broad group.\n\nEncryption is important, but it is not the whole story. A secret encrypted at rest can still be exposed if too many identities can read it. A vault can still become a high-value concentration of risk if ownership is unclear or administrator access is too broad. A backup of the vault may need the same protection as the vault itself. Availability matters too: if applications cannot retrieve required secrets during startup or failover, the storage design can become an outage source.\n\nGood storage design includes ownership. Each secret should have a business or engineering owner, a purpose, an environment, an access policy, and a rotation expectation. Teams should know whether a secret is still needed, which services depend on it, and what procedure replaces it. Without ownership, secrets accumulate like abandoned infrastructure: still powerful, still risky, and no longer understood.\n\nThe practical lesson is that a vault is a foundation, not a finish line. Put secrets in approved protected systems, but also design policies, monitoring, backup, availability, application integration, and rotation around them. A secret manager helps teams control secrets; it does not automatically make every secret safe.",
  "narrationPoints": [
    "Secrets should not be hardcoded or stored in plaintext.",
    "Secret managers centralize storage and policy.",
    "Audit logs and versioning support accountability.",
    "Environment separation reduces blast radius.",
    "Vaults still need ownership and monitoring."
  ]
};
