window.COURSE_MODULE = {
  "title": "Documentation and Case Management",
  "graphicAlt": "Blank placeholder graphic for DFIR documentation and case management",
  "narration": "Documentation is part of the toolkit because DFIR work must be explainable. Case notes should capture actions taken, observations, timestamps, decisions, evidence references, assumptions, and open questions. Notes help analysts keep their own thinking organized, but they also help other responders understand what has already been done. During a long incident, good notes prevent repeated work and reduce the risk of losing important context during shift changes.\n\nAn evidence inventory should identify each item collected, where it came from, who collected it, when it was collected, where it is stored, and how integrity was checked. Chain of custody forms extend that record by documenting transfers, handling, access, and storage. These records matter even when an incident does not become a legal case. They support confidence in the findings and help the organization defend its process.\n\nTimeline templates are also valuable. A useful timeline separates observed facts from analysis and response actions. For example, it should distinguish a suspicious login, an administrator disabling an account, an analyst exporting logs, and a business owner approving recovery. Decision logs capture why key actions were taken, such as isolating a system, delaying a reboot, notifying leadership, or prioritizing one service over another.\n\nReporting templates help turn investigation work into usable communication. A technical appendix may support analysts, while an executive summary may support leadership decisions. Screenshots should be labeled and tied to evidence references. Scripts and procedures should live in version control so the team can track changes, review updates, and know which version was used during a case. Documentation is not paperwork for its own sake; it is how DFIR becomes repeatable and defensible.",
  "narrationPoints": [
    "Documentation is part of the toolkit because DFIR work must be explainable.",
    "An evidence inventory should identify each item collected, where it came from, who collected it, when it was collected, where it is stored,...",
    "Timeline templates are also valuable.",
    "Reporting templates help turn investigation work into usable communication."
  ]
};
