window.COURSE_MODULE = {
  "title": "What Is macOS Forensics?",
  "graphicAlt": "Blank placeholder graphic for macOS forensics overview",
  "narration": "macOS forensics is the preservation and analysis of evidence from Apple desktop and laptop systems. The system may be an employee MacBook, an iMac, a developer workstation, an enterprise-managed device, a virtualized testing system, or an Apple Silicon platform with modern security controls. The forensic goal is to understand what happened, when it happened, what users or systems were involved, and what evidence supports the conclusion.\n\nmacOS investigations often support DFIR, insider investigations, endpoint response, user activity reconstruction, policy investigations, and malware triage. Evidence may exist in user home directories, system and user libraries, unified logs, application data, preferences, launch items, file metadata, quarantine attributes, browser artifacts, endpoint security telemetry, and cloud or identity records. No single source tells the entire story.\n\nAuthorization and careful handling matter because Macs often contain sensitive business records, source code, credentials, personal files, messaging data, browser history, and regulated information. Analysts should work under approved authority, collect only what is needed, preserve it appropriately, and document how evidence was handled. Enterprise management tools may help collection, but they also add their own artifacts and constraints.\n\nEvidence integrity is the foundation. Investigator activity can alter timestamps, create logs, update caches, or change volatile state. Sometimes live response is necessary, especially when a device is remote or encrypted, but actions should be deliberate and recorded. Strong macOS forensics is careful, contextual, and evidence-driven. It avoids overclaiming from isolated artifacts and focuses on defensible conclusions.",
  "narrationPoints": [
    "macOS forensics is the preservation and analysis of evidence from Apple desktop and laptop systems.",
    "macOS investigations often support DFIR, insider investigations, endpoint response, user activity reconstruction, policy investigations, and...",
    "Authorization and careful handling matter because Macs often contain sensitive business records, source code, credentials, personal files,...",
    "Evidence integrity is the foundation."
  ]
};
