window.COURSE_MODULE = {
  "title": "Vulnerability Auditing and Triage",
  "graphicAlt": "Audit findings need reachability, exposure, fix-option, and compatibility review; remediation is tested, and exceptions require ownership and a review date.",
  "narration": "npm audit and similar tools are useful because they compare the dependency tree against known vulnerability advisories. They can show affected packages, severity labels, vulnerable version ranges, and possible upgrade paths. That visibility is important, especially in projects where dependencies change quickly. But an audit report is an input to engineering judgment, not a complete risk decision by itself.\n\nTriage should consider whether the vulnerable package is present in production code, whether the vulnerable function is reachable, whether the package runs only during development, what privilege or data exposure is involved, and whether a fix is available without breaking compatibility. A critical finding in an unreachable development-only tool may be handled differently from a moderate finding in a public request path. Severity labels help prioritize, but they do not replace context.\n\nBlindly running npm audit fix can be risky because automated remediation may change package versions, alter transitive dependencies, or introduce breaking behavior. A safer workflow is to review the proposed change, understand the upgrade path, run tests, compare lockfile movement, and document any accepted risk. When no patch is available, teams may need compensating controls, package replacement, feature isolation, or a tracked exception with an owner and expiration date.",
  "narrationPoints": [
    "npm audit and similar tools are useful because they compare the dependency tree against known vulnerability advisories.",
    "Triage should consider whether the vulnerable package is present in production code, whether the vulnerable function is reachable, whether the package runs only during development, what privilege or data exposure is involved, and whether a fix is available without breaking compatibility.",
    "Blindly running npm audit fix can be risky because automated remediation may change package versions, alter transitive dependencies, or introduce breaking behavior."
  ]
};
