window.COURSE_MODULE = {
  "title": "Enforce Workflow, Concurrency, and Transaction Rules",
  "graphicAlt": "Three panels show a stale browser approval blocked by current rejected server state, repeated requests with one idempotency key producing one persisted result, and two inventory requests producing one success and one conflict through an atomic check and change. Conditional writes, version checks, locks, transactions, and constraints support the required state invariant.",
  "narration": "Security enforcement continues after fields, identity, and permission have been checked. The server also owns workflow and shared-state invariants. A rejected item may no longer be approvable. A benefit may be redeemable only once. Inventory cannot be reserved after another request consumes the final unit. A record displayed in the browser may change before the user's request arrives. Client-side state describes an earlier observation; it cannot enforce current state shared by all callers.\n\nA disabled button after submission does not prevent a script from sending the request twice, two tabs from acting concurrently, or a network retry from repeating the operation. Where safe repetition is required, define idempotency deliberately. An idempotency key can associate retries with one logical operation, but the server must persist and enforce that relationship. For naturally unique events, a database uniqueness constraint may be stronger than an in-memory flag on one server process.\n\nConsider the interval between checking a condition and changing protected state. Code that reads available inventory, confirms a positive count, and later writes a decrement contains a race when another request can change the row between those actions. The check and change may need a transaction, conditional update, lock, optimistic concurrency with a version field, or a database operation that succeeds only while the invariant remains true. The mechanism depends on the data store; application validation alone does not eliminate concurrency.\n\nTransactions group changes that must succeed or fail together, while database constraints protect invariants against every writer. Application services still provide readable policy and meaningful errors. Handle transaction conflicts and constraint violations as expected outcomes rather than assuming an earlier check guaranteed success. The engineering sequence is to authorize the transition, verify authoritative state, and make the protected change atomically whenever concurrent requests could otherwise violate the rule.",
  "narrationPoints": [
    "Server state, not browser state, determines permitted workflow transitions.",
    "Idempotency and uniqueness controls contain duplicate operations.",
    "Checks and protected writes may need atomic execution.",
    "Combine clear application policy with transactions and database invariants."
  ]
};
