window.COURSE_MODULE = {
  "title": "What MCP Security Means",
  "graphicAlt": "Blank course placeholder for module 1.",
  "narration": "Model Context Protocol security is about protecting the integration path between AI applications and the outside systems they can reach. MCP makes it easier for an AI host to connect to tools, resources, prompts, data stores, and services. That usefulness changes the security boundary. A model response is no longer only text on a screen; it may lead to a tool call, a file read, an API request, a ticket update, or another action in a real environment.\n\nAt a high level, an MCP host is the AI application or environment where the user works. An MCP client is the component that speaks to an MCP server. The server exposes tools, resources, or prompts. A tool is an action the system can call. A resource is data the system can read or present. Prompt templates can shape how tasks are framed. Transports carry messages. Downstream systems are the APIs, files, databases, cloud services, and workflow platforms that ultimately provide data or perform work.\n\nMCP security is not only model security. Prompt wording can help guide behavior, but it is not a reliable security boundary. The important controls live across application security, identity, authorization, data protection, tool governance, supply-chain review, logging, monitoring, and operations. A secure design asks what the model can see, what tools it can call, which identity those calls use, what data can move, and what actions can change real systems.\n\nUseful MCP systems must be bounded, authorized, observable, and recoverable. Bounded means tools and resources have clear limits. Authorized means permissions come from policy and identity, not from model confidence. Observable means tool calls, denials, approvals, and resource access can be investigated. Recoverable means high-impact actions have rollback plans and incident response paths. The goal is not to block MCP adoption; it is to make powerful integrations safe enough to operate.",
  "narrationPoints": [
    "Model Context Protocol security is about protecting the integration path between AI applications and the outside systems they can reach.",
    "At a high level, an MCP host is the AI application or environment where the user works.",
    "MCP security is not only model security.",
    "Useful MCP systems must be bounded, authorized, observable, and recoverable."
  ]
};
