window.COURSE_MODULE = {
  "title": "Data Protection and Resource Access",
  "graphicAlt": "Blank course placeholder for module 6.",
  "narration": "MCP systems can move sensitive data through prompts, resources, files, logs, retrieval results, tool responses, and downstream APIs. That makes data protection a first-class design concern. A model context may include customer records, internal documents, code, tickets, telemetry, credentials, regulated information, or personal data. The fact that the data is being used to help the user does not remove the need for access control, minimization, retention limits, and monitoring.\n\nResource access should be governed by application policy and identity, not by model confidence. If a user is not allowed to read a document, the model should not receive that document because it seems useful. Per-user access filtering, tenant isolation, group membership checks, and resource-level permissions should happen before content enters the model context. Cross-user or cross-tenant leakage is a severe failure because the model may summarize, combine, or expose information that never should have been available.\n\nResource provenance helps teams reason about trust. The system should know where content came from, when it was retrieved, which identity accessed it, and whether it is authoritative for the current task. Stale or untrusted resources should not silently drive high-impact actions. Redaction can reduce exposure when full content is unnecessary. Data minimization asks whether the model needs the whole file, a small excerpt, metadata, or a structured result from a server-side query.\n\nSecrets handling deserves special care. Tokens, credentials, private keys, session cookies, and connection strings should not be placed in prompts, tool descriptions, or logs. Local file access should be constrained to intended paths and operations. Cloud resource access should use least privilege and service-side policy. Encryption, retention controls, and logging hygiene matter, but they do not replace authorization. MCP data protection works best when sensitive content is filtered before it reaches the model.",
  "narrationPoints": [
    "MCP systems can move sensitive data through prompts, resources, files, logs, retrieval results, tool responses, and downstream APIs.",
    "Resource access should be governed by application policy and identity, not by model confidence.",
    "Resource provenance helps teams reason about trust.",
    "Secrets handling deserves special care."
  ]
};
