window.COURSE_MODULE = {
  "title": "Memory, Pointers, and Object Lifetime",
  "graphicAlt": "An object can have owner and alias pointers, but its lifetime ends when freed; clearing one pointer does not invalidate every stored alias.",
  "narration": "Memory safety starts with one practical question: what object does this pointer refer to, and how long does that object remain valid. In C, a pointer carries an address, but it does not carry a complete runtime ownership contract. The code and its surrounding conventions must make that contract visible.\n\nStack objects, heap allocations, static storage, and borrowed pointers have different lifetime expectations. Stack objects usually stop being valid when the function returns. Heap allocations remain valid until released. Static storage lasts for the program lifetime. Borrowed pointers may be valid only while another owner preserves the underlying object.\n\nEvery dynamically allocated object should have a clear owner and a clear cleanup path. Ownership can belong to a function, a structure, a module, a caller, or a transfer operation, but it should not be ambiguous. Ambiguity is where leaks, double cleanup, dangling pointers, and invalid access often begin.\n\nInitialize variables and pointers before use. Uninitialized data can carry whatever value happened to be present in storage. That creates unpredictable behavior and makes review harder because the code does not show a reliable starting state. Clear initialization also makes cleanup paths easier to write safely.\n\nAfter memory is freed, avoid continuing to use aliases that still point to the old storage. Setting one pointer to null does not update every copy of that pointer. Code review should look for stored aliases, callbacks, global references, and structures that may retain a pointer beyond the object's lifetime.\n\nAvoid returning pointers to stack-local data because the object will no longer be valid after the function returns. Prefer small scopes, visible ownership comments, and cleanup patterns that make lifetime rules easy to follow. The aim is not decorative documentation; it is making memory ownership clear enough that the next maintainer can preserve it.",
  "narrationPoints": [
    "Memory safety starts with one practical question: what object does this pointer refer to, and how long does that object remain valid.",
    "Stack objects, heap allocations, static storage, and borrowed pointers have different lifetime expectations.",
    "Every dynamically allocated object should have a clear owner and a clear cleanup path.",
    "Initialize variables and pointers before use.",
    "After memory is freed, avoid continuing to use aliases that still point to the old storage."
  ]
};
