window.COURSE_MODULE = {
  "title": "Undefined Behavior and Compiler Assumptions",
  "graphicAlt": "Undefined behavior permits compiler assumptions that can produce differing results; warnings, sanitizers, and review help identify fragile assumptions without proving all code safe.",
  "narration": "Undefined behavior means the C standard does not define what the program must do for a construct or situation. Once code enters undefined behavior, the compiler and platform are not required to preserve the behavior a developer expected from a local test run.\n\nCompiler optimizations can make undefined behavior especially surprising. An optimization may assume that certain invalid states never occur and transform code based on that assumption. A program can appear to work under one compiler, optimization level, or architecture and fail differently under another.\n\nCommon areas to review include out-of-bounds access, invalid pointer use, signed integer overflow, uninitialized reads, invalid shifts, strict aliasing assumptions, and lifetime violations. These are not only academic concerns. They affect whether the compiled program still matches the programmer's intent.\n\nSecurity-sensitive code should avoid relying on undefined, unspecified, or implementation-specific behavior. If behavior depends on compiler flags, platform representation, integer size, byte order, or alignment assumptions, document and test those assumptions rather than letting them remain hidden.\n\nCompiler warnings and sanitizers can help identify undefined behavior, but they do not prove all code is safe. They are part of the review and test strategy. They work best when teams run them regularly, investigate findings, and keep the codebase clean enough that new warnings stand out.\n\nPortability matters when code is built for different compilers, optimization levels, architectures, operating systems, or embedded targets. A secure C baseline treats compiler assumptions as part of the design and release process.",
  "narrationPoints": [
    "Undefined behavior means the C standard does not define what the program must do for a construct or situation.",
    "Compiler optimizations can make undefined behavior especially surprising.",
    "Common areas to review include out-of-bounds access, invalid pointer use, signed integer overflow, uninitialized reads, invalid shifts, strict aliasing assumptions, and lifetime violations.",
    "Security-sensitive code should avoid relying on undefined, unspecified, or implementation-specific behavior.",
    "Compiler warnings and sanitizers can help identify undefined behavior, but they do not prove all code is safe."
  ]
};
