window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Access Control, Retention, and Privacy with reviewable Python controls.",
  "codeExamples": [
    {
      "title": "Authorize access to a log export",
      "language": "python",
      "blurb": "The export service checks a dedicated permission and records only validated opaque identifiers, not exported records, usernames, raw tenant names, or request details.",
      "code": "from dataclasses import dataclass\nfrom datetime import datetime, timezone\nimport re\n\nOPAQUE_ID = re.compile(r\"[A-Za-z0-9][A-Za-z0-9._-]{0,63}\\Z\")\nMAX_EXPORT_SECONDS = 31 * 24 * 60 * 60\n\n@dataclass(frozen=True)\nclass LogExportQuery:\n    tenant_id: str\n    start: datetime\n    end: datetime\n\ndef require_opaque_id(value: object, field_name: str) -> str:\n    if not isinstance(value, str) or OPAQUE_ID.fullmatch(value) is None:\n        raise ValueError(f\"{field_name} must be an opaque bounded identifier\")\n    return value\n\ndef validated_export_query(value: object) -> LogExportQuery:\n    if type(value) is not LogExportQuery:\n        raise TypeError(\"log export query rejected\")\n    tenant_id = require_opaque_id(value.tenant_id, \"tenant_id\")\n    if (\n        type(value.start) is not datetime\n        or type(value.end) is not datetime\n        or value.start.tzinfo is None\n        or value.start.utcoffset() is None\n        or value.end.tzinfo is None\n        or value.end.utcoffset() is None\n    ):\n        raise ValueError(\"timezone-aware export range required\")\n    start = value.start.astimezone(timezone.utc)\n    end = value.end.astimezone(timezone.utc)\n    seconds = (end - start).total_seconds()\n    if not 0 < seconds <= MAX_EXPORT_SECONDS:\n        raise ValueError(\"log export range rejected\")\n    return LogExportQuery(tenant_id=tenant_id, start=start, end=end)\n\ndef export_logs(subject, query, authorizer, exporter, audit):\n    subject_id = require_opaque_id(getattr(subject, \"id\", None), \"subject_id\")\n    approved_query = validated_export_query(query)\n    allows = authorizer.allows\n    create_export = exporter.create\n    record_audit = audit.record\n    if not all(callable(operation) for operation in (allows, create_export, record_audit)):\n        raise TypeError(\"log export adapter contract rejected\")\n    if allows(subject, \"logs:export\", tenant_id=approved_query.tenant_id) is not True:\n        record_audit(\n            \"log_export_denied\",\n            subject_id=subject_id,\n            tenant_id=approved_query.tenant_id,\n        )\n        raise PermissionError(\"log export not permitted\")\n    result = create_export(approved_query, maximum_records=50_000)\n    export_id = require_opaque_id(getattr(result, \"id\", None), \"export_id\")\n    record_audit(\n        \"log_export_created\",\n        subject_id=subject_id,\n        tenant_id=approved_query.tenant_id,\n        export_id=export_id,\n    )\n    return result\n"
    },
    {
      "title": "Select retention by data classification",
      "language": "python",
      "blurb": "A trusted policy maps known event classes to bounded retention; request data cannot choose how long logs persist.",
      "code": "from datetime import timedelta\n\nRETENTION = {\n    \"security_audit\": timedelta(days=365),\n    \"application_error\": timedelta(days=30),\n    \"request_metric\": timedelta(days=14),\n}\n\ndef retention_for(event_class: str) -> timedelta:\n    try:\n        return RETENTION[event_class]\n    except KeyError:\n        raise ValueError(\"unclassified log event\") from None\n"
    }
  ]
};
