window.COURSE_MODULE = {
  "title": "Access Control, Retention, and Privacy",
  "graphicAlt": "Control-flow diagram for Access Control, Retention, and Privacy, showing application event, field allowlist, recursive redactor, structured log sink, restricted viewer, and retention boundary; labeled arrows identify safe telemetry flow and blocked sensitive fields and the point where unsafe input or behavior is rejected.",
  "narration": "Logs are sensitive operational data. Even well-designed logs can reveal system behavior, customer activity, administrative actions, support cases, security signals, internal service names, environment details, and privacy-relevant metadata. Access should be based on role and need. Developers, support staff, security analysts, administrators, auditors, and vendors may need different views, different retention, and different approval paths.\n\nProduction log access deserves special care. Broad access can turn logs into a workaround for data access controls. A person who cannot query production databases directly may still learn sensitive facts from logs if events include too much detail or access is too open. Role-based access, reviewable permissions, just-in-time access, environment separation, and audit trails for log access can reduce that risk while still supporting operations.\n\nRetention policies define how long logs remain useful and how long sensitive operational data continues to exist. Retaining everything forever can increase exposure, cost, and legal complexity. Deleting too quickly can harm incident response, compliance, and reliability analysis. The right retention period depends on business needs, regulatory expectations, investigation timelines, storage cost, and data sensitivity. Lifecycle rules should apply to backups and exports, not just the primary log system.\n\nPrivacy-aware logging uses data minimization before access control has to compensate. It avoids unnecessary personal data, uses safe identifiers where possible, limits vendor and support sharing, and treats exported log bundles as sensitive artifacts. When logs are shared externally, teams should review what is included, redact where appropriate, and understand where the data will be stored. Safe logging does not end when the record leaves the application.",
  "narrationPoints": [
    "Even well-designed logs can reveal system behavior, customer activity, administrative actions, support cases, security signals, internal service names, environment details, and privacy-relevant metadata.",
    "Broad access can turn logs into a workaround for data access controls.",
    "Retaining everything forever can increase exposure, cost, and legal complexity.",
    "The right retention period depends on business needs, regulatory expectations, investigation timelines, storage cost, and data sensitivity.",
    "When logs are shared externally, teams should review what is included, redact where appropriate, and understand where the data will be stored.",
    "Production log access deserves special care."
  ]
};
