window.COURSE_MODULE = {
  "title": "Testing, Monitoring, and Incident Response",
  "graphicAlt": "Operational lifecycle diagram for Testing, Monitoring, and Incident Response, showing application event, field allowlist, recursive redactor, structured log sink, restricted viewer, and retention boundary; labeled arrows identify safe telemetry flow and blocked sensitive fields and the point where unsafe input or behavior is rejected.",
  "narration": "Logging behavior should be tested like other security-relevant behavior. Tests can confirm that important events are emitted, structured fields are present, correlation IDs flow through request handling, and sensitive values do not appear. Redaction tests should cover common secrets, tokens, session identifiers, reset links, connection strings, and representative personal data. Negative tests are valuable because failures, exceptions, and validation errors often produce the messiest logs.\n\nReviewing log samples is practical and revealing. Teams can inspect representative records from authentication, authorization, administrative changes, transactions, background jobs, dependency failures, and exception paths. The review should ask whether the event is useful, whether fields are consistent, whether sensitive data is minimized, and whether a responder could investigate without requiring full payloads. Secrets scanning of logs and artifacts can help at a high level, but it should complement good design rather than replace it.\n\nMonitoring turns logs into action. Alerts can watch for unusual authentication patterns, repeated authorization failures, unexpected administrative activity, transaction anomalies, dependency failure spikes, high error rates, or signs that redaction failed. Good monitoring is tuned to reduce noise while surfacing events that deserve attention. The same structured fields that make logs searchable also make alerting more reliable.\n\nIf sensitive data appears in logs, treat it as potentially exposed. Assess what was logged, where it was stored, who could access it, how long it was retained, and whether it was exported. Rotate or revoke secrets when appropriate, restrict or remove affected records where feasible, preserve evidence needed for investigation, fix the logging path, and add regression tests. Logging safety must evolve as code, dependencies, infrastructure, and observability pipelines change.",
  "narrationPoints": [
    "Logging behavior should be tested like other security-relevant behavior.",
    "Redaction tests should cover common secrets, tokens, session identifiers, reset links, connection strings, and representative personal data.",
    "Teams can inspect representative records from authentication, authorization, administrative changes, transactions, background jobs, dependency failures, and exception paths.",
    "If sensitive data appears in logs, treat it as potentially exposed.",
    "Logging safety must evolve as code, dependencies, infrastructure, and observability pipelines change.",
    "Monitoring turns logs into action."
  ]
};
