window.COURSE_MODULE = {
  "title": "What Post-Quantum Cryptography Means",
  "graphicAlt": "Instructional illustration for What Post-Quantum Cryptography Means.",
  "narration": "Post-quantum cryptography is cryptography designed to remain safe against attacks from both ordinary classical computers and cryptographically relevant quantum computers. The phrase can sound exotic, but the practical idea is straightforward. Organizations depend on public-key cryptography to protect sessions, authenticate systems, verify software, and establish trust across networks. Post-quantum cryptography is about preparing those trust mechanisms for a future where some older public-key assumptions may no longer be strong enough.\n\nA common misunderstanding is that post-quantum algorithms require quantum computers to run. They do not. These algorithms run on normal servers, laptops, phones, appliances, and embedded devices. The quantum part is about the attacker model, not the hardware used by the defender. That makes PQC a migration topic for ordinary engineering teams: libraries must be updated, protocols must negotiate new algorithms, certificates may change, and systems need to keep working while the transition happens.\n\nIt also helps to separate similar terms. Quantum computing is a computing model that may eventually threaten some current public-key schemes. Quantum cryptography is a broad phrase that can mean several things. Quantum key distribution uses quantum communication channels and specialized equipment to detect certain kinds of interception. Post-quantum cryptography is different: it uses mathematical algorithms intended to run on classical systems while resisting attacks from future quantum-capable adversaries.\n\nThe reason this belongs in security planning is that cryptography is woven into infrastructure. It is not only a math choice buried in a library. It affects encryption, key establishment, digital signatures, identity, software supply chains, remote access, certificates, and vendor products. The right mental model is migration and risk management. Teams need to understand where cryptography is used, what role it plays, how long protected data must remain confidential, and how to change systems without creating outages or weaker security.",
  "narrationPoints": [
    "Post-quantum cryptography is cryptography designed to remain safe against attacks from both ordinary classical computers and cryptographically...",
    "A common misunderstanding is that post-quantum algorithms require quantum computers to run.",
    "It also helps to separate similar terms.",
    "The reason this belongs in security planning is that cryptography is woven into infrastructure."
  ]
};
