window.COURSE_MODULE = {
  "title": "Why Current Public-Key Cryptography Is at Risk",
  "graphicAlt": "Instructional illustration for Why Current Public-Key Cryptography Is at Risk.",
  "narration": "Public-key cryptography lets systems that have never shared a secret still communicate securely or verify identity. At a high level, one key can be public while a related private key remains protected. That pattern supports key establishment, signatures, certificates, remote administration, secure browsing, software updates, and many other services. It is one of the reasons modern networks can scale trust beyond a single closed environment.\n\nSeveral widely deployed public-key approaches depend on mathematical problems that are believed to be difficult for classical computers at appropriate key sizes. RSA, finite-field Diffie-Hellman, elliptic-curve Diffie-Hellman, and ECDSA are examples practitioners see in certificates, TLS, VPNs, SSH, code signing, and identity systems. The main quantum concern is that sufficiently capable quantum computers could make some of these underlying problems much easier to solve than they are today.\n\nThat risk does not affect every cryptographic function in the same way. Symmetric encryption and hashing are still important, and they are also considered in quantum risk discussions, but the practical concern is different. Strong symmetric algorithms can often be addressed with key-size and configuration choices. Public-key migration is harder because it touches protocols, trust stores, certificates, interoperability, hardware, vendors, and long-lived operational assumptions.\n\nThe planning urgency comes partly from harvest-now, decrypt-later risk. An attacker may copy encrypted traffic or stored data today and try to decrypt it later if stronger capabilities become available. That matters most when confidentiality must last for many years, such as sensitive personal information, government data, intellectual property, regulated records, or strategic business material. Migration should begin before emergency pressure arrives, because discovering cryptography, coordinating vendors, testing replacements, and updating dependent systems can take a long time.",
  "narrationPoints": [
    "Public-key cryptography lets systems that have never shared a secret still communicate securely or verify identity.",
    "Several widely deployed public-key approaches depend on mathematical problems that are believed to be difficult for classical computers at...",
    "That risk does not affect every cryptographic function in the same way.",
    "The planning urgency comes partly from harvest-now, decrypt-later risk."
  ]
};
