window.COURSE_MODULE = {
  "title": "Concurrency and Iterator Stability",
  "graphicAlt": "Concurrency diagram showing a mutex-protected shared vector copied to a snapshot before iterators traverse it without concurrent mutation or retained shared references.",
  "narration": "Iterator validity and thread safety are related concerns, but they are not the same concern. A container can provide valid iterators in single-threaded code and still be unsafe when another thread mutates the container during traversal. The iterator may have been valid at the start of the loop and become invalid because concurrent code changed the underlying range.\n\nShared ownership does not automatically solve this problem. A shared pointer to a container can keep the container object alive, but it does not by itself synchronize access to the container's elements or internal structure. Safe concurrent traversal requires an explicit synchronization strategy, immutable snapshots, message passing, or another design that controls mutation.\n\nAsync callbacks and worker tasks deserve special attention. They may capture iterators, references, views, or spans and use them after the owning component has moved on. Shutdown and cancellation paths are especially risky because containers may be cleared while deferred work is still queued or running.\n\nDefensive code documents the concurrency rule near the data structure. It should be clear who may read, who may mutate, what lock or ownership rule applies, and whether iterators can be retained across callbacks or thread boundaries. Hidden concurrency assumptions are hard to test and harder to debug.\n\nWhen in doubt, prefer designs that shorten iterator lifetime. Complete traversal while the synchronization rule is active, copy the data needed by the worker, or pass stable identifiers that can be validated when work executes.",
  "narrationPoints": [
    "A container can provide valid iterators in single-threaded code and still be unsafe when another thread mutates the container during traversal.",
    "A shared pointer to a container can keep the container object alive, but it does not by itself synchronize access to the container's elements or internal structure.",
    "Safe concurrent traversal requires an explicit synchronization strategy, immutable snapshots, message passing, or another design that controls mutation.",
    "Shutdown and cancellation paths are especially risky because containers may be cleared while deferred work is still queued or running.",
    "Hidden concurrency assumptions are hard to test and harder to debug.",
    "Complete traversal while the synchronization rule is active, copy the data needed by the worker, or pass stable identifiers that can be validated when work executes."
  ]
};
