window.COURSE_MODULE = {
  "title": "What Is Cloud Incident Response?",
  "graphicAlt": "Blank placeholder graphic for module 1",
  "narration": "Cloud incident response is the organized process for detecting, analyzing, containing, recovering from, and learning from security incidents in cloud environments. It uses the same discipline as traditional incident response, but the evidence, control points, and recovery actions often look different. A responder may need to understand identities, policies, API activity, storage permissions, network controls, serverless functions, managed services, and SaaS integrations rather than only host images and network packets.\n\nTraditional incident response often starts with a compromised endpoint or server. Cloud incidents may start with a suspicious login, a new access key, an unexpected policy change, an exposed storage bucket, abnormal data transfer, or automated resource creation. The control plane matters because many important actions happen through provider APIs. A single identity with excessive permissions can change infrastructure, read data, create resources, and alter logging if safeguards are weak.\n\nCloud environments are also highly distributed. A single business application may use several accounts, subscriptions, projects, regions, storage services, queues, databases, identity providers, and third-party integrations. Incident responders need to scope the incident across those boundaries without making assumptions. The first alert may be only one symptom of a broader identity or configuration issue.\n\nGood response work is authorized, documented, and evidence-preserving. Responders should know who approved the work, what systems are in scope, what actions were taken, and what evidence was collected. The goal is not only to stop immediate harm. The goal is to understand what happened, protect affected data and systems, restore trust, and support legal, privacy, compliance, and business decisions with defensible facts.\n\nCloud incident response is therefore both technical and operational. It requires preparation, visibility, clear roles, careful containment, communication, and follow-through. A fast reaction that destroys evidence or causes avoidable outages can create new problems. A strong response balances urgency with control.",
  "narrationPoints": [
    "Cloud incident response is the organized process for detecting, analyzing, containing, recovering from, and learning from security incidents i...",
    "Traditional incident response often starts with a compromised endpoint or server.",
    "Cloud environments are also highly distributed.",
    "Good response work is authorized, documented, and evidence-preserving.",
    "Cloud incident response is therefore both technical and operational."
  ]
};
