window.COURSE_MODULE = {
  "title": "Identity and Access Incidents",
  "graphicAlt": "Blank placeholder graphic for module 5",
  "narration": "Identity is often the first containment priority in cloud incidents because cloud control is heavily identity-driven. A compromised user account, service account, automation identity, token, or access key may allow changes across many services. If the identity has broad permissions, the incident can expand quickly into data access, configuration changes, resource creation, logging changes, or lateral movement across environments.\n\nResponders should review recent identity activity, including logins, source context, MFA behavior, privilege changes, role assumptions, key creation, token use, group membership changes, and access to sensitive resources. The goal is to determine whether the identity was used in a way that matches normal behavior, an approved automation path, or suspicious activity. The same evidence also informs containment scope.\n\nContainment may include disabling or restricting affected identities, rotating credentials, revoking sessions where supported, removing unauthorized keys, tightening policies, or temporarily limiting high-risk permissions. These actions should be documented and coordinated because identity changes can interrupt production services, automation, deployments, or integrations. The safest containment is specific enough to stop misuse without causing unnecessary outages.\n\nLeaked access keys deserve urgent attention because they may allow API access from outside normal user sessions depending on permissions. Emergency credential rotation should be paired with evidence review. If a key is deleted before its use is understood, responders may lose context about what systems depended on it and what activity occurred. The answer is not to delay containment forever, but to preserve what can be preserved before major changes when practical.\n\nRecovery should move toward least privilege. After the immediate incident, review why the identity had the permissions it had, whether MFA coverage was sufficient, whether service accounts were overbroad, and whether detection covered key creation and privilege changes. Identity incidents are often symptoms of deeper access governance gaps.",
  "narrationPoints": [
    "Identity is often the first containment priority in cloud incidents because cloud control is heavily identity-driven.",
    "Responders should review recent identity activity, including logins, source context, MFA behavior, privilege changes, role assumptions, key cr...",
    "Containment may include disabling or restricting affected identities, rotating credentials, revoking sessions where supported, removing unauth...",
    "Leaked access keys deserve urgent attention because they may allow API access from outside normal user sessions depending on permissions.",
    "Recovery should move toward least privilege."
  ]
};
