window.COURSE_MODULE = {
  "title": "Workloads, Storage, and Network Incidents",
  "graphicAlt": "Blank placeholder graphic for module 6",
  "narration": "Cloud incidents can involve virtual machines, containers, serverless functions, managed services, object storage, snapshots, firewall rules, security groups, routing, and data flows. The response approach depends on the affected service and evidence available. A compromised virtual machine offers different evidence and containment options than an exposed storage bucket or suspicious serverless function update.\n\nWorkload response should preserve evidence before destructive actions when practical. Snapshotting disks, capturing metadata, recording configuration, preserving relevant logs, and documenting network controls can allow later analysis while containment and recovery proceed. Quarantine patterns may include restricting network access, moving a workload into an isolated security group, detaching risky permissions, or replacing the workload from trusted infrastructure-as-code.\n\nStorage incidents often involve exposure or unexpected access. Exposed object storage, public snapshots, broadly shared files, or unexpected data transfer require careful scoping. Responders need to identify what data was accessible, when exposure began, who or what accessed it, whether logs are available, and what business, privacy, legal, or customer notification questions may follow.\n\nNetwork incidents may appear as suspicious outbound traffic, unexpected firewall changes, exposed management ports, or unusual connectivity between services. Cloud network controls are highly programmable, so configuration history matters. A rule may have been changed manually, through automation, or as part of an infrastructure deployment. Understanding the change path helps prevent recurrence.\n\nCloud-native containment should avoid destroying evidence or creating unnecessary outages. Sometimes isolation is better than termination. Sometimes rebuilding from known-good infrastructure is safer than trying to clean a running workload. The right choice depends on business criticality, evidence needs, data sensitivity, and the confidence responders have in the affected resource.",
  "narrationPoints": [
    "Cloud incidents can involve virtual machines, containers, serverless functions, managed services, object storage, snapshots, firewall rules, s...",
    "Workload response should preserve evidence before destructive actions when practical.",
    "Storage incidents often involve exposure or unexpected access.",
    "Network incidents may appear as suspicious outbound traffic, unexpected firewall changes, exposed management ports, or unusual connectivity be...",
    "Cloud-native containment should avoid destroying evidence or creating unnecessary outages."
  ]
};
