window.COURSE_MODULE = {
  "title": "Intelligence Requirements and Collection Discipline",
  "graphicAlt": "Conceptual visual of intelligence requirements narrowing collection to decision-relevant information.",
  "narration": "Good coordination starts with a clear intelligence requirement. A requirement states the decision to be supported, the audience, the timeframe, and the information needed to answer the question. It turns a broad topic into a focused analytic task. Without a clear requirement, teams can collect too much, share too widely, or confuse interesting information with necessary information.\n\nFor example, a requirement might ask whether a supplier risk indicator affects currently used vendors, whether a fraud pattern is appearing across business units, or whether a cyber threat report is relevant to the organization's exposed services. Each requirement implies a different audience, data need, and urgency. A technical operations team may need actionable indicators and affected assets. Executives may need risk, impact, confidence, and decisions required. Legal or privacy reviewers may need source, authority, retention, and handling detail.\n\nCollection discipline means gathering only what is authorized, relevant, proportionate, and useful for the decision. It does not mean collecting every available log, every identity record, every partner note, or every personal identifier just in case. More data can increase privacy risk, make sharing harder, create retention burdens, and dilute analytic focus. The safest intelligence product often answers the decision question without exposing raw sensitive material.\n\nMinimization begins at the requirements stage. If the decision can be supported with aggregated counts, sanitized case summaries, pseudonymous identifiers, or a narrow time window, the team should not default to full raw datasets. If a partner only needs a trend, do not send names. If an operational team only needs affected systems, do not include unrelated personal details. If legal review is needed before using a data source, the requirement should name that condition.\n\nA strong requirement is also reviewable. It records assumptions, scope limits, data sources, expected output, caveats, and owner. If the question changes, the requirement should be updated rather than silently expanding collection. That discipline keeps intelligence work aligned with authority, privacy, and decision support.",
  "narrationPoints": [
    "Intelligence requirements connect work to decisions.",
    "Clear requirements reduce overcollection.",
    "Collection should be authorized and relevant.",
    "Timeframe and audience shape the analytic product.",
    "Minimization starts before collection begins."
  ]
};
