window.COURSE_MODULE = {
  "title": "A JWT Is Not Trusted Because It Can Be Decoded",
  "graphicAlt": "A signed JWT has readable encoded header and payload sections. Decoding is blocked from directly creating trusted context. The accepted path verifies protection, validates claims, creates context, and makes a separate authorization decision before access.",
  "narration": "A JSON Web Token carries claims that another system may use to make security decisions. For an Express API, receiving readable claims is only the beginning of processing. A JWT becomes trustworthy only after the application verifies its cryptographic protection and validates every claim required by the application's token policy. Decoding alone establishes nothing.\n\nAn ordinary signed JWT commonly uses the compact JSON Web Signature format, or JWS. Its protected header, claims payload, and cryptographic signature are separated by dots. The header and payload use base64url encoding. This makes them transportable, not confidential. Anyone holding the token can normally read those sections. Do not put passwords, private keys, API credentials, or unnecessary sensitive personal data into claims.\n\nThe deliberately unsafe example decodes a token and immediately assigns the result to the request's user context. A decoder can parse client-supplied JSON without proving who protected it or whether it belongs at this API. A familiar subject or role field does not change that. Do not use parsed claims to grant access, even temporarily, while verification is still pending.\n\nDefine a complete processing boundary. Extract one token from the expected transport and enforce size and basic format limits. Use a mature library to verify cryptographic protection with trusted keys under a server-defined algorithm policy. Validate issuer, audience, time restrictions, token purpose, and required application claims. Only then construct an authenticated context. Authorization is a subsequent decision about the requested operation and resource.\n\nEncrypted JWTs use a different mechanism, JSON Web Encryption, or JWE. Encryption can provide confidentiality within a properly designed protocol, but it does not remove claim validation or other required cryptographic checks. This course focuses on signed access tokens. Their integrity supports authentication; encoding alone provides neither authentication nor secrecy.",
  "narrationPoints": [
    "Decoding parses input; it does not authenticate a request.",
    "Ordinary signed JWT claims are encoded, not encrypted.",
    "Verify protection and required claims before creating context.",
    "Perform application authorization separately."
  ]
};
