window.COURSE_MODULE = {
  "title": "Verify Signatures with an Explicit Algorithm Policy",
  "graphicAlt": "Server configuration defines allowed algorithms. An HMAC shared secret can sign and verify; asymmetric signing uses the issuer's private key while an API verifies with a public key. Unsigned tokens are rejected.",
  "narration": "Cryptographic verification establishes that the protected token content matches the expected key and algorithm. Use a maintained JOSE or JWT library for this operation. Application code should configure policy and handle results, not implement signature parsing, cryptographic primitives, or compatibility workarounds.\n\nSymmetric protection, such as an HMAC, uses a shared secret to create and verify the authentication code. Every verifier holding that secret can also create tokens, so distribution expands signing authority. Use strong generated key material and restricted custody, not a memorable password. Asymmetric signing separates a private signing key from public verification keys. APIs can verify signatures without receiving the authority to issue tokens.\n\nThe verifier decides which algorithms are acceptable. The token does not get to expand that policy. Configure a narrow allowlist appropriate to the issuer and key material, and ensure the selected key type matches the expected algorithm family. Do not mix symmetric and asymmetric models simply to accommodate whatever arrives. Reject unsigned tokens at a boundary that requires authenticated access.\n\nThe JOSE header is untrusted input before verification. Its algorithm, key identifier, and type fields can guide controlled processing, but they do not independently establish trust. A library may inspect those fields to select an allowed operation and candidate key. The server still owns the accepted algorithm set, key source, and token profile. Reject unsupported critical header requirements rather than silently ignoring them.\n\nThe conceptual example allows one algorithm for a configured issuer. Its exact API syntax varies by library, and algorithm selection is only one part of the full verifier. Review library documentation and secure defaults, keep dependencies maintained, and test rejection of disallowed algorithms and incompatible key types. A successful signature check must flow into claim validation; it must never become an automatic permission to enter every protected route.",
  "narrationPoints": [
    "The server owns the algorithm allowlist.",
    "Match issuer policy, algorithm family, and key type.",
    "Shared verification secrets also confer signing authority.",
    "Use maintained libraries and reject unsupported requirements."
  ]
};
