window.COURSE_MODULE = {
  "title": "Validate Issuer, Audience, Time, and Token Purpose",
  "graphicAlt": "An access token passes required issuer, audience, time, and purpose checks. Expiration is required and not-before respected; issued-at is not expiration and a JWT identifier alone is not replay defense. A refresh token is rejected at the access-token API boundary.",
  "narration": "A valid signature can protect a token that this API must reject. The issuer claim, called iss, identifies the issuing authority. Configure the exact issuer values trusted at this boundary and bind each issuer to its verification keys. Finding any key that verifies a token does not make its issuer acceptable.\n\nThe audience claim, aud, identifies intended recipients. Require the audience designated for this API. The JWT format permits a single audience string or an array; use the library's documented matching behavior against explicit configured values. A token issued for another service must not pass merely because the same identity provider signed it. Avoid substring matching or a policy that accepts every audience.\n\nTime policy needs both presence checks and value checks. Require expiration for access tokens and reject them when expired. Respect the not-before claim when present, and require it if your profile depends on it. JWT NumericDate values use seconds since the Unix epoch, unlike JavaScript timestamps in milliseconds. Let the library validate these values and apply only a small, justified clock tolerance. Fix clock synchronization instead of hiding problems with broad leeway.\n\nIssued at, or iat, records issuance time and can support maximum-age policy; it does not replace expiration. Subject, or sub, identifies a principal according to the issuer's contract. Require the subject when constructing user identity. The JWT identifier, jti, can identify a token but does not automatically prevent replay. Rejecting repeat use requires an additional protocol or server-side mechanism.\n\nToken purpose is another boundary. Access, refresh, email-verification, password-recovery, and service tokens must have distinct acceptance rules. An identity token intended for a client is not automatically an API access token. Use the issuer's documented profile, including audience, explicit type, or a dedicated purpose claim as appropriate. Validate the combination, not an isolated label, before trusting application-specific claims.",
  "narrationPoints": [
    "Require the intended issuer and API audience.",
    "Check required claim presence as well as values.",
    "Expiration, not-before, and issued-at have different roles.",
    "Token purpose and jti require deliberate application policy."
  ]
};
