window.COURSE_MODULE = {
  "title": "Course Summary: Verify, Validate, Then Authorize",
  "graphicAlt": "Server policy requires trusted keys and required claims before creating narrow context. Authorization is a separate gate. A decoded-payload shortcut stops before context. Protected transport, lifecycle planning, and failure testing support the whole design.",
  "narration": "Treat JWT handling as a security boundary with an explicit acceptance policy. A readable payload is merely decoded input. Base64url encoding is not encryption, and a successful signature check is not complete token validation. The verifier must use trusted key material and enforce the algorithm family configured for the issuer.\n\nIssuer and audience answer different questions: who issued the assertion, and which recipient should accept it. Validate both. Require expiration for access tokens, respect not-before restrictions, and use only justified clock tolerance. Issued-at records issuance time rather than expiry. A JWT identifier can support tracking, but its presence alone does not prevent replay.\n\nKeep token purposes distinct. Access tokens belong at their intended APIs; refresh tokens belong in the refresh flow with stronger lifecycle controls. Other signed token classes must meet their own acceptance rules. Key selection is also constrained: token-provided identifiers can select candidates within trusted configuration, never establish a new key source or trigger arbitrary retrieval.\n\nIn Express, verify first, validate required runtime claim shapes and meanings, and then create the minimum authenticated context. TypeScript types do not perform those checks. Authentication precedes object, tenant, scope, role, ownership, and business authorization. Decide how fresh authorization state must be for each operation instead of assuming signed claims remain current indefinitely.\n\nOperational controls complete the design. Protect browser storage and transport according to the threat model, keep credentials out of telemetry, and plan refresh, key rotation, revocation, and dependency failures. Local logout is not automatic invalidation of all issued tokens. Test rejected tokens and denied access alongside successful requests.\n\nTrust a JWT only after the server has verified who protected it, confirmed that it was issued for this application and purpose, established that it is currently valid, and translated its claims into the minimum authenticated context needed for a separate authorization decision.",
  "narrationPoints": [
    "Decode, verify, validate, and authorize are distinct steps.",
    "Trust comes from server policy and authenticated key sources.",
    "Runtime validation produces a narrow authenticated context.",
    "Plan token freshness, protected transport, and revocation."
  ]
};
