window.COURSE_MODULE = {
  "title": "Why Environment Variable Security Matters",
  "graphicAlt": "Trust-boundary diagram with a parent process and deployment platform feeding environment strings into a C++ process, followed by validation before configuration reaches sensitive subsystems.",
  "narration": "Environment variables are a common way to configure C++ programs without changing source code, command-line arguments, or configuration files. They can control file paths, logging levels, debug behavior, network endpoints, feature flags, credentials, library behavior, temporary directories, and deployment-specific settings. That convenience makes them useful, but it also makes them easy to overtrust.\n\nA program should not treat environment variables as trusted constants. They are inputs. They may come from a shell, service manager, container platform, CI runner, parent process, installer, or deployment system. Some sources are tightly controlled; others may be easier to influence than the application expects. The code should not assume that a value is safe just because it arrived through the process environment.\n\nUnsafe values can weaken security controls or reliability decisions. A path can point somewhere unexpected. A debug flag can increase sensitive logging. A feature flag can change validation behavior. A secret can appear in places where the team did not intend it to appear. Environment variables can also be inherited by child processes, extending their influence beyond the current program.\n\nSecure environment handling means clear policy, centralized loading, typed validation, safe defaults, secret protection, controlled inheritance, and review. The goal is practical: make environment-dependent behavior visible, predictable, and testable before it becomes production surprise.\n\nFor C++ teams, the important habit is to put environment use on the same engineering path as other external input. If a value can change security posture, file access, network behavior, diagnostics, or authentication, it deserves an owner, a validation rule, a documented default, and a test that proves the intended behavior.",
  "narrationPoints": [
    "Environment variables are a common way to configure C++ programs without changing source code, command-line arguments, or configuration files.",
    "The code should not assume that a value is safe just because it arrived through the process environment.",
    "Unsafe values can weaken security controls or reliability decisions.",
    "Secure environment handling means clear policy, centralized loading, typed validation, safe defaults, secret protection, controlled inheritance, and review.",
    "If a value can change security posture, file access, network behavior, diagnostics, or authentication, it deserves an owner, a validation rule, a documented default, and a test that proves the intended behavior.",
    "For C++ teams, the important habit is to put environment use on the same engineering path as other external input."
  ]
};
