window.COURSE_MODULE = {
  "title": "Process Environment and Trust Boundaries",
  "graphicAlt": "Process tree showing a supervisor launching an application with inherited variables, overridden deployment values, and a highlighted boundary where untrusted launch context enters the child.",
  "narration": "A process environment usually comes from whatever launched the program. That might be an interactive shell, a service manager, a container runtime, a CI runner, a scheduled task, an installer, a parent process, or a deployment platform. The trust level of each value depends on who controls that launch path and how changes are approved.\n\nThis matters because environment variables can look like internal configuration even when they are supplied from outside the application. A value injected by a protected deployment system may deserve different trust than one inherited from an interactive shell. A service account may receive a carefully curated environment, while a local developer run may include many unrelated values.\n\nChild processes add another boundary. Unless the program constructs a controlled environment, a child may inherit values from its parent. That can accidentally pass configuration, secrets, search paths, debug flags, or library options to tools that were never meant to receive them. Inheritance should be a deliberate choice rather than a default assumption.\n\nSecurity-sensitive applications should document which environment variables are allowed, where they are expected to come from, and which sources are trusted enough to affect behavior. That documentation helps code review, operations, and incident response because the team can reason about environment influence as a visible contract.\n\nA useful review question is, \"who could set this value before the process starts?\" The answer may be a developer, a service operator, a container manifest, a CI job, or another executable. Once the owner is clear, the team can decide whether the value needs stricter validation, approval, or sanitization.",
  "narrationPoints": [
    "The trust level of each value depends on who controls that launch path and how changes are approved.",
    "A value injected by a protected deployment system may deserve different trust than one inherited from an interactive shell.",
    "Inheritance should be a deliberate choice rather than a default assumption.",
    "Security-sensitive applications should document which environment variables are allowed, where they are expected to come from, and which sources are trusted enough to affect behavior.",
    "A useful review question is, \"who could set this value before the process starts?\" The answer may be a developer, a service operator, a container.",
    "Once the owner is clear, the team can decide whether the value needs stricter validation, approval, or sanitization."
  ]
};
