window.COURSE_MODULE = {
  "title": "Testing, Logging, and Operational Governance",
  "graphicAlt": "Audit-event diagram showing deployment label, policy version, and acceptance status flowing to operations while token and password values remain outside the event schema.",
  "narration": "Environment-driven behavior should be tested directly. Tests should cover missing variables, malformed values, empty strings, invalid booleans, out-of-range numbers, unsafe paths, conflicting settings, secret redaction, and production versus development behavior. A codebase that only tests the default environment can miss failures that appear immediately during deployment.\n\nLogging should help diagnose configuration problems without printing sensitive values. It is useful to report that a required variable is missing, that a value failed validation, or that a fallback was selected. It is not safe to dump the full environment or echo secret variables into broad logs, crash reports, or CI artifacts.\n\nCI systems need special attention because they often contain environment variables used for credentials, deployment, or signing. Build scripts should avoid echoing secret values, and test artifacts should not capture process environments by default. Secret redaction should be verified, not assumed.\n\nCode review should include environment contract changes. Adding a new environment variable can alter application security behavior, deployment requirements, and operational procedures. Reviewers should ask who controls the value, how it is validated, whether it is sensitive, whether it reaches child processes, and how operators will know what value is active.\n\nGovernance does not need to be heavy, but it should be consistent. Track environment variables in documentation, configuration schemas, deployment manifests, and runbooks. When a value changes meaning, becomes sensitive, or starts affecting a new process boundary, treat that as a visible change that deserves review and tests.",
  "narrationPoints": [
    "Tests should cover missing variables, malformed values, empty strings, invalid booleans, out-of-range numbers, unsafe paths, conflicting settings, secret redaction, and production versus development behavior.",
    "Logging should help diagnose configuration problems without printing sensitive values.",
    "Build scripts should avoid echoing secret values, and test artifacts should not capture process environments by default.",
    "Adding a new environment variable can alter application security behavior, deployment requirements, and operational procedures.",
    "When a value changes meaning, becomes sensitive, or starts affecting a new process boundary, treat that as a visible change that deserves review and tests.",
    "Governance does not need to be heavy, but it should be consistent."
  ]
};
