window.COURSE_MODULE = {
  "title": "What Harvest Now, Decrypt Later Means",
  "graphicAlt": "Blank course placeholder for module 1.",
  "narration": "Harvest-now, decrypt-later is a defensive threat model for long-term confidentiality. The idea is that an adversary may collect encrypted data today, store it, and wait for a future point when decryption becomes easier or feasible. The attacker may not be able to read the data now. The risk exists because the data may still be sensitive later, while cryptanalytic techniques, computing capability, implementation knowledge, or available tooling may improve over time.\n\nThis is different from immediate compromise. In an immediate compromise, the protected information is exposed now because an account, system, key, application, or protocol fails in the present. In harvest-now, decrypt-later planning, the concern is future exposure of data that seemed protected at the time it was collected. That distinction matters because it changes how teams think about retention, data lifetime, cryptographic choices, and migration timing.\n\nFuture quantum computing is one reason this model receives attention, especially for data protected by public-key cryptography that may be considered vulnerable to cryptographically relevant quantum capabilities. Quantum computing is not the only possible source of future risk, and responsible planning should avoid countdowns or panic. The practical question is simpler: if encrypted information is copied today, how long must it remain confidential, and what assumptions protect it?\n\nThis course treats harvest-now, decrypt-later as a defensive planning topic. The goal is not to intercept traffic, steal data, or attempt unauthorized decryption. The goal is to help security, engineering, legal, privacy, operations, and leadership teams identify long-lived sensitive information, understand how cryptography protects it, and reduce future confidentiality risk before emergency migration becomes necessary.",
  "narrationPoints": [
    "Harvest-now, decrypt-later is a defensive threat model for long-term confidentiality.",
    "This is different from immediate compromise.",
    "Future quantum computing is one reason this model receives attention, especially for data protected by public-key cryptography that may be con...",
    "This course treats harvest-now, decrypt-later as a defensive planning topic."
  ]
};
