window.COURSE_MODULE = {
  "title": "Mitigation and Migration Strategies",
  "graphicAlt": "Blank course placeholder for module 7.",
  "narration": "Mitigation should be risk-based, tested, and operationally realistic. Post-quantum cryptography is one part of the response, especially for public-key cryptographic roles that may be vulnerable in the future. But PQC adoption should be standards-based and implemented through mature libraries and supported protocols. Teams should avoid custom cryptography, unsupported algorithm choices, and private protocol designs, because unreviewed mechanisms can create new risk while trying to solve future risk.\n\nCrypto agility is another key mitigation. A crypto-agile system can change algorithms, keys, libraries, or protocols without redesigning the whole architecture. That requires configuration discipline, versioned dependencies, clear ownership, test environments, rollback plans, and monitoring. Hybrid cryptography may also appear during transition periods, conceptually combining classical and post-quantum mechanisms. Hybrid approaches still require standards-aware implementation, compatibility testing, and governance.\n\nData lifecycle management can reduce exposure. If sensitive data is not retained unnecessarily, it cannot be harvested from that location for long-term future exposure. Retention review, minimization, segmentation, access control, secure deletion processes, and archive governance all contribute. Key rotation may help in some contexts, but teams should understand what rotation does and does not protect. Changing keys does not automatically erase risk from traffic or data already captured under older assumptions.\n\nPractical migration uses pilots and staged deployment. Teams can start with lower-risk systems, test interoperability, measure performance, review logging, coordinate with vendors, and document results. Vendor readiness tracking is important because many cryptographic dependencies live in cloud services, products, libraries, appliances, and platforms outside direct control. The best mitigation program combines cryptographic migration with data minimization, operational testing, and clear decision records.",
  "narrationPoints": [
    "Mitigation should be risk-based, tested, and operationally realistic.",
    "Crypto agility is another key mitigation.",
    "Data lifecycle management can reduce exposure.",
    "Practical migration uses pilots and staged deployment."
  ]
};
