window.COURSE_MODULE = {
  "title": "What an Incident Response Playbook Is",
  "graphicAlt": "Conceptual visual of an incident response playbook guiding a SOC team through repeatable actions, decisions, evidence, and escalation paths.",
  "narration": "An incident response playbook is a practical, repeatable guide for handling a specific class of security incident. It gives responders a shared starting point when an alert, report, or external notification needs coordinated action. A good playbook does not try to describe every possible variation. It describes the expected workflow, the important decisions, the evidence to collect, the people to involve, and the safest ways to move from triage through containment, recovery, and improvement.\n\nIt helps to separate a playbook from related documents. A policy states the organization's expectations. An incident response plan defines the overall program, authority, lifecycle, escalation model, and responsibilities. A procedure may describe a required process in detail. A runbook often tells an operator how to perform a repeatable technical task, such as disabling an account or collecting logs. A checklist gives a compact reminder of items to verify. Analyst notes capture what happened during one investigation. A playbook sits between strategy and execution. It connects the incident response plan to a scenario, such as phishing, suspicious login, malware infection, exposed cloud key, or data exposure.\n\nPlaybooks reduce confusion because incidents happen under pressure. During a real event, responders may be dealing with incomplete facts, conflicting priorities, noisy alerts, worried business owners, and time-sensitive containment choices. Without a shared guide, teams can duplicate work, miss evidence, notify the wrong people, or take a containment action before understanding the impact. A playbook gives the team a common language and a sequence of questions: what triggered the response, what is known, what is unknown, how severe is it, who owns the affected systems, what evidence is needed, and what action is authorized next.\n\nAt the same time, a playbook is not a substitute for trained responders. Incidents are messy. The facts may not fit the first assumption. A phishing report may reveal credential misuse. A malware alert may turn into a broader endpoint issue. A cloud key exposure may involve development tooling, external repositories, and production access. Responders still need judgment, communication skills, and technical understanding. The playbook supports that judgment by making routine steps visible and by forcing important decisions to be explicit.\n\nThe best playbooks are operational documents. They are written for the people who will use them during a shift, not for a binder that nobody opens. They use clear triggers, concrete roles, known data sources, practical containment options, and closure criteria. They are tested in tabletop exercises and real operations. They are updated when tools, teams, systems, or lessons learned change. In short, an incident response playbook helps a team respond consistently without pretending that every incident can be solved by a script.",
  "narrationPoints": [
    "Playbooks guide specific incident scenarios.",
    "They translate plans into repeatable actions.",
    "They reduce confusion during pressure.",
    "They preserve room for responder judgment.",
    "They differ from policies, runbooks, and notes."
  ]
};
