window.COURSE_MODULE = {
  "title": "Communications, Coordination, and Escalation",
  "graphicAlt": "Coordination map linking SOC, IT, identity, cloud, legal, privacy, communications, business owners, executives, and external stakeholders.",
  "narration": "Technically strong response work can still fail operationally if communication is poor. Incidents affect systems, people, business services, legal obligations, privacy expectations, customer trust, and executive decision-making. A playbook should define communication and coordination rules before the team is under pressure.\n\nInternal coordination often includes the SOC, IT operations, endpoint teams, identity teams, cloud teams, network teams, application owners, legal, privacy, HR, communications, business owners, and executives. Not every incident needs every group, but the playbook should explain when to involve them. A suspicious login for a single user may start with the SOC and identity team. A possible data exposure may require privacy and legal review. A ransomware event may require IT operations, business continuity, communications, executives, and possibly external partners.\n\nExternal coordination must be handled carefully. Vendors may provide logs, product support, or managed service assistance. Customers may need updates if their service is affected. Insurers may have notification requirements. Regulators may have reporting timelines. Law enforcement or government partners may be appropriate in some circumstances. The playbook should not make every responder responsible for external statements. It should identify who is authorized to coordinate outside the organization and when escalation is required.\n\nGood playbook communication rules answer four questions: who updates whom, when, through which channel, and with what level of detail. A technical channel may be appropriate for responder coordination. A ticket or case record may be the official system of record. Executive updates should be concise and focused on impact, current status, decisions needed, and next update time. Legal or privacy discussions may require restricted channels. Sensitive evidence should not be posted broadly.\n\nResponders should avoid speculation. It is acceptable to say that something is under investigation, suspected, confirmed, contained, recovered, or unresolved. It is risky to guess about root cause, impact, attribution, or data exposure before evidence supports the statement. Stakeholders need clarity, not confident uncertainty. A playbook can help by providing status language and update templates that separate facts from assumptions.\n\nEscalation is not a sign of failure. It is how the organization brings the right authority to the right decision. Some containment actions may affect production services. Some notifications may have legal consequences. Some recovery choices may require business risk acceptance. A playbook should identify severity thresholds, escalation contacts, backup contacts, and decision owners. When communication is planned, responders can focus on the incident instead of inventing coordination paths in the middle of it.",
  "narrationPoints": [
    "Communication failures can break response.",
    "Many teams may need coordination.",
    "External stakeholders require care.",
    "Updates need audience and channel rules.",
    "Responders should avoid speculation."
  ]
};
