window.COURSE_MODULE = {
  "title": "Performance, Reliability, and Concurrency",
  "graphicAlt": "Concurrent logging architecture showing bounded producer queues, one synchronized sink, backpressure and drop accounting, safe shutdown, allocation limits, and separation between application progress and unavailable telemetry.",
  "narration": "Logging is production code, and production code has performance and reliability consequences. A log call can allocate memory, format strings, acquire locks, write to disk, send data to an agent, or block behind a slow sink.\n\nSynchronous logging is simple to reason about, but it can add latency or stall work if the destination is slow. Asynchronous logging can reduce direct latency, but it introduces queues, buffering, shutdown behavior, and backpressure decisions that must be designed.\n\nRepeated errors can create log storms. A tight loop that logs every failure, a noisy retry path, or many threads reporting the same condition can consume CPU, disk, network bandwidth, and operator attention. Rate limiting, aggregation, and sampling may be appropriate.\n\nThread safety matters in C++ logging libraries and wrappers. Shared sinks, formatter state, buffers, and locks need clear ownership and concurrency behavior. Lock contention in a hot path can become a performance problem even when each individual log call looks small.\n\nPlan for unavailable log sinks. The application should define whether to drop logs, buffer temporarily, apply backpressure, switch to a fallback destination, or fail closed for special audit-sensitive paths. The policy should be intentional and documented.\n\nLogging failures should not corrupt application state. If a log write fails, the error-handling path should preserve invariants and avoid recursive logging loops. Monitoring should make logging health visible without causing another burst of events.\n\nExcessive logging can weaken availability and make important events harder to find. Safe logging balances detail, cost, and signal so operators receive useful information when the system is healthy and when it is under pressure.\n\nPerformance review should include both the call site and the pipeline. Formatting work in a hot path, queue growth in an async logger, collector delays, and storage quotas can all affect production behavior.\n\nConcurrency review should include shutdown. Threads may still be writing events while buffers flush or sinks close. A safe design defines ordering, ownership, and what happens to queued records during controlled shutdown.",
  "narrationPoints": [
    "Logging is production code, and production code has performance and reliability consequences.",
    "A tight loop that logs every failure, a noisy retry path, or many threads reporting the same condition can consume CPU, disk, network bandwidth, and operator attention.",
    "Shared sinks, formatter state, buffers, and locks need clear ownership and concurrency behavior.",
    "If a log write fails, the error-handling path should preserve invariants and avoid recursive logging loops.",
    "Safe logging balances detail, cost, and signal so operators receive useful information when the system is healthy and when it is under pressure.",
    "A safe design defines ordering, ownership, and what happens to queued records during controlled shutdown."
  ]
};
