window.COURSE_MODULE = {
  "title": "Retention, Access, and Operational Governance",
  "graphicAlt": "Log-governance lifecycle showing collection, protected transport, restricted storage, role-based access, retention expiry, deletion, audit review, and incident use, with sensitive environments separated from broad analytics.",
  "narration": "Safe logging continues after code writes the event. Logs are collected, transported, indexed, searched, retained, exported, and sometimes copied into tickets or incident records. Governance has to cover the whole lifecycle.\n\nAccess control is essential because logs often aggregate sensitive operational context. Even if individual events avoid obvious secrets, combined logs can reveal identifiers, timing, system behavior, environment names, and business activity that should not be broadly visible.\n\nRetention rules should be defined before storage grows indefinitely. Some logs support short-term debugging. Others support audit or incident response. Each category should have a retention period, deletion policy, and owner who understands the operational and privacy tradeoffs.\n\nRedaction and classification policies should be reviewed regularly. Field names, data sources, third-party libraries, and diagnostic practices change over time. A field that was safe in one version may become sensitive after a feature change.\n\nSeparate environments and audiences. Development logs, test logs, production logs, and regulated operational records may require different access, retention, and masking. Copying production-style logs into less controlled places should be governed.\n\nLogging changes should be reviewed like other security-sensitive code. Adding a new event, changing a field, increasing verbosity, or expanding retention can change the risk profile. Governance keeps logging useful without allowing it to become unmanaged data collection.\n\nOperational governance should also include periodic sampling. Reviewing real events helps teams find accidental sensitive fields, noisy messages, missing correlation, and retention categories that no longer match how the system is used.\n\nOwnership should be explicit. Someone should be accountable for the logging policy, the field taxonomy, access approvals, retention exceptions, and the process for updating events when requirements change.",
  "narrationPoints": [
    "Access control is essential because logs often aggregate sensitive operational context.",
    "Each category should have a retention period, deletion policy, and owner who understands the operational and privacy tradeoffs.",
    "A field that was safe in one version may become sensitive after a feature change.",
    "Development logs, test logs, production logs, and regulated operational records may require different access, retention, and masking.",
    "Governance keeps logging useful without allowing it to become unmanaged data collection.",
    "Someone should be accountable for the logging policy, the field taxonomy, access approvals, retention exceptions, and the process for updating events when requirements change."
  ]
};
