window.COURSE_MODULE = {
  "title": "Tool Calls, Actions, and Audit Trails",
  "graphicAlt": "An audit trail distinguishes a proposed action, policy and approval decisions, execution and downstream result; denied actions stop before execution and remain observable.",
  "narration": "Tools are the bridge between model output and real systems. A read-only tool may retrieve a status or lookup a document. A write-capable tool may modify a file, send a message, create a ticket, update a repository, or change a cloud resource. Because tools can connect agent decisions to real data and actions, tool-call logs are security-critical. They show where the agent moved from conversation into operational effect.\n\nA high-impact action audit trail should include the requester, the model-proposed action, tool name, tool arguments or a safe summary, authorization decision, policy version, approval status, executed action, downstream result, and any rollback reference. If a human approved the action, the audit trail should show what they saw when they approved it. Approval that cannot be reconstructed later is weak evidence.\n\nTool monitoring should also record validation and control decisions. Argument validation, allowlists, rate limits, transaction previews, dry-run modes, approval gates, and policy denials all matter. A denied action can be as important as an executed one because repeated denials may show user confusion, prompt manipulation, attempted misuse, or a broken workflow. Logs should capture decisions without relying only on the final model text.\n\nTool logs must be tied to identity and authorization. The system should distinguish the user who requested the action, the application identity that brokered it, the model or prompt version involved, and the service identity used against the downstream system. This makes investigation possible and helps prevent models from becoming invisible middle layers between people and privileged operations.",
  "narrationPoints": [
    "Tools are the bridge between model output and real systems.",
    "A high-impact action audit trail should include the requester, the model-proposed action, tool name, tool arguments or a safe summary, authorization decision, policy version, approval status, executed action, downstream result, and any rollback reference.",
    "Tool monitoring should also record validation and control decisions.",
    "Tool logs must be tied to identity and authorization."
  ]
};
