window.COURSE_MODULE = {
  "title": "Retrieval, Memory, and Data Access Monitoring",
  "graphicAlt": "Tenant-scoped retrieval passes an access check with a source reference attached, while unauthorized cross-tenant access is stopped and memory reads, writes, and deletions are monitored.",
  "narration": "Retrieval-augmented generation and memory features can strongly influence agent behavior. The agent may query a vector store, retrieve documents, consult prior notes, read user-specific memory, or write new memory for later interactions. Monitoring needs to show what information influenced the response or action. If the agent cites a policy, recommends a change, or takes an action, investigators should be able to see the source path behind that behavior.\n\nSource provenance is central to retrieval monitoring. Logs should identify where retrieved content came from, which tenant or workspace it belonged to, when it was accessed, and how it was used. Source references are more durable and privacy-aware than storing full retrieved text in every log. They also help analysts detect stale, conflicting, or unauthorized sources that may have affected the agent's output.\n\nMemory requires special care because it can shape future behavior. Memory reads should be visible when they affect a response. Memory writes should be monitored because they may store sensitive, incorrect, stale, or unauthorized information. Memory deletion should also be recorded when relevant. Cross-user or cross-tenant memory exposure is a serious risk, so monitoring should confirm that isolation boundaries are working.\n\nRetrieved content can also carry untrusted instructions at a high level. Monitoring should help teams identify when external content influenced tool use or policy-sensitive behavior. The system does not need to log every token of protected content to be useful. It does need to record the source, access decision, redaction decision, and relationship between retrieved context, model output, and action.",
  "narrationPoints": [
    "Retrieval-augmented generation and memory features can strongly influence agent behavior.",
    "Source provenance is central to retrieval monitoring.",
    "Memory requires special care because it can shape future behavior.",
    "Retrieved content can also carry untrusted instructions at a high level."
  ]
};
