window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Signing Workflows and Data Preparation with reviewable Python controls.",
  "codeExamples": [
    {
      "title": "Create stable JSON bytes for constrained data",
      "language": "python",
      "blurb": "This is a stable encoding for a tightly controlled JSON schema. For cross-language signatures, use a documented canonical JSON profile such as RFC 8785.",
      "code": "import json\nfrom collections.abc import Mapping\nfrom typing import Any\n\nJsonValue = None | bool | int | str | list[\"JsonValue\"] | dict[str, \"JsonValue\"]\nMAX_SIGNED_JSON_NODES = 10_000\nMAX_SIGNED_JSON_DEPTH = 32\nMAX_SIGNED_JSON_TEXT = 8192\nMAX_SIGNED_JSON_BYTES = 1_000_000\nMAX_SIGNED_JSON_INTEGER = 1_000_000_000_000_000\n\ndef reject_ambiguous_json(value: Any) -> None:\n    pending = [(value, 0)]\n    seen_containers: set[int] = set()\n    nodes = 0\n    while pending:\n        current, depth = pending.pop()\n        nodes += 1\n        if nodes > MAX_SIGNED_JSON_NODES or depth > MAX_SIGNED_JSON_DEPTH:\n            raise ValueError(\"signed JSON complexity limit exceeded\")\n        if current is None or type(current) is bool:\n            continue\n        if type(current) is int:\n            if abs(current) > MAX_SIGNED_JSON_INTEGER:\n                raise ValueError(\"signed JSON integer rejected\")\n            continue\n        if type(current) is str:\n            if len(current) > MAX_SIGNED_JSON_TEXT:\n                raise ValueError(\"signed JSON text rejected\")\n            continue\n        if isinstance(current, float):\n            raise ValueError(\"floating-point values are not allowed in signed JSON\")\n        if isinstance(current, Mapping):\n            identity = id(current)\n            if identity in seen_containers:\n                raise ValueError(\"cyclic or shared signed JSON container rejected\")\n            seen_containers.add(identity)\n            if len(current) > 256:\n                raise ValueError(\"signed JSON object rejected\")\n            for key, item in current.items():\n                if type(key) is not str or not 1 <= len(key) <= 128:\n                    raise ValueError(\"JSON object key rejected\")\n                pending.append((item, depth + 1))\n            continue\n        if type(current) is list:\n            identity = id(current)\n            if identity in seen_containers:\n                raise ValueError(\"cyclic or shared signed JSON container rejected\")\n            seen_containers.add(identity)\n            if len(current) > 1024:\n                raise ValueError(\"signed JSON array rejected\")\n            pending.extend((item, depth + 1) for item in current)\n            continue\n        raise TypeError(\n            f\"unsupported signed JSON value: {type(current).__name__}\"\n        )\n\ndef stable_json_bytes(value: JsonValue) -> bytes:\n    reject_ambiguous_json(value)\n    encoded = json.dumps(\n        value,\n        ensure_ascii=False,\n        allow_nan=False,\n        sort_keys=True,\n        separators=(\",\", \":\"),\n    ).encode(\"utf-8\")\n    if len(encoded) > MAX_SIGNED_JSON_BYTES:\n        raise ValueError(\"signed JSON byte limit exceeded\")\n    return encoded\n"
    },
    {
      "title": "Bind a signature to its purpose",
      "language": "python",
      "blurb": "A domain separator prevents the same bytes from being interpreted as a different kind of signed instruction.",
      "code": "from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey\n\nDOMAIN = b\"example.test/payment-approval/v1\\x00\"\nMAX_PAYMENT_BYTES = 16_384\n\ndef sign_payment(\n    private_key: Ed25519PrivateKey,\n    stable_payment: bytes,\n) -> bytes:\n    if not isinstance(private_key, Ed25519PrivateKey):\n        raise TypeError(\"Ed25519 private key required\")\n    if (\n        type(stable_payment) is not bytes\n        or not 1 <= len(stable_payment) <= MAX_PAYMENT_BYTES\n    ):\n        raise ValueError(\"payment payload rejected\")\n    return private_key.sign(DOMAIN + stable_payment)\n"
    }
  ]
};
