window.COURSE_MODULE = {
  "title": "C Memory, Objects, and Pointers",
  "graphicAlt": "Bullet summary graphic for C Memory, Objects, and Pointers.",
  "narration": "C programs work with objects stored in memory. An object may be a scalar variable, an array, a structure, dynamically allocated storage, or another region with a defined type and lifetime. Memory safety depends on accessing the right object, through an appropriate type, within its valid range, while the object is still alive.\n\nA pointer stores an address, but it is not a complete safety contract. The pointer value alone does not reliably describe the size of the object, the number of valid elements, who owns the storage, whether it may be written, or how long it remains valid. Those facts must come from the surrounding contract.\n\nArray names often decay to pointers when passed to functions. A callee that receives a pointer usually cannot recover the original array length from the pointer alone. If the function needs to read or write a bounded region, pass the valid length, destination capacity, or structured metadata along with the pointer.\n\nPointer arithmetic depends on the pointed-to type and element size. Advancing an int pointer by one moves to the next int. Advancing a structure pointer by one moves by the size of the structure. Reviewers should understand which object the pointer is intended to traverse and which range of elements is valid.\n\nThe sizeof operator behaves differently on actual arrays and pointer parameters. In the scope where an array is declared, sizeof can describe the whole array object. Inside a function that receives a pointer parameter, sizeof describes the pointer itself, not the storage behind it. This distinction is a common source of incorrect bounds logic.\n\nDefensive C code avoids assuming that raw pointers can explain themselves. A safer interface states whether the pointer is borrowed or owned, how many elements are valid, how much capacity is available, whether writes are allowed, and what happens when an operation does not fit.",
  "narrationPoints": [
    "An object may be a scalar variable, an array, a structure, dynamically allocated storage, or another region with a defined type and lifetime.",
    "The pointer value alone does not reliably describe the size of the object, the number of valid elements, who owns the storage.",
    "A callee that receives a pointer usually cannot recover the original array length from the pointer alone.",
    "Reviewers should understand which object the pointer is intended to traverse and which range of elements is valid.",
    "Defensive C code avoids assuming that raw pointers can explain themselves."
  ]
};
