window.COURSE_MODULE = {
  "title": "Storage Duration and Object Lifetime",
  "graphicAlt": "Bullet summary graphic for Storage Duration and Object Lifetime.",
  "narration": "Storage duration and object lifetime are central to memory-safe C. An object is safe to access only while its lifetime is active and only through operations that respect its type and bounds. A pointer may still contain an address after an object has gone away, but the program no longer has a valid object at that lifetime.\n\nAutomatic objects usually live for a block or function scope. Local variables, local arrays, and local structures are convenient for temporary work, but their lifetime ends when execution leaves the relevant scope. Returning a pointer to such an object, or storing that address for later use, creates a pointer to storage whose intended lifetime has ended.\n\nStatic objects live for the duration of the program. They can be appropriate for constants, shared state, or long-lived tables, but long lifetime is not the same as safe access. Static storage can still create data races, hidden dependencies, stale state, or confusing ownership if the contract is unclear.\n\nDynamically allocated objects live until explicitly released. That flexibility is useful when a result must outlive a function call or when capacity is determined at runtime. It also creates responsibility: someone must own the allocation, update metadata consistently, and release it exactly according to the contract.\n\nDangling pointers occur when code keeps using an address after the object's lifetime has ended. This can happen after a local object goes out of scope, after dynamic storage is released, after a buffer is reallocated, or after ownership is transferred but the old owner keeps using the pointer.\n\nFunction contracts and cleanup logic should make lifetime and ownership visible. A caller should know whether it owns returned storage, whether it may retain a borrowed pointer, whether the callee stores a pointer, and which cleanup path is responsible for release. Clear lifetime rules reduce whole classes of memory defects.",
  "narrationPoints": [
    "An object is safe to access only while its lifetime is active and only through operations that respect its type and bounds.",
    "Returning a pointer to such an object, or storing that address for later use, creates a pointer to storage whose intended lifetime has ended.",
    "Static storage can still create data races, hidden dependencies, stale state, or confusing ownership if the contract is unclear.",
    "Dangling pointers occur when code keeps using an address after the object's lifetime has ended.",
    "Function contracts and cleanup logic should make lifetime and ownership visible."
  ]
};
