window.COURSE_MODULE = {
  "title": "Bounds Errors and Buffer Misuse",
  "graphicAlt": "Bullet summary graphic for Bounds Errors and Buffer Misuse.",
  "narration": "Bounds errors happen when code reads from or writes to memory outside the intended object. The object may be an array, a dynamically allocated buffer, a structure field, a local workspace, or a region described by a pointer and length. The safety question is always the same: is this access inside the valid range for this object right now.\n\nOut-of-bounds reads access memory outside the intended object. They may return unrelated data, stale data, padding, or bytes that happen to be nearby in a particular build. Even when a read does not crash, it can corrupt program logic by feeding later code a value that was never part of the intended input or state.\n\nOut-of-bounds writes modify memory outside the intended object. That can corrupt adjacent state, break data structures, disturb length fields, invalidate pointers, or crash the program. A write beyond the intended region is especially dangerous because it changes the program's future behavior, not just the current result.\n\nOff-by-one errors often come from incorrect loop conditions, endpoint confusion, or terminator handling. For a zero-based array with count elements, valid indexes are less than count. A condition that permits index equal to count steps one element beyond the array. Strings add another common boundary: space for the content is not the same as space for content plus terminator.\n\nLengths, indexes, offsets, and capacities must be validated before use. A start offset can be valid while the range from start through start plus length is not. A length can describe one buffer while code accidentally applies it to another. A capacity can describe total space while count describes current data. Defensive code keeps those facts separate.\n\nCheck ranges before performing pointer arithmetic or memory access. It is easier to reason about offsets and lengths as values first, then derive a pointer after the operation is known to fit. A reviewed helper for repeated range checks can make this pattern consistent across the codebase.",
  "narrationPoints": [
    "Bounds errors happen when code reads from or writes to memory outside the intended object.",
    "Out-of-bounds reads access memory outside the intended object.",
    "Out-of-bounds writes modify memory outside the intended object.",
    "A start offset can be valid while the range from start through start plus length is not.",
    "A reviewed helper for repeated range checks can make this pattern consistent across the codebase."
  ]
};
