window.COURSE_MODULE = {
  "title": "OT Environments and System Topologies",
  "graphicAlt": "Blank course graphic placeholder",
  "narration": "OT topologies connect physical processes with control, supervision, engineering, operations, and enterprise functions. At the field level, sensors measure process conditions and actuators create physical action. Controllers such as PLCs and RTUs read inputs, execute logic, and update outputs.\n\nHuman-machine interfaces give operators visibility into status, alarms, trends, and commands. SCADA systems coordinate monitoring and supervisory control across distributed assets. Distributed control systems support coordinated control within plants or processes. Engineering workstations configure controllers and applications, while historians store time-series operational data.\n\nThese systems also connect to site services and enterprise applications for scheduling, reporting, maintenance, identity, remote support, and analytics. Purdue-style layers can provide a useful mental model for these functions, but the actual environment may include cloud platforms, wireless devices, vendor appliances, remote sites, and legacy links that cross traditional boundaries.\n\nTopology matters because communication paths shape risk. A reporting flow from a historian to an enterprise application has different consequences from an engineering path that can modify controller logic. A remote support connection may bypass expected boundaries if it uses a separate cellular or vendor-managed service.\n\nAccurate diagrams should show assets, trust boundaries, data and control flows, remote access, dependencies, redundancy, and external connections. This information supports segmentation, monitoring placement, vulnerability analysis, and incident containment. During response, teams need to know which functions can continue locally and what may be lost when a connection is isolated. Security architecture begins with understanding how the operation actually communicates.",
  "narrationPoints": [
    "OT topologies connect physical processes with control, supervision, engineering, operations, and enterprise functions.",
    "Human-machine interfaces give operators visibility into status, alarms, trends, and commands.",
    "These systems also connect to site services and enterprise applications for scheduling, reporting, maintenance, identity, remote support, and...",
    "Topology matters because communication paths shape risk.",
    "Accurate diagrams should show assets, trust boundaries, data and control flows, remote access, dependencies, redundancy, and external connections."
  ]
};
