window.COURSE_MODULE = {
  "title": "Operating and Maintaining OT Security",
  "graphicAlt": "Blank course graphic placeholder",
  "narration": "Sustainable OT security depends on accurate operational practices. Asset inventory should record hardware, software, firmware, network identity, physical location, owner, vendor, function, criticality, communication, and support status. Inventory changes as equipment is replaced, temporary systems are added, and vendors modify support paths.\n\nConfiguration management establishes trusted baselines for controllers, network devices, servers, workstations, applications, and security controls. Back up logic and settings, review differences, and document authorized changes. Change control should define testing, approvals, maintenance windows, rollback, and post-change validation.\n\nPatch and vulnerability management require coordination. Monitor vendor advisories, confirm affected assets and versions, evaluate exposure and consequence, test updates, and schedule work. When remediation is delayed, use compensating controls with owners and review dates. Unsupported technology needs lifecycle planning rather than indefinite exception.\n\nLogging and monitoring should focus on useful events: remote sessions, authentication, privilege, configuration transfer, new devices, boundary traffic, security-tool status, and changes to expected communication. Analysts need operational context to distinguish approved maintenance from suspicious activity.\n\nTraining should prepare operators, engineers, administrators, vendors, and incident responders for their responsibilities. Exercises can test loss of visibility, ransomware, remote-access misuse, and recovery. Lessons should update procedures, architecture, contacts, and control priorities.\n\nContinuous improvement uses evidence from incidents, near misses, assessments, exceptions, maintenance, and technology changes. Track whether controls work, whether risk decisions remain valid, and whether recovery can meet operational needs. Security becomes part of normal operations when ownership, maintenance, monitoring, and engineering decisions reinforce one another.",
  "narrationPoints": [
    "Sustainable OT security depends on accurate operational practices.",
    "Configuration management establishes trusted baselines for controllers, network devices, servers, workstations, applications, and security controls.",
    "Patch and vulnerability management require coordination.",
    "Logging and monitoring should focus on useful events: remote sessions, authentication, privilege, configuration transfer, new devices, boundary...",
    "Training should prepare operators, engineers, administrators, vendors, and incident responders for their responsibilities.",
    "Continuous improvement uses evidence from incidents, near misses, assessments, exceptions, maintenance, and technology changes."
  ]
};
