window.COURSE_MODULE = {
  "title": "Input Validation, API Routes, and Server Actions",
  "graphicAlt": "Form and API mutations pass a narrow server contract, validation, and authorization while server-owned fields remain outside client control.",
  "narration": "Every request input should be treated as untrusted until validated on the server. Path parameters, query parameters, headers, cookies, JSON bodies, form submissions, and uploaded files can all influence behavior. Frontend validation helps users correct mistakes early, but it is not an enforcement boundary. Browser clients can be modified, requests can be replayed, and API handlers can be called without the intended interface. The server must validate before sensitive processing.\n\nSchema validation concepts help make request contracts visible. Handlers should check type, shape, required fields, optional fields, length, range, format, enum values, and content type where appropriate. Business-rule validation is separate from type validation. A string may be a valid identifier format but still refer to a resource the user cannot access. A number may be in range but still violate policy. A form may be structurally valid but still request an unauthorized mutation.\n\nAPI routes, route handlers, and server actions should be explicit, narrow, and reviewable. Mutation paths need particular care because they change state. The code should define which fields may be updated, avoid mass assignment, apply request size limits, validate file uploads before downstream processing, handle parsing errors safely, and return consistent error responses. The handler should not rely on hidden assumptions from the page that submitted the request.\n\nSafe validation is also an operations feature. Clear request contracts make tests easier, reduce surprising behavior, and give logs better structure. When validation fails, the response should help the caller correct the request without revealing internals. Internal logs can record safe diagnostic detail, but they should avoid secrets, tokens, session values, private payloads, and unnecessary personal data.",
  "narrationPoints": [
    "Every request input should be treated as untrusted until validated on the server.",
    "Schema validation concepts help make request contracts visible.",
    "API routes, route handlers, and server actions should be explicit, narrow, and reviewable.",
    "Safe validation is also an operations feature."
  ]
};
