window.COURSE_MODULE = {
  "title": "Secrets, Dependencies, Logging, and Deployment",
  "graphicAlt": "Release review covers private configuration, dependencies, safe logging, and production settings, keeping secret material out of exposed artifacts.",
  "narration": "Secrets management is a core part of Next.js security. API keys, database credentials, signing secrets, session secrets, OAuth credentials, and service tokens should remain server-side and come from protected configuration or secret management systems. Public configuration and server-only configuration must be clearly separated. A value that reaches a client bundle should be assumed visible to users. Secrets should not be committed, logged, placed in images, exposed through previews, or copied into support artifacts.\n\nDependency hygiene matters because web applications depend on packages, build tools, plugins, middleware, and deployment integrations. Lockfiles, dependency review, update discipline, package provenance, and security advisories all help manage risk. Scanning is useful, but it is not the whole practice. Teams should pay particular attention to packages that handle authentication, parsing, rendering, serialization, file processing, data fetching, or build-time behavior because those packages sit close to security boundaries.\n\nSafe logging supports investigation without becoming a data leak. Logs may need route names, request IDs, user or service identity, outcome, timing, authorization denials, validation failures, and high-impact actions. They should avoid secrets, credentials, tokens, session values, private payloads, and unnecessary personal data. Redaction and retention rules should be designed before an incident, not improvised after sensitive data has already been copied across log systems.\n\nDeployment review closes the loop. Production and development settings should differ intentionally. Debug routes, stack traces, development middleware, test data, preview environments, staging credentials, CORS settings, security headers, reverse proxy behavior, and environment variables should all be part of release review. Monitoring and incident response readiness matter because Next.js security continues after code is merged. Teams need to know when traffic, errors, denials, dependency behavior, or data access patterns change.",
  "narrationPoints": [
    "Secrets management is a core part of Next.js security.",
    "Dependency hygiene matters because web applications depend on packages, build tools, plugins, middleware, and deployment integrations.",
    "Safe logging supports investigation without becoming a data leak.",
    "Deployment review closes the loop."
  ]
};
