window.COURSE_MODULE = {
  "title": "Detection, Testing, and Code Review",
  "graphicAlt": "A detection pipeline combines AddressSanitizer, container-invalidation tests, asynchronous shutdown tests, and lifetime-focused code review.",
  "narration": "Use-after-free prevention is a design activity, but tooling helps catch mistakes earlier. AddressSanitizer can detect many memory lifetime and access errors during instrumented execution. UndefinedBehaviorSanitizer can help with related undefined behavior. Compiler warnings, static analysis, and focused diagnostics can point reviewers toward suspicious ownership or invalidation patterns.\n\nTools only observe the paths that are built, instrumented, and exercised. A sanitizer run that passes does not prove every lifetime is safe. Tests should target lifecycle-sensitive scenarios: object destruction, container mutation, error exits, cancellation, unregistration, ownership handoff, and callback execution after shutdown begins. Regression tests are especially valuable when fixing a stale access bug so the same pattern does not return.\n\nCode review should ask practical lifetime questions. Who owns this object? Can any pointer, reference, iterator, view, or callback outlive it? Can a container modification invalidate stored access? Does a moved object still get used? Is .release() followed by an immediate owner? Are raw pointer boundaries documented? These questions turn lifetime safety into a repeatable review habit.\n\nPrioritize tests that exercise the boring edges. Destroy objects while work is pending, resize containers after taking views, move owners before callbacks run, and force failure paths that usually receive less attention. These scenarios are valuable because lifetime bugs often hide in cleanup and rarely used recovery logic. Make the test describe the lifetime rule it protects.\n\nFindings should be treated as engineering defects, not one-off cleanup chores. Track them, add tests, improve API contracts, and consider whether similar patterns exist elsewhere. Tools support judgment, but clear ownership design remains the strongest defense.",
  "narrationPoints": [
    "Use-after-free prevention is a design activity, but tooling helps catch mistakes earlier.",
    "Compiler warnings, static analysis, and focused diagnostics can point reviewers toward suspicious ownership or invalidation patterns.",
    "Tests should target lifecycle-sensitive scenarios: object destruction, container mutation, error exits, cancellation, unregistration, ownership handoff, and callback execution after shutdown begins.",
    "Can any pointer, reference, iterator, view, or callback outlive it?",
    "Findings should be treated as engineering defects, not one-off cleanup chores.",
    "Tools support judgment, but clear ownership design remains the strongest defense."
  ]
};
