window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Key Issuance, Rotation, Revocation, and Expiration' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Represent API-key lifecycle metadata as validated immutable state",
      "language": "csharp",
      "blurb": "The factory validates the identifier, positive version, ordered activation and expiration, and an application-owned maximum lifetime; active checks also honor revocation.",
      "code": "public sealed class ApiKeyMetadata\n{\n    private static readonly TimeSpan MaximumLifetime = TimeSpan.FromDays(180);\n\n    private ApiKeyMetadata(\n        string keyId,\n        long version,\n        DateTimeOffset activatesAt,\n        DateTimeOffset expiresAt,\n        bool revoked)\n    {\n        KeyId = keyId;\n        Version = version;\n        ActivatesAt = activatesAt;\n        ExpiresAt = expiresAt;\n        Revoked = revoked;\n    }\n\n    public string KeyId { get; }\n    public long Version { get; }\n    public DateTimeOffset ActivatesAt { get; }\n    public DateTimeOffset ExpiresAt { get; }\n    public bool Revoked { get; }\n\n    public static ApiKeyMetadata Create(\n        string keyId,\n        long version,\n        DateTimeOffset activatesAt,\n        DateTimeOffset expiresAt,\n        bool revoked)\n    {\n        if (!IsIdentifier(keyId) || version <= 0 ||\n            expiresAt <= activatesAt || expiresAt - activatesAt > MaximumLifetime)\n        {\n            throw new ArgumentException(\"API-key lifecycle rejected.\");\n        }\n        return new ApiKeyMetadata(keyId, version, activatesAt, expiresAt, revoked);\n    }\n\n    public bool IsActive(DateTimeOffset now) =>\n        !Revoked && now >= ActivatesAt && now < ExpiresAt;\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    },
    {
      "title": "Activate only the next reviewed API-key version",
      "language": "csharp",
      "blurb": "The rotation gate obtains time from the system clock, requires distinct identifiers, checks version increment without overflow, and admits only an active candidate after the current key has reached its overlap window.",
      "code": "public static class ApiKeyRotationPolicy\n{\n    private static readonly TimeSpan MaximumOverlap = TimeSpan.FromHours(24);\n\n    public static bool CanActivate(\n        RotationKey current,\n        RotationKey candidate)\n    {\n        ArgumentNullException.ThrowIfNull(current);\n        ArgumentNullException.ThrowIfNull(candidate);\n        if (current.Version == long.MaxValue ||\n            candidate.Version != current.Version + 1 ||\n            string.Equals(candidate.KeyId, current.KeyId, StringComparison.Ordinal))\n        {\n            return false;\n        }\n\n        var now = DateTimeOffset.UtcNow;\n        return candidate.ActivatesAt <= now && candidate.ExpiresAt > now &&\n               current.ExpiresAt >= now && current.ExpiresAt - now <= MaximumOverlap;\n    }\n}\n\npublic sealed class RotationKey\n{\n    private static readonly TimeSpan MaximumLifetime = TimeSpan.FromDays(180);\n\n    private RotationKey(string keyId, long version, DateTimeOffset activatesAt, DateTimeOffset expiresAt)\n    {\n        KeyId = keyId;\n        Version = version;\n        ActivatesAt = activatesAt;\n        ExpiresAt = expiresAt;\n    }\n\n    public string KeyId { get; }\n    public long Version { get; }\n    public DateTimeOffset ActivatesAt { get; }\n    public DateTimeOffset ExpiresAt { get; }\n\n    public static RotationKey Create(string keyId, long version, DateTimeOffset activatesAt, DateTimeOffset expiresAt)\n    {\n        if (string.IsNullOrEmpty(keyId) || keyId.Length > 64 ||\n            keyId.Any(character => !char.IsAsciiLetterOrDigit(character) && character is not '-' and not '_') ||\n            version <= 0 || expiresAt <= activatesAt ||\n            expiresAt - activatesAt > MaximumLifetime)\n        {\n            throw new ArgumentException(\"Rotation key rejected.\");\n        }\n        return new RotationKey(keyId, version, activatesAt, expiresAt);\n    }\n}\n"
    }
  ]
};
