window.COURSE_MODULE = {
  "title": "ASP.NET Core Authentication Patterns for API Keys",
  "graphicAlt": "Bullet summary graphic for ASP.NET Core Authentication Patterns for API Keys.",
  "narration": "API key validation should be consistent and reviewable. The application should have a clear pattern for extracting the key, identifying the candidate client, validating the credential, attaching the caller identity, and producing predictable failure behavior. Reviewers should not need to inspect every endpoint to discover a different local rule.\n\nCustom authentication handlers can integrate API key validation with the ASP.NET Core authentication and authorization pipeline. That can make API-key callers behave like other authenticated principals, allowing endpoint metadata, named policies, route groups, and authorization attributes to participate in the same review model.\n\nMiddleware, endpoint filters, action filters, gateway enforcement, or service-specific checks may also be useful depending on architecture. A gateway can protect a broad perimeter. Middleware can centralize extraction. Filters can support endpoint-specific requirements. Service checks can verify resource-specific rules. The right pattern depends on where identity and policy should be enforced.\n\nWhat teams should avoid is scattered ad hoc checks hidden inside individual endpoints. Repeated local string comparisons, inconsistent header names, different error responses, and endpoint-specific logging choices are difficult to audit. They also make rotation, revocation, and monitoring harder.\n\nAuthentication identifies the calling client or integration. Authorization decides what that caller may do. A valid API key should establish identity or client context, but it should not automatically grant every operation. Endpoint metadata, route groups, named policies, and clear conventions help keep that separation visible.\n\nAuthentication failure behavior should be predictable and should not reveal unnecessary detail about whether a specific key exists. The response should be safe for clients, while protected logs can record enough context for operators to understand validation outcomes without storing the key itself.",
  "narrationPoints": [
    "API key validation should be consistent and reviewable.",
    "Custom authentication handlers can integrate API key validation with the ASP.NET Core authentication and authorization pipeline.",
    "The right pattern depends on where identity and policy should be enforced.",
    "A valid API key should establish identity or client context, but it should not automatically grant every operation.",
    "Authentication failure behavior should be predictable and should not reveal unnecessary detail about whether a specific key exists."
  ]
};
