window.COURSE_MODULE = {
  "title": "Secure Storage and Validation of API Keys",
  "graphicAlt": "Bullet summary graphic for Secure Storage and Validation of API Keys.",
  "narration": "Raw API keys should be treated like passwords or bearer credentials. If someone can read the raw key, they may be able to use it wherever that key is accepted. That is why keys do not belong in source code, ordinary appsettings files, public configuration, documentation, sample projects, or support notes.\n\nDevelopment secret storage is not production secret management. Developer tools can keep local work from becoming hardcoded configuration, but production secrets should use environment-appropriate secret stores, managed platforms, deployment identity, or controlled configuration systems. Production storage needs access control, rotation support, auditability, and operational ownership.\n\nFor inbound client API keys, prefer storing a non-reversible verifier such as a strong hash, plus a separate lookup identifier or prefix. This lets the system identify a candidate key record and validate the presented value without retaining every full raw secret in ordinary storage.\n\nA key prefix or identifier is useful for lookup, display, support, and rotation, but it is not the secret. Prefixes should help humans and systems find the right record without granting access by themselves. Support tooling should display enough to identify the key record, not enough to reconstruct or use the key.\n\nGenerated keys need enough entropy for their purpose. The generation process should be owned and consistent, and keys should be distinguishable from ordinary text so teams can recognize their type, environment, or issuer without exposing the secret material.\n\nValidation behavior should avoid unnecessary information disclosure. Candidate keys should be compared carefully, failures should be consistent, and logs should record safe identifiers rather than raw keys. The user-facing response should not reveal which part of validation failed.\n\nPlan for multi-instance deployments. Validation data, caches, revocation state, and rotation windows need to behave consistently across application instances, regions, gateways, and background workers. A key that is revoked in one place should not remain active elsewhere because state was cached without a plan.",
  "narrationPoints": [
    "Raw API keys should be treated like passwords or bearer credentials.",
    "For inbound client API keys, prefer storing a non-reversible verifier such as a strong hash, plus a separate lookup identifier or prefix.",
    "A key prefix or identifier is useful for lookup, display, support, and rotation, but it is not the secret.",
    "The user-facing response should not reveal which part of validation failed.",
    "Validation data, caches, revocation state, and rotation windows need to behave consistently across application instances, regions, gateways, and background workers."
  ]
};
