window.COURSE_MODULE = {
  "title": "Key Issuance, Rotation, Revocation, and Expiration",
  "graphicAlt": "Bullet summary graphic for Key Issuance, Rotation, Revocation, and Expiration.",
  "narration": "API keys need a lifecycle. Issuance should record owner, purpose, environment, scope, creation time, display behavior, approval path, and expected rotation path. A key should not appear in production without a record that explains why it exists and who is responsible for it.\n\nKeys should be shown only when appropriate. Many systems use display-once behavior for newly generated secrets so the full value is not retrievable later. That pattern reduces unnecessary exposure and encourages secure storage by the owner. If a system allows full retrieval later, the risk should be explicitly accepted and protected.\n\nRotation should allow safe transition. In many systems, that means allowing overlapping old and new keys for a limited period while clients are updated. The overlap window should be visible and bounded. Operators should be able to tell which clients are still using the old key and when it is safe to remove it.\n\nRevocation should be fast enough for the risk of the system. Some keys can be disabled manually during normal operations. Others require near-real-time propagation across gateways, instances, and regions. The right design depends on what the key can access and how quickly the organization must respond.\n\nExpiration reduces stale credential risk but must be balanced with operational reliability. Short lifetimes can force better hygiene but may break integrations if owners are not prepared. Long lifetimes reduce maintenance pressure but increase the chance that forgotten keys remain active.\n\nCompromise response should include disabling the key, identifying usage, notifying owners, rotating dependent systems, reviewing logs, and documenting what changed. Stale keys, orphaned keys, test keys, and unused integration keys should be cleaned up through a regular review process.",
  "narrationPoints": [
    "A key should not appear in production without a record that explains why it exists and who is responsible for it.",
    "Operators should be able to tell which clients are still using the old key and when it is safe to remove it.",
    "The right design depends on what the key can access and how quickly the organization must respond.",
    "Expiration reduces stale credential risk but must be balanced with operational reliability.",
    "Compromise response should include disabling the key, identifying usage, notifying owners, rotating dependent systems, reviewing logs, and documenting what changed."
  ]
};
