window.COURSE_MODULE = {
  "title": "Logging, Monitoring, Rate Limits, and Abuse Signals",
  "graphicAlt": "Bullet summary graphic for Logging, Monitoring, Rate Limits, and Abuse Signals.",
  "narration": "Logs should support security operations without exposing secrets. A useful log record can identify the key record, owner, client, endpoint, result code, tenant, rate-limit decision, and correlation ID where appropriate. It does not need the full key or raw sensitive request content.\n\nNever log full API keys, provider tokens, secrets, raw sensitive payloads, or unredacted credential-bearing headers. Redaction should be tested across application logs, reverse proxy logs, structured logging, tracing, error handling, and support tooling. A key can appear in more places than the application team expects.\n\nMonitoring should cover failed validation, denied access, excessive request rates, unusual endpoint usage, new geography, unexpected user agents, tenant anomalies, key use after rotation, and access after revocation. These signals help operators distinguish normal integration behavior from activity that needs review.\n\nRate limits and quotas should align with key scope, client type, endpoint cost, tenant plan, and backend capacity. A low-cost read endpoint, a high-cost report, and a workflow-changing operation may require different limits. Limits should support reliability and fairness while preserving legitimate use.\n\nAlerting should distinguish suspicious behavior from normal operational spikes. A scheduled partner job, a batch import, or a deployment event may create predictable increases in traffic. Good alert design combines rate, endpoint, owner, tenant, outcome, and historical context rather than reacting to raw volume alone.\n\nThe defensive goal is visibility without exposure. Teams should be able to answer which key was used, what it tried to do, whether it was allowed, how often it happened, and who owns the integration without disclosing the secret material itself.",
  "narrationPoints": [
    "A useful log record can identify the key record, owner, client, endpoint, result code, tenant, rate-limit decision, and correlation ID where appropriate.",
    "Redaction should be tested across application logs, reverse proxy logs, structured logging, tracing, error handling, and support tooling.",
    "Monitoring should cover failed validation, denied access, excessive request rates, unusual endpoint usage, new geography, unexpected user agents, tenant anomalies, key use after rotation, and access after revocation.",
    "Rate limits and quotas should align with key scope, client type, endpoint cost, tenant plan, and backend capacity.",
    "Good alert design combines rate, endpoint, owner, tenant, outcome, and historical context rather than reacting to raw volume alone."
  ]
};
