window.COURSE_MODULE = {
  "title": "Access Control, Downloads, and Metadata Protection",
  "graphicAlt": "Two-path comparison for Access Control, Downloads, and Metadata Protection in Secure File Uploads in Node.js: an unsafe flow bypasses the relevant control, while the approved flow passes through enforcement, bounded processing, and an auditable outcome.",
  "narration": "Upload authorization and download authorization are separate decisions. A user who can upload a file should not automatically be allowed to download every file, preview every file, or access metadata for other users, cases, projects, or tenants. Retrieval is often where sensitive data exposure occurs. Before serving a file, generating a signed URL, creating a preview, or returning metadata, the application should enforce object-level authorization for that specific file and business context.\n\nPrivate files should not rely on predictable public URLs for protection. Storage keys, signed URLs, preview endpoints, thumbnail paths, and metadata APIs all need careful control. Signed URLs can be useful, but their scope, lifetime, permissions, and logging should match the sensitivity of the file. Metadata such as original filename, uploader identity, upload time, file size, content type, scan status, tenant ID, and storage key may itself be sensitive and should be exposed only when appropriate.\n\nDownload responses also need safe handling. Set content type and content disposition deliberately, especially when browsers may try to render content inline. Avoid reflecting untrusted filenames into headers or HTML without proper handling. File deletion, ownership transfer, sharing, retention, and administrative access should follow the same business authorization model as the rest of the application. File security does not end when intake succeeds. It continues every time the file or its metadata is retrieved.",
  "narrationPoints": [
      "A user who can upload a file should not automatically be allowed to download every file, preview every file, or access metadata for other users, cases, projects, or tenants.",
      "Metadata such as original filename, uploader identity, upload time, file size, content type, scan status, tenant ID, and storage key may itself be sensitive and should be exposed only when appropriate.",
      "File deletion, ownership transfer, sharing, retention, and administrative access should follow the same business authorization model as the rest of the application.",
      "Before serving a file, generating a signed URL, creating a preview, or returning metadata, the application should enforce object-level authorization for that specific file and business context.",
      "Private files should not rely on predictable public URLs for protection.",
      "Storage keys, signed URLs, preview endpoints, thumbnail paths, and metadata APIs all need careful control."
  ]
};
