window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Unsafe SQL, Query Construction, and Data Access' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Build an order query from typed values and fixed SQL literals",
      "language": "csharp",
      "blurb": "The command builder validates the tenant, page size, and closed sort enum; selects a complete application-owned SQL literal; binds typed parameters; and disposes partial state if construction fails.",
      "code": "using System.Data;\nusing System.Data.Common;\n\npublic enum OrderSort\n{\n    CreatedNewest,\n    CreatedOldest\n}\n\npublic static class OrderQuery\n{\n    public static DbCommand Create(\n        DbConnection connection,\n        string tenantId,\n        OrderSort sort,\n        int take)\n    {\n        ArgumentNullException.ThrowIfNull(connection);\n        if (!IsIdentifier(tenantId))\n            throw new ArgumentException(\"Tenant identifier rejected.\", nameof(tenantId));\n        if (!Enum.IsDefined(sort))\n            throw new ArgumentOutOfRangeException(nameof(sort));\n        if (take is < 1 or > 100)\n            throw new ArgumentOutOfRangeException(nameof(take));\n\n        var command = connection.CreateCommand();\n        try\n        {\n            switch (sort)\n            {\n                case OrderSort.CreatedNewest:\n                    command.CommandText =\n                        \"SELECT Id, CreatedUtc, Status FROM Orders \" +\n                        \"WHERE TenantId = @tenant ORDER BY CreatedUtc DESC LIMIT @take\";\n                    break;\n                case OrderSort.CreatedOldest:\n                    command.CommandText =\n                        \"SELECT Id, CreatedUtc, Status FROM Orders \" +\n                        \"WHERE TenantId = @tenant ORDER BY CreatedUtc ASC LIMIT @take\";\n                    break;\n                default:\n                    throw new ArgumentOutOfRangeException(nameof(sort));\n            }\n\n            AddParameter(command, \"@tenant\", DbType.String, tenantId, 64);\n            AddParameter(command, \"@take\", DbType.Int32, take);\n            return command;\n        }\n        catch (Exception operationError)\n        {\n            try\n            {\n                command.Dispose();\n            }\n            catch (Exception cleanupError)\n            {\n                throw new AggregateException(\n                    \"Command construction and cleanup both failed.\",\n                    operationError,\n                    cleanupError);\n            }\n            throw;\n        }\n    }\n\n    private static void AddParameter(\n        DbCommand command,\n        string name,\n        DbType type,\n        object value,\n        int? size = null)\n    {\n        var parameter = command.CreateParameter();\n        parameter.ParameterName = name;\n        parameter.DbType = type;\n        parameter.Value = value;\n        if (size is int boundedSize)\n            parameter.Size = boundedSize;\n        command.Parameters.Add(parameter);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    },
    {
      "title": "Parse an explicit profile patch instead of mass-assigning input",
      "language": "csharp",
      "blurb": "The patch factory rejects duplicate and unknown JSON members, validates every supplied field, distinguishes absence from an invalid value, and exposes only the two properties the operation may update.",
      "code": "using System.Net.Mail;\nusing System.Text;\nusing System.Text.Json;\n\npublic sealed class AccountProfilePatch\n{\n    private AccountProfilePatch(string? displayName, string? email)\n    {\n        DisplayName = displayName;\n        Email = email;\n    }\n\n    public string? DisplayName { get; }\n    public string? Email { get; }\n\n    public static AccountProfilePatch Parse(ReadOnlyMemory<byte> utf8Json)\n    {\n        if (utf8Json.Length is 0 or > 8 * 1024)\n            throw new JsonException(\"Profile patch size rejected.\");\n\n        using var document = JsonDocument.Parse(utf8Json, new JsonDocumentOptions\n        {\n            AllowTrailingCommas = false,\n            CommentHandling = JsonCommentHandling.Disallow,\n            MaxDepth = 2\n        });\n        if (document.RootElement.ValueKind != JsonValueKind.Object)\n            throw new JsonException(\"Profile patch must be an object.\");\n\n        string? displayName = null;\n        string? email = null;\n        var supplied = new HashSet<string>(StringComparer.Ordinal);\n        foreach (var property in document.RootElement.EnumerateObject())\n        {\n            if (!supplied.Add(property.Name))\n                throw new JsonException(\"Duplicate profile field rejected.\");\n\n            switch (property.Name)\n            {\n                case \"displayName\":\n                    displayName = ReadDisplayName(property.Value);\n                    break;\n                case \"email\":\n                    email = ReadEmail(property.Value);\n                    break;\n                default:\n                    throw new JsonException(\"Unknown profile field rejected.\");\n            }\n        }\n        if (supplied.Count == 0)\n            throw new JsonException(\"At least one profile field is required.\");\n        return new AccountProfilePatch(displayName, email);\n    }\n\n    private static string ReadDisplayName(JsonElement value)\n    {\n        var text = value.ValueKind == JsonValueKind.String\n            ? value.GetString()\n            : null;\n        if (text is null || text.Length is < 1 or > 80 ||\n            !string.Equals(text, text.Trim(), StringComparison.Ordinal) ||\n            text.Any(char.IsControl) || Encoding.UTF8.GetByteCount(text) > 160)\n        {\n            throw new JsonException(\"Display name rejected.\");\n        }\n        return text;\n    }\n\n    private static string ReadEmail(JsonElement value)\n    {\n        var text = value.ValueKind == JsonValueKind.String\n            ? value.GetString()\n            : null;\n        if (text is null || text.Length > 254 || text.Any(char.IsControl) ||\n            !MailAddress.TryCreate(text, out var address) ||\n            !string.Equals(address.Address, text, StringComparison.OrdinalIgnoreCase))\n        {\n            throw new JsonException(\"Email address rejected.\");\n        }\n        return text;\n    }\n}\n"
    }
  ]
};
