window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'TLS, Certificates, HTTP Clients, and External Calls' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Create outbound endpoints from a closed HTTPS destination policy",
      "language": "csharp",
      "blurb": "The factory admits an absolute URI only when scheme, authority, credentials, port, path, query, and fragment match one application-owned endpoint, then returns immutable endpoint state for request construction.",
      "code": "public sealed class ApprovedOrdersEndpoint\n{\n    private ApprovedOrdersEndpoint(Uri value) => Value = value;\n\n    public Uri Value { get; }\n\n    public static ApprovedOrdersEndpoint Create(Uri candidate)\n    {\n        ArgumentNullException.ThrowIfNull(candidate);\n        if (!candidate.IsAbsoluteUri ||\n            !string.Equals(candidate.Scheme, Uri.UriSchemeHttps, StringComparison.Ordinal) ||\n            !string.Equals(candidate.IdnHost, \"orders-api.example.com\", StringComparison.Ordinal) ||\n            !string.IsNullOrEmpty(candidate.UserInfo) ||\n            (!candidate.IsDefaultPort && candidate.Port != 443) ||\n            !string.Equals(candidate.AbsolutePath, \"/v1/orders\", StringComparison.Ordinal) ||\n            !string.IsNullOrEmpty(candidate.Query) ||\n            !string.IsNullOrEmpty(candidate.Fragment))\n        {\n            throw new InvalidOperationException(\"Outbound destination rejected.\");\n        }\n        return new ApprovedOrdersEndpoint(new Uri(candidate.AbsoluteUri, UriKind.Absolute));\n    }\n}\n"
    },
    {
      "title": "Read an HTTP JSON body under a physical byte ceiling",
      "language": "csharp",
      "blurb": "The consumer rejects redirects, failures, unexpected content types, and oversized Content-Length evidence, then streams at most one byte beyond the application limit so chunked responses cannot bypass the physical ceiling.",
      "code": "using System.Net;\n\npublic static class BoundedJsonResponse\n{\n    private const int MaximumBodyBytes = 64 * 1024;\n\n    public static async Task<byte[]> ReadAsync(\n        HttpResponseMessage response,\n        CancellationToken cancellationToken)\n    {\n        ArgumentNullException.ThrowIfNull(response);\n        var statusCode = response.StatusCode;\n        var content = response.Content;\n        if ((int)statusCode is >= 300 and <= 399 ||\n            statusCode is < HttpStatusCode.OK or >= HttpStatusCode.MultipleChoices)\n        {\n            throw new HttpRequestException(\"Upstream status rejected.\");\n        }\n\n        var mediaType = content.Headers.ContentType?.MediaType;\n        if (!string.Equals(mediaType, \"application/json\", StringComparison.OrdinalIgnoreCase) ||\n            content.Headers.ContentLength is > MaximumBodyBytes)\n        {\n            throw new InvalidDataException(\"Upstream response metadata rejected.\");\n        }\n\n        var input = await content\n            .ReadAsStreamAsync(cancellationToken)\n            .ConfigureAwait(false);\n        byte[] body;\n        try\n        {\n            using var output = new MemoryStream();\n            var buffer = new byte[8 * 1024];\n            while (true)\n            {\n                var remaining = MaximumBodyBytes + 1 - checked((int)output.Length);\n                if (remaining == 0)\n                    throw new InvalidDataException(\"Upstream response exceeded the byte limit.\");\n                var read = await input.ReadAsync(\n                    buffer.AsMemory(0, Math.Min(buffer.Length, remaining)),\n                    cancellationToken).ConfigureAwait(false);\n                if (read == 0)\n                {\n                    body = output.ToArray();\n                    break;\n                }\n                await output.WriteAsync(\n                    buffer.AsMemory(0, read),\n                    cancellationToken).ConfigureAwait(false);\n            }\n        }\n        catch (Exception operationError)\n        {\n            try\n            {\n                await input.DisposeAsync().ConfigureAwait(false);\n            }\n            catch (Exception cleanupError)\n            {\n                throw new AggregateException(\n                    \"Response read and stream cleanup both failed.\",\n                    operationError,\n                    cleanupError);\n            }\n            throw;\n        }\n        await input.DisposeAsync().ConfigureAwait(false);\n        return body;\n    }\n}\n"
    }
  ]
};
