window.COURSE_MODULE = {
  "title": "TLS, Certificates, HTTP Clients, and External Calls",
  "graphicAlt": "Bullet summary graphic for TLS, Certificates, HTTP Clients, and External Calls.",
  "narration": "Disabling certificate validation is a dangerous anti-pattern, even when it begins as a local testing shortcut. Certificate validation is part of how the application confirms service identity and transport trust. Removing that check changes the meaning of the connection.\n\nTemporary trust-all callbacks, broad certificate exceptions, or environment flags can drift into production when they are copied, forgotten, or treated as harmless scaffolding. Development trust decisions should be scoped, documented, and separated from production behavior.\n\nOutbound HTTP clients need deliberate configuration. Lifetimes, timeouts, cancellation, retry behavior, base addresses, default headers, credentials, proxy settings, and logging rules all affect reliability and confidentiality. External calls are part of the application boundary, not plumbing to ignore.\n\nCreating and disposing HttpClient instances casually can create connection and socket-management problems. Reusing clients incorrectly can also cause problems, such as leaking headers, cookies, bearer values, tenant context, or base address assumptions across unrelated calls. The safer habit is to use a reviewed client factory or service-specific client design.\n\nRetries and fan-out should not amplify load against downstream services. A retry policy that looks reasonable in isolation can become harmful when many requests fail at once. Bound concurrency, add cancellation, apply timeouts, and make retry behavior appropriate for the dependency and operation.\n\nExternal service errors should be handled predictably without exposing secrets, tokens, URLs with credentials, raw sensitive payloads, or internal provider details. Logs should capture safe context: dependency name, operation category, status category, correlation ID, latency, retry count, and outcome.",
  "narrationPoints": [
    "Certificate validation is part of how the application confirms service identity and transport trust.",
    "External calls are part of the application boundary, not plumbing to ignore.",
    "Reusing clients incorrectly can also cause problems, such as leaking headers, cookies, bearer values, tenant context, or base address assumptions across unrelated calls.",
    "Bound concurrency, add cancellation, apply timeouts, and make retry behavior appropriate for the dependency and operation.",
    "External service errors should be handled predictably without exposing secrets, tokens, URLs with credentials, raw sensitive payloads, or internal provider details."
  ]
};
