window.COURSE_MODULE = {
  "title": "Authentication and Session Security",
  "graphicAlt": "Blank placeholder graphic for module 4, Authentication and Session Security.",
  "narration": "Authentication answers the question: who is this actor? Login flows, password handling, MFA, account recovery, identity provider integration, session creation, and session expiration are all part of that answer. Weaknesses in these workflows can undermine the rest of the application because every authorization decision depends on the identity being reliable. Good authentication design avoids leaking whether accounts exist, protects password reset flows, rate limits sensitive actions, and uses MFA where the risk warrants it.\n\nPassword handling should rely on established password hashing algorithms and strong operational controls rather than custom cryptography. The application should never store plaintext passwords, log them, place them in URLs, or send them to third-party tools unnecessarily. Account recovery should be treated like authentication, not like a convenience feature. If recovery tokens are predictable, long-lived, reusable, or exposed through logs and referrers, an attacker may not need the user password at all.\n\nSession security protects the authenticated state after login. Session identifiers should be unpredictable, rotated when privilege changes, invalidated on logout when appropriate, and expired according to risk. Cookie attributes matter: Secure helps ensure cookies are sent over HTTPS, HttpOnly helps keep scripts from reading them, and SameSite can reduce some cross-site request risks when configured for the application flow. Session management is also a workflow problem. Teams should consider concurrent sessions, idle timeouts, remember-me behavior, device trust, and how account recovery or password changes affect existing sessions.",
  "narrationPoints": [
    "Authentication answers the question: who is this actor?",
    "Password handling should rely on established password hashing algorithms and strong operational controls rather than custom cryptography.",
    "Session security protects the authenticated state after login."
  ]
};
