window.COURSE_MODULE = {
  "title": "How SQL Injection Crosses the Data-Code Boundary",
  "graphicAlt": "Two lanes contrast unsafe SQL construction with safe parameter binding. Concatenation or interpolation inserts untrusted input into a SQL program before parsing, while the safe lane delivers trusted SQL structure and bound values through separate API ports. Browser validation, authentication, and TypeScript types do not perform SQL binding.",
  "narration": "A relational database executes a SQL program and evaluates data values within that program. SQL injection becomes possible when externally controlled data is used to construct the program itself. In TypeScript, the dangerous boundary is easy to cross with string concatenation, template-literal interpolation, or a helper that accepts a complete SQL fragment. A route that inserts a request email directly between quote characters has not merely mishandled punctuation. It has allowed request data to influence where SQL syntax begins and ends.\n\nThe same defect can appear outside a simple WHERE comparison. Applications dynamically assemble filters, sort clauses, selected columns, table names, reporting expressions, and administrative commands. If raw request text enters any of those structural positions, the database may interpret part of that text as program logic. The consequences can affect confidentiality, writes, authentication decisions, reporting accuracy, and data integrity. A read-only endpoint is not automatically low risk when its database account can reach sensitive data.\n\nBrowser validation cannot defend this boundary because a client can send HTTP directly. Authentication also does not make input safe; an authenticated user can submit unexpected data and may be limited to only part of a shared database. TypeScript types improve development, but an external string remains a runtime string even if code asserts that it has a trusted interface. None of these controls separates the value from the SQL parser.\n\nThe durable design rule is that trusted application code authors SQL structure, while external values are bound separately through the database API. This keeps a value in a data position regardless of its contents. Structural choices that cannot be ordinary parameters require a different treatment: the server maps a limited client choice to a trusted fragment. Secure review therefore follows provenance. Identify which text forms the SQL program, determine where each part originated, and ensure that untrusted values never become executable syntax through string construction.",
  "narrationPoints": [
    "Injection occurs when untrusted data influences SQL program structure.",
    "Concatenation and raw interpolation are dangerous across every SQL clause.",
    "Authentication, browser validation, and TypeScript types do not parameterize queries.",
    "Trusted code owns SQL structure; external values travel through bindings."
  ]
};
