window.COURSE_MODULE = {
  "title": "Find and Prevent SQL Injection Through Review and Testing",
  "graphicAlt": "Three panels show tracing fixed SQL, bound values, and mapped structure to a data-access call; reviewing concatenation, interpolation, raw methods, fragments, wrappers, and API documentation; and testing ordinary punctuation, Unicode, empty values, arrays, and rejected sort choices. Tests assert results, protected database state, and separation of statements from parameters.",
  "narration": "Code review begins with high-signal construction patterns. Search for SQL keywords inside template literals, concatenation near query calls, interpolation in raw methods, dynamically assembled WHERE or ORDER BY clauses, literal-expression helpers, and generic functions that accept complete fragments. These patterns identify places where values may cross into SQL structure. Review wrappers as well as callers; a helper named safeQuery provides no assurance if it concatenates arguments internally.\n\nTrace every query component to its source. Mark fixed SQL syntax, bound values, and dynamic structural fragments separately. Confirm that external values reach the driver's parameter channel. When a request affects a column, operator, direction, or table, locate the closed server-side mapping that produces the fragment. Verify ORM raw methods and tagged-template semantics from library documentation. Also examine tenant scope, authorization conditions, and database-account privileges.\n\nIntegration tests should exercise ordinary and unexpected input as data. Include punctuation, Unicode, long-but-allowed strings, empty values, optional-filter combinations, dynamic sort choices, arrays, and rejected structural choices. Assert results and protected database state, not merely response codes. Add regression tests around previously unsafe construction. A catalog of offensive payloads is less reliable than proving that request values never enter generated statement text. Driver mocks can verify statement-and-parameter separation, while selected real-database tests catch dialect and binding differences.\n\nStatic analysis and lint rules can flag raw-query calls, SQL-bearing template literals, or banned unsafe helpers. Route exceptions through explicit review rather than quiet suppression. Keep raw SQL in a small searchable data-access surface and require tests for its dynamic paths. Automated checks will not understand every library contract, so pair them with design review. The strongest review question remains consistent: does this API bind the value, or insert text into the SQL program? Answering from implementation and documentation is more dependable than judging whether a sample input appears harmless.",
  "narrationPoints": [
    "Search for concatenation, interpolation, raw methods, and literal fragments.",
    "Trace SQL syntax, bound values, and mapped structure to their sources.",
    "Test combinations and unexpected data while asserting database state.",
    "Use static rules to focus human review on security-sensitive escape hatches."
  ]
};
