window.COURSE_MODULE = {
  "title": "Linux Boot Flow: From Firmware to Root Filesystem",
  "graphicAlt": "Conceptual visual of the Linux boot chain from firmware to bootloader, kernel, initramfs, and root filesystem.",
  "narration": "To reason about RAM-backed booting, it helps to understand the normal Linux boot path. At a practical level, firmware starts the machine. On modern systems this is often UEFI, though older systems may use BIOS-style boot. Firmware initializes enough hardware to find a boot target and hand control to a bootloader. The bootloader, such as GRUB, systemd-boot, or another distribution-specific loader, presents entries and loads the Linux kernel, usually with a kernel command line and an initramfs image.\n\nThe kernel starts next. It initializes hardware, memory management, device drivers, and the early environment it needs. The initramfs is then used as early user space. It can load modules, unlock encrypted devices, assemble storage, discover root devices, prepare live-media layers, or run distribution-specific scripts. Eventually the system finds, mounts, or constructs the real root filesystem and switches from early user space into the normal operating system.\n\nRAM-boot designs usually affect this early path. A live system that supports a toram option may use initramfs logic to copy the compressed live image into memory. An overlay design may have early boot scripts that mount a read-only lower layer and a writable tmpfs upper layer before presenting a merged root. A volatile root design may change what is mounted as persistent storage and what is recreated on each boot.\n\nThis is why exact commands vary so much. The safe method depends on the distribution, bootloader, initramfs framework, filesystem layout, encrypted disk setup, secure boot configuration, hardware drivers, and storage naming. A kernel parameter that works on one live distribution may mean nothing on another. A bootloader edit that is harmless on a virtual machine can make a laptop hard to recover if there is no known-good entry or recovery media.\n\nThe lesson is conceptual first. Know where the bootloader, kernel, initramfs, root filesystem, and user space fit. Then test changes in a virtual machine, spare disk, or lab system before touching a primary machine.",
  "narrationPoints": [
    "Firmware starts the boot process.",
    "The bootloader loads the kernel and initramfs.",
    "The initramfs prepares early user space.",
    "The system eventually switches to a root filesystem.",
    "RAM-boot designs usually affect early boot."
  ]
};
