window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Rotation, Expiration, and Least Privilege through distinct, reviewable JavaScript security boundaries.",
  "codeExamples": [
    {
      "title": "Cache one secret version for a bounded TTL",
      "language": "javascript",
      "blurb": "The loader coalesces concurrent access, rejects empty or oversized manager values, caches only an owned bounded buffer, returns a fresh copy, and clears cache storage on expiry.",
      "code": "const MAXIMUM_SECRET_BYTES = 64 * 1024;\n\nfunction validatedSecretReference(reference) {\n  const name = reference?.name;\n  const version = reference?.version;\n  if (typeof name !== \"string\" || !/^[a-z0-9_-]{1,128}$/i.test(name) ||\n      typeof version !== \"string\" || !/^\\d{1,20}$/.test(version)) {\n    throw new TypeError(\"versioned secret reference required\");\n  }\n  return Object.freeze({ name, version });\n}\n\nfunction validSecretBuffer(value) {\n  return Buffer.isBuffer(value) && value.length >= 1 && value.length <= MAXIMUM_SECRET_BYTES;\n}\n\nexport function createVersionedSecretCache(manager, reference, ttlMs = 30_000) {\n  const requested = validatedSecretReference(reference);\n  const rawAccessSecret = manager?.access;\n  if (typeof rawAccessSecret !== \"function\") throw new TypeError(\"secret manager required\");\n  if (!Number.isSafeInteger(ttlMs) || ttlMs < 1 || ttlMs > 5 * 60_000) throw new RangeError(\"secret cache TTL invalid\");\n  const accessSecret = rawAccessSecret.bind(manager);\n  let value = null; let inFlight = null; let timer = null;\n  const expire = () => { value?.fill(0); value = null; timer = null; };\n  return async function load() {\n    if (value !== null) return Buffer.from(value);\n    if (!inFlight) inFlight = accessSecret(requested).then((result) => {\n      const name = result?.name;\n      const version = result?.version;\n      const secretValue = result?.value;\n      if (name !== requested.name || version !== requested.version ||\n          !validSecretBuffer(secretValue)) {\n        throw new Error(\"secret version response invalid\");\n      }\n      value = Buffer.from(secretValue);\n      const loaded = Buffer.from(value);\n      clearTimeout(timer); timer = setTimeout(expire, ttlMs); timer.unref?.();\n      return loaded;\n    }).finally(() => { inFlight = null; });\n    const loaded = await inFlight;\n    return Buffer.from(loaded);\n  };\n}\n"
    },
    {
      "title": "Rotate consumers between explicit secret versions",
      "language": "javascript",
      "blurb": "Rotation validates a nonempty bounded candidate, probes an owned temporary copy, clears that copy, and only then atomically changes the active version with a bounded rollback window.",
      "code": "const MAXIMUM_ROTATION_SECRET_BYTES = 64 * 1024;\nconst clearBuffer = Function.prototype.call.bind(Buffer.prototype.fill);\n\nexport async function rotateSecretReference(store, manager, name, candidateVersion, approvalId) {\n  if (typeof name !== \"string\" || !/^[a-z0-9_-]{1,128}$/i.test(name) ||\n      typeof candidateVersion !== \"string\" || !/^\\d{1,20}$/.test(candidateVersion) ||\n      typeof approvalId !== \"string\" || !/^[A-Za-z0-9_-]{8,128}$/.test(approvalId)) {\n    throw new TypeError(\"versioned rotation target, approval, and adapters required\");\n  }\n  const rawAccessCandidate = manager?.access;\n  const rawProbeCandidate = manager?.probe;\n  const rawLoadCurrent = store?.current;\n  const rawCompareAndSwap = store?.compareAndSwap;\n  if (typeof rawAccessCandidate !== \"function\" ||\n      typeof rawProbeCandidate !== \"function\" ||\n      typeof rawLoadCurrent !== \"function\" ||\n      typeof rawCompareAndSwap !== \"function\") {\n    throw new TypeError(\"versioned rotation target, approval, and adapters required\");\n  }\n  const accessCandidate = rawAccessCandidate.bind(manager);\n  const probeCandidate = rawProbeCandidate.bind(manager);\n  const loadCurrent = rawLoadCurrent.bind(store);\n  const compareAndSwap = rawCompareAndSwap.bind(store);\n  const candidate = await accessCandidate({ name, version: candidateVersion });\n  const candidateName = candidate?.name;\n  const returnedVersion = candidate?.version;\n  const candidateValue = candidate?.value;\n  if (candidateName !== name || returnedVersion !== candidateVersion ||\n      !Buffer.isBuffer(candidateValue) || candidateValue.length < 1 ||\n      candidateValue.length > MAXIMUM_ROTATION_SECRET_BYTES) {\n    throw new Error(\"rotation secret response invalid\");\n  }\n  const probeValue = Buffer.from(candidateValue);\n  let probeResult;\n  try { probeResult = await probeCandidate(probeValue); }\n  finally { clearBuffer(probeValue, 0); }\n  if (probeResult !== true) throw new Error(\"rotation secret probe failed\");\n\n  const current = await loadCurrent(name);\n  const previousVersion = current?.version;\n  if (typeof previousVersion !== \"string\" || !/^\\d{1,20}$/.test(previousVersion) ||\n      previousVersion === candidateVersion) {\n    throw new Error(\"current secret version invalid\");\n  }\n  const changed = await compareAndSwap(name, previousVersion, Object.freeze({\n    version: candidateVersion, previous: previousVersion,\n    rollbackUntil: new Date(Date.now() + 15 * 60 * 1000).toISOString(), approvalId\n  }));\n  if (changed !== true) throw new Error(\"secret rotation conflict\");\n  return Object.freeze({ active: candidateVersion, previous: previousVersion, approvalId });\n}\n"
    }
  ]
};
