window.COURSE_MODULE = {
  "title": "Why Secrets Management Matters in Node.js",
  "graphicAlt": "Two-path comparison for Why Secrets Management Matters in Node.js in Secrets Management in Node.js: an unsafe flow bypasses the relevant control, while the approved flow passes through enforcement, bounded processing, and an auditable outcome.",
  "narration": "Secrets are values that grant access, prove identity, decrypt data, sign tokens, or authorize operations. In a Node.js application, they often sit quietly behind everyday features: database connections, third-party APIs, OAuth clients, JWT signing, sessions, webhooks, cloud services, message queues, npm publishing, and deployment automation. When one of those values leaks, a small coding or workflow mistake can become account compromise, data exposure, fraudulent use, cloud cost abuse, or supply chain impact.\n\nA typical project starts with a local .env file and one developer. Later it grows into staging, production, CI/CD, cloud services, containers, serverless functions, multiple developers, support workflows, and external integrations. Secrets spread unless the team designs a disciplined path for them. They appear in machines, repositories, logs, build systems, screenshots, Docker layers, support tickets, chat messages, crash reports, shell history, and copied documentation.\n\nSecrets management is a lifecycle, not a one-time configuration step and not just putting a value in an environment variable. The lifecycle includes identifying secrets, storing them safely, controlling access, delivering them to runtime, limiting privilege, rotating them, redacting them from observability tools, detecting leaks, responding to exposure, and assigning ownership. The goal is to make secret use intentional, minimal, protected, observable, and recoverable.",
  "narrationPoints": [
      "Secrets are values that grant access, prove identity, decrypt data, sign tokens, or authorize operations.",
      "Secrets spread unless the team designs a disciplined path for them.",
      "Secrets management is a lifecycle, not a one-time configuration step and not just putting a value in an environment variable.",
      "In a Node.js application, they often sit quietly behind everyday features: database connections, third-party APIs, OAuth clients, JWT signing, sessions, webhooks, cloud services, message queues, npm publishing, and deployment automation.",
      "The lifecycle includes identifying secrets, storing them safely, controlling access, delivering them to runtime, limiting privilege, rotating them, redacting them from observability tools, detecting leaks, responding to exposure, and assigning ownership.",
      "The goal is to make secret use intentional, minimal, protected, observable, and recoverable."
  ]
};
