window.COURSE_MODULE = {
  "title": "CI/CD, Build Systems, and Deployment Secrets",
  "graphicAlt": "Trust-boundary map for CI/CD, Build Systems, and Deployment Secrets in Secrets Management in Node.js, with distinct caller, application, platform, and external-service zones connected only through labeled validation and authorization checkpoints.",
  "narration": "CI/CD secrets are attractive targets because automation can change real systems. A Node.js pipeline might install dependencies, run tests, build an artifact, publish a package, build a container, deploy to staging, and then deploy to production. Each stage should have only the secrets it needs. Package publishing tokens, cloud credentials, SSH keys, signing keys, scanner tokens, artifact upload credentials, notification webhooks, and deployment tokens should be scoped to specific workflows, repositories, branches, roles, environments, or deployment targets when possible.\n\nAvoid exposing production secrets to untrusted pull requests, forks, preview builds, broad test jobs, dependency scripts, or jobs that do not need them. Build logs, npm lifecycle scripts, failed commands, test output, deployment tools, and debug traces can reveal values unexpectedly. CI/CD systems should mask secrets where possible, but masking is not a replacement for minimizing exposure. Some secrets should only be available after approval gates or only inside protected production deployment workflows.\n\nPrefer short-lived credentials or trusted identity-based publishing and deployment flows where available. Rotate npm tokens, cloud credentials, SSH keys, signing keys, and deployment tokens when they are exposed or no longer needed. Keep enough evidence to review which workflow used which secret, without exposing secret values. The practical question at each stage is simple: what does this job need, what would happen if that secret leaked, and can we reduce the blast radius.",
  "narrationPoints": [
      "Package publishing tokens, cloud credentials, SSH keys, signing keys, scanner tokens, artifact upload credentials, notification webhooks, and deployment tokens should be scoped to specific workflows, repositories, branches, roles, environments, or deployment targets when possible.",
      "Avoid exposing production secrets to untrusted pull requests, forks, preview builds, broad test jobs, dependency scripts, or jobs that do not need them.",
      "Rotate npm tokens, cloud credentials, SSH keys, signing keys, and deployment tokens when they are exposed or no longer needed.",
      "Some secrets should only be available after approval gates or only inside protected production deployment workflows.",
      "A Node.js pipeline might install dependencies, run tests, build an artifact, publish a package, build a container, deploy to staging, and then deploy to production.",
      "Each stage should have only the secrets it needs."
  ]
};
