window.COURSE_MODULE = {
  "title": "Leaks, Detection, and Incident Response",
  "graphicAlt": "Control-and-evidence diagram for Leaks, Detection, and Incident Response in Secrets Management in Node.js, linking each security decision to the protected asset, the enforcing component, the failure state, and the observable verification signal.",
  "narration": "When a secret is exposed or suspected to be exposed, treat it as compromised unless there is strong evidence otherwise. The first goal is containment. Immediate actions may include revocation, rotation, disabling tokens, removing exposed material, pausing affected workflows, and reviewing usage logs. Removing a secret from the latest commit does not remove it from Git history, package artifacts, container layers, caches, screenshots, logs, backups, search indexes, or external copies.\n\nIncident response should identify what the secret could access, when it was exposed, whether it was used, which systems require recovery, what evidence must be retained, and who needs to be notified. Secret scanning should exist in repositories, CI/CD, container images, build artifacts, logs, and cloud environments where possible. Detection is not just about finding strings; it is about connecting exposed credentials to real authority and real systems.\n\nA calm workflow matters more than blame during the first hour. Contain, rotate, investigate, validate, communicate, and improve controls. Post-incident work should reduce recurrence through workflow changes, pre-commit hooks, permissions, rotation automation, dependency-script controls, safer CI/CD scopes, redaction fixes, and training. Response plans should be practiced before production exposure occurs, because practiced teams move faster and make fewer damaging guesses under pressure.",
  "narrationPoints": [
      "Removing a secret from the latest commit does not remove it from Git history, package artifacts, container layers, caches, screenshots, logs, backups, search indexes, or external copies.",
      "Incident response should identify what the secret could access, when it was exposed, whether it was used, which systems require recovery, what evidence must be retained, and who needs to be notified.",
      "Post-incident work should reduce recurrence through workflow changes, pre-commit hooks, permissions, rotation automation, dependency-script controls, safer CI/CD scopes, redaction fixes, and training.",
      "Contain, rotate, investigate, validate, communicate, and improve controls.",
      "Secret scanning should exist in repositories, CI/CD, container images, build artifacts, logs, and cloud environments where possible.",
      "Response plans should be practiced before production exposure occurs, because practiced teams move faster and make fewer damaging guesses under pressure."
  ]
};
