window.COURSE_MODULE = {
  "title": "Course Summary and Practical Checklist",
  "graphicAlt": "Left-to-right security workflow for Course Summary and Practical Checklist in Secrets Management in Node.js: untrusted input crosses a labeled boundary, a validating component enforces policy, and only a verified result reaches the protected resource.",
  "narration": "Secrets management in Node.js starts with recognition. Identify values that grant access, prove identity, decrypt data, sign tokens, or authorize operations. Keep real secrets out of source code, committed files, frontend bundles, Docker images, logs, tickets, screenshots, and copied documentation. Use documented local development patterns, such as .env.example files, without sharing production credentials or turning developer machines into uncontrolled stores of production access.\n\nStore production secrets in controlled secret-management systems, and treat environment variables as delivery mechanisms rather than complete controls. Scope CI/CD secrets carefully and avoid exposing them to untrusted builds, broad jobs, or workflows that do not need them. Apply least privilege, ownership, expiration, and rotation expectations. Keep server-side secrets server-side, avoid baking secrets into images or static artifacts, and make runtime delivery compatible with future rotation.\n\nA practical first week plan is direct: find secrets in repositories, create .env.example files, review CI/CD secret scope, remove production credentials from local development, confirm log redaction, identify rotation owners, check container images for embedded secrets, and document the incident response path for leaked secrets. Then build secrets review into pull requests, deployment reviews, CI/CD workflows, operational runbooks, monitoring, and incident response. The goal is durable control over the full secret lifecycle.",
  "narrationPoints": [
      "Identify values that grant access, prove identity, decrypt data, sign tokens, or authorize operations.",
      "Keep server-side secrets server-side, avoid baking secrets into images or static artifacts, and make runtime delivery compatible with future rotation.",
      "A practical first week plan is direct: find secrets in repositories, create .env.example files, review CI/CD secret scope, remove production credentials from local development, confirm log redaction, identify rotation owners, check container images for embedded secrets, and document the incident response path for leaked secrets.",
      "Scope CI/CD secrets carefully and avoid exposing them to untrusted builds, broad jobs, or workflows that do not need them.",
      "Store production secrets in controlled secret-management systems, and treat environment variables as delivery mechanisms rather than complete controls.",
      "Then build secrets review into pull requests, deployment reviews, CI/CD workflows, operational runbooks, monitoring, and incident response."
  ]
};
