window.COURSE_MODULE = {
  "title": "Why OT Monitoring Matters",
  "graphicAlt": "Blank course graphic placeholder",
  "narration": "OT environments can operate for years with communication that appears stable, yet blind spots accumulate as vendors add remote access, equipment is replaced, and temporary connections become permanent. Monitoring reveals these changes and gives the organization evidence about the architecture it actually operates.\n\nEarly detection can limit operational impact. A new device, unexpected protocol, unusual engineering session, or communication across a trust boundary may be investigated before it develops into loss of visibility or control. Monitoring also identifies failed controls, such as an inactive sensor or firewall rule that permits more traffic than intended.\n\nDuring incident response, telemetry helps establish a timeline, affected assets, communication paths, user activity, and process conditions. It can show whether suspicious activity remained in enterprise systems, reached site operations, or interacted with controllers. This evidence supports safer containment and more confident recovery.\n\nMonitoring improves asset knowledge as well. Observed devices and communication can update inventory, reveal dormant systems, and identify unmanaged connections. Vulnerability teams can use this context to understand reachability and prioritize findings. Architecture teams can verify whether documented segmentation matches real traffic.\n\nThe operational purpose remains central. Security monitoring protects production and physical processes by improving awareness, not by issuing uncontrolled automated responses. Isolating an OT asset may remove a cyber pathway but also remove a necessary control or alarm. Response workflows should define which actions require operator or engineering approval.\n\nEffective monitoring reduces uncertainty. It allows teams to distinguish normal behavior from change, detect conditions that deserve investigation, and coordinate decisions using shared evidence. Without visibility, incident response begins with guesswork at the moment the organization can least afford it.",
  "narrationPoints": [
    "OT environments can operate for years with communication that appears stable, yet blind spots accumulate as vendors add remote access, equipment is replaced, and...",
    "Monitoring reveals these changes and gives the organization evidence about the architecture it actually operates.",
    "Early detection can limit operational impact.",
    "A new device, unexpected protocol, unusual engineering session, or communication across a trust boundary may be investigated before it develops into loss of...",
    "Monitoring also identifies failed controls, such as an inactive sensor or firewall rule that permits more traffic than intended.",
    "During incident response, telemetry helps establish a timeline, affected assets, communication paths, user activity, and process conditions."
  ]
};
