window.COURSE_MODULE = {
  "title": "OT Telemetry Sources",
  "graphicAlt": "Blank course graphic placeholder",
  "narration": "Industrial network traffic is a foundational telemetry source. It shows which devices communicate, the protocols they use, the direction and timing of connections, and in some cases the industrial operations represented by those messages. Traffic at trust boundaries is especially useful for understanding movement between enterprise, site, and control functions.\n\nControllers and PLC-related communications can reveal logic transfers, mode changes, programming sessions, and unusual peers when the protocol and collection point provide that visibility. HMIs and SCADA applications may record operator logons, alarms, commands, application faults, and communication loss.\n\nEngineering workstations offer high-value evidence because they contain privileged tools. Endpoint, application, and authentication logs can show users, processes, removable media, project changes, and connections to control devices. Collection must be tested to avoid affecting supported applications.\n\nHistorians provide process trends and operating context. They can help investigators compare a cyber observation with changes in equipment state or production. Historian access logs and replication paths may also reveal cross-boundary activity.\n\nRemote-access gateways, VPNs, jump hosts, and vendor platforms should record identity, session times, destination, approval, and sensitive actions where feasible. Firewalls and network devices provide permitted and denied connections, configuration changes, link status, and boundary events. Identity systems contribute authentication, privilege, and account-lifecycle evidence.\n\nTelemetry quality matters more than raw volume. Time synchronization, asset identity, retention, integrity, access control, and clear ownership determine whether records support investigation. Build a source map that explains what each system can report, what it cannot see, how long data is retained, and who responds when the source fails.",
  "narrationPoints": [
    "Industrial network traffic is a foundational telemetry source.",
    "It shows which devices communicate, the protocols they use, the direction and timing of connections, and in some cases the industrial operations represented by those...",
    "Traffic at trust boundaries is especially useful for understanding movement between enterprise, site, and control functions.",
    "Controllers and PLC-related communications can reveal logic transfers, mode changes, programming sessions, and unusual peers when the protocol and collection point...",
    "HMIs and SCADA applications may record operator logons, alarms, commands, application faults, and communication loss.",
    "Engineering workstations offer high-value evidence because they contain privileged tools."
  ]
};
