window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Hostname Validation and Service Identity with reviewable Python controls.",
  "codeExamples": [
    {
      "title": "Connect with hostname verification",
      "language": "python",
      "blurb": "The intended DNS name is supplied during the handshake while default chain and hostname checks remain enabled.",
      "code": "import re\nimport socket\nimport ssl\n\nDNS_NAME = re.compile(\n    r\"(?=.{1,253}\\Z)(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.)*\"\n    r\"[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\Z\"\n)\n\ndef open_verified_tls(hostname: str, port: int = 443) -> ssl.SSLSocket:\n    if not isinstance(hostname, str) or DNS_NAME.fullmatch(hostname) is None:\n        raise ValueError(\"TLS hostname rejected\")\n    if type(port) is not int or not 1 <= port <= 65_535:\n        raise ValueError(\"TLS port rejected\")\n    context = ssl.create_default_context()\n    context.minimum_version = ssl.TLSVersion.TLSv1_2\n    raw = socket.create_connection((hostname, port), timeout=5)\n    try:\n        return context.wrap_socket(raw, server_hostname=hostname)\n    except BaseException:\n        raw.close()\n        raise\n"
    },
    {
      "title": "Validate the full authority of every redirect destination",
      "language": "python",
      "blurb": "Every hop must use HTTPS, an approved hostname, no URL credentials, and port 443; environment-derived proxies and CA overrides are disabled, and redirect responses are closed.",
      "code": "from urllib.parse import urljoin, urlsplit\nimport requests\n\nAPPROVED_HOSTS = {\"api.example.com\", \"api-backup.example.com\"}\nMAX_URL_BYTES = 2_048\n\ndef checked_url(value: object) -> str:\n    if (\n        not isinstance(value, str)\n        or not value\n        or len(value.encode(\"utf-8\")) > MAX_URL_BYTES\n        or any(character.isspace() or ord(character) < 0x20 for character in value)\n    ):\n        raise ValueError(\"redirect destination rejected\")\n    return value\n\ndef close_redirect_response(\n    response: requests.Response,\n    primary_error: BaseException | None = None,\n) -> None:\n    try:\n        response.close()\n    except BaseException as cleanup_error:\n        if primary_error is not None:\n            raise BaseExceptionGroup(\n                \"redirect validation and response cleanup failed\",\n                [primary_error, cleanup_error],\n            )\n        raise RuntimeError(\"redirect response cleanup failed\") from cleanup_error\n    if primary_error is not None:\n        raise primary_error\n\ndef get_without_crossing_trust_boundary(url: str) -> requests.Response:\n    current = checked_url(url)\n    with requests.Session() as session:\n        session.trust_env = False\n        for _ in range(4):\n            target = urlsplit(current)\n            try:\n                port = target.port\n            except ValueError as error:\n                raise ValueError(\"redirect destination rejected\") from error\n            if (\n                target.scheme != \"https\"\n                or target.hostname not in APPROVED_HOSTS\n                or target.username is not None\n                or target.password is not None\n                or port not in {None, 443}\n            ):\n                raise ValueError(\"redirect destination rejected\")\n            response = session.get(\n                current,\n                allow_redirects=False,\n                timeout=(3, 10),\n            )\n            try:\n                is_redirect = response.is_redirect\n            except BaseException as error:\n                close_redirect_response(response, error)\n                raise AssertionError(\"unreachable\")\n            if type(is_redirect) is not bool:\n                close_redirect_response(\n                    response,\n                    ValueError(\"redirect response evidence rejected\"),\n                )\n            if not is_redirect:\n                return response\n            try:\n                location = checked_url(response.headers[\"Location\"])\n                next_url = checked_url(urljoin(current, location))\n            except BaseException as error:\n                close_redirect_response(response, error)\n                raise AssertionError(\"unreachable\")\n            close_redirect_response(response)\n            current = next_url\n    raise RuntimeError(\"redirect limit exceeded\")\n"
    }
  ]
};
