window.COURSE_MODULE = {
  "title": "What Validation Checks",
  "graphicAlt": "Layered architecture diagram for What Validation Checks, showing Python client, TLS endpoint, certificate chain, hostname, and trust store; labeled arrows identify accepted and rejected validation paths and the point where unsafe input or behavior is rejected.",
  "narration": "Certificate validation is a set of checks, not a single certificate exists decision. A client checks whether the certificate chains to an issuer it trusts, whether signatures are valid at a high level, whether the certificate is within its valid time window, whether the name matches the intended service, and whether the certificate is appropriate for the expected purpose. Skipping any of these concepts can weaken the trust model.\n\nTime checks matter because certificates have not-before and not-after dates. A certificate can be too new, expired, or outside an expected rotation period. Expiration is not just administrative paperwork. It is part of how trust is bounded over time. Python services should not ignore expired certificates simply because a dependency is important. Instead, teams need renewal processes, monitoring, and safe failure behavior.\n\nIssuer trust and certificate policy concepts matter because not every authority is trusted for every purpose. Publicly trusted certificates, private certificate authorities, and environment-specific roots have different roles. Local trust configuration can add approved private roots, but that decision should be documented and limited to the intended environment. A certificate from the wrong issuer or wrong trust anchor should not be accepted just because it is technically well formed.\n\nRevocation concepts such as certificate revocation lists and online status checks exist to address certificates that should no longer be trusted before their normal expiration. Different clients and environments handle revocation differently, so teams should understand their practical risk and platform behavior. The stable lesson is that validation is a bundle of trust decisions: chain, issuer, dates, name, purpose, policy, and local configuration all contribute.",
  "narrationPoints": [
    "Certificate validation is a set of checks, not a single certificate exists decision.",
    "Time checks matter because certificates have not-before and not-after dates.",
    "Instead, teams need renewal processes, monitoring, and safe failure behavior.",
    "Publicly trusted certificates, private certificate authorities, and environment-specific roots have different roles.",
    "Different clients and environments handle revocation differently, so teams should understand their practical risk and platform behavior.",
    "Expiration is not just administrative paperwork."
  ]
};
