window.COURSE_MODULE = {
  "title": "Testing and Reviewing Validation",
  "graphicAlt": "Blank placeholder image for Testing and Reviewing Validation.",
  "narration": "Validation code deserves the same testing discipline as business logic because it defines what the application will accept. Unit tests should cover valid examples, but they should also include negative tests for missing fields, malformed values, unexpected types, overlong strings, empty arrays, duplicate items, invalid enum values, and extra properties. Boundary tests are especially useful because validators often fail at the edges: maximum lengths, minimum amounts, date limits, nesting depth, and collection size.\n\nMalformed input tests help confirm that the application fails safely. Send strings where numbers are expected, objects where arrays are expected, null where a value is required, and values that parse ambiguously. Property-based testing can be useful at a high level because it explores many variations instead of only hand-picked cases. API contract tests help keep clients, servers, schemas, and documentation aligned as the system evolves.\n\nCode review should ask direct questions. Where does external data enter this function. Is it typed as unknown before validation. Does the schema reject unexpected fields. Are type assertions justified by prior checks. Are client-side and server-side rules aligned without relying on the client. Are domain invariants enforced somewhere durable. Do error messages reveal only what a client needs to fix the request. Those questions keep review practical instead of turning validation into a style debate.\n\nLogging invalid input requires balance. Logs should support troubleshooting and abuse detection, but they should not store secrets, session tokens, passwords, full payment data, or unnecessary personal information. It is often enough to log a request identifier, endpoint, validation failure category, user or tenant context when appropriate, and safe metadata such as field names. Good tests and careful logs turn validation from a pile of checks into an observable, maintainable security control.",
  "narrationPoints": [
    "Validation code deserves the same testing discipline as business logic because it defines what the application will accept.",
    "Unit tests should cover valid examples, but they should also include negative tests for missing fields, malformed values, unexpected types, overlong strings, empty arrays.",
    "Boundary tests are especially useful because validators often fail at the edges: maximum lengths, minimum amounts, date limits, nesting depth, and collection size.",
    "Malformed input tests help confirm that the application fails safely.",
    "Send strings where numbers are expected, objects where arrays are expected, null where a value is required, and values that parse ambiguously.",
    "Property-based testing can be useful at a high level because it explores many variations instead of only hand-picked cases."
  ]
};
