window.COURSE_MODULE = {
  "title": "Course Summary",
  "graphicAlt": "Blank placeholder image for Course Summary.",
  "narration": "The main lesson is simple: TypeScript helps structure code, but runtime validation is still required for external input. Types improve the developer experience and catch many mistakes before deployment, yet they disappear at runtime. Any value that crosses a trust boundary should be treated as unknown until the application has checked its shape, format, limits, and context. That mindset prevents static types from being confused with security validation.\n\nStrong validation starts by identifying boundaries. Request bodies, parameters, headers, cookies, browser storage, WebSocket messages, postMessage events, environment variables, configuration files, queues, files, and SDK responses can all carry surprising data. At those boundaries, schemas and guards should parse unknown values into trusted internal objects. Libraries such as Zod, Joi, Yup, and Ajv can help, especially when teams keep schemas, inferred types, tests, and API contracts aligned.\n\nGood validation also distinguishes transport shape from business meaning. A payload may be structurally valid while still violating ownership, workflow, date, money, or cross-field rules. Transport validators should reject malformed and unexpected input. Domain validation should protect invariants that must remain true inside the application. That separation makes the code easier to reason about and reduces the chance that an API convenience becomes a business logic weakness.\n\nFinally, validation needs evidence. Negative tests, boundary tests, malformed input tests, contract tests, and focused code review questions all help confirm that the rules work under pressure. Safe error responses and careful logging make failures useful without exposing unnecessary detail. In practical TypeScript engineering, the goal is not to validate everything everywhere. The goal is to make runtime data trustworthy before it reaches the typed application logic that matters most.",
  "narrationPoints": [
    "The main lesson is simple: TypeScript helps structure code, but runtime validation is still required for external input.",
    "Types improve the developer experience and catch many mistakes before deployment, yet they disappear at runtime.",
    "Any value that crosses a trust boundary should be treated as unknown until the application has checked its shape, format, limits, and context.",
    "That mindset prevents static types from being confused with security validation.",
    "Strong validation starts by identifying boundaries.",
    "Request bodies, parameters, headers, cookies, browser storage, WebSocket messages, postMessage events, environment variables, configuration files, queues, files, and SDK responses can all carry surprising."
  ]
};
