window.COURSE_MODULE = {
  "title": "Page Models, Handlers, Routing, and Organization",
  "graphicAlt": "Purpose-based page folders and visible state-changing handlers make access, input, side effects, and output easier to review.",
  "narration": "Page organization affects how well a Razor Pages application can be reviewed. A small application may begin with only a few pages, but it can grow into public pages, account pages, user dashboards, administrative workflows, support tools, reporting pages, upload pages, and operational views. When those areas are mixed together without clear structure, access expectations become harder to inspect.\n\nPage models and handler methods should communicate intent. A handler that only renders a view has different expectations from a handler that changes account settings, updates a workflow, modifies configuration, or records an approval. Handler names, folder placement, and page model structure should help reviewers identify state-changing actions quickly, especially in pages with multiple handlers.\n\nFolder structure is a useful review tool. Public pages, authenticated user workflows, administrative pages, sensitive data workflows, and operational pages should be separated in ways that match the application's access model. Folder-level conventions can then support consistent authorization and reduce one-off page decisions.\n\nRouting and friendly URLs should help users and reviewers, but they should not hide sensitive behavior. A friendly route can make an application feel clean while still leading to a handler that changes important data. Review should follow the page model and handler behavior, not only the visible URL.\n\nShared layouts, partial views, tag helpers, and page conventions can improve consistency. They can also hide exceptions if teams rely on them without review. Shared elements are helpful when they make repeated decisions easier to apply, but a page with unusual access rules, unusual form behavior, or sensitive data still deserves direct inspection.\n\nA practical review asks four questions for each page area: who can reach it, what state can change, what request data is accepted, and what data is returned. If the page organization makes those answers obvious, Razor Pages becomes easier to maintain safely as the application grows.",
  "narrationPoints": [
    "Page organization affects how well a Razor Pages application can be reviewed.",
    "Page models and handler methods should communicate intent.",
    "Folder structure is a useful review tool.",
    "Routing and friendly URLs should help users and reviewers, but they should not hide sensitive behavior.",
    "Shared layouts, partial views, tag helpers, and page conventions can improve consistency."
  ]
};
