window.COURSE_MODULE = {
  "title": "Forms, Antiforgery, and Request Intent",
  "graphicAlt": "Safe retrieval is separate from state-changing forms, which require request-intent validation and authorization before mutation.",
  "narration": "Razor Pages applications commonly use browser forms for account changes, profile updates, search filters, approvals, edits, uploads, preferences, and administrative workflows. Forms are productive and familiar, but a form that changes server-side state needs more than a signed-in browser session. The application needs confidence that the request came from the intended user interaction.\n\nA logged-in browser request does not automatically prove request intent. Browsers carry cookies according to browser rules, and those cookies may represent an authenticated session. Antiforgery validation adds a request-intent check for unsafe browser requests by requiring a value that the application expects and validates before processing the state change.\n\nFramework form helpers and Razor conventions often make antiforgery support feel routine. That is useful, but teams should still review nonstandard forms, custom HTML, partial views, AJAX submissions, JavaScript-driven requests, and handlers that sit outside the expected pattern. The places that differ from convention are the places most likely to need attention.\n\nGET-style requests should not modify server-side state. A request used for navigation, display, filtering, or lookup should not approve an item, change a setting, trigger a workflow, delete a record, or update a user's state. Keeping state changes in handlers that expect unsafe methods makes request intent easier to reason about and easier to protect.\n\nCSRF protection is separate from authentication, authorization, and CORS. Authentication identifies the user. Authorization decides whether the user may perform the action. CORS controls certain browser cross-origin read behavior. Antiforgery validation addresses a different concern: whether an unsafe browser request reflects the expected user interaction.\n\nFailure handling matters. Token validation failures should be predictable, safe, and useful to operators. The user-facing response should not expose sensitive implementation details. The operational record should provide enough context to understand which page, handler, and request category failed without recording secrets or sensitive form values.",
  "narrationPoints": [
    "Razor Pages applications commonly use browser forms for account changes, profile updates, search filters, approvals, edits, uploads, preferences, and administrative workflows.",
    "A logged-in browser request does not automatically prove request intent.",
    "Framework form helpers and Razor conventions often make antiforgery support feel routine.",
    "GET-style requests should not modify server-side state.",
    "CSRF protection is separate from authentication, authorization, and CORS."
  ]
};
