window.COURSE_MODULE = {
  "title": "Engineering Implications of FedRAMP High",
  "graphicAlt": "Instructional illustration for Engineering Implications of FedRAMP High.",
  "narration": "FedRAMP High has direct engineering implications. Strong identity and access control, privileged access management, least privilege, segmentation, encryption, secure configuration, vulnerability management, change control, audit logging, monitoring, incident response readiness, backup and recovery, resilience, secure development practices, infrastructure-as-code, and configuration baselines all become part of the operating picture.\n\nHigh-impact services should be secure, observable, recoverable, and evidence-producing by design. Secure means controls are built into architecture and workflows rather than patched on later. Observable means security-relevant events can be collected, protected, reviewed, and used for investigation. Recoverable means the service can respond to disruption in ways that match mission expectations. Evidence-producing means normal operations generate records that support assessment and monitoring.\n\nEngineering teams should reduce manual ambiguity wherever possible. Infrastructure-as-code can help enforce consistent environments and preserve change history. Configuration baselines can reduce drift. Centralized logging and monitoring can support detection and investigation. Automated vulnerability workflows can make remediation more visible. Access reviews, approval paths, and administrative logging can support accountability. These practices help the service sustain High expectations over time.\n\nHigh also requires maintainability. A control that depends on one specialist remembering an undocumented procedure is fragile. A control built into deployment pipelines, access systems, monitoring dashboards, ticketing workflows, and incident processes is more resilient. The engineering goal is not simply to produce evidence for an assessor; it is to operate a service whose security posture can be understood and maintained under pressure.",
  "narrationPoints": [
    "FedRAMP High has direct engineering implications.",
    "High-impact services should be secure, observable, recoverable, and evidence-producing by design.",
    "Engineering teams should reduce manual ambiguity wherever possible.",
    "High also requires maintainability."
  ]
};
