window.COURSE_MODULE = {
  "title": "Evidence and Preservation",
  "graphicAlt": "Placeholder illustration for evidence preservation",
  "narration": "Evidence is useful only when the organization can trust how it was collected and handled. In DFIR, evidence integrity means preserving information in a way that supports reliable analysis. That does not mean every case requires courtroom-grade procedures, but it does mean analysts should avoid unnecessary changes, document collection steps, and keep original sources separate from working copies whenever practical.\n\nChain of custody is the documentation that shows how evidence moved from collection to analysis to storage. It should identify what was collected, when it was collected, where it came from, who collected it, who received it, and how it was protected. This documentation is especially important when incidents may involve regulatory reporting, employee investigations, insurance claims, litigation, law enforcement, or customer commitments.\n\nCommon evidence sources include logs, disk images, memory captures, network data, cloud records, screenshots, notes, authentication events, email records, and administrative audit trails. Each source has different strengths. Memory may reveal running processes or network connections that never touched disk. Disk images may preserve deleted files and operating system artifacts. Cloud audit logs may show identity activity that is invisible from the endpoint.\n\nA practical rule is to preserve before changing systems when the situation allows. Before wiping a host, rotating every credential, deleting a mailbox rule, or shutting down a workload, consider what evidence may disappear. During urgent containment, safety comes first, but even then notes matter. Record what was changed, when it was changed, and why. Those details help later analysts understand the timeline instead of mistaking response activity for attacker activity.",
  "narrationPoints": [
    "Evidence is useful only when the organization can trust how it was collected and handled.",
    "In DFIR, evidence integrity means preserving information in a way that supports reliable analysis.",
    "That does not mean every case requires courtroom-grade procedures, but it does mean analysts should avoid unnecessary changes, document collection steps, and keep original.",
    "Chain of custody is the documentation that shows how evidence moved from collection to analysis to storage.",
    "It should identify what was collected, when it was collected, where it came from, who collected it, who received it, and how it was.",
    "This documentation is especially important when incidents may involve regulatory reporting, employee investigations, insurance claims, litigation, law enforcement, or customer commitments."
  ]
};
