window.COURSE_MODULE = {
  "title": "Common DFIR Data Sources",
  "graphicAlt": "Placeholder illustration for common DFIR data sources",
  "narration": "DFIR depends on telemetry. Endpoint logs can show process creation, service changes, file modifications, PowerShell activity, scheduled tasks, USB usage, and security tool events. Windows Event Logs are especially important in many enterprise environments because they can reveal logons, privilege use, account changes, policy changes, and system activity. Endpoint Detection and Response telemetry may add richer behavioral context, but it should still be interpreted against the broader timeline.\n\nIdentity and authentication logs often tell the story of access. They can show successful and failed logins, multi-factor prompts, impossible travel patterns, new device registrations, token activity, conditional access outcomes, and administrative actions. In many modern incidents, identities are the path through the environment, so authentication records can be as important as endpoint artifacts.\n\nNetwork and infrastructure data provide another angle. Firewall logs, proxy logs, DNS logs, VPN records, packet captures, and NetFlow can show connections between systems and external destinations. Email records can reveal phishing delivery, forwarding rules, message access, attachment activity, and user interaction. Cloud audit logs can show changes to storage, compute, identity, secrets, applications, and administrative consoles.\n\nSIEM data can help correlate these sources, but the SIEM is only as good as what it receives and retains. Backups and snapshots may support recovery and forensic comparison. The practical lesson is to know your data sources before the incident. Understand what is logged, how long it is retained, who can access it, how to export it, and what blind spots exist. During an incident, the team should not be discovering for the first time that critical evidence was never collected.",
  "narrationPoints": [
    "DFIR depends on telemetry.",
    "Endpoint logs can show process creation, service changes, file modifications, PowerShell activity, scheduled tasks, USB usage, and security tool events.",
    "Windows Event Logs are especially important in many enterprise environments because they can reveal logons, privilege use, account changes, policy changes, and system activity.",
    "Endpoint Detection and Response telemetry may add richer behavioral context, but it should still be interpreted against the broader timeline.",
    "Identity and authentication logs often tell the story of access.",
    "They can show successful and failed logins, multi-factor prompts, impossible travel patterns, new device registrations, token activity, conditional access outcomes, and administrative actions."
  ]
};
