window.COURSE_MODULE = {
  "title": "Prevent Log Injection and Preserve Event Boundaries",
  "graphicAlt": "Two-path infographic showing untrusted newline, control, and delimiter characters creating forged-looking records when interpolated into plain-text log syntax. The safer path keeps server-controlled event name and severity separate, places the bounded untrusted value inside one structured field, and preserves that field through serialization, export, terminal, dashboard, and SIEM rendering. The central principle states that data is not record syntax.",
  "narration": "Log injection occurs when untrusted data changes how a telemetry record is interpreted. A username, path, header, or message can contain carriage returns, line feeds, control sequences, delimiters, or text that resembles another event. When application code builds a plain-text line by interpolation, attacker-controlled characters may blur record boundaries or create a forged-looking entry. The problem is not limited to newlines; it is a confusion between data and the syntax that defines the record.\n\nPrefer structured serialization. The application supplies a server-controlled event name and severity, then places validated or bounded untrusted values in dedicated fields. A capable serializer encodes those values as data rather than asking the handler to construct log syntax. This gives collectors and query tools clearer boundaries and avoids brittle application-wide character replacement. Limit the length of request-controlled values as well, because even correctly encoded data can consume storage, overload indexing, or make dashboards unusable.\n\nStructured output does not finish the security work. Exporters may convert JSON into delimited text, terminals may interpret control sequences, and dashboards or HTML log viewers may render fields unsafely. SIEM ingestion rules can also split, truncate, or reinterpret values. Every transformation and presentation layer must preserve field boundaries and apply encoding appropriate to its destination. A CSV export, terminal, and web page have different rendering requirements.\n\nEvent names, field names, and severity levels are schema, so keep them under server control. Do not accept an arbitrary client-provided log level or use request input as the event name. Correlation identifiers and displayed values should be validated, normalized, and length-bounded, but avoid claiming that a short list of replaced characters is a universal solution. The durable principle is that untrusted values belong inside structured fields, never in the syntax that determines what event was recorded.",
  "narrationPoints": [
    "Injection is confusion between untrusted data and record-defining syntax.",
    "Place bounded untrusted values in structured fields with server-controlled schemas.",
    "Protect downstream exports, terminals, dashboards, and HTML viewers too.",
    "Character replacement alone is not a universal logging defense."
  ]
};
