window.COURSE_MODULE = {
  "title": "Protect the Telemetry Pipeline and Test What Is Emitted",
  "graphicAlt": "End-to-end telemetry pipeline showing an application event moving through encrypted transport, a bounded queue, central collection, and protected storage with least access, environment separation, retention and deletion, and integrity monitoring. Queue controls show finite retries, a drop counter, and backpressure, while debug and high-value audit events follow different explicit failure policies. A test harness inspects serialized output for required fields and excludes secrets, authorization headers, cookies, and unknown fields.",
  "narration": "After emission, telemetry becomes security-sensitive stored data. Protect it in transit and at rest, separate production from development access, and grant operators, developers, support staff, and vendors only the visibility their roles require. Retention should balance incident and audit value against exposure, cost, privacy, and deletion obligations. Centralized append-oriented collection can improve availability and make casual modification harder than mutable local files, but ordinary centralized logging is not automatically tamper-proof or sufficient for high-assurance audit evidence.\n\nDesign failure behavior according to event criticality. A dropped debug event should not normally crash a request, while a regulated or security-critical audit workflow may require durable acknowledgement or a business-specific failure path. Make that distinction explicit. Asynchronous exporters need bounded queues, finite retry budgets, timeouts, drop counters, and backpressure policies. Unbounded buffering or infinite retries can turn a collector outage or attacker-generated event flood into memory exhaustion and application failure. Metrics should reveal drops and saturation without using unbounded user-controlled labels.\n\nTest the data leaving the logger, not only whether a logging method was called. Capture the serialized output and verify that authorization headers, cookies, secrets, unknown request properties, and disallowed exception details are absent. Submit values containing newlines and control characters, then confirm they remain one structured field through serialization and ingestion. Verify correlation identifiers are normalized and bounded, expected event fields are present, and a future secret-looking request property does not appear simply because the request model changed.\n\nTest operational semantics too. Confirm a high-value audit event is emitted exactly once where required, including retry and duplicate-delivery paths. Simulate transport loss, full buffers, exporter exceptions, and rate spikes; verify the application follows the documented policy and remains within memory and latency bounds. Validate access controls and retention configuration outside the code repository. Secure telemetry is an end-to-end property of event design, serialization, transport, storage, presentation, access, and deletion.",
  "narrationPoints": [
    "Apply transport, storage, access, environment, and retention controls to telemetry.",
    "Use event-specific failure policies with bounded queues and retries.",
    "Test serialized output for forbidden fields and preserved event boundaries.",
    "Centralized collection improves operations but is not automatically tamper-proof."
  ]
};
