window.COURSE_MODULE = {
  "title": "Course Summary: Capture Evidence Without Creating New Exposure",
  "graphicAlt": "Course-summary operating model centered on a minimum useful event containing what, who, resource, and outcome. Four connected pillars show minimizing data and excluding secrets, structuring server-controlled fields, distinguishing success, deny, validation, error, client, and diagnostic outcomes, and protecting and testing the telemetry pipeline. Correlation is shown as distinct from authentication, and audit delivery is visually separated from disposable debug output.",
  "narration": "Secure telemetry begins by treating observability as a security-relevant data flow. Define meaningful events before collecting fields, then map only the identity, tenant, resource, action, outcome, and correlation facts that serve an operational, security, or audit purpose. Structured logging makes those facts consistent and preserves record boundaries, but it does not make an unsafe value safe. Logging everything in JSON is still indiscriminate logging.\n\nMinimize before redacting. Keep credentials and authentication material out of every telemetry path, including logs, traces, and hosted error reports. Apply deliberate policy to identifiers, personal data, customer text, network attributes, headers, and request content. Redaction is defense in depth for known fields; hashing is not automatic anonymization. Keep request-controlled values inside bounded structured fields, while event names and severity remain server-controlled. Downstream viewers and exports must render those fields safely.\n\nEvidence is most useful when outcomes remain distinct. Authentication failure, validation rejection, authorization denial, infrastructure error, and successful privileged action convey different meaning. Correlation identifiers connect related work but do not authenticate a subject. Client-facing errors should reveal less than protected internal diagnostics, while useful stack traces can be retained under suitable access and retention controls. Security records and disposable debug output may require different schemas and delivery guarantees.\n\nFinally, protect and test the complete pipeline. Define who can read telemetry, how long it remains, how deletion works, and what happens when exporters fail. Bound queues, volume, and retries so observability cannot exhaust the application. Test the actual serialized records for required evidence and forbidden data, and verify behavior through transport and presentation where possible. The best security telemetry reconstructs important behavior while refusing to become a copy of the application's most sensitive data.",
  "narrationPoints": [
    "Structured telemetry still requires deliberate field selection and minimization.",
    "Keep secrets out; govern identifiers, personal data, and customer content.",
    "Preserve meaningful outcome categories and separate diagnostics from client responses.",
    "Protect and test the entire path from event construction through deletion."
  ]
};
