window.COURSE_MODULE = {
  "title": "Input Validation, Parsing, and File Handling",
  "graphicAlt": "Express requests follow expected schemas, explicit update allowlists, and business rules; uploads have deliberate size, storage, access, and cleanup controls.",
  "narration": "Express makes request data easy to reach through req.body, req.query, req.params, req.headers, and cookies. Convenience is not trust. Every value from the request should be treated as untrusted until validated. Body fields, query strings, route parameters, headers, cookies, and upload metadata can all influence database queries, business rules, redirects, file paths, template rendering, outbound calls, or side effects. Validation belongs at the API boundary before the application relies on the data.\n\nSchema validation helps make expected request shapes explicit. A handler should know which fields are required, which are optional, what types are allowed, what lengths and ranges are acceptable, which enum values are valid, and whether unexpected fields should be rejected. For update routes, explicit allowlists reduce mass assignment risk by choosing which fields may change instead of accepting every property the client sends. Type validation and business-rule validation are related, but they are not the same; both may be needed.\n\nFile handling needs particular care because uploaded content often moves through storage, scanning, previews, downloads, and downstream processors. A secure design considers size limits, type expectations, storage location, access control, temporary file cleanup, and scanning requirements where appropriate. Avoid using unvalidated input in filesystem paths, command execution, database queries, redirects, template rendering, or service destinations. The defensive pattern is predictable parsing followed by narrow, intentional use.",
  "narrationPoints": [
    "Express makes request data easy to reach through req.body, req.query, req.params, req.headers, and cookies.",
    "Schema validation helps make expected request shapes explicit.",
    "File handling needs particular care because uploaded content often moves through storage, scanning, previews, downloads, and downstream processors."
  ]
};
