window.COURSE_MODULE = {
  "title": "Relationship to NIST SP 800-53",
  "graphicAlt": "NIST SP 800-53 relationship map showing security controls flowing into FedRAMP requirements, assessment, and monitoring.",
  "narration": "FedRAMP is built on NIST guidance, particularly NIST Special Publication 800-53. NIST SP 800-53 provides a catalog of security and privacy controls used across federal information systems and programs.\n\nIn FedRAMP, those controls provide the foundation for many security requirements and assessment activities. They help define what a cloud service provider needs to implement, document, assess, and monitor.\n\nControls cover many areas, including access control, incident response, configuration management, contingency planning, identification and authentication, audit logging, risk assessment, system communications, and vulnerability management.\n\nThe NIST relationship is important because FedRAMP is not invented separately from federal risk management practices. It is connected to the same control language used in broader federal cybersecurity governance.\n\nCloud providers and agencies use these controls to structure security plans, implementation statements, assessment procedures, findings, remediation plans, and monitoring activities.\n\nControl implementation is not just a paperwork activity. A control may involve technical configuration, operational procedures, policy, monitoring, evidence generation, and clear ownership.\n\nFor learners, the key takeaway is that FedRAMP translates NIST control expectations into a standardized cloud security assessment and monitoring model for federal use.\n\nThis connection also helps technical teams. When engineers understand the control families behind FedRAMP requirements, they can connect architecture, configuration, logging, identity, and operational practices to specific risk objectives.\n\nThe control language provides a bridge between implementation and governance. It lets a technical safeguard become part of a larger story about how the cloud service protects federal information and supports agency risk decisions.",
  "narrationPoints": [
    "FedRAMP is built on NIST guidance, particularly NIST Special Publication 800-53.",
    "In FedRAMP, those controls provide the foundation for many security requirements and assessment activities.",
    "Controls cover many areas, including access control, incident response, configuration management, contingency planning, identification and...",
    "The NIST relationship is important because FedRAMP is not invented separately from federal risk management practices.",
    "Cloud providers and agencies use these controls to structure security plans, implementation statements, assessment procedures, findings,..."
  ]
};
