window.COURSE_MODULE = {
  "title": "Defining Expected Shape, Type, and Range",
  "graphicAlt": "Contract diagram listing expected representation, type, field set, numeric range, collection size, and business rule before implementation chooses a parser.",
  "narration": "Good validation starts before parsing code is written. The team should define what the program expects to accept: required fields, optional fields, value types, valid ranges, units, lengths, counts, enum-like values, formats, and relationships between fields. Without that contract, validation becomes a collection of scattered guesses.\n\nNarrow acceptance is easier to reason about than broad acceptance. When possible, prefer allowlists: known commands, known modes, known field names, known units, and known formats. A broad rule that accepts whatever appears convenient today often becomes hard to review after the input format grows.\n\nShape matters. A configuration entry might require a name, a timeout, and a mode. An external record might require exactly three fields. A command-line option might require a single value and no extra trailing text. Required fields should be present, optional fields should have defined defaults, and unexpected fields should be treated according to a clear policy.\n\nType and range matter as much as syntax. A value may parse as a number but still be invalid because it is negative, too large, in the wrong unit, outside a business rule, or inconsistent with another count. A string may match a general pattern but still be too long for a downstream storage or display rule.\n\nValidation should reject ambiguity. Wrong units, duplicate fields, inconsistent counts, empty values where emptiness is not meaningful, and extra values that the program does not understand should not quietly become accepted behavior.\n\nAfter validation succeeds, convert the input into a narrow internal type. A validated port number, bounded size, known mode, or canonical identifier communicates more than a raw string. That typed representation reduces repeated checks and makes later code easier to review.\n\nThis upfront definition also helps teams discuss compatibility. If a field is allowed for future use, document that policy. If unknown fields are rejected, make that behavior consistent so callers do not rely on accidental acceptance.",
  "narrationPoints": [
    "The team should define what the program expects to accept: required fields, optional fields, value types, valid ranges, units, lengths, counts, enum-like values, formats, and relationships between fields.",
    "A broad rule that accepts whatever appears convenient today often becomes hard to review after the input format grows.",
    "Required fields should be present, optional fields should have defined defaults, and unexpected fields should be treated according to a clear policy.",
    "A value may parse as a number but still be invalid because it is negative, too large, in the wrong unit, outside a business rule, or inconsistent with another count.",
    "A validated port number, bounded size, known mode, or canonical identifier communicates more than a raw string.",
    "If a field is allowed for future use, document that policy."
  ]
};
