window.COURSE_MODULE = {
  "title": "Resource Limits and Defensive Failure",
  "graphicAlt": "Resource-budget diagram combining item count, per-item bytes, cumulative bytes, and validation work before any batch is accepted or partially published.",
  "narration": "Validation is also a resource-control mechanism. Untrusted input can influence how much memory the program allocates, how long it loops, how many records it stores, how deeply it recurses, and how much work it schedules. Reasonable limits should be part of the input contract.\n\nSet maximum lengths, item counts, nesting depth, allocation budgets, and processing limits before accepting data. A design that loads everything into memory may be fine for small trusted files but inappropriate for larger external inputs. Streaming, chunking, and early rejection can keep resource use predictable.\n\nFailure behavior should be controlled. When input is malformed, oversized, inconsistent, or unsupported, the program should return a clear failure result, clean up temporary resources, preserve object invariants, and avoid leaving partially trusted state behind.\n\nError messages need different audiences. User-facing messages should be useful without revealing sensitive implementation details. Internal logs can include more diagnostic context, but they should still avoid unsafe logging practices such as recording unnecessary secrets or enormous raw values.\n\nValidation failures should not be exceptional mysteries. They are expected outcomes at a trust boundary. Code should handle them through documented paths, and monitoring should distinguish normal invalid input from unusual patterns that deserve operational attention.\n\nThe goal is predictable behavior under pressure. When limits are explicit, invalid or oversized input consumes bounded memory and time, cleanup remains reliable, and the program keeps its internal assumptions intact.\n\nResource policies should be reviewed with operations in mind. A limit should have a reason, a failure response, and a signal that maintainers can observe when legitimate workloads approach that limit.",
  "narrationPoints": [
    "Untrusted input can influence how much memory the program allocates, how long it loops, how many records it stores, how deeply it recurses, and how much work it schedules.",
    "Set maximum lengths, item counts, nesting depth, allocation budgets, and processing limits before accepting data.",
    "When input is malformed, oversized, inconsistent, or unsupported, the program should return a clear failure result, clean up temporary resources, preserve object invariants, and avoid leaving partially trusted state behind.",
    "Internal logs can include more diagnostic context, but they should still avoid unsafe logging practices such as recording unnecessary secrets or enormous raw values.",
    "Code should handle them through documented paths, and monitoring should distinguish normal invalid input from unusual patterns that deserve operational attention.",
    "A limit should have a reason, a failure response, and a signal that maintainers can observe when legitimate workloads approach that limit."
  ]
};
