window.COURSE_MODULE = {
  "title": "Validation Workflow, Testing, and Review",
  "graphicAlt": "Three-stage validation workflow showing encoding, structural shape, and action authorization returning distinct typed errors that a compact negative corpus and fuzz tests exercise.",
  "narration": "A validation workflow should make accepted and rejected behavior visible. Tests should include ordinary valid inputs, invalid inputs, boundary values, malformed structures, missing fields, duplicate fields, wrong units, large counts, edge indexes, unusual text, and resource-limit cases.\n\nNegative tests are especially important. They confirm that invalid input remains outside trusted state. When a validation defect is fixed, add a regression test that describes the intended contract, not just the old symptom. Over time, the test suite becomes executable documentation for the boundary.\n\nDefensive fuzzing can help at a high level when applied to parsers and validators. The goal is not spectacle; it is to explore unexpected combinations and confirm that the program fails cleanly, preserves invariants, and does not consume unreasonable resources.\n\nCode review should ask consistent questions. Where does input enter? What shape, type, range, encoding, and resource limits are expected? Is parse success checked? Are partial parses rejected? Are raw and trusted values separated? Are numeric conversions and derived sizes reviewed?\n\nTooling helps, but it does not replace design. Compiler warnings, sanitizers, static analysis, and CI checks can identify risky patterns and regressions. They are most valuable when the team has already made the validation contract explicit.\n\nOwnership also matters. Each input boundary should have a clear maintainer, documented expectations, and tests that run as part of normal development. Validation quality improves when it is treated as ordinary engineering work instead of emergency cleanup.\n\nDuring review, it helps to trace one accepted input and one rejected input from entry point to final decision. That exercise often reveals missing parse checks, repeated conversions, unclear logging, or trusted values that were never clearly created.",
  "narrationPoints": [
    "A validation workflow should make accepted and rejected behavior visible.",
    "When a validation defect is fixed, add a regression test that describes the intended contract, not just the old symptom.",
    "What shape, type, range, encoding, and resource limits are expected.",
    "Compiler warnings, sanitizers, static analysis, and CI checks can identify risky patterns and regressions.",
    "Each input boundary should have a clear maintainer, documented expectations, and tests that run as part of normal development.",
    "During review, it helps to trace one accepted input and one rejected input from entry point to final decision."
  ]
};
