window.COURSE_MODULE = {
  "title": "Content Security Policy at a High Level",
  "graphicAlt": "Blank placeholder image for Content Security Policy at a High Level.",
  "narration": "Content Security Policy, or CSP, is a resource-loading policy for browsers. It tells the browser which sources are allowed for scripts, styles, images, fonts, frames, connections, forms, and other content. A strong CSP can reduce the impact of injected markup or script because the browser has a separate policy that limits what can load or execute. That makes CSP one of the most powerful security headers, and also one of the easiest to break if it is copied blindly.\n\nCommon directives include default-src, script-src, style-src, img-src, connect-src, object-src, base-uri, and form-action. default-src can provide a fallback. script-src controls script sources and is often the most sensitive directive. style-src controls styles. img-src covers image locations. connect-src affects fetch, XHR, WebSocket, and similar connections. object-src can usually be locked down. base-uri and form-action reduce risks around base tag injection and unexpected form submission destinations.\n\nCSP should reflect the real application. A single-page application that calls APIs, loads analytics, and uses a CDN will need different directives from a static documentation site. A legacy app with inline scripts may require a staged modernization plan. Nonces and hashes can support safer script execution patterns, but they need build and rendering support. Overly broad values such as unrestricted wildcards often give a false sense of protection.\n\nReport-only mode is useful because it lets teams observe possible policy violations before blocking users. A report-only policy can reveal forgotten resource sources, browser extensions, development tooling, and application paths that need cleanup. After review, the policy can be tightened and enforced. CSP is not a one-time header. It is a maintained control that should be reviewed when frontend architecture, third-party scripts, or deployment patterns change.",
  "narrationPoints": [
    "Content Security Policy, or CSP, is a resource-loading policy for browsers.",
    "Common directives include default-src, script-src, style-src, img-src, connect-src, object-src, base-uri, and form-action.",
    "CSP should reflect the real application.",
    "Report-only mode is useful because it lets teams observe possible policy violations before blocking users."
  ]
};
