window.COURSE_MODULE = {
  "title": "Framing and Clickjacking Protections",
  "graphicAlt": "Blank placeholder image for Framing and Clickjacking Protections.",
  "narration": "Clickjacking happens when an attacker frames a legitimate page and tricks a user into clicking or interacting with it in a misleading context. The user believes they are clicking one thing, but the framed application receives a different interaction. This risk is especially important for pages that change settings, submit transactions, approve actions, or expose sensitive workflows. Browser framing controls help the application decide where it may be embedded.\n\nX-Frame-Options is an older but still common header for controlling framing. DENY tells browsers that the page should not be framed. SAMEORIGIN allows framing by pages from the same origin. These settings are simple and useful for many applications, but they are limited. They do not express complex partner allowlists well, and modern policy design often uses CSP frame-ancestors for more flexible control.\n\nThe frame-ancestors directive in Content Security Policy controls which origins may frame the page. It can support more precise policies for applications that have legitimate embedding needs, such as partner portals, internal dashboards, or integrated workflows. The key is to decide intentionally which pages can be framed and by whom. Public login pages, account settings, administrative actions, and payment flows usually deserve strict framing protections.\n\nAvoid accidental breakage by understanding legitimate embeds before enforcing a new policy. Some applications depend on internal iframes, partner integrations, identity flows, or documentation portals. A good rollout tests representative workflows and documents exceptions. The safest framing policy is the narrowest one that still supports required business use. Anything broader should have an owner and a reason.",
  "narrationPoints": [
    "Clickjacking happens when an attacker frames a legitimate page and tricks a user into clicking or interacting with it in a misleading context.",
    "X-Frame-Options is an older but still common header for controlling framing.",
    "The frame-ancestors directive in Content Security Policy controls which origins may frame the page.",
    "Avoid accidental breakage by understanding legitimate embeds before enforcing a new policy."
  ]
};
