window.COURSE_MODULE = {
  "title": "Hashes, MACs, and Password Storage",
  "graphicAlt": "Comparison panel separating hashes, keyed MACs, and salted password KDFs by input, secret requirement, and verification purpose.",
  "narration": "Cryptographic hashes produce one-way digests. They are useful for identifying data, checking that content has not changed in a trusted context, building higher-level protocols through approved libraries, and comparing known values without storing the original data.\n\nHashes are not encryption. A digest is not meant to be decrypted. If a system needs confidentiality, it needs an encryption design with keys and access control, not a hash.\n\nChecksums and cryptographic hashes are also different. A checksum may detect accidental corruption, but it is not designed as a security control against deliberate modification. Security-sensitive integrity should use approved cryptographic mechanisms.\n\nA message authentication code, or MAC, adds a secret key to the integrity decision. A valid MAC shows that the message was produced or accepted by a party with the key, assuming the key is protected and the verification is handled correctly.\n\nPassword storage has its own rules. Passwords should not be stored as plaintext, and fast unsalted hashes are not acceptable for modern defensive systems. Use approved password-hashing functions or platform identity systems with salts and work factors according to policy.\n\nAvoid building password storage from low-level pieces unless organizational policy explicitly provides the construction. The application should rely on vetted mechanisms, maintain configuration, and plan for parameter upgrades over time.\n\nReviewers should ask whether the code is using the right tool: hash for digest identity, MAC for keyed integrity, password hashing for stored passwords, and encryption for confidentiality.\n\nThey should also check comparison behavior. Security-sensitive comparisons should use approved library routines where policy requires them rather than ad hoc string comparisons.\n\nFor password systems, operational controls matter too: account recovery, rate limits, rotation policy, and integration with identity providers can be just as important as the storage primitive.",
  "narrationPoints": [
    "Cryptographic hashes produce one-way digests.",
    "Checksums and cryptographic hashes are also different.",
    "A message authentication code, or MAC, adds a secret key to the integrity decision.",
    "Passwords should not be stored as plaintext, and fast unsalted hashes are not acceptable for modern defensive systems.",
    "The application should rely on vetted mechanisms, maintain configuration, and plan for parameter upgrades over time.",
    "For password systems, operational controls matter too: account recovery, rate limits, rotation policy, and integration with identity providers can be just as important as the storage primitive."
  ]
};
