window.COURSE_MODULE = {
  "title": "Safe Connection Lifecycle Management",
  "graphicAlt": "Client-service connection diagram for Safe Connection Lifecycle Management, showing exposure policy, handle ownership, partial I/O, exact protocol framing, TLS peer authentication, resource budgets, shutdown, and payload-free operational events.",
  "narration": "Sockets are resources with lifecycles. They are created, configured, connected or accepted, used, shut down, and closed. In C++, that lifecycle should be represented clearly in ownership types. A socket handle that is passed around as an unadorned integer or platform handle is easy to leak, close twice, or keep alive longer than the protocol state allows.\n\nRAII wrappers are a strong default. The object that owns a descriptor or handle closes it when the object leaves scope, including on error paths. That does not remove the need for protocol-level shutdown, but it prevents cleanup from depending on scattered manual close calls. Move-only ownership can make it clear which part of the program is responsible for a live connection.\n\nCross-platform code needs to respect platform differences. POSIX descriptors and Windows socket handles have different types and setup rules, and Windows networking may require library initialization and cleanup. These details should be hidden behind a small, tested abstraction rather than repeated throughout business logic. The abstraction should make invalid or closed states explicit.\n\nConnection lifecycles also include accept loops, cancellation, normal completion, protocol errors, authentication failures, and shutdown. A service should know how to stop accepting new connections, how to finish or cancel current work, and when a connection should be closed. Predictable cleanup protects availability because it keeps resource use understandable even when clients disconnect or behave unexpectedly.",
  "narrationPoints": [
    "A socket handle that is passed around as an unadorned integer or platform handle is easy to leak, close twice, or keep alive longer than the protocol state allows.",
    "The object that owns a descriptor or handle closes it when the object leaves scope, including on error paths.",
    "POSIX descriptors and Windows socket handles have different types and setup rules, and Windows networking may require library initialization and cleanup.",
    "Connection lifecycles also include accept loops, cancellation, normal completion, protocol errors, authentication failures, and shutdown.",
    "Predictable cleanup protects availability because it keeps resource use understandable even when clients disconnect or behave unexpectedly.",
    "A service should know how to stop accepting new connections, how to finish or cancel current work, and when a connection should be closed."
  ]
};
