window.COURSE_MODULE = {
  "title": "Reading, Writing, and Partial I/O",
  "graphicAlt": "Client-service connection diagram for Reading, Writing, and Partial I/O, showing exposure policy, handle ownership, partial I/O, exact protocol framing, TLS peer authentication, resource budgets, shutdown, and payload-free operational events.",
  "narration": "Socket I/O is rarely as simple as one send and one receive. A read can return fewer bytes than requested, even when the connection is still healthy. A write can accept only part of a buffer. Operations can block, time out, be interrupted, fail, or report that the peer closed the connection. Secure code treats each of these outcomes as expected behavior, not as strange edge cases.\n\nTCP does not preserve application message boundaries. If a protocol says a message has a header and a body, the application must collect enough bytes for the header, validate the length, then collect the body within defined limits. Using whatever bytes happen to be available as if they were a complete message leads to parsing errors and inconsistent state. The safer design has explicit read states and clear maximum sizes.\n\nWrites need the same care. A send operation may write only a prefix of the data, so the code must track what remains and decide whether to continue, wait, time out, or close the connection. If the program uses nonblocking I/O or an event loop, partial progress must be represented in connection state. That state should be bounded so slow or stalled peers cannot grow memory use without limit.\n\nReturn values matter. Defensive code checks them, handles disconnects cleanly, avoids using incomplete data, and preserves safe state when an operation stops halfway. Buffers should have explicit bounds, and conversions from length fields to allocation sizes should be reviewed carefully. Partial I/O handling is not only about correctness; it is a core part of secure network programming.",
  "narrationPoints": [
    "Secure code treats each of these outcomes as expected behavior, not as strange edge cases.",
    "If a protocol says a message has a header and a body, the application must collect enough bytes for the header, validate the length, then collect the body within defined limits.",
    "If the program uses nonblocking I/O or an event loop, partial progress must be represented in connection state.",
    "Buffers should have explicit bounds, and conversions from length fields to allocation sizes should be reviewed carefully.",
    "Defensive code checks them, handles disconnects cleanly, avoids using incomplete data, and preserves safe state when an operation stops halfway.",
    "Partial I/O handling is not only about correctness; it is a core part of secure network programming."
  ]
};
