window.COURSE_MODULE = {
  "title": "A01: Broken Access Control",
  "graphicAlt": "Graphic for A01: Broken Access Control",
  "narration": "Authorization failures matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Privilege escalation matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.\n\nTeams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Insecure direct object references matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication.\n\nAccess control bypasses matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Least privilege Role-based access control Server-side authorization checks Selected HIPAA mappings for this topic include Section 164.312(a)(1) - Access control; Section 164.312(a)(2)(i) - Unique user identification; Section 164.308(a)(4) - Information access management.",
  "narrationPoints": [
    "Authorization failures matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Privilege escalation matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.",
    "Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Insecure direct object references matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication.",
    "Access control bypasses matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Least privilege Role-based access control Server-side authorization checks Selected HIPAA mappings for this topic include Section 164.312(a)(1) - Access control; Section 164.312(a)(2)(i) - Unique user identification; Section 164.308(a)(4) - Information access management.",
    "Authorization failures matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.",
    "Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication.",
    "Privilege escalation matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.",
    "Insecure direct object references matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations."
  ]
};
