window.COURSE_MODULE = {
  "title": "A04: Insecure Design",
  "graphicAlt": "Graphic for A04: Insecure Design",
  "narration": "Missing security requirements matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Weak workflows matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.\n\nTeams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Unsafe architecture matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication.\n\nLack of threat modeling matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Threat modeling Secure SDLC Security architecture reviews Selected HIPAA mappings for this topic include Section 164.308(a)(1)(ii)(A) - Risk analysis; Section 164.308(a)(1)(ii)(B) - Risk management; Section 164.308(a)(8) - Evaluation.",
  "narrationPoints": [
    "Missing security requirements matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Weak workflows matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.",
    "Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Unsafe architecture matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication.",
    "Lack of threat modeling matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Threat modeling Secure SDLC Security architecture reviews Selected HIPAA mappings for this topic include Section 164.308(a)(1)(ii)(A) - Risk analysis; Section 164.308(a)(1)(ii)(B) - Risk management; Section 164.308(a)(8) - Evaluation.",
    "Missing security requirements matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.",
    "Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication.",
    "Weak workflows matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.",
    "Unsafe architecture matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations."
  ]
};
