window.COURSE_MODULE = {
  "title": "A05: Security Misconfiguration",
  "graphicAlt": "Graphic for A05: Security Misconfiguration",
  "narration": "Default credentials matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Open cloud storage matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.\n\nTeams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Unnecessary services matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication.\n\nDebug configurations matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Secure baselines Hardening standards Configuration management Selected HIPAA mappings for this topic include Section 164.312(c)(1) - Integrity; Section 164.308(a)(1)(ii)(B) - Risk management.",
  "narrationPoints": [
    "Default credentials matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Open cloud storage matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.",
    "Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Unnecessary services matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication.",
    "Debug configurations matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Secure baselines Hardening standards Configuration management Selected HIPAA mappings for this topic include Section 164.312(c)(1) - Integrity; Section 164.308(a)(1)(ii)(B) - Risk management.",
    "Default credentials matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.",
    "Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication.",
    "Open cloud storage matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.",
    "Unnecessary services matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations."
  ]
};
