window.COURSE_MODULE = {
  "title": "A08: Software and Data Integrity Failures",
  "graphicAlt": "Graphic for A08: Software and Data Integrity Failures",
  "narration": "CI/CD compromise matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Unsigned code matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.\n\nTeams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Insecure deserialization matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication.\n\nBuild pipeline attacks matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Code signing Integrity validation Secure build pipelines Selected HIPAA mappings for this topic include Section 164.312(c)(1) - Integrity; Section 164.312(c)(2) - Mechanism to authenticate ePHI; Section 164.308(a)(1)(ii)(B) - Risk management.",
  "narrationPoints": [
    "CI/CD compromise matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Unsigned code matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.",
    "Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Insecure deserialization matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication.",
    "Build pipeline attacks matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations. Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication. Code signing Integrity validation Secure build pipelines Selected HIPAA mappings for this topic include Section 164.312(c)(1) - Integrity; Section 164.312(c)(2) - Mechanism to authenticate ePHI; Section 164.308(a)(1)(ii)(B) - Risk management.",
    "CI/CD compromise matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.",
    "Teams should look for this issue in user-facing features, administrative tools, background jobs, and service-to-service communication.",
    "Unsigned code matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations.",
    "Insecure deserialization matters because healthcare applications often handle ePHI, user identity, clinical workflows, patient portals, APIs, and integrations."
  ]
};
