window.COURSE_MODULE = {
  "title": "Assessments and Verification",
  "graphicAlt": "CMMC assessment workflow showing scope, requirement implementation, evidence, assessment, findings, affirmation, status, and ongoing maintenance.",
  "narration": "CMMC assessments provide a structured way to verify whether required cybersecurity practices are implemented within a defined assessment scope. The required assessment type depends on the CMMC level and the applicable acquisition requirement.\n\nA self-assessment is still a formal representation. The organization needs knowledgeable personnel, accurate scope, reliable evidence, documented results, and accountable affirmation rather than an informal opinion about general security maturity.\n\nSome Level 2 contracts require an assessment by an authorized CMMC Third-Party Assessment Organization. Level 3 uses the government assessment role established by the program. Organizations should confirm current assessor and status requirements through official channels.\n\nScope is a critical starting point. The assessment needs a clear understanding of systems, people, facilities, services, security-protection assets, external providers, and information flows associated with the covered contract information.\n\nEvidence may include policies, procedures, configurations, logs, tickets, training records, diagrams, inventories, approvals, technical outputs, interviews, and demonstrations. Strong evidence reflects normal operation rather than material created only for an assessment.\n\nAssessment results can identify findings that require action. Program rules govern status, remediation, any permitted plan of action, affirmation, and reporting, so organizations should not assume that every gap can be deferred.\n\nVerification is a point-in-time activity supported by ongoing responsibility. Systems change, employees move, suppliers change, configurations drift, and new vulnerabilities emerge after an assessment has ended.\n\nAudit readiness is therefore an operational condition. Clear ownership, current documentation, repeatable controls, retained evidence, internal review, and timely remediation make assessment results more accurate and security outcomes more sustainable.",
  "narrationPoints": [
    "CMMC assessments provide a structured way to verify whether required cybersecurity practices are implemented within a defined assessment scope.",
    "A self-assessment is still a formal representation.",
    "Some Level 2 contracts require an assessment by an authorized CMMC Third-Party Assessment Organization.",
    "Scope is a critical starting point.",
    "Evidence may include policies, procedures, configurations, logs, tickets, training records, diagrams, inventories, approvals, technical..."
  ]
};
