window.COURSE_MODULE = {
  "title": "CI/CD, Monitoring, Audit, and Incident Response",
  "graphicAlt": "An approved trigger obtains federated identity but still requires job-scoped permissions to reach production; audit evidence supports pausing, revoking, and impact review.",
  "narration": "Google Cloud CLI scripts often run in CI/CD systems, scheduled jobs, deployment agents, containers, and operational workstations. Each environment has different credential, logging, network, and runtime behavior. Pipeline identities should be scoped to the job, and production paths should be protected with branch, tag, release, environment, and approval gates.\n\nWorkload Identity Federation and other runtime identity patterns can reduce reliance on stored service account keys, but they still require careful scoping. A low-trust trigger should not receive production authority. Validation, build, publish, deploy, and rollback jobs should have permissions that match their purpose, and sensitive environments should have technical gates that align with the release process.\n\nOperational logs should identify the automation identity, project, region or zone, target category, action, time, and result without exposing secrets. Cloud Audit Logs, identity logs, service logs, monitoring alerts, and access reviews help teams understand what automation did. Monitoring should look for unusual identities, unexpected projects or regions, high-impact actions outside release windows, repeated failures, unexpected IAM changes, and service behavior that differs from the expected deployment outcome.\n\nIncident response should cover credential exposure, wrong-project changes, unexpected IAM changes, failed changes, and rollback or containment actions. Teams should know how to revoke or rotate credentials, pause affected workflows, identify impacted resources, review audit evidence, and update guardrails. Incidents and near misses should lead to better validation, narrower roles, safer logging, and stronger review processes.",
  "narrationPoints": [
    "Google Cloud CLI scripts often run in CI/CD systems, scheduled jobs, deployment agents, containers, and operational workstations.",
    "Workload Identity Federation and other runtime identity patterns can reduce reliance on stored service account keys, but they still require careful scoping.",
    "Operational logs should identify the automation identity, project, region or zone, target category, action, time, and result without exposing secrets.",
    "Incident response should cover credential exposure, wrong-project changes, unexpected IAM changes, failed changes, and rollback or containment actions."
  ]
};
