window.COURSE_MODULE = {
  "title": "Password Hashing in .NET and ASP.NET Core Identity",
  "graphicAlt": "Bullet summary graphic for Password Hashing in .NET and ASP.NET Core Identity.",
  "narration": "Passwords should be stored as password hashes, not plaintext, reversible encryption, or fast general-purpose hashes. A password hash is designed so the application can verify a password later without storing the original secret. That design reduces damage if a password database is exposed, because the stored value is not the password itself.\n\nSalts and work factors are central concepts. A salt is unique data used when hashing an individual password. Each password needs its own salt so two users with the same password do not end up with the same stored hash value. A work factor controls how expensive verification is. Higher work makes large-scale offline guessing more costly if hashes are exposed, while still allowing normal sign-in to complete within acceptable performance limits.\n\nNew ASP.NET Core applications with password-based sign-in should use framework-supported password hashing, such as ASP.NET Core Identity PasswordHasher, rather than custom cryptography. Password storage is easy to get wrong, and maintained framework components provide safer defaults, versioned formats, verification behavior, and migration support.\n\nConceptually, PasswordHasher<TUser> hashes the password when it is set or changed, verifies the submitted password during sign-in, and can indicate when a stored hash should be updated to a newer format. Rehash-on-successful-login is a common migration idea: when a user signs in with the correct password, the application can upgrade the stored hash format without ever recovering the plaintext password from storage.\n\nLow-level cryptographic primitives should not be copied into application code without a strong protocol reason and expert review. The password handling decision should be boring in the best sense: use the framework, configure it deliberately, monitor performance, and plan migrations as standards and application requirements evolve.",
  "narrationPoints": [
    "A password hash is designed so the application can verify a password later without storing the original secret.",
    "Each password needs its own salt so two users with the same password do not end up with the same stored hash value.",
    "New ASP.NET Core applications with password-based sign-in should use framework-supported password hashing, such as ASP.NET Core Identity PasswordHasher, rather than custom cryptography.",
    "Conceptually, PasswordHasher<TUser> hashes the password when it is set or changed, verifies the submitted password during sign-in, and can indicate when a stored hash should be updated to a newer format.",
    "The password handling decision should be boring in the best sense: use the framework, configure it deliberately, monitor performance, and plan migrations as standards and application requirements evolve."
  ]
};
