window.COURSE_MODULE = {
  "title": "What Wormable Prompt Injection Means",
  "narration": "Wormable prompt injection is not just a stronger phrase for ordinary prompt injection. It describes a propagation risk in connected AI systems. A model sees untrusted content, treats part of that content as instruction, and then helps move the influence into another system, user workflow, memory store, retrieval corpus, connector, or agent. The important feature is not clever wording. The important feature is an application path that lets malicious influence travel.\n\nThe Morris-II research made this risk concrete. It studied adversarial self-replicating prompts in GenAI ecosystems that use retrieval-augmented generation. The paper describes a computer-worm-like chain reaction where a prompt can trigger indirect prompt injections across connected applications. That research is a warning about architecture, not an invitation to build payloads. In this course, we discuss the mechanics only at a defensive level.\n\nWormability requires several conditions. There must be untrusted content that an AI system processes. There must be enough authority for the system to produce output, take action, update memory, or write to a shared surface. There must be a path by which that output reaches another model-enabled workflow. And there must be weak enough trust boundaries that the downstream system may treat the propagated content as instruction.\n\nThat means the risk lives outside the model as much as inside it. Email assistants, shared document summarizers, RAG systems, ticket triage tools, browser agents, chat connectors, and workflow automations can all create spread paths if they copy, summarize, forward, store, or act on untrusted text without strong controls.\n\nThe defensive goal is to break the chain. A system should assume that retrieved documents, tool results, emails, comments, and web pages may contain hostile instructions. The application must keep data separate from authority, restrict actions, preserve provenance, and prevent untrusted content from becoming a command channel.",
  "narrationPoints": [
    "Wormability requires a propagation path, not just a malicious prompt.",
    "The Morris-II research frames the risk as a connected-system problem.",
    "AI workflows can spread influence through memory, retrieval, output, and connectors.",
    "The defense goal is to break the chain between untrusted content and authority."
  ]
};
