window.COURSE_MODULE = {
  "title": "Direct, Indirect, and Wormable Prompt Injection",
  "narration": "Direct prompt injection happens when the user-facing prompt itself attempts to steer the model away from the intended task. The application receives the instruction directly from the person using the interface. That is serious, but the trust boundary is easier to see: the user input is untrusted and should not be allowed to override the system\u2019s role, policy, or authorization model.\n\nIndirect prompt injection is different. The attacker does not need direct access to the prompt box. Instead, instructions are embedded in external content that the model later processes: a web page, document, email, ticket, repository file, search result, or tool output. NIST describes this class as adversaries exploiting LLM-integrated applications by injecting prompts into data likely to be retrieved. OWASP similarly treats external content as a prompt injection source.\n\nJailbreaking overlaps with prompt injection but is not the same category. A jailbreak tries to defeat model behavior or safety constraints. Prompt injection is broader: it manipulates the application workflow by mixing instructions and data. RAG poisoning targets retrieval content or indexes. Tool-output injection targets data returned from an external tool. Wormable propagation appears when those influences can move onward to another AI-enabled surface.\n\nThat distinction matters for defense. If an organization treats prompt injection as only a bad chat message, it will miss the systems where no user typed the malicious content. A document processor may retrieve untrusted text. An agent may parse a web page. A support assistant may summarize inbound email. A workflow bot may read comments and write follow-up tasks.\n\nThe practical question is always: where can untrusted content enter, what can the model see, what can it influence, and what downstream systems may consume its output? Wormable prompt injection is the risk that those answers form a loop or chain.",
  "narrationPoints": [
    "Direct injection enters through the prompt interface; indirect injection enters through content.",
    "Jailbreaking, RAG poisoning, and tool-output injection are related but distinct risks.",
    "Wormable propagation appears when AI-influenced output reaches downstream AI workflows.",
    "Threat modeling should map inputs, authority, outputs, and downstream consumers."
  ]
};
