window.COURSE_MODULE = {
  "title": "Replication, Payload, Propagation, and Persistence",
  "narration": "A defensive model for wormable prompt injection has four core pieces: replication, payload, propagation, and persistence. Replication means the malicious influence is copied or restated in a form another model-enabled system may process. Payload means the influence tries to cause an unwanted result, such as changing content, steering a decision, using a tool improperly, or exposing information. Propagation is the path to the next surface. Persistence is how the influence remains available for future runs.\n\nThis model is useful because it avoids mysticism. A prompt does not spread by itself. It spreads only if the application gives it a route. A summarizer may copy instructions into a generated summary. A retrieval system may store poisoned text in an index. An email assistant may include tainted content in a reply. A workflow tool may write model-generated notes into a shared ticket that another agent later reads.\n\nThe blast radius depends on authority. A read-only summarizer with no memory and no outbound connector has less propagation potential than an agent that can write documents, send messages, modify tickets, update knowledge bases, or call business APIs. The more systems the agent can touch, the more important permission boundaries become.\n\nPersistence is especially important. If untrusted content is stored in long-lived memory, embedded into a retrieval corpus, copied into templates, or synchronized into shared records, the risk becomes less like a single bad response and more like contamination of the work environment. The same content can be rediscovered later under a different user, task, or context.\n\nDefenders should therefore ask which part of the chain they can break. Prevent replication into authoritative outputs. Block payload effects with policy and approval gates. Limit propagation with egress and connector controls. Reduce persistence by quarantining untrusted content and cleaning poisoned indexes or memory stores.",
  "narrationPoints": [
    "Replication, payload, propagation, and persistence describe the defensive risk model.",
    "A prompt spreads only when the application gives it a route.",
    "Blast radius depends on agent authority and connected surfaces.",
    "Persistent memory and retrieval stores can turn one bad input into recurring exposure."
  ]
};
