window.COURSE_MODULE = {
  "title": "Defensive Architecture and Trust Boundaries",
  "narration": "Model-only filtering is not enough for wormable prompt injection. Filters can help, but NIST and OWASP both emphasize that current mitigations do not provide perfect prevention. The stronger posture is system-level defense: assume untrusted content may contain instructions, and design the application so those instructions do not gain authority.\n\nThe first boundary is instruction versus data. System policy, developer instructions, user intent, retrieved evidence, tool output, and memory should not be treated as equal sources of authority. The application should explicitly label and structure those categories. It should also validate model outputs before they reach tools, files, messages, or business decisions.\n\nThe second boundary is observation versus action. A model may need to read untrusted content to summarize or classify it, but that does not mean it should act on instructions found inside that content. High-impact actions should require deterministic checks, user confirmation, or policy approval. A secure workflow can let the model draft an action while preventing it from executing the action without authorization.\n\nThe third boundary is context isolation. Separate tasks, tenants, users, and trust levels should not share uncontrolled memory. Content from one workspace should not quietly become instructions for another. If memory is used, it needs provenance, expiration, review, and a way to quarantine suspicious entries. The same principle applies to summaries, drafts, extracted action items, and generated labels that may later be retrieved as facts.\n\nUseful controls include source allowlists, retrieval filters, output schemas, destination allowlists, egress limits, rate limits, canary content, audit logs, and connector-specific permissions. None of these is a silver bullet. Together they make the system less brittle. The goal is layered containment: when a model misreads untrusted text, the application should still preserve control. Express as many safety decisions as possible in deterministic application code, where they can be tested and audited.",
  "narrationPoints": [
    "Model-only filtering cannot be the whole defense.",
    "Instruction, data, retrieved evidence, tool output, and memory need separate authority.",
    "Observation should not automatically imply permission to act.",
    "Layered controls make prompt injection a contained failure instead of a spread path."
  ]
};
