window.COURSE_MODULE = {
  "title": "Detection, Containment, and Incident Response",
  "narration": "Incident response for wormable prompt injection starts with the propagation path. Which untrusted content entered the system? Which model or agent processed it? What output was generated? Where was that output stored, sent, indexed, or copied? Which downstream workflows consumed it? This timeline matters more than arguing whether the model was fooled in an abstract sense.\n\nContainment should reduce spread quickly. Disable risky connectors if they can write, send, or synchronize. Pause automated actions that depend on model-generated instructions. Quarantine suspicious documents, messages, tickets, and retrieved chunks. If memory or RAG indexes may be poisoned, stop using them for high-risk tasks until they are reviewed or rebuilt.\n\nCredentials and permissions need a separate pass. If an agent had access to mail, storage, tickets, source control, cloud resources, or business APIs, review what it could do and what it actually did. Rotate exposed credentials where appropriate. Revoke unnecessary tokens. Tighten scopes that allowed broad reads or writes. The incident is not only about text; it is about authority granted to automation.\n\nLogs should answer operational questions. What sources were retrieved? Which tools were called? What destinations received output? Which user approved or did not approve the action? What memory entries were read or written? Without this telemetry, defenders may be forced to guess which surfaces are contaminated. The best logs connect model activity to application decisions, so investigators can distinguish a strange answer from a workflow action that changed state.\n\nRecovery should include design changes, not only cleanup. Add provenance, approval gates, connector restrictions, retrieval hygiene, output validation, and monitoring for unusual copying or forwarding behavior. A good post-incident review names the broken trust boundary and the missing control that allowed propagation. Tabletop exercises are useful here because teams can rehearse connector shutdown, index quarantine, token rotation, and communication before a real incident forces those choices.",
  "narrationPoints": [
    "Response starts by mapping the propagation path and downstream consumers.",
    "Containment may require pausing connectors, automation, memory, and retrieval surfaces.",
    "Credential and permission review is part of prompt injection response.",
    "Recovery should fix the broken trust boundary, not only clean affected content."
  ]
};
