window.COURSE_MODULE = {
  "title": "FluentValidation and Service-Layer Validation",
  "graphicAlt": "Blank placeholder image for FluentValidation and Service-Layer Validation.",
  "narration": "FluentValidation is commonly used in C# applications when validation rules become richer than simple attributes. It lets teams define validators in code, compose reusable rules, express conditional validation, and keep request validation close to application behavior. This can make complex contracts easier to read than a long set of attributes on a model. The important benefit is consistency: a request shape should have one clear validator that all entry points can use.\n\nCentralized validators reduce duplication, but they should not become a dumping ground for every rule. Request validation should answer whether the input is shaped correctly for a use case. Domain validation should answer whether the operation is allowed by the business model. Service-layer validation sits between those concerns and is especially important when work can be triggered by controllers, minimal APIs, background jobs, scheduled tasks, message consumers, or internal service calls.\n\nValidation gaps often appear when only controllers validate. A background job may call the same service with data from a queue. An integration test may seed data directly. An internal API may bypass an MVC filter. If the service layer assumes every caller already validated perfectly, invalid data can reach business-critical logic from a less obvious path. Shared validators and domain invariants help close that gap.\n\nMaintainability matters as applications grow. Validators should be named clearly, covered by tests, and organized around use cases rather than broad persistence entities. Reusable rules are helpful when they represent real shared policy, such as email format, tenant identifiers, or money limits. They are harmful when abstraction hides context-specific business decisions. Good validation code is boring in the best way: obvious, explicit, and easy to update when the contract changes.",
  "narrationPoints": [
    "FluentValidation is commonly used in C# applications when validation rules become richer than simple attributes.",
    "It lets teams define validators in code, compose reusable rules, express conditional validation, and keep request validation close to application behavior.",
    "This can make complex contracts easier to read than a long set of attributes on a model.",
    "The important benefit is consistency: a request shape should have one clear validator that all entry points can use.",
    "Centralized validators reduce duplication, but they should not become a dumping ground for every rule.",
    "Request validation should answer whether the input is shaped correctly for a use case."
  ]
};
