window.COURSE_MODULE = {
  "title": "Logging, Monitoring, and Testing APIs",
  "graphicAlt": "Safe API events support monitoring without token or payload dumps; contract, authorization, and negative tests provide evidence for ongoing review.",
  "narration": "Security-relevant API logs should help teams understand who called what, from where, against which resource, with what result, and at what volume. Useful fields often include timestamp, request ID, caller identity, client application, tenant, endpoint, operation, status, latency, decision category, and safe error code. Logs should support investigation and monitoring without turning into a second copy of sensitive payloads.\n\nAvoid secrets and sensitive payloads in logs. Authorization headers, bearer tokens, API keys, cookies, passwords, payment data, personal data, and full request or response bodies should be handled carefully. Redaction should be designed, tested, and applied consistently. Audit trails should capture meaningful actions such as administrative changes, access to sensitive records, failed authorization decisions, and changes to API credentials.\n\nTesting should cover the contract and the abuse cases. API contract tests confirm that required fields, response shapes, status codes, and schema expectations remain stable. Negative tests send malformed, missing, oversized, unexpected, and type-confused input. Authorization tests verify that callers can only perform allowed actions on resources they are permitted to access. Fuzzing at a high level can help exercise parsers and edge cases that hand-written tests miss.\n\nReviewing OpenAPI specifications and production behavior closes the loop. Specifications can reveal undocumented endpoints, missing authentication, broad parameters, inconsistent error models, or response fields that do not match least-privilege expectations. Production monitoring can reveal unusual volume, repeated failures, enumeration patterns, expensive queries, and clients using deprecated behavior. Observability is part of API security because unknown behavior cannot be managed.",
  "narrationPoints": [
    "Security-relevant API logs should help teams understand who called what, from where, against which resource, with what result, and at what volume.",
    "Avoid secrets and sensitive payloads in logs.",
    "Testing should cover the contract and the abuse cases.",
    "Reviewing OpenAPI specifications and production behavior closes the loop."
  ]
};
