window.COURSE_MODULE = {
  "title": "Event Schemas, Validation, and Versioning",
  "graphicAlt": "Security diagram for Event-Driven Security in Node.js, Event Schemas, Validation, and Versioning, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "An event should be treated as a contract between producers and consumers. That contract should describe the event type, version, required fields, allowed types, size limits, formats, identifiers, and intended meaning. Without a clear schema, every consumer starts inventing its own interpretation of the payload. That creates brittle integrations and quiet security drift, especially when a producer changes a field that a downstream worker uses for authorization, tenant routing, or state transitions.\n\nValidate event payloads before using them in business logic. Reject unsupported event types, unknown versions, malformed payloads, oversized messages, unexpected structures, and values outside allowed ranges. Treat IDs, tenant IDs, user IDs, object keys, URLs, file paths, amounts, roles, scopes, and workflow states as untrusted until they are verified. A message can be syntactically valid and still refer to a resource the actor does not own or a state transition that should not be allowed.\n\nVersioning is a security concern because contracts change over time. A new version might rename a field, change the meaning of a status, add a sensitive property, or alter the conditions under which a consumer takes action. Producers and consumers should agree on compatibility expectations. Old consumers should fail safely when they receive an unsupported version rather than silently applying outdated assumptions to new data.\n\nValidation failures also need a safe path. Some malformed events can be dropped with metrics. Others should move to a failure destination for investigation. Logs should include enough detail to troubleshoot the contract problem without dumping full sensitive payloads. Schema validation supports security, but it does not replace authorization, ownership checks, business-state checks, or idempotency.",
  "narrationPoints": [
    "That contract should describe the event type, version, required fields, allowed types, size limits, formats, identifiers, and intended meaning.",
    "Treat IDs, tenant IDs, user IDs, object keys, URLs, file paths, amounts, roles, scopes, and workflow states as untrusted until they are verified.",
    "Versioning is a security concern because contracts change over time.",
    "Schema validation supports security, but it does not replace authorization, ownership checks, business-state checks, or idempotency.",
    "Validate event payloads before using them in business logic.",
    "An event should be treated as a contract between producers and consumers."
  ]
};
