window.COURSE_MODULE = {
  "title": "Safe Retries, Dead-Letter Queues, and Failure Handling",
  "graphicAlt": "Security diagram for Event-Driven Security in Node.js, Safe Retries, Dead-Letter Queues, and Failure Handling, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "Retries can recover from temporary failures, but they can also amplify outages or repeat unsafe actions. A retry that helps during a brief network interruption can be harmful when the downstream database is overloaded, the payload is invalid, or the handler has already completed a side effect. Retry behavior should match the operation's idempotency, downstream capacity, and business impact. Backoff, retry limits, and failure destinations are part of the security design, not just reliability tuning.\n\nPoison messages should be isolated for investigation instead of retried forever. A malformed event, unsupported version, missing tenant, or invalid state transition is unlikely to become valid by running the same code hundreds of times. Infinite retries can hide the real problem, flood logs, create cost, delay other work, or repeatedly call a fragile downstream service. Failure handling should make important security and business events visible without causing unnecessary repeated side effects.\n\nDead-letter queues are useful, but they can become sensitive data stores. They may contain customer data, file names, object keys, internal workflow details, authorization context, or failed webhook payloads. Access to dead-letter queues should be controlled, retention should be intentional, and logs or support tools should avoid exposing full sensitive payloads. Manual replay should require authorization, audit logging, careful scoping, and a clear understanding of idempotency.\n\nA failed event should not disappear, loop forever, or become impossible to explain. Good failure handling records what failed, why it failed, how often it has retried, where it was routed, who can inspect it, and what steps are safe for recovery. Error messages and failure logs should help operators resolve the issue without exposing secrets, tokens, full sensitive event bodies, or unnecessary personal data.",
  "narrationPoints": [
    "Backoff, retry limits, and failure destinations are part of the security design, not just reliability tuning.",
    "Failure handling should make important security and business events visible without causing unnecessary repeated side effects.",
    "Access to dead-letter queues should be controlled, retention should be intentional, and logs or support tools should avoid exposing full sensitive payloads.",
    "Error messages and failure logs should help operators resolve the issue without exposing secrets, tokens, full sensitive event bodies, or unnecessary personal data.",
    "Manual replay should require authorization, audit logging, careful scoping, and a clear understanding of idempotency.",
    "Dead-letter queues are useful, but they can become sensitive data stores."
  ]
};
