window.COURSE_MODULE = {
  "title": "Authentication, Tokens, and Credential Handling",
  "graphicAlt": "Layered architecture diagram for Authentication, Tokens, and Credential Handling, showing Python API client, credential provider, destination policy, TLS channel, response validator, retry budget, and remote service; labeled arrows identify outbound request and response trust boundaries and the point where unsafe input or behavior is rejected.",
  "narration": "API clients often authenticate with API keys, bearer tokens, signed tokens, OAuth client credentials, service accounts, workload identity, or mutual TLS. These mechanisms differ, but they all represent authority. A client credential may allow data reads, administrative changes, billing activity, account creation, infrastructure changes, or access to regulated information. Treating credentials as ordinary strings is a common root cause of exposure, overuse, and difficult incident response.\n\nCredential protection starts with storage and scope. Secrets should live in an approved secret store or platform identity mechanism whenever practical. They should not be hardcoded, committed to repositories, pasted into notebooks, embedded in URLs, printed in traces, placed in support bundles, or casually inherited through process environments. Rotation should be possible without code changes, and each credential should have a clear owner, purpose, environment, permission set, and expiration or review cycle.\n\nLeast privilege matters because API credentials are often used by automation. A token for a reporting job should not be able to administer accounts. A credential for staging should not work in production. A client that needs one endpoint should not receive broad platform authority. Scopes, roles, service-account permissions, audience restrictions, token lifetime, and network constraints can reduce blast radius when a credential is misused or accidentally exposed.\n\nAuthenticating to an API does not remove the need for local authorization or response checks. A successful token exchange proves that the client presented acceptable credentials to the remote service. It does not prove that the current user is allowed to trigger the operation, that the requested object belongs to the right tenant, that the response is safe to store, or that the workflow action is appropriate. Local business rules still matter.",
  "narrationPoints": [
    "API clients often authenticate with API keys, bearer tokens, signed tokens, OAuth client credentials, service accounts, workload identity, or mutual TLS.",
    "Secrets should live in an approved secret store or platform identity mechanism whenever practical.",
    "Least privilege matters because API credentials are often used by automation.",
    "A client that needs one endpoint should not receive broad platform authority.",
    "Authenticating to an API does not remove the need for local authorization or response checks.",
    "Local business rules still matter."
  ]
};
