window.COURSE_MODULE = {
  "title": "Safe Request Construction and Data Minimization",
  "graphicAlt": "Sequence diagram for Safe Request Construction and Data Minimization, showing Python API client, credential provider, destination policy, TLS channel, response validator, retry budget, and remote service; labeled arrows identify outbound request and response trust boundaries and the point where unsafe input or behavior is rejected.",
  "narration": "Safe request construction means building method, path, query parameters, headers, body, content type, and optional file uploads through controlled patterns. The client should know which HTTP methods are allowed for each operation, which path shapes are expected, which headers are required, and which fields can appear in JSON or form payloads. Dynamic assembly is sometimes necessary, but untrusted input should not freely control URLs, header names, authentication material, request methods, or protocol behavior.\n\nValidation should happen before data leaves the application. Check type, shape, length, format, allowed values, tenant context, and business intent. If a user-controlled field becomes part of a query parameter, body field, file name, metadata value, or downstream action, the client should enforce the contract locally rather than assuming the remote API will reject unsafe or unintended values. Remote validation is useful, but it is not a substitute for protecting your own workflow.\n\nData minimization is a security control, not only a privacy preference. Clients should send only the data needed for the approved purpose. Avoid forwarding complete local records when the remote service only needs an identifier, status, or specific field. Avoid including secrets, internal notes, debug fields, unnecessary user attributes, or unrelated payload data. Minimization reduces exposure if the destination logs requests, has broader access, is misconfigured, or later changes how it uses received data.\n\nRequest signing and canonicalization concepts can be useful for some APIs, but they require consistency. The client should be clear about exactly what is signed, how timestamps or nonces are used, and how retries interact with signed requests. Even when a library handles signing, callers should avoid modifying signed headers or paths after the signature is created. The practical goal is predictable requests whose security meaning matches the operation the application intended.",
  "narrationPoints": [
    "Safe request construction means building method, path, query parameters, headers, body, content type, and optional file uploads through controlled patterns.",
    "Check type, shape, length, format, allowed values, tenant context, and business intent.",
    "Data minimization is a security control, not only a privacy preference.",
    "Avoid including secrets, internal notes, debug fields, unnecessary user attributes, or unrelated payload data.",
    "Request signing and canonicalization concepts can be useful for some APIs, but they require consistency.",
    "The practical goal is predictable requests whose security meaning matches the operation the application intended."
  ]
};
