window.COURSE_MODULE = {
  "title": "Pagination, Rate Limits, Retries, and Idempotency",
  "graphicAlt": "Boundary map for Pagination, Rate Limits, Retries, and Idempotency, showing Python API client, credential provider, destination policy, TLS channel, response validator, retry budget, and remote service; labeled arrows identify outbound request and response trust boundaries and the point where unsafe input or behavior is rejected.",
  "narration": "Pagination is more than a convenience feature. Page-based and cursor-based retrieval can create partial results, duplicate records, missing records, inconsistent ordering, or stale views when data changes during a scan. A secure client should define how it detects completion, handles empty pages, limits total records, preserves ordering assumptions, and resumes safely after interruption. Poor pagination can cause security decisions to be based on incomplete or duplicated data.\n\nRate limits and quotas shape safe behavior under load. A client should understand how the API signals throttling, whether retry-after guidance is available, and what limits apply by tenant, credential, endpoint, or time period. Ignoring rate limits can create outages, unexpected cost, blocked credentials, or noisy failure loops. Treat rate-limit handling as part of the integration contract, especially when the API supports important business workflows.\n\nRetries need strict discipline. Connection timeouts, read timeouts, transient errors, and ambiguous outcomes should be handled deliberately. Retrying every failure forever can amplify incidents, duplicate actions, flood dependencies, or hide real problems. Bounded retries, backoff, jitter concepts, circuit-breaking patterns, and clear failure reporting help the application recover without turning a dependency problem into a wider operational issue.\n\nIdempotency is critical when API calls change state. If a request creates a charge, opens a ticket, approves access, sends a message, provisions a resource, or records a decision, the client must avoid unintended duplicate effects. Idempotency keys, operation identifiers, state checks, and clear reconciliation behavior help repeated requests represent one intended operation. Timeout ambiguity is the hard case: the client may not know whether the remote side completed the action, so the design must account for that uncertainty.",
  "narrationPoints": [
    "Page-based and cursor-based retrieval can create partial results, duplicate records, missing records, inconsistent ordering, or stale views when data changes during a scan.",
    "Poor pagination can cause security decisions to be based on incomplete or duplicated data.",
    "Ignoring rate limits can create outages, unexpected cost, blocked credentials, or noisy failure loops.",
    "Retrying every failure forever can amplify incidents, duplicate actions, flood dependencies, or hide real problems.",
    "Idempotency keys, operation identifiers, state checks, and clear reconciliation behavior help repeated requests represent one intended operation.",
    "Retries need strict discipline."
  ]
};
