window.COURSE_MODULE = {
  "title": "Course Summary: A Secure ASP.NET Core Baseline",
  "graphicAlt": "Bullet summary graphic for Course Summary: A Secure ASP.NET Core Baseline.",
  "narration": "A secure ASP.NET Core baseline starts with the application lifecycle. Security belongs in architecture, coding, configuration, deployment, and operations. The request pipeline should make transport, routing, errors, authentication, authorization, and endpoints work together in a way the team can explain and test.\n\nAuthenticate explicitly and authorize on the server. Authentication identifies the caller. Authorization decides what that caller may do. Access rules should protect MVC actions, Razor Pages, controllers, APIs, Minimal APIs, operational endpoints, and administrative surfaces. User interface hints are not a substitute for server-side enforcement.\n\nProtect state carefully. Cookies can carry security-sensitive state, antiforgery protections help with state-changing browser requests, CORS is not identity, and session state should be minimized. Configuration and secrets are also part of state: keep secrets out of source control, use appropriate secret storage, and plan Data Protection key persistence and rotation.\n\nHandle data deliberately. Validate input on the server, shape request DTOs carefully, avoid over-posting, preserve Razor encoding defaults, avoid raw rendering of untrusted content, shape API responses, control error details, and handle files with limits and clear storage rules. Security is strongest when data boundaries are explicit.\n\nFinally, operate the application. Log meaningful security and operational events without exposing sensitive data. Monitor trends, review production configuration, keep dependencies current, plan secret rotation, prepare for incidents, and improve after real operational feedback. Security is not a one-time setting; it is an engineering habit that keeps the application understandable as it changes.",
  "narrationPoints": [
    "A secure ASP.NET Core baseline starts with the application lifecycle.",
    "User interface hints are not a substitute for server-side enforcement.",
    "Configuration and secrets are also part of state: keep secrets out of source control, use appropriate secret storage, and plan Data Protection key persistence and rotation.",
    "Validate input on the server, shape request DTOs carefully, avoid over-posting, preserve Razor encoding defaults, avoid raw rendering of untrusted content, shape API responses, control error details, and handle files with limits and clear storage rules.",
    "Monitor trends, review production configuration, keep dependencies current, plan secret rotation, prepare for incidents, and improve after real operational feedback."
  ]
};
