window.COURSE_MODULE = {
  "title": "Why Browser Forensics Matters",
  "graphicAlt": "Blank white placeholder image for module 1, Why Browser Forensics Matters.",
  "narration": "Browsers are major sources of investigative evidence because so much modern work and personal activity happens through the web. A browser may hold evidence of web activity, searches, downloads, cloud service use, webmail access, SaaS interaction, browser extensions, notifications, and user settings. In many investigations, the browser becomes the bridge between local endpoint activity and cloud-based applications.\n\nBrowser artifacts can support many investigative questions. In incident response, they may show phishing pages, downloaded payloads, suspicious redirects, or webmail access. In corporate investigations, they may help explain SaaS usage, cloud drive activity, data downloads, or policy concerns. In fraud or insider investigations, they may provide leads about searches, web sessions, accounts, or files obtained through web applications.\n\nThe key word is leads. Browser evidence is powerful, but it rarely proves the full story alone. A page visit is not always deliberate reading. A URL can appear because of a redirect, embedded resource, background request, synchronization, tab restoration, or automatic loading. A search may show curiosity, research, mistake, or another user's activity on a shared profile. Strong investigators avoid turning artifacts into conclusions too quickly.\n\nAuthorized and documented practice matters. Browser data can expose sensitive personal information, account identifiers, application state, and business records. Investigators should work within legal authority, organizational authorization, consent, or another valid basis. They should preserve evidence, document methods, avoid unnecessary exposure, and report privacy-sensitive findings with discipline.\n\nThe goal of browser forensics is not to overclaim browser data. The goal is to use browser artifacts responsibly as part of a defensible investigative picture. That means identifying the right user and profile, preserving relevant data, interpreting artifacts in context, correlating with other sources, and documenting uncertainty.",
  "narrationPoints": [
    "Browsers are major sources of investigative evidence because so much modern work and personal activity happens through the web.",
    "Browser artifacts can support many investigative questions.",
    "The key word is leads.",
    "Authorized and documented practice matters.",
    "The goal of browser forensics is not to overclaim browser data."
  ]
};
