window.COURSE_MODULE = {
  "title": "Searches, Forms, Bookmarks, and Extensions",
  "graphicAlt": "Blank white placeholder image for module 6, Searches, Forms, Bookmarks, and Extensions.",
  "narration": "Searches, forms, bookmarks, and extensions reveal convenience features that can become important evidence sources. Search engine queries may show research, navigation attempts, troubleshooting, intent signals, or simple curiosity. Form history and autofill artifacts may show repeated entries or user convenience behavior. Bookmarks and favorites may show saved resources, work applications, or personal interests.\n\nSearch artifacts require careful interpretation. A query can be typed, suggested, repeated, synchronized, or generated as part of a browser or search workflow. It may show that a phrase was entered, but it does not always show why. A search result page may load many resources, redirects, or previews. Analysts should distinguish the query itself from the pages that were subsequently visited.\n\nForm history and autofill can be highly privacy sensitive. They may contain names, addresses, email addresses, phone numbers, search terms, organization names, or other personal and business data. Investigators should limit review to authorized scope and avoid reporting unnecessary personal information. Autofill existence does not automatically prove that the same user typed a value during the investigation window.\n\nExtensions matter because they can affect browsing behavior, permissions, storage, and application interaction. Installed extension lists, extension permissions, extension storage, update records, and configuration data can help explain redirects, content modification, password-manager behavior, downloads, notifications, or unusual browser activity. An extension should not be labeled malicious by default; its behavior must be analyzed and corroborated.\n\nBrowser notifications can also be useful. They may show that a web application had permission to send alerts or that a site produced a notification. But notification presence does not always prove the user saw, opened, or acted on it. Like other browser artifacts, these convenience features are most useful when they are tied to a timeline and supported by other evidence.",
  "narrationPoints": [
    "Searches, forms, bookmarks, and extensions reveal convenience features that can become important evidence sources.",
    "Search artifacts require careful interpretation.",
    "Form history and autofill can be highly privacy sensitive.",
    "Extensions matter because they can affect browsing behavior, permissions, storage, and application interaction.",
    "Browser notifications can also be useful."
  ]
};
