window.COURSE_MODULE = {
  "title": "What TLS Means for Python Developers",
  "graphicAlt": "Client and server establish an encrypted channel through protocol negotiation, certificate chain validation, hostname checking, protected private keys, application authorization, monitoring, renewal, and controlled failure.",
  "narration": "TLS is a protocol family used to protect network communication between systems. Python developers encounter TLS whenever they make HTTPS requests, expose APIs, connect to databases, publish to message brokers, receive webhooks, call internal services, write command-line automation, or run background workers that talk across the network. Even when a library hides most details, the application still depends on trust decisions about identity, encryption, configuration, and failure behavior.\n\nTLS, HTTPS, certificates, encryption, authentication, and authorization are related but different. HTTPS is HTTP carried over TLS. Encryption helps protect data in transit. Certificates support endpoint identity validation. Application authentication identifies users, services, or clients at the application layer. Authorization decides what an authenticated subject may do. A secure design understands which layer is responsible for which decision instead of assuming TLS solves everything.\n\nTLS can protect communication in transit, but it does not make remote data automatically trustworthy. A response can be malformed, stale, unauthorized for the current user, inconsistent with an API contract, or harmful to process incorrectly. Likewise, a connection that works is not necessarily secure. It may be encrypted to the wrong endpoint, using a development trust setting, logging secrets, or ignoring certificate errors that should stop the operation.\n\nDevelopers need to understand TLS because defaults and infrastructure are only part of the story. Libraries, reverse proxies, service meshes, cloud services, private certificate authorities, and hosting platforms may handle mechanics, but developers still choose clients, configure endpoints, handle errors, protect credentials, validate responses, and decide what is safe in production. TLS literacy helps teams review those choices instead of treating transport security as invisible magic.",
  "narrationPoints": [
    "TLS is a protocol family used to protect network communication between systems.",
    "A secure design understands which layer is responsible for which decision instead of assuming TLS solves everything.",
    "TLS can protect communication in transit, but it does not make remote data automatically trustworthy.",
    "Developers need to understand TLS because defaults and infrastructure are only part of the story.",
    "TLS literacy helps teams review those choices instead of treating transport security as invisible magic.",
    "Even when a library hides most details, the application still depends on trust decisions about identity, encryption, configuration, and failure behavior."
  ]
};
