window.COURSE_MODULE = {
  "title": "TLS Security Goals and Trust Boundaries",
  "graphicAlt": "Application data crosses plaintext inside each endpoint and ciphertext across the network; certificate authorities, DNS names, private keys, TLS termination, proxies, and backend services mark separate trust boundaries.",
  "narration": "TLS commonly supports three goals: confidentiality, integrity, and endpoint authentication for data in transit. Confidentiality helps keep network observers from reading protected traffic. Integrity helps detect certain kinds of tampering while data moves between endpoints. Endpoint authentication helps a client verify that it is communicating with the expected service identity, and in some designs helps a server verify the client identity as well.\n\nTLS trust boundaries appear wherever communication crosses between systems. A browser connecting to a Python web application crosses one boundary. A Python service calling another service crosses another. A worker connecting to a database or message broker crosses another. Internal versus external location matters, but it is not the same as trust. A private network can reduce exposure, yet the identity of the endpoint still matters when sensitive data or credentials are involved.\n\nReal architectures often include reverse proxies, load balancers, gateways, service meshes, and application servers. TLS may terminate at an edge component, continue to a backend service, or be re-established between internal components. Teams should know where TLS starts and ends, which component owns certificates and keys, which headers carry original request information, and whether backend traffic still needs transport protection based on the risk model.\n\nTLS should be considered alongside authentication, authorization, logging, monitoring, deployment architecture, and incident response. It protects the transport path, but it does not decide whether a user is allowed to access a record, whether a webhook payload is fresh, or whether an internal service is trustworthy. Internal network location alone should not be proof of trust. Secure systems combine validated transport with clear application and operational controls.",
  "narrationPoints": [
    "TLS commonly supports three goals: confidentiality, integrity, and endpoint authentication for data in transit.",
    "Internal versus external location matters, but it is not the same as trust.",
    "Real architectures often include reverse proxies, load balancers, gateways, service meshes, and application servers.",
    "TLS should be considered alongside authentication, authorization, logging, monitoring, deployment architecture, and incident response.",
    "TLS may terminate at an edge component, continue to a backend service, or be re-established between internal components.",
    "Integrity helps detect certain kinds of tampering while data moves between endpoints."
  ]
};
