window.COURSE_MODULE = {
  "title": "Authentication, Authorization, and Tenant Boundaries",
  "graphicAlt": "Verified identity and trusted resource ownership inform tenant authorization; client IDs and interface behavior do not grant access.",
  "narration": "Authentication and authorization are different controls. Authentication identifies the caller: a user, service, job, or automation context. Authorization decides whether that caller may perform a specific action on a specific resource in a specific tenant or workflow state. A handler that knows the caller identity still needs permission checks before returning or changing protected data.\n\nIn Go REST APIs, trusted server-side code should enforce sensitive decisions. Client-side route guards, hidden buttons, disabled fields, and frontend role checks can improve usability, but they are not enforcement. The handler or service layer must verify the action, object, tenant, and context using trusted data.\n\nTenant boundaries deserve special attention. A user may have access to one organization, project, account, or workspace but not another. IDs supplied in paths, query strings, headers, or request bodies should not become authority by themselves. The server should connect the requested object to the caller's permitted scope before using or returning it.\n\nConsistent authorization helpers reduce drift. Shared policy functions, middleware that attaches authenticated context, and service-layer checks can make decisions more reviewable. Still, the authorization should be close enough to the sensitive action that reviewers can see what is protected and why the caller is allowed.\n\nDeny-by-default behavior keeps missing context from becoming accidental access. Tests should include unauthorized users, wrong tenants, missing identity, stale sessions, and service-to-service callers. Access control is strongest when failure is expected and handled deliberately.\n\nThe authorization decision should be tied to data loaded from trusted sources. If the route receives a resource ID, the server should confirm that resource belongs to the allowed scope before using it. That habit keeps identity, object access, and tenant isolation connected, even as routes, teams, and data models evolve. Denial cases should be named in tests.",
  "narrationPoints": [
    "Authentication and authorization are different controls.",
    "In Go REST APIs, trusted server-side code should enforce sensitive decisions.",
    "Tenant boundaries deserve special attention.",
    "Consistent authorization helpers reduce drift.",
    "Deny-by-default behavior keeps missing context from becoming accidental access."
  ]
};
