window.COURSE_MODULE = {
  "title": "Data Access and Output Safety",
  "graphicAlt": "Validated updates use bound values within tenant scope; response models exclude internal fields, and transactions commit or roll back deliberately.",
  "narration": "Data access is part of REST API security because handlers often stand between untrusted requests and durable business records. Go code should use safe database access patterns, parameterized operations, clear repository or service contracts, and reviewed query construction. The goal is that untrusted input does not become executable behavior or an uncontrolled selector.\n\nValidation should happen before storage or downstream use. A decoded request should not be written directly to the database just because its fields fit a struct. The service should check shape, meaning, ownership, tenant scope, and workflow rules before it creates, updates, deletes, or forwards data.\n\nOutput safety is just as important as input safety. APIs should return explicit response models rather than automatically serializing internal records. Internal database models may contain fields that clients do not need, such as administrative notes, internal flags, authorization metadata, secrets, or fields that become sensitive as the model evolves.\n\nResponse shaping helps preserve least privilege. It also gives teams a clear place to review which fields are safe for which caller. Downstream service data should receive the same treatment. A response from another system should be validated and minimized before it becomes part of the API response.\n\nTenant separation must be preserved in data access, not only in route checks. Queries, repository methods, cache keys, object references, file references, and pagination should carry the tenant or ownership context needed to prevent accidental cross-scope data exposure. Safe APIs control both what they accept and what they return.\n\nTransaction boundaries should also be intentional. When a route changes multiple records or calls multiple systems, failure handling should preserve a clear state. Data access code should make partial updates, retries, and cleanup visible enough to review.",
  "narrationPoints": [
    "Data access is part of REST API security because handlers often stand between untrusted requests and durable business records.",
    "Validation should happen before storage or downstream use.",
    "Output safety is just as important as input safety.",
    "Response shaping helps preserve least privilege.",
    "Tenant separation must be preserved in data access, not only in route checks."
  ]
};
