window.COURSE_MODULE = {
  "title": "Error Responses, Logging, and Observability",
  "graphicAlt": "Internal errors pass through separate safe-client-response and redacted-operator-log paths; secrets and raw request content are excluded.",
  "narration": "Go's explicit errors are useful, but API security depends on how those errors are handled. Internal errors may include database details, downstream service information, file paths, configuration names, or implementation clues. Clients need useful failure information, but they do not need stack traces, raw queries, secrets, tokens, cookies, or private configuration.\n\nA secure API maps internal failures to safe client-facing responses. Validation errors, authentication failures, authorization denials, missing records, dependency timeouts, and unexpected internal failures should have consistent status codes and response shapes. The response should help a legitimate caller recover without exposing details that belong in internal logs.\n\nLogging and observability should support investigation. Structured logs, request IDs, correlation IDs, route names, caller context, timing, and outcome fields can help operators understand behavior. Security-relevant events may include authentication outcomes, authorization denials, sensitive state changes, administrative actions, validation spikes, and unusual resource-control events.\n\nRedaction is essential because logs rarely stay in one place. They may flow into dashboards, alerting systems, tickets, long-term archives, and third-party tools. Raw request bodies, API keys, passwords, tokens, cookies, private user data, and sensitive records should not be logged casually.\n\nGood observability is controlled, not blind. Log enough to detect and investigate problems, but avoid recording data that creates a second exposure channel. Document what is logged, what is redacted, who can access logs, and how long sensitive operational data is retained.\n\nTeams should also separate user-facing error language from internal diagnostic detail. A wrapped internal error can help engineers find the source of a failure, while the HTTP response remains stable and safe for clients. That separation keeps operations useful without exposing implementation details or sensitive context unnecessarily.",
  "narrationPoints": [
    "Go's explicit errors are useful, but API security depends on how those errors are handled.",
    "A secure API maps internal failures to safe client-facing responses.",
    "Logging and observability should support investigation.",
    "Redaction is essential because logs rarely stay in one place.",
    "Good observability is controlled, not blind."
  ]
};
