window.COURSE_MODULE = {
  "title": "Dependencies, Configuration, Testing, and Secure Delivery",
  "graphicAlt": "Dependency review, configuration validation and rejection tests feed a CI gate before least-privileged deployment, patching and rollback.",
  "narration": "A Go REST API is shaped by more than route code. Dependencies, configuration, build settings, tests, deployment choices, and release habits all influence security. Go modules make dependencies visible, but visible dependencies still need ownership, review, update paths, and a reason to exist.\n\ngo.mod and go.sum changes should be reviewed with care. Teams should understand direct and transitive dependencies, abandoned packages, version pins, module checksums, vulnerability notices where available, and the process for replacing a package that no longer fits the risk profile. Fewer unnecessary dependencies often means less code to trust.\n\nConfiguration should be explicit and environment-aware. Development behavior, debug output, CORS settings, TLS termination assumptions, service credentials, runtime permissions, and feature flags should not drift silently into production. Required settings should be validated at startup, and sensitive values should come from controlled configuration rather than source code or broad logs.\n\nTesting should cover security-relevant behavior, not only successful requests. Handler tests, validation tests, authorization tests, tenant-boundary tests, error-path tests, timeout behavior, and configuration checks all help keep assumptions from regressing. Negative tests are especially useful because they prove the API rejects cases it should reject.\n\nSecure delivery is repeatable governance. Static analysis, linting, CI checks, release notes, rollback readiness, patch workflows, and documented security changes help teams ship without relying on memory. A maintainable API has a clear path for routine fixes and urgent updates.\n\nThe best delivery process makes important risk visible before deployment. A dependency change, a new route, a new tenant rule, a new environment variable, or a changed timeout should leave evidence in review and release notes. That evidence helps operations understand what changed and helps future maintainers patch confidently later, especially during urgent maintenance or compliance review.",
  "narrationPoints": [
    "A Go REST API is shaped by more than route code.",
    "go.mod and go.sum changes should be reviewed with care.",
    "Configuration should be explicit and environment-aware.",
    "Testing should cover security-relevant behavior, not only successful requests.",
    "Secure delivery is repeatable governance."
  ]
};
