window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Sensitive Data, Logging, and Auditing' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Project entities into a minimal nonsecret audit view",
      "language": "csharp",
      "blurb": "The projection filters by tenant before selecting only account identifier, state, and credential-presence metadata; password hashes, recovery codes, security stamps, contact data, and tracked entity instances never enter the result contract.",
      "code": "public sealed record AccountEntity(\n    string Id,\n    string TenantId,\n    string State,\n    string? PasswordHash,\n    string? SecurityStamp,\n    int RecoveryCodeCount);\n\npublic sealed record AccountAuditView(\n    string Id,\n    string State,\n    bool HasPassword,\n    bool HasRecoveryCodes);\n\npublic static class AccountAuditProjection\n{\n    public static IQueryable<AccountAuditView> Apply(\n        IQueryable<AccountEntity> accounts,\n        string tenantId)\n    {\n        ArgumentNullException.ThrowIfNull(accounts);\n        if (string.IsNullOrEmpty(tenantId) || tenantId.Length > 64 ||\n            !tenantId.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_'))\n        {\n            throw new ArgumentException(\"Tenant identifier rejected.\", nameof(tenantId));\n        }\n        return accounts\n            .Where(account => account.TenantId == tenantId)\n            .Select(account => new AccountAuditView(\n                account.Id,\n                account.State,\n                account.PasswordHash != null,\n                account.RecoveryCodeCount > 0));\n    }\n}\n"
    },
    {
      "title": "Create a bounded persistence audit event after save",
      "language": "csharp",
      "blurb": "The event factory accepts closed entity, operation, and outcome enums plus canonical tenant and correlation identifiers and a bounded affected-row count; it has no entity snapshot, SQL, parameter, personal-data, or exception-message field.",
      "code": "public enum PersistenceEntity { Order, Customer, Account }\npublic enum PersistenceOperation { Insert, Update, Delete }\npublic enum PersistenceOutcome { Succeeded, Conflict, Failed }\n\npublic sealed class PersistenceAuditEvent\n{\n    private PersistenceAuditEvent(\n        PersistenceEntity entity,\n        PersistenceOperation operation,\n        PersistenceOutcome outcome,\n        string tenantId,\n        string correlationId,\n        int affectedRows)\n    {\n        Entity = entity;\n        Operation = operation;\n        Outcome = outcome;\n        TenantId = tenantId;\n        CorrelationId = correlationId;\n        AffectedRows = affectedRows;\n    }\n\n    public PersistenceEntity Entity { get; }\n    public PersistenceOperation Operation { get; }\n    public PersistenceOutcome Outcome { get; }\n    public string TenantId { get; }\n    public string CorrelationId { get; }\n    public int AffectedRows { get; }\n\n    public static PersistenceAuditEvent Create(\n        PersistenceEntity entity,\n        PersistenceOperation operation,\n        PersistenceOutcome outcome,\n        string tenantId,\n        string correlationId,\n        int affectedRows)\n    {\n        if (!Enum.IsDefined(entity) || !Enum.IsDefined(operation) || !Enum.IsDefined(outcome) ||\n            !IsIdentifier(tenantId, 1) || !IsIdentifier(correlationId, 8) ||\n            affectedRows is < 0 or > 10_000)\n        {\n            throw new ArgumentException(\"Persistence audit event rejected.\");\n        }\n        return new PersistenceAuditEvent(\n            entity, operation, outcome, tenantId, correlationId, affectedRows);\n    }\n\n    private static bool IsIdentifier(string value, int minimumLength) =>\n        !string.IsNullOrEmpty(value) && value.Length >= minimumLength && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    }
  ]
};
