window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Query Safety with LINQ and Parameters' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Compose a bounded tenant query from LINQ expressions",
      "language": "csharp",
      "blurb": "The helper validates and snapshots tenant, status, sort, and page size; filters by tenant before projection; admits only a closed status and sort enum; selects public columns; and applies deterministic ordering plus an application-owned Take limit.",
      "code": "public enum OrderQuerySort { Newest, Oldest }\n\npublic sealed record OrderEntity(\n    string Id,\n    string TenantId,\n    string Status,\n    long TotalCents,\n    DateTimeOffset CreatedUtc);\n\npublic sealed record OrderListItem(\n    string Id,\n    string Status,\n    long TotalCents);\n\npublic static class SafeOrderLinqQuery\n{\n    public static IQueryable<OrderListItem> Apply(\n        IQueryable<OrderEntity> orders,\n        string tenantId,\n        string status,\n        OrderQuerySort sort,\n        int take)\n    {\n        ArgumentNullException.ThrowIfNull(orders);\n        if (!IsIdentifier(tenantId) || status is not (\"pending\" or \"paid\" or \"shipped\") ||\n            !Enum.IsDefined(sort) || take is < 1 or > 100)\n        {\n            throw new ArgumentException(\"Order query rejected.\");\n        }\n        var filtered = orders.Where(order =>\n            order.TenantId == tenantId && order.Status == status);\n        var ordered = sort == OrderQuerySort.Newest\n            ? filtered.OrderByDescending(order => order.CreatedUtc).ThenBy(order => order.Id)\n            : filtered.OrderBy(order => order.CreatedUtc).ThenBy(order => order.Id);\n        return ordered\n            .Select(order => new OrderListItem(order.Id, order.Status, order.TotalCents))\n            .Take(take);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    },
    {
      "title": "Build a closed customer search predicate without dynamic code",
      "language": "csharp",
      "blurb": "The search factory validates a bounded control-free prefix and closed account state, snapshots both primitive values, and composes provider-translatable equality and StartsWith expressions instead of interpolating SQL or parsing caller-supplied expression text.",
      "code": "using System.Text;\n\npublic sealed record CustomerEntity(\n    string Id,\n    string TenantId,\n    string DisplayName,\n    string State);\n\npublic sealed record CustomerSearchResult(string Id, string DisplayName);\n\npublic static class CustomerSearchQuery\n{\n    public static IQueryable<CustomerSearchResult> Apply(\n        IQueryable<CustomerEntity> customers,\n        string tenantId,\n        string displayNamePrefix,\n        string state)\n    {\n        ArgumentNullException.ThrowIfNull(customers);\n        if (!IsIdentifier(tenantId) || state is not (\"active\" or \"suspended\") ||\n            string.IsNullOrEmpty(displayNamePrefix) || displayNamePrefix.Length > 80 ||\n            Encoding.UTF8.GetByteCount(displayNamePrefix) > 160 ||\n            displayNamePrefix.Any(char.IsControl))\n        {\n            throw new ArgumentException(\"Customer search rejected.\");\n        }\n        return customers\n            .Where(customer =>\n                customer.TenantId == tenantId &&\n                customer.State == state &&\n                customer.DisplayName.StartsWith(displayNamePrefix))\n            .OrderBy(customer => customer.Id)\n            .Select(customer => new CustomerSearchResult(customer.Id, customer.DisplayName))\n            .Take(50);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    }
  ]
};
