window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Authorization-Aware Data Access and Multi-Tenancy' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Snapshot one authenticated tenant and subject for data access",
      "language": "csharp",
      "blurb": "The factory requires an authenticated principal, exactly one canonical subject and tenant claim, rejects ambiguous duplicates, and copies those immutable identifiers before any asynchronous repository operation can observe mutable caller state.",
      "code": "using System.Security.Claims;\n\npublic sealed class DataAccessIdentity\n{\n    private DataAccessIdentity(string subjectId, string tenantId)\n    {\n        SubjectId = subjectId;\n        TenantId = tenantId;\n    }\n\n    public string SubjectId { get; }\n    public string TenantId { get; }\n\n    public static DataAccessIdentity From(ClaimsPrincipal principal)\n    {\n        ArgumentNullException.ThrowIfNull(principal);\n        if (principal.Identity?.IsAuthenticated != true)\n            throw new UnauthorizedAccessException(\"Authentication required.\");\n        var subjects = principal.FindAll(\"sub\").Select(claim => claim.Value).Take(2).ToArray();\n        var tenants = principal.FindAll(\"tenant_id\").Select(claim => claim.Value).Take(2).ToArray();\n        if (subjects.Length != 1 || tenants.Length != 1 ||\n            !IsIdentifier(subjects[0]) || !IsIdentifier(tenants[0]))\n        {\n            throw new UnauthorizedAccessException(\"Data-access identity rejected.\");\n        }\n        return new DataAccessIdentity(subjects[0], tenants[0]);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    },
    {
      "title": "Filter document mutations by tenant and owner",
      "language": "csharp",
      "blurb": "The mutation selector requires immutable validated access context, validates the document identifier, includes tenant and owner predicates alongside the primary key, and returns only the matching row rather than authorizing from an earlier unscoped read.",
      "code": "public sealed record DocumentRow(\n    string Id,\n    string TenantId,\n    string OwnerId,\n    string Title);\n\npublic sealed class DocumentAccessContext\n{\n    private DocumentAccessContext(string tenantId, string subjectId)\n    {\n        TenantId = tenantId;\n        SubjectId = subjectId;\n    }\n\n    public string TenantId { get; }\n    public string SubjectId { get; }\n\n    public static DocumentAccessContext Create(string tenantId, string subjectId)\n    {\n        if (!IsIdentifier(tenantId) || !IsIdentifier(subjectId))\n            throw new ArgumentException(\"Document access context rejected.\");\n        return new DocumentAccessContext(tenantId, subjectId);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n\npublic static class AuthorizedDocumentMutation\n{\n    public static IQueryable<DocumentRow> SelectTarget(\n        IQueryable<DocumentRow> documents,\n        DocumentAccessContext access,\n        string documentId)\n    {\n        ArgumentNullException.ThrowIfNull(documents);\n        ArgumentNullException.ThrowIfNull(access);\n        if (string.IsNullOrEmpty(documentId) || documentId.Length > 64 ||\n            !documentId.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_'))\n        {\n            throw new ArgumentException(\"Document identifier rejected.\", nameof(documentId));\n        }\n        return documents.Where(document =>\n            document.Id == documentId &&\n            document.TenantId == access.TenantId &&\n            document.OwnerId == access.SubjectId);\n    }\n}\n"
    }
  ]
};
