window.COURSE_MODULE = {
  "title": "Raw SQL, Dynamic Queries, and Stored Procedures",
  "graphicAlt": "Bullet summary graphic for Raw SQL, Dynamic Queries, and Stored Procedures.",
  "narration": "EF Core raw SQL features are useful in some cases, but they are higher-review areas. Teams may use raw SQL for performance, complex queries, provider-specific capabilities, existing stored procedures, or reporting needs. Those reasons can be valid, but raw SQL should be limited, documented, and reviewed because it moves developers closer to the database command boundary.\n\nValues supplied to raw SQL APIs should be handled through safe provider-supported mechanisms. The central rule remains the same: application-defined command structure should stay separate from variable values. Reviewers should be able to see where values are bound, where structure is chosen, and why raw SQL is necessary for that path.\n\nDynamic filtering, sorting, reporting, and export features deserve special care. They often accept flexible caller options and may touch broad data sets. A safe design maps caller choices to approved internal query shapes instead of allowing arbitrary field names, expressions, fragments, or table-like choices to flow into database structure.\n\nStored procedures can provide a useful database boundary, but they are not automatic security guarantees. A procedure can still contain unsafe dynamic construction, broad permissions, sensitive logging, or weak ownership assumptions. The application and database teams should review procedure behavior, parameters, permissions, and operational use together.\n\nDynamic SQL inside stored procedures still requires careful design. The same defensive questions apply inside the database: which parts are approved structure, which parts are values, how are values bound, who can call the procedure, and what objects can it affect. The fact that logic is inside a procedure does not remove the need for safe construction.\n\nClients should not control SQL structure. They may choose supported filters, statuses, ranges, or report options, but the application should translate those choices into approved queries. Building query features around approved shapes gives product teams flexibility without making data access impossible to review.",
  "narrationPoints": [
    "EF Core raw SQL features are useful in some cases, but they are higher-review areas.",
    "Values supplied to raw SQL APIs should be handled through safe provider-supported mechanisms.",
    "A safe design maps caller choices to approved internal query shapes instead of allowing arbitrary field names, expressions, fragments, or table-like choices to flow into database structure.",
    "Stored procedures can provide a useful database boundary, but they are not automatic security guarantees.",
    "Dynamic SQL inside stored procedures still requires careful design."
  ]
};
