window.COURSE_MODULE = {
  "title": "Migrations, Seeding, and Database Change Control",
  "graphicAlt": "Bullet summary graphic for Migrations, Seeding, and Database Change Control.",
  "narration": "EF Core migrations are production-impacting changes. They can alter schema, constraints, indexes, relationships, defaults, permissions, and data shape. A migration that works locally can still have operational and security consequences when it runs against production data and production permissions.\n\nSchema changes and data transformations need review. Adding a nullable field, changing an index, altering a relationship, dropping a column, widening a permission-related table, or moving tenant data can affect authorization, auditing, performance, privacy, and rollback plans. Destructive operations deserve explicit review and communication.\n\nSeed data can be security-sensitive. Roles, users, permissions, feature flags, default settings, administrative accounts, sample tenants, and development shortcuts should be treated carefully. Seed logic that is harmless in local development can be risky if it reaches staging or production without environment-specific controls.\n\nDevelopment convenience should be separated from production discipline. Automatic database creation, broad local permissions, sample credentials, test data, and relaxed constraints may help developers move quickly. Production migrations need change control, controlled execution identity, review, monitoring, and a plan for what happens if the migration fails partway through.\n\nPermission separation is important for migrations. The identity that runs schema changes may need rights that the runtime application should not have. Keeping those responsibilities distinct can reduce the impact of runtime defects and make audit records clearer.\n\nRollback planning and operational communication are part of secure delivery. Teams should know whether a migration is reversible, whether data loss is possible, how long it may run, what users may observe, and who is responsible for monitoring. Database change control belongs in the secure software delivery process, not outside it.",
  "narrationPoints": [
    "A migration that works locally can still have operational and security consequences when it runs against production data and production permissions.",
    "Seed logic that is harmless in local development can be risky if it reaches staging or production without environment-specific controls.",
    "Production migrations need change control, controlled execution identity, review, monitoring, and a plan for what happens if the migration fails partway through.",
    "Keeping those responsibilities distinct can reduce the impact of runtime defects and make audit records clearer.",
    "Database change control belongs in the secure software delivery process, not outside it."
  ]
};
