window.COURSE_MODULE = {
  "title": "Course Summary: Secure EF Core Workflow",
  "graphicAlt": "Bullet summary graphic for Course Summary: Secure EF Core Workflow.",
  "narration": "Secure EF Core usage is a repeatable engineering workflow. It starts with clear DbContext lifetime, environment-specific configuration, protected connection settings, and database permissions that match the application's real responsibilities. Configuration is security code when it controls how data access behaves.\n\nFor normal data access, prefer LINQ and framework-supported parameterized patterns. Keep query structure under developer control, validate values for business meaning, shape responses to return only needed data, and review performance changes for security side effects. Safe query syntax and safe application behavior both matter.\n\nEnforce authorization close to data access. Object-level checks, tenant boundaries, global query filters, service-layer rules, and least privilege should work together. Avoid bypass paths where background jobs, support tools, reporting features, or administrative actions skip the normal access model.\n\nModel updates defensively. Separate API models from persistence entities when useful, control which properties each workflow can change, review relationship changes, and protect ownership, approval, pricing, tenant, role, and audit fields. Tracking and concurrency behavior should match the operation's intent.\n\nFinally, maintain the data layer over time. Review raw SQL, stored procedures, migrations, seed data, EF logging, auditing, dependencies, resource limits, and operational failure behavior. Secure EF Core development is not a one-time checklist; it is the steady practice of keeping data access understandable, bounded, and reviewable as the application evolves.",
  "narrationPoints": [
    "Secure EF Core usage is a repeatable engineering workflow.",
    "Keep query structure under developer control, validate values for business meaning, shape responses to return only needed data, and review performance changes for security side effects.",
    "Object-level checks, tenant boundaries, global query filters, service-layer rules, and least privilege should work together.",
    "Separate API models from persistence entities when useful, control which properties each workflow can change, review relationship changes, and protect ownership, approval, pricing, tenant, role, and audit fields.",
    "Secure EF Core development is not a one-time checklist; it is the steady practice of keeping data access understandable, bounded, and reviewable as the application evolves."
  ]
};
