window.COURSE_MODULE = {
  "title": "Secure Server Socket Behavior",
  "graphicAlt": "A private listener uses a finite backlog and thirty-two handler slots; excess accepted clients are closed rather than queued into unlimited threads or descriptors.",
  "narration": "A listening socket is an exposure decision. Binding to loopback can make a service local-only, while binding to a broader interface can make it reachable from other hosts. Ports, firewall rules, container networking, host networking, and load balancer configuration all shape who can connect. Development listeners and production services should not share casual assumptions. Every listening socket should have a clear owner, purpose, exposure model, access model, and monitoring path.\n\nConnection acceptance and backlog behavior affect availability. A server that accepts unlimited connections or lets idle clients remain forever can exhaust file descriptors, memory, worker threads, or event-loop capacity. Backlog settings, per-client timeouts, connection limits, and graceful close behavior should be chosen deliberately. The server should treat resource management as part of security because availability is one of the system?s security properties.\n\nAuthentication should happen before sensitive actions. A peer that can open a socket should not automatically read data, change state, run commands, or access tenant-specific resources. Authorization should be enforced per command or message, not only at the moment the connection starts. If a long-lived connection changes state, the server should keep authorization decisions aligned with the current peer, resource, and operation.\n\nRate limiting, throttling, and safe shutdown behavior help keep the service manageable. A server should handle malformed messages, unexpected disconnects, slow clients, and repeated failures without leaking sensitive details or leaving shared state inconsistent. Operational logs should show connection lifecycle, safe peer identifiers where appropriate, protocol errors, authentication outcomes, and resource pressure without turning raw payloads into permanent records.",
  "narrationPoints": [
    "Ports, firewall rules, container networking, host networking, and load balancer configuration all shape who can connect.",
    "Backlog settings, per-client timeouts, connection limits, and graceful close behavior should be chosen deliberately.",
    "Authorization should be enforced per command or message, not only at the moment the connection starts.",
    "Rate limiting, throttling, and safe shutdown behavior help keep the service manageable.",
    "Every listening socket should have a clear owner, purpose, exposure model, access model, and monitoring path.",
    "The server should treat resource management as part of security because availability is one of the system?s security properties."
  ]
};
