window.COURSE_MODULE = {
  "title": "The STL as a Safety Tool, Not a Safety Guarantee",
  "graphicAlt": "C++ container safety diagram for The STL as a Safety Tool, Not a Safety Guarantee, linking ownership and lifetime to bounds, invalidation, algorithm contracts, bounded growth, synchronization, and exception-safe commit behavior.",
  "narration": "The requested title uses STL, and many developers still use that term in everyday conversation. Modern teams often talk more broadly about the C++ standard library, including containers, strings, views, spans, algorithms, smart pointers, and filesystem utilities. This course uses STL as shorthand while focusing on practical standard-library use.\n\nThe standard library is a major safety improvement over manual arrays, manual memory management, and handwritten algorithms. Containers manage storage, strings preserve length, algorithms express intent, and wrappers can make ownership clearer. These abstractions give reviewers more structure to reason about.\n\nBut the library does not automatically make code safe. A vector can still be indexed out of range. A string_view can still outlive the string it observes. An iterator can still become invalid after a mutation. A comparator can still violate the rules an ordered container depends on.\n\nSecure STL usage means respecting each abstraction's contract. The important questions are lifetime, bounds, ownership, invalidation, resource growth, exception behavior, and thread-safety assumptions. Those questions do not disappear just because the code uses standard types.\n\nA good review does not ask only whether a standard container is present. It asks whether the chosen type makes the intended access pattern clear, whether sizes and indexes are validated, whether views are short-lived, and whether mutations invalidate cached access.\n\nThe goal is defensive engineering: use standard-library tools to reduce manual mistakes, then combine them with explicit contracts, tests, sanitizers, static analysis, and review.\n\nA useful mindset is to treat every standard-library type as an abstraction with rules. The more important the data or boundary, the more clearly those rules should appear in naming, API shape, and tests.",
  "narrationPoints": [
    "The requested title uses STL, and many developers still use that term in everyday conversation.",
    "The standard library is a major safety improvement over manual arrays, manual memory management, and handwritten algorithms.",
    "A comparator can still violate the rules an ordered container depends on.",
    "The important questions are lifetime, bounds, ownership, invalidation, resource growth, exception behavior, and thread-safety assumptions.",
    "A good review does not ask only whether a standard container is present.",
    "The more important the data or boundary, the more clearly those rules should appear in naming, API shape, and tests."
  ]
};
