window.COURSE_MODULE = {
  "title": "Choosing the Right Container",
  "graphicAlt": "C++ container safety diagram for Choosing the Right Container, linking ownership and lifetime to bounds, invalidation, algorithm contracts, bounded growth, synchronization, and exception-safe commit behavior.",
  "narration": "Container selection is a security and maintainability decision, not only a performance detail. The container communicates how data is owned, how it grows, how callers access it, and what kinds of invalidation reviewers should expect.\n\nstd::vector is often the right default for dynamic contiguous storage. It has simple ownership, cache-friendly iteration, and clear size behavior. It also reallocates as it grows, so pointers, references, and iterators into the vector can become invalid after some operations.\n\nstd::array is useful when the size is fixed and known by design. The fixed size can make bounds and lifetime easier to review. std::deque may fit designs that need growth at both ends or different stability properties, but its own iterator rules still need attention.\n\nAssociative containers such as maps and sets can make lookup rules explicit, while unordered containers can make key-based lookup efficient. Their safety depends on correct key design, comparator behavior, hashing, equality, and resource limits.\n\nElement ownership should be deliberate. Storing values is often simpler and clearer. Storing unique_ptr, shared_ptr, or other owning objects can be appropriate, but it changes lifetime, sharing, and review questions. A container of raw owning pointers is usually a sign that ownership needs a clearer type.\n\nGrowth and memory pressure should be part of the contract. If input can influence item count, reserve behavior, or element size, the code needs limits before storage grows without a boundary.\n\nChoose the container that makes the expected access pattern and lifetime easiest to reason about. The safest choice is often the one that turns design assumptions into visible code rather than hidden convention.\n\nContainer choice also affects API clarity. A function that accepts a span communicates a contiguous borrowed range. A function that accepts a vector by value communicates ownership transfer or copying. A function that accepts a map communicates lookup by key. These choices help reviewers understand intent.\n\nWhen the container choice feels awkward, it may reveal a deeper design question. Perhaps the data should be streamed instead of stored, capped instead of unbounded, or converted into a narrower domain type before entering shared state.",
  "narrationPoints": [
    "The container communicates how data is owned, how it grows, how callers access it, and what kinds of invalidation reviewers should expect.",
    "The fixed size can make bounds and lifetime easier to review. std::deque may fit designs that need growth at both ends or different stability.",
    "Storing unique_ptr, shared_ptr, or other owning objects can be appropriate, but it changes lifetime, sharing, and review questions.",
    "If input can influence item count, reserve behavior, or element size, the code needs limits before storage grows without a boundary.",
    "Choose the container that makes the expected access pattern and lifetime easiest to reason about.",
    "When the container choice feels awkward, it may reveal a deeper design question."
  ]
};
