window.COURSE_MODULE = {
  "title": "Strings, Views, and Spans",
  "graphicAlt": "C++ container safety diagram for Strings, Views, and Spans, linking ownership and lifetime to bounds, invalidation, algorithm contracts, bounded growth, synchronization, and exception-safe commit behavior.",
  "narration": "std::string owns its character data and tracks its length. That makes it safer and clearer than many raw character-buffer patterns. But string safety still depends on lifetime, mutation, indexing, encoding assumptions, and the APIs used around it.\n\nstd::string_view is a non-owning view into character data. It is useful because it avoids unnecessary copies and carries a length. It does not extend the lifetime of the string, buffer, or temporary object it refers to. If the source disappears, the view becomes unsafe to use.\n\nstd::span provides a non-owning view over contiguous elements. Like string_view, it preserves a length and helps express a range. Also like string_view, it does not own the underlying storage. A span into a vector is only valid while the vector's relevant storage remains valid and unmoved.\n\nLength-preserving APIs are valuable. A string_view or span can represent data that contains embedded zero bytes or values that are not null-terminated. Code should not accidentally pass such data to APIs that expect a different representation.\n\nViews should usually be short-lived parameters or local variables. Storing them in objects, returning them from factories, or caching them across mutations requires a clear source lifetime guarantee. Views into temporary strings are especially review-sensitive.\n\nSource mutation can invalidate views. Appending to a string, resizing a vector, reserving capacity, clearing storage, or moving an owning object can change where data lives. Existing views, pointers, and references may no longer describe valid data.\n\nThe review question is simple: who owns the data, how long does it live, and can it move or change before the view is used? If those answers are not obvious, prefer an owning type or shorten the view's lifetime.",
  "narrationPoints": [
    "But string safety still depends on lifetime, mutation, indexing, encoding assumptions, and the APIs used around it.",
    "If the source disappears, the view becomes unsafe to use.",
    "Code should not accidentally pass such data to APIs that expect a different representation.",
    "Storing them in objects, returning them from factories, or caching them across mutations requires a clear source lifetime guarantee.",
    "Appending to a string, resizing a vector, reserving capacity, clearing storage, or moving an owning object can change where data lives.",
    "The review question is simple: who owns the data, how long does it live, and can it move or change before the view is used."
  ]
};
