window.COURSE_MODULE = {
  "title": "Secrets, Dependencies, Testing, and Monitoring",
  "graphicAlt": "Managed secrets, reviewed dependencies, boundary tests, and safe monitoring sustain the Flask service over its lifecycle.",
  "narration": "Flask applications frequently use API keys, database credentials, tokens, signing keys, webhook secrets, and service credentials. These values should not be hardcoded into Python files, templates, tests, sample configs, Docker images, logs, or repository history. Secret managers and environment-specific configuration can help, but the key principle is controlled access and rotation. A secret should have an owner, a purpose, a storage location, and a plan for replacement.\n\nDependency hygiene matters because Flask applications are built from the framework, extensions, Python packages, container images, operating system libraries, and deployment components. Pinning concepts, dependency review, vulnerability scanning, and update processes help teams avoid surprises. The goal is not to chase every alert blindly, but to know what is running, where it is used, what risk it creates, and how updates are tested and deployed safely.\n\nSecurity testing should be part of normal Flask development. Unit and integration tests can verify request validation, authentication requirements, authorization boundaries, CSRF behavior, session transitions, upload limits, error handling, and logging expectations. Negative tests are especially valuable because they prove the application refuses actions it should not allow. Static analysis and secrets scanning can support this work, but human review still matters for business logic and design assumptions.\n\nMonitoring and incident readiness keep security alive after deployment. Safe logs should capture important security events without exposing secrets or sensitive data unnecessarily. Audit events may include login changes, MFA changes, permission changes, administrative actions, exports, failed authorization attempts, and configuration changes. Teams should know which events matter, how alerts are triaged, and how to investigate safely. Flask security continues for as long as the application is operated.",
  "narrationPoints": [
    "Flask applications frequently use API keys, database credentials, tokens, signing keys, webhook secrets, and service credentials.",
    "Dependency hygiene matters because Flask applications are built from the framework, extensions, Python packages, container images, operating system libraries, and deployment components.",
    "Security testing should be part of normal Flask development.",
    "Monitoring and incident readiness keep security alive after deployment."
  ]
};
