window.COURSE_MODULE = {
  "title": "Use Authenticated Encryption for Protected Application Data",
  "graphicAlt": "An encrypted record with nonce, tag, and format and key-version metadata enters authenticated decryption with the key and trusted expected context. Provisional bytes stay inside the gate. Verification releases plaintext; failure ends with no plaintext. Access authorization and replay rules are separate application checks.",
  "narration": "When application data needs confidentiality and tamper detection, use an established authenticated encryption construction supported by a mature library. Authenticated encryption with associated data, often abbreviated AEAD, accepts plaintext and optional context that needs integrity protection without secrecy. AES GCM and ChaCha20 Poly1305 are common examples. The engineering task is to satisfy the chosen construction's contract, not to compare algorithms casually or assemble equivalent behavior from lower level pieces.\n\nAssociated data can bind ciphertext to a tenant, record, purpose, or schema version. It remains visible, but a change causes authentication to fail when the expected context is supplied during decryption. Reconstruct that expected context from the authorized operation and trusted records, rather than accepting an arbitrary context supplied alongside the ciphertext. Define a stable byte encoding for it. Semantically similar objects with different serialization can otherwise produce different authentication inputs.\n\nPreserve the information needed to decrypt: an approved format version, key identifier or version, nonce, ciphertext, and authentication tag where the API exposes it separately. A format may combine some of these fields. Binary values can be encoded for storage, but their encoding adds no protection. Validate the record's structure and route version metadata through controlled policy. Stored algorithm names must not enable arbitrary constructions or unexpected key access.\n\nAuthenticated decryption must either return verified plaintext or fail. Some low level streaming APIs produce provisional bytes before the final authentication check; do not release those bytes to callers or side effects. Prefer a wrapper that enforces this boundary and bounds record size. Successful authentication does not establish that the requester may read the record, nor does it automatically prove freshness or prevent replay. Enforce application permissions separately and add state rules if replay matters. The result is a protected representation with clear cryptographic guarantees and clearly identified responsibilities outside those guarantees.",
  "narrationPoints": [
    "Use supported AEAD when confidentiality and tamper detection are required.",
    "Bind trusted expected context through stable associated-data encoding.",
    "Preserve nonce, tag, and controlled format/key metadata.",
    "Release plaintext only after authentication; enforce authorization separately."
  ]
};
