window.COURSE_MODULE = {
  "title": "Generate Keys, Nonces, and Tokens with Cryptographic Randomness",
  "graphicAlt": "Cryptographic randomness supplies keys, tokens, and suitable random nonces; Math.random is rejected. Multiple writers using the same key must not reuse a nonce. Random nonce generation needs collision and usage limits, while counters need durable uniqueness through restarts and restoration. A nonce may accompany ciphertext and is not a secret key.",
  "narration": "Security values need randomness designed to resist prediction. Use the platform's cryptographically secure facilities for keys, unpredictable tokens, and random nonces when the construction calls for them. Node.js provides secure key generation and random bytes, while Web Crypto provides appropriate key generation and secure random APIs. Node's random UUID function is useful for suitable identifiers, but a UUID is not a universal replacement for an algorithm's key or nonce requirements.\n\nDo not use Math dot random for cryptographic keys, reset tokens, or security sensitive nonce generation. Human readable phrases, account identifiers, and timestamps are also poor substitutes for properly generated keys. Follow the algorithm's required key length and generation mechanism. If a human password must be the source, use a purpose built password derivation process rather than simply hashing it into a buffer of the desired size.\n\nA nonce is an input whose required behavior depends on the construction. It usually does not need secrecy and can be stored with ciphertext. For GCM, reuse of a nonce under the same key can critically undermine confidentiality and authentication. A fixed nonce is therefore not a harmless simplification. The uniqueness requirement follows the actual key material, not merely a renamed version label or a process that has just restarted.\n\nRandom nonces can be appropriate within the construction's limits, but random does not mean guaranteed unique. Collision probability, message volume, and all writers sharing a key matter. A counter can work only when the architecture preserves uniqueness across concurrency, failures, restarts, and restored backups. Follow library guidance on nonce size and per key usage limits, and make allocation an owned responsibility of the cryptographic service. Test operational assumptions, not just the byte length. Secure randomness supplies essential material; correct coordination and lifecycle rules determine whether that material is used safely over the full lifetime of a key.",
  "narrationPoints": [
    "Use cryptographic key generation and secure random facilities.",
    "Match key and nonce requirements to the selected construction.",
    "Prevent nonce reuse under the same key across writers and restarts.",
    "Randomness requires collision and usage limits; counters require durable uniqueness."
  ]
};
