window.COURSE_MODULE = {
  "title": "Treat Passwords and Derived Keys Differently from Random Keys",
  "graphicAlt": "Three lanes distinguish salted, expensive password hashing for stored verifiers; password-based key derivation with change and recovery planning; and HKDF with distinct purposes for subkeys from a strong random master secret. Salts are not secret encryption keys, and fast hashing is not a password-storage construction.",
  "narration": "A human password has a different security profile from a randomly generated key. Password choices have limited, uneven entropy, so storing an ordinary fast digest leaves verification guesses inexpensive. Password storage should use a dedicated construction such as Argon2id or scrypt, with a fresh salt for each password and deliberately expensive computation. Select supported parameters for the deployment and benchmark them under realistic load rather than copying an unexplained cost setting.\n\nSalts are normally stored with the password hash and its algorithm and cost metadata. They are not secret encryption keys and do not encrypt the password. Their purpose includes making otherwise identical passwords have distinct stored results and preventing useful sharing of precomputed work across accounts. Let a maintained password hashing interface generate and encode the required salt. Preserve versioned parameters so successful verification can trigger an upgrade when policy changes.\n\nPassword based key derivation is related but serves a different purpose. If the application truly needs a key derived from a human password, use a password KDF with an appropriate salt, work factors, and output length. This does not turn a weak password into a high entropy random secret. Password changes and recovery must be designed around how the resulting key protects data, because changing the password can otherwise make earlier ciphertext inaccessible.\n\nDeriving subkeys from strong secret key material is another case. A construction such as HKDF can produce context separated keys, but it is not an expensive password hashing function and does not replace one. Domain separation gives different roles explicit context, such as encryption versus message authentication or one protocol versus another. Use independently generated keys or a reviewed derivation scheme with distinct purpose labels. Separate environments as well. Reusing one key everywhere makes unrelated cryptographic roles share failure and lifecycle assumptions that the application may never have intended to connect.",
  "narrationPoints": [
    "Store passwords with a dedicated, salted, deliberately expensive password hash.",
    "Keep salts and versioned parameters with password verifiers.",
    "Use a password KDF for password-derived keys; plan changes and recovery.",
    "Use appropriate KDFs and distinct context for subkeys from strong secrets."
  ]
};
