window.COURSE_MODULE = {
  "title": "Course Summary: Design for Cryptography and Key Change Together",
  "graphicAlt": "Four connected responsibilities summarize the design: choose the required security property, protect data with secure randomness and authenticated encryption, control KEKs and DEKs, and plan versioned key changes and recovery. Supporting checks authorize access, verify before releasing plaintext, and test failures and recovery. Password hashing is separate from data encryption, and tampered data is rejected.",
  "narration": "Start with the property the application needs. Confidentiality, integrity, authenticity, and password verification require appropriate constructions. Encoding changes representation, while encryption protects recoverable data with a key. Ordinary hashing does not provide encryption or an appropriate password verifier by itself. Use maintained, high level cryptographic interfaces, and prefer authenticated encryption when stored data needs both confidentiality and tamper detection. Keep authorization and TLS as separate parts of the system.\n\nGenerate keys and security values with cryptographic randomness. Follow the exact nonce contract, including uniqueness under the same key where required. A nonce is not a secret key, and random generation does not eliminate collision or operational limits. Human passwords need deliberately expensive password hashing or password based derivation. Salts normally accompany the stored result and are not secret encryption keys. Derive subkeys from strong material only with an appropriate construction and explicit purpose separation.\n\nA data encryption key protects application content; a key encryption key protects the data key. Envelope encryption can keep long lived keys in managed infrastructure while allowing scoped data keys and controlled rewrapping. It does not prevent plaintext data keys from entering application memory during local operations. Minimize that exposure, separate environments, and make key access narrowly authorized and auditable. Type declarations and delivery through configuration do not supply those controls.\n\nPreserve controlled format and key version metadata so historical records remain understandable. New write rotation, re-encryption, and rewrapping perform different jobs. Emergency compromise response must address exposure that routine rotation cannot undo. Test authentication failures, malformed records, nonce allocation, retired key policy, and migration before depending on those paths. A cryptographic design is not complete when encryption works today. It is complete when the application can use the right primitive safely, protect its keys, detect tampering, rotate those keys, and still understand protected data years later.",
  "narrationPoints": [
    "Match the primitive to the required security property.",
    "Use secure randomness, correct nonces, password hashing, and purpose-separated keys.",
    "Protect DEKs and KEKs with explicit lifecycle and access controls.",
    "Preserve versions and test tampering, rotation, and historical-data recovery."
  ]
};
