window.COURSE_MODULE = {
  "title": "Choosing .NET Base Images",
  "graphicAlt": "Bullet summary graphic for Choosing .NET Base Images.",
  "narration": "Base image selection affects what ships with the application. The image determines available operating system components, runtime dependencies, patching behavior, diagnostics options, certificate stores, globalization support, time zone data, native libraries, and operational tooling. A base image is part of the production architecture, not just a build detail.\n\nSDK images are useful during build because they include compilers, package restore tooling, and development utilities. They should not usually be the final production runtime image. The final image should contain the application and the runtime dependencies needed to operate, without carrying build tools that are not needed after publishing.\n\n.NET runtime and ASP.NET Core runtime images should match the deployment need. A console worker, minimal API, MVC application, background service, and native dependency-heavy application may have different requirements. The right image is the one that supports the application clearly while keeping unnecessary contents out of production.\n\nChiseled or distroless-style .NET images can reduce image contents by omitting shells, package managers, and many extra operating system components. That reduction can make production behavior easier to reason about, but it also means teams must verify diagnostics, certificates, globalization, time zones, native dependencies, and support workflows before adopting the image.\n\nImage tags should be deliberate and maintainable. Teams should know whether they use a version-specific tag, how base image updates are detected, when images are rebuilt, and who approves the move to a new runtime or operating system base. Smaller images help only when the update process is disciplined enough to keep them current.",
  "narrationPoints": [
    "A base image is part of the production architecture, not just a build detail.",
    "SDK images are useful during build because they include compilers, package restore tooling, and development utilities.",
    ".NET runtime and ASP.NET Core runtime images should match the deployment need.",
    "Chiseled or distroless-style .NET images can reduce image contents by omitting shells, package managers, and many extra operating system components.",
    "Teams should know whether they use a version-specific tag, how base image updates are detected, when images are rebuilt, and who approves the move to a new runtime or operating system base."
  ]
};
