window.COURSE_MODULE = {
  "title": "Secrets, Configuration, and Environment Separation",
  "graphicAlt": "Bullet summary graphic for Secrets, Configuration, and Environment Separation.",
  "narration": "Container images should not contain production secrets. Secrets include connection strings, API keys, tokens, certificates, private keys, package feed credentials, signing keys, and cloud credentials. If a secret is baked into an image layer, it can spread through registries, caches, developer machines, build systems, and older image tags.\n\nRuntime configuration should be separated by environment and injected through controlled platform mechanisms. Development, staging, and production should not share secret material or accidentally override reviewed behavior. Local compose files, sample settings, and developer convenience configuration should not drift into production images or deployments.\n\nEnvironment variables can be useful for ordinary configuration, but sensitive values need access control, logging review, and platform-specific handling. Secret mounts, orchestrator secrets, managed identities, workload identities, and external secret stores can reduce secret sprawl when teams govern who can read them and how they rotate.\n\nASP.NET Core configuration precedence should be understood. Values can come from files, environment variables, command line arguments, user secrets in development, mounted files, and platform providers. A later source may override an earlier reviewed setting, so teams should document expected sources and validate sensitive production configuration.\n\nDiagnostics and support workflows must not expose secrets. Logs, crash dumps, environment dumps, exception pages, health endpoints, screenshots, shell history, and support bundles can all reveal container environment values or mounted secret contents if they are not reviewed. Redaction should be designed into the application and platform process.",
  "narrationPoints": [
    "If a secret is baked into an image layer, it can spread through registries, caches, developer machines, build systems, and older image tags.",
    "Runtime configuration should be separated by environment and injected through controlled platform mechanisms.",
    "Environment variables can be useful for ordinary configuration, but sensitive values need access control, logging review, and platform-specific handling.",
    "Values can come from files, environment variables, command line arguments, user secrets in development, mounted files, and platform providers.",
    "Logs, crash dumps, environment dumps, exception pages, health endpoints, screenshots, shell history, and support bundles can all reveal container environment values or mounted secret contents if they are not reviewed."
  ]
};
