window.COURSE_MODULE = {
  "title": "Logging, Diagnostics, Debugging, and Production Review",
  "graphicAlt": "Bullet summary graphic for Logging, Diagnostics, Debugging, and Production Review.",
  "narration": "Production containers should be observable without carrying unnecessary debug tools or exposing sensitive data. Runtime images should not include shells, package managers, debug utilities, source code, test data, or secret-bearing artifacts unless there is a justified and reviewed operational need.\n\nLogs should flow to the platform logging pipeline and be safe for centralized collection. They should avoid tokens, connection strings, cookies, authorization headers, raw request bodies, secret environment variables, mounted secret contents, and sensitive business data. Structured logs should include safe context such as operation name, correlation ID, image version, environment, and dependency name.\n\nDebug endpoints, diagnostic ports, crash dumps, tracing, and metrics should be environment-scoped and access-controlled. A diagnostic feature that is appropriate in development may be inappropriate in production without access controls, redaction, retention rules, and incident handling guidance.\n\nUseful operational signals include container health, restart count, memory usage, CPU pressure, socket usage, failed probes, startup time, image version, deployment metadata, dependency errors, and configuration source. These signals help teams distinguish application faults, platform constraints, dependency problems, and deployment mistakes.\n\nProduction review should cover image choice, Dockerfile design, user identity, writable paths, secrets, ports, probes, resource limits, image scanning, registry controls, logging, rollback, and incident response. A secure container release is not only a Dockerfile; it is a lifecycle that keeps build, runtime, and operations aligned.",
  "narrationPoints": [
    "Runtime images should not include shells, package managers, debug utilities, source code, test data, or secret-bearing artifacts unless there is a justified and reviewed operational need.",
    "Structured logs should include safe context such as operation name, correlation ID, image version, environment, and dependency name.",
    "Debug endpoints, diagnostic ports, crash dumps, tracing, and metrics should be environment-scoped and access-controlled.",
    "Useful operational signals include container health, restart count, memory usage, CPU pressure, socket usage, failed probes, startup time, image version, deployment metadata, dependency errors, and configuration source.",
    "Production review should cover image choice, Dockerfile design, user identity, writable paths, secrets, ports, probes, resource limits, image scanning, registry controls, logging, rollback, and incident response."
  ]
};
