window.COURSE_MODULE = {
  "title": "Threat Intelligence and Hunting",
  "graphicAlt": "Threat-intelligence integration model connecting adversary trends, organizational risk, local telemetry, hypotheses, investigations, and detection feedback.",
  "narration": "Threat intelligence helps hunters decide where to focus. It provides context about adversary behaviors, affected sectors, common objectives, technology trends, and observed changes that may be relevant to the organization.\n\nIntelligence is most useful when connected to local risk. A report may be important globally but less relevant to the organization's technologies, geography, data, customers, or operating model. Hunters should evaluate applicability before committing resources.\n\nBehavioral information often has longer value than a single technical indicator. Understanding the kinds of actions an adversary may attempt can help teams look for patterns across different systems even after specific infrastructure or identifiers change.\n\nTechnical indicators can still support focused review, but they require context, freshness, and validation. An old or low-confidence indicator should not automatically be treated as proof of harmful activity.\n\nIntelligence can shape a hypothesis by identifying a plausible concern, likely targets, expected evidence, and relevant data sources. The resulting hunt should remain an investigation, not a predetermined effort to confirm the intelligence report.\n\nLocal observations also improve intelligence. Hunters may learn that a reported behavior is not visible with current telemetry, that it appears differently in their environment, or that particular systems deserve stronger defensive attention.\n\nCollaboration among intelligence analysts, hunters, detection engineers, incident responders, and system owners creates a useful feedback loop. External context becomes a local question, and local evidence improves future defensive decisions.\n\nIntelligence does not guarantee findings or replace telemetry. It helps prioritize limited hunting capacity and gives analysts a stronger basis for selecting questions that matter to the organization's risk.",
  "narrationPoints": [
    "Threat intelligence helps hunters decide where to focus.",
    "It provides context about adversary behaviors, affected sectors, common objectives, technology trends, and observed changes that may be relevant to the organization.",
    "Intelligence is most useful when connected to local risk.",
    "A report may be important globally but less relevant to the organization's technologies, geography, data, customers, or operating model.",
    "Hunters should evaluate applicability before committing resources.",
    "Behavioral information often has longer value than a single technical indicator."
  ]
};
