window.COURSE_MODULE = {
  "title": "Data Races and Shared Mutable State",
  "graphicAlt": "Concurrent execution diagram for Data Races and Shared Mutable State, showing worker lanes around protected shared state, scoped synchronization, cancellation and shutdown paths, plus a deterministic test checkpoint for the shared invariant.",
  "narration": "A data race occurs when multiple threads access the same mutable object without proper synchronization and at least one access modifies it. In C++, that is more than a timing bug. It can create undefined behavior, which means the program is no longer operating under a reliable contract.\n\nThe defensive response is not to add locks everywhere after the fact. Start by reducing shared mutable state. If data can be immutable, passed by value, owned by one thread, or moved through a queue, the design is often easier to reason about than a shared object protected by scattered synchronization.\n\nThread confinement is a powerful simplifier. When a piece of state is only accessed by one worker, one event loop, or one owner at a time, review can focus on transfer points instead of every line that touches the object.\n\nWhen state must be shared, make the sharing visible. Avoid hidden global state, untracked singletons, caches with unclear locking policy, and references that quietly cross thread boundaries. A reviewer should not have to search the whole program to learn what else can mutate an object.\n\nPassing tests once does not prove concurrency safety. Scheduling changes with CPU count, compiler options, instrumentation, logging, timing, load, and operating-system behavior. A race that does not appear during a normal test run can still be present.\n\nSecure design should first ask whether sharing is necessary. If it is, define the owner, the protection mechanism, the allowed operations, and the lifetime of the shared object. That clarity turns concurrency review from guesswork into a concrete engineering check.\n\nThe durable habit is to prefer simple ownership over clever coordination. Shared mutable state is sometimes necessary, but every shared object should earn its place and have a documented protection story.",
  "narrationPoints": [
    "A data race occurs when multiple threads access the same mutable object without proper synchronization and at least one access modifies it.",
    "If data can be immutable, passed by value, owned by one thread, or moved through a queue, the design is often easier to reason about than a shared object protected by scattered synchronization.",
    "When a piece of state is only accessed by one worker, one event loop, or one owner at a time, review can focus on transfer points instead of every line that touches the object.",
    "Avoid hidden global state, untracked singletons, caches with unclear locking policy, and references that quietly cross thread boundaries.",
    "Scheduling changes with CPU count, compiler options, instrumentation, logging, timing, load, and operating-system behavior.",
    "Shared mutable state is sometimes necessary, but every shared object should earn its place and have a documented protection story."
  ]
};
