window.COURSE_MODULE = {
  "title": "Mutexes, RAII Locks, and Critical Sections",
  "graphicAlt": "Concurrent execution diagram for Mutexes, RAII Locks, and Critical Sections, showing worker lanes around protected shared state, scoped synchronization, cancellation and shutdown paths, plus a deterministic test checkpoint for the shared invariant.",
  "narration": "Mutexes remain one of the most practical tools for protecting shared C++ state. A mutex should guard a specific invariant: a relationship among fields, a container and its metadata, a queue and its shutdown flag, or another piece of shared state that must be observed consistently.\n\nRAII lock wrappers make mutex use safer. std::lock_guard, std::unique_lock, and std::scoped_lock tie lock release to scope exit. That matters when a function returns early, throws an exception, or grows over time. Manual lock and unlock calls are fragile because every future path must remember to release the lock exactly once.\n\nThe lock scope should be easy to see. Keep critical sections focused on reading or updating the protected state. Avoid placing unrelated formatting, slow computation, callbacks, or blocking work inside the lock unless the design clearly requires it.\n\nDocument which mutex protects which data. The most maintainable pattern is often a private mutex near the data it protects, with methods that preserve the invariant while the lock is held. Comments can help when a class has more than one synchronization domain.\n\nAvoid accessing protected data outside the lock. Even a single convenience read can weaken the whole design if another thread may update the same object concurrently. If an unlocked read is intentional, it should have a clearly justified policy, such as immutable data or atomic state.\n\nReview should ask what must be true while the lock is held, what can happen if an exception occurs, and whether callers can observe half-updated state. Clarity is usually more valuable than clever locking patterns.\n\nA good mutex design gives maintainers a small proof to check: acquire the right lock, update the invariant, release through RAII, and leave no hidden path around the protection.",
  "narrationPoints": [
    "A mutex should guard a specific invariant: a relationship among fields, a container and its metadata, a queue and its shutdown flag, or another piece of shared state that must be observed consistently.",
    "RAII lock wrappers make mutex use safer. std::lock_guard, std::unique_lock, and std::scoped_lock tie lock release to scope exit.",
    "Avoid placing unrelated formatting, slow computation, callbacks, or blocking work inside the lock unless the design clearly requires it.",
    "Even a single convenience read can weaken the whole design if another thread may update the same object concurrently.",
    "Review should ask what must be true while the lock is held, what can happen if an exception occurs, and whether callers can observe half-updated state.",
    "A good mutex design gives maintainers a small proof to check: acquire the right lock, update the invariant, release through RAII, and leave no hidden path around the protection."
  ]
};
