window.COURSE_MODULE = {
  "title": "Atomics and Memory Ordering at a Safe Level",
  "graphicAlt": "Concurrent execution diagram for Atomics and Memory Ordering at a Safe Level, showing worker lanes around protected shared state, scoped synchronization, cancellation and shutdown paths, plus a deterministic test checkpoint for the shared invariant.",
  "narration": "Atomics are specialized synchronization tools for simple shared state. They are commonly used for flags, counters, reference-like coordination, state transitions, and low-level concurrency utilities. Used carefully, they can prevent data races on the atomic object itself.\n\nThe important limitation is that an atomic field does not automatically make a larger object safe. If two fields must change together, or if a container and a status flag form one invariant, making only one field atomic may leave the relationship unprotected.\n\nMutexes protect invariants across multiple operations. Atomics protect individual atomic operations and carefully designed coordination patterns. Choosing between them should be based on the shape of the state, not on an assumption that atomics are always faster or more advanced.\n\nMemory ordering should be treated with humility. The default sequentially consistent ordering is generally easier for teams to reason about. Weaker ordering can be correct, but it requires a clear proof, strong justification, careful review, and maintainers who understand the contract.\n\nAtomic code is often compact, which can make it deceptively hard to review. A compare-exchange loop, generation counter, or cancellation flag may carry important assumptions about visibility, progress, and ownership.\n\nUse higher-level synchronization when it makes the design clearer. A simple mutex and condition variable may be safer than a custom atomic protocol if more engineers can understand and maintain it.\n\nA defensible atomic design names what the atomic value represents, what transitions are allowed, what other data it coordinates with, and what memory-ordering assumptions are being made. Without that explanation, atomic code should be considered review-sensitive.",
  "narrationPoints": [
    "Used carefully, they can prevent data races on the atomic object itself.",
    "If two fields must change together, or if a container and a status flag form one invariant, making only one field atomic may leave the relationship unprotected.",
    "Choosing between them should be based on the shape of the state, not on an assumption that atomics are always faster or more advanced.",
    "Weaker ordering can be correct, but it requires a clear proof, strong justification, careful review, and maintainers who understand the contract.",
    "A simple mutex and condition variable may be safer than a custom atomic protocol if more engineers can understand and maintain it.",
    "A defensible atomic design names what the atomic value represents, what transitions are allowed, what other data it coordinates with, and what memory-ordering assumptions are being made."
  ]
};
