window.COURSE_MODULE = {
  "title": "Testing, Tooling, Logging, and Review",
  "graphicAlt": "Concurrent execution diagram for Testing, Tooling, Logging, and Review, showing worker lanes around protected shared state, scoped synchronization, cancellation and shutdown paths, plus a deterministic test checkpoint for the shared invariant.",
  "narration": "Multithreaded C++ needs both design review and practical validation. Tools cannot prove every concurrency property, but they can reveal defects that ordinary tests may miss. ThreadSanitizer is useful where available for detecting data races during instrumented test execution.\n\nAddressSanitizer can also help with lifetime-adjacent issues that become visible in concurrent code, such as use after object destruction on a path that testing happens to exercise. Static analysis, compiler warnings, debug iterator modes, and code review checklists all add useful coverage.\n\nTests should include deterministic unit tests around synchronization boundaries. Exercise empty queues, full queues, cancellation, shutdown while work is pending, repeated start and stop cycles, and contention on shared state. Stress tests are useful, but they should complement focused tests rather than replace them.\n\nLogging in concurrent code must also be reviewed. Log calls should not introduce races, hold locks for long periods, call back into components while locks are held, or expose sensitive data. Logs should contain enough context to reconstruct behavior without overwhelming the system.\n\nReview questions should be concrete. What state is shared? What protects it? Which mutex protects which invariant? Can callbacks outlive their targets? Can shutdown race with pending work? Can lock order create a wait cycle? Are atomics coordinating more than they safely describe?\n\nCI checks can run sanitizer-enabled builds, targeted concurrency tests, static analysis, and warnings-as-errors for code that is practical to cover that way. The goal is to make race-sensitive code visible during normal engineering workflow.\n\nTools support design judgment; they do not replace it. The best results come from code that has clear ownership and synchronization first, then uses tools to catch mistakes before they reach production.",
  "narrationPoints": [
    "ThreadSanitizer is useful where available for detecting data races during instrumented test execution.",
    "Static analysis, compiler warnings, debug iterator modes, and code review checklists all add useful coverage.",
    "Stress tests are useful, but they should complement focused tests rather than replace them.",
    "Logging in concurrent code must also be reviewed.",
    "CI checks can run sanitizer-enabled builds, targeted concurrency tests, static analysis, and warnings-as-errors for code that is practical to cover that way.",
    "The best results come from code that has clear ownership and synchronization first, then uses tools to catch mistakes before they reach production."
  ]
};
