window.COURSE_MODULE = {
  "title": "Securing API Access from Blazor Clients",
  "graphicAlt": "APIs independently authenticate, authorize, and validate Blazor requests; CORS governs browser origins, while cookie request intent and token audience and lifetime are separate concerns.",
  "narration": "Blazor applications often depend on backend APIs for data retrieval and state changes. Those APIs may be called from server-side code, browser-delivered WebAssembly code, or a mix of client and server paths. The API is the authority for protected data and operations, so it must authenticate and authorize requests independently of what the UI decided to show.\n\nA Blazor WebAssembly client should be treated like a browser single-page application from a security standpoint. It can hold user interface logic and call services, but it is not a trusted boundary. API design should assume that requests arrive from a browser client and must be evaluated by the backend.\n\nCookie-authenticated browser APIs and bearer-token APIs have different implications. Cookie-based flows may require antiforgery protection for unsafe browser requests and careful cookie settings. Token-based flows require review of token audience, lifetime, storage, refresh behavior, and what parts of the system can access them.\n\nBrowser-accessible tokens and state require careful design. If a value is available to browser code, the application should not treat it as a protected server secret. The design should minimize what is exposed, prefer short-lived and scoped credentials where appropriate, and keep authoritative decisions in the backend.\n\nCORS controls browser cross-origin access behavior. It is not authentication, and it is not authorization. Allowing a browser origin to call an API does not mean the API should trust the caller or skip policy checks. CORS should describe approved browser integration, while identity and authorization remain separate controls.\n\nBackend-for-frontend and server-mediated API access are design options when teams want the server to manage sensitive coordination or reduce browser exposure. Those patterns can improve control when applied carefully, but they still need clear authentication, authorization, validation, logging, and operational ownership.",
  "narrationPoints": [
    "Blazor applications often depend on backend APIs for data retrieval and state changes.",
    "A Blazor WebAssembly client should be treated like a browser single-page application from a security standpoint.",
    "Cookie-authenticated browser APIs and bearer-token APIs have different implications.",
    "Browser-accessible tokens and state require careful design.",
    "CORS controls browser cross-origin access behavior."
  ]
};
