window.COURSE_MODULE = {
  "title": "Browser Storage, Client State, and JavaScript Interop",
  "graphicAlt": "Browser storage and client state support convenience, JavaScript interop is reviewed as a data boundary, and authoritative permissions and protected secrets remain server-side.",
  "narration": "Browser storage and client state are not trusted security boundaries. localStorage, sessionStorage, IndexedDB, query strings, hidden fields, and client-side component state can support useful workflows, but they are not the right place for secrets or authoritative permissions. The browser is an environment controlled by the user.\n\nClient state can improve performance and user experience. It can remember view preferences, draft choices, non-sensitive workflow hints, or cached data that the application is comfortable revalidating. It should not decide who owns a record, which tenant is active, what role a user has, or whether a sensitive action is allowed.\n\nProtected browser storage has important limitations. It can help with specific scenarios, but it should not be treated as a universal production secret store. Teams should understand what protection it provides, which hosting models it supports, how keys are handled, and what data remains visible or usable in the browser context.\n\nJavaScript interop crosses a boundary between .NET code and browser JavaScript. Data passed through interop should be reviewed, especially when it includes user-controlled values, identifiers, sensitive fields, or values used by third-party libraries. Interop can be necessary and useful, but it deserves clear ownership and review.\n\nThird-party JavaScript, browser extensions, analytics scripts, embedded content, and component libraries can change the risk picture. They may observe page behavior, manipulate the document, load additional resources, or change how data is handled. A production Blazor application should know which browser-side dependencies it uses and why.\n\nAuthoritative checks belong on the server or API. The client may hold temporary state and coordinate the interface, but the server should confirm identity, authorization, resource scope, and business rules before returning protected data or performing important operations.",
  "narrationPoints": [
    "Browser storage and client state are not trusted security boundaries. localStorage, sessionStorage, IndexedDB, query strings, hidden fields, and client-side component state can support useful workflows, but they are not the right place for secrets or authoritative permissions.",
    "Client state can improve performance and user experience.",
    "Protected browser storage has important limitations.",
    "JavaScript interop crosses a boundary between .NET code and browser JavaScript.",
    "Third-party JavaScript, browser extensions, analytics scripts, embedded content, and component libraries can change the risk picture."
  ]
};
