window.COURSE_MODULE = {
  "title": "Course Summary: An Intelligence Analysis Operating Routine",
  "graphicAlt": "Conceptual visual of a repeatable intelligence analysis operating routine.",
  "narration": "A repeatable intelligence analysis routine begins with the decision. Before collecting more information, define the intelligence question, audience, timeframe, and level of detail needed. Ask what decision the analysis should support and what would make the answer useful. This keeps the work focused and prevents collection from becoming a substitute for reasoning.\n\nGather only authorized, relevant information. Use lawful, ethical, policy-approved sources such as public reports, internal authorized telemetry summaries, incident notes, vendor advisories, risk registers, business context, and sanitized case data. Protect sensitive information and minimize what you collect. Analysis quality does not require invading privacy or gathering information outside approved boundaries.\n\nEvaluate sources and information. Separate source reliability from information credibility. Ask whether the source has relevant access, whether the claim is plausible, whether it is timely, whether it is corroborated, and what limitations apply. Document those limits so others can review and update the assessment later.\n\nOrganize evidence. Build a timeline, source table, evidence matrix, issue tracker, or structured note set that preserves provenance. Good organization reveals sequence, gaps, patterns, and contradictions. It also helps the team work under pressure without losing track of what is known and what is assumed.\n\nSeparate facts, assumptions, hypotheses, judgments, and recommendations. Label assumptions. Test hypotheses against evidence. Use structured analytic techniques when the problem is complex, uncertain, or important. Consider alternatives and ask what evidence would change the assessment. This reduces the chance that the first plausible answer becomes the final answer too quickly.\n\nCommunicate clearly. Lead with key judgments or bottom-line findings. Explain evidence, assumptions, confidence, uncertainty, implications, and next steps. Match the product to the audience. Avoid unsupported claims, vague wording, and hidden uncertainty. A good intelligence product makes reasoning visible enough that decision makers can act and reviewers can understand.\n\nFinally, review outcomes. After the decision, ask whether the analysis helped, what changed, what assumptions held, what evidence was missing, and what should be improved next time. Intelligence analysis is disciplined reasoning in service of better decisions. Its value comes from evidence, transparency, humility, and a constant effort to make judgment more useful.",
  "narrationPoints": [
    "Define the decision and intelligence question.",
    "Evaluate sources and organize evidence.",
    "Separate facts, assumptions, judgments, and recommendations.",
    "Test alternatives and communicate uncertainty.",
    "Review outcomes to improve future analysis."
  ]
};
