window.COURSE_MODULE = {
  "title": "Mapping Child Process Flows and Trust Boundaries",
  "graphicAlt": "Control-and-evidence diagram for Mapping Child Process Flows and Trust Boundaries in Secure Child Process Usage in Node.js, linking each security decision to the protected asset, the enforcing component, the failure state, and the observable verification signal.",
  "narration": "A secure review starts with context. Inventory every place the application uses child_process, shell wrappers, npm scripts, CLI tools, deployment scripts, background workers, and libraries that may start external programs. Include production routes, scheduled jobs, CI/CD workflows, local maintenance scripts that might be promoted later, and third-party packages that invoke native tools. A child process hidden behind a helper is still a child process from a risk perspective.\n\nFor each execution path, identify who or what can trigger it. Public users, authenticated users, administrators, webhooks, queues, scheduled jobs, internal services, and build systems all create different risk levels. Then map input sources: route parameters, request bodies, uploaded filenames, database values, queue messages, configuration, environment variables, admin form fields, and metadata from previous processing steps. A value from a database can still be externally influenced if it originally came from a user or partner system.\n\nThe key review questions are practical. Why is this process needed? Which executable is allowed? Which arguments are allowed? What files, directories, secrets, network services, stdin, stdout, stderr, and inherited environment variables are available? Where does output go? How long can it run? What happens when it fails? This turns child process review into a system design exercise instead of a narrow inspection of one helper function.",
  "narrationPoints": [
      "A child process hidden behind a helper is still a child process from a risk perspective.",
      "Then map input sources: route parameters, request bodies, uploaded filenames, database values, queue messages, configuration, environment variables, admin form fields, and metadata from previous processing steps.",
      "This turns child process review into a system design exercise instead of a narrow inspection of one helper function.",
      "Inventory every place the application uses child_process, shell wrappers, npm scripts, CLI tools, deployment scripts, background workers, and libraries that may start external programs.",
      "What files, directories, secrets, network services, stdin, stdout, stderr, and inherited environment variables are available?",
      "Include production routes, scheduled jobs, CI/CD workflows, local maintenance scripts that might be promoted later, and third-party packages that invoke native tools."
  ]
};
