window.COURSE_MODULE = {
  "title": "Least Privilege, Isolation, and Runtime Controls",
  "graphicAlt": "Control-and-evidence diagram for Least Privilege, Isolation, and Runtime Controls in Secure Child Process Usage in Node.js, linking each security decision to the protected asset, the enforcing component, the failure state, and the observable verification signal.",
  "narration": "Child process security should assume mistakes can happen. Validation may be incomplete, a tool may contain a vulnerability, a dependency may behave unexpectedly, or an input file may trigger expensive behavior. Least privilege and isolation reduce the blast radius when something goes wrong. Run the Node.js application and child processes with only the privileges they need, and avoid root or administrative execution unless there is a documented exceptional requirement.\n\nHigher-risk processing can often be moved into isolated workers, containers, restricted service accounts, or dedicated job environments. A conversion worker might have a read-only input directory, a narrow writable temporary directory, no production secrets, no unnecessary outbound network access, limited CPU and memory, and a queue that controls concurrency. Avoid exposing Docker sockets, broad host mounts, secret directories, privileged container settings, or broad credentials to process-execution workflows.\n\nDefense in depth does not replace safe command construction and validation. execFile, spawn, argument arrays, allowlists, validation, and containers are useful controls, but none of them alone proves the workflow is safe. Review runtime policy together with application code. Ask what the child process can read, what it can write, what network destinations it can reach, which secrets it can see, and how much damage it can cause if the tool or input behaves unexpectedly.",
  "narrationPoints": [
      "Least privilege and isolation reduce the blast radius when something goes wrong.",
      "Avoid exposing Docker sockets, broad host mounts, secret directories, privileged container settings, or broad credentials to process-execution workflows.",
      "Ask what the child process can read, what it can write, what network destinations it can reach, which secrets it can see, and how much damage it can cause if the tool or input behaves unexpectedly.",
      "Child process security should assume mistakes can happen.",
      "A conversion worker might have a read-only input directory, a narrow writable temporary directory, no production secrets, no unnecessary outbound network access, limited CPU and memory, and a queue that controls concurrency.",
      "Validation may be incomplete, a tool may contain a vulnerability, a dependency may behave unexpectedly, or an input file may trigger expensive behavior."
  ]
};
