window.COURSE_MODULE = {
  "title": "Course Summary and Practical Checklist",
  "graphicAlt": "Layered architecture view of Course Summary and Practical Checklist for Secure Child Process Usage in Node.js, placing the protected asset at the center and surrounding it with identity, validation, resource, lifecycle, and monitoring controls.",
  "narration": "Secure child process usage starts by asking whether a child process is needed. If a safer library, platform API, or service interface meets the requirement, prefer that option. When a child process is justified, prefer direct executable calls with structured argument arrays over shell command strings. Treat all externally influenced values as untrusted, including values from users, databases, queues, webhooks, configuration, uploaded filenames, admin forms, and environment variables.\n\nMake command behavior explicit. Allowlist supported commands, modes, formats, options, paths, and business actions. Validate each argument by purpose, type, length, range, format, and allowed values. Control environment variables, cwd, PATH behavior, stdin, stdout, stderr, generated files, and temporary storage. Avoid leaking secrets, command details, private paths, file contents, or sensitive output through logs and error responses.\n\nBound the process lifecycle and reduce blast radius. Set timeouts, output limits, concurrency limits, queue limits, and cleanup behavior. Run with least privilege and isolate higher-risk processing with narrow filesystem access, limited mounts, restricted credentials, controlled network access, and monitored worker environments. Avoid privileged execution, broad host mounts, Docker socket exposure, broad filesystem access, and inherited production secrets unless a strict exception has been reviewed.\n\nA practical first-week plan is direct: inventory child_process usage, remove unnecessary shell calls, replace raw command strings with fixed executables and argument arrays, validate arguments, minimize environment inheritance, add timeouts, review privileges, check logs for secrets, and add tests for rejected input and timeout behavior. Over time, build child process review into pull requests, CI/CD, monitoring, and incident response so the control remains durable.",
  "narrationPoints": [
      "Secure child process usage starts by asking whether a child process is needed.",
      "Avoid leaking secrets, command details, private paths, file contents, or sensitive output through logs and error responses.",
      "Set timeouts, output limits, concurrency limits, queue limits, and cleanup behavior.",
      "A practical first-week plan is direct: inventory child_process usage, remove unnecessary shell calls, replace raw command strings with fixed executables and argument arrays, validate arguments, minimize environment inheritance, add timeouts, review privileges, check logs for secrets, and add tests for rejected input and timeout behavior.",
      "Run with least privilege and isolate higher-risk processing with narrow filesystem access, limited mounts, restricted credentials, controlled network access, and monitored worker environments.",
      "Over time, build child process review into pull requests, CI/CD, monitoring, and incident response so the control remains durable."
  ]
};
