window.COURSE_MODULE = {
  "title": "Endpoint Organization, Route Groups, and Metadata",
  "graphicAlt": "Purpose-based route groups make public, tenant, administrative, and internal surfaces visible, with exceptions singled out for review.",
  "narration": "Endpoint organization affects security review. Minimal APIs can grow from a few routes into many endpoints across public features, tenant workflows, administrative operations, internal integrations, health checks, and preview functionality. If those endpoints are mixed casually, reviewers can struggle to see which security expectations apply to which surface.\n\nRoute groups can apply shared conventions and make related endpoints easier to inspect. A group can represent a public API area, a tenant-scoped API, an administrative API, or a versioned API surface. Shared metadata, tags, authorization requirements, filters, and OpenAPI conventions can make the group's purpose visible.\n\nEndpoint names, tags, route structure, and metadata should communicate purpose. A route name that describes a business operation is easier to review than a generic handler name. Tags help documentation readers understand the API surface. Metadata can reveal authorization policy, rate-limit policy, OpenAPI behavior, and other expectations that matter during review.\n\nAdmin, internal, public, tenant, and user-facing endpoints should not be mixed without clear boundaries. A public route group should not casually contain administrative operations. A tenant route group should preserve tenant context and access expectations. Internal endpoints should have explicit access rules and operational ownership rather than relying on where they happen to live in the file.\n\nGroup-level configuration improves consistency, but it can also hide exceptions. If most endpoints in a group require one policy and one endpoint needs different behavior, that exception should be visible, documented, and reviewed. Exceptions are not forbidden, but they should not be accidental.\n\nGood route organization also helps authorization, OpenAPI documentation, logging, and operations. When endpoints are grouped by purpose and sensitivity, teams can apply policies consistently, produce more accurate documentation, create clearer metrics, and troubleshoot production behavior with less guesswork.",
  "narrationPoints": [
    "Endpoint organization affects security review.",
    "Route groups can apply shared conventions and make related endpoints easier to inspect.",
    "Endpoint names, tags, route structure, and metadata should communicate purpose.",
    "Admin, internal, public, tenant, and user-facing endpoints should not be mixed without clear boundaries.",
    "Group-level configuration improves consistency, but it can also hide exceptions."
  ]
};
