window.COURSE_MODULE = {
  "title": "Authentication in Minimal APIs",
  "graphicAlt": "Configured authentication establishes caller context before authorization; cookies and explicitly presented bearer tokens require different handling.",
  "narration": "Authentication answers the question, who is making this request. Minimal APIs use the same ASP.NET Core authentication system as the rest of the platform. Depending on the application, that may involve bearer tokens for API clients, cookies for browser-based workflows, external identity providers, or other configured schemes.\n\nThe important point is that authentication must be explicit. A Minimal API endpoint should not rely on local development identity assumptions, trusted test headers, route naming, or a client convention as proof of identity. The identity should come from the configured authentication system and should be available to the endpoint through the normal ASP.NET Core request context.\n\nAuthentication middleware behavior and order should be understood. The application needs the authentication middleware to establish the caller before authorization decisions depend on that identity. Route groups and endpoint metadata can make requirements visible, but the pipeline still needs to be configured correctly so those requirements are enforced at runtime.\n\nCookie-authenticated browser APIs and bearer-token APIs have different security considerations. Cookie-based APIs may involve browser session behavior, SameSite settings, CSRF prevention for unsafe requests, and frontend integration choices. Bearer-token APIs usually expect the client to present a token explicitly, which changes the browser credential model but still requires careful token handling and authorization.\n\nAuthentication failure behavior should be predictable for API clients. A browser page may expect a redirect in some flows, while an API client may expect a status response with a clear but minimal error shape. The response should not disclose sensitive internal details, and it should be consistent enough for clients and operators to understand.\n\nA good Minimal API baseline documents which schemes are used, which endpoints require identity, how failures are represented, and how development behavior differs from production behavior. That clarity prevents identity assumptions from becoming hidden application policy.",
  "narrationPoints": [
    "Authentication answers the question, who is making this request.",
    "The important point is that authentication must be explicit.",
    "Authentication middleware behavior and order should be understood.",
    "Cookie-authenticated browser APIs and bearer-token APIs have different security considerations.",
    "Authentication failure behavior should be predictable for API clients."
  ]
};
