window.COURSE_MODULE = {
  "title": "Parameter Binding, DTOs, and Input Boundaries",
  "graphicAlt": "Narrow input and response DTOs surround validation and authorization; server-controlled fields remain outside the client update contract.",
  "narration": "Minimal API parameter binding converts request data into handler parameters. That data may come from route values, query strings, headers, request bodies, forms, services, or custom binders. Binding is convenient because it lets the handler receive typed values. It is not a security decision by itself.\n\nBound data remains untrusted. A value that arrives as an integer, GUID, enum, string, DTO, uploaded file, or service-resolved object still needs validation for the operation. The binder can help create a value in the expected .NET shape, but it does not know whether the value is allowed, meaningful, owned by the caller, or safe for downstream use.\n\nDTOs help define the intended input contract. A create request, update request, search request, import request, and administrative request should accept only the fields the caller is supposed to provide. A narrow DTO is easier to validate and easier to review than a broad domain model with many properties.\n\nAvoid binding directly to domain models when doing so would allow over-posting or accidental modification of sensitive fields. Server-controlled values such as ownership, tenant, role, approval state, pricing, status, audit fields, or administrative flags should usually be assigned by server logic, not accepted from a general request body.\n\nExplicit output models matter too. The object used internally by the application may include fields that should not leave the server. Response DTOs help avoid accidental exposure of internal fields, secrets, flags, tokens, administrative notes, or implementation details. Input and output boundaries are both part of API security.\n\nRequest body size, file upload behavior, and form binding risk should also be reviewed conceptually. Large bodies, file data, multipart forms, and custom binders can consume resources or introduce parsing assumptions before the handler performs business validation. Endpoint design should make those boundaries explicit.",
  "narrationPoints": [
    "Minimal API parameter binding converts request data into handler parameters.",
    "Bound data remains untrusted.",
    "DTOs help define the intended input contract.",
    "Avoid binding directly to domain models when doing so would allow over-posting or accidental modification of sensitive fields.",
    "Explicit output models matter too."
  ]
};
