window.COURSE_MODULE = {
  "title": "Endpoint Telemetry",
  "graphicAlt": "Endpoint visibility diagram showing process, file, registry, user, network, and security events flowing into investigation context.",
  "narration": "Endpoints generate valuable telemetry about activity occurring on workstations, servers, and other managed devices. Depending on the platform and tools in use, events may describe process execution, command activity, file changes, registry modifications, user sessions, services, scheduled tasks, and network connections.\n\nProcess telemetry can help analysts understand which program started, which user or parent process initiated it, what arguments were supplied, and what happened next. File and configuration events can reveal changes to important locations, persistence mechanisms, security settings, or application state.\n\nEndpoint telemetry frequently plays a central role in investigations because it connects user activity with system behavior. Analysts may use it to establish a timeline, identify related hosts, verify whether a control blocked an action, or determine whether suspicious behavior continued after an initial event.\n\nCoverage still requires care. Devices may be offline, unmanaged, misconfigured, or unable to retain detailed events. Teams should monitor sensor health, collection policy, time synchronization, parsing, and gaps so that endpoint visibility remains dependable when an incident occurs.\n\nCollection settings should be tested against performance, privacy, and operational needs. Detailed endpoint data can be valuable, but excessive collection may increase storage, processing, or review costs. Teams should protect sensitive fields, restrict access, and document why higher-detail telemetry is necessary for particular assets, threats, or response requirements.",
  "narrationPoints": [
    "Endpoints generate valuable telemetry about activity occurring on workstations, servers, and other managed devices. Depending on the platform and tools in use, events may describe process execution, command activity, file changes, registry modifications, user sessions, services, scheduled tasks, and network connections.",
    "Process telemetry can help analysts understand which program started, which user or parent process initiated it, what arguments were supplied, and what happened next. File and configuration events can reveal changes to important locations, persistence mechanisms, security settings, or application state.",
    "Endpoint telemetry frequently plays a central role in investigations because it connects user activity with system behavior. Analysts may use it to establish a timeline, identify related hosts, verify whether a control blocked an action, or determine whether suspicious behavior continued after an initial event.",
    "Coverage still requires care. Devices may be offline, unmanaged, misconfigured, or unable to retain detailed events. Teams should monitor sensor health, collection policy, time synchronization, parsing, and gaps so that endpoint visibility remains dependable when an incident occurs.",
    "Collection settings should be tested against performance, privacy, and operational needs. Detailed endpoint data can be valuable, but excessive collection may increase storage, processing, or review costs. Teams should protect sensitive fields, restrict access, and document why higher-detail telemetry is necessary for particular assets, threats, or response requirements."
  ]
};
