window.COURSE_MODULE = {
  "title": "Telemetry Quality and Coverage",
  "graphicAlt": "Telemetry quality model showing completeness, accuracy, timeliness, normalization, enrichment, retention, and coverage checks.",
  "narration": "Not all telemetry is equally useful. Effective programs evaluate completeness, accuracy, timeliness, consistency, retention, normalization, enrichment, and coverage. A source can be connected and still fail to provide the fields or history analysts need for a meaningful security question.\n\nCompleteness asks whether expected systems and event types are represented. Accuracy considers whether fields, timestamps, identities, and asset references are trustworthy. Timeliness measures whether events arrive quickly enough for detection and response, while retention determines how far back an investigation can look.\n\nNormalization helps teams compare different sources through consistent fields and concepts. Enrichment adds business, asset, identity, vulnerability, threat, or geographic context. Both can improve analysis, but teams should preserve enough original data to understand how a normalized event was produced.\n\nCoverage analysis connects collection to threats, use cases, and critical services. Teams document blind spots, monitor source health, test expected events, and review changes in architecture. Quality is an ongoing operational responsibility rather than a one-time onboarding task.\n\nSource-health measures make quality visible. Useful measures include expected-versus-reporting assets, event arrival delay, parsing failures, missing fields, sudden volume changes, retention status, and the age of unresolved collection issues. Owners can use thresholds and review routines to detect degradation before an analyst discovers it during a high-pressure investigation.",
  "narrationPoints": [
    "Not all telemetry is equally useful. Effective programs evaluate completeness, accuracy, timeliness, consistency, retention, normalization, enrichment, and coverage. A source can be connected and still fail to provide the fields or history analysts need for a meaningful security question.",
    "Completeness asks whether expected systems and event types are represented. Accuracy considers whether fields, timestamps, identities, and asset references are trustworthy. Timeliness measures whether events arrive quickly enough for detection and response, while retention determines how far back an investigation can look.",
    "Normalization helps teams compare different sources through consistent fields and concepts. Enrichment adds business, asset, identity, vulnerability, threat, or geographic context. Both can improve analysis, but teams should preserve enough original data to understand how a normalized event was produced.",
    "Coverage analysis connects collection to threats, use cases, and critical services. Teams document blind spots, monitor source health, test expected events, and review changes in architecture. Quality is an ongoing operational responsibility rather than a one-time onboarding task.",
    "Source-health measures make quality visible. Useful measures include expected-versus-reporting assets, event arrival delay, parsing failures, missing fields, sudden volume changes, retention status, and the age of unresolved collection issues. Owners can use thresholds and review routines to detect degradation before an analyst discovers it during a high-pressure investigation."
  ]
};
