window.COURSE_MODULE = {
  "title": "Telemetry and Detection",
  "graphicAlt": "Detection workflow showing telemetry collection, parsing, enrichment, analytic logic, alert context, triage, and feedback.",
  "narration": "Detection logic depends on telemetry. An analytic can only evaluate behavior that the organization can observe, and its reliability depends on stable fields, understandable semantics, appropriate retention, and predictable delivery from the underlying sources.\n\nDetection planning should therefore begin with data requirements. Engineers identify the behavior to observe, determine which sources record it, confirm the necessary fields, and test how normal and suspicious scenarios appear. This prevents rules from being designed around data that does not exist or cannot be trusted.\n\nTelemetry context also affects detection quality. Asset criticality, identity role, device state, vulnerability information, and prior activity can help a detection distinguish routine behavior from meaningful risk. Poor context may create noise or leave analysts without enough information to triage an alert.\n\nDetection and telemetry teams need a feedback loop. When fields change, sources stop reporting, or analysts identify missing context, detections should be reviewed. Likewise, detection failures can reveal collection gaps that deserve engineering attention and coverage investment.\n\nTesting should cover the data pipeline as well as the analytic rule. Teams can generate an approved test event, confirm that the source records it, verify that collection and parsing preserve the expected fields, and then check whether the detection produces useful context. This end-to-end method separates logic problems from telemetry failures and supports safer change management.",
  "narrationPoints": [
    "Detection logic depends on telemetry. An analytic can only evaluate behavior that the organization can observe, and its reliability depends on stable fields, understandable semantics, appropriate retention, and predictable delivery from the underlying sources.",
    "Detection planning should therefore begin with data requirements. Engineers identify the behavior to observe, determine which sources record it, confirm the necessary fields, and test how normal and suspicious scenarios appear. This prevents rules from being designed around data that does not exist or cannot be trusted.",
    "Telemetry context also affects detection quality. Asset criticality, identity role, device state, vulnerability information, and prior activity can help a detection distinguish routine behavior from meaningful risk. Poor context may create noise or leave analysts without enough information to triage an alert.",
    "Detection and telemetry teams need a feedback loop. When fields change, sources stop reporting, or analysts identify missing context, detections should be reviewed. Likewise, detection failures can reveal collection gaps that deserve engineering attention and coverage investment.",
    "Testing should cover the data pipeline as well as the analytic rule. Teams can generate an approved test event, confirm that the source records it, verify that collection and parsing preserve the expected fields, and then check whether the detection produces useful context. This end-to-end method separates logic problems from telemetry failures and supports safer change management."
  ]
};
