window.COURSE_MODULE = {
  "title": "What Secure FastAPI Development Means",
  "graphicAlt": "Four complementary layers—framework, application, dependencies, and operations—surround the API surface.",
  "narration": "FastAPI is a modern Python framework for building APIs and web services. It gives developers a productive path for defining path operations, request models, response models, dependencies, and documentation. That productivity is useful, but it can also make sensitive behavior available quickly. A route that takes only a few lines of code may still expose account data, approve business actions, trigger background work, or connect internal systems to outside clients.\n\nSecure FastAPI development means protecting the full API surface: routes, request models, dependencies, authentication, authorization, tokens, data access, file handling, secrets, generated documentation, package dependencies, and deployment configuration. It is not only about whether type hints exist or whether validation runs. It is about whether the application makes correct security decisions when inputs are unexpected, tokens are stale, clients are untrusted, or resources belong to another user or tenant.\n\nIt helps to separate responsibility across layers. FastAPI provides framework features. Application logic defines business rules and access decisions. Third-party packages add authentication, data access, serialization, and operational capabilities. Infrastructure provides TLS, proxying, gateways, runtime isolation, and monitoring. Operations teams handle deployment, logging, patching, and incident response. A secure service is built when these layers reinforce each other instead of assuming one layer silently solves every problem.\n\nAPI-first applications are security-sensitive because they expose business logic directly to clients, integrations, services, and automation. There may be no browser interface hiding the complexity. The API contract is the product surface. Security therefore needs to be designed into path operations, models, dependencies, service boundaries, and operational review from the start. The goal is repeatable defensive engineering, not a one-time hardening pass after the API is already in production.",
  "narrationPoints": [
    "FastAPI is a modern Python framework for building APIs and web services.",
    "Secure FastAPI development means protecting the full API surface: routes, request models, dependencies, authentication, authorization, tokens, data access, file handling, secrets, generated documentation, package dependencies, and deployment configuration.",
    "It helps to separate responsibility across layers.",
    "API-first applications are security-sensitive because they expose business logic directly to clients, integrations, services, and automation."
  ]
};
