window.COURSE_MODULE = {
  "title": "Request Validation and Data Modeling",
  "graphicAlt": "Request data passes separate shape and size, business meaning, and action permission checks before an operation.",
  "narration": "FastAPI makes request modeling convenient, but request data still deserves skepticism. Inputs may come from path parameters, query parameters, headers, cookies, JSON bodies, forms, and file uploads. They may be sent by browsers, mobile applications, command line clients, partner systems, automation, or services inside the environment. The defensive default is to treat request data as untrusted until it has been validated for the specific use case.\n\nType validation is valuable because it catches malformed data early and makes API contracts clearer. It is not enough by itself. Correctly typed data can still violate business rules, authorization rules, ownership boundaries, limits, workflow state, or tenant isolation. A valid integer may identify someone else's record. A valid string may be too broad for a search. A valid file may still exceed size, content, storage, or processing expectations.\n\nRequest models and schema validation should describe what the API accepts, including required fields, optional fields, formats, ranges, and allowed values. Unexpected fields should be handled deliberately so clients cannot influence server-controlled attributes by accident. Size limits matter because request bodies, uploaded files, and nested objects can consume memory, storage, parsing time, and downstream capacity if they are not bounded.\n\nSafe error responses are part of validation. Clients need enough information to correct bad requests, but they do not need raw stack traces, internal model details, secrets, query fragments, or service topology. Clear validation boundaries make path operations easier to review: parse the request, validate shape and business meaning, authenticate the caller, authorize the action, perform the operation, and return only the intended response.",
  "narrationPoints": [
    "FastAPI makes request modeling convenient, but request data still deserves skepticism.",
    "Type validation is valuable because it catches malformed data early and makes API contracts clearer.",
    "Request models and schema validation should describe what the API accepts, including required fields, optional fields, formats, ranges, and allowed values.",
    "Safe error responses are part of validation."
  ]
};
