window.COURSE_MODULE = {
  "title": "Least Privilege in Practice",
  "graphicAlt": "Conceptual visual of least privilege design from tasks to scoped actions, resources, conditions, separation of duties, and periodic review.",
  "narration": "Least privilege means granting only the access needed to perform a specific job. In cloud IAM, this is easy to say and harder to operate. Teams often begin with broad administrator, owner, contributor, wildcard, or full-access permissions because they make work move quickly. The risk is that those permissions can also create resources, modify policy, expose data, change networks, disable logging, or delete systems far beyond the original task.\n\nA practical least-privilege process starts with tasks. What does this person, pipeline, function, or service need to do? Which actions are required? Which resources are in scope? Does the work apply only to development, production, one account, one project, one storage bucket, one key, or one application? Can conditions limit access by tag, environment, source, approval state, or time? The more specific the task, the easier it is to design narrow permissions.\n\nSeparation of duties is part of least privilege. The same identity should not casually be able to develop code, approve deployment, change logging, modify security controls, and grant itself more access. In real environments, duties sometimes overlap, especially in small teams, but the risk should be visible. Sensitive actions such as changing trust relationships, attaching policies, creating keys, or modifying deployment automation deserve extra review and monitoring.\n\nLeast privilege is an engineering process, not a one-time setting. Permissions need to be tested, monitored, reviewed, and adjusted as applications change. Overly tight access can block work and lead to emergency grants. Overly broad access increases risk. The healthy middle is iterative: start from known tasks, scope carefully, collect access-denied feedback, approve changes deliberately, and remove permissions that are no longer needed.\n\nLeast privilege also benefits reliability. When an automation role can only change the resources it owns, accidental deployments are less likely to damage unrelated systems. When a support role can view diagnostics without editing production policy, troubleshooting becomes safer. Narrow permissions reduce both security risk and operational blast radius.\n\nAccess-denied events can be useful feedback when handled carefully. They may show that a role is too narrow for a legitimate task, or they may reveal that a person or workload is attempting something unexpected. Mature teams use those signals to refine roles rather than reflexively granting broad access. Iteration is normal; unmanaged broadening is the danger.\n\nOne practical pattern is to create task-oriented roles instead of person-oriented privilege piles. A database support role, deployment role, log reader role, or incident response role can be reviewed against a specific job. If the job changes, the role changes. If a person changes teams, membership changes. This makes access easier to reason about than broad grants attached directly to individuals.",
  "narrationPoints": [
    "Least privilege grants only needed access.",
    "Broad admin and wildcard permissions are risky.",
    "Start from tasks and map required actions.",
    "Scope access by resource and condition.",
    "Least privilege needs regular review."
  ]
};
