window.COURSE_MODULE = {
  "title": "Course Summary: A Practical Cloud IAM Checklist",
  "graphicAlt": "Conceptual visual of a practical cloud IAM checklist covering identity inventory, owners, tasks, least privilege, federation, workload identity, monitoring, and review.",
  "narration": "A practical cloud IAM workflow starts with inventory. List human users, groups, roles, service accounts, managed identities, workload identities, applications, API keys, tokens, temporary credential patterns, and emergency accounts. Assign owners and classify whether the access is human, workload, automation, administrative, production, development, or third-party. If an identity has no owner or purpose, it is already a governance problem.\n\nNext, define tasks and grant least privilege. Start from what the person or workload needs to do, map required actions to resources, scope permissions narrowly, use conditions where appropriate, and separate duties for sensitive work. Avoid broad administrator, owner, contributor, wildcard, and full-access permissions unless there is a clear, approved reason. Review effective access, not only the most visible role assignment.\n\nUse federation and MFA for human access where possible. Prefer temporary credentials, role assumption, just-in-time access, and managed identity patterns over long-lived secrets. Protect workload identities with narrow deployment roles, environment separation, secret rotation, and auditability. Treat CI/CD pipelines, containers, virtual machines, serverless functions, and service accounts as first-class IAM subjects.\n\nFinally, monitor and review continuously. Log IAM activity and cloud API usage. Watch for policy changes, key creation, trust relationship changes, role passing, impersonation, denied access, unusual API calls, and changes to logging or security controls. Review access regularly, remove stale identities, track exceptions, protect emergency accounts, and measure progress. Secure cloud IAM depends on identity lifecycle, permission design, monitoring, and governance working together.\n\nA compact review checklist helps keep the practice repeatable. Can every identity be explained? Does every privileged role have an owner? Are human users federated where possible? Are workloads using short-lived or managed identity patterns? Are long-lived keys justified and monitored? Are sensitive IAM changes logged and reviewed? Are stale grants removed quickly?\n\nThe final lesson is that cloud IAM is never finished. New projects, pipelines, vendors, identities, and services appear constantly. Secure programs build review into the operating rhythm. They make safe access easy to request, risky access visible, and stale access easy to remove. That is how IAM becomes a durable cloud security foundation instead of a growing list of exceptions.",
  "narrationPoints": [
    "Inventory identities and owners.",
    "Classify human and workload access.",
    "Grant task-based least privilege.",
    "Prefer federation and temporary credentials.",
    "Monitor and review IAM continuously."
  ]
};
