window.COURSE_MODULE = {
  "title": "Course Summary: A Go Engineer's Secrets Checklist",
  "graphicAlt": "Conceptual visual of a Go engineer reviewing a secrets management checklist across code, runtime, infrastructure, and operations.",
  "narration": "A practical secrets review for a Go service starts with inventory. Identify the values that grant access, prove identity, protect integrity, or unlock private material. Separate ordinary configuration from true secrets. Name each secret by purpose, owner, environment, permission boundary, and rotation path. If no one knows who owns a credential or how it can be replaced, the service has an operational risk, not just a documentation gap.\n\nNext, check where secrets enter the system. They should not be hardcoded in source, embedded in binaries, committed to fixtures, baked into Docker layers, or printed by CI. A Go configuration loader should use explicit required settings, prefer os.LookupEnv when it needs to distinguish unset from empty, and fail closed when production secrets are missing. Startup errors should name missing configuration keys without printing values.\n\nThen inspect how secrets move through code. Pass them only to components that need them. Avoid broad global config objects that every package can print or serialize. Redact secret-bearing structs. Do not log full DSNs, Authorization headers, raw config, provider responses, or panic output containing sensitive fields. If the service needs diagnostics, log safe identifiers and error classes instead.\n\nProvider integration deserves its own check. If the service uses a managed store, verify authentication, least privilege, context timeouts, retry limits, and audit visibility. If the platform injects secrets, verify file permissions, environment exposure, refresh behavior, and restart expectations. If the service caches secrets, document the time-to-live, refresh policy, failure behavior, and revocation implications.\n\nFinally, review rotation, testing, CI/CD, and incident response. Rotation should be possible without guesswork. Tests should use fake providers and nonworking values unless an integration environment is explicitly required. CI secrets should be scoped, protected from logs, and separated by environment. Secret scanning should help block risky commits. Incident response should include how to identify affected secrets, rotate or revoke them, redeploy safely, and confirm that logs and artifacts did not spread the exposure.\n\nSecrets management is a system behavior. Go code matters, but so do runtime identity, infrastructure policy, developer workflow, observability, and operations. A secure service is not one that merely hides a string. It is one that can load, use, rotate, audit, and recover secrets deliberately.",
  "narrationPoints": [
    "Inventory secrets and classify sensitive values.",
    "Keep secrets out of source, logs, images, and artifacts.",
    "Validate startup configuration without printing values.",
    "Use managed providers, least privilege, and context timeouts.",
    "Plan caching, rotation, testing, and incident response."
  ]
};
