window.COURSE_MODULE = {
  "title": "File Access Flows and Trust Boundaries",
  "graphicAlt": "Security diagram for Path Traversal Prevention in Node.js, File Access Flows and Trust Boundaries, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "Developers often search for one dangerous filesystem call, but better review starts with file flows. Identify every place the application reads, writes, serves, lists, deletes, renames, extracts, transforms, or generates files. Then identify where path-like values originate. They may come from route parameters, query strings, request bodies, headers, cookies, uploaded filenames, archive entries, database records, queue messages, webhook payloads, object keys, or configuration. A value stored in a database can still be untrusted if it originally came from a user or partner system.\n\nTrust boundaries matter because path-like values move between systems. A filename inside an uploaded archive is untrusted. A queue message from another service may cross a boundary. A webhook payload may contain a key that looks internal but was supplied externally. A background worker can be just as risky as an HTTP route if it trusts a file path from a queue or database. Ask who supplied the path-like value, where the operation should be allowed to go, and who is authorized to access the result.\n\nStorage boundaries should be explicit. Public assets, private files, generated exports, temporary files, logs, configuration, secrets, uploaded content, and administrative artifacts should not all share the same assumptions. Path safety and authorization must work together. A file can be inside the correct directory and still belong to another user, tenant, case, or workflow. The design should define which users and services may access which file objects before code constructs a path.",
  "narrationPoints": [
    "They may come from route parameters, query strings, request bodies, headers, cookies, uploaded filenames, archive entries, database records, queue messages, webhook payloads, object keys, or configuration.",
    "A background worker can be just as risky as an HTTP route if it trusts a file path from a queue or database.",
    "The design should define which users and services may access which file objects before code constructs a path.",
    "Public assets, private files, generated exports, temporary files, logs, configuration, secrets, uploaded content, and administrative artifacts should not all share the same assumptions.",
    "Ask who supplied the path-like value, where the operation should be allowed to go, and who is authorized to access the result.",
    "Developers often search for one dangerous filesystem call, but better review starts with file flows."
  ]
};
