window.COURSE_MODULE = {
  "title": "Enforcing Base Directory Boundaries",
  "graphicAlt": "Security diagram for Path Traversal Prevention in Node.js, Enforcing Base Directory Boundaries, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "Sometimes a dynamic file selection must still occur inside a known directory. In that case, begin with a fixed, application-controlled base directory for the file category. Public assets, private user files, temporary files, generated reports, logs, and administrative files should use separate base locations when their risk and access rules differ. The application should know which storage root applies before it interprets the requested filename or relative segment.\n\nResolve the candidate path against the base directory and confirm that the final resolved or canonicalized path remains within the intended boundary. Reject absolute paths, parent-directory movement, empty names, unexpected separators, unsupported characters, reserved names, and values that do not match the expected segment structure where appropriate. Segment-level validation is often useful when the application expects a simple filename or small relative path rather than an arbitrary tree.\n\nA base-directory boundary is not a replacement for authorization. A path can stay inside the right folder and still refer to another user's file, another tenant's export, or an administrative object the requester should not access. The safer sequence is to identify the business object, verify the caller's rights, select the intended storage boundary, resolve the candidate consistently, confirm it remains inside the boundary, and perform the file operation with narrow process permissions.",
  "narrationPoints": [
    "Public assets, private user files, temporary files, generated reports, logs, and administrative files should use separate base locations when their risk and access rules differ.",
    "Resolve the candidate path against the base directory and confirm that the final resolved or canonicalized path remains within the intended boundary.",
    "The safer sequence is to identify the business object, verify the caller's rights, select the intended storage boundary, resolve the candidate consistently, confirm it remains inside the boundary, and perform the file operation with narrow process permissions.",
    "A path can stay inside the right folder and still refer to another user's file, another tenant's export, or an administrative object the requester should not access.",
    "Sometimes a dynamic file selection must still occur inside a known directory.",
    "In that case, begin with a fixed, application-controlled base directory for the file category."
  ]
};
