window.COURSE_MODULE = {
  "title": "Express Routes, Static Files, and Downloads",
  "graphicAlt": "Security diagram for Path Traversal Prevention in Node.js, Express Routes, Static Files, and Downloads, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "Express-style applications often expose path traversal risk through download routes, preview routes, report exports, avatar serving, static middleware, and admin utilities. A private download route should not pass an untrusted path value directly into filesystem operations. It should identify the file object, verify object-level authorization, choose the storage location, and serve the file through a controlled path or storage API. Static middleware is appropriate for intentionally public assets, not private user files.\n\nKeep public static files and private files in separate storage and routing patterns. Static middleware should point only at intended public asset directories, and those directories should not contain source files, configuration, logs, generated artifacts, temporary files, or private uploads. Avoid directory listings unless they are intentionally required and reviewed. Reverse proxies and deployment configuration can also change which URL paths are reachable, so route-level assumptions should be checked against the actual production path.\n\nResponse behavior matters. Avoid reflecting untrusted filenames into headers or HTML without proper handling. Set content type and content disposition deliberately for downloads. Error responses should not reveal internal filesystem paths, stack traces, storage keys, bucket names, or sensitive metadata. A download feature should be designed as an authorization-aware file retrieval workflow, not a convenience wrapper around a user-provided path.",
  "narrationPoints": [
    "It should identify the file object, verify object-level authorization, choose the storage location, and serve the file through a controlled path or storage API.",
    "Static middleware should point only at intended public asset directories, and those directories should not contain source files, configuration, logs, generated artifacts, temporary files, or private uploads.",
    "A download feature should be designed as an authorization-aware file retrieval workflow, not a convenience wrapper around a user-provided path.",
    "Keep public static files and private files in separate storage and routing patterns.",
    "Express-style applications often expose path traversal risk through download routes, preview routes, report exports, avatar serving, static middleware, and admin utilities.",
    "Reverse proxies and deployment configuration can also change which URL paths are reachable, so route-level assumptions should be checked against the actual production path."
  ]
};
