window.COURSE_MODULE = {
  "title": "Symlinks, Race Conditions, and Platform Differences",
  "graphicAlt": "Security diagram for Path Traversal Prevention in Node.js, Symlinks, Race Conditions, and Platform Differences, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "String checks are useful, but real filesystems can surprise application code. Filesystem state may change between checking a path and using it. Symlinks and hard links can make a path appear to sit inside one location while referring elsewhere depending on how the operation is performed. Race conditions can occur when a separate check and use step relies on mutable filesystem state, especially when directories are writable by other processes or shared across workflows.\n\nPlatform differences add another layer. Windows and POSIX systems differ in separators, drive letters, reserved names, case sensitivity, and path interpretation. Container mounts, shared volumes, network filesystems, serverless temporary storage, and object storage abstractions can change what a path-like value means. Test on the platforms and deployment models the application actually uses rather than assuming local workstation behavior represents production.\n\nHigher-risk workflows may require stronger controls: canonical filesystem checks, safe open patterns, isolated workers, immutable storage records, object storage policies, or avoiding raw filesystem paths entirely. Least-privilege process permissions and storage isolation reduce damage if a boundary check fails. The safest designs reduce dependence on fragile path strings by using generated identifiers, controlled manifests, narrow writable locations, and file operations that are bound to business objects.",
  "narrationPoints": [
    "Race conditions can occur when a separate check and use step relies on mutable filesystem state, especially when directories are writable by other processes or shared across workflows.",
    "Container mounts, shared volumes, network filesystems, serverless temporary storage, and object storage abstractions can change what a path-like value means.",
    "Higher-risk workflows may require stronger controls: canonical filesystem checks, safe open patterns, isolated workers, immutable storage records, object storage policies, or avoiding raw filesystem paths entirely.",
    "Least-privilege process permissions and storage isolation reduce damage if a boundary check fails.",
    "The safest designs reduce dependence on fragile path strings by using generated identifiers, controlled manifests, narrow writable locations, and file operations that are bound to business objects.",
    "Symlinks and hard links can make a path appear to sit inside one location while referring elsewhere depending on how the operation is performed."
  ]
};
