window.COURSE_MODULE = {
  "title": "Caller Identity, Permissions, and Access Control",
  "graphicAlt": "Interprocess communication diagram for Caller Identity, Permissions, and Access Control, with separate caller and service trust zones connected by an authenticated, length-bounded message channel and explicit authorization, cleanup, and failure controls.",
  "narration": "Caller identity is central to secure IPC. A server may need to know which user, service account, session, container, or process context is connected before it can safely decide what work to perform. Where the platform provides peer credentials, endpoint permissions, access control lists, or service identity information, the IPC layer should use those signals deliberately and document their limits.\n\nAuthentication and authorization are separate decisions. Allowing a process to connect does not mean every requested operation is allowed. A status query, a read-only request, an administrative operation, and a request that touches another user’s data may all require different checks. Operation-level authorization keeps sensitive actions from inheriting authority merely because the pipe, socket, or queue accepted a connection.\n\nLeast privilege should shape the interface. Expose only the commands each caller needs, pass scoped capabilities instead of broad host access, and avoid ambient authority hidden in global state. A helper process should not receive the power to perform every operation just because one workflow needs a narrow function.\n\nBoundaries such as user, session, tenant, project, desktop, service, and privilege level should be represented in the design. Checks should happen close to the IPC boundary and again near sensitive resource use when context matters. Safe defaults should deny unknown callers, unsupported operations, and requests that cannot be tied to a permitted authority. Permission checks should be testable, not implied by comments or naming. Include cases for the right user, the wrong user, a service account, a stale client, and a caller that can connect but lacks authority for a specific operation. Good diagnostics should explain the category of denial without exposing sensitive context to the caller or logs.",
  "narrationPoints": [
    "Where the platform provides peer credentials, endpoint permissions, access control lists, or service identity information, the IPC layer should use those signals deliberately and document their limits.",
    "A server may need to know which user, service account, session, container, or process context is connected before it can safely decide what work to perform.",
    "Operation-level authorization keeps sensitive actions from inheriting authority merely because the pipe, socket, or queue accepted a connection.",
    "Expose only the commands each caller needs, pass scoped capabilities instead of broad host access, and avoid ambient authority hidden in global state.",
    "Checks should happen close to the IPC boundary and again near sensitive resource use when context matters.",
    "Safe defaults should deny unknown callers, unsupported operations, and requests that cannot be tied to a permitted authority."
  ]
};
