window.COURSE_MODULE = {
  "title": "Handles, File Descriptors, and Shared Memory",
  "graphicAlt": "Interprocess communication diagram for Handles, File Descriptors, and Shared Memory, with separate caller and service trust zones connected by an authenticated, length-bounded message channel and explicit authorization, cleanup, and failure controls.",
  "narration": "Some IPC designs transfer more than data. They pass operating-system handles, file descriptors, shared-memory objects, memory mappings, temporary file references, named resources, or other capability-bearing values. Those transfers are review-sensitive because the receiver may gain access to a file, device, process object, memory region, event, or resource that carries authority.\n\nA handle is not harmless metadata. The contract should define what the handle refers to, which permissions it carries, who owns it, who may duplicate it, who may close it, and how long it remains valid. The receiver should not assume that a transferred resource is safe merely because the sender is local. Access rights, expected type, size, and lifetime still need validation.\n\nShared memory needs especially clear rules. Both sides need agreement on mapping size, layout, synchronization, read and write permissions, initialization state, and cleanup. A size stored in shared memory should not be trusted without bounds. A writer should not be able to change data while a reader assumes it is stable unless the protocol defines synchronization.\n\nShutdown and failure are part of ownership. A peer may exit while the other side still has a mapping, descriptor, or outstanding operation. The design should prevent stale access from becoming normal behavior, release resources deterministically, and define whether the remaining process may continue using a transferred capability.\n\nThe secure habit is to document resources as carefully as messages. Who can read, who can write, who can close, what size is valid, what synchronization is required, and what happens when either side fails should all be explicit. Reviewers should also look at how resources cross privilege boundaries, how duplicate handles are tracked, and whether cleanup still happens when requests are cancelled or retried. Ownership tests should include normal completion, denial, timeout, duplicate transfer, and peer exit paths.",
  "narrationPoints": [
    "The receiver should not assume that a transferred resource is safe merely because the sender is local.",
    "A size stored in shared memory should not be trusted without bounds.",
    "The design should prevent stale access from becoming normal behavior, release resources deterministically, and define whether the remaining process may continue using a transferred capability.",
    "Who can read, who can write, who can close, what size is valid, what synchronization is required, and what happens when either side fails should all be explicit.",
    "Ownership tests should include normal completion, denial, timeout, duplicate transfer, and peer exit paths.",
    "Reviewers should also look at how resources cross privilege boundaries, how duplicate handles are tracked, and whether cleanup still happens when requests are cancelled or retried."
  ]
};
