window.COURSE_MODULE = {
  "title": "Safer Formatting and Input Conversion",
  "graphicAlt": "Bullet summary graphic for Safer Formatting and Input Conversion.",
  "narration": "Formatting APIs often look harmless because the program is constructing a string from known pieces. The risk appears when the destination is fixed-size, one input component is longer than expected, or the caller assumes that a formatted buffer is complete without checking the result. Size-aware formatting is the starting point, not the finish line.\n\nWhen formatting into a buffer, the code should pass the destination capacity and check what the API reports. If the output was truncated, the program needs a deliberate response. Sometimes truncation is acceptable for a human-readable status field. Sometimes it changes the meaning of a path, identifier, or protocol value and must be treated as a failure.\n\nFormatting return values should be checked before the resulting buffer is used. If the operation fails or reports that the output did not fit, later code should not proceed as though the full string exists. A good migration turns silent assumptions into visible error paths.\n\nInput conversion has a similar shape. scanf-style input needs field widths for string destinations, conversion count checks, and careful handling when input does not match the expected format. Without those checks, the code may accept partial data or leave previous values unchanged while appearing to parse successfully.\n\nNumeric conversion should detect invalid input, range errors, leftover characters, and overflow. A robust parser distinguishes a clean value from a value with trailing junk, a value outside the destination type, and a missing value. That distinction matters because accepting partial or ambiguous input can make downstream behavior unpredictable.\n\nSafer formatting and conversion are about contracts. What format is accepted? What size is allowed? What does truncation mean? What happens when input is malformed? The code should answer those questions explicitly so tests and reviewers can verify the behavior.",
  "narrationPoints": [
    "Formatting APIs often look harmless because the program is constructing a string from known pieces.",
    "When formatting into a buffer, the code should pass the destination capacity and check what the API reports.",
    "Formatting return values should be checked before the resulting buffer is used.",
    "Input conversion has a similar shape. scanf-style input needs field widths for string destinations, conversion count checks.",
    "Numeric conversion should detect invalid input, range errors, leftover characters, and overflow."
  ]
};
