window.COURSE_MODULE = {
  "title": "Memory Operations and Buffer Contracts",
  "graphicAlt": "Bullet summary graphic for Memory Operations and Buffer Contracts.",
  "narration": "Memory operations in C operate on bytes. That sounds straightforward, but many bugs start when code confuses byte counts, character counts, element counts, and allocated capacity. A structure array with ten elements is not ten bytes unless each element is one byte. A string length does not include terminator space unless the caller adds it deliberately.\n\nBefore calling a memory operation, the code should know the source pointer, destination pointer, number of bytes to move, and valid size of each region. If the count was computed from element size and element count, that calculation should be checked for overflow before allocation or copying occurs.\n\nOverlap assumptions matter. Some operations require source and destination regions not to overlap. When overlap is possible, the code should use the operation designed for that case. Reviewers should not rely on current data layout by accident; they should ask whether the contract forbids overlap or handles it safely.\n\nAllocation math should distinguish capacity from used length. A buffer may allocate space for many elements while only some are initialized. A helper that receives both capacity and used length can make it harder to read or write outside the meaningful range. That same helper can check whether appending or copying would exceed available space.\n\nClearing memory also deserves attention. When buffers contain sensitive values, the project should use a reliable library or platform-supported clearing mechanism where compiler optimization is relevant. For ordinary buffers, cleanup still needs to match ownership and lifetime rules so that callers do not free the same allocation twice or leak it indefinitely.\n\nA clear buffer contract defines pointer, capacity, used length, element count, ownership, and failure behavior. Small helper functions can centralize these checks so that reviewers see the same pattern repeatedly instead of revalidating fragile size arithmetic at every call site.",
  "narrationPoints": [
    "A string length does not include terminator space unless the caller adds it deliberately.",
    "Before calling a memory operation, the code should know the source pointer, destination pointer, number of bytes to move.",
    "A helper that receives both capacity and used length can make it harder to read or write outside the meaningful range.",
    "For ordinary buffers, cleanup still needs to match ownership and lifetime rules.",
    "A clear buffer contract defines pointer, capacity, used length, element count, ownership."
  ]
};
