window.COURSE_MODULE = {
  "title": "What AI Changes in Cloud Security Assessments",
  "graphicAlt": "Approved cloud evidence is organized by AI and checked by reviewers; missing context, stale evidence, and invented claims remain explicit risks.",
  "narration": "Cloud security assessments are structured reviews of the resources and controls that shape cloud risk. A practical assessment looks at identities, assets, configurations, data exposure, network paths, logging, workload posture, governance, and operational readiness. The goal is to understand how the environment is actually configured, where risk is concentrated, and what remediation would make the largest defensive difference.\n\nAI changes the workflow by helping teams organize large amounts of evidence. It can summarize cloud inventory exports, normalize inconsistent names, draft review questions, group posture findings by theme, and turn raw notes into clearer findings. It can also help create owner review packets, remediation summaries, and executive explanations. Used well, AI reduces clerical friction so reviewers can spend more time on judgment.\n\nAI-assisted assessment is not the same as automated offensive testing. It should not expand scope, probe unknown systems, infer authorization, or recommend actions against assets that have not been approved for review. In this course, AI is used as a documentation and analysis assistant for authorized cloud evidence, not as an autonomous attacker or scanner.\n\nThe most important quality rule is grounding. Findings should be tied to source material such as cloud exports, IAM data, configuration snapshots, diagrams, authorized scan summaries, logs, or owner confirmation. AI can suggest patterns, but a suggestion is not evidence. If the evidence is stale, incomplete, or ambiguous, the output should say so instead of pretending to be complete.\n\nThere are real risks. AI can hallucinate findings, preserve stale assumptions, miss business context, or expose sensitive cloud data if the workflow is careless. Professional assessments keep scope defined, data handling approved, source references preserved, human reviewers accountable, and conclusions defensible. AI should make the work faster and clearer, not less controlled.",
  "narrationPoints": [
    "Cloud security assessments are structured reviews of the resources and controls that shape cloud risk.",
    "AI changes the workflow by helping teams organize large amounts of evidence.",
    "AI-assisted assessment is not the same as automated offensive testing.",
    "The most important quality rule is grounding.",
    "There are real risks."
  ]
};
