window.COURSE_MODULE = {
  "title": "Scope, Authorization, and Assessment Boundaries",
  "graphicAlt": "A documented approved scope encloses authorized cloud assets, while related systems remain outside until approved; ownership, data handling, and exclusions define the review.",
  "narration": "Before any AI-assisted cloud assessment begins, the team must define what is authorized. Scope should identify the cloud providers, accounts, subscriptions, projects, tenants, organizations, folders, regions, environments, and services included in the review. It should also identify exclusions. A model should never be allowed to infer that a related system is in scope just because it appears in evidence.\n\nAssessment boundaries should address ownership. The environment may include internal systems, client-owned resources, vendor-managed services, shared platforms, and third-party integrations. Each category can have different access rules, evidence limits, and approval paths. The assessment should respect those boundaries even when the technical architecture crosses them.\n\nRules of engagement translate authorization into operating instructions. They should describe what data may be processed, what evidence may be shared with AI tools, which activities are allowed, which actions are prohibited, who approves changes, and how sensitive information must be handled. This is especially important for IAM exports, logs, architecture records, and vulnerability summaries that may include secrets, identifiers, or regulated data.\n\nProduction and development systems should be handled deliberately. Development environments often have weaker controls, but they may still hold sensitive data or privileged identities. Production environments may require stricter handling because mistakes can affect customers or business operations. The assessment should document environment differences rather than treating every cloud resource as equivalent.\n\nScope control protects both the organization and the assessment team. It prevents unauthorized analysis, reduces accidental disclosure, and keeps findings tied to defensible authority. AI should help within the defined boundary. It should not broaden the boundary, create assumptions about permission, or suggest actions that require approval the team does not have.",
  "narrationPoints": [
    "Before any AI-assisted cloud assessment begins, the team must define what is authorized.",
    "Assessment boundaries should address ownership.",
    "Rules of engagement translate authorization into operating instructions.",
    "Production and development systems should be handled deliberately.",
    "Scope control protects both the organization and the assessment team."
  ]
};
