window.COURSE_MODULE = {
  "title": "Identity, Access, and Permission Review",
  "graphicAlt": "An identity’s permissions are reviewed against its resources, business purpose, and workload behavior; access changes require owner review and operational validation.",
  "narration": "Identity and access review is central to cloud security assessment because cloud control is heavily permission-driven. The review should consider user identities, service accounts, workload identities, roles, policies, groups, privileged access, inactive accounts, exposed credentials, cross-account or cross-tenant trust, and emergency access patterns. The question is not only who exists, but what each identity can do.\n\nAI can summarize permission patterns across large exports. It can group identities by role, highlight broad permissions, list inactive accounts for review, compare similar policies, and draft questions for owners. It can also identify places where a service identity appears to have more access than its stated function requires. These outputs are starting points, not final judgments.\n\nLeast privilege requires context. A permission that looks broad may be necessary for a deployment service, while a smaller permission may be risky if attached to an exposed workload. Reviewers need to understand business purpose, workload behavior, automation needs, and compensating controls before recommending changes. AI should not overclaim risk from permissions without context.\n\nCredential exposure and stale access deserve special care. Long-lived keys, inactive users, unused roles, weak ownership, or unclear trust relationships can increase risk. Assessment findings should describe the evidence, the likely impact, and the validation needed. If a credential or secret appears in evidence, handling should follow approved sensitive-data procedures.\n\nHuman review is required before changing access. Removing a role, rotating a key, or disabling an identity can interrupt production systems. The assessment should produce clear remediation options, owner assignments, and validation steps. The safest outcome is not instant automated change; it is controlled improvement toward least privilege.",
  "narrationPoints": [
    "Identity and access review is central to cloud security assessment because cloud control is heavily permission-driven.",
    "AI can summarize permission patterns across large exports.",
    "Least privilege requires context.",
    "Credential exposure and stale access deserve special care.",
    "Human review is required before changing access."
  ]
};
