window.COURSE_MODULE = {
  "title": "Device Identity, Tracking, and Terminology Boundaries",
  "narration": "Device tracking begins with a simple operational fact: modern operating systems need persistent identifiers. Without them, Windows could not keep track of activation, update eligibility, app licensing, diagnostic events, device health, or account-connected experiences. The privacy question is not whether identifiers exist. The question is what they identify, how persistent they are, who can see them, what controls apply, and whether users and organizations understand the tradeoff.\n\nThe term GDID, or Global Device Identifier, should be handled carefully. It is not the same thing as a Windows device instance ID, hardware ID, compatible ID, container ID, device setup class GUID, or device interface GUID. Those identifiers support Plug and Play, driver matching, physical device grouping, and software discovery. Public reporting and court records discuss GDID differently. In that context, it is described as a Microsoft service-side device or installation identifier used across certain Microsoft services and scenarios.\n\nGDID is also different from the Windows Advertising ID. Advertising ID is a user-and-device scoped identifier exposed to apps for advertising and personalization, with a visible Windows privacy setting. Microsoft documentation says disabling that setting prevents apps from retrieving the advertising ID. That does not mean every other service identity disappears, and it does not describe the same mechanism as the GDID discussed in the public case.\n\nThis course uses the public GDID story as a case study in device tracking, telemetry, account linkage, and governance. It is not a guide to hiding activity, defeating accountability, or disrupting Windows services. The practical goal is lawful data minimization, better user notice, better enterprise policy, and clearer forensic interpretation.\n\nA successful learner can separate identifier families without collapsing them into one scary word. They can say which facts are documented by Microsoft, which claims come from a criminal complaint, which details come from secondary reporting, and which implementation details remain uncertain. That boundary discipline is what makes privacy analysis useful instead of noisy.",
  "narrationPoints": [
    "Persistent identifiers support Windows services, but each identifier has a different purpose.",
    "GDID is distinct from Plug and Play identifiers and the Windows Advertising ID.",
    "The course separates documented facts, court-record claims, reporting, and uncertainty.",
    "Privacy guidance focuses on lawful minimization and governance, not evasion.",
    "Good analysis starts by asking what an identifier identifies and who can use it."
  ]
};
