window.COURSE_MODULE = {
  "title": "What the Public GDID Story Revealed",
  "narration": "The public conversation around GDID accelerated after a July 2026 Windows Latest report. The report focused on a federal complaint involving Peter Stokes, an alleged member of the Scattered Spider hacking group. The DOJ press release says the complaint alleges a luxury jewelry retailer was breached in May 2025, data was exfiltrated, and an approximately eight million dollar ransom demand was made. Stokes should be described as accused or alleged unless a later court outcome changes that status.\n\nThe complaint is important because it describes a Global Device Identifier in unusually direct language. It says a Microsoft representative described the identifier as persistent and device-level. It also says the identifier is designed to uniquely identify a Windows installation. That installation may be on a physical device or a virtual machine, across certain Microsoft services and scenarios. The complaint further says the identifier remains consistent across Windows operating system updates, while a reinstall is tied to a new unique GDID.\n\nInvestigators allegedly used the GDID as one piece of correlation evidence. The complaint states that Microsoft records connected the GDID to an ngrok signup page at a time matching ngrok records, then connected the same GDID to other activity through proxy infrastructure. Investigators then compared IP address activity associated with the device to account activity they attributed to Stokes.\n\nThe lesson is not that one identifier alone proves identity. The lesson is that a persistent service-side device identifier can be powerful when combined with timestamps, IP addresses, account records, provider subpoenas, travel records, and other evidence. In an investigation, correlation becomes stronger when independent records point to the same timeline.\n\nFor privacy and governance teams, the story revealed a transparency gap. Many Windows users had never heard the term GDID, and Microsoft public documentation is sparse. The right response is not panic. It is to understand persistence, scope, legal-process exposure, user visibility, and controls so that organizations can explain their Windows telemetry posture honestly.",
  "narrationPoints": [
    "The public GDID story came from reporting around a DOJ complaint.",
    "The complaint describes GDID as persistent across updates but changed by reinstall.",
    "Investigators allegedly used GDID as correlation evidence, not as a standalone proof.",
    "Persistent identifiers become powerful when combined with account, IP, and timeline data.",
    "The case highlights a transparency and governance gap for Windows telemetry identity."
  ]
};
