window.COURSE_MODULE = {
  "title": "Account Linkage, Installation Identity, Reinstall Boundaries, and Misconceptions",
  "narration": "A common misconception is that device tracking is a single switch. In practice, Windows identity signals come from overlapping layers: the Windows installation, Microsoft Account sign-in, work or school account enrollment, activation, Microsoft Store licensing, Delivery Optimization, browser sync, search integration, cloud content features, crash reporting, and app permissions. Turning one setting off can reduce one category of collection without removing every other relationship.\n\nAnother misconception is that reinstalling Windows is a complete privacy reset. The complaint says a reinstall is tied to a new unique GDID, but that does not mean all linkage risk disappears. If the same person signs into the same Microsoft account, restores the same apps, uses the same browser profile, joins the same tenant, activates the same license path, or resumes the same cloud services, many other records can still connect the new installation to earlier activity.\n\nLocal accounts can reduce some account-linked signals, but they also change the experience. Store licensing, OneDrive, Windows backup, account recovery, cross-device clipboard, cloud search, and some managed services may work differently or require separate sign-in. The privacy question should be framed as a tradeoff between service integration and identity minimization.\n\nIt is also important not to confuse visibility with absence. A user may be able to see and control Advertising ID, activity history, cloud content search, or optional diagnostic data. That visibility does not prove undocumented service identifiers do not exist. At the same time, the existence of service identifiers does not prove every action is captured or exposed to every Microsoft service.\n\nThe best mental model is layered linkage. Ask what service generated the identifier, whether it is installation-scoped or account-scoped, whether it survives updates, what resets it, what policy controls exist, and what records could connect it to other identifiers. That model is more reliable than looking for one magic privacy button.",
  "narrationPoints": [
    "Windows tracking signals come from overlapping service and account layers.",
    "A reinstall may change an installation identifier without breaking all account linkage.",
    "Local accounts reduce some signals but change service integration.",
    "Visible privacy controls do not necessarily describe every service identifier.",
    "Layered linkage is a better model than a single on/off switch."
  ]
};
