window.COURSE_MODULE = {
  "title": "Enterprise Governance, Compliance, and Monitoring",
  "narration": "Enterprises should treat Windows telemetry identity as a governance topic, not just a workstation setting. The organization needs to know which diagnostic level is configured, which endpoints are allowed, which services depend on telemetry, which reporting products consume the data, and who is accountable for explaining that posture to users, auditors, legal counsel, and security teams.\n\nMicrosoft documentation describes policy paths for managing diagnostic data through Group Policy and MDM, including AllowTelemetry, dump collection limits, and diagnostic log collection limits. It also describes Windows diagnostic data processor configuration for eligible Microsoft Entra joined devices, where Microsoft may act as processor and the organization as controller under defined conditions. That governance distinction matters for data subject requests, retention, and compliance evidence.\n\nA privacy baseline should document purpose. If Delivery Optimization reporting is enabled, say why. If optional diagnostic data is allowed for a pilot group, define the scope and review date. If Feedback Hub or app telemetry is permitted, explain how feedback data differs from Windows diagnostic processor controls. Vague collection is hard to defend; bounded collection is easier to explain.\n\nSecurity teams also need to understand lawful disclosure risk. A persistent device identifier may become meaningful during an investigation when combined with provider records, account logs, IP history, and timestamps. That can support incident response and abuse investigations, but it also raises user trust and transparency questions. Organizations should not promise anonymity where managed devices generate service records.\n\nEffective governance is visible in artifacts: policy settings, management baselines, data-flow notes, retention schedules, user notices, exception registers, and periodic reviews. The objective is not to remove every Microsoft connection from Windows. It is to make identity and telemetry choices deliberate, documented, minimized, monitored, and proportionate to the organization’s risk and operational needs.",
  "narrationPoints": [
    "Windows telemetry identity belongs in enterprise governance.",
    "Group Policy and MDM can manage diagnostic settings and related limits.",
    "Processor configuration changes compliance responsibilities for eligible devices.",
    "Persistent identifiers can matter in investigations and legal-process exposure.",
    "Good governance produces documented, minimized, proportionate telemetry decisions."
  ]
};
