window.COURSE_MODULE = {
  "title": "Containers, Reallocation, and Iterator Invalidation",
  "graphicAlt": "Vector reallocation timeline showing storage moving, an old iterator becoming invalid, and a stable key reacquiring the record.",
  "narration": "Dangling access is not limited to manual allocation and manual deletion. Containers can invalidate pointers, references, and iterators when they grow, shrink, erase elements, clear contents, or otherwise rearrange storage. A pointer to an element may become invalid even while the container itself remains alive.\n\nstd::vector reallocation is a common example. When a vector needs more capacity, it may move elements into new storage. Pointers, references, and iterators that pointed into the old storage no longer refer to the current elements. Code that stores those observers across a mutation must be reviewed carefully.\n\nErase and clear operations also matter because they end element lifetimes. An iterator or reference to an erased element should not be used later. Mutation while iterating deserves a deliberate pattern that updates iterators according to the container's rules and avoids keeping stale observers.\n\nDifferent containers have different invalidation rules. Some provide more stable node addresses for certain operations, while others prioritize contiguous storage or compact layout. The choice of container should reflect both performance needs and lifetime requirements for observers.\n\nWhen long-lived observers are required, stable ownership may be a better design. That could mean owning objects separately and storing identifiers, handles, or smart pointers according to the lifecycle policy. The important point is to separate stable identity from temporary container layout when observers outlive ordinary mutations.\n\nTests should cover mutation during observation. Push, reserve, erase, clear, resize, sort, and replacement operations can all reveal whether stored access paths are still valid. Reviewers should pay special attention to code that caches element addresses or iterators and later mutates the container.",
  "narrationPoints": [
    "Dangling access is not limited to manual allocation and manual deletion.",
    "When a vector needs more capacity, it may move elements into new storage.",
    "Erase and clear operations also matter because they end element lifetimes.",
    "Some provide more stable node addresses for certain operations, while others prioritize contiguous storage or compact layout.",
    "That could mean owning objects separately and storing identifiers, handles, or smart pointers according to the lifecycle policy.",
    "Reviewers should pay special attention to code that caches element addresses or iterators and later mutates the container."
  ]
};
