window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Idempotency, Retries, and Failure Safety' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Derive a canonical idempotency key",
      "language": "csharp",
      "blurb": "The factory validates queue, tenant, message, and operation identifiers, length-prefixes every component, hashes the exact UTF-8 bytes with SHA-256, and returns a canonical lowercase key without ambiguous delimiter concatenation.",
      "code": "using System.Buffers.Binary;\nusing System.Security.Cryptography;\nusing System.Text;\n\npublic static class BackgroundIdempotencyKey\n{\n    public static string Create(\n        string queue,\n        string tenantId,\n        string messageId,\n        string operation)\n    {\n        if (!IsIdentifier(queue) || !IsIdentifier(tenantId) ||\n            !IsIdentifier(messageId) || !IsOperation(operation))\n        {\n            throw new ArgumentException(\"Idempotency key input rejected.\");\n        }\n        var values = new[] { queue, tenantId, messageId, operation };\n        var encoded = values.Select(Encoding.UTF8.GetBytes).ToArray();\n        var total = encoded.Sum(value => checked(4 + value.Length));\n        var input = new byte[total];\n        var offset = 0;\n        foreach (var value in encoded)\n        {\n            BinaryPrimitives.WriteInt32BigEndian(input.AsSpan(offset, 4), value.Length);\n            offset += 4;\n            value.CopyTo(input, offset);\n            offset += value.Length;\n        }\n        try\n        {\n            return Convert.ToHexStringLower(SHA256.HashData(input));\n        }\n        finally\n        {\n            CryptographicOperations.ZeroMemory(input);\n        }\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n\n    private static bool IsOperation(string value) =>\n        value is \"invoice.generate\" or \"order.export\" or \"document.scan\";\n}\n"
    },
    {
      "title": "Calculate bounded retry attempts without overflow",
      "language": "csharp",
      "blurb": "The retry policy validates maximum attempts and base delay, rejects attempts outside the policy, doubles delay with subtraction-before-multiplication checks, and caps every result at a short application-owned maximum.",
      "code": "public sealed class BackgroundRetryPolicy\n{\n    private readonly int _maximumAttempts;\n    private readonly TimeSpan _baseDelay;\n\n    private BackgroundRetryPolicy(int maximumAttempts, TimeSpan baseDelay)\n    {\n        _maximumAttempts = maximumAttempts;\n        _baseDelay = baseDelay;\n    }\n\n    public static BackgroundRetryPolicy Create(int maximumAttempts, TimeSpan baseDelay)\n    {\n        if (maximumAttempts is < 1 or > 10 || baseDelay < TimeSpan.FromMilliseconds(100) ||\n            baseDelay > TimeSpan.FromSeconds(10))\n        {\n            throw new ArgumentException(\"Retry policy rejected.\");\n        }\n        return new BackgroundRetryPolicy(maximumAttempts, baseDelay);\n    }\n\n    public TimeSpan DelayForAttempt(int attempt)\n    {\n        if (attempt is < 1 || attempt > _maximumAttempts)\n            throw new ArgumentOutOfRangeException(nameof(attempt));\n        const long maximumTicks = TimeSpan.TicksPerMinute;\n        var ticks = _baseDelay.Ticks;\n        for (var index = 1; index < attempt; index++)\n        {\n            if (ticks > maximumTicks / 2) return TimeSpan.FromTicks(maximumTicks);\n            ticks *= 2;\n        }\n        return TimeSpan.FromTicks(Math.Min(ticks, maximumTicks));\n    }\n}\n"
    }
  ]
};
