window.COURSE_MODULE = {
  "title": "Queues, Messages, and Trust Boundaries",
  "graphicAlt": "Bullet summary graphic for Queues, Messages, and Trust Boundaries.",
  "narration": "Queue messages, event data, job parameters, scheduled job metadata, imported files, and database-driven work items are inputs to background services. They may arrive from internal code, partner systems, administrative tools, scheduled processes, or older versions of the application. The worker should not treat them as safe merely because they arrived through a familiar queue or table.\n\nAn ExampleQueueMessage should have a documented schema. Required fields, optional fields, version information, identifiers, tenant context, expected producer, and allowed operation names should be clear. When a worker receives the message, it should validate the size, structure, required values, version, and business meaning before processing. Parsing is not the same as acceptance.\n\nInternal queues can carry stale, duplicate, incorrect, or incomplete work. Messages may be delayed during an outage, replayed after a retry, delivered out of order, produced by old code, or left behind after a partial deployment. A worker should be prepared for messages that no longer match current state or that refer to records that have changed since the job was created.\n\nMessage ownership and tenant context need verification. A message containing ExampleTenantId is not enough by itself. The worker should confirm that the referenced record, file, report, or job belongs to the expected tenant and that the operation is still allowed. Background services often run under service identities, so they must preserve the business authorization context instead of assuming service access equals permission.\n\nReplay, duplicate delivery, out-of-order messages, stale messages, and expired work should be handled defensively. A message may need a unique ExampleJobId, created timestamp, expiration policy, state check, version check, and idempotency key. The exact design depends on the queue and business process, but the worker should not rely on perfect delivery.\n\nKeep parsing, validation, authorization, and processing responsibilities clear. That separation gives reviewers a place to ask: did we understand the message, did it match the contract, is it still allowed, and what did we do with it. Blending those steps into one block of code makes background work harder to test and harder to trust.",
  "narrationPoints": [
    "The worker should not treat them as safe merely because they arrived through a familiar queue or table.",
    "When a worker receives the message, it should validate the size, structure, required values, version, and business meaning before processing.",
    "Messages may be delayed during an outage, replayed after a retry, delivered out of order, produced by old code, or left behind after a partial deployment.",
    "A message may need a unique ExampleJobId, created timestamp, expiration policy, state check, version check, and idempotency key.",
    "Keep parsing, validation, authorization, and processing responsibilities clear."
  ]
};
