window.COURSE_MODULE = {
  "title": "What SOC 2 Is Really For",
  "graphicAlt": "Conceptual visual of SOC 2 as scoped customer assurance based on controls and evidence.",
  "narration": "SOC 2 is best understood as an assurance report, not a badge that proves perfect security. It is an attestation report used by service organizations to help customers understand how controls are designed and, depending on report type, how those controls operate. The report is scoped to a defined system, service, set of commitments, and set of controls. It does not automatically cover every product, employee, tool, environment, or business process in the company.\n\nCustomers often ask for SOC 2 because they need evidence before trusting a vendor with important data or business operations. A report can reduce questionnaire friction, support vendor risk review, and give customers a structured view of how the service organization manages security, availability, confidentiality, processing integrity, or privacy commitments. It is not a replacement for every customer due diligence process, but it can make that process more consistent and evidence based.\n\nSOC 2 is built around controls. A control might describe how access is approved, how changes are reviewed, how incidents are handled, how backups are tested, how vendors are reviewed, or how monitoring is performed. The report is concerned with whether those controls are suitably designed and, for Type II, whether they operated effectively over the review period. That means evidence matters. Policies without operation are weak. Operation without evidence is difficult to support.\n\nIt is important to avoid overclaiming. SOC 2 does not mean the organization cannot have incidents. It does not guarantee that every system is secure. It does not mean every control is perfect. It provides auditor-assessed assurance about scoped controls against defined criteria and commitments. Exact requirements depend on the organization, scope, auditor, systems, controls, and reporting period.\n\nFor technical teams, SOC 2 is practical because many controls live inside everyday work. Access reviews, change tickets, vulnerability remediation, incident records, vendor reviews, monitoring alerts, backup tests, and policy acknowledgments are not abstract compliance artifacts. They are records that show whether the organization operates the way it says it operates.\n\nThe useful mindset is this: SOC 2 is not audit theater. It is a structured way to describe a service, define relevant trust criteria, operate controls, gather honest evidence, track exceptions, remediate gaps, and communicate assurance to customers. When approached that way, SOC 2 can support both customer trust and internal operational discipline.",
  "narrationPoints": [
    "SOC 2 is an attestation report, not a certification.",
    "It helps customers evaluate trust and risk.",
    "The report applies to a defined system and scope.",
    "SOC 2 focuses on controls and evidence.",
    "It does not prove perfect security."
  ]
};
