window.COURSE_MODULE = {
  "title": "Trust Services Categories and Scope",
  "graphicAlt": "Conceptual visual of Trust Services Categories connected to system scope, customer commitments, and controls.",
  "narration": "SOC 2 reports are organized around Trust Services Criteria. The Security category is commonly included because nearly every SOC 2 report needs to address protection against unauthorized access, unauthorized disclosure, and damage to systems that support the service. Other categories may be included depending on the service and the commitments made to customers. Availability, Confidentiality, Processing Integrity, and Privacy are not automatic. They should be included when they match the service, contractual promises, risk profile, and customer expectations.\n\nScope is where SOC 2 becomes concrete. The scope defines which service or system is included, which environments are relevant, which people and teams operate the controls, which processes support the service, and which controls map to the selected criteria. A cloud platform, a customer-facing SaaS application, an internal support process, and a data processing workflow can all have different scope boundaries.\n\nGood scope connects the service being sold to the promises made to customers. If customers rely on uptime commitments, availability may matter. If the service stores confidential customer information, confidentiality may matter. If the service processes transactions where completeness and accuracy are central, processing integrity may matter. If the service collects personal information under privacy commitments, privacy may matter. The scope should explain these relationships without pretending the report covers more than it does.\n\nWeak scope creates confusion. If the report includes a control but not the system customers care about, the report may not answer the real risk question. If the report describes a service broadly but evidence covers only a small environment, the team may struggle during audit and customer review. If commitments are vague, teams may collect evidence that does not connect to the criteria. Scope is not just paperwork; it drives evidence, ownership, and report usefulness.\n\nTechnical and operational teams should understand scope because their work may become evidence. Access to production, change management for customer-facing systems, incident response for the service, vendor dependencies, backup processes, monitoring, and onboarding or offboarding may all be in scope. Teams need to know which systems and processes matter so they can operate controls consistently.\n\nThe practical lesson is to define scope early and keep it aligned with reality. Document the service, boundaries, dependencies, selected Trust Services Categories, customer commitments, and control owners. When the scope is clear, Type I readiness and Type II evidence collection become much easier to manage.",
  "narrationPoints": [
    "Trust Services Categories shape SOC 2 scope.",
    "Security is common; other categories depend on commitments.",
    "Scope defines systems, processes, people, and controls.",
    "Good scope connects services to customer promises.",
    "Weak scope leads to audit and customer confusion."
  ]
};
