window.COURSE_MODULE = {
  "title": "XSS Is a Context and Interpretation Problem",
  "graphicAlt": "Infographic showing untrusted data from requests, databases, and browser state reaching two browser operations. textContent displays the literal markup characters as text, while innerHTML parses the same value into formatting. Reflected, stored, and DOM-based XSS all require source-to-transformation-to-sink analysis. TypeScript types do not provide runtime content safety.",
  "narration": "Web applications move data through several interpreters. An HTTP value may enter a server template, become HTML source, produce DOM nodes, flow into a URL property, or reach JavaScript or CSS processing. Cross-site scripting occurs when untrusted data crosses one of those boundaries in a representation the browser can interpret as active content instead of inert application data. The correct defense therefore depends on what will interpret the value next.\n\nReflected XSS returns request data in a response, stored XSS persists data that is rendered later, and DOM-based XSS is created by client-side data flow and browser APIs. These labels describe where to investigate, but they do not change the engineering method. A value can be safely emitted by an API and become unsafe when frontend code inserts it into an HTML-parsing sink. Server-rendered and client-rendered paths both need source-to-destination analysis.\n\nThe assignment container.innerHTML equals userMessage is deliberately unsafe because it asks an HTML parser to create structure from untrusted text. Assigning the same value to textContent states the intended semantics directly: the value becomes a text node, not HTML source. That is stronger than trying to identify suspicious substrings. The browser never receives an instruction to reinterpret the message as markup. TypeScript types do not alter this runtime behavior; a string assertion cannot make content trusted.\n\nUse a repeatable model. Identify the trust of the data and the exact output context. Prefer an API that keeps data separate from source code. When source generation is unavoidable, encode for that specific parser and location. Sanitize only when the product intentionally permits markup, then preserve the sanitizer's result without unsafe mutation. Add browser controls as independent layers. XSS prevention is not a single escape function applied everywhere. It is a set of explicit decisions at every interpretation boundary.",
  "narrationPoints": [
    "Trace untrusted data through each browser interpretation boundary.",
    "Reflected, stored, and DOM-based paths use the same source-to-sink method.",
    "Use textContent when the intended result is text rather than markup.",
    "Choose defenses according to the parser and context that comes next."
  ]
};
