window.COURSE_MODULE = {
  "title": "Treat URLs and Attributes as Their Own Security Contexts",
  "graphicAlt": "Infographic separating syntax safety from behavior policy. A candidate URL is parsed with a trusted base when needed, passes protocol and destination checks, and is assigned only if allowed; rejected candidates stop. Lower panels show fixed text-attribute names, event listeners instead of inline handler strings, and allowlisted style properties and values.",
  "narration": "Attributes combine syntax with behavior. Text-like attributes such as title, aria-label, and controlled data attributes can receive values through fixed DOM properties or safe attribute serialization. Even there, keep the attribute name under application control. An API that safely serializes a value does not make a user-selected event attribute or other active attribute acceptable.\n\nURL-bearing properties such as href, src, form actions, and resource locations add semantic policy. Parse a candidate with a standards-aware URL API, account deliberately for relative URLs by supplying a trusted base when they are allowed, and permit only the protocols and origins the feature needs. A URL can be syntactically valid and safely assigned to a property while still navigating or loading from a forbidden location. Percent encoding protects component boundaries; it does not decide whether a protocol or destination is authorized.\n\nInline event-handler attributes are JavaScript source contexts. Do not build onclick or similar strings from external data. Register a developer-authored function with addEventListener and let request data remain data passed to that function. This approach separates behavior from markup and avoids a nested language boundary where HTML parsing hands a string to the JavaScript engine. String-to-code functions deserve the same scrutiny.\n\nStyle attributes and style text create CSS interpretation. Prefer assigning a known property with a value selected from an allowlist, such as a small set of theme tokens, rather than accepting arbitrary CSS. Review the property itself because some values can cause resource loads or other behavior. The durable distinction is that output encoding protects a syntax boundary, while URL, event, and style policy governs what the resulting browser feature is permitted to do. Both may be necessary, and neither can substitute for the other.",
  "narrationPoints": [
    "Keep attribute names fixed and treat each property's behavior explicitly.",
    "URL serialization and URL protocol or origin policy solve different problems.",
    "Use addEventListener instead of constructing inline handler source.",
    "Prefer allowlisted style properties and values over arbitrary CSS text."
  ]
};
