window.COURSE_MODULE = {
  "title": "Sanitize Rich HTML Only When HTML Is Actually Required",
  "graphicAlt": "Infographic showing intentional rich HTML passing through a maintained parser-based sanitizer with an element, attribute, and URL policy before a reviewed HTML sink. Active content is removed and benign formatting retained. Unsafe post-sanitization appending or decoding is blocked. Ordinary text follows a separate textContent path, while regex tag stripping and type assertions are not sanitizer substitutes.",
  "narration": "Some products intentionally accept markup for formatted comments, rich-text documents, article bodies, or controlled publishing. Rendering that input with textContent would correctly make it inert but would also remove the required formatting. This is the case for sanitization: parse the markup and remove or rewrite constructs that fall outside a defined security policy. Sanitization and encoding are not synonyms.\n\nUse a mature, actively maintained HTML sanitizer suitable for the browser or server environment. Regular expressions and home-grown tag removal do not model the HTML parser, nested content, namespaces, attributes, or URL behavior reliably. Configure the allowed elements and attributes, URL-bearing attributes and protocols, embedded content, and style handling according to the product requirement. A policy that permits more markup creates a larger surface and deserves stronger review.\n\nTreat the sanitizer result according to its documented contract. Do not append an untrusted HTML string after sanitization, decode it into a different representation, or pass it through transformations that can recreate active markup. Keep the sanitization boundary close to the HTML-parsing sink, and make bypasses difficult to call accidentally. TypeScript branding can document that only the wrapper should create a rich-HTML value, but the runtime sanitizer and call-path controls provide the actual security. A type assertion alone performs no transformation.\n\nServer-side sanitization can protect stored content and downstream web consumers, while client-side sanitization can enforce policy at the rendering boundary. Architecture may use both, especially when old stored values or multiple ingestion paths exist. Other consumers, such as email or document renderers, may require their own policy. Maintain the sanitizer and regression tests as browser behavior evolves. Do not add sanitization to ordinary text paths: text APIs are simpler, preserve the intended semantics, and avoid interpreting markup at all.",
  "narrationPoints": [
    "Use sanitization only when the product intentionally accepts HTML markup.",
    "Rely on a mature parser-based sanitizer with an explicit allow policy.",
    "Do not concatenate or decode untrusted markup after sanitization.",
    "Type brands document the boundary; runtime sanitization enforces it."
  ]
};
