window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Output Handling, Logging, Testing, and Monitoring with reviewable Python controls.",
  "codeExamples": [
    {
      "title": "Bound child output and execution with one deadline",
      "language": "python",
      "blurb": "Nonblocking selector reads and process waiting share one monotonic deadline; cleanup signals the POSIX process group, waits with a bounded timeout, closes stdout, and preserves cleanup failures.",
      "code": "import os\nimport selectors\nimport signal\nimport subprocess\nfrom time import monotonic\n\ndef bounded_stdout(\n    command: list[str],\n    maximum: int = 1_000_000,\n    wall_clock_seconds: float = 2.0,\n) -> bytes:\n    if os.name != \"posix\":\n        raise NotImplementedError(\"this process-group example requires POSIX\")\n    if maximum < 0 or wall_clock_seconds <= 0:\n        raise ValueError(\"positive process limits required\")\n    process = subprocess.Popen(\n        command,\n        stdout=subprocess.PIPE,\n        stderr=subprocess.DEVNULL,\n        start_new_session=True,\n    )\n    selector = None\n    cleanup_error = None\n    try:\n        if process.stdout is None:\n            raise RuntimeError(\"child stdout pipe was not opened\")\n        descriptor = process.stdout.fileno()\n        os.set_blocking(descriptor, False)\n        selector = selectors.DefaultSelector()\n        selector.register(descriptor, selectors.EVENT_READ)\n        deadline = monotonic() + wall_clock_seconds\n        output = bytearray()\n        while selector.get_map():\n            remaining = deadline - monotonic()\n            if remaining <= 0:\n                raise TimeoutError(\"child process exceeded its deadline\")\n            for key, _ in selector.select(timeout=min(remaining, 0.1)):\n                try:\n                    chunk = os.read(key.fd, 64 * 1024)\n                except BlockingIOError:\n                    continue\n                if not chunk:\n                    selector.unregister(key.fd)\n                    continue\n                if len(output) + len(chunk) > maximum:\n                    raise ValueError(\"child output exceeded its limit\")\n                output.extend(chunk)\n        remaining = deadline - monotonic()\n        if remaining <= 0:\n            raise TimeoutError(\"child process exceeded its deadline\")\n        if process.wait(timeout=remaining) != 0:\n            raise RuntimeError(\"child process failed\")\n        return bytes(output)\n    finally:\n        if selector is not None:\n            selector.close()\n        if process.poll() is None:\n            try:\n                os.killpg(process.pid, signal.SIGKILL)\n            except ProcessLookupError:\n                pass\n            except OSError as error:\n                cleanup_error = error\n        try:\n            process.wait(timeout=2)\n        except subprocess.TimeoutExpired as error:\n            if cleanup_error is None:\n                cleanup_error = error\n        finally:\n            if process.stdout is not None:\n                process.stdout.close()\n        if cleanup_error is not None:\n            raise cleanup_error\n"
    },
    {
      "title": "Test a complete fixed process invocation",
      "language": "python",
      "blurb": "The listing includes the process wrapper, then verifies its executable, argument boundaries, timeout, shell policy, and output settings without launching a real program.",
      "code": "import subprocess\nfrom unittest.mock import Mock\n\ndef image_dimensions(path: str) -> subprocess.CompletedProcess[str]:\n    return subprocess.run(\n        [\"/usr/bin/identify\", \"-format\", \"%w %h\", \"--\", path],\n        shell=False,\n        text=True,\n        capture_output=True,\n        timeout=5,\n        check=True,\n    )\n\ndef test_image_dimensions_uses_safe_arguments(monkeypatch):\n    runner = Mock()\n    monkeypatch.setattr(\"subprocess.run\", runner)\n    image_dimensions(\"-debug.png\")\n    arguments, keywords = runner.call_args\n    assert arguments[0] == [\"/usr/bin/identify\", \"-format\", \"%w %h\", \"--\", \"-debug.png\"]\n    assert keywords[\"shell\"] is False\n    assert keywords[\"timeout\"] == 5\n    assert keywords[\"capture_output\"] is True\n"
    }
  ]
};
