window.COURSE_MODULE = {
  "title": "File Paths, Working Directories, and Temporary Files",
  "graphicAlt": "Decision diagram for File Paths, Working Directories, and Temporary Files, showing validated operation, fixed executable, argument vector, minimal environment, bounded child process, and captured result; labeled arrows identify process launch and termination controls and the point where unsafe input or behavior is rejected.",
  "narration": "File handling and process execution are closely connected because many child processes read input files, write output files, inspect directories, or create temporary artifacts. A safe design builds paths from trusted base directories, uses path-aware APIs, validates identifiers, and checks that resolved file access remains inside approved locations. User-facing display names should be separated from storage names so a friendly label does not become an instruction to the filesystem.\n\nWorking directory control matters because relative paths are interpreted relative to a current location. If the working directory is inherited accidentally or controlled indirectly, the same argument may point at different files in different deployments. A secure design sets the working directory intentionally or avoids relying on it. The process should only see the files and directories needed for the approved operation, not broad application or host locations.\n\nTemporary files deserve care because they often hold uploads, transformed data, reports, exports, or intermediate processing results. Predictable temporary names, shared directories, weak permissions, incomplete cleanup, and reuse across concurrent jobs can create exposure or confusion. Safer patterns use platform helpers that create unpredictable names with appropriate permissions, keep temporary files in approved locations, and clean up during both success and failure paths.\n\nPermissions on input and output files should match the risk of the workflow. A child process should not need access to source code, production configuration, private keys, unrelated customer data, or broad system directories to perform a narrow task. File access should be explicit enough that code review can identify what the process can read and write. This is one reason process execution should be treated as an architecture decision, not just a utility call.",
  "narrationPoints": [
    "File handling and process execution are closely connected because many child processes read input files, write output files, inspect directories, or create temporary artifacts.",
    "User-facing display names should be separated from storage names so a friendly label does not become an instruction to the filesystem.",
    "If the working directory is inherited accidentally or controlled indirectly, the same argument may point at different files in different deployments.",
    "The process should only see the files and directories needed for the approved operation, not broad application or host locations.",
    "Predictable temporary names, shared directories, weak permissions, incomplete cleanup, and reuse across concurrent jobs can create exposure or confusion.",
    "File access should be explicit enough that code review can identify what the process can read and write."
  ]
};
