window.COURSE_MODULE = {
  "title": "Temporary File Trust Boundaries and Risk Model",
  "graphicAlt": "Shared temporary directory, private application directory, generated object, worker process, backup system, and final destination are separated by ownership, naming, permission, and lifecycle boundaries.",
  "narration": "Temporary file workflows cross trust boundaries just like permanent storage. Trusted application code may create a staging directory. User input may influence file names, upload metadata, archive entries, report parameters, or processing options. A background job may read a file created by a web request. A subprocess may consume an input file and produce an output file. Each transition matters because the application is moving data between subjects, processes, directories, and lifecycle states.\n\nA useful risk model asks who can create, read, modify, delete, or influence each temporary artifact. On a developer machine, the answer may be simple. On a shared host, container node, CI runner, job queue, or multi-tenant platform, the answer can be more complicated. Operating system permissions, runtime identity, mounted volumes, container boundaries, serverless temporary storage, and cleanup behavior all affect who can interact with the file.\n\nTemporary workflows should preserve the same trust boundaries as permanent storage. If a user is not authorized to read a document after it is stored permanently, they should not be able to read it while it is staged temporarily. If one tenant cannot access another tenant?s report in the final system, the temporary processing area should not mix those reports under weak assumptions. Temporary storage should not become a bypass around application authorization or tenant separation.\n\nRisk modeling also clarifies where validation and logging belong. Uploaded content, generated reports, archive entries, and subprocess output should be treated according to source and sensitivity. Logs should identify useful operational events without copying private contents or sensitive paths. The goal is to make the temporary workflow visible enough to operate while keeping the files themselves constrained to the principals and processes that need them.",
  "narrationPoints": [
    "Each transition matters because the application is moving data between subjects, processes, directories, and lifecycle states.",
    "A useful risk model asks who can create, read, modify, delete, or influence each temporary artifact.",
    "Temporary storage should not become a bypass around application authorization or tenant separation.",
    "Uploaded content, generated reports, archive entries, and subprocess output should be treated according to source and sensitivity.",
    "User input may influence file names, upload metadata, archive entries, report parameters, or processing options.",
    "On a shared host, container node, CI runner, job queue, or multi-tenant platform, the answer can be more complicated."
  ]
};
