window.COURSE_MODULE = {
  "title": "Course Summary and Key Takeaways",
  "graphicAlt": "Blank white placeholder image for module 9, Course Summary and Key Takeaways.",
  "narration": "Quantum threats matter because future quantum capability could weaken public-key cryptography that is widely used for key exchange, digital signatures, certificates, software trust, identity, and secure communications. The issue is not panic. It is timing. Complex migration takes planning, and some data and systems have lifetimes long enough that preparation should begin before the threat is operational.\n\nThe highest-priority risks involve long-lived confidential data, long-lived systems, hard-to-replace cryptographic dependencies, and trust mechanisms such as signatures, certificates, code signing, and firmware validation. Harvest-now-decrypt-later risk matters most when sensitive encrypted data could remain valuable for years. Signature risk matters when authenticity and trust must remain verifiable over long operational periods.\n\nStrong security practice starts with inventory, prioritization, cryptographic agility, testing, vendor engagement, and staged migration planning. Inventory shows where cryptography exists. Prioritization shows where quantum risk matters most. Agility makes change possible. Testing reduces deployment risk. Vendor engagement addresses dependencies outside direct control. Staged migration turns a large uncertain problem into manageable work.\n\nThe final takeaway is simple: quantum readiness is a practical engineering and governance program. Practitioners do not need to become quantum physicists, but they do need to understand where public-key cryptography supports confidentiality, integrity, authentication, and trust. The goal is readiness before migration becomes urgent, with decisions grounded in real systems rather than fear or speculation.",
  "narrationPoints": [
    "Quantum threats matter because future quantum capability could weaken public-key cryptography that is widely used for key exchange, digital si...",
    "The highest-priority risks involve long-lived confidential data, long-lived systems, hard-to-replace cryptographic dependencies, and trust mec...",
    "Strong security practice starts with inventory, prioritization, cryptographic agility, testing, vendor engagement, and staged migration planning.",
    "The final takeaway is simple: quantum readiness is a practical engineering and governance program."
  ]
};
