window.COURSE_MODULE = {
  "title": "Why Kubernetes Deployment Scripts Matter",
  "graphicAlt": "A deployment script can change workloads, network exposure, and access, so releases need scoping, review, verification, and recovery.",
  "narration": "Kubernetes deployment scripts are often created because teams need repeatable ways to apply manifests, update images, render Helm charts, run Kustomize overlays, trigger rollouts, check status, and coordinate releases. A script may look like a thin wrapper around kubectl or a deployment tool, but it can still change real cluster state. That makes it production automation, not just command-line convenience.\n\nThe impact of a deployment script can be broad. It may update workloads, services, ingress configuration, network exposure, volumes, service accounts, ConfigMaps, Secrets, resource limits, probes, and availability behavior. A small script can determine what image runs, which namespace receives a change, which service account is used, and whether a release becomes visible to users. Those are security and reliability decisions.\n\nCommon deployment incidents often begin with ordinary mistakes: the wrong cluster context, the wrong namespace, an unexpected image tag, an overbroad identity, an unreviewed rendered manifest, or an ignored command failure. The risk is not that teams use Bash. The risk is that a simple wrapper can hide assumptions that should be explicit and reviewable before production state changes.\n\nSecure Kubernetes deployment scripting treats every deployment as a controlled change to a real system. The defensive goal is scoped, reviewed, observable, and recoverable automation. The script should validate its target, use least privilege, protect credentials, invoke tools predictably, expose enough information for review, verify rollout health, and support recovery when a change does not behave as expected.",
  "narrationPoints": [
    "Kubernetes deployment scripts are often created because teams need repeatable ways to apply manifests, update images, render Helm charts, run Kustomize overlays, trigger rollouts, check status, and coordinate releases.",
    "The impact of a deployment script can be broad.",
    "Common deployment incidents often begin with ordinary mistakes: the wrong cluster context, the wrong namespace, an unexpected image tag, an overbroad identity, an unreviewed rendered manifest, or an ignored command failure.",
    "Secure Kubernetes deployment scripting treats every deployment as a controlled change to a real system."
  ]
};
