window.COURSE_MODULE = {
  "title": "Why iPhone Forensics Matters",
  "graphicAlt": "Blank white placeholder image for module 1, Why iPhone Forensics Matters.",
  "narration": "iPhones are major sources of investigative evidence because they connect communications, accounts, applications, cloud services, media, location signals, and device configuration in one personal device. A lawful investigation may find messages, calls, photos, browsing records, app activity, notifications, account traces, iCloud synchronization, and settings that help explain what happened and when it may have happened.\n\niPhone evidence appears in many professional settings. Incident responders may need to understand whether a user received a suspicious message or interacted with a managed application. Corporate investigators may examine authorized evidence related to insider activity, data handling, or policy concerns. Fraud teams may compare device records, account activity, and communications. Digital forensic practitioners may preserve and analyze an iPhone as one piece of a broader evidence set.\n\nThe key is careful interpretation. Device possession is not the same as device use. Device use is not the same as user intent. Account activity may come from another Apple device, a web session, synchronization, automation, or server-side processing. App activity may be local, cached, restored from backup, or synchronized through a service. A strong investigator keeps those distinctions visible.\n\nAuthorized, documented, evidence-preserving work is the baseline. Investigators need legal authority, organizational authorization, consent, or another valid basis before handling a device or account. They should document condition, custody, collection methods, tool versions, assumptions, and limitations. Privacy also matters: relevant evidence should be handled with care, and unrelated personal data should not be exposed unnecessarily.\n\nThe practical goal is not to extract everything possible. The goal is to preserve relevant evidence, understand where artifacts came from, corroborate findings, and support defensible conclusions. iPhone forensics is strongest when technical artifact knowledge is paired with restraint, documentation, and a willingness to state uncertainty plainly.",
  "narrationPoints": [
    "iPhones are major sources of investigative evidence because they connect communications, accounts, applications, cloud services, media,...",
    "iPhone evidence appears in many professional settings.",
    "The key is careful interpretation.",
    "Authorized, documented, evidence-preserving work is the baseline.",
    "The practical goal is not to extract everything possible."
  ]
};
