window.COURSE_MODULE = {
  "title": "iOS Architecture for Investigators",
  "graphicAlt": "Blank white placeholder image for module 2, iOS Architecture for Investigators.",
  "narration": "iOS and iPadOS are tightly controlled operating systems designed around application isolation, data protection, and integrated hardware security. For investigators, that architecture explains why evidence can be rich but access can be limited. The device model, iOS version, patch level, lock state, configuration, and management posture can all affect what can be acquired and how artifacts should be interpreted.\n\nApp sandboxing is central. Apps are generally isolated from each other and operate inside containers with controlled access to their own data and shared resources. An app may have a data container, preferences, databases, cache files, media, or shared containers used by related apps or extensions. A bundle identifier helps connect artifacts to the application that created or used them.\n\niOS also uses user data partitions, system data, app containers, shared containers, and protected storage. Some artifacts may be available through backups or supported acquisition methods, while others may depend on device state and lawful access conditions. Keychain concepts are relevant at a high level because some credentials, tokens, certificates, or secrets are handled through protected storage mechanisms. Investigators should understand that such material is sensitive and should not be misused.\n\nData protection classes and Secure Enclave concepts matter because they influence availability. At a high level, iOS protects data differently depending on class, lock state, and whether the device has been unlocked after boot. The Secure Enclave supports security functions such as passcode-related protection and cryptographic operations. These concepts explain limitations; they are not a license to bypass protections.\n\nArchitecture affects both acquisition and interpretation. A present artifact may reflect local action, background processing, restoration, or account synchronization. Good forensic reasoning starts by asking how iOS would create, store, protect, and expose the data in question.",
  "narrationPoints": [
    "iOS and iPadOS are tightly controlled operating systems designed around application isolation, data protection, and integrated hardware security.",
    "App sandboxing is central.",
    "iOS also uses user data partitions, system data, app containers, shared containers, and protected storage.",
    "Data protection classes and Secure Enclave concepts matter because they influence availability.",
    "Architecture affects both acquisition and interpretation."
  ]
};
