window.COURSE_MODULE = {
  "title": "Mass Assignment Is an Update-Boundary Failure",
  "graphicAlt": "A two-path boundary diagram contrasts an unsafe direct flow from client JSON through request-body assignment, object spread, merging, generic patch handling, and ORM update into privileged database fields with a safe flow through an operation contract, runtime validation, object authorization, business rules, and explicit mapping. A newly added database column remains locked, reinforcing that user-interface restrictions and authentication are not field-level authorization.",
  "narration": "A TypeScript service may represent one account as incoming JSON, a request object, a domain object, an ORM entity, a persistence update, and an API response. Those representations have different purposes and capabilities. Mass assignment, also called over-posting, occurs when externally supplied properties cross too broadly from a request representation into a sensitive model or persistence operation.\n\nThe statement that updates an account with data equal to req.body is deliberately unsafe. The problem is not unique to a particular ORM. Object spread, Object.assign, entity merging, document-database operators, automatic model binding, generic PATCH handlers, and nested writes can create the same boundary failure. The persistence tool normally performs the update the application requested; it does not know which fields that endpoint intended to expose. Create and upsert endpoints need the same discipline because server-owned defaults, identifiers, and relationships can be over-posted before a record exists.\n\nA client can submit fields that the visible form never contained. Role, tenant identifier, owner identifier, verification state, billing status, account balance, approval flags, audit metadata, and workflow state may all exist in the stored model. Hiding or disabling those controls in the UI is not authorization. Authentication is also insufficient: a user may be allowed to edit a profile but not to change administrative or server-owned state on that same record.\n\nThe server must define writable fields for each operation. Parse and validate the request against a narrow runtime contract, authorize both the target object and the requested operation, apply business rules, and construct the persistence update from approved properties. New database columns should remain unreachable until an operation deliberately maps them. The durable distinction is that a request body describes what the client wants to change; it does not define what the client is permitted to change.",
  "narrationPoints": [
    "Mass assignment is excessive request control over model or persistence properties.",
    "Direct assignment, spread, merging, and generic updates share the same risk.",
    "UI behavior and authentication do not establish field-level permission.",
    "Each operation needs an explicit writable-field contract."
  ]
};
