window.COURSE_MODULE = {
  "title": "Enforce Authorization, Test Negative Paths, and Review Update Flows",
  "graphicAlt": "A secure update pipeline moves from request through runtime validation, object scope, field permission, business rules, explicit mapping, and persistence. A review scanner flags broad data-flow patterns, while negative tests for extra, privileged, nested, cross-tenant, null, and bulk inputs verify both a rejected response and an unchanged database; constraints and least privilege remain defense in depth beneath application policy.",
  "narration": "A narrow field contract does not determine which record a caller may change. Enforce object-level scope with tenant, owner, administrator, and current-state rules. Prefer scoped lookups or updates that include the security boundary in the query where appropriate, then apply field-level permission and business logic. An authenticated principal can still be unauthorized for the target object or for a particular field transition. Ensure an unscoped object loaded earlier cannot bypass the tenant condition during persistence.\n\nReview the complete flow from request through runtime validation, authorization, mapping, business logic, and persistence. Search for direct req.body usage, object spread, Object.assign, generic model binders, Partial of an entity used as a public DTO, ORM-generated update inputs in controller signatures, nested relation operations, and bulk updates. Identify where the writable-field allowlist is expressed and confirm later code cannot reintroduce raw data.\n\nNegative tests are especially important because intended clients never send the properties that reveal this defect. Submit unknown keys, server-owned fields, privileged state fields, nested unauthorized children, and fields valid on a different endpoint. Test another tenant's identifier, unauthorized administrative actions, null and omission boundaries, empty values, duplicate or conflicting changes, and bulk requests containing at least one out-of-scope object. Assert both the response and unchanged persistence state.\n\nAdd regression tests when models gain columns or relations. A useful invariant is that the endpoint's writable set changes only when its contract and mapper change. Log denied privileged operations and authorization failures without recording sensitive request bodies. Least-privilege database accounts and constraints provide containment and invariant protection, but ordinary database permissions rarely express field-level business policy per endpoint. The application service remains responsible for translating authenticated intent into an authorized, explicit persistence command.",
  "narrationPoints": [
    "Enforce object scope and field-level permission as separate decisions.",
    "Review the full request-to-validation-to-authorization-to-persistence flow.",
    "Test fields the intended client never sends and verify state remains unchanged.",
    "Use database controls as defense-in-depth, not endpoint authorization."
  ]
};
