window.COURSE_MODULE = {
  "title": "Error Handling, Logging, and Secret Protection",
  "graphicAlt": "Errors lead to controlled cleanup, bounded retries or safe responses, while minimal events are redacted before protected logging and secrets remain excluded.",
  "narration": "Go makes errors explicit, which is useful for security review. Each returned error is a point where the application decides whether to retry, stop, clean up, roll back, log, or return a response. Secure error handling preserves invariants on failure. It avoids partial state changes that leave a request half-complete or a resource in an unclear state.\n\nInternal errors can include useful technical context, but user-facing responses should be safe and consistent. A client usually needs to know whether a request was invalid, unauthorized, not found, conflicted, rate limited, or temporarily unavailable. The client does not need raw stack traces, secret values, SQL text, internal file paths, dependency details, or configuration values.\n\nLogging should support investigation without becoming a data leak. Structured logs, request IDs, correlation IDs, event categories, and appropriate log levels help operators understand what happened. At the same time, tokens, cookies, API keys, passwords, private user data, raw payloads, and internal configuration should not be logged casually. Logs often flow to dashboards, tickets, alerts, long-term storage, and third-party monitoring platforms.\n\nSecret protection should be boring and disciplined. Keep secrets server-side. Read them from approved environment or secret-store mechanisms. Avoid printing secrets during startup or tests. Scope credentials to the job they need. When errors and logs are designed carefully, teams get useful visibility while reducing the chance that observability becomes another exposure path.\n\nThe safest error strategy is intentional and consistent. Decide which errors should be retried, which should be reported to the caller, which should trigger alerts, and which should be summarized without sensitive details. Then test those paths. Error handling is part of the application's security contract because failure is when assumptions are most likely to break.",
  "narrationPoints": [
    "Go makes errors explicit, which is useful for security review.",
    "Internal errors can include useful technical context, but user-facing responses should be safe and consistent.",
    "Logging should support investigation without becoming a data leak.",
    "Secret protection should be boring and disciplined.",
    "The safest error strategy is intentional and consistent."
  ]
};
