window.COURSE_MODULE = {
  "title": "Dependencies, Build Settings, and Secure Delivery",
  "graphicAlt": "Reviewed dependencies pass testing and analysis into a build and least-privilege deployment, with separate configuration and secret injection plus patch and rollback readiness.",
  "narration": "Go applications often compile into a small, simple deployment artifact. That simplicity is useful, but the security of the artifact still depends on source code, dependencies, build inputs, configuration, runtime permissions, and release practices. A clean binary does not remove the need for disciplined delivery.\n\nGo modules make dependency management explicit, but teams still need ownership. Review new packages before adding them. Understand why a dependency is needed, whether it is maintained, what transitive dependencies it brings, and how it will be updated. Module checksums and version control support repeatability, but they do not replace review, vulnerability monitoring, or removal of unnecessary packages.\n\nBuild and delivery settings deserve security attention. Static analysis, linting, unit tests, integration tests, negative tests, dependency checks, and CI gates all help catch issues before release. Container image choices, runtime users and permissions, environment separation, configuration sources, and secret injection paths affect the behavior of the deployed service. Development convenience should not silently become production policy.\n\nSecure delivery is a repeatable process, not a one-time scan. Maintain release notes, rollback readiness, patch workflows, and evidence that important controls were tested. When a dependency changes, a build setting changes, or a deployment target changes, reviewers should ask what security assumptions changed with it. A well-governed Go service is easier to update when vulnerabilities, incidents, or operational needs appear.\n\nDelivery decisions should be visible to both developers and operators. A secure build is easier to trust when inputs are known, configuration is separated by environment, runtime permissions are narrow, and release evidence is easy to find. That visibility turns patching from a panic into a practiced workflow.",
  "narrationPoints": [
    "Go applications often compile into a small, simple deployment artifact.",
    "Go modules make dependency management explicit, but teams still need ownership.",
    "Build and delivery settings deserve security attention.",
    "Secure delivery is a repeatable process, not a one-time scan.",
    "Delivery decisions should be visible to both developers and operators."
  ]
};
