window.COURSE_MODULE = {
  "title": "File Uploads Cross Several Trust Boundaries",
  "graphicAlt": "An uploaded file and its name, type, and size claims cross an application boundary into parsing, restricted storage, validation and processing, explicit publication, and delivery. Pending files remain restricted and invalid files are rejected. Authentication does not validate the file; the server chooses destinations, authorizes operations, and cleans up partial work.",
  "narration": "A file upload introduces untrusted content and untrusted metadata into several parts of an application. Receiving the HTTP request is only the beginning. Multipart parsing separates fields and file streams. Temporary storage or memory buffering holds the bytes. Validation classifies them, persistence assigns ownership, and processors may decode, transform, or scan them. Later, a download endpoint or public delivery service interprets the stored record again. Each transition needs an explicit trust decision.\n\nThe original filename, extension, declared media type, and claimed size all come from the sender. So do the file contents, embedded metadata, archive entry names, and any submitted tenant or destination identifiers. Authentication identifies a caller; it does not make those values reliable. TypeScript interfaces and assertions also provide no runtime file validation. Renaming a request object to a trusted upload type changes the compiler's assumptions without changing the evidence available to the service.\n\nWriting a file buffer to a path formed from an upload directory and the original filename hides several independent assumptions. It assumes the filename chooses an acceptable destination, the resulting path stays inside the intended root, and an existing object may be overwritten. It also assumes the full buffer fits safely in memory, the format is permitted, and future consumers can handle the stored bytes. A path joining function does not establish those guarantees, and a successful write establishes none of the missing file checks.\n\nDesign the pipeline so those decisions remain visible. Authorize the intended operation, constrain incoming work, validate the supported file class, assign storage identity on the server, and isolate content from application code. Then control every later use of the bytes. Temporary files need the same path, permission, and cleanup discipline as permanent objects. Public availability should be a deliberate state reached after required checks, rather than an accidental consequence of where an upload happened to land.",
  "narrationPoints": [
    "Uploads cross parsing, storage, processing, publication, and delivery boundaries.",
    "File bytes and all client metadata remain untrusted after authentication.",
    "Original filenames and path joining do not establish safe storage.",
    "Make trust decisions and cleanup responsibilities explicit at each stage."
  ]
};
