window.COURSE_MODULE = {
  "title": "Validate File Type Using Multiple Signals",
  "graphicAlt": "Client filename and media-type hints, byte-pattern recognition, and bounded decoding provide distinct evidence to a feature-policy decision that accepts or rejects content. A narrow image workflow decodes and re-encodes a derived image, checks the output, and discards unnecessary metadata. Documents and archives need their own rules; no single check proves safety.",
  "narration": "File classification starts with what the feature intends to accept. An extension allowlist and the multipart media type can catch ordinary client mistakes, but both values are supplied by the sender. A request labeled as a PNG still carries arbitrary bytes. Define how the service handles mismatches and unsupported types, and reject ambiguous results rather than silently widening the accepted formats until some parser succeeds.\n\nContent signatures provide another signal by recognizing characteristic bytes. They identify many common formats, but do not describe every structure in the file or prove that later processing is safe. Use recognition by the intended parser or decoder, together with application specific checks, to establish the supported representation. Successful decoding is useful evidence about format compatibility. It is not proof that embedded content, external references, metadata, or the parser implementation itself are harmless.\n\nFor a narrow image workflow, canonicalization can reduce what is retained. Decode an explicitly supported format with resource limits, enforce dimensions and pixel count, and encode a new representation under server control. Retain only metadata the feature needs. If the original has no business purpose, discard it according to cleanup policy and store the derived image. The published classification and extension should describe the actual output, and checks must apply to the exact bytes selected for publication.\n\nThis technique is specific to the chosen media workflow. Re-encoding an image does not create a universal sanitizer for PDFs, office documents, archives, or every browser viewable format. Those formats need policies for their own structures and active capabilities. Keep decoders and inspection libraries maintained, and isolate complex parsing where the risk warrants it. Malware scanning can add another layer, but a clean result does not prove complete safety. The acceptance decision should combine the business contract, content evidence, resource policy, and intended downstream use rather than depending on one convenient label.",
  "narrationPoints": [
    "Extensions and declared media types are hints supplied by the client.",
    "Combine content recognition, intended decoding, and structural policy.",
    "Re-encode selected media under limits when it meaningfully reduces retained structure.",
    "Neither magic bytes, decoding, re-encoding, nor scanning proves universal safety."
  ]
};
