window.COURSE_MODULE = {
  "title": "Store Uploads Where They Cannot Become Application Code",
  "graphicAlt": "Uploaded content stays in private storage until an explicit publication gate approves it, separate from application source, templates, and executable code. Download authorization resolves a trusted attachment and server-owned key before applying response type, disposition, cache, and scoped-link policy. Browser nosniff and isolation for high-risk inline content are separate controls, not guarantees of harmless rendering.",
  "narration": "Storage design determines what other systems can do with uploaded bytes. Keep uploads out of application source, template directories, executable script locations, and paths involved in module or configuration loading. Avoid a static web directory whose configuration could expose content immediately or interpret it in an unintended way. Use a dedicated storage area with generated identifiers and permissions limited to the operations each service actually needs.\n\nA private object bucket can provide useful separation, but it does not supply application authorization automatically. Bucket policies, object keys, service credentials, and signed URLs all affect access. Keep unpublished objects inaccessible to normal download paths. When public files are required, make publication an explicit transition after validation and processing. Services that ingest or transform content should not receive broad access to unrelated application files or other tenants' objects.\n\nServing introduces a separate interpretation boundary. Authorize the caller against the attachment record before resolving its server owned storage key. Choose the response content type from the validated classification or a deliberate generic download policy, not the original multipart header. Use attachment disposition when the product only needs a download, and construct the display filename with safe header handling. Add the no sniff response header to constrain browser type guessing in the contexts where that header applies.\n\nAttachment disposition and no sniff are delivery controls, not guarantees that opening a file is harmless. Intentionally inline formats need an appropriate active content model, and higher risk untrusted content may warrant a separate origin without the application's credentials. Set cache policy to match confidentiality; a private download must not become a shared cached response. Issue download links only after authorization, with appropriate scope and lifetime. A generated storage key or an expired application session does not necessarily revoke an already issued signed URL. Design storage, publication, and browser delivery together so each consumer receives only the authority intended for that file.",
  "narrationPoints": [
    "Isolate uploads from source, templates, executable paths, and automatic publication.",
    "Use least privilege for storage and processing identities.",
    "Authorize retrieval and set server-selected type, disposition, and cache policy.",
    "Attachment and nosniff are partial controls; inline content needs its own security model."
  ]
};
