window.COURSE_MODULE = {
  "title": "Process Archives, Images, and Documents with Resource Limits",
  "graphicAlt": "A resource-budget gate constrains expanded pages and images through pixel, page, expansion, depth, CPU, memory, time, and output limits. Separate controls contain archive entries, block escaping paths, isolate workers with restricted filesystem and network access, stop timed-out work, clean up partial output, and validate derived artifacts. Request-size limits do not replace processing limits.",
  "narration": "Processing can amplify both complexity and resource use far beyond the upload request. Image decoders, document parsers, archive extractors, media converters, metadata tools, scanners, and indexing services all interpret structures chosen by the sender. A small compressed file can describe a large amount of output. An image's encoded byte size does not bound its decoded pixel count. A request limit therefore protects a different stage from processing limits.\n\nSet budgets for the actual work: dimensions and pixels, document pages, archive entries, nesting depth, decompressed bytes, output size, processing time, CPU, and memory. Enforce limits while work proceeds, not only after all output has been allocated. Bound concurrency and temporary disk usage as well. When a processor times out, stop its work and remove partial output; returning an error while the process continues consuming resources does not enforce the budget.\n\nArchive extraction also crosses a filesystem boundary. Every entry must resolve inside the intended extraction root. Entry names do not get to choose arbitrary destinations, and links or existing directory structures must not redirect writes outside that root. Prefer a maintained extractor with safe defaults, reject unsupported entry types, and extract into a fresh restricted workspace. Verify containment for each output and constrain total expansion. Nested archives require an explicit depth policy rather than unrestricted recursive unpacking.\n\nKeep file processing libraries patched because validation intentionally exposes parsers to hostile bytes. Separate workers, sandboxed processes, or restricted containers can limit the consequences of parser failure. Use low privilege identities, restrict filesystem access, and disable unnecessary network access to prevent processors from reaching unrelated resources. Isolation supplements format validation and resource budgets; it does not decide what the feature should accept. Treat derived outputs as new artifacts requiring an expected format, bounded size, and controlled promotion. Successful process exit alone should not cause every generated file to become downloadable.",
  "narrationPoints": [
    "Bound decoded and decompressed work independently of upload byte size.",
    "Limit time, CPU, memory, concurrency, temporary space, and output size.",
    "Contain every archive entry and prevent link-based destination changes.",
    "Patch and isolate processors; validate derived outputs before publication."
  ]
};
