window.COURSE_MODULE = {
  "title": "Why ShellCheck Matters",
  "graphicAlt": "Small shell scripts can affect deployments, backups, services, and incident response, so review belongs before operational impact.",
  "narration": "Shell scripts are often introduced as small pieces of glue code, but many of them become operational software. They deploy applications, rotate logs, copy files, restart services, run backups, collect diagnostics, move data between systems, and support incident response. When a script controls real infrastructure, a small parsing mistake or unchecked assumption can become an outage, a failed deployment, or a confusing production incident.\n\nShell is easy to underestimate because simple commands look readable. The hard parts are usually the invisible ones: quoting, expansion, word splitting, globbing, exit status, command substitution, pipelines, and the differences between shell dialects. A script can appear correct with one filename, one environment, or one test value, then behave differently when a path contains a space, a variable is empty, a wildcard appears in input, or the script runs under a different shell.\n\nShellCheck helps by applying static analysis to shell scripts before they reach production. It looks for patterns that commonly lead to bugs, confusing behavior, portability problems, and unsafe automation. It can flag likely quoting problems, suspicious tests, unused variables, dialect mismatches, and other issues that reviewers may miss during a busy pull request. The value is consistency: the same class of mistake can be caught repeatedly across teams and repositories.\n\nShellCheck does not replace engineering judgment, testing, or review. It cannot know every operational context or decide what failure should mean for a specific workflow. The right posture is tool-assisted review, not blind trust. A finding is a prompt to understand the script more carefully. Used well, ShellCheck reduces preventable failures, improves maintainability, and gives teams a practical way to make shell automation safer before it matters most.",
  "narrationPoints": [
    "Shell scripts are often introduced as small pieces of glue code, but many of them become operational software.",
    "Shell is easy to underestimate because simple commands look readable.",
    "ShellCheck helps by applying static analysis to shell scripts before they reach production.",
    "ShellCheck does not replace engineering judgment, testing, or review."
  ]
};
