window.COURSE_MODULE = {
  "title": "Quoting, Word Splitting, and Globbing",
  "graphicAlt": "An unquoted path containing a space can become two arguments; quoted expansion preserves it as one argument.",
  "narration": "Quoting is one of the most important ShellCheck themes because it protects argument boundaries. In many programming languages, a string variable remains one string when it is passed to another function. In shell, an unquoted variable expansion may be split into multiple words and may also be treated as a filename pattern. That behavior can change the number and meaning of arguments sent to a command.\n\nThe problem often appears with ordinary data: paths with spaces, empty values, names that contain wildcard characters, or values produced by another command. A script may work during testing because the sample path is simple, then fail later when a real path contains whitespace. It may behave unexpectedly when an empty variable removes an argument or when an asterisk is interpreted as a pattern rather than data. ShellCheck warnings help reviewers notice those conditions before they become incidents.\n\nQuoting is not just a style preference. It is a safety control that tells the shell to treat a value as data. When a variable represents one path, one identifier, or one option value, quoting usually preserves the intent. Reviewers should ask whether the script wants one argument or many, whether empty values are allowed, and whether filename expansion is intended. Most of the time, preserving the value as one argument is safer and clearer.\n\nThere are legitimate cases where a script intentionally relies on splitting or pattern expansion, but those cases should be obvious and reviewed. If the script needs a list, consider using a safer structure appropriate for the intended shell. If it needs a pattern, make that intent explicit. ShellCheck is most useful when it pushes the team to distinguish accidental shell interpretation from deliberate design.",
  "narrationPoints": [
    "Quoting is one of the most important ShellCheck themes because it protects argument boundaries.",
    "The problem often appears with ordinary data: paths with spaces, empty values, names that contain wildcard characters, or values produced by another command.",
    "Quoting is not just a style preference.",
    "There are legitimate cases where a script intentionally relies on splitting or pattern expansion, but those cases should be obvious and reviewed."
  ]
};
