window.COURSE_MODULE = {
  "title": "What Is Critical Thinking?",
  "graphicAlt": "Blank white placeholder image for module 1, What Is Critical Thinking?.",
  "narration": "Critical thinking is disciplined evaluation of claims, evidence, assumptions, and reasoning. It is not the habit of rejecting everything, and it is not a personality style where someone simply sounds sharp in a meeting. It is a practical skill for slowing down enough to ask what is being claimed, what supports it, what might be missing, and how strong the conclusion should be.\n\nIt helps to separate criticism, skepticism, cynicism, and careful judgment. Criticism can point out flaws, but it can also become reactive. Skepticism asks for reasons before accepting a claim, which can be healthy when it stays proportionate. Cynicism assumes the worst and often stops inquiry too early. Careful judgment is different: it stays open to evidence, tests assumptions, and adjusts confidence as the situation becomes clearer.\n\nCritical thinking matters anywhere decisions are made under pressure. In technical work, it helps teams avoid confusing a symptom with a root cause. In security, it helps analysts evaluate alerts, threat claims, vendor promises, and incident evidence. In leadership and operations, it supports clearer priorities, better escalation, and fewer avoidable mistakes. In learning, it helps people distinguish understanding from memorized confidence.\n\nThe skill is not reserved for unusually argumentative people. It can be practiced through better questions, structured review, clearer definitions, and willingness to update. A junior engineer can think critically about a design assumption. A manager can think critically about a staffing plan. A learner can think critically about a source that sounds polished but gives weak evidence.\n\nThe goal is better questions, clearer reasoning, and more reliable conclusions. Critical thinking does not make uncertainty disappear, and it does not guarantee that every conclusion will be correct. It improves the process by which conclusions are reached, communicated, tested, and revised.",
  "narrationPoints": [
    "Critical thinking is disciplined evaluation of claims, evidence, assumptions, and reasoning.",
    "It is not the habit of rejecting everything, and it is not a personality style where someone simply sounds sharp in a meeting.",
    "It is a practical skill for slowing down enough to ask what is being claimed, what supports it, what might be missing, and how strong the conclusion should be.",
    "It helps to separate criticism, skepticism, cynicism, and careful judgment.",
    "Criticism can point out flaws, but it can also become reactive.",
    "Skepticism asks for reasons before accepting a claim, which can be healthy when it stays proportionate."
  ]
};
