window.COURSE_MODULE = {
  "title": "Federation, SSO, and Modern Identity Protocols",
  "graphicAlt": "Blank placeholder image for a lesson on federation, SSO, and modern identity protocols.",
  "narration": "Single sign-on, or SSO, allows users to authenticate through a central identity provider and access multiple applications that trust that provider. The application or service relying on that identity information is often called a service provider or relying party. Federation is the trust relationship that lets one system rely on identity information from another. This can improve consistency, but it also concentrates risk in identity configuration.\n\nSAML, OAuth, and OpenID Connect are often discussed together, but they serve different roles at a high level. SAML is commonly used for enterprise federation and signed assertions. OAuth is primarily about delegated access, where a client receives permission to access resources on behalf of a user or service. OpenID Connect adds an identity layer on top of OAuth-style flows for sign-in and identity claims.\n\nScopes and claims describe requested access and identity information. A scope might represent delegated permission. A claim might state an identifier, group, assurance level, or other attribute. Protocol data must be validated carefully by the application or platform that consumes it. Teams should understand protocol roles and trust boundaries, while relying on mature libraries and identity platforms rather than hand-rolling protocol behavior.\n\nFederation applies to enterprise identity, customer identity, service-to-service authentication, and workload identity. It can make authentication more consistent and easier to govern, but misconfigured trust, overly broad application assignment, weak claim handling, stale certificates, or excessive delegated access can affect many systems at once. Federation needs governance, review, monitoring, and lifecycle management.",
  "narrationPoints": [
    "Single sign-on, or SSO, allows users to authenticate through a central identity provider and access multiple applications that trust that prov...",
    "SAML, OAuth, and OpenID Connect are often discussed together, but they serve different roles at a high level.",
    "Scopes and claims describe requested access and identity information.",
    "Federation applies to enterprise identity, customer identity, service-to-service authentication, and workload identity."
  ]
};
