window.COURSE_MODULE = {
  "title": "A04: Insecure Design",
  "graphicAlt": "Graphic for A04: Insecure Design",
  "narration": "Threat modeling helps teams ask how a feature can be abused before the implementation hardens into production behavior. Without that step, teams may protect individual endpoints while leaving unsafe business flows intact. Security requirements translate risk into design constraints.\n\nRequirements such as rate limits, approval gates, auditability, tenant isolation, and fraud controls should be visible before coding begins. Unsafe architectural assumptions often appear when services trust internal networks, client-side state, partner integrations, or sequence order more than they should. Attackers routinely exploit those assumptions rather than a single defective line of code.\n\nInsecure design is not fixed by scanning alone. It requires review of workflows, trust boundaries, misuse cases, control ownership, and the decisions that determine how the application is supposed to behave. Use a secure SDLC with security requirements at design time.\n\nRun threat modeling for critical workflows and trust boundaries. Perform security architecture reviews before major releases. Selected NIST mappings for this topic include SA-3 - System Development Life Cycle; SA-8 - Security and Privacy Engineering Principles; RA-3 - Risk Assessment.",
  "narrationPoints": [
    "Threat modeling helps teams ask how a feature can be abused before the implementation hardens into production behavior. Without that step, teams may protect individual endpoints while leaving unsafe business flows intact. Security requirements translate risk into design constraints.",
    "Requirements such as rate limits, approval gates, auditability, tenant isolation, and fraud controls should be visible before coding begins. Unsafe architectural assumptions often appear when services trust internal networks, client-side state, partner integrations, or sequence order more than they should. Attackers routinely exploit those assumptions rather than a single defective line of code.",
    "Insecure design is not fixed by scanning alone. It requires review of workflows, trust boundaries, misuse cases, control ownership, and the decisions that determine how the application is supposed to behave. Use a secure SDLC with security requirements at design time.",
    "Run threat modeling for critical workflows and trust boundaries. Perform security architecture reviews before major releases. Selected NIST mappings for this topic include SA-3 - System Development Life Cycle; SA-8 - Security and Privacy Engineering Principles; RA-3 - Risk Assessment."
  ]
};
