window.COURSE_MODULE = {
  "title": "A06: Vulnerable and Outdated Components",
  "graphicAlt": "Graphic for A06: Vulnerable and Outdated Components",
  "narration": "Dependency management requires knowing what software the application uses and where it is deployed. Without inventory, teams cannot reliably assess exposure when a new vulnerability is announced. Unsupported software is difficult to defend because fixes may no longer be available.\n\nLegacy frameworks, old runtimes, abandoned packages, and unmaintained plugins can become permanent risk unless they are replaced. Third-party risk includes both known vulnerabilities and the possibility of supply chain compromise. Packages, build tools, images, and vendor components should be evaluated as part of the application security boundary.\n\nVersion updates must be paired with testing and release discipline. The goal is to remediate exploitable risk quickly without creating instability that causes teams to delay patching indefinitely. Maintain software inventory and dependency visibility.\n\nUse vulnerability monitoring and dependency scanning. Patch, upgrade, or isolate vulnerable components according to risk. Selected NIST mappings for this topic include SI-2 - Flaw Remediation; CM-8 - System Component Inventory; RA-5 - Vulnerability Monitoring and Scanning.",
  "narrationPoints": [
    "Dependency management requires knowing what software the application uses and where it is deployed. Without inventory, teams cannot reliably assess exposure when a new vulnerability is announced. Unsupported software is difficult to defend because fixes may no longer be available.",
    "Legacy frameworks, old runtimes, abandoned packages, and unmaintained plugins can become permanent risk unless they are replaced. Third-party risk includes both known vulnerabilities and the possibility of supply chain compromise. Packages, build tools, images, and vendor components should be evaluated as part of the application security boundary.",
    "Version updates must be paired with testing and release discipline. The goal is to remediate exploitable risk quickly without creating instability that causes teams to delay patching indefinitely. Maintain software inventory and dependency visibility.",
    "Use vulnerability monitoring and dependency scanning. Patch, upgrade, or isolate vulnerable components according to risk. Selected NIST mappings for this topic include SI-2 - Flaw Remediation; CM-8 - System Component Inventory; RA-5 - Vulnerability Monitoring and Scanning."
  ]
};
