window.COURSE_MODULE = {
  "title": "A08: Software and Data Integrity Failures",
  "graphicAlt": "Graphic for A08: Software and Data Integrity Failures",
  "narration": "CI/CD compromise can turn the build pipeline into an attack path. Build credentials, deployment tokens, source control permissions, artifact repositories, and runner environments all require protection. Unsigned updates and unverified artifacts make it difficult to know whether code is authentic.\n\nIntegrity checks help prevent tampering between development, build, release, and deployment stages. Insecure deserialization is a data integrity problem because the application trusts serialized input to reconstruct objects or behavior. Attackers may use that trust to trigger unexpected code paths or manipulate application state.\n\nPipeline integrity depends on separation of duties, access restrictions, reviewed changes, protected branches, reproducible builds where practical, and traceability from source to deployed artifact. Verify artifact integrity and provenance. Sign code and protect release channels.\n\nSecure CI/CD pipelines with least privilege, approvals, and monitored changes. Selected NIST mappings for this topic include SI-7 - Software, Firmware, and Information Integrity; CM-5 - Access Restrictions for Change; SA-10 - Developer Configuration Management.",
  "narrationPoints": [
    "CI/CD compromise can turn the build pipeline into an attack path. Build credentials, deployment tokens, source control permissions, artifact repositories, and runner environments all require protection. Unsigned updates and unverified artifacts make it difficult to know whether code is authentic.",
    "Integrity checks help prevent tampering between development, build, release, and deployment stages. Insecure deserialization is a data integrity problem because the application trusts serialized input to reconstruct objects or behavior. Attackers may use that trust to trigger unexpected code paths or manipulate application state.",
    "Pipeline integrity depends on separation of duties, access restrictions, reviewed changes, protected branches, reproducible builds where practical, and traceability from source to deployed artifact. Verify artifact integrity and provenance. Sign code and protect release channels.",
    "Secure CI/CD pipelines with least privilege, approvals, and monitored changes. Selected NIST mappings for this topic include SI-7 - Software, Firmware, and Information Integrity; CM-5 - Access Restrictions for Change; SA-10 - Developer Configuration Management."
  ]
};
