window.COURSE_MODULE = {
  "title": "Course Summary and Compliance Context",
  "graphicAlt": "Graphic for Course Summary and Compliance Context",
  "narration": "The OWASP Top 10 gives teams a compact way to discuss common application risks, from access control and cryptography to injection, design, configuration, components, identity, integrity, monitoring, and SSRF. NIST SP 800-53 controls help translate those risks into expectations for governance, engineering, operations, monitoring, and evidence. A mapping can show where application security activities support broader control objectives.\n\nSecurity and compliance share responsibility across developers, platform teams, security engineers, administrators, managers, and compliance teams. The strongest programs make secure behavior repeatable rather than dependent on heroics. Completion of this course should be treated as awareness training.\n\nIt does not prove that an organization has implemented controls, remediated vulnerabilities, or achieved compliance with any specific framework. Useful follow-on materials include OWASP references, NIST SP 800-53 references, secure coding checklists, a glossary, a mapping matrix, developer quick-reference sheets, and audit support documentation. Use this mapping as a discussion and planning aid.\n\nValidate control implementation in the local environment. Maintain evidence for secure development, monitoring, configuration, and remediation activities. Selected NIST mappings for this topic include RA-5 - Vulnerability Monitoring and Scanning; SA-11 - Developer Testing and Evaluation; CA-2 - Control Assessments.",
  "narrationPoints": [
    "The OWASP Top 10 gives teams a compact way to discuss common application risks, from access control and cryptography to injection, design, configuration, components, identity, integrity, monitoring, and SSRF. NIST SP 800-53 controls help translate those risks into expectations for governance, engineering, operations, monitoring, and evidence. A mapping can show where application security activities support broader control objectives.",
    "Security and compliance share responsibility across developers, platform teams, security engineers, administrators, managers, and compliance teams. The strongest programs make secure behavior repeatable rather than dependent on heroics. Completion of this course should be treated as awareness training.",
    "It does not prove that an organization has implemented controls, remediated vulnerabilities, or achieved compliance with any specific framework. Useful follow-on materials include OWASP references, NIST SP 800-53 references, secure coding checklists, a glossary, a mapping matrix, developer quick-reference sheets, and audit support documentation. Use this mapping as a discussion and planning aid.",
    "Validate control implementation in the local environment. Maintain evidence for secure development, monitoring, configuration, and remediation activities. Selected NIST mappings for this topic include RA-5 - Vulnerability Monitoring and Scanning; SA-11 - Developer Testing and Evaluation; CA-2 - Control Assessments."
  ]
};
