window.COURSE_MODULE = {
  "title": "Begin with Intent, Scope, and Constraints",
  "graphicAlt": "A vague software request being transformed into a focused engineering task with user, goal, inputs, outputs, constraints, and testable success criteria.",
  "narration": "Weak AI-assisted results often begin with an unclear request. \"Build an app\" leaves the assistant to guess the user, the environment, the data, the interface, and the standard for success. A stronger request explains who the software is for, what outcome it should produce, what inputs it receives, what outputs it creates, and what must remain unchanged.\n\nBefore asking for code, define the smallest useful outcome. \"Improve reporting\" is a direction, not an implementation target. \"Add comma-separated value export to the existing report page without changing the database schema\" gives the assistant a narrower problem to solve. Small outcomes make the first patch easier to review and easier to reject if it heads in the wrong direction.\n\nConstraints are part of the task, not optional decoration. The assistant needs to know the programming language and version, the framework already in use, supported operating systems, browser expectations, data formats, accessibility needs, performance limits, security requirements, and files that should not be touched. If new libraries are not allowed, say so. If the command must run on Windows and Linux, say that too.\n\nSuccess criteria should be observable. \"Make it better\" is hard to test. \"The command accepts an input file, rejects malformed rows, and writes a valid JavaScript Object Notation result\" can be checked. These criteria do not need to become heavy paperwork. A few precise acceptance criteria give both the developer and the assistant a shared target. They also make it easier to notice when an attractive implementation solves a different problem.\n\nWhen the task is ambiguous or consequential, ask the assistant to restate the plan before it writes code. That pause can reveal a wrong assumption about the data model, the user interface, or the files to edit. Clear intent does not require a perfect specification. It reduces avoidable ambiguity enough to make the first implementation useful, bounded, and reviewable.",
  "narrationPoints": [
    "Clear intent improves generated code.",
    "The smallest useful outcome keeps the patch reviewable.",
    "Technical and operational constraints belong in the request.",
    "Observable success criteria make validation possible.",
    "A proposed plan can expose incorrect assumptions before code changes begin."
  ]
};
