window.COURSE_MODULE = {
  "title": "Security, Privacy, and Dependency Risks",
  "graphicAlt": "A secure AI coding boundary showing protected secrets, dependency verification, least-privilege tools, code review, and human approval gates.",
  "narration": "AI-assisted coding can accelerate good decisions, but it can also accelerate dangerous ones. Security cannot be postponed until the end of the conversation. The same speed that helps a prototype appear quickly can also add an unsafe default, a broad permission, or a risky dependency before anyone has stopped to ask whether it belongs.\n\nProtect sensitive information first. Do not paste credentials, private keys, access tokens, personal data, confidential source code, internal logs, or customer information into a coding service unless the environment and organizational policy explicitly permit it. A useful assistant response is never worth exposing data that should stay private. When in doubt, replace real values with realistic examples and keep the original material inside approved systems.\n\nGenerated code may introduce familiar weaknesses. Watch for missing authorization checks, unsafe command construction, injection risks, insecure temporary files, weak secret handling, excessive permissions, overly detailed error messages, unvalidated file paths, or unsafe deserialization, which means turning data back into program objects without enough checks. These issues are not exotic. They are common ways ordinary software becomes unsafe, especially when a patch is accepted because it appears to solve the visible happy path.\n\nDependencies need their own review. An assistant may suggest a package that is unnecessary, outdated, incompatible, poorly maintained, incorrectly licensed, or nonexistent. Verify the package name, official source, version, license, maintenance status, and security history before adding it. Installation commands and scripts also deserve inspection, because they can run downloaded code or change the machine.\n\nUse least privilege for tools and agents. Give access only to the repository, commands, credentials, and deployment capabilities needed for the current task. High-impact actions such as deleting data, changing infrastructure, deploying to production, using credentials, sending external messages, or spending money should require deliberate human approval. Convenience does not transfer accountability. The developer remains responsible for protecting systems and data.",
  "narrationPoints": [
    "AI assistance can amplify insecure decisions.",
    "Sensitive data should stay out of unapproved systems.",
    "Generated code must be reviewed for common weaknesses.",
    "Dependencies and installation commands require verification.",
    "Least privilege limits tool and agent impact.",
    "High-impact actions need human approval gates."
  ]
};
