window.COURSE_MODULE = {
  "title": "From Prototype to Maintainable Software",
  "graphicAlt": "A rough AI-generated prototype moving through testing, security, refactoring, documentation, monitoring, and deployment gates to become maintainable software.",
  "narration": "A successful prototype answers a limited question: can this idea work well enough to explore? Production software has a harder job. It must continue working for real users, changing requirements, operational failures, security expectations, and future maintainers who were not present during the original AI conversation.\n\nPrototype code often carries useful shortcuts. It may contain hard-coded values, minimal error handling, weak authentication, no migration strategy, limited logging, incomplete accessibility, fragile dependencies, and tests that cover only the happy path. These weaknesses do not mean the prototype was a failure. They mean the prototype has not yet been prepared for real use. The same shortcut that helped answer a design question can become a defect when real users, real data, and real outages enter the picture.\n\nBefore treating a prototype as a product, perform a deliberate hardening pass. Review architecture and ownership boundaries, configuration management, secret handling, input validation, error behavior, logging, monitoring, backup and recovery, performance limits, accessibility, dependency risk, deployment, rollback, test coverage, and documentation. Observability means the system gives operators enough signals, such as logs and metrics, to understand what is happening in production.\n\nRefactoring is part of that transition. Generated code may contain duplicated logic, inconsistent naming, unnecessary abstractions, or logic placed in the wrong layer. Refactoring should improve structure while preserving observable behavior. Tests make this safer because they help confirm that the cleanup did not change the intended result.\n\nImportant knowledge should live in the repository, not only in the chat history. Future contributors need setup instructions, architecture decisions, environment requirements, test commands, known limitations, and operational procedures. They should not have to reconstruct the system from a vanished conversation or trust that a generated structure was sensible by default. Rapid generation and maintainability are not opposites. Speed is most valuable when the resulting system remains understandable, testable, and safe to change.",
  "narrationPoints": [
    "A prototype proves an idea; a product must survive real use.",
    "Prototype shortcuts need a hardening pass before production.",
    "Security, observability, deployment, recovery, and tests need review.",
    "Refactoring improves structure while preserving behavior.",
    "Important project knowledge should live in the repository.",
    "Sustainable speed preserves understanding and changeability."
  ]
};
