window.COURSE_MODULE = {
  "title": "Design Caches and Fallbacks Without Creating Fail-Open Authorization",
  "graphicAlt": "Infographic of an authorization cache vault whose decision key binds subject, tenant, resource, action, attributes, and policy version. Cache miss, expired, invalid, and outage states stop at non-grant. Expiration, revocation, and negative-cache controls govern entries. A low-risk read may use an explicitly bounded stale window, while administrative and financial operations require a fresh decision and indefinite stale allow is prohibited. A separate comparison shows signed policy configuration enabling fresh local evaluation while an old subject permit can preserve revoked privilege.",
  "narration": "Authorization caches reduce latency and dependency load, but a cached value is evidence only under a defined freshness policy. A cache miss, parse failure, expired entry, or cache outage does not establish allow. Replacing any of those states with a global default permit creates a fail-open fallback. The application must either obtain a trustworthy decision or stop the protected operation. Treat cache contents as security data: validate their structure and prevent untrusted writers from manufacturing decisions.\n\nCache keys should bind the subject, tenant, resource, action, relevant attributes, and policy version closely enough to prevent reuse across a different decision. Positive entries need explicit expiration, and sensitive systems may require revocation events, short lifetimes, or fresh evaluation for high-impact actions. Negative caching can reduce repeated work, but its lifetime also affects how quickly a newly granted permission becomes usable. Both directions involve correctness and availability.\n\nStale authorization is not universally forbidden, but it must be an explicit risk decision. A limited stale window may be acceptable for a low-risk read when policy infrastructure is unavailable. The same choice may be unacceptable for financial changes, administrator actions, or environments with strict revocation requirements. Bound the window, document which operations permit it, record when stale evidence was used, and never allow an indefinite stale permit.\n\nDistinguish last-known-good configuration from a last-known allow for one subject and resource. Stable signed policy configuration may let an in-process evaluator continue making fresh decisions. A cached permit can preserve privilege after membership or ownership has been revoked. Ask what evidence still justifies this exact action now. Improve authorization-service replication, local evaluation, cache availability, and operational recovery without quietly redefining dependency failure as permission.",
  "narrationPoints": [
    "Cache absence, expiry, invalid data, and outages are not authorization evidence.",
    "Bind decisions to subject, tenant, resource, action, attributes, and policy version.",
    "Treat bounded stale permits as documented security and availability tradeoffs.",
    "Configuration fallback differs from replaying a principal's old allow decision."
  ]
};
