window.COURSE_MODULE = {
  "title": "Preserve Fail-Secure Behavior Across Middleware and Service Layers",
  "graphicAlt": "Infographic of an Express-style middleware pipeline from authentication and context construction through awaited policy evaluation, explicit allow, next, and a protected service. Deny, indeterminate, and error branches return or throw before the allow gate. Crossed-out anti-patterns show calling next after denial, missing return, treating an unresolved promise as truthy, and double completion. REST, GraphQL, worker, scheduler, RPC, and administrative entry points all converge on a protected service requiring authorization context, trusted resource attributes, and operation-specific policy.",
  "narration": "Correct policy logic can still fail open through control flow. Express-style middleware may call next after reporting a denial, an early response may lack return, a promise may be started without await, or an error handler may resume a route unexpectedly. Structure the guard so every non-allow branch returns or throws and the only path to next is after a recognized allow. Avoid mixed callback and promise conventions that permit double completion.\n\nMissing await is especially dangerous because a Promise object is truthy. Code that tests an unresolved authorization promise can enter the protected branch before any decision exists. Enable lint rules for floating promises and make authorization APIs hard to misuse, but retain runtime tests around the actual call path. A compiler configuration or linter reduces mistakes; it does not replace the enforcement boundary. Ensure rejected promises and late callbacks cannot trigger a second continuation after the request has already entered an error path.\n\nDo not rely exclusively on a global route guard when authorization depends on the resource and action. Middleware can authenticate and establish common context. Object-specific authorization often belongs in or near the application service that has the trusted resource attributes and knows the side effect. Sensitive services should require AuthContext and an explicit command rather than accept an optional request object.\n\nTrace every entry point: REST routes, GraphQL resolvers, queue workers, scheduled processes, internal RPC, administrative tools, and background retries. A job may act with a service identity or on behalf of a user, but that authority must be explicit and scoped. Centralize reusable policy evaluation and failure translation while keeping operation-specific checks visible. Service reuse is safe only when alternate callers cannot bypass the authorization required by the underlying capability.",
  "narrationPoints": [
    "Make next or protected execution reachable only after explicit allow.",
    "Await every authorization decision; unresolved promises are truthy objects.",
    "Use middleware for common context and enforce resource policy near the operation.",
    "Cover every HTTP, RPC, worker, scheduler, and administrative entry point."
  ]
};
