window.COURSE_MODULE = {
  "title": "Test Failure Paths, Not Just Allow and Deny",
  "graphicAlt": "Infographic of a failure-path test matrix covering missing identity and tenant, malformed roles, database errors, policy timeout, invalid response, cache miss, expired entry, circuit-open state, and exceptions. Controlled clocks, fake policy, cache, and repository dependencies plus cancellation and late completion feed an authorization boundary that produces a non-grant result. A verification panel shows zero database, queue, file, audit-command, privileged-API, and background-job effects. Backward review highlights undefined-as-allow, missing return, unawaited checks, and unbounded stale permits, while observability keeps deny, timeout, invalid response, and stale evidence distinct.",
  "narration": "Authorization tests commonly prove that an approved user succeeds and a disallowed user receives denial. Fail-secure assurance adds a third family: the system cannot obtain a trustworthy decision. Exercise missing identity and tenant context, malformed role data, object lookup failure, database exceptions, policy timeouts, invalid response shapes, unknown decision values, cache misses, expired entries, circuit-open behavior, and thrown exceptions.\n\nFor each case, assert the absence of the protected side effect. An HTTP status alone is insufficient if a mutation occurred before the error surfaced. Verify database state, emitted messages, file changes, audit commands, and calls to privileged downstream APIs. For asynchronous flows, confirm background work was not queued and retries cannot execute with lost authorization context. Use controllable fakes for clocks, policy clients, caches, and repositories so failure timing remains deterministic. Also test cancellation and late policy completion so an abandoned request cannot resume into the protected branch.\n\nReview code from the side effect backward. Identify the exact branch that performs it, the value that exists before authorization, and every exception or return path that can reach that branch. Look for undefined or null interpreted as allow, permissive fallback constants, unawaited checks, missing returns, stale permits without limits, and secondary entry points that omit the policy. Test new enum values and malformed remote data so TypeScript assumptions do not mask runtime uncertainty.\n\nObserve denial and indeterminate separately. Metrics for policy latency, timeouts, validation failures, cache freshness, and dependency health support availability work without weakening authorization. Security logs should capture subject and resource references appropriate to the risk while avoiding tokens and unnecessary policy data. Alert on sustained evaluation failures and unexpected use of stale evidence. The operational response is to restore trustworthy decision-making, never to make access the emergency default.",
  "narrationPoints": [
    "Test indeterminate authorization as deliberately as allow and deny.",
    "Assert that every protected side effect remains absent on failure.",
    "Review backward from the sensitive branch through every control-flow path.",
    "Observe denial, timeout, invalid response, and stale evidence separately."
  ]
};
