window.COURSE_MODULE = {
  "title": "A01: Broken Access Control",
  "graphicAlt": "Graphic for A01: Broken Access Control",
  "narration": "Authorization failures happen when an application does not consistently verify whether a signed-in user can perform a specific action or access a specific record. Authentication proves identity, but authorization enforces what that identity may do. Privilege escalation can let a standard user perform administrative actions or view data belonging to another customer, department, or tenant.\n\nIn SaaS systems, this can quickly become a customer trust and SOC 2 concern. Insecure direct object references occur when identifiers such as account IDs, invoice IDs, file names, or project IDs are exposed without checking ownership or permission for the target object. Access control bypasses often appear in APIs, hidden routes, forced browsing, disabled client-side controls, or role values supplied by the browser.\n\nSensitive authorization decisions must be enforced on the server. Apply least privilege to users, services, and administrators. Enforce server-side authorization on every sensitive action and object.\n\nUse role-based access control with clear ownership and review processes. Selected SOC 2 mappings for this topic include CC6.1 - Logical access controls; CC6.2 - Authentication controls; CC6.3 - Authorization management.",
  "narrationPoints": [
    "Authorization failures happen when an application does not consistently verify whether a signed-in user can perform a specific action or access a specific record. Authentication proves identity, but authorization enforces what that identity may do. Privilege escalation can let a standard user perform administrative actions or view data belonging to another customer, department, or tenant.",
    "In SaaS systems, this can quickly become a customer trust and SOC 2 concern. Insecure direct object references occur when identifiers such as account IDs, invoice IDs, file names, or project IDs are exposed without checking ownership or permission for the target object. Access control bypasses often appear in APIs, hidden routes, forced browsing, disabled client-side controls, or role values supplied by the browser.",
    "Sensitive authorization decisions must be enforced on the server. Apply least privilege to users, services, and administrators. Enforce server-side authorization on every sensitive action and object.",
    "Use role-based access control with clear ownership and review processes. Selected SOC 2 mappings for this topic include CC6.1 - Logical access controls; CC6.2 - Authentication controls; CC6.3 - Authorization management."
  ]
};
