window.COURSE_MODULE = {
  "title": "A09: Security Logging and Monitoring Failures",
  "graphicAlt": "Graphic for A09: Security Logging and Monitoring Failures",
  "narration": "Missing audit logs leave teams unable to reconstruct important events. Applications should capture authentication activity, authorization failures, administrative actions, sensitive data access, configuration changes, and high-risk workflow events. Poor alerting creates noise without action or misses the events that matter most.\n\nAlerts should focus on anomalies, suspicious access, high-risk changes, and activity affecting sensitive data. Delayed incident detection increases attacker dwell time and impact. Without monitoring and review, compromise, insider abuse, and data access anomalies may continue unnoticed.\n\nIncomplete monitoring can also weaken SOC 2 readiness. Logs need retention, integrity, ownership, review procedures, and escalation paths that support investigation and evidence. Centralize logging from applications, identity systems, infrastructure, and cloud services.\n\nIntegrate telemetry with SIEM or monitoring workflows. Create security alerting and review processes for high-risk events. Selected SOC 2 mappings for this topic include CC7.2 - Monitoring activities; CC7.3 - Incident detection and response support.",
  "narrationPoints": [
    "Missing audit logs leave teams unable to reconstruct important events. Applications should capture authentication activity, authorization failures, administrative actions, sensitive data access, configuration changes, and high-risk workflow events. Poor alerting creates noise without action or misses the events that matter most.",
    "Alerts should focus on anomalies, suspicious access, high-risk changes, and activity affecting sensitive data. Delayed incident detection increases attacker dwell time and impact. Without monitoring and review, compromise, insider abuse, and data access anomalies may continue unnoticed.",
    "Incomplete monitoring can also weaken SOC 2 readiness. Logs need retention, integrity, ownership, review procedures, and escalation paths that support investigation and evidence. Centralize logging from applications, identity systems, infrastructure, and cloud services.",
    "Integrate telemetry with SIEM or monitoring workflows. Create security alerting and review processes for high-risk events. Selected SOC 2 mappings for this topic include CC7.2 - Monitoring activities; CC7.3 - Incident detection and response support."
  ]
};
