window.COURSE_MODULE = {
  "title": "A10: Server-Side Request Forgery",
  "graphicAlt": "Graphic for A10: Server-Side Request Forgery",
  "narration": "Internal network abuse occurs when a user-controlled URL or destination influences a server-side request. Features such as URL previews, webhook testing, file import, and document conversion can become SSRF entry points. Cloud metadata exploitation is a major SSRF scenario.\n\nIf a workload can reach metadata endpoints, attackers may attempt to obtain temporary credentials or environmental information. Trust boundary violations happen when applications treat user-supplied destinations as safe. URL validation, protocol restrictions, redirect handling, and DNS behavior need careful design.\n\nSSRF defenses work best when application validation is paired with network segmentation, egress filtering, infrastructure protections, and monitoring for unusual server-initiated traffic. Use network segmentation and infrastructure protections. Validate URLs and restrict destinations with allow lists where possible.\n\nApply egress filtering and monitor unusual outbound requests. Selected SOC 2 mappings for this topic include CC6.6 - Network security protections; CC7.1 - Threat and vulnerability management.",
  "narrationPoints": [
    "Internal network abuse occurs when a user-controlled URL or destination influences a server-side request. Features such as URL previews, webhook testing, file import, and document conversion can become SSRF entry points. Cloud metadata exploitation is a major SSRF scenario.",
    "If a workload can reach metadata endpoints, attackers may attempt to obtain temporary credentials or environmental information. Trust boundary violations happen when applications treat user-supplied destinations as safe. URL validation, protocol restrictions, redirect handling, and DNS behavior need careful design.",
    "SSRF defenses work best when application validation is paired with network segmentation, egress filtering, infrastructure protections, and monitoring for unusual server-initiated traffic. Use network segmentation and infrastructure protections. Validate URLs and restrict destinations with allow lists where possible.",
    "Apply egress filtering and monitor unusual outbound requests. Selected SOC 2 mappings for this topic include CC6.6 - Network security protections; CC7.1 - Threat and vulnerability management."
  ]
};
