window.COURSE_MODULE = {
  "title": "Dynamic SQL, Identifiers, and Stored Procedures",
  "graphicAlt": "A symbolic sort and direction enter a four-entry static map that supplies SQL fragments; a stored-procedure call binds values while dynamic procedure and identifier text remain blocked.",
  "narration": "Some applications need dynamic query behavior. Users may choose a report column, sort order, search field, date range, or optional filter. Administrators may configure dashboards or exports. These requirements are normal, but they should not give callers direct control over SQL structure. Parameterization protects data values; it does not turn arbitrary table names, column names, operators, or query fragments into safe structure.\n\nIdentifiers should be allowlisted or mapped. If a user selects a sort field, the application can map that choice to one of a fixed set of known internal column expressions. If a report supports several views, the application can choose among predefined query templates. If direction is configurable, it can be limited to a small known set. This pattern preserves functionality while keeping SQL structure under developer control.\n\nStored procedures require the same careful thinking. A stored procedure can centralize database behavior and enforce consistency, but it is not automatically safe. If the procedure builds dynamic SQL from parameters without constraints, the risk has moved into the database layer rather than disappeared. Teams should review stored procedures, database functions, and report builders with the same question they ask in Python: which parts are structure, which parts are values, and who controls them?\n\nSearch features, optional filters, and administrative tools are common places for dynamic SQL to grow gradually. A small reporting feature may start with one safe filter and later gain configurable fields, operators, grouping, and exports. Each added option should have an approved representation rather than raw user-controlled syntax. Dynamic SQL can be safe, but only when its design is explicit, constrained, and reviewed.",
  "narrationPoints": [
    "Users may choose a report column, sort order, search field, date range, or optional filter.",
    "If a report supports several views, the application can choose among predefined query templates.",
    "A stored procedure can centralize database behavior and enforce consistency, but it is not automatically safe.",
    "Search features, optional filters, and administrative tools are common places for dynamic SQL to grow gradually.",
    "Dynamic SQL can be safe, but only when its design is explicit, constrained, and reviewed.",
    "A small reporting feature may start with one safe filter and later gain configurable fields, operators, grouping, and exports."
  ]
};
