window.COURSE_MODULE = {
  "title": "Error Handling, Logging, and Data Exposure",
  "graphicAlt": "A database error rolls back and becomes an opaque application failure; logs keep a stable query identifier and driver category while SQL, parameters, credentials, and raw messages stay hidden.",
  "narration": "Safe error handling keeps database internals away from users while preserving enough detail for trusted operators and developers. Production responses should not expose detailed database errors, query text, connection strings, table names, credentials, stack traces, or sensitive values. A user can receive a controlled failure message and a correlation ID while logs capture the information needed for investigation under appropriate access controls.\n\nLogging can help teams detect problems, but database logs can also leak sensitive data. Query logging may include values, identifiers, tokens, credentials, personal data, or business-sensitive terms if it is enabled without care. Teams should decide what is logged, who can access those logs, how long they are retained, and whether sensitive fields are redacted. Debug behavior should be different from production behavior and should not accidentally follow a deployment into production.\n\nOperational visibility should include audit events and anomaly detection concepts. Unusual database access patterns, repeated query failures, unexpected report usage, large exports, permission denials, or changes to data-access code may all be worth monitoring depending on the application. Correlation IDs can connect user-facing errors to server logs without exposing internals to the caller. Good observability helps investigation without turning logs into another sensitive database.\n\nSecrets deserve special attention. Database credentials, connection strings, API tokens, and administrative passwords should not appear in error pages, logs, metrics, traces, or support exports. A secure Python application treats operational outputs as part of the data exposure surface. The goal is not silent failure. The goal is useful visibility with controlled disclosure, so teams can diagnose safely when database behavior goes wrong.",
  "narrationPoints": [
    "Safe error handling keeps database internals away from users while preserving enough detail for trusted operators and developers.",
    "Debug behavior should be different from production behavior and should not accidentally follow a deployment into production.",
    "Correlation IDs can connect user-facing errors to server logs without exposing internals to the caller.",
    "A secure Python application treats operational outputs as part of the data exposure surface.",
    "Logging can help teams detect problems, but database logs can also leak sensitive data.",
    "The goal is useful visibility with controlled disclosure, so teams can diagnose safely when database behavior goes wrong."
  ]
};
