window.COURSE_MODULE = {
  "title": "Why File Handling Safety Matters",
  "graphicAlt": "File-operation threat map connecting untrusted names, writable directories, symlinks, races, oversized content, partial writes, permissions, and cleanup failures to the validation and ownership controls that contain them.",
  "narration": "File handling is one of the most common ways a C++ program touches the outside world. A file path may come from a user, a configuration entry, a command line, a service workflow, another process, or an operating system component. Even when the path is internal, the file contents, metadata, permissions, and filesystem behavior can influence what the program does next.\n\nThat makes file handling both a reliability boundary and a security boundary. Unsafe handling can lead to data loss, accidental disclosure, corrupted state, unreliable processing, or access to files the application never intended to use. A program may read the wrong file, overwrite useful output, keep temporary data longer than expected, or trust malformed content because it came from a familiar directory.\n\nThe defensive goal is not to fear every file operation. The goal is to design file operations with clear trust boundaries and predictable behavior. The code should make it obvious which locations are allowed, which inputs are validated, which operations can create or overwrite data, and how failures are handled.\n\nSafe file handling is layered engineering. Path policy, content validation, least privilege, RAII cleanup, temporary file discipline, platform awareness, logging, tests, and review all support each other. No single library call proves a design is safe. A maintainable design makes file assumptions visible, narrow, and testable before they become production incidents.",
  "narrationPoints": [
    "A file path may come from a user, a configuration entry, a command line, a service workflow, another process, or an operating system component.",
    "Even when the path is internal, the file contents, metadata, permissions, and filesystem behavior can influence what the program does next.",
    "A program may read the wrong file, overwrite useful output, keep temporary data longer than expected, or trust malformed content because it came from a familiar directory.",
    "The code should make it obvious which locations are allowed, which inputs are validated, which operations can create or overwrite data, and how failures are handled.",
    "Path policy, content validation, least privilege, RAII cleanup, temporary file discipline, platform awareness, logging, tests, and review all support each other.",
    "A maintainable design makes file assumptions visible, narrow, and testable before they become production incidents."
  ]
};
