window.COURSE_MODULE = {
  "title": "A04: Insecure Design",
  "graphicAlt": "Graphic for A04: Insecure Design",
  "narration": "Missing threat modeling matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.\n\nWeak architectural decisions matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.\n\nUnsafe workflows matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.\n\nMissing abuse-case analysis matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines. Threat modeling Secure SDLC Security architecture reviews Selected ISO mappings for this topic include 8.\n\n25 - Secure development lifecycle; 5. 8 - Information security in project management; 5. 12 - Classification of information.",
  "narrationPoints": [
    "Missing threat modeling matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.",
    "Weak architectural decisions matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.",
    "Unsafe workflows matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.",
    "Missing abuse-case analysis matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines. Threat modeling Secure SDLC Security architecture reviews Selected ISO mappings for this topic include 8.",
    "25 - Secure development lifecycle; 5. 8 - Information security in project management; 5. 12 - Classification of information."
  ]
};
