window.COURSE_MODULE = {
  "title": "A06: Vulnerable and Outdated Components",
  "graphicAlt": "Graphic for A06: Vulnerable and Outdated Components",
  "narration": "Unsupported software matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.\n\nDependency management matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.\n\nVulnerable third-party libraries matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.\n\nSupply chain concerns matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines. Patch management Dependency scanning Software inventory tracking Selected ISO mappings for this topic include 8.\n\n8 - Management of technical vulnerabilities; 5. 21 - Managing information security in ICT supply chain.",
  "narrationPoints": [
    "Unsupported software matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.",
    "Dependency management matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.",
    "Vulnerable third-party libraries matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.",
    "Supply chain concerns matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines. Patch management Dependency scanning Software inventory tracking Selected ISO mappings for this topic include 8.",
    "8 - Management of technical vulnerabilities; 5. 21 - Managing information security in ICT supply chain."
  ]
};
