window.COURSE_MODULE = {
  "title": "A08: Software and Data Integrity Failures",
  "graphicAlt": "Graphic for A08: Software and Data Integrity Failures",
  "narration": "CI/CD compromise matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.\n\nUnsigned code matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.\n\nInsecure deserialization matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.\n\nBuild pipeline attacks matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines. Code signing Integrity verification Secure CI/CD controls Selected ISO mappings for this topic include 8. 28 - Secure coding; 8.\n\n29 - Security testing; 5. 21 - ICT supply chain security.",
  "narrationPoints": [
    "CI/CD compromise matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.",
    "Unsigned code matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.",
    "Insecure deserialization matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines.",
    "Build pipeline attacks matters because applications often enforce access, process sensitive information, connect to business systems, and create operational evidence. Teams should evaluate this issue across user-facing features, APIs, administrative tools, cloud services, and delivery pipelines. Code signing Integrity verification Secure CI/CD controls Selected ISO mappings for this topic include 8. 28 - Secure coding; 8.",
    "29 - Security testing; 5. 21 - ICT supply chain security."
  ]
};
