window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Input Validation and Query Shape Control' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Parse an exact invoice-search command",
      "language": "csharp",
      "blurb": "The parser caps the UTF-8 document and depth, rejects comments, trailing commas, duplicate or unknown members, requires primitive types, and validates a closed state plus a coherent nonnegative amount range.",
      "code": "using System.Text.Json;\n\npublic sealed class InvoiceSearchCriteria\n{\n    private InvoiceSearchCriteria(string state, long minimumCents, long maximumCents)\n    {\n        State = state;\n        MinimumCents = minimumCents;\n        MaximumCents = maximumCents;\n    }\n\n    public string State { get; }\n    public long MinimumCents { get; }\n    public long MaximumCents { get; }\n\n    public static InvoiceSearchCriteria Parse(ReadOnlyMemory<byte> utf8Json)\n    {\n        if (utf8Json.Length is 0 or > 4 * 1024)\n            throw new JsonException(\"Invoice search size rejected.\");\n        using var document = JsonDocument.Parse(utf8Json, new JsonDocumentOptions\n        {\n            AllowTrailingCommas = false,\n            CommentHandling = JsonCommentHandling.Disallow,\n            MaxDepth = 2\n        });\n        if (document.RootElement.ValueKind != JsonValueKind.Object)\n            throw new JsonException(\"Invoice search must be an object.\");\n        string? state = null;\n        long? minimum = null;\n        long? maximum = null;\n        var names = new HashSet<string>(StringComparer.Ordinal);\n        foreach (var property in document.RootElement.EnumerateObject())\n        {\n            if (!names.Add(property.Name)) throw new JsonException(\"Duplicate member rejected.\");\n            switch (property.Name)\n            {\n                case \"state\" when property.Value.ValueKind == JsonValueKind.String:\n                    state = property.Value.GetString();\n                    break;\n                case \"minimumCents\" when property.Value.TryGetInt64(out var min):\n                    minimum = min;\n                    break;\n                case \"maximumCents\" when property.Value.TryGetInt64(out var max):\n                    maximum = max;\n                    break;\n                case \"state\" or \"minimumCents\" or \"maximumCents\":\n                    throw new JsonException(\"Invoice search member type rejected.\");\n                default:\n                    throw new JsonException(\"Unknown invoice search member rejected.\");\n            }\n        }\n        if (state is not (\"pending\" or \"paid\" or \"voided\") ||\n            minimum is null or < 0 || maximum is null or < 0 ||\n            minimum > maximum || maximum > 1_000_000_000_00L)\n        {\n            throw new JsonException(\"Invoice search values rejected.\");\n        }\n        return new InvoiceSearchCriteria(state, minimum.Value, maximum.Value);\n    }\n}\n"
    },
    {
      "title": "Apply validated search values without dynamic SQL",
      "language": "csharp",
      "blurb": "The query accepts only the already validated criteria object, snapshots tenant and cursor primitives, filters by fixed properties, orders by a stable composite cursor, projects minimal fields, and enforces an application page ceiling.",
      "code": "public sealed record SearchableInvoice(\n    string Id,\n    string TenantId,\n    string State,\n    long TotalCents,\n    DateTimeOffset CreatedUtc,\n    long Sequence);\n\npublic sealed record InvoiceSearchItem(string Id, long TotalCents, DateTimeOffset CreatedUtc);\n\npublic sealed class ValidatedInvoiceFilter\n{\n    private ValidatedInvoiceFilter(string state, long minimumCents, long maximumCents)\n    {\n        State = state;\n        MinimumCents = minimumCents;\n        MaximumCents = maximumCents;\n    }\n\n    public string State { get; }\n    public long MinimumCents { get; }\n    public long MaximumCents { get; }\n\n    public static ValidatedInvoiceFilter Create(\n        string state,\n        long minimumCents,\n        long maximumCents)\n    {\n        if (state is not (\"pending\" or \"paid\" or \"voided\") ||\n            minimumCents < 0 || maximumCents < minimumCents ||\n            maximumCents > 1_000_000_000_00L)\n        {\n            throw new ArgumentException(\"Invoice filter rejected.\");\n        }\n        return new ValidatedInvoiceFilter(state, minimumCents, maximumCents);\n    }\n}\n\npublic static class ValidatedInvoiceSearch\n{\n    public static IQueryable<InvoiceSearchItem> Apply(\n        IQueryable<SearchableInvoice> invoices,\n        string tenantId,\n        ValidatedInvoiceFilter criteria,\n        DateTimeOffset afterCreatedUtc,\n        long afterSequence,\n        int take)\n    {\n        ArgumentNullException.ThrowIfNull(invoices);\n        ArgumentNullException.ThrowIfNull(criteria);\n        if (!IsIdentifier(tenantId) || afterSequence < 0 || take is < 1 or > 100)\n            throw new ArgumentException(\"Invoice page rejected.\");\n        var state = criteria.State;\n        var minimum = criteria.MinimumCents;\n        var maximum = criteria.MaximumCents;\n        return invoices\n            .Where(invoice => invoice.TenantId == tenantId && invoice.State == state &&\n                invoice.TotalCents >= minimum && invoice.TotalCents <= maximum &&\n                (invoice.CreatedUtc > afterCreatedUtc ||\n                 (invoice.CreatedUtc == afterCreatedUtc && invoice.Sequence > afterSequence)))\n            .OrderBy(invoice => invoice.CreatedUtc)\n            .ThenBy(invoice => invoice.Sequence)\n            .Select(invoice => new InvoiceSearchItem(\n                invoice.Id, invoice.TotalCents, invoice.CreatedUtc))\n            .Take(take);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    }
  ]
};
