window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Error Handling, Logging, and Detection Signals' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Emit a bounded low-cardinality SQL diagnostic",
      "language": "csharp",
      "blurb": "The event accepts only closed operation and outcome enums, validated tenant and correlation identifiers, finite bounded duration and row counts, and deliberately omits statements, parameters, connection strings, and exception text.",
      "code": "public enum SqlOperation { OrderLookup, InvoiceSearch, OrderTransition }\npublic enum SqlOutcome { Succeeded, NotFound, Conflict, TimedOut, Failed }\n\npublic sealed class SqlDiagnosticEvent\n{\n    private SqlDiagnosticEvent(\n        SqlOperation operation,\n        SqlOutcome outcome,\n        string tenantId,\n        string correlationId,\n        int durationBucketMilliseconds,\n        int rowCount)\n    {\n        Operation = operation;\n        Outcome = outcome;\n        TenantId = tenantId;\n        CorrelationId = correlationId;\n        DurationBucketMilliseconds = durationBucketMilliseconds;\n        RowCount = rowCount;\n    }\n\n    public SqlOperation Operation { get; }\n    public SqlOutcome Outcome { get; }\n    public string TenantId { get; }\n    public string CorrelationId { get; }\n    public int DurationBucketMilliseconds { get; }\n    public int RowCount { get; }\n\n    public static SqlDiagnosticEvent Create(\n        SqlOperation operation,\n        SqlOutcome outcome,\n        string tenantId,\n        string correlationId,\n        TimeSpan elapsed,\n        int rowCount)\n    {\n        if (!Enum.IsDefined(operation) || !Enum.IsDefined(outcome) ||\n            !IsIdentifier(tenantId, 1) || !IsIdentifier(correlationId, 8) ||\n            elapsed < TimeSpan.Zero || elapsed > TimeSpan.FromMinutes(1) ||\n            rowCount is < 0 or > 10_000)\n        {\n            throw new ArgumentException(\"SQL diagnostic rejected.\");\n        }\n        var bucket = elapsed <= TimeSpan.FromMilliseconds(10) ? 10 :\n            elapsed <= TimeSpan.FromMilliseconds(100) ? 100 :\n            elapsed <= TimeSpan.FromSeconds(1) ? 1_000 : 60_000;\n        return new SqlDiagnosticEvent(\n            operation, outcome, tenantId, correlationId, bucket, rowCount);\n    }\n\n    private static bool IsIdentifier(string value, int minimum) =>\n        !string.IsNullOrEmpty(value) && value.Length >= minimum && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    },
    {
      "title": "Map database failures without exposing SQL details",
      "language": "csharp",
      "blurb": "A trusted provider adapter first classifies the database result into a closed category; the public mapper then returns fixed status, code, and retry guidance without reflecting SQL text, parameters, schema names, or provider exception messages.",
      "code": "public enum SqlFailureKind { NotFound, Conflict, Timeout, Unavailable, Internal }\n\npublic sealed record PublicSqlFailure(int StatusCode, string Code, bool Retryable);\n\npublic static class SqlFailureResponse\n{\n    public static PublicSqlFailure Map(SqlFailureKind kind)\n    {\n        if (!Enum.IsDefined(kind)) throw new ArgumentOutOfRangeException(nameof(kind));\n        return kind switch\n        {\n            SqlFailureKind.NotFound => new PublicSqlFailure(404, \"not_found\", false),\n            SqlFailureKind.Conflict => new PublicSqlFailure(409, \"conflict\", false),\n            SqlFailureKind.Timeout => new PublicSqlFailure(503, \"database_timeout\", true),\n            SqlFailureKind.Unavailable => new PublicSqlFailure(503, \"database_unavailable\", true),\n            SqlFailureKind.Internal => new PublicSqlFailure(500, \"internal_error\", false),\n            _ => throw new ArgumentOutOfRangeException(nameof(kind))\n        };\n    }\n}\n"
    }
  ]
};
