window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Stored Procedures, Dynamic SQL, and Database Boundaries' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Call one stored procedure through a closed contract",
      "language": "csharp",
      "blurb": "The boundary fixes the procedure name and command type, validates tenant, order, and transition values, binds each parameter with an explicit size, applies a short timeout, and disposes incomplete commands if provider setup fails.",
      "code": "using System.Data;\nusing System.Data.Common;\n\npublic static class AdvanceOrderStoredProcedure\n{\n    public static DbCommand Create(\n        DbConnection connection,\n        string tenantId,\n        string orderId,\n        string nextState)\n    {\n        ArgumentNullException.ThrowIfNull(connection);\n        if (!IsIdentifier(tenantId) || !IsIdentifier(orderId) ||\n            nextState is not (\"paid\" or \"shipped\" or \"cancelled\"))\n        {\n            throw new ArgumentException(\"Order transition rejected.\");\n        }\n        var command = connection.CreateCommand();\n        try\n        {\n            command.CommandType = CommandType.StoredProcedure;\n            command.CommandText = \"orders_advance_state\";\n            command.CommandTimeout = 5;\n            Add(command, \"tenant_id\", tenantId, 64);\n            Add(command, \"order_id\", orderId, 64);\n            Add(command, \"next_state\", nextState, 16);\n            return command;\n        }\n        catch (Exception operationError)\n        {\n            try\n            {\n                command.Dispose();\n            }\n            catch (Exception cleanupError)\n            {\n                throw new AggregateException(\n                    \"Command construction and cleanup both failed.\",\n                    operationError,\n                    cleanupError);\n            }\n            throw;\n        }\n    }\n\n    private static void Add(DbCommand command, string name, string value, int size)\n    {\n        var parameter = command.CreateParameter();\n        parameter.ParameterName = name;\n        parameter.DbType = DbType.String;\n        parameter.Size = size;\n        parameter.Value = value;\n        command.Parameters.Add(parameter);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    },
    {
      "title": "Select dynamic report shape from closed enums",
      "language": "csharp",
      "blurb": "Only application-defined dimension and ordering enums can select SQL literals; tenant and date values remain typed parameters. Invalid future enum representations fail before a command is allocated.",
      "code": "using System.Data;\nusing System.Data.Common;\n\npublic enum RevenueDimension { Currency, Region }\npublic enum RevenueOrder { HighestFirst, LowestFirst }\n\npublic static class RevenueReportCommand\n{\n    public static DbCommand Create(\n        DbConnection connection,\n        string tenantId,\n        DateTimeOffset fromUtc,\n        DateTimeOffset untilUtc,\n        RevenueDimension dimension,\n        RevenueOrder order)\n    {\n        ArgumentNullException.ThrowIfNull(connection);\n        if (!IsIdentifier(tenantId) || fromUtc >= untilUtc ||\n            untilUtc - fromUtc > TimeSpan.FromDays(31) ||\n            !Enum.IsDefined(dimension) || !Enum.IsDefined(order))\n        {\n            throw new ArgumentException(\"Revenue report rejected.\");\n        }\n        var column = dimension == RevenueDimension.Currency ? \"Currency\" : \"Region\";\n        var direction = order == RevenueOrder.HighestFirst ? \"DESC\" : \"ASC\";\n        var command = connection.CreateCommand();\n        try\n        {\n            command.CommandText =\n                $\"SELECT {column}, SUM(TotalCents) AS TotalCents FROM Orders \" +\n                $\"WHERE TenantId = @tenant AND CreatedUtc >= @from AND CreatedUtc < @until \" +\n                $\"GROUP BY {column} ORDER BY TotalCents {direction}\";\n            command.CommandTimeout = 5;\n            Add(command, \"@tenant\", DbType.String, tenantId, 64);\n            Add(command, \"@from\", DbType.DateTimeOffset, fromUtc);\n            Add(command, \"@until\", DbType.DateTimeOffset, untilUtc);\n            return command;\n        }\n        catch (Exception operationError)\n        {\n            try\n            {\n                command.Dispose();\n            }\n            catch (Exception cleanupError)\n            {\n                throw new AggregateException(\n                    \"Command construction and cleanup both failed.\",\n                    operationError,\n                    cleanupError);\n            }\n            throw;\n        }\n    }\n\n    private static void Add(\n        DbCommand command,\n        string name,\n        DbType type,\n        object value,\n        int? size = null)\n    {\n        var parameter = command.CreateParameter();\n        parameter.ParameterName = name;\n        parameter.DbType = type;\n        parameter.Value = value;\n        if (size is int length) parameter.Size = length;\n        command.Parameters.Add(parameter);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    }
  ]
};
