window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Least Privilege, Secrets, and Database Configuration' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Admit one exact least-privilege SQL role",
      "language": "csharp",
      "blurb": "The factory requires a duplicate-free exact permission set for the runtime role and rejects extra or missing privileges, including ownership, schema changes, impersonation, replication, and future unknown names.",
      "code": "using System.Collections.ObjectModel;\n\npublic sealed class SqlRuntimeRole\n{\n    private static readonly HashSet<string> Required =\n        new([\"CONNECT\", \"SELECT\", \"EXECUTE\"], StringComparer.Ordinal);\n    private readonly ReadOnlyCollection<string> _permissions;\n\n    private SqlRuntimeRole(string name, string[] permissions)\n    {\n        Name = name;\n        _permissions = Array.AsReadOnly(permissions);\n    }\n\n    public string Name { get; }\n    public IReadOnlyList<string> Permissions => _permissions;\n\n    public static SqlRuntimeRole Create(string name, IEnumerable<string> permissions)\n    {\n        ArgumentNullException.ThrowIfNull(permissions);\n        if (!IsIdentifier(name)) throw new ArgumentException(\"Role name rejected.\", nameof(name));\n        var snapshot = permissions.Take(4).ToArray();\n        if (snapshot.Length != Required.Count ||\n            snapshot.Any(permission => string.IsNullOrEmpty(permission) || permission.Length > 32) ||\n            snapshot.Distinct(StringComparer.Ordinal).Count() != snapshot.Length ||\n            !Required.SetEquals(snapshot))\n        {\n            throw new ArgumentException(\"Runtime SQL permissions rejected.\", nameof(permissions));\n        }\n        Array.Sort(snapshot, StringComparer.Ordinal);\n        return new SqlRuntimeRole(name, snapshot);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    },
    {
      "title": "Keep topology and credential references separate",
      "language": "csharp",
      "blurb": "The configuration admits one reviewed database origin and name, requires transport encryption without trusting a server certificate, parses only a canonical versioned vault reference, and never accepts a raw password or full connection string.",
      "code": "using System.Globalization;\n\npublic sealed class SqlRuntimeConfiguration\n{\n    private SqlRuntimeConfiguration(\n        string host,\n        string database,\n        string credentialReference,\n        int credentialVersion,\n        bool encrypt,\n        bool trustServerCertificate)\n    {\n        Host = host;\n        Database = database;\n        CredentialReference = credentialReference;\n        CredentialVersion = credentialVersion;\n        Encrypt = encrypt;\n        TrustServerCertificate = trustServerCertificate;\n    }\n\n    public string Host { get; }\n    public string Database { get; }\n    public string CredentialReference { get; }\n    public int CredentialVersion { get; }\n    public bool Encrypt { get; }\n    public bool TrustServerCertificate { get; }\n\n    public static SqlRuntimeConfiguration Create(\n        string host,\n        string database,\n        string credentialReference,\n        bool encrypt,\n        bool trustServerCertificate)\n    {\n        const string prefix = \"vault://orders/sql-runtime/v\";\n        if (!string.Equals(host, \"orders-db.internal.example\", StringComparison.Ordinal) ||\n            !string.Equals(database, \"Orders\", StringComparison.Ordinal) || !encrypt ||\n            trustServerCertificate || credentialReference is null ||\n            !credentialReference.StartsWith(prefix, StringComparison.Ordinal) ||\n            !int.TryParse(\n                credentialReference.AsSpan(prefix.Length),\n                NumberStyles.None,\n                CultureInfo.InvariantCulture,\n                out var version) ||\n            version is < 1 or > 1_000_000 ||\n            !string.Equals(\n                credentialReference,\n                prefix + version.ToString(CultureInfo.InvariantCulture),\n                StringComparison.Ordinal))\n        {\n            throw new ArgumentException(\"Runtime database configuration rejected.\");\n        }\n        return new SqlRuntimeConfiguration(\n            host, database, credentialReference, version, encrypt, trustServerCertificate);\n    }\n}\n"
    }
  ]
};
