window.COURSE_MODULE = {
  "title": "SQL Injection Risk in .NET Applications",
  "graphicAlt": "Bullet summary graphic for SQL Injection Risk in .NET Applications.",
  "narration": "SQL injection prevention in .NET starts with a simple defensive idea: data supplied to an application must stay data when it reaches the database boundary. The risk appears when query construction allows input values, report filters, search terms, customer identifiers, order statuses, or date ranges to be interpreted as part of the database instruction itself.\n\nThe primary prevention strategy is safe query construction, not trying to identify every suspicious string. Blocking a few characters or replacing text is fragile because business data changes, database syntax varies, and applications reuse values in many contexts. The stronger pattern is to keep command text and parameter values separate through provider-supported APIs.\n\n.NET applications reach databases in many ways. A team may use ADO.NET command objects, Entity Framework Core, Dapper or another micro-ORM, stored procedures, reporting components, background jobs, import tools, administrative utilities, or migration scripts. SQL injection prevention has to cover all of those paths, not only the most visible web endpoint.\n\nInjection prevention is part of ordinary engineering. Code review should notice query construction. Tests should cover risky data-access paths. Maintenance should include dependency review and legacy remediation. Teams should document approved patterns so new features do not reintroduce unsafe construction after the initial cleanup.\n\nDefense is layered. Parameterized access prevents the central problem. Least privilege reduces blast radius if an application path behaves unexpectedly. Safe error handling prevents database details from reaching users. Logging and monitoring help operators see unusual validation failures, repeated database errors, or administrative activity that deserves review.",
  "narrationPoints": [
    "SQL injection prevention in .NET starts with a simple defensive idea: data supplied to an application must stay data when it reaches the database boundary.",
    "The primary prevention strategy is safe query construction, not trying to identify every suspicious string.",
    "SQL injection prevention has to cover all of those paths, not only the most visible web endpoint.",
    "Teams should document approved patterns so new features do not reintroduce unsafe construction after the initial cleanup.",
    "Logging and monitoring help operators see unusual validation failures, repeated database errors, or administrative activity that deserves review."
  ]
};
