window.COURSE_MODULE = {
  "title": "Entity Framework Core Safe Patterns and Pitfalls",
  "graphicAlt": "Bullet summary graphic for Entity Framework Core Safe Patterns and Pitfalls.",
  "narration": "Entity Framework Core helps reduce injection risk when developers use LINQ and parameterized APIs as intended. In common query patterns, EF Core translates expression trees and values into provider-supported database operations. That is a strong baseline for many applications, especially compared with handwritten command text assembled from request values.\n\nEF Core does not remove the need for authorization, validation, data shaping, and review. A query can be safely parameterized and still return records the caller should not see. A model can be mapped correctly and still expose too many fields. A filter can be syntactically safe and still allow an inappropriate business operation. Injection prevention is necessary, but not the whole data-access security story.\n\nRaw SQL features are higher-review areas. EF Core supports raw SQL for legitimate reasons such as performance, provider-specific capabilities, or complex queries, but those features should preserve parameterization and keep variable data out of command structure. A raw SQL path should have a clear reason, an owner, and review proportional to the data it touches.\n\nDynamic filtering, sorting, and projection require careful design. Callers should not provide arbitrary field names, query fragments, or projection rules. Instead, the application should map supported sort fields, filters, report columns, and views to approved internal query shapes. This preserves flexibility for clients while keeping SQL structure under application control.\n\nSeparating API boundary models from persistence models can improve safety. Request DTOs should express what the caller is allowed to provide. Response DTOs should express what the caller is allowed to receive. Database entities often contain relationships, audit fields, internal flags, or operational data that should not become external contract by accident.\n\nPerformance-driven query changes deserve security review. Optimization work may introduce raw SQL, broader projections, caching, denormalized views, or reporting shortcuts. Those changes can be valuable, but they should still preserve parameterization, authorization filters, data minimization, and tenant boundaries.",
  "narrationPoints": [
    "In common query patterns, EF Core translates expression trees and values into provider-supported database operations.",
    "EF Core does not remove the need for authorization, validation, data shaping, and review.",
    "A raw SQL path should have a clear reason, an owner, and review proportional to the data it touches.",
    "Instead, the application should map supported sort fields, filters, report columns, and views to approved internal query shapes.",
    "Response DTOs should express what the caller is allowed to receive."
  ]
};
