window.COURSE_MODULE = {
  "title": "Keep Executable Selection Under Application Control",
  "graphicAlt": "Convert, inspect, and compile operation keys map to approved programs through a closed tool map, while unknown choices are rejected. Executable ownership and installation location are verified, a missing program fails closed, and silent PATH fallback is discouraged. Script, plugin, and configuration inputs also pass approval locks before reaching an interpreter.",
  "narration": "An argument array provides little protection if the request can choose which program receives it. Executable selection should come from application code or trusted deployment configuration. When an endpoint supports several operations, accept a logical operation key and map it to a closed set of approved tools. Reject unknown keys. This expresses the actual product capability and prevents a client from turning one endpoint into a launcher for every installed utility.\n\nA known absolute executable path is often the clearest choice for a security-sensitive service because it avoids ambiguous PATH lookup. A bare program name may resolve differently across development machines, containers, service accounts, and production hosts. Search order can be affected by environment variables and platform rules, and an unexpected binary with the same name may be found first. Absolute paths are not universally required, but the deployment must define and protect whatever resolution mechanism it uses.\n\nDo not validate arbitrary executable strings by checking their characters or extension. A syntactically ordinary path can still identify an unauthorized program. Instead, configure approved paths outside request data, verify deployment ownership and permissions, and map supported operations to those values. If portability requires platform-specific locations, select them from trusted configuration at startup and fail closed when the configured executable is missing or outside the expected installation. Avoid falling back silently to a PATH search.\n\nExecutable trust also includes interpreters and wrappers. Launching a trusted runtime with a request-selected script merely moves executable selection into an argument. Package scripts, plugins, and configuration files can carry equivalent power. Review every input that determines what code the child loads, not only the first process argument. A narrow launcher binds one operation to one approved program and a defined argument grammar, making both security review and deployment verification tractable.",
  "narrationPoints": [
    "Map logical operations to approved executable paths.",
    "Understand and control PATH and platform-specific resolution behavior.",
    "Do not accept arbitrary executable names that merely look syntactically safe.",
    "Treat scripts, plugins, and interpreter inputs as code-selection mechanisms."
  ]
};
