window.COURSE_MODULE = {
  "title": "Control Paths, Environment, and Working Directory",
  "graphicAlt": "Three panels control the process context: file identifiers resolve into approved directories with private temporary storage and checks for links and replacement races; a trusted working directory is inspected for automatic configuration discovery; and a selective environment filter retains required variables while excluding unnecessary secrets. All three feed the child process, and secrets are kept out of command-line arguments.",
  "narration": "A process can be launched with a fixed executable and safe argument boundaries while remaining exposed through its surrounding context. File paths determine what the utility reads and writes. The current working directory can affect relative paths and automatic discovery of configuration, plugins, or scripts. Environment variables can change executable search, language runtimes, credentials, proxy behavior, and tool configuration. Treat all three as explicit launch inputs.\n\nPrefer server-side identifiers that map to controlled files over arbitrary paths submitted by clients. Place inputs and outputs beneath approved directories with application-generated names and appropriate permissions. When joining a relative name to a base directory, normalize and verify containment using platform-aware path operations; a substring check for two dots is not sufficient. Consider symbolic links, junctions, replacement races, and how the target utility follows them. For sensitive workflows, create private temporary locations and maintain ownership of opened files rather than relying only on a preflight path check.\n\nSet the working directory to a known application-controlled location. Do not let request data choose it, and do not assume the web service's startup directory is stable. Review the utility for implicit configuration lookup in that directory and in parent or user-home locations. An absolute input path does not neutralize a hostile working directory when the tool also discovers plugins or configuration relative to it.\n\nMinimize the child environment to the variables it needs instead of blindly forwarding every secret in process.env. Preserve platform variables genuinely required for correct process startup, but select them deliberately and source their values from trusted deployment configuration. Give credentials only to the operation that needs them, and avoid placing secrets in command-line arguments where operating-system process listings or logs may expose them. Explicit paths, a controlled working directory, and a purpose-built environment improve security and make behavior reproducible across hosts.",
  "narrationPoints": [
    "Map storage identifiers to controlled server-side paths.",
    "Use platform-aware containment checks and account for links and replacement races.",
    "Set a trusted working directory and review implicit configuration discovery.",
    "Build a minimal child environment without unnecessary parent-process secrets."
  ]
};
