window.COURSE_MODULE = {
  "title": "Limit Privilege, Resources, and Process Lifetime",
  "graphicAlt": "A before-during-after process diagram combines input limits, a concurrency cap, least privilege, and explicit isolation policy with asynchronous execution, a deadline, and capped buffered or streamed output. At exit, a process tree warns that terminating one child may not stop descendants, and temporary-file cleanup covers success, failure, and cancellation.",
  "narration": "A well-structured launch still starts code with real capabilities. By default, the child commonly inherits the service's operating-system identity, accessible filesystem, network position, selected environment, and configured standard streams. If the parent runs with broad permissions, a defect in the utility or an overly powerful option can have broad consequences. Use the least practical privilege for the service and, where risk warrants it, isolate the operation with a dedicated account, constrained filesystem access, or an existing sandbox or container boundary. Isolation must have an explicit policy; a container label alone is not a permission model.\n\nBound the work before launch. Validate file size, dimensions, duration, page count, or other cost indicators relevant to the utility. Limit concurrent children so request bursts cannot exhaust processes, memory, CPU, file descriptors, or temporary storage. Place quotas at a shared server boundary rather than only in one handler instance. Authorization and rate limits should reflect that an external processor may be substantially more expensive than an ordinary API call.\n\nUse asynchronous process APIs in request-handling paths so the Node.js event loop can continue serving other work. Synchronous variants block the event loop until the child exits and require a deliberate, bounded use case. Choose output handling intentionally. Exec-style APIs buffer stdout and stderr and enforce a maximum buffer; understand that limit and treat overflow as failure. Spawn can stream output, but the application must apply backpressure, byte caps, and safe destinations rather than accumulating unbounded data in memory or logs.\n\nDefine a deadline with a timeout or AbortSignal and handle cancellation, exit codes, signals, and partial output. Terminating the direct child may not always stop descendants created by wrappers or shells, so test process-tree behavior on supported platforms and use stronger job or isolation controls when necessary. Clean up temporary files on success, failure, and cancellation. Timeouts, output bounds, and concurrency controls do not prevent injection; they contain denial-of-service and operational risk after a permitted process has started.",
  "narrationPoints": [
    "Run the service and child with the least practical operating-system access.",
    "Bound input cost and concurrent child-process count before launch.",
    "Prefer asynchronous APIs and deliberately cap buffered or streamed output.",
    "Test cancellation and process-tree cleanup on every supported platform."
  ]
};
