window.COURSE_MODULE = {
  "title": "Course Summary: Make Process Execution Narrow and Explicit",
  "graphicAlt": "A requested capability uses an in-process library when suitable or enters a restricted execution service when an external process is needed. The service validates and authorizes input, chooses an approved tool, fixes the argument layout, controls context, and bounds the run. Arbitrary commands are blocked, while direct execution, target rules, testing, and process-tree cleanup support the design.",
  "narration": "Begin by avoiding an external process when a suitable in-process library can provide the capability with a smaller boundary. When a child process is necessary, define a narrow application operation. Select the executable from trusted configuration or a closed map, prefer direct execution, and keep shell-enabled behavior rare and explicitly reviewed. The application owns the argument array; clients supply only validated and authorized values for designated operands.\n\nDirect execution and argument separation remove shell parsing, but they do not authorize an argument. Understand the target program's grammar, map formats and modes to approved values, handle option-prefixed operands as the utility documents, and never forward a client-supplied argument list. TypeScript types help maintain the internal model but do not validate runtime request data. Executable control, input validation, and target-program option control are related but separate responsibilities.\n\nTreat process context as part of the operation. Map storage identifiers to controlled paths, use private temporary locations, set a trusted working directory, and provide a minimal environment with only required variables. Run with the least practical access. Bound input size, execution time, concurrency, output, and temporary storage. Prefer asynchronous APIs in request paths, handle every exit and cancellation outcome, and test cleanup and descendant-process behavior on supported platforms.\n\nFinally, centralize launches behind small purpose-specific interfaces, inventory every escape hatch, and test the exact executable, arguments, options, and failure paths. Shell-injection prevention, least privilege, and resource control solve different problems and belong together. A secure process launch exposes a small application-defined operation, not a general-purpose command interface. That principle remains useful across Node.js APIs, operating systems, external tools, and future implementation changes.",
  "narrationPoints": [
    "Avoid external processes when an in-process library reasonably fits.",
    "Fix executable and argument structure; validate only narrow variable operands.",
    "Control paths, environment, directory, privilege, lifetime, and output.",
    "Expose purpose-specific operations instead of arbitrary commands."
  ]
};
