window.COURSE_MODULE = {
  "title": "What Prompt Injection Defense Means",
  "graphicAlt": "Blank placeholder image for a lesson introducing prompt injection defenses in Python.",
  "narration": "Prompt injection defense is the discipline of building AI applications so untrusted natural-language content cannot quietly take control of the system. In a Python application, prompts may come from users, documents, tickets, web pages, messages, code repositories, tool outputs, or retrieval systems. Some of that content can look like instructions, but the application must decide what authority it actually has. Defense begins with treating language as input, not as policy.\n\nPrompt injection is different from an ordinary user instruction, a model error, a hallucination, or a pure access-control failure. A normal user instruction expresses the user's goal. A hallucination is an incorrect or unsupported model response. An access-control failure occurs when the application exposes or modifies something without proper permission. Prompt injection is the risk that untrusted content changes model behavior in a way the application did not intend, especially when the output affects data, tools, decisions, or workflows.\n\nDirect prompt injection comes from content the user intentionally enters into the AI interface. Indirect prompt injection comes from content the system later reads, retrieves, summarizes, or processes, such as documents, emails, web pages, PDFs, support tickets, code comments, logs, or knowledge-base articles. The defensive pattern is the same at a high level: understand where content came from, what authority it has, what it is allowed to influence, and what controls must be enforced outside the model.\n\nPrompt injection defense is application security, not only prompt writing. Clear prompts help guide behavior, but they do not reliably enforce authorization, tenant boundaries, data access, tool permissions, or high-impact approvals. Python code, identity systems, retrieval filters, tool wrappers, output validators, logs, tests, and monitoring all participate in the defense. The model can assist the workflow, but the application must remain in charge of security decisions.",
  "narrationPoints": [
    "Prompt injection defense is the discipline of building AI applications so untrusted natural-language content cannot quietly take control of the system.",
    "In a Python application, prompts may come from users, documents, tickets, web pages, messages, code repositories, tool outputs, or retrieval systems.",
    "Some of that content can look like instructions, but the application must decide what authority it actually has.",
    "Defense begins with treating language as input, not as policy.",
    "Prompt injection is different from an ordinary user instruction, a model error, a hallucination, or a pure access-control failure.",
    "A normal user instruction expresses the user's goal."
  ]
};
