window.COURSE_MODULE = {
  "title": "Safe User-Facing Error Messages",
  "graphicAlt": "Layered architecture diagram for Safe User-Facing Error Messages, showing request handler, exception mapper, safe response, protected diagnostic log, and correlation identifier; labeled arrows identify public and internal error paths and the point where unsafe input or behavior is rejected.",
  "narration": "User-facing error messages should be clear enough to support legitimate recovery and limited enough to avoid exposing internal detail. A message can say that a request could not be completed, that input needs correction, that access is not available, or that support should be contacted with a request identifier. It usually should not include raw exception strings, stack traces, connection strings, file paths, internal object names, table names, secret values, or full downstream service messages.\n\nSensitive operations often need generic wording. Login, password reset, account recovery, invitation, token refresh, and access-denied flows can reveal more than intended if they say too much. At a high level, wording that distinguishes nonexistent users, wrong passwords, missing factors, disabled accounts, or tenant membership can support enumeration. The safe approach is to help legitimate users proceed without teaching outsiders how identity and authorization decisions are structured.\n\nAPIs need the same care as web pages. A JSON response can have a consistent shape, an appropriate status, a safe error code, a safe message, and a correlation or request identifier. That response should be stable enough for clients to handle but should not become a diagnostic dump. Command-line tools and internal utilities also deserve review because their output may end up in terminals, shared logs, CI output, tickets, notebooks, or chat messages.\n\nGood user-facing errors are boring in the best way. They acknowledge failure, avoid blame, offer safe next steps, and give support or engineering a way to locate internal detail without exposing it. A correlation ID is especially useful because it lets a user report a problem while the team consults controlled logs. The message helps the user recover without helping someone map the system.",
  "narrationPoints": [
    "User-facing error messages should be clear enough to support legitimate recovery and limited enough to avoid exposing internal detail.",
    "At a high level, wording that distinguishes nonexistent users, wrong passwords, missing factors, disabled accounts, or tenant membership can support enumeration.",
    "APIs need the same care as web pages.",
    "A JSON response can have a consistent shape, an appropriate status, a safe error code, a safe message, and a correlation or request identifier.",
    "A correlation ID is especially useful because it lets a user report a problem while the team consults controlled logs.",
    "Sensitive operations often need generic wording."
  ]
};
