window.COURSE_MODULE = {
  "title": "Tracebacks, Debug Mode, and Environment Separation",
  "graphicAlt": "Sequence diagram for Tracebacks, Debug Mode, and Environment Separation, showing request handler, exception mapper, safe response, protected diagnostic log, and correlation identifier; labeled arrows identify public and internal error paths and the point where unsafe input or behavior is rejected.",
  "narration": "Python tracebacks are valuable during development because they show where failure occurred and how execution reached that point. They can include file paths, module names, function names, line numbers, framework internals, dependency behavior, variable representations, and sometimes sensitive values embedded in exception messages. That detail helps developers fix issues, but it is rarely appropriate for production users or unauthenticated clients.\n\nDebug mode and interactive debugger features are particularly sensitive in web applications. Development tools may show exception pages, local variables, environment details, request data, configuration hints, or interactive controls. Those features are intended for trusted local diagnostics, not public or semi-public environments. Production systems should use safe defaults that prevent raw tracebacks and interactive debugging interfaces from reaching untrusted users.\n\nEnvironment separation keeps diagnostic behavior in its proper place. Local development can be verbose because the audience is the developer. Staging may need more detail than production, but it can still contain sensitive data or external integrations. Production should send limited responses while preserving controlled internal diagnostics in logs, traces, crash reports, or error reporting systems with appropriate access control and redaction.\n\nFramework-provided error handlers are helpful when configured deliberately. Flask, Django, FastAPI, ASGI servers, worker frameworks, and task queues each have ways to shape error handling. The durable principle is to verify the deployed behavior, not just assume defaults are safe. Production-like tests should confirm that raw tracebacks, debug pages, unsafe headers, and internal exception text are not exposed through normal failure paths.",
  "narrationPoints": [
    "Python tracebacks are valuable during development because they show where failure occurred and how execution reached that point.",
    "Development tools may show exception pages, local variables, environment details, request data, configuration hints, or interactive controls.",
    "Environment separation keeps diagnostic behavior in its proper place.",
    "Staging may need more detail than production, but it can still contain sensitive data or external integrations.",
    "Flask, Django, FastAPI, ASGI servers, worker frameworks, and task queues each have ways to shape error handling.",
    "Production-like tests should confirm that raw tracebacks, debug pages, unsafe headers, and internal exception text are not exposed through normal failure paths."
  ]
};
