window.COURSE_MODULE = {
  "title": "Testing, Review, Monitoring, and Remediation",
  "graphicAlt": "Operational lifecycle diagram for Testing, Review, Monitoring, and Remediation, showing request handler, exception mapper, safe response, protected diagnostic log, and correlation identifier; labeled arrows identify public and internal error paths and the point where unsafe input or behavior is rejected.",
  "narration": "Exception safety should be tested directly. Unit tests can exercise known error cases and confirm that handlers return safe messages. Integration tests can verify web pages, API responses, CLI output, and background job records under validation failures, authentication failures, authorization failures, database outages, file errors, timeouts, and third-party failures. Production-like configuration tests should confirm that tracebacks and debug pages are not exposed.\n\nCode review should ask practical questions. Does this handler return a raw exception string? Does a log call include request bodies, headers, tokens, or connection strings? Does a broad except block hide a failed permission check? Does a dependency error reach the client unchanged? Are correlation IDs available? Are custom exception types used consistently? Are redaction rules tested? These questions keep review focused on failure paths that often receive less attention than successful paths.\n\nMonitoring should treat unusual error patterns as signals. Repeated failures, spikes in authentication errors, unexpected authorization denials, new exception types, dependency timeouts, redaction failures, or sudden increases in debug-like responses may indicate a reliability issue, an attack attempt, a misconfiguration, or a data exposure. Good monitoring connects application logs, traces, security alerts, and operational dashboards without requiring sensitive data in every record.\n\nWhen a response, log, trace, alert, or report exposes sensitive information, remediation should be deliberate. Assess what was exposed, where it was stored, who could access it, and how long it was retained. Rotate or revoke exposed secrets when appropriate, remove or restrict affected records where feasible, fix the handler or redaction path, and add regression tests. Exception handling improves when every leak becomes feedback for safer defaults.",
  "narrationPoints": [
    "Unit tests can exercise known error cases and confirm that handlers return safe messages.",
    "Does a log call include request bodies, headers, tokens, or connection strings?",
    "Monitoring should treat unusual error patterns as signals.",
    "Rotate or revoke exposed secrets when appropriate, remove or restrict affected records where feasible, fix the handler or redaction path, and add regression tests.",
    "Code review should ask practical questions.",
    "Are redaction rules tested?"
  ]
};
