window.COURSE_MODULE = {
  "title": "Graph Structure and Conditional Independence",
  "graphicAlt": "Diagram comparing chain, fork, and collider structures in a directed acyclic graph.",
  "narration": "The graph in a Bayesian network is a directed acyclic graph, often shortened to DAG. Directed means the edges have arrow direction. Acyclic means the arrows cannot form a loop that returns to the same node. If an arrow points from A to B, A is a parent of B, and B is a child of A. Ancestors are nodes that can reach a variable through directed paths. Descendants are nodes that can be reached from a variable through directed paths.\n\nA path is a connection through edges. A directed path follows arrow direction. These graph words are not just vocabulary. They define how the model organizes dependencies. A Bayesian network assumes that each variable is conditionally independent of its non-descendants given its parents. In plain language, once a node's direct parents are known, other non-descendant variables should not add information about that node, according to the network structure.\n\nThree common patterns help build intuition. In a chain, A influences B, and B influences C. Information can often flow along the chain, but observing the middle variable can block some of that flow. In a fork, A influences both B and C. The shared parent can explain why the children are related. If the parent is known, the children may become independent in the model.\n\nA collider works differently. A and B both influence C. Before observing C, information may not flow between A and B through that structure. But if C is observed, or a descendant of C is observed, information can connect the alternative explanations. D-separation is the formal method for determining when paths are open or blocked by observations. You do not need to perform complex proofs here. The key point is that graph structure encodes conditional independence assumptions that affect inference.\n\nThese assumptions should be treated as model claims, not facts handed down by the software. If a domain expert says two variables are still related after their modeled parents are known, the graph may need another parent, another edge, or another hidden variable. If data suggests a dependency but the domain story is weak, the team should investigate before accepting the relationship. Conditional independence is powerful because it simplifies the joint distribution, but it must be credible for the problem.",
  "narrationPoints": [
    "Bayesian networks use directed acyclic graphs.",
    "Parent and child relationships organize dependencies.",
    "Graph structure encodes conditional independence assumptions.",
    "Chains, forks, and colliders behave differently.",
    "D-separation formalizes whether information can flow."
  ]
};
