window.COURSE_MODULE = {
  "title": "Evidence, Inference, and Belief Updating",
  "graphicAlt": "Visual showing evidence entering a network and updated probabilities propagating to related variables.",
  "narration": "Inference is the process of computing probabilities from the network. A query variable is the variable you are asking about. An evidence variable is a variable whose state has been observed. Hidden or unobserved variables are variables in the model whose states are not currently known. The result of inference is often a posterior distribution, which describes updated probabilities after the evidence is considered.\n\nImagine an equipment model. If Alarm Active is observed as true, the estimated probability of Equipment Fault may increase. If Power Available is observed as normal, the probability of a power-related cause may decrease. The update can move through related variables because the network structure connects them through local probability distributions. This is evidence propagation: observations in one part of the model change beliefs elsewhere.\n\nExact inference methods calculate mathematically precise answers for the model. They can be appropriate for small networks or networks with favorable structure. But exact inference can become expensive when networks are large, densely connected, or have many variable states. Approximate inference methods, including sampling approaches, trade some precision for scalability. They estimate probabilities rather than computing an exact answer directly.\n\nThe important engineering point is that computation quality and model quality are different. A precise calculation from a poor graph, poor CPT, biased data source, or missing variable can still be misleading. Inference should be paired with model validation, sensitivity analysis, and review. When evidence arrives, a Bayesian network updates beliefs according to its assumptions. The analyst still has to ask whether those assumptions fit the real situation.\n\nIt also matters how evidence is handled. Some evidence is direct, such as a sensor reading. Some evidence is indirect, such as a human report, a derived alert, or a summary score. Evidence may be missing, delayed, noisy, or measured by an unreliable process. A well-documented model explains what each evidence variable represents and how uncertainty in observation is handled. Otherwise, the model may treat weak evidence as stronger than it really is.",
  "narrationPoints": [
    "Inference computes probabilities from the network.",
    "Evidence changes posterior distributions.",
    "Queries ask about variables of interest.",
    "Exact and approximate inference have different tradeoffs.",
    "Precise computation does not guarantee a correct model."
  ]
};
