window.COURSE_MODULE = {
  "title": "OPC and OPC UA",
  "graphicAlt": "Blank course graphic placeholder",
  "narration": "OPC technologies help industrial applications exchange data across products and vendors. Instead of every application implementing every device-specific interface, an OPC layer can expose process values, alarms, events, and other information through a common model.\n\nOPC Classic refers to older specifications built around Microsoft COM and DCOM technologies. These deployments may depend heavily on Windows configuration, service identities, and network permissions. Their architecture can be difficult to segment cleanly, so inventory and supported hardening guidance are important.\n\nOPC Unified Architecture, or OPC UA, is a newer, platform-independent approach with richer information modeling. It can support client-server communication and publish-subscribe patterns. OPC UA also includes modern security capabilities such as application authentication, user authentication, message signing, and encryption when profiles and endpoints are configured appropriately.\n\nAvailable security is not the same as enabled security. Administrators must select suitable security policies, restrict anonymous or overly broad access, protect private keys, and manage application certificates and trust lists. Expired certificates, copied trust stores, weak fallback endpoints, or inaccurate system time can undermine otherwise strong design.\n\nOPC servers and gateways often aggregate valuable data and connect multiple architectural levels. Treat them as important assets: minimize services, separate management access, monitor configuration and trust changes, limit approved clients, and protect the systems that issue or approve certificates.\n\nMonitoring should identify expected endpoints, applications, users, subscriptions, and data flows without weakening encryption for convenience. When content is protected, metadata, server audit records, certificate events, and endpoint telemetry can still support investigation. Secure OPC depends on both protocol features and disciplined lifecycle management.",
  "narrationPoints": [
    "OPC technologies help industrial applications exchange data across products and vendors.",
    "OPC Classic refers to older specifications built around Microsoft COM and DCOM technologies.",
    "OPC Unified Architecture, or OPC UA, is a newer, platform-independent approach with richer information modeling.",
    "Available security is not the same as enabled security.",
    "OPC servers and gateways often aggregate valuable data and connect multiple architectural levels.",
    "Monitoring should identify expected endpoints, applications, users, subscriptions, and data flows without weakening encryption for convenience."
  ]
};
