window.COURSE_MODULE = {
  "title": "Deployment, Containers, and CI/CD Environments",
  "graphicAlt": "Boundary map for Deployment, Containers, and CI/CD Environments, showing developer shell, Python process, deployment platform, child process, and secret store; labeled arrows identify configuration flow and exposure paths and the point where unsafe input or behavior is rejected.",
  "narration": "Deployment platforms make environment variables easy to set, but they also create new lifecycle questions. Containers, serverless functions, managed runtimes, CI/CD systems, and job runners may all provide ways to inject variables at build time or runtime. Build-time values and runtime values should be separated. A value needed only when the application runs should not be baked into an image, cache, artifact, package, or build log.\n\nCI/CD secret variables deserve the same hygiene as application secrets. Pipeline jobs often have access to source code, build output, deployment permissions, package registries, test systems, and cloud environments. A misconfigured job can print secrets, pass them to untrusted tools, store them in artifacts, or reuse them across environments. Least privilege for pipeline access reduces the impact of mistakes and compromises.\n\nPer-environment separation is essential. Development, staging, testing, and production should not share the same secrets or broad access. A variable named the same way across environments should still point to different values with different permissions. Deployment configuration should make it difficult for a staging job to use production credentials or for a production service to inherit a debug-oriented value.\n\nRuntime secret injection can be useful when it avoids long-lived values in images and source code, but it still requires access control, redaction, rotation, and monitoring. Teams should understand who can set variables, who can read them, where they are stored, how they are audited, and how they are replaced during an incident. Build systems and deployment platforms are part of the secret-handling boundary, not outside it.",
  "narrationPoints": [
    "Deployment platforms make environment variables easy to set, but they also create new lifecycle questions.",
    "Build-time values and runtime values should be separated.",
    "Pipeline jobs often have access to source code, build output, deployment permissions, package registries, test systems, and cloud environments.",
    "Least privilege for pipeline access reduces the impact of mistakes and compromises.",
    "Deployment configuration should make it difficult for a staging job to use production credentials or for a production service to inherit a debug-oriented value.",
    "Per-environment separation is essential."
  ]
};
