window.COURSE_MODULE = {
  "title": "Child Processes, Python Runtime Behavior, and Inherited State",
  "graphicAlt": "Control-flow diagram for Child Processes, Python Runtime Behavior, and Inherited State, showing developer shell, Python process, deployment platform, child process, and secret store; labeled arrows identify configuration flow and exposure paths and the point where unsafe input or behavior is rejected.",
  "narration": "When Python launches a child process, relevant environment values may be inherited unless the application controls them explicitly. This matters for subprocess usage, worker processes, build helpers, data tools, and administrative utilities. A child process may not need the parent application database password, token, signing key, proxy setting, or service configuration, yet it may receive those values by default if the environment is copied broadly.\n\nSome environment variables influence runtime behavior rather than simply providing secrets. PATH-like variables can affect executable lookup. Python path and runtime settings can influence imports and behavior. Proxy and network-related values can change outbound connectivity. Locale and encoding settings can influence parsing and output. These values may be legitimate, but they should be understood because they can change what code runs, where traffic goes, and how data is interpreted.\n\nConstructing an explicit environment for subprocesses is often safer than inheriting everything. The application can pass only the variables needed for the approved task and omit unrelated secrets or behavior-changing values. If a child process needs a secret, the design should consider whether there is a narrower channel, shorter-lived credential, or service-specific identity that reduces exposure.\n\nAvoid placing secrets in command arguments when possible because arguments may appear in process listings, diagnostics, job metadata, logs, crash output, or monitoring systems depending on the platform. Environment variables can have similar exposure paths, so they should not be treated casually either. The practical standard is least data, least privilege, least inheritance, and clear review of what the child process actually receives.",
  "narrationPoints": [
    "When Python launches a child process, relevant environment values may be inherited unless the application controls them explicitly.",
    "Python path and runtime settings can influence imports and behavior.",
    "Locale and encoding settings can influence parsing and output.",
    "Constructing an explicit environment for subprocesses is often safer than inheriting everything.",
    "Environment variables can have similar exposure paths, so they should not be treated casually either.",
    "PATH-like variables can affect executable lookup."
  ]
};
