window.COURSE_MODULE = {
  "title": "Rotation, Testing, Monitoring, and Incident Response",
  "graphicAlt": "Operational lifecycle diagram for Rotation, Testing, Monitoring, and Incident Response, showing developer shell, Python process, deployment platform, child process, and secret store; labeled arrows identify configuration flow and exposure paths and the point where unsafe input or behavior is rejected.",
  "narration": "Environment variable security is easier when teams maintain an inventory. Important variables should have owners, descriptions, sensitivity classifications, expected locations, rotation expectations, and references to the systems that depend on them. An inventory does not need to be overly complex to be useful. It helps teams understand which values are required, which are optional, which are secrets, and which are safe to expose in limited contexts.\n\nRotation and revocation should be planned before an incident. A secret may need emergency replacement if it appears in logs, CI output, a repository, a support bundle, a screenshot, or a compromised environment. Teams should know how to update the value, redeploy affected services, recycle workers, refresh child processes, invalidate old credentials, and verify that the old value is no longer accepted. Rotation is an operational process, not only a secret-store update.\n\nTesting should cover missing variables, invalid variables, unsafe defaults, redaction, and environment-specific behavior. Tests can confirm that security-critical values fail closed, production-like settings do not enable debug behavior, sensitive variables are not logged, and child process environments are minimized where expected. Secrets scanning can help find accidental exposure in repositories, build output, logs, and artifacts, but it should complement good design.\n\nIf an environment variable containing a secret is exposed, treat it as potentially compromised until assessed. Identify what was exposed, where it was stored, who could access it, which systems used it, and whether suspicious activity occurred. Rotate or revoke the value when appropriate, clean up affected records where feasible, fix the exposure path, and add regression tests. Incident response should turn the leak into stronger configuration practice.",
  "narrationPoints": [
    "Environment variable security is easier when teams maintain an inventory.",
    "An inventory does not need to be overly complex to be useful.",
    "A secret may need emergency replacement if it appears in logs, CI output, a repository, a support bundle, a screenshot, or a compromised environment.",
    "Secrets scanning can help find accidental exposure in repositories, build output, logs, and artifacts, but it should complement good design.",
    "Identify what was exposed, where it was stored, who could access it, which systems used it, and whether suspicious activity occurred.",
    "Incident response should turn the leak into stronger configuration practice."
  ]
};
