window.COURSE_MODULE = {
  "title": "Building Requests Safely",
  "graphicAlt": "Structured request diagram separating method, encoded target, headers, and body, with query metacharacters percent-encoded and carriage-return or line-feed header input rejected.",
  "narration": "Safe request construction preserves structure. URLs, schemes, hosts, ports, paths, query parameters, headers, content types, and request bodies all have syntax and meaning. When code builds those pieces with casual string concatenation, unexpected characters, encodings, separators, or whitespace can create requests that differ from what the developer intended.\n\nPrefer library-supported URL, query, header, and body construction APIs where they are available. These APIs help keep data in the field where it belongs. A query value should be encoded as a query value. A header value should be validated as a header value. A JSON body should be serialized by a structured serializer, not assembled by hand from untrusted fragments.\n\nDestination handling deserves special care. If callers can influence the URL, host, port, path, or scheme, the application should decide whether that flexibility is allowed. Some clients should contact only a fixed service from trusted configuration. Others may support a bounded set of destinations. Values from files, environment variables, plugins, command-line options, queues, or other services should not become trusted destinations without validation.\n\nKeep trusted configuration separate from external input. A base service endpoint, credential scope, or tenant boundary should not be quietly replaced by user-controlled text. When request fields combine trusted and untrusted values, document the rules and validate the final structured form before sending.\n\nRequest construction is easier to review when the code says what each value means. The safest clients make schemes, hosts, headers, body formats, encodings, and content types explicit rather than hiding protocol text inside a string. This also improves diagnostics: when a request is rejected, the team can tell whether the problem was destination policy, encoding, authentication, content type, or an application-level rule.",
  "narrationPoints": [
    "When code builds those pieces with casual string concatenation, unexpected characters, encodings, separators, or whitespace can create requests that differ from what the developer intended.",
    "A JSON body should be serialized by a structured serializer, not assembled by hand from untrusted fragments.",
    "Values from files, environment variables, plugins, command-line options, queues, or other services should not become trusted destinations without validation.",
    "If callers can influence the URL, host, port, path, or scheme, the application should decide whether that flexibility is allowed.",
    "When request fields combine trusted and untrusted values, document the rules and validate the final structured form before sending.",
    "Request construction is easier to review when the code says what each value means."
  ]
};
