window.COURSE_MODULE = {
  "title": "Timeouts, Retries, Errors, and Observability",
  "graphicAlt": "Retry timeline showing three idempotent attempts sharing one wall-clock deadline, stopping immediately for cancellation, authentication, validation, or permanent failures.",
  "narration": "Reliable failure behavior is part of HTTP client security. A client without timeouts can tie up threads, sockets, memory, and user workflows while waiting for a remote system. Set connection timeouts, read timeouts, and where appropriate, a total operation deadline. Cancellation should be available when the caller no longer needs the result.\n\nRetries need policy. Retrying a safe lookup may improve resilience. Retrying a non-idempotent operation can duplicate effects, increase load, or make the failure harder to understand. Retry rules should consider method semantics, request body replay, remote service guidance, backoff, jitter, maximum attempts, and whether a circuit-breaker style control is needed at a higher layer.\n\nError classification helps both security and operations. DNS failure, TLS validation failure, authentication failure, timeout, protocol error, response validation failure, and application-level rejection should not all collapse into one vague result. The caller needs enough information to choose a safe response without exposing internal details or secrets.\n\nObservability should record useful, safe context. Endpoint labels, status categories, timing, retry counts, validation outcomes, correlation identifiers, and sanitized error classes can help teams troubleshoot. Authorization headers, cookies, tokens, request bodies with sensitive data, private keys, and sensitive response fields should stay out of logs and traces.\n\nA well-designed client fails predictably. It stops when trust checks fail, limits resource use, avoids uncontrolled retry storms, and gives maintainers enough safe evidence to understand what happened. That evidence should support dashboards, alerts, and incident review without turning logs into a secondary store of sensitive request or response data or credentials for later exposure risk.",
  "narrationPoints": [
    "A client without timeouts can tie up threads, sockets, memory, and user workflows while waiting for a remote system.",
    "Retrying a non-idempotent operation can duplicate effects, increase load, or make the failure harder to understand.",
    "Retry rules should consider method semantics, request body replay, remote service guidance, backoff, jitter, maximum attempts, and whether a circuit-breaker style control is needed at a higher layer.",
    "DNS failure, TLS validation failure, authentication failure, timeout, protocol error, response validation failure, and application-level rejection should not all collapse into one vague result.",
    "The caller needs enough information to choose a safe response without exposing internal details or secrets.",
    "Endpoint labels, status categories, timing, retry counts, validation outcomes, correlation identifiers, and sanitized error classes can help teams troubleshoot."
  ]
};
