window.COURSE_MODULE = {
  "title": "What Secure C++ Programming Means",
  "graphicAlt": "Secure C++ overview showing ownership, bounds, validation, failure handling, concurrency, trusted libraries, tooling, and operational review as overlapping defenses around application assets.",
  "narration": "Secure C++ programming means writing code that behaves predictably under realistic conditions: unexpected input, partial failure, concurrency, platform differences, and future maintenance. It is not only about avoiding a short list of dangerous functions. It is about making the program's assumptions visible enough that they can be tested, reviewed, and enforced.\n\nC++ is used for high-performance systems because it gives developers precise control over memory, object layout, resource management, and execution cost. That control is valuable, but it also means the language allows undefined behavior when code uses invalid lifetimes, incorrect bounds, unsafe casts, data races, or mismatched ownership. Secure C++ keeps the performance benefits while reducing the number of fragile manual contracts.\n\nCommon risks include stale pointers, dangling references, out-of-bounds access, unchecked input, integer conversion mistakes, unsafe casts, resource leaks, partial initialization, and error handling that continues after an invalid state. These are often reliability defects first, but they can also weaken security when they occur near trust boundaries, parsers, credentials, file handling, or network input.\n\nA secure design makes assumptions explicit. If a buffer has a capacity, code should know it. If a value comes from outside the process, code should validate it before trusting it. If a component owns a resource, that ownership should be represented in the type or interface. If an operation can fail, the failure path should leave the program in a valid state.\n\nSecure C++ starts with safer abstractions, clear ownership, validation before trust, and reviewable failure behavior. Modern language and library facilities give developers better options than raw arrays, manual cleanup, and scattered pointer arithmetic in many situations. The skill is choosing those facilities deliberately and understanding the contracts they create.",
  "narrationPoints": [
    "Secure C++ programming means writing code that behaves predictably under realistic conditions: unexpected input, partial failure, concurrency, platform differences, and future maintenance.",
    "C++ is used for high-performance systems because it gives developers precise control over memory, object layout, resource management, and execution cost.",
    "Common risks include stale pointers, dangling references, out-of-bounds access, unchecked input, integer conversion mistakes, unsafe casts, resource leaks, partial initialization, and error handling that continues after an invalid state.",
    "If a component owns a resource, that ownership should be represented in the type or interface.",
    "If an operation can fail, the failure path should leave the program in a valid state.",
    "Secure C++ starts with safer abstractions, clear ownership, validation before trust, and reviewable failure behavior."
  ]
};
