window.COURSE_MODULE = {
  "title": "Bounds, Containers, and String Safety",
  "graphicAlt": "Buffer diagram showing an overlapping payload first copied to owned snapshot storage, then framed into a bounded output span without corrupting source bytes.",
  "narration": "Bounds safety starts with choosing the right representation. Standard containers such as vector, array, and string are usually easier to reason about than raw arrays because they carry size information and manage storage. They are not magic shields, but they reduce the amount of handwritten bookkeeping that developers must get right.\n\nWhen code must work near low-level buffers, it should track size and capacity explicitly. Capacity is how much storage exists. Size or used length is how much meaningful data is present. Confusing those values can lead to reading uninitialized data, overwriting memory, or truncating information without noticing.\n\nRange checks should happen before indexing, copying, parsing, or converting data. A check after the access is too late. Reviewers should look for how an index was derived, whether it can be negative or wrap through conversion, whether the container can change size, and whether the check still applies at the point of use.\n\nNon-owning view types such as span and string_view are useful because they pair a pointer-like view with a length. But they do not extend the lifetime of the referenced data. A string_view returned from a temporary string, or a span stored beyond the lifetime of the array it views, can become a clean-looking lifetime bug.\n\nC-style strings require special discipline. They depend on null termination, but many data sources provide byte ranges rather than valid C strings. Before using string-only operations, the code should know that the data is terminated, that the terminator is within bounds, and that binary data is not being treated as text.\n\nSecure review should distinguish owning containers, borrowed views, raw buffers, and string data. Each has different lifetime and bounds rules. The goal is not to forbid low-level code; it is to make low-level assumptions explicit and keep them out of places where a safer abstraction would do the job.",
  "narrationPoints": [
    "Bounds safety starts with choosing the right representation.",
    "When code must work near low-level buffers, it should track size and capacity explicitly.",
    "Reviewers should look for how an index was derived, whether it can be negative or wrap through conversion, whether the container can change size, and whether the check still applies at the point of use.",
    "A string_view returned from a temporary string, or a span stored beyond the lifetime of the array it views, can become a clean-looking lifetime bug.",
    "Before using string-only operations, the code should know that the data is terminated, that the terminator is within bounds, and that binary data is not being treated as text.",
    "Secure review should distinguish owning containers, borrowed views, raw buffers, and string data."
  ]
};
