window.COURSE_MODULE = {
  "title": "Secure Libraries, Crypto, and Dependencies",
  "graphicAlt": "Cryptography boundary diagram showing plaintext and associated context sent with an opaque key identifier to a reviewed provider that returns authenticated ciphertext.",
  "narration": "Security-sensitive code should use trusted libraries rather than custom cryptography, custom secret-storage mechanisms, or custom security protocols. The value of a trusted library is not only the implementation; it is documentation, maintenance, test coverage, platform support, and a path for updates when guidance changes.\n\nLibrary APIs still require careful integration. The caller must pass correct sizes, encodings, object lifetimes, algorithm identifiers, handles, contexts, and error destinations. A strong library cannot protect a program from ignoring return values, truncating inputs, mixing units, or using an object after cleanup.\n\nDependencies should be inventoried and reviewed for security impact. Teams should know which libraries are used, which versions are shipped, which features are enabled, and what update process applies. This matters for cryptography, parsing, compression, serialization, networking, and any component that handles untrusted input.\n\nSecrets should not be hardcoded, logged, embedded in test fixtures, or passed unnecessarily across process boundaries. C++ applications often connect library use with configuration, credentials, environment variables, files, and child processes. Those surrounding paths deserve the same care as the library call itself.\n\nWrappers can help centralize safe API use, but they should not hide errors or make security behavior ambiguous. A good wrapper narrows choices, records policy, checks status, and makes misuse harder. A poor wrapper swallows failure or obscures which algorithm, mode, or configuration is actually active.\n\nDocumentation should state which libraries, algorithms, versions, and platform assumptions are part of the security design. That information helps reviewers, operators, and future maintainers decide whether a dependency update, platform change, or policy revision affects the application.",
  "narrationPoints": [
    "Security-sensitive code should use trusted libraries rather than custom cryptography, custom secret-storage mechanisms, or custom security protocols.",
    "The caller must pass correct sizes, encodings, object lifetimes, algorithm identifiers, handles, contexts, and error destinations.",
    "Teams should know which libraries are used, which versions are shipped, which features are enabled, and what update process applies.",
    "C++ applications often connect library use with configuration, credentials, environment variables, files, and child processes.",
    "Wrappers can help centralize safe API use, but they should not hide errors or make security behavior ambiguous.",
    "Documentation should state which libraries, algorithms, versions, and platform assumptions are part of the security design."
  ]
};
