window.COURSE_MODULE = {
  "title": "Parse URLs Structurally and Allow Only Expected Protocols",
  "graphicAlt": "Infographic splitting a URL into parsed components and checking required protocols, absence of embedded credentials, hostname rules, and effective port. Only when all rules pass does the target proceed to DNS and IP checks; failures are rejected. Fragments are not sent in HTTP, raw prefix matches are inadequate, and valid syntax does not authorize a destination.",
  "narration": "When a workflow must accept a URL, parse it once with a standards-aware API such as Node's URL class. A URL is structured data: protocol, username, password, hostname, port, path, query, and fragment have distinct meanings. Security rules should inspect those parsed components rather than search the original string. Raw prefix tests confuse textual resemblance with origin identity and can approve a hostname that merely contains trusted text.\n\nBegin with an explicit protocol allowlist. A web retrieval feature generally needs HTTPS, or HTTPS and HTTP when the business requirement justifies both. Reject every other scheme by default. Also reject embedded usernames and passwords unless the protocol contract explicitly requires them. Credentials inside a URL complicate logging, redaction, and authority interpretation. Fragments are not sent in an HTTP request and should not influence destination policy.\n\nTreat the port as part of the destination. An allowed hostname does not imply that every service port on that host is permitted. Normalize the absent port to the protocol default for policy comparison, and allow only the specific ports the operation needs. Compare hostname values exactly or apply one deliberately defined subdomain rule. Authorizing trusted.example is different from authorizing every controlled child beneath it, and neither rule should match an unrelated name that only ends with the same characters.\n\nStructured parsing provides useful normalization, including case handling and internationalized domain processing, but it is not a complete security decision. The parser may accept an IP literal, an IPv6 host, an explicit port, or a perfectly valid public-looking hostname whose DNS answers lead somewhere forbidden. Record the parsed, normalized components for the next policy steps, while avoiding sensitive query data in logs. URL parsing answers whether the input can be interpreted under supported syntax. Destination authorization still requires hostname policy, DNS resolution, address classification, redirect controls, and an approved connection path.",
  "narrationPoints": [
    "Parse once with Node's standards-aware URL API and inspect components.",
    "Allow only required protocols; reject unsupported schemes and embedded credentials.",
    "Authorize hostname and port with exact, explicit rules.",
    "Valid URL syntax is not destination authorization."
  ]
};
