window.COURSE_MODULE = {
  "title": "Resolve Hostnames and Validate Every Destination Address",
  "graphicAlt": "Infographic comparing two DNS candidate sets across IPv4 and IPv6. Every applicable result is parsed and classified; any denied result rejects the destination without opening a connection, while an all-approved set can proceed under policy. IP literals bypass DNS only, not classification. Loopback, private, link-local, special-purpose, and deployment exclusions are considered; errors or missing results deny access.",
  "narration": "Hostname authorization and address authorization answer different questions. A hostname is an application-level name; DNS determines candidate network addresses. One name may resolve to several IPv4 and IPv6 results, and those results can change. For a feature intended to reach the public Internet, every address the connection may select must satisfy the public-destination policy before any connection is opened. Checking only the first answer leaves unchecked candidates available to the transport.\n\nThe policy should classify parsed addresses, not textual prefixes. At minimum, an Internet-fetching service normally excludes loopback, private-use, link-local, multicast, unspecified, and other special-purpose or deployment-forbidden ranges. Production policy may also exclude organization-owned networks that are globally numbered but still sensitive. Use a well-tested IP parser and range classifier informed by the current special-purpose address registries. Account for both address families and equivalent forms such as IPv4-mapped IPv6. Hand-maintained string tests are too easy to make incomplete or representation-dependent.\n\nIP literals need the same classification without a DNS query. Hostnames should be resolved through the name-resolution path that matches the eventual connection environment. In Node, operating-system resolution and direct DNS queries are not interchangeable: they can consult different sources. Whichever mechanism the design selects, request all applicable results and reject the destination if any candidate that the client could use violates policy. Treat no result, resolution errors, and malformed answers as denial, not permission.\n\nA business allowlist is stronger and simpler when the service talks to a small known set of providers, but a trusted name does not automatically make an unexpected address safe. Monitor approved names and validate their resolved addresses according to the deployment's intended network model. For a broad public-URL feature, classification is an explicit security boundary. The decision must cover the address the transport can actually choose, not merely the hostname that appeared in the original input.",
  "narrationPoints": [
    "Hostname policy and resolved-address policy are separate controls.",
    "Validate every applicable IPv4 and IPv6 result before connecting.",
    "Use vetted IP parsing and classification, including mapped address forms.",
    "Apply deployment-specific exclusions in addition to general special-purpose ranges."
  ]
};
