window.COURSE_MODULE = {
  "title": "Centralize, Test, Review, and Observe Outbound Requests",
  "graphicAlt": "Infographic showing webhook, importer, and preview callers selecting explicit policies for a narrow outbound service that centralizes parsing, address checks, redirects, and budgets. Deterministic resolver and transport tests cover mixed DNS, denied redirects, resource limits, IPv6 mapped forms, and cross-tenant access. Sanitized policy outcomes exclude secrets and response bodies.",
  "narration": "Scattered fetch calls make destination policy inconsistent and difficult to audit. A narrow outbound-request service can centralize URL parsing, named destination policies, DNS and address checks, redirect handling, resource budgets, credential rules, and sanitized logging. Avoid a magical helper that silently guesses intent. Each caller should select a specific policy and operation, and the service should return constrained results rather than exposing unrestricted client options.\n\nCode review should trace the destination from input to socket. Inventory Fetch, Axios-style clients, Undici dispatchers, webhook senders, importers, preview services, proxies, and raw or alternate-protocol clients. Confirm where the target originates, whether an arbitrary URL is truly required, which protocols and ports are allowed, how hostnames are compared, which resolver the transport uses, whether every candidate address is classified, and what happens after redirects. Review credentials, proxy behavior, timeouts, response limits, and the networks reachable by the workload.\n\nTests should exercise policy boundaries without becoming an exploitation catalog. Cover malformed URLs, unsupported protocols, embedded credentials, forbidden ports, direct IP literals, loopback and private classifications, IPv6 and mapped forms, mixed DNS results, resolution failure, redirects to denied destinations, redirect loops, and excessive chains. Use controlled test resolvers and transports so results are deterministic. Verify that the connection layer receives only an approved address and that an independently changing answer cannot bypass the test. Also test connection timeouts, oversized or over-expanded responses, and cross-tenant attempts to use stored integrations.\n\nObservability should distinguish parse rejection, destination-policy denial, DNS failure, connection failure, redirect denial, resource-limit termination, and upstream error without revealing secrets or response bodies. Metrics can identify repeated denials or unexpected destination drift, while alerts should be tuned to the service's risk and volume. Centralization, tests, review, and telemetry do not replace a sound destination model. They make that model visible, enforceable, and maintainable as libraries and deployment routes evolve.",
  "narrationPoints": [
    "Centralize mechanics while requiring callers to choose an explicit destination policy.",
    "Review every outbound client from request input through the actual socket path.",
    "Test parsing, all-address DNS policy, redirects, budgets, and tenant authorization.",
    "Log policy outcomes without exposing credentials or sensitive content."
  ]
};
