window.COURSE_MODULE = {
  "title": "Course Summary: Validate the Destination Actually Reached",
  "graphicAlt": "Course-summary infographic coordinating operation authorization, URL policy, all-address checks, binding to an approved connection address, scoped request budgets, and enforced egress. TLS and Host identity are preserved. A redirect response loops back to destination validation, and any denied address stops access. Testing, safe logs, and review support the endpoint decision.",
  "narration": "SSRF prevention begins by minimizing the network capability exposed to a requester. Prefer configured integrations, fixed provider bases, and server-controlled destination mappings over arbitrary URLs. Authorize the caller's use of that integration separately. When user-provided URLs are essential, define a narrow operation and an explicit destination policy before making a connection.\n\nParse with a standards-aware URL API. Allow only required protocols, reject unwanted embedded credentials, and authorize hostname and port as structured values. These checks establish syntax and application policy, not the network endpoint. Resolve hostnames through the intended connection environment and classify every applicable IPv4 and IPv6 address with a vetted mechanism. Include special-purpose and deployment-specific forbidden ranges, and apply the same classification to IP literals. A successful parse, trusted-looking hostname, or authenticated caller never substitutes for this decision.\n\nTreat every redirect as a new target. Repeat protocol, hostname, port, resolution, and address policy before the next hop. Close the DNS check-and-use gap so the transport connects only to an approved address while preserving hostname-based TLS and HTTP identity. Then constrain the request itself: method, headers, credentials, time, redirect count, request body, response bytes, decompression, and expected content. Resource controls limit abuse but do not validate a destination.\n\nFinally, make the policy durable. Route outbound operations through reviewable abstractions, test changing destination states, log sanitized policy outcomes, and constrain workload egress through firewalls, proxies, segmentation, or service identities. Network controls contain mistakes but cannot enforce business authorization; application checks understand the operation but should not be the only barrier. A secure outbound request is not defined by the URL the client submitted. It is defined by the destination the server has explicitly permitted and actually connects to.",
  "narrationPoints": [
    "Prefer narrow server-controlled operations over arbitrary URL fetching.",
    "Separate URL parsing, business authorization, DNS, and IP classification.",
    "Reauthorize redirects and bind connections to approved addresses.",
    "Combine scoped requests and credentials with independent egress containment."
  ]
};
