window.COURSE_MODULE = {
  "title": "From Prompt Engineering to Loop Engineering",
  "graphicAlt": "A comparison between a single prompt-response interaction and an engineered AI loop with context preparation, model action, policy validation, tool execution, observation, evaluation, state update, and controlled stopping.",
  "narration": "Prompt engineering is the design of instructions and context for an individual model interaction. It still matters. A clear prompt can shape the format of an answer, describe the task, and provide the facts the model needs for that moment. But many useful AI-enabled workflows cannot be completed reliably in one call, especially when the task requires inspecting evidence, taking actions, learning from tool results, and deciding whether more work is justified.\n\nAn AI loop is an application-level control structure around repeated model and tool interactions. A typical iteration prepares focused context, asks the model for a proposed next action, validates that action against policy, executes one approved tool, records the observation, evaluates progress, updates explicit state, and decides whether to continue, pause, escalate, or stop. The loop is software behavior, not just a longer prompt.\n\nThe difference between repetition and engineering is important. Sending the same request again and again is not a reliable loop. An engineered loop changes its next step based on recorded observations, task state, evidence, resource limits, and terminal conditions. The system should know what changed, what evidence was collected, what action is currently allowed, and what would count as a valid stopping point.\n\nSome loops are fixed workflows, and some are agentic loops. A fixed workflow follows a predetermined path, such as extract data, validate a schema, and send a report for review. An agentic loop lets the model choose among permitted next actions. Neither design is automatically better. Predictable work often benefits from fixed control flow, while uncertain work may justify carefully bounded model-directed decisions.\n\nConsider an AI coding loop assigned to fix a failing feature in a local repository. A vague one-shot request says, \"fix the application.\" A loop-engineered version names the failing test, permitted repository path, available tools, editable files, completion evidence, iteration limit, and actions requiring approval. Loop engineering is the harness around model behavior: the model proposes work, but software-defined controls decide what can execute, what evidence is recorded, and when the run must stop.",
  "narrationPoints": [
    "Prompt engineering shapes one model interaction.",
    "Loop engineering coordinates repeated model, tool, observation, and evaluation cycles.",
    "Repetition alone does not create a reliable loop.",
    "Fixed workflows follow known paths while agentic loops choose among allowed actions.",
    "The harness controls execution, evidence, state, and stopping.",
    "Human system owners remain accountable for loop behavior."
  ]
};
