window.COURSE_MODULE = {
  "title": "Manage Context, Memory, and Progress",
  "graphicAlt": "A context-management pipeline selecting stable instructions, current state, relevant files, recent observations, verified memory, and source-linked summaries while archiving irrelevant history.",
  "narration": "Every loop iteration needs context, but unlimited context is neither possible nor desirable. Large, poorly selected histories can bury the current task, preserve outdated assumptions, increase cost, and make the model attend to irrelevant material. Context construction is an engineering decision about the information needed for the next action and the material that should stay outside the call.\n\nIt helps to separate information layers. Stable task instructions define policy and boundaries. Structured state records progress. Recent observations capture tool results. Source artifacts provide authoritative project facts. Working notes may help with the current hypothesis. Durable memory can preserve lessons across runs. Archived history supports investigation, but it does not need to be copied into every iteration. Keeping these layers distinct makes context smaller and authority clearer.\n\nSummarization and compaction are useful when they preserve the right things. A good summary records decisions, evidence, unresolved questions, changed artifacts, and the current status while removing repetitive conversation. A poor summary can omit a constraint, blur a failed hypothesis into a fact, or lose the source of an observation. Critical facts should remain linked to source records that can be reread. The summary should reduce noise without becoming the only copy of the evidence.\n\nProvenance tells the loop where a fact came from. A user instruction, configuration file, tool result, test output, retrieved document, and model inference should not carry the same authority. If a log file contains text that looks like an instruction, it remains untrusted task data. If a model inferred a cause, that inference needs evidence before it drives a risky action.\n\nProgress tracking also needs freshness checks. Files, services, databases, and external systems may change between iterations or after a paused run. Before acting on old information, the loop may need to reread a file or rerun a targeted check. In the coding loop, the next call may need the task contract, failing test, related source file, latest patch, test output, and a short record of failed hypotheses. Useful memory supports progress without pretending continuity is perfect.",
  "narrationPoints": [
    "More context does not automatically improve loop decisions.",
    "Stable instructions, state, observations, artifacts, and memory serve different roles.",
    "Context should be selected for the current decision.",
    "Summaries must preserve evidence and source links.",
    "Provenance distinguishes authoritative facts from model inferences.",
    "Stale information should be revalidated before consequential actions."
  ]
};
