window.COURSE_MODULE = {
  "title": "Course Summary: The Disciplined AI Loop",
  "graphicAlt": "A complete disciplined AI loop architecture showing task contract, explicit state, focused context, model action, policy validation, bounded tools, observations, evaluation, budgets, approval gates, traces, and terminal states.",
  "narration": "A prompt is one component inside an engineered AI loop. The prompt shapes an interaction, but the loop coordinates repeated decisions, tool calls, observations, evaluations, state changes, and terminal decisions. Reliable behavior comes from the whole harness: the task contract, state model, tool boundaries, evaluation logic, policy enforcement, budgets, traces, and human oversight. Improving only the wording while ignoring the harness leaves important failure modes untouched.\n\nThe disciplined loop begins with a contract. Define the intended outcome, permitted scope, observable completion evidence, constraints, required approvals, and limits. Initialize explicit state, then construct focused context for the current decision. Ask for one bounded next action, validate it against schema and policy, execute only an approved tool, record the observation, evaluate progress, update state, and decide whether to continue, pause, escalate, or terminate.\n\nThe major boundaries are the safety rails of the architecture. Models propose; application policy authorizes. Tools perform bounded operations. Observations are recorded and validated. Evaluators test claims against criteria. Budgets limit execution. Human approvals control consequential actions. Traces support investigation and improvement. Terminal states make stopping explicit instead of leaving the run to fade out in free-form conversation.\n\nThe common failure patterns are familiar by now. Vague definitions of done lead to false completion. Unbounded retries waste resources. Activity is mistaken for progress. The generator is allowed to certify its own success. Entire histories are copied into every iteration. Tools are too broad. Untrusted content is treated as instruction. Uncertainty is hidden behind confident language. Deployment happens without evaluation, or cost is optimized while false completion rises.\n\nA useful loop is not the one that runs longest or sounds most autonomous. It is the one that reaches a justified outcome or stops safely. A well-designed AI loop continues only while the next action is permitted, evidence indicates meaningful progress, resources remain within budget, and the path toward a valid terminal state is still credible. When those conditions fail, the system should preserve evidence and hand control back cleanly. That is the discipline that turns repeated model calls into engineering.",
  "narrationPoints": [
    "A prompt is one component inside an engineered loop.",
    "Task contracts and evidence define meaningful completion.",
    "Explicit state and bounded tools make behavior controllable.",
    "Evaluation converts observations into progress decisions.",
    "Budgets, guardrails, and approvals constrain execution.",
    "Traces turn real failures into measurable improvements.",
    "A reliable loop either proves completion or stops safely."
  ]
};
