window.COURSE_MODULE = {
  "title": "A05: Security Misconfiguration",
  "graphicAlt": "Graphic for A05: Security Misconfiguration",
  "narration": "Default credentials are especially dangerous in payment environments because attackers routinely scan for known administrative paths, vendor defaults, sample accounts, and unmanaged service consoles. Open cloud storage, permissive access policies, public dashboards, and exposed payment administration tools can create direct paths to sensitive data or systems that affect the cardholder data environment. Unnecessary services increase attack surface.\n\nEvery open port, enabled plugin, feature flag, debug endpoint, and administrative function should have a documented purpose and owner. Debug configurations can disclose stack traces, secrets, paths, payment workflow details, and internal service names. Diagnostic detail belongs in protected logs, not public responses.\n\nUse secure configuration baselines for applications, cloud services, containers, and servers. Apply hardening standards and remove unnecessary functionality. Manage configuration changes through reviewed and repeatable processes.\n\nSelected PCI DSS mappings for this topic include Req. 2.2 - Secure configuration standards; Req. 6.4 - Change management; Req. 11.2 - Vulnerability scanning.",
  "narrationPoints": [
    "Default credentials are especially dangerous in payment environments because attackers routinely scan for known administrative paths, vendor defaults, sample accounts, and unmanaged service consoles. Open cloud storage, permissive access policies, public dashboards, and exposed payment administration tools can create direct paths to sensitive data or systems that affect the cardholder data environment. Unnecessary services increase attack surface.",
    "Every open port, enabled plugin, feature flag, debug endpoint, and administrative function should have a documented purpose and owner. Debug configurations can disclose stack traces, secrets, paths, payment workflow details, and internal service names. Diagnostic detail belongs in protected logs, not public responses.",
    "Use secure configuration baselines for applications, cloud services, containers, and servers. Apply hardening standards and remove unnecessary functionality. Manage configuration changes through reviewed and repeatable processes.",
    "Selected PCI DSS mappings for this topic include Req. 2.2 - Secure configuration standards; Req. 6.4 - Change management; Req. 11.2 - Vulnerability scanning."
  ]
};
