window.COURSE_MODULE = {
  "title": "A08: Software and Data Integrity Failures",
  "graphicAlt": "Graphic for A08: Software and Data Integrity Failures",
  "narration": "CI/CD compromise can turn the build pipeline into a path for unauthorized payment application changes. Source control permissions, runner environments, deployment tokens, and artifact repositories all need protection. Unsigned code and unverified artifacts make it difficult to prove that deployed software is authentic and unchanged.\n\nIntegrity verification helps protect the path from source to build to release. Insecure deserialization occurs when applications trust serialized data to reconstruct objects or behavior. Attackers may manipulate serialized input to alter state, bypass controls, or trigger unsafe server behavior.\n\nBuild pipeline attacks are especially relevant when deployment automation can affect payment pages, scripts, APIs, or administrative tools. Change traceability, approvals, and monitoring help reduce this risk. Use code signing and artifact integrity checks.\n\nSecure CI/CD pipelines with least privilege and approvals. Monitor and log system and application changes. Selected PCI DSS mappings for this topic include Req. 6.3 - Software integrity protections; Req. 11.5 - File integrity monitoring; Req. 10.2 - Logging of system changes.",
  "narrationPoints": [
    "CI/CD compromise can turn the build pipeline into a path for unauthorized payment application changes. Source control permissions, runner environments, deployment tokens, and artifact repositories all need protection. Unsigned code and unverified artifacts make it difficult to prove that deployed software is authentic and unchanged.",
    "Integrity verification helps protect the path from source to build to release. Insecure deserialization occurs when applications trust serialized data to reconstruct objects or behavior. Attackers may manipulate serialized input to alter state, bypass controls, or trigger unsafe server behavior.",
    "Build pipeline attacks are especially relevant when deployment automation can affect payment pages, scripts, APIs, or administrative tools. Change traceability, approvals, and monitoring help reduce this risk. Use code signing and artifact integrity checks.",
    "Secure CI/CD pipelines with least privilege and approvals. Monitor and log system and application changes. Selected PCI DSS mappings for this topic include Req. 6.3 - Software integrity protections; Req. 11.5 - File integrity monitoring; Req. 10.2 - Logging of system changes."
  ]
};
