window.COURSE_MODULE = {
  "title": "A09: Security Logging and Monitoring Failures",
  "graphicAlt": "Graphic for A09: Security Logging and Monitoring Failures",
  "narration": "Missing logs leave teams unable to reconstruct important events. Payment applications should capture authentication, authorization failures, administrative actions, sensitive data access, transaction changes, and configuration changes. Poor alerting creates noise without action or misses the events that matter most.\n\nAlerts should focus on suspicious behavior, high-risk changes, fraud indicators, and activity affecting the cardholder data environment. Delayed detection increases the time attackers have to abuse accounts, alter transactions, move laterally, or destroy evidence. Monitoring needs clear ownership and response paths.\n\nInsufficient monitoring can also harm assessment readiness. PCI DSS expects audit trails and review processes that support investigation, accountability, and security operations. Centralize application, identity, infrastructure, and cloud logs.\n\nIntegrate security telemetry with SIEM or monitoring workflows. Review logs and alerts through documented, repeatable processes. Selected PCI DSS mappings for this topic include Req. 10.2 - Audit logs; Req. 10.4 - Log review; Req. 10.6 - Daily log review processes.",
  "narrationPoints": [
    "Missing logs leave teams unable to reconstruct important events. Payment applications should capture authentication, authorization failures, administrative actions, sensitive data access, transaction changes, and configuration changes. Poor alerting creates noise without action or misses the events that matter most.",
    "Alerts should focus on suspicious behavior, high-risk changes, fraud indicators, and activity affecting the cardholder data environment. Delayed detection increases the time attackers have to abuse accounts, alter transactions, move laterally, or destroy evidence. Monitoring needs clear ownership and response paths.",
    "Insufficient monitoring can also harm assessment readiness. PCI DSS expects audit trails and review processes that support investigation, accountability, and security operations. Centralize application, identity, infrastructure, and cloud logs.",
    "Integrate security telemetry with SIEM or monitoring workflows. Review logs and alerts through documented, repeatable processes. Selected PCI DSS mappings for this topic include Req. 10.2 - Audit logs; Req. 10.4 - Log review; Req. 10.6 - Daily log review processes."
  ]
};
