window.COURSE_MODULE = {
  "title": "A10: Server-Side Request Forgery",
  "graphicAlt": "Graphic for A10: Server-Side Request Forgery",
  "narration": "Internal network abuse occurs when an application feature that fetches URLs or integrates with remote systems can reach services that the attacker cannot access directly. Payment environments often contain internal services that should not be reachable from user-controlled input. Cloud metadata exploitation is a serious SSRF scenario.\n\nIf a workload can reach metadata endpoints, attackers may attempt to obtain temporary credentials or environmental information. Trust boundary violations happen when applications treat user-provided destinations as safe. URL fetchers, webhook validators, image importers, document converters, and integration testing features all need careful destination controls.\n\nSSRF defenses work best when application validation is paired with network segmentation, egress filtering, and monitoring for unusual server-initiated traffic. Segment networks and restrict access to internal payment systems. Validate and restrict outbound URLs using allow lists where possible.\n\nApply egress filtering and monitor unusual server-initiated requests. Selected PCI DSS mappings for this topic include Req. 1.3 - Network segmentation and restrictions; Req. 7.2 - Access restrictions; Req. 11.4 - Intrusion detection/prevention.",
  "narrationPoints": [
    "Internal network abuse occurs when an application feature that fetches URLs or integrates with remote systems can reach services that the attacker cannot access directly. Payment environments often contain internal services that should not be reachable from user-controlled input. Cloud metadata exploitation is a serious SSRF scenario.",
    "If a workload can reach metadata endpoints, attackers may attempt to obtain temporary credentials or environmental information. Trust boundary violations happen when applications treat user-provided destinations as safe. URL fetchers, webhook validators, image importers, document converters, and integration testing features all need careful destination controls.",
    "SSRF defenses work best when application validation is paired with network segmentation, egress filtering, and monitoring for unusual server-initiated traffic. Segment networks and restrict access to internal payment systems. Validate and restrict outbound URLs using allow lists where possible.",
    "Apply egress filtering and monitor unusual server-initiated requests. Selected PCI DSS mappings for this topic include Req. 1.3 - Network segmentation and restrictions; Req. 7.2 - Access restrictions; Req. 11.4 - Intrusion detection/prevention."
  ]
};
