window.COURSE_MODULE = {
  "title": "Why Secret Storage Matters",
  "graphicAlt": "Secret-lifecycle diagram for Why Secret Storage Matters, connecting an opaque provider reference to least-privilege retrieval, bounded in-memory use, protected storage, rotation, revocation, safe telemetry, and incident recovery.",
  "narration": "Secrets are values that grant access, prove identity, decrypt data, sign operations, or connect one system to another. In C++ applications they can appear in backend services, desktop software, command-line tools, embedded devices, agents, plugins, and shared libraries. A program can be careful about memory management and still create serious risk if it logs an API key, embeds a credential in a binary, or stores a private key in a file with weak access controls.\n\nSecure secret storage is not only about encrypting a string. It is the full lifecycle of the secret: how the value is created, delivered, accessed, used, monitored, rotated, revoked, and eventually removed from operational systems. Each stage can introduce exposure. A secret may be safe in a managed store but unsafe when copied into a command line, crash dump, support bundle, test fixture, or build artifact. Defensive engineering looks at the path, not just the container.\n\nThe goal is to make safe handling the normal path. Teams should identify which values are secrets, classify their scope, choose approved stores, control delivery, keep runtime exposure short, redact logs, and plan rotation before an incident forces the issue. The decision should be visible in design notes, deployment configuration, and code review so the next maintainer understands the intended path. This course focuses on practical C++ engineering habits: clear ownership, platform-aware storage, careful runtime use, least privilege, and reviewable lifecycle rules.",
  "narrationPoints": [
    "A program can be careful about memory management and still create serious risk if it logs an API key, embeds a credential in a binary, or stores a private key in a file with weak access controls.",
    "Secrets are values that grant access, prove identity, decrypt data, sign operations, or connect one system to another.",
    "A secret may be safe in a managed store but unsafe when copied into a command line, crash dump, support bundle, test fixture, or build artifact.",
    "Secure secret storage is not only about encrypting a string.",
    "The decision should be visible in design notes, deployment configuration, and code review so the next maintainer understands the intended path.",
    "Teams should identify which values are secrets, classify their scope, choose approved stores, control delivery, keep runtime exposure short, redact logs, and plan rotation before an incident forces the issue."
  ]
};
