window.COURSE_MODULE = {
  "title": "Approved Secret Stores and Platform Facilities",
  "graphicAlt": "Secret-lifecycle diagram for Approved Secret Stores and Platform Facilities, connecting an opaque provider reference to least-privilege retrieval, bounded in-memory use, protected storage, rotation, revocation, safe telemetry, and incident recovery.",
  "narration": "Most teams should use approved secret storage mechanisms instead of inventing their own. Depending on the environment, the right answer may be an operating-system credential store, a managed vault, an orchestrator secret mechanism, hardware-backed storage, an encrypted configuration system, or a vetted cryptographic library. The product name is less important than the engineering principle: centralize protection, enforce access control, support rotation, and make secret access auditable.\n\nCustom storage schemes are risky because secret storage combines cryptography, permissions, platform behavior, deployment policy, logging, backup, and operational recovery. A homegrown encrypted file format can still fail if the key is stored beside the ciphertext, if permissions are broad, if rotation is impossible, or if error handling encourages unsafe fallbacks. Approved stores reduce that burden by giving teams reviewed behavior and established operational patterns.\n\nC++ applications can still benefit from a small internal wrapper around the approved mechanism. The wrapper can provide a stable interface, hide platform differences, centralize error handling, and make call sites easier to review. It should not become a second secret store or a place to bypass policy. Keep the wrapper simple, documented, and owned. When deployment platforms change, the implementation can adapt while the application code continues to ask for secrets through the same reviewed boundary.",
  "narrationPoints": [
    "Most teams should use approved secret storage mechanisms instead of inventing their own.",
    "Custom storage schemes are risky because secret storage combines cryptography, permissions, platform behavior, deployment policy, logging, backup, and operational recovery.",
    "A homegrown encrypted file format can still fail if the key is stored beside the ciphertext, if permissions are broad, if rotation is impossible, or if error handling encourages unsafe fallbacks.",
    "Approved stores reduce that burden by giving teams reviewed behavior and established operational patterns.",
    "The wrapper can provide a stable interface, hide platform differences, centralize error handling, and make call sites easier to review.",
    "When deployment platforms change, the implementation can adapt while the application code continues to ask for secrets through the same reviewed boundary."
  ]
};
