window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples apply Resource Protection, Rate Limiting, and Abuse Controls with concrete, reviewable Node.js boundaries.",
  "codeExamples": [
    {
      "title": "Apply an atomic subject rate limit",
      "language": "javascript",
      "blurb": "The limiter key uses validated authenticated context, the store increments and expires atomically, and malformed store results fail closed.",
      "code": "export function createSubjectRateLimiter(clock = () => Date.now()) {\n  if (typeof clock !== \"function\") throw new TypeError(\"trusted rate-limit clock required\");\n  return async function enforceSubjectLimit(store, auth, route) {\n    const subjectId = auth?.subjectId;\n    const rawIncrementWithExpiryCapability = store?.incrementWithExpiry;\n    const incrementWithExpiry = typeof rawIncrementWithExpiryCapability === \"function\"\n      ? rawIncrementWithExpiryCapability.bind(store)\n      : null;\n    if (typeof subjectId !== \"string\" || !/^[A-Za-z0-9_-]{1,128}$/.test(subjectId) ||\n        !incrementWithExpiry) {\n      throw new Error(\"valid authentication and rate store required before rate limiting\");\n    }\n    if (typeof route !== \"string\" || !/^[A-Za-z0-9._-]{1,80}$/.test(route)) {\n      throw new TypeError(\"invalid rate-limit route\");\n    }\n    const now = clock();\n    if (!Number.isSafeInteger(now) || now < 0) throw new TypeError(\"invalid rate-limit clock\");\n    const window = Math.floor(now / 60_000);\n    const key = [\"rate\", route, subjectId, window].join(\":\");\n    const result = await incrementWithExpiry(key, 120_000);\n    const count = result?.count;\n    if (!Number.isSafeInteger(count) || count < 1) throw new Error(\"invalid rate-store result\");\n    if (count > 60) {\n      return Object.freeze({\n        allowed: false, retryAfterSeconds: 60 - Math.floor((now % 60_000) / 1000)\n      });\n    }\n    return Object.freeze({ allowed: true, remaining: 60 - count });\n  };\n}\n\nexport const enforceSubjectLimit = createSubjectRateLimiter();\n"
    },
    {
      "title": "Apply a search deadline and verify cancellation settles",
      "language": "javascript",
      "blurb": "The helper aborts the trusted search adapter at the deadline and reports a lifecycle failure if cancellation does not settle promptly.",
      "code": "const MAXIMUM_SEARCH_DEADLINE_MS = 30_000;\nconst FINAL_SEARCH_SETTLEMENT_MS = 1000;\n\nasync function boundedSettlement(operation, timeoutMs) {\n  let timer;\n  try {\n    return await Promise.race([\n      operation.then((value) => ({ status: \"settled\", value })),\n      new Promise((resolve) => {\n        timer = setTimeout(() => resolve({ status: \"timeout\" }), timeoutMs);\n      })\n    ]);\n  } finally { clearTimeout(timer); }\n}\n\nexport async function boundedSearch(input, search, timeoutMs = 1500) {\n  const query = input?.query;\n  const limit = input?.limit === undefined ? 20 : input.limit;\n  if (typeof query !== \"string\" || query.length < 2 || query.length > 100 ||\n      typeof search !== \"function\") {\n    throw new TypeError(\"invalid search request or adapter\");\n  }\n  if (!Number.isSafeInteger(limit) || limit < 1 || limit > 50) throw new RangeError(\"invalid search limit\");\n  if (!Number.isSafeInteger(timeoutMs) || timeoutMs < 10 || timeoutMs > MAXIMUM_SEARCH_DEADLINE_MS) {\n    throw new RangeError(\"invalid search deadline\");\n  }\n  const controller = new AbortController();\n  let timer;\n  const operation = Promise.resolve().then(() => search(Object.freeze({\n    query, limit, signal: controller.signal\n  }))).then((value) => ({ kind: \"result\", value }),\n    (error) => ({ kind: \"error\", error }));\n  const deadline = new Promise((resolve) => {\n    timer = setTimeout(() => resolve({ kind: \"timeout\" }), timeoutMs);\n  });\n  try {\n    const winner = await Promise.race([operation, deadline]);\n    if (winner.kind === \"error\") throw winner.error;\n    if (winner.kind === \"result\") return winner.value;\n\n    controller.abort();\n    const deadlineError = new Error(\"search deadline exceeded\");\n    const settlement = await boundedSettlement(operation, FINAL_SEARCH_SETTLEMENT_MS);\n    if (settlement.status === \"timeout\") {\n      throw new AggregateError([\n        deadlineError, new Error(\"search did not settle after cancellation\")\n      ], \"search deadline lifecycle failed\");\n    }\n    throw deadlineError;\n  } finally { clearTimeout(timer); }\n}\n"
    }
  ]
};
