window.COURSE_MODULE = {
  "title": "Authorization and Object-Level Access Control",
  "graphicAlt": "Security diagram for REST API Security in NodeJS, Authorization and Object-Level Access Control, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "Authorization answers the question, what is this identity allowed to do. The most important REST API security principle is that every protected action must verify the caller is allowed to perform that action on that specific object. Authentication alone does not stop one authenticated user from accessing another user's record, another tenant's document, or an organization feature they do not manage. The server must make that decision for each relevant object and action.\n\nRoute-level checks are useful but often insufficient. A route may require the user role of manager, but the API still needs to verify that the manager belongs to the organization being modified. A route may require a service credential, but the service account may only be allowed to operate on a subset of tenants. Function-level authorization controls access to capabilities, while object-level authorization controls access to specific records, files, accounts, invoices, projects, or memberships.\n\nNever trust client-supplied IDs, roles, tenant IDs, or ownership claims as proof of access. Treat them as request parameters that must be checked against server-side state. Access control should be centralized enough to stay consistent, but close enough to business logic to understand context. For multi-tenant APIs, admin features, shared documents, invitations, exports, and service accounts, authorization rules should be explicit, tested, and logged when they deny sensitive actions.",
  "narrationPoints": [
    "The most important REST API security principle is that every protected action must verify the caller is allowed to perform that action on that specific object.",
    "Function-level authorization controls access to capabilities, while object-level authorization controls access to specific records, files, accounts, invoices, projects, or memberships.",
    "For multi-tenant APIs, admin features, shared documents, invitations, exports, and service accounts, authorization rules should be explicit, tested, and logged when they deny sensitive actions.",
    "A route may require the user role of manager, but the API still needs to verify that the manager belongs to the organization being modified.",
    "Access control should be centralized enough to stay consistent, but close enough to business logic to understand context.",
    "Authorization answers the question, what is this identity allowed to do."
  ]
};
