window.COURSE_MODULE = {
  "title": "Applying IEC 62443 in Practice",
  "graphicAlt": "Blank course graphic placeholder",
  "narration": "Practical IEC 62443 adoption begins with scope and ownership. Define the system under consideration, the physical process it supports, responsible organizations, lifecycle stage, and risk decision makers. Build an asset inventory that includes devices, software, firmware, communication paths, remote connections, suppliers, and operational dependencies.\n\nPerform risk assessment with engineers and operators. Identify credible threats, vulnerabilities, existing safeguards, process consequences, and required recovery. Use the results to define zones, conduits, target security levels, and requirements. Avoid copying an architecture from another site without confirming that functions and consequences match.\n\nReview the architecture for unnecessary connectivity and uncontrolled trust. Design segmentation, secure remote access, administration, monitoring, backups, and update pathways together. Procurement and supplier requirements should state expected capabilities, evidence, vulnerability handling, support periods, and integration assumptions.\n\nDuring implementation, configure component security features, remove unused functions, manage identities and privileges, document exceptions, and test controls under realistic conditions. Acceptance testing should verify security behavior as well as process operation. The asset owner needs accurate diagrams, account ownership, configuration records, backup procedures, and recovery information.\n\nOperation requires change control, vulnerability management, monitoring, incident response, periodic access review, backup testing, and lifecycle planning. Evidence should show what was implemented, who approved it, how it was tested, and how deviations are managed. Metrics should support decisions rather than exist only for reporting.\n\nOrganizations do not need to solve every issue at once. Start with high-consequence systems and pathways, create achievable improvement plans, and integrate cybersecurity with existing engineering, safety, reliability, and maintenance processes. IEC 62443 works best as an operating discipline, not a one-time documentation project.",
  "narrationPoints": [
    "Practical IEC 62443 adoption begins with scope and ownership.",
    "Perform risk assessment with engineers and operators.",
    "Review the architecture for unnecessary connectivity and uncontrolled trust.",
    "During implementation, configure component security features, remove unused functions, manage identities and privileges, document exceptions, and...",
    "Operation requires change control, vulnerability management, monitoring, incident response, periodic access review, backup testing, and lifecycle...",
    "Organizations do not need to solve every issue at once."
  ]
};
