window.COURSE_MODULE = {
  "title": "Prefer Workload Identity Over Long-Lived Application Keys",
  "graphicAlt": "Infographic showing a trusted runtime establishing workload identity, a provider obtaining a short-lived credential, and a separate authorization gate controlling access to a resource. Federation trust checks issuer, audience, and workload claims. A Kubernetes service account requires trust integration for cloud access. Short-lived credentials remain sensitive and avoid permanent application keys.",
  "narration": "Workload identity represents software rather than a human user. A platform can associate that identity with a virtual machine, container, serverless function, hosted application, Kubernetes workload, or deployment job. The identity is not itself a secret. It is the principal and trust mechanism through which the workload obtains usable credentials.\n\nThe common flow starts with the platform establishing the workload's identity. Application code asks a supported credential provider for access to a target service. The platform issues or brokers a short-lived credential, often a token. The client presents that credential, or uses temporary signing credentials, and the receiving service evaluates authorization. The application avoids carrying a permanent cloud key through its deployment configuration.\n\nExamples include cloud roles, managed identities, service accounts, and federated identities. With OpenID Connect federation, a trusted issuer supplies an assertion that a receiving system validates and may exchange for service credentials. Trust must constrain the expected issuer, audience, and workload claims. An assertion intended for one audience is not automatically a valid access token for every API.\n\nFor Kubernetes, use workload-specific service accounts, narrowly scoped permissions, and short-lived projected tokens where supported. Access to cloud services requires an appropriate trust integration; creating a Kubernetes service account alone does not grant cloud authority. Protect the runtime and its credential endpoint because compromised code may still obtain credentials as the workload.\n\nCompared with permanent keys in environment variables, this design reduces static distribution and developer handling. Providers can renew credentials automatically, and identity-specific audit records improve attribution. Removing trust or permissions can stop future access, but already issued credentials may remain usable until expiration or until the service enforces revocation. Short-lived does not mean harmless: tokens remain sensitive while valid. Finally, identity establishes who is requesting access. Narrow roles and resource permissions still determine what that workload may do.",
  "narrationPoints": [
    "The platform establishes identity; providers obtain credentials.",
    "Constrain federation trust by issuer, audience, and workload.",
    "Short-lived credentials remain sensitive while valid.",
    "Assign narrow permissions independently of authentication."
  ]
};
