window.COURSE_MODULE = {
  "title": "Keep Secrets Out of Code, Logs, Images, and Client Bundles",
  "graphicAlt": "Four-panel infographic preventing credential copies in repositories, build artifacts, browser bundles, and telemetry. Samples use placeholders, image layers can retain a key deleted later, and ephemeral build-secret delivery must not place secrets in output. Browser-delivered credentials are visible to users; authorized server operations retain confidential credentials server-side. Logs contain approved key identifiers and versions instead of secret values.",
  "narration": "Preventing copies is more reliable than cleaning them up later. Keep production credentials out of source files, committed environment files, sample configuration, fixtures, build scripts, and troubleshooting output. Local development environment files can be useful, but credential-bearing files belong outside version control with appropriate access controls. Samples should name required settings using empty values or unmistakable placeholders.\n\nEnvironment variables are a delivery mechanism, not a secret-management system or encryption. Their protection depends on provisioning, process isolation, inspection privileges, deployment tooling, and operational controls. A child process may inherit them. Crash collection and process dumps may capture them. Review what each process receives and what diagnostic systems retain instead of assuming either that all environment variables are safe or that they are always prohibited.\n\nBuild systems create another boundary. Container build arguments and copied files can expose credentials in image layers, build records, or caches. Removing a file in a later layer does not erase it from earlier layers. Use the build platform's supported ephemeral secret mechanism when a build needs authentication, and ensure the command does not copy or print the value into an artifact.\n\nBrowser JavaScript is delivered to users. A frontend variable called SECRET_KEY is visible if bundled into the application, including through build-time substitution. Source maps and generated static files can expose additional content. Put operations requiring confidential credentials behind an authenticated, authorized server endpoint; validate the requested operation so that endpoint does not become an unrestricted credential proxy.\n\nTelemetry must follow the same boundary. Do not log tokens, passwords, API keys, private keys, authorization headers, or complete credential objects. Prefer an allowlist of safe fields, such as an approved key identifier or credential version. Sanitize SDK errors and request traces before collection. Redaction helps, but structured diagnostics that never accept secret values are easier to reason about.",
  "narrationPoints": [
    "Keep credentials out of repositories and build artifacts.",
    "Evaluate environment delivery and process access controls.",
    "Treat every browser-delivered value as visible to users.",
    "Allowlist diagnostic metadata; exclude credential values."
  ]
};
