window.COURSE_MODULE = {
  "title": "Course Summary: Reduce Secrets and Strengthen Identity",
  "graphicAlt": "Course-summary infographic showing workload identity, a supported provider, short-lived credentials, and a separate least-privilege gate to the required resource. A narrow fixed accessor handles only secrets still needed from managed storage. Assigned ownership covers provisioning, delivery, use, renewal, and revocation. Supporting controls prevent copies, bound caches, verify the effective principal, and test denials.",
  "narration": "Review a TypeScript application's credential design as a lifecycle. Begin with the capabilities it needs, the identity that should exercise them, and the resources that identity may reach. Follow each credential from provisioning through delivery, runtime use, renewal, and revocation. This reveals unnecessary copies and authority that a storage-only review can miss.\n\nTreat reusable secrets as portable authority. Eliminate permanent application keys where workload identity is supported, and let platform credential providers obtain and refresh narrowly scoped, short-lived credentials. Identity establishes the requesting workload; authorization remains a separate least-privilege decision. A service identity is not a reason to grant administrative access, and temporary credentials remain sensitive while valid.\n\nFor credentials that remain necessary, managed storage controls custody without eliminating the secret. Prefer workload identity to solve the store's authentication bootstrap, then restrict access to specific secrets. Environment variables deliver configuration; they do not supply secret management by themselves. Keep confidential values out of source control, logs, images, build artifacts, and browser bundles. Secret scanning detects some mistakes, while prevention reduces the opportunities to make them.\n\nDesign rotation together with consumer refresh. Replacing a stored value and making a running process use it are distinct operations. Bound caches, renew expiring credentials, and account for connection pools and revocation behavior. Use bounded failure handling when dependencies are unavailable, without falling back to permanent or more privileged credentials.\n\nKeep developer identity distinct from workload identity, and separate development, test, staging, production, and deployment authority. Verify provider precedence and the effective principal, then test denied access as carefully as successful requests. Assign ownership for renewal and incident response so that the design remains operable after release.\n\nThe strongest secret is often the one the application no longer needs because the runtime can prove its identity and obtain narrowly scoped, short-lived authority instead.",
  "narrationPoints": [
    "Review the full credential lifecycle and its owner.",
    "Replace permanent keys with scoped workload credentials.",
    "Separate identity, authorization, storage, and delivery.",
    "Test real identity use and consumer refresh behavior."
  ]
};
