window.COURSE_MODULE = {
  "title": "What Prompt Engineering Is",
  "graphicAlt": "Conceptual visual of a prompt connecting user intent, context, model behavior, output, and evaluation.",
  "narration": "Prompt engineering is the process of designing and testing the instruction and context package given to a language model. That package may include the task, background information, constraints, examples, source material, tool descriptions, and output requirements. A prompt is not just a sentence at the end of a chat. In an application, it is often an interface contract between user intent, available context, model behavior, and the output that another person or system will review.\n\nLanguage model output is probabilistic. The model predicts likely continuations based on training, current instructions, available context, settings, and application configuration. Output may vary across runs, models, sampling settings, system configurations, retrieved content, and tool results. A better prompt can improve consistency and usefulness, but it cannot guarantee truth, safety, or perfect formatting.\n\nThat is why prompt engineering should be treated as disciplined design work, not a collection of magic phrases. A polished answer may still be wrong. A confident answer may still lack evidence. A prompt that works for one model or product workflow may behave differently in another. Good prompt engineering makes the intended behavior clearer, then tests whether the behavior actually appears across representative cases.\n\nIn practice, a dependable AI workflow combines prompting with verification, application controls, and human review where consequences matter. Source support may be required for factual claims. Authorization, validation, logging, rate limiting, output filtering, and approval gates remain application responsibilities. Prompting helps specify behavior. It does not replace engineering controls or accountable decision-making.\n\nThis framing also helps teams avoid anthropomorphism. The model is not deciding like a person with stable intent. It is generating likely text or tool requests within a configured system. A prompt can guide that generation by making the task, context, boundaries, and output expectations explicit. The more important the workflow, the more the prompt should be treated like a tested software artifact rather than an informal message.",
  "narrationPoints": [
    "Prompt engineering designs instructions and context.",
    "Model outputs are probabilistic.",
    "Better prompts can improve consistency and usefulness.",
    "Prompts cannot guarantee correctness.",
    "Prompting works best with testing and application controls."
  ]
};
