window.COURSE_MODULE = {
  "title": "Define the Task, Audience, and Success Criteria",
  "graphicAlt": "Prompt design worksheet showing task, audience, input, scope, and success criteria.",
  "narration": "Strong prompts begin with a clearly defined task. Weak prompts often describe a topic but not the desired action. Asking for \"something about quarterly support tickets\" is vague. Asking the model to summarize the top five issue themes from the provided ticket notes for a support manager is much clearer. The prompt should say what action to perform, what input to use, who the result is for, and what a successful result looks like.\n\nTask verbs matter. Explain, summarize, classify, extract, compare, transform, critique, draft, and recommend all imply different outputs. A classification prompt should define valid labels and how to handle ambiguous cases. An extraction prompt should define fields and what to do when information is missing. A drafting prompt should define audience, purpose, tone, and required sections. A recommendation prompt should define criteria, constraints, and uncertainty handling.\n\nAudience changes the answer. A status update for executives should not read like implementation notes for engineers. A lesson for beginners needs different vocabulary than a design review for experienced developers. The prompt can specify the intended reader and the level of detail. That helps the model choose examples, terminology, and structure that fit the communication goal.\n\nSuccess criteria should be observable. Useful criteria include required sections, maximum length, valid categories, supported claims, citations, completeness rules, formatting requirements, or a checklist the output must satisfy. Observable criteria make testing possible. If the criteria are vague, evaluation becomes opinion. Prompt engineering starts with specification: define the task, audience, input, scope, and success conditions before tuning wording.\n\nConsider a technical writing example. \"Improve this\" is weak because improvement could mean shorter, clearer, friendlier, more formal, or more complete. A stronger prompt might ask for a concise revision for new users, preserving technical accuracy, using no more than five bullets, and listing assumptions separately. The model now has a task, audience, input, scope, and observable success criteria. The result is easier to judge.",
  "narrationPoints": [
    "Begin with a specific action.",
    "Identify the intended audience.",
    "Define the input and scope.",
    "Make success criteria observable.",
    "Different task verbs require different outputs."
  ]
};
