window.COURSE_MODULE = {
  "title": "Grounding, Retrieval, and Tool Use",
  "graphicAlt": "Grounded AI workflow connecting trusted documents, retrieval, the model, tools, and validated results.",
  "narration": "A model's internal knowledge may be incomplete, outdated, or wrong for the current task. Grounding provides task-relevant external information. That information may come from user-provided documents, approved knowledge bases, search results, databases, application state, tool output, or current system records. Grounding is especially important when factual accuracy, recency, or organization-specific policy matters.\n\nRetrieval-augmented generation is a common pattern. The application retrieves relevant information and includes it in the model context before generation. The model can then answer using the retrieved material rather than relying only on internal knowledge. This can improve factual relevance, but it does not make the answer automatically correct. The retrieval system may miss important sources, retrieve stale material, or include irrelevant content.\n\nRetrieved content should be treated as potentially untrusted input. Documents, webpages, emails, files, database records, and tool output may contain irrelevant, incorrect, conflicting, or hostile instructions. The application should separate trusted instructions from retrieved content. It should apply authorization before retrieving sensitive records and should avoid treating content inside a document as a higher-priority instruction than the system or application rules.\n\nTool use lets a model-assisted workflow request calculations, searches, code execution, file operations, database queries, or API actions. Tools require schema validation, permission checks, logging, error handling, and rate limiting. High-impact actions may require human approval. Prompting can describe when a tool should be considered, but the application should enforce what the model is allowed to do. Model output is not authorization.\n\nGrounding also has a freshness problem. A retrieved policy may be outdated, a database record may be incomplete, and a search result may be only partly relevant. Good prompts should ask the model to distinguish supplied facts from its own interpretation and to cite or label the source used when factual accuracy matters. Good applications should track where context came from, who was allowed to access it, and whether the result can be audited later.",
  "narrationPoints": [
    "Grounding supplies task-relevant external information.",
    "Retrieval can improve factual relevance.",
    "Retrieved content may be untrusted.",
    "Tool calls need validation and authorization.",
    "High-impact actions may require human approval."
  ]
};
