window.COURSE_MODULE = {
  "title": "Security, Privacy, and Reliability",
  "graphicAlt": "Secure AI application boundary showing trusted instructions, untrusted content, least-privilege tools, privacy controls, and approval gates.",
  "narration": "Prompt engineering is only one layer in a secure AI application. Prompt injection is a security problem where untrusted input contains instructions that attempt to redirect model behavior. The source might be a document, webpage, email, uploaded file, database record, or tool output. Defensive design treats those sources as data, not as trusted operating instructions. This course does not provide specific attack examples. The focus is on safe architecture.\n\nDefensive controls include separating trusted instructions from untrusted content, applying least privilege to tools and data, validating tool arguments, logging important model and tool activity, and requiring approval for consequential actions. Output filtering or constrained output formats may help in some workflows. Applications should avoid treating model output as authorization. A model can recommend an action, but the system must decide whether that action is allowed.\n\nPrivacy matters. Sensitive data, secrets, credentials, private records, and regulated information should not be placed into prompts unless the system is explicitly approved to handle them. Minimize data. Redact unnecessary fields. Define retention, access controls, and deployment boundaries. Review vendor, hosting, and logging behavior before sending sensitive content into a model workflow.\n\nReliability also needs application support. Factual claims may need trusted source support. The model should be allowed to state uncertainty when information is missing or conflicting. Critical rules should use deterministic validation where possible. Important workflows should have safe fallback and escalation paths. Prompting can improve behavior, but it does not replace authorization, validation, logging, rate limiting, output filtering, or approval gates.\n\nAvoid relying on hidden reasoning disclosure as a quality control. In many systems, it is better to request concise explanations, verifiable outputs, structured intermediate artifacts, citations, checklists, or brief rationales. Those are observable and reviewable. A user or evaluator should be able to check whether the answer followed the prompt, used trusted sources, respected privacy, and stayed within the allowed workflow.",
  "narrationPoints": [
    "Prompt injection comes from untrusted instructions in data.",
    "Tools and data should use least privilege.",
    "Model output must not serve as authorization.",
    "Sensitive prompt data requires approved handling.",
    "Critical workflows need validation, logging, and safe fallback."
  ]
};
