window.COURSE_MODULE = {
  "title": "Course Summary: A Prompt Engineering Workflow",
  "graphicAlt": "End-to-end prompt engineering workflow from task definition through testing, deployment, and maintenance.",
  "narration": "A repeatable prompt engineering workflow begins with a clear task and intended user. Define the action, input, scope, audience, and success criteria. Then write a clear primary instruction. Add context only when it helps the model perform the task. Add constraints deliberately, and make sure they do not contradict each other. Specify the output format so the response can be reviewed, reused, or processed.\n\nUse examples when they clarify behavior. Zero-shot prompts can work for simple tasks. One-shot and few-shot prompts can show labels, style, transformations, or formatting. Choose examples carefully because they can introduce bias or accidental constraints. For complex work, decompose the task into smaller stages with intermediate outputs that can be reviewed. Treat intermediate data as part of the application workflow, with appropriate protection.\n\nGround factual tasks with trusted information. Retrieval and tools can improve relevance and capability, but retrieved content may be untrusted, and tool calls need validation and authorization. Protect data with least privilege. Avoid placing sensitive information into prompts unless the system is approved for that use. High-impact actions should have approval gates and logging.\n\nFinally, test and maintain the prompt. Use representative and difficult cases. Measure correctness, completeness, relevance, format compliance, citation quality, safety, cost, and latency. Combine automated checks with human review where appropriate. Rerun tests after prompts, models, tools, retrieval sources, or application configuration change. Prompt engineering is a practical discipline of specification, testing, and control. A good prompt clarifies intended behavior, but a dependable AI system also needs trusted data, safeguards, evaluation, and ongoing maintenance.\n\nThe course workflow is intentionally practical. Define the task before wording the prompt. Add context and constraints because they serve a purpose, not because they sound sophisticated. Use examples when they demonstrate behavior you actually want. Ground factual work with trusted information. Protect tools and sensitive data. Test changes and keep versions. That is how prompt engineering becomes an engineering practice rather than a guessing game.",
  "narrationPoints": [
    "Begin with a clear task and success criteria.",
    "Add context, constraints, format, and examples deliberately.",
    "Ground factual work and validate tool use.",
    "Test representative cases and track regressions.",
    "Maintain prompts as versioned application components."
  ]
};
