window.COURSE_MODULE = {
  "title": "Define Strict Schemas for Object Shape and Values",
  "graphicAlt": "A schema checks required, optional, and nullable fields, ranges, formats, arrays, and nested objects. Unknown fields follow a deliberate reject, strip, or controlled-extension policy. Downstream code receives the returned value, never a bypassing raw request; role and tenant stay server-controlled.",
  "narration": "A useful schema describes the smallest shape an operation needs. Start with whether the top level must be an object, then specify each accepted field. Required, optional, and nullable mean different things. A missing field can mean leave the existing value unchanged, while null can mean clear it. Define those meanings deliberately, and reject combinations the operation does not support rather than relying on later code to guess.\n\nValue constraints make the shape operationally meaningful. Bound string lengths, require finite numbers within appropriate ranges, and distinguish integer counts from fractional measurements. Use explicit booleans and closed enumerations where the contract requires them. Specify identifier and date representations, including which format checks the chosen validator actually enforces. Constrain both array length and each element. Apply object rules recursively, and bound dictionary keys, value shapes, property counts, and permitted nesting.\n\nFor a profile update, the public contract might allow an optional display name of one to one hundred characters and an optional timezone from the application's supported set. Decide whether an empty update is meaningful. Neither a role nor a tenant identifier belongs in that contract simply because the persistence entity has those fields. Strictness means making the acceptance policy explicit; it does not require every interface to make the same compatibility decision.\n\nUnknown properties need a deliberate policy at every relevant level. Rejecting them detects contract mistakes. Stripping them can support compatible clients if the application uses the stripped result. A constrained extension area can support metadata without opening the entire object. Defaults vary between validators, so verify the selected behavior with nested examples. Always continue with the value returned by validation when the validator returns an accepted or transformed object. Calling a schema parser and then updating the database with the original request body discards the boundary's result. Downstream code must receive the contract you checked, not another copy of the unverified input.",
  "narrationPoints": [
    "Specify required, optional, nullable, and empty-update behavior.",
    "Bound values, collections, nesting, and dictionary keys.",
    "Choose reject, strip, or constrained extensions for unknown properties.",
    "Pass the validated or transformed result to downstream code."
  ]
};
