window.COURSE_MODULE = {
  "title": "Course Summary: Parse, Validate, Map, Then Trust Narrowly",
  "graphicAlt": "Bound and parse external bytes, apply a runtime schema, use the returned value, check domain rules and permission, explicitly map a narrow command, and enforce invariants at the protected effect. A raw-input bypass ends at rejection. Closed behavior, resource limits, and denial tests support the boundary; an accepted DTO is not the full persistence entity.",
  "narration": "A secure deserialization boundary establishes a sequence of limited guarantees. Parsing establishes that bytes or text can be interpreted in the selected format. Runtime validation establishes that the resulting value satisfies an explicit input contract. TypeScript helps maintain that contract inside the program, but its annotations and assertions do not create the runtime evidence. Keeping unverified input as unknown makes the missing evidence visible without supplying it automatically.\n\nA useful contract covers the whole value: required and optional fields, nullability, ranges, formats, array contents, nested objects, discriminators, and a deliberate policy for unknown properties. If validation strips, normalizes, or transforms input, use the returned value. Intentional coercion can support a documented interface, but conversion alone is not validation. The accepted representation must preserve the meaning the application expects, including identifiers, boolean values, and numeric precision.\n\nStructural validity remains separate from domain meaning and permission. Services enforce relationships and state rules using trusted context. Authorization establishes whether the actual caller may perform the requested action on the actual resource. Persistence controls protect critical invariants when concurrent activity changes that state. Map validated input into narrow application commands and explicit updates. A transfer object describes permitted input; a persistence entity describes far more of the system than an external caller should control.\n\nClosed discriminators select known behavior under server control. They do not justify arbitrary object construction, dynamic loading, or unrestricted model hydration. Resource limits protect the work required before and during validation, because correct parsing is not the same as affordable parsing. Test the entire route through every relevant entry point, including rejection before protected side effects. Keep these responsibilities identifiable as schemas and services evolve. The safest deserialization boundary turns external bytes into a small, validated application value—not into a broad object that the rest of the system is expected to trust automatically.",
  "narrationPoints": [
    "Parse, runtime-validate, check semantics, map narrowly, and authorize effects.",
    "Use returned values; keep DTOs separate from persistence entities.",
    "Select only known behavior and bound the work of processing input.",
    "Test every boundary and prevent side effects after rejection."
  ]
};
