window.COURSE_MODULE = {
  "title": "Introduction: OWASP and CMMC 2.0",
  "graphicAlt": "Graphic for Introduction: OWASP and CMMC 2.0",
  "narration": "Secure application development matters because applications often process, display, transmit, or influence access to sensitive business and defense information. Weak application controls can expose Controlled Unclassified Information, expand attack surface, or undermine evidence needed for assessment readiness. OWASP provides community-driven application security guidance. The OWASP Top 10 gives developers, DevSecOps teams, security engineers, and compliance teams a shared vocabulary for common and high-impact web application risks. CMMC 2.0 is a cybersecurity model for defense contractors and organizations in the defense industrial base.\n\nLevel 1 focuses on foundational safeguarding practices, while Level 2 aligns with NIST SP 800-171 requirements for protecting CUI. Application security supports CMMC by reducing software attack surface, strengthening authentication and access control, improving monitoring, and helping teams demonstrate that secure development and operational controls are understood and repeatable. Each module explains an OWASP risk, practical attack scenarios, mitigations, and selected CMMC practice mappings. These mappings are awareness aids and must be validated against the organization's actual CMMC scope. Use OWASP categories to organize application risk discussions.\n\nUse CMMC practice domains to connect engineering work to CUI protection responsibilities. Validate mappings with the organization's security and compliance teams. Selected CMMC mappings for this topic include RA.L2-3.11.1 - Risk assessments; CA.L2-3.12.1 - Security assessments; SI.L2-3.14.2 - Flaw remediation.",
  "narrationPoints": [
    "Secure application development matters because applications often process, display, transmit, or influence access to sensitive business and defense information. Weak application controls can expose Controlled Unclassified Information, expand attack surface, or undermine evidence needed for assessment readiness. OWASP provides community-driven application security guidance. The OWASP Top 10 gives developers, DevSecOps teams, security engineers, and compliance teams a shared vocabulary for common and high-impact web application risks. CMMC 2.0 is a cybersecurity model for defense contractors and organizations in the defense industrial base.",
    "Level 1 focuses on foundational safeguarding practices, while Level 2 aligns with NIST SP 800-171 requirements for protecting CUI. Application security supports CMMC by reducing software attack surface, strengthening authentication and access control, improving monitoring, and helping teams demonstrate that secure development and operational controls are understood and repeatable. Each module explains an OWASP risk, practical attack scenarios, mitigations, and selected CMMC practice mappings. These mappings are awareness aids and must be validated against the organization's actual CMMC scope. Use OWASP categories to organize application risk discussions.",
    "Use CMMC practice domains to connect engineering work to CUI protection responsibilities. Validate mappings with the organization's security and compliance teams. Selected CMMC mappings for this topic include RA.L2-3.11.1 - Risk assessments; CA.L2-3.12.1 - Security assessments; SI.L2-3.14.2 - Flaw remediation.",
    "Secure application development matters because applications often process, display, transmit, or influence access to sensitive business and defense information.",
    "Weak application controls can expose Controlled Unclassified Information, expand attack surface, or undermine evidence needed for assessment readiness.",
    "OWASP provides community-driven application security guidance.",
    "The OWASP Top 10 gives developers, DevSecOps teams, security engineers, and compliance teams a shared vocabulary for common and high-impact web application risks."
  ]
};
