window.COURSE_MODULE = {
  "title": "A06: Vulnerable and Outdated Components",
  "graphicAlt": "Graphic for A06: Vulnerable and Outdated Components",
  "narration": "Dependency risks begin with visibility. Teams need to know what components are used, where they run, who owns them, and whether they affect systems that process, store, or transmit CUI. Unsupported software becomes difficult to defend because security fixes may no longer be available. End-of-life frameworks, plugins, runtimes, and operating systems should be replaced or isolated according to risk. Third-party components and supply chain dependencies can introduce vulnerabilities or malicious behavior. Package sources, build tools, container images, and vendor software should be governed as part of the application boundary.\n\nVulnerability response requires prioritization, testing, and timely remediation. Teams should evaluate exploitability, exposure, compensating controls, and business impact while avoiding indefinite patch delays. Maintain software inventory and ownership. Use dependency scanning and vulnerability monitoring. Patch, upgrade, replace, or isolate vulnerable components. Selected CMMC mappings for this topic include SI.L2-3.14.1 - Flaw remediation; CM.L2-3.4.1 - Inventory awareness.",
  "narrationPoints": [
    "Dependency risks begin with visibility. Teams need to know what components are used, where they run, who owns them, and whether they affect systems that process, store, or transmit CUI. Unsupported software becomes difficult to defend because security fixes may no longer be available. End-of-life frameworks, plugins, runtimes, and operating systems should be replaced or isolated according to risk. Third-party components and supply chain dependencies can introduce vulnerabilities or malicious behavior. Package sources, build tools, container images, and vendor software should be governed as part of the application boundary.",
    "Vulnerability response requires prioritization, testing, and timely remediation. Teams should evaluate exploitability, exposure, compensating controls, and business impact while avoiding indefinite patch delays. Maintain software inventory and ownership. Use dependency scanning and vulnerability monitoring. Patch, upgrade, replace, or isolate vulnerable components. Selected CMMC mappings for this topic include SI.L2-3.14.1 - Flaw remediation; CM.L2-3.4.1 - Inventory awareness.",
    "Dependency risks begin with visibility.",
    "Teams need to know what components are used, where they run, who owns them, and whether they affect systems that process, store, or transmit CUI.",
    "Unsupported software becomes difficult to defend because security fixes may no longer be available.",
    "End-of-life frameworks, plugins, runtimes, and operating systems should be replaced or isolated according to risk.",
    "Third-party components and supply chain dependencies can introduce vulnerabilities or malicious behavior."
  ]
};
