window.COURSE_MODULE = {
  "title": "A08: Software and Data Integrity Failures",
  "graphicAlt": "Graphic for A08: Software and Data Integrity Failures",
  "narration": "CI/CD compromise can turn a development pipeline into an attack path. Source control permissions, runner environments, deployment keys, artifact repositories, and build scripts all need protection. Insecure deserialization allows attackers to manipulate serialized input and influence object state or server behavior. This can lead to control bypass, data tampering, or code execution in vulnerable patterns. Unsigned code and unverified artifacts make it difficult to prove that deployed software is authentic and unchanged. Integrity validation should cover the path from source to build to release.\n\nBuild pipeline attacks are especially relevant when automation deploys to systems that handle CUI. Change control, separation of duties, approvals, and monitoring help keep the pipeline trustworthy. Use code signing and artifact integrity validation. Secure build pipelines with least privilege and approvals. Restrict and monitor changes to software and deployment processes. Selected CMMC mappings for this topic include SI.L2-3.14.6 - Integrity verification; CM.L2-3.4.5 - Change control restrictions.",
  "narrationPoints": [
    "CI/CD compromise can turn a development pipeline into an attack path. Source control permissions, runner environments, deployment keys, artifact repositories, and build scripts all need protection. Insecure deserialization allows attackers to manipulate serialized input and influence object state or server behavior. This can lead to control bypass, data tampering, or code execution in vulnerable patterns. Unsigned code and unverified artifacts make it difficult to prove that deployed software is authentic and unchanged. Integrity validation should cover the path from source to build to release.",
    "Build pipeline attacks are especially relevant when automation deploys to systems that handle CUI. Change control, separation of duties, approvals, and monitoring help keep the pipeline trustworthy. Use code signing and artifact integrity validation. Secure build pipelines with least privilege and approvals. Restrict and monitor changes to software and deployment processes. Selected CMMC mappings for this topic include SI.L2-3.14.6 - Integrity verification; CM.L2-3.4.5 - Change control restrictions.",
    "CI/CD compromise can turn a development pipeline into an attack path.",
    "Source control permissions, runner environments, deployment keys, artifact repositories, and build scripts all need protection.",
    "Insecure deserialization allows attackers to manipulate serialized input and influence object state or server behavior.",
    "This can lead to control bypass, data tampering, or code execution in vulnerable patterns.",
    "Unsigned code and unverified artifacts make it difficult to prove that deployed software is authentic and unchanged."
  ]
};
