window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Hashing, MACs, and Password Hashing' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Authenticate bounded messages with HMAC-SHA-256",
      "language": "csharp",
      "blurb": "The helper requires a substantial application-owned key, bounds the message, computes into temporary storage, and compares the complete tag in fixed time.",
      "code": "using System.Security.Cryptography;\n\npublic static class MessageMac\n{\n    private const int TagBytes = 32;\n    private const int MaximumMessageBytes = 1024 * 1024;\n\n    public static byte[] Compute(\n        ReadOnlySpan<byte> key,\n        ReadOnlySpan<byte> message)\n    {\n        Validate(key, message);\n        var tag = new byte[TagBytes];\n        _ = HMACSHA256.HashData(key, message, tag);\n        return tag;\n    }\n\n    public static bool Verify(\n        ReadOnlySpan<byte> key,\n        ReadOnlySpan<byte> message,\n        ReadOnlySpan<byte> expectedTag)\n    {\n        if (expectedTag.Length != TagBytes) return false;\n        Validate(key, message);\n\n        Span<byte> actualTag = stackalloc byte[TagBytes];\n        try\n        {\n            _ = HMACSHA256.HashData(key, message, actualTag);\n            return CryptographicOperations.FixedTimeEquals(actualTag, expectedTag);\n        }\n        finally\n        {\n            CryptographicOperations.ZeroMemory(actualTag);\n        }\n    }\n\n    private static void Validate(\n        ReadOnlySpan<byte> key,\n        ReadOnlySpan<byte> message)\n    {\n        if (key.Length is < 32 or > 64)\n            throw new ArgumentException(\"HMAC key length rejected.\", nameof(key));\n        if (message.Length > MaximumMessageBytes)\n            throw new ArgumentException(\"Message exceeds the byte limit.\", nameof(message));\n    }\n}\n"
    },
    {
      "title": "Use ASP.NET Core password hashing without treating hashes as encryption",
      "language": "csharp",
      "blurb": "The service validates bounded account and password inputs, delegates format and work-factor management to PasswordHasher, and reports when an accepted hash should be upgraded.",
      "code": "using Microsoft.AspNetCore.Identity;\n\npublic sealed record PasswordAccount(string Id);\n\npublic readonly record struct PasswordCheck(\n    bool Accepted,\n    bool RehashRequired);\n\npublic sealed class AccountPasswordHasher\n{\n    private readonly PasswordHasher<PasswordAccount> _hasher = new();\n\n    public string Hash(PasswordAccount account, string password)\n    {\n        Validate(account, password);\n        return _hasher.HashPassword(account, password);\n    }\n\n    public PasswordCheck Verify(\n        PasswordAccount account,\n        string encodedHash,\n        string password)\n    {\n        Validate(account, password);\n        if (string.IsNullOrWhiteSpace(encodedHash) || encodedHash.Length > 2048)\n            return new PasswordCheck(false, false);\n\n        var result = _hasher.VerifyHashedPassword(account, encodedHash, password);\n        return result switch\n        {\n            PasswordVerificationResult.Success => new(true, false),\n            PasswordVerificationResult.SuccessRehashNeeded => new(true, true),\n            _ => new(false, false)\n        };\n    }\n\n    private static void Validate(PasswordAccount account, string password)\n    {\n        ArgumentNullException.ThrowIfNull(account);\n        ArgumentNullException.ThrowIfNull(password);\n        if (!IsIdentifier(account.Id))\n            throw new ArgumentException(\"Account identifier rejected.\", nameof(account));\n        if (password.Length is 0 or > 1024)\n            throw new ArgumentException(\"Password length rejected.\", nameof(password));\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) &&\n        value.Length <= 64 &&\n        value.All(character =>\n            character is >= 'A' and <= 'Z' or\n                         >= 'a' and <= 'z' or\n                         >= '0' and <= '9' or '-' or '_');\n}\n"
    }
  ]
};
