window.COURSE_MODULE = {
  "title": "Hashing, MACs, and Password Hashing",
  "graphicAlt": "Bullet summary graphic for Hashing, MACs, and Password Hashing.",
  "narration": "Ordinary cryptographic hashes produce fixed-length digests from input data. They are useful for integrity checks, identifiers, change detection, and other workflows when the design fits their properties. A hash can help detect that data changed, but it does not hide the original data in the way encryption is intended to do.\n\nHashes are not encryption and cannot be decrypted. That distinction matters in design reviews. If a team needs to recover the original value, ordinary hashing is the wrong tool. If a team needs to compare whether the same input was seen again, a hash may be useful, but the privacy and reversibility implications still need review.\n\nA hash alone does not prove authenticity unless it is part of a trusted protocol or combined with a protected secret key. HMAC provides integrity and authenticity when both parties share the secret key and that key is protected. The receiver can verify that the data matches the MAC and that the MAC was produced with the shared secret.\n\nPassword hashing is a different problem from ordinary hashing. Password storage must account for low-entropy human-chosen secrets. Good password hashing uses salts and deliberate work factors to make large-scale guessing more expensive. Fast hashes such as SHA-256 are not suitable for password storage by themselves.\n\nNew ASP.NET Core password-based applications should use framework-supported password hashing rather than custom password storage logic. Framework behavior is designed for the password storage problem, includes format and upgrade considerations, and benefits from maintenance over time.\n\nThe practical review question is what kind of value is being handled. Is this a file integrity digest, a keyed authenticity check, or a password verifier. Each case has different storage, keying, comparison, and lifecycle expectations.",
  "narrationPoints": [
    "If a team needs to compare whether the same input was seen again, a hash may be useful, but the privacy and reversibility implications still need review.",
    "HMAC provides integrity and authenticity when both parties share the secret key and that key is protected.",
    "Good password hashing uses salts and deliberate work factors to make large-scale guessing more expensive.",
    "New ASP.NET Core password-based applications should use framework-supported password hashing rather than custom password storage logic.",
    "Is this a file integrity digest, a keyed authenticity check, or a password verifier."
  ]
};
