window.COURSE_MODULE = {
  "title": "ASP.NET Core Data Protection and Framework Tokens",
  "graphicAlt": "Bullet summary graphic for ASP.NET Core Data Protection and Framework Tokens.",
  "narration": "ASP.NET Core Data Protection is a framework service for protecting application data and framework-generated payloads. It is commonly involved in cookies, antiforgery tokens, password reset tokens, email confirmation tokens, and other protected workflow values. Many applications depend on it even when developers are not directly calling cryptography APIs.\n\nPurpose isolation helps separate protected payloads used for different application purposes. A value protected for one purpose should not be casually reused for another. That isolation is part of how Data Protection keeps framework and application payloads separated by intent.\n\nData Protection depends on key-ring persistence and protection. In a single developer workstation, defaults may appear to work without thought. In production, containers, deployment slots, multiple servers, restarts, or cloud hosting can change where keys live and whether protected payloads remain readable across instances.\n\nMulti-instance deployments need shared and durable key rings when protected payloads must be read across instances. If one instance creates a protected cookie or token and another instance must validate it, both need compatible application identity and key access. Losing or isolating keys can break users and workflows.\n\nDevelopment defaults may not be suitable for production or containers. Teams should review key storage, encryption at rest, access control, application name, deployment topology, backup, and rotation behavior before release.\n\nData Protection is not a general replacement for all encryption, signing, token, database, or key management needs. It is a maintained framework service for specific protected-payload scenarios. Use it where it fits, and choose other reviewed mechanisms when the requirement is different.",
  "narrationPoints": [
    "ASP.NET Core Data Protection is a framework service for protecting application data and framework-generated payloads.",
    "Data Protection depends on key-ring persistence and protection.",
    "If one instance creates a protected cookie or token and another instance must validate it, both need compatible application identity and key access.",
    "Teams should review key storage, encryption at rest, access control, application name, deployment topology, backup, and rotation behavior before release.",
    "Data Protection is not a general replacement for all encryption, signing, token, database, or key management needs."
  ]
};
