window.COURSE_MODULE = {
  "title": "Common Crypto Mistakes in .NET Applications",
  "graphicAlt": "Bullet summary graphic for Common Crypto Mistakes in .NET Applications.",
  "narration": "Common crypto review findings in .NET applications are often practical rather than exotic. Teams may find custom algorithms, copied snippets whose assumptions are not understood, hardcoded keys, shared keys across environments, or low-level primitives used where a framework service would have been safer.\n\nPassword storage is a frequent review area. Fast hashes are useful in some integrity contexts, but they are not appropriate for password storage by themselves. Password-based systems should use maintained password hashing behavior with salts and work factors rather than custom verifier logic.\n\nEncryption without integrity protection is another common problem. Confidentiality alone may not detect modification. Authenticated encryption or a reviewed framework protection service is usually a better fit when the application must know that protected data has not been changed.\n\nNonce or IV handling should be reviewed against the chosen algorithm. Weak random generation, repeated values where uniqueness is required, or improvised construction from timestamps and counters can undermine the intended design. Randomness and uniqueness rules are part of the protocol, not decoration.\n\nCertificate validation should not be disabled in production behavior. Accepting any certificate removes important service identity guarantees. If a development environment needs a special trust path, that path should be environment-scoped and not become a production shortcut.\n\nSecrets can also leak through ordinary operations. Logs, URLs, screenshots, source control, support tickets, build output, and client-delivered assets can all expose keys or decrypted sensitive data. Safe crypto review includes redaction, operational workflows, and deployment behavior, not only source code.\n\nA safe review process starts with the security property needed, the protected data, the key owner, the storage location, the maintained API or framework service, rotation expectations, incident response expectations, and documented assumptions or exceptions.",
  "narrationPoints": [
    "Common crypto review findings in .NET applications are often practical rather than exotic.",
    "Fast hashes are useful in some integrity contexts, but they are not appropriate for password storage by themselves.",
    "Authenticated encryption or a reviewed framework protection service is usually a better fit when the application must know that protected data has not been changed.",
    "Safe crypto review includes redaction, operational workflows, and deployment behavior, not only source code.",
    "A safe review process starts with the security property needed, the protected data, the key owner, the storage location, the maintained API or framework service, rotation expectations, incident response expectations, and documented assumptions or exceptions."
  ]
};
