window.COURSE_MODULE = {
  "title": "Node.js Encryption APIs and API Choice",
  "graphicAlt": "Security diagram for Encryption Fundamentals in Node.js, Node.js Encryption APIs and API Choice, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "Node.js gives developers powerful encryption tools through the traditional node:crypto API and, in modern runtimes, Web Crypto. The traditional API is common in server-side applications and libraries. Web Crypto can be useful for standards-aligned, promise-based, or cross-platform patterns. Both can be safe when used carefully, and both can be misused when the surrounding design is unclear.\n\nEncryption APIs require explicit handling of keys, IVs or nonces, plaintext, ciphertext, authentication tags, associated data, encodings, and errors. createCipheriv and createDecipheriv style workflows make those choices visible. That visibility is good for review, but it also means the application must choose the algorithm, key size, IV or nonce construction, tag handling, and output format deliberately.\n\nOlder convenience APIs and copied snippets are a common source of risk because they may hide key derivation, use unsafe defaults, omit authentication, or normalize fragile patterns that are no longer recommended. Current documentation and reviewed helper functions are safer than code copied from an old blog post. If the team cannot explain the mode, key source, nonce handling, and tag verification, the implementation is not ready to become a shared pattern.\n\nFor maintainability, encryption code should be centralized behind a small reviewed utility, service boundary, or library. Route handlers and job processors should not each invent their own crypto format. A good central boundary can enforce authenticated modes, metadata structure, key identifiers, versioning, redaction, and consistent error behavior. That gives reviewers one place to evaluate the encryption design instead of hunting through scattered one-off calls.",
  "narrationPoints": [
    "js gives developers powerful encryption tools through the traditional node:crypto API and, in modern runtimes, Web Crypto.",
    "Encryption APIs require explicit handling of keys, IVs or nonces, plaintext, ciphertext, authentication tags, associated data, encodings, and errors.",
    "Older convenience APIs and copied snippets are a common source of risk because they may hide key derivation, use unsafe defaults, omit authentication, or normalize fragile patterns that are no longer recommended.",
    "For maintainability, encryption code should be centralized behind a small reviewed utility, service boundary, or library.",
    "That visibility is good for review, but it also means the application must choose the algorithm, key size, IV or nonce construction, tag handling, and output format deliberately.",
    "That gives reviewers one place to evaluate the encryption design instead of hunting through scattered one-off calls."
  ]
};
