window.COURSE_MODULE = {
  "title": "Keys, IVs, Nonces, Salts, and Tags",
  "graphicAlt": "Security diagram for Encryption Fundamentals in Node.js, Keys, IVs, Nonces, Salts, and Tags, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "A key, IV, nonce, salt, and authentication tag may all appear near encryption code, but they have different jobs. A developer should not treat them as generic random strings. A key is the secret that protects confidentiality. It must be unpredictable, protected, scoped to a purpose, and rotated according to policy. If the key is exposed, the encrypted data may be exposed too.\n\nIVs and nonces are algorithm-specific supporting values. Some modes require unique nonces for a given key, and reuse can be catastrophic. Some IVs must be unpredictable. Some constructions can use counters only under strict rules. Static IVs, hardcoded nonces, timestamps, filenames, and user IDs are usually unsafe unless a reviewed algorithm-specific design explicitly permits them.\n\nSalts are different. They are commonly used in password hashing or key derivation so that the same input does not produce the same derived output. A salt is not a substitute for an IV or nonce. Authentication tags are different again: in authenticated encryption, the tag lets the decrypting side verify that the ciphertext and authenticated context have not been modified. The tag must be stored and verified with the encrypted record.\n\nEncoding and metadata are part of the design. Buffers, hex, base64, base64url, JSON, and database binary fields can all be valid, but they must be consistent and documented. Key identifiers and version metadata help support rotation and decryption of older records. A well-formed encrypted record stores enough non-secret metadata to decrypt and verify later, while keeping the key protected separately.",
  "narrationPoints": [
    "It must be unpredictable, protected, scoped to a purpose, and rotated according to policy.",
    "Static IVs, hardcoded nonces, timestamps, filenames, and user IDs are usually unsafe unless a reviewed algorithm-specific design explicitly permits them.",
    "Authentication tags are different again: in authenticated encryption, the tag lets the decrypting side verify that the ciphertext and authenticated context have not been modified.",
    "A well-formed encrypted record stores enough non-secret metadata to decrypt and verify later, while keeping the key protected separately.",
    "A key, IV, nonce, salt, and authentication tag may all appear near encryption code, but they have different jobs.",
    "Some modes require unique nonces for a given key, and reuse can be catastrophic."
  ]
};
