window.COURSE_MODULE = {
  "title": "Passwords, Secrets, and What Not to Encrypt",
  "graphicAlt": "Security diagram for Encryption Fundamentals in Node.js, Passwords, Secrets, and What Not to Encrypt, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "Encryption is powerful because it is reversible by design. That is exactly why it is often the wrong tool. Password storage is the clearest example. Applications should not store passwords using reversible encryption for normal login verification. They should store password verifiers created with password-hashing algorithms or key-derivation functions designed to slow guessing, with salts and parameters that can be upgraded over time.\n\nOther secrets may not need to be recovered either. Reset tokens, email verification tokens, and some API tokens can often be stored as digests when the application only needs to verify a presented value. If the database is read, a digest can reduce the exposure compared with storing the live bearer secret. The design still needs expiration, revocation, ownership, comparison discipline, and abuse monitoring.\n\nInfrastructure secrets need secrets management, not casual encryption and forgetfulness. Database passwords, OAuth client secrets, JWT signing keys, HMAC keys, private keys, and encryption keys should be handled as high-value secrets with controlled storage, access policy, rotation, and redaction. Encrypting a secret and then storing the decryption key beside it is not meaningful protection.\n\nEncryption also does not make unsafe logging safe, does not replace authorization, does not remove the need for least privilege, and does not justify collecting more data than necessary. Client-side or frontend JavaScript cannot keep server secrets secret. A practical review question is whether the application truly needs to recover plaintext. If not, hashing, digest storage, redaction, minimization, or access control may be the better control.",
  "narrationPoints": [
    "Applications should not store passwords using reversible encryption for normal login verification.",
    "Reset tokens, email verification tokens, and some API tokens can often be stored as digests when the application only needs to verify a presented value.",
    "Database passwords, OAuth client secrets, JWT signing keys, HMAC keys, private keys, and encryption keys should be handled as high-value secrets with controlled storage, access policy, rotation, and redaction.",
    "Encryption also does not make unsafe logging safe, does not replace authorization, does not remove the need for least privilege, and does not justify collecting more data than necessary.",
    "Infrastructure secrets need secrets management, not casual encryption and forgetfulness.",
    "The design still needs expiration, revocation, ownership, comparison discipline, and abuse monitoring."
  ]
};
