window.COURSE_MODULE = {
  "title": "Application Patterns: Fields, Files, Messages, and Backups",
  "graphicAlt": "Security diagram for Encryption Fundamentals in Node.js, Application Patterns: Fields, Files, Messages, and Backups, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "Encryption decisions show up differently across common Node.js workflows. Field-level encryption can protect selected database values such as notes, identifiers, or sensitive attributes. It can also complicate search, sorting, uniqueness checks, analytics, support workflows, and debugging. A team should decide which fields need protection, which workflows require plaintext, and which product features change when values are encrypted.\n\nFile encryption can protect documents in object storage, generated exports, backups, archives, and customer uploads. The content may be encrypted, but keys, filenames, metadata, preview generation, virus scanning, access control, and retention still require design. Message encryption can protect queued payloads or service-to-service data, but routing, retries, dead-letter queues, and logs can still expose sensitive information if they copy plaintext.\n\nBackup encryption protects stored copies, but backup access, restore testing, retention, and key recovery matter just as much. A backup that cannot be restored is not a recovery plan. A backup encrypted under a lost key may be unrecoverable. A backup decrypted into a support environment may create a new exposure. Encryption should be reviewed together with the full backup and restore workflow.\n\nTransport encryption such as TLS protects data in motion, but it does not protect data after it is stored, indexed, exported, or logged. Database or disk encryption can protect some storage-layer scenarios, but application code and authorized database paths may still see plaintext. Each pattern should specify where plaintext appears, who can decrypt, how rotation works, how incidents are investigated, and how long sensitive data is retained.",
  "narrationPoints": [
    "A team should decide which fields need protection, which workflows require plaintext, and which product features change when values are encrypted.",
    "File encryption can protect documents in object storage, generated exports, backups, archives, and customer uploads.",
    "Backup encryption protects stored copies, but backup access, restore testing, retention, and key recovery matter just as much.",
    "Database or disk encryption can protect some storage-layer scenarios, but application code and authorized database paths may still see plaintext.",
    "Message encryption can protect queued payloads or service-to-service data, but routing, retries, dead-letter queues, and logs can still expose sensitive information if they copy plaintext.",
    "Field-level encryption can protect selected database values such as notes, identifiers, or sensitive attributes."
  ]
};
