window.COURSE_MODULE = {
  "title": "Errors, Logging, Testing, and Code Review",
  "graphicAlt": "Security diagram for Encryption Fundamentals in Node.js, Errors, Logging, Testing, and Code Review, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "Encryption code should be centralized, tested, documented, and reviewed because small mistakes can become durable data-protection failures. Tests should cover successful round trips, wrong-key failure, tamper detection, missing-tag failure, malformed input handling, key-version behavior, and safe error paths. Tests must use fake keys or controlled test keys, never production secrets copied into fixtures or CI logs.\n\nError handling should fail closed without revealing sensitive detail. A decryption failure may indicate corrupted data, wrong key selection, tampering, missing metadata, deployment drift, or an attempted misuse of the encrypted record. The client should not receive stack traces, plaintext, ciphertext internals, keys, internal paths, or detailed cryptographic metadata. Operators need enough signal to investigate, but not so much that logs become a new exposure.\n\nLogging rules must be explicit. Logs should not contain plaintext secrets, decrypted sensitive data, encryption keys, private key material, tokens, full environment variables, or unnecessary personal data. They also should not normalize printing entire encrypted record structures when those structures include sensitive metadata. Redaction should be tested before values reach centralized logging, tracing, error reporting, analytics, or support tooling.\n\nA practical pull request review asks what is encrypted, which key protects it, how the IV or nonce is generated, where the tag is stored, how metadata is encoded, what happens if decryption fails, and how rotation works. Monitoring should detect repeated decryption failures, key access anomalies, unexpected encryption errors, rotation failures, and workflow changes. Incident response should include key exposure analysis, credential rotation, data exposure review, log review, backup review, and recovery validation.",
  "narrationPoints": [
    "Tests must use fake keys or controlled test keys, never production secrets copied into fixtures or CI logs.",
    "The client should not receive stack traces, plaintext, ciphertext internals, keys, internal paths, or detailed cryptographic metadata.",
    "Logs should not contain plaintext secrets, decrypted sensitive data, encryption keys, private key material, tokens, full environment variables, or unnecessary personal data.",
    "Incident response should include key exposure analysis, credential rotation, data exposure review, log review, backup review, and recovery validation.",
    "Monitoring should detect repeated decryption failures, key access anomalies, unexpected encryption errors, rotation failures, and workflow changes.",
    "A practical pull request review asks what is encrypted, which key protects it, how the IV or nonce is generated, where the tag is stored, how metadata is encoded, what happens if decryption fails, and how rotation works."
  ]
};
