window.COURSE_MODULE = {
  "title": "Course Summary and Practical Checklist",
  "graphicAlt": "Security diagram for Encryption Fundamentals in Node.js, Course Summary and Practical Checklist, showing the protected asset, trust boundary, enforcing component, and verification path with arrows from untrusted input to controlled output.",
  "narration": "The safest encryption work begins before implementation. Define the threat model, the sensitive data, where plaintext is allowed, which systems may decrypt, and what operational requirements still need to work. Use encryption for confidentiality. Do not treat it as a replacement for authentication, authorization, password hashing, data minimization, redaction, access review, or incident response.\n\nFor sensitive application data, prefer authenticated encryption so the application can detect tampering and context mistakes as well as protect confidentiality. Use cryptographically secure randomness for keys, IVs, nonces, and other security-sensitive values. Follow the algorithm-specific requirements for IVs and nonces. Store authentication tags, key identifiers, version metadata, and associated-data policy consistently with the encrypted record.\n\nProtect keys separately from encrypted data. Avoid hardcoded keys, static IVs, nonce reuse, deprecated algorithms, unauthenticated modes for sensitive data, ignored tags, and copied snippets with unclear assumptions. Do not encrypt passwords for login verification. Use password-hashing approaches. Do not expose plaintext, decrypted data, keys, tokens, full environment variables, or internal cryptographic details in logs or client responses.\n\nA practical first-week plan is concrete. Inventory encryption use across the codebase. Remove hardcoded keys. Check for static IVs or nonce reuse. Confirm authenticated modes and tag verification. Review password handling. Document key owners and key versions. Test wrong-key and tamper failure paths. Redact logs and error reports. Define a key-rotation path. Then make encryption review part of pull requests, testing, monitoring, deployment, and incident response.",
  "narrationPoints": [
    "Do not treat it as a replacement for authentication, authorization, password hashing, data minimization, redaction, access review, or incident response.",
    "Use cryptographically secure randomness for keys, IVs, nonces, and other security-sensitive values.",
    "Avoid hardcoded keys, static IVs, nonce reuse, deprecated algorithms, unauthenticated modes for sensitive data, ignored tags, and copied snippets with unclear assumptions.",
    "Then make encryption review part of pull requests, testing, monitoring, deployment, and incident response.",
    "Define the threat model, the sensitive data, where plaintext is allowed, which systems may decrypt, and what operational requirements still need to work.",
    "For sensitive application data, prefer authenticated encryption so the application can detect tampering and context mistakes as well as protect confidentiality."
  ]
};
