window.COURSE_MODULE = {
  "title": "Identity Is the New Perimeter",
  "graphicAlt": "Conceptual visual of identity, roles, policies, and least-privilege access to cloud resources.",
  "narration": "In cloud environments, identity is often the main control plane boundary. A network boundary still matters, but cloud APIs can create resources, change policies, attach storage, modify network rules, rotate keys, deploy workloads, and delete systems. If an identity can call those APIs with broad permissions, that identity can create broad risk. This is why identity and access management is central to cloud security.\n\nCloud identity includes more than human users. It includes groups, roles, service accounts, workload identities, API keys, temporary credentials, managed identities, and automation principals used by deployment pipelines. A developer might sign in with multi-factor authentication and assume a role for a limited task. A container might use a workload identity to read a specific secret. A pipeline might use a service account to deploy approved resources. Each identity should have a clear purpose, a defined owner, and permissions that match the work it actually needs to perform.\n\nLeast privilege is the practical design goal. It means an identity can do the job it needs to do, but not every adjacent job in the account, subscription, project, or tenant. Broad administrator access may be necessary for a small set of break-glass or platform roles, but it should be rare, monitored, and reviewed. Daily engineering work should use narrower roles. Read-only access, deployment access, data access, and security administration should not be casually combined unless there is a documented reason.\n\nAccess should also be time-aware. Temporary credentials are safer than long-lived keys because they reduce the lifetime of exposure. Privileged access should be justified and recorded. Dormant users, unused service accounts, old API keys, and abandoned workload identities should be reviewed and removed. Secrets should not be embedded in source code, images, tickets, chat messages, or local scripts. They should be stored in approved secret-management systems with access logging and rotation processes.\n\nSeparation of duties helps prevent accidental concentration of power. The person who writes an application does not always need permission to approve production access changes. A workload that reads from one storage bucket does not need write access to every bucket. A monitoring tool may need to read logs without being able to disable logging. These distinctions are engineering controls, not paperwork.\n\nA healthy IAM routine asks: who or what has access, why, for how long, and how would we notice misuse or drift? Permissions should be reviewed as systems change, not only during initial setup. Cloud security improves when identity is treated as live infrastructure: designed, documented, monitored, and continuously cleaned up.",
  "narrationPoints": [
    "Cloud control often happens through identity.",
    "Broad permissions create broad risk.",
    "Least privilege limits what identities can do.",
    "Service accounts and workload identities need review.",
    "Access should be temporary, monitored, and justified."
  ]
};
