window.COURSE_MODULE = {
  "title": "Network Exposure and Segmentation",
  "graphicAlt": "Conceptual visual of public and private cloud network exposure with segmented services.",
  "narration": "Cloud network security is about controlling what is reachable, from where, and for what purpose. A cloud service may be private, internal to a virtual network, exposed through a controlled entry point, or reachable from the public internet. Public exposure is not automatically wrong. Many applications need public endpoints. The security question is whether that exposure is intentional, minimal, protected, and monitored.\n\nCloud networks are built from several control layers. Security groups, firewall rules, routing tables, load balancers, private endpoints, network access controls, and service-level settings all influence reachability. A resource can look private at one layer and still be reachable through another path. That is why network review should focus on effective exposure, not just one setting in one place.\n\nSegmentation limits unnecessary communication. A public web tier might need to receive traffic from users and connect to a private application tier. The application tier might need limited access to a database. The database usually should not accept connections from the internet, from every workload, or from every team network. Segmentation helps contain mistakes and makes normal communication easier to reason about.\n\nGood firewall and security group rules are specific. They avoid broad source ranges unless there is a documented need. They limit ports to what the service actually uses. They name ownership and purpose clearly. They are reviewed when applications change. Temporary access rules should expire or be removed after use. A rule that was safe during a migration can become risky if it is forgotten for months.\n\nNetwork controls also connect to identity and data protection. A private endpoint does not replace IAM. A restrictive firewall rule does not replace encryption. A public endpoint does not have to mean weak access control. These controls work together. The safest design usually combines intentional exposure, strong identity, encrypted transport, service-level authorization, logging, and alerting.\n\nA practical network review asks four questions. What is reachable from the internet? What can talk to what inside the cloud environment? Which ports and protocols are open? Which services should be private or reachable only through controlled entry points? Teams should document the expected answers and compare them against actual configuration. When the actual network does not match the intended architecture, the next step is safe remediation: tighten rules, add segmentation, update owners, and monitor for recurrence.",
  "narrationPoints": [
    "Cloud network exposure must be intentional.",
    "Public services need strict control and monitoring.",
    "Segmentation limits unnecessary communication.",
    "Firewall and security group rules should be reviewed.",
    "Ask what is reachable and whether it should be."
  ]
};
