window.COURSE_MODULE = {
  "title": "Views, URLs, Forms, and Request Validation",
  "graphicAlt": "Path, form, JSON, and upload inputs need type, range, size, format, and business-intent validation before a Django view performs an action.",
  "narration": "Django routes requests through URL patterns into function-based or class-based views. Those views receive data from many places: path parameters, query strings, form fields, JSON bodies, headers, cookies, and uploaded files. Some inputs arrive from a browser, while others may come from mobile clients, scripts, webhooks, or internal services. The secure default is to treat request data as untrusted until it has been validated for the specific operation being performed.\n\nValidation should check type, shape, format, range, size, and business intent. A value can be syntactically correct and still be inappropriate for the action. A user identifier can be an integer but refer to another tenant. A file can have an expected extension but contain unexpected content. A JSON body can have the right fields but describe an action the caller is not allowed to take. Validation narrows what the application accepts, while authorization decides whether the current subject may use that data in context.\n\nDjango forms and model validation concepts can help make input rules explicit. Forms are especially useful when a request maps to a known set of fields, constraints, and user-facing validation errors. Model validation can protect data consistency, but it does not automatically capture every request-specific rule, authorization decision, or workflow constraint. Developers should be clear about where validation happens and why, rather than assuming that one layer covers every path into the system.\n\nSafe request handling also includes method discipline, size limits, and controlled error behavior. State-changing actions should use appropriate methods and protections. Large bodies and uploads should have reasonable limits before they consume memory, storage, or parser time. Error responses should help legitimate clients fix bad input without disclosing stack traces, model internals, secrets, raw queries, or internal paths. Well-structured views make security review and maintenance much easier.",
  "narrationPoints": [
    "Django routes requests through URL patterns into function-based or class-based views.",
    "Validation should check type, shape, format, range, size, and business intent.",
    "Django forms and model validation concepts can help make input rules explicit.",
    "Safe request handling also includes method discipline, size limits, and controlled error behavior."
  ]
};
