window.COURSE_MODULE = {
  "title": "ORM, Database Access, Files, and Serialization",
  "graphicAlt": "Scoped queries, explicit request-writable fields, constrained file and parser handling, least-privilege database access, and predictable transactions preserve Django data boundaries.",
  "narration": "Django's ORM provides safer patterns for common database operations by separating application values from query construction. That is a strong starting point, but it does not remove every database risk. Raw SQL, dynamic filters, user-controlled ordering, complex annotations, and custom query construction deserve review. Parameterized queries and safe ORM usage help prevent SQL injection, while clear authorization filters help ensure a query only returns records the caller is allowed to see.\n\nDatabase security also includes migrations, schema changes, transaction behavior, error handling, and database account permissions. A migration can accidentally expose or transform sensitive data. A failed transaction can leave a workflow in a confusing state. A database user with excessive privileges can increase the impact of an application flaw. The web application's data access should match the least capability it needs, and sensitive operations should have predictable rollback and error behavior.\n\nMass assignment and over-posting concepts are important in model-backed forms and serializers. If user-submitted fields are bound too broadly, a caller may influence fields that should be controlled only by the server, such as ownership, role, status, pricing, or approval state. Defensive code explicitly chooses which fields can be set from a request and which fields are derived from authenticated context, workflow, or server-side policy. Convenience should not decide the trust boundary.\n\nFile handling and serialization create additional paths into the system. Uploads require size limits, safe names, constrained storage locations, content handling rules, and authorization around access and deletion. Media files and static files serve different purposes and should not be confused. JSON, YAML, XML, and CSV processing should use safe parsers, reasonable limits, and clear schemas. Unsafe deserialization at a high level is the risk of turning untrusted data into behavior or objects the application did not intend.",
  "narrationPoints": [
    "Django's ORM provides safer patterns for common database operations by separating application values from query construction.",
    "Database security also includes migrations, schema changes, transaction behavior, error handling, and database account permissions.",
    "Mass assignment and over-posting concepts are important in model-backed forms and serializers.",
    "File handling and serialization create additional paths into the system."
  ]
};
