window.COURSE_MODULE = {
  "title": "Course Summary and Key Takeaways",
  "graphicAlt": "Repeatable Django security uses safe defaults, validated requests, separate identity and permission checks, controlled outputs, constrained data paths, and continued testing and monitoring.",
  "narration": "Secure Django applications depend on both framework protections and deliberate engineering choices. Django provides strong building blocks for settings, forms, templates, authentication, sessions, CSRF protection, ORM access, and administrative workflows. Those building blocks work best when developers avoid disabling protections for convenience and when teams understand which decisions remain application-specific, such as object ownership, tenant boundaries, file handling, API behavior, and deployment assumptions.\n\nThe core habits are stable across Django versions and hosting platforms. Keep settings explicit and environment-aware. Protect secrets outside source code. Treat request data as untrusted until validated for type, shape, format, range, size, and business intent. Separate authentication from authorization. Protect sessions and cookies. Preserve CSRF defenses for browser-based state changes. Enforce permissions on the server, close to sensitive actions, and test denied cases directly.\n\nDjango security also requires careful output and data handling. Templates need context-aware rendering. Redirects should be constrained. Responses should minimize unnecessary data. ORM and raw SQL usage should preserve safe query construction and authorization filters. Uploads, media files, static files, and serialized data should maintain trust boundaries. Dependencies, scanners, tests, logs, audit events, and monitoring extend security beyond the initial code review.\n\nThe goal is not perfect code and not blind reliance on the framework. The goal is repeatable, maintainable risk reduction across the Django application lifecycle. Settings, code, infrastructure, and operations should reinforce one another. When developers can explain where data enters, how identity is established, where authorization is enforced, how outputs are rendered, and how failures are observed, the application becomes much easier to defend and improve.",
  "narrationPoints": [
    "Secure Django applications depend on both framework protections and deliberate engineering choices.",
    "The core habits are stable across Django versions and hosting platforms.",
    "Django security also requires careful output and data handling.",
    "The goal is not perfect code and not blind reliance on the framework."
  ]
};
