window.COURSE_MODULE = {
  "title": "What XSS Prevention Means",
  "graphicAlt": "Untrusted browser-bound data passes through context-specific handling for HTML text, quoted attributes, URLs, JavaScript data, JSON, CSS, rich text, DOM sinks, and defense-in-depth headers.",
  "narration": "Cross-site scripting, often shortened to XSS, is a browser-side injection risk involving untrusted content rendered into executable or otherwise unsafe browser contexts. The concern is not limited to one framework or one page type. A Python application can introduce XSS through server-rendered templates, API responses consumed by browser code, administrative screens, internal tools, user-generated content, error pages, or hybrid frontends that combine backend and client-side rendering.\n\nXSS prevention protects users, sessions, application data, and trust in the interface. If a browser treats untrusted data as markup or script-like behavior, the application may lose control over what the user sees and what actions appear to happen inside the trusted interface. This course stays on the defensive side: how to design rendering paths, templates, APIs, and content handling so untrusted data remains data rather than becoming browser behavior.\n\nStored, reflected, and DOM-based XSS describe where unsafe rendering is introduced at a high level. Stored risk involves content saved by the application and later rendered. Reflected risk involves request data rendered in a response. DOM-based risk involves client-side code placing data into the browser document unsafely. The categories help organize review, but prevention still comes back to the same question: where did the data come from, and where is it being rendered?\n\nInput validation, output encoding, sanitization, Content Security Policy, and browser protections do different jobs. Validation narrows what the application accepts. Encoding makes data safe for a specific output context. Sanitization can allow limited rich content under a content policy. CSP can reduce impact as defense in depth. None of these is a universal replacement for the others. Strong XSS prevention designs safe rendering across templates, APIs, frontend code, content storage, and response handling.",
  "narrationPoints": [
    "The concern is not limited to one framework or one page type.",
    "XSS prevention protects users, sessions, application data, and trust in the interface.",
    "Stored, reflected, and DOM-based XSS describe where unsafe rendering is introduced at a high level.",
    "Strong XSS prevention designs safe rendering across templates, APIs, frontend code, content storage, and response handling.",
    "Input validation, output encoding, sanitization, Content Security Policy, and browser protections do different jobs.",
    "DOM-based risk involves client-side code placing data into the browser document unsafely."
  ]
};
