window.COURSE_MODULE = {
  "title": "User-Generated Content and Sanitization",
  "graphicAlt": "User biography and Markdown pass through an element, attribute, and protocol allowlist before Markup; script elements, event handlers, javascript URLs, and mutation after sanitization are excluded.",
  "narration": "User-generated content includes comments, profiles, descriptions, support tickets, forum posts, markdown, rich text, uploaded files, and CMS-style fields. Some of this content should be plain text. Some applications need limited formatting, links, lists, or embedded media. The first security decision is the content policy: what formatting is actually allowed, who can create it, who can view it, and which contexts will render it.\n\nSanitization at a high level means preserving useful allowed content while removing or neutralizing unsafe content. It should rely on vetted libraries and clear policies rather than ad hoc string replacement. Browser parsing is complex, and simple replacements tend to miss contexts, encodings, malformed input, or future rendering changes. A durable approach defines allowed elements, allowed attributes, URL rules, and output handling rules in one maintainable policy.\n\nStoring raw versus sanitized content is an architectural decision. Storing raw content can allow reprocessing if the policy changes, but it requires strict controls around where raw content is viewed or exported. Storing sanitized content can simplify rendering, but policy changes may require re-sanitization or migration. Some applications store both with careful access rules. The important point is to make the choice deliberately and document the consequences.\n\nRich content should be reviewed whenever policy, libraries, templates, or frontend rendering changes. A sanitized field may be safe for one page and unsafe if reused in another context. Markdown conversion, preview features, imports, and admin editing can all create alternate paths. The safest teams treat rich content as a long-lived trust boundary, not as a one-time cleanup step at input time.",
  "narrationPoints": [
    "User-generated content includes comments, profiles, descriptions, support tickets, forum posts, markdown, rich text, uploaded files, and CMS-style fields.",
    "Sanitization at a high level means preserving useful allowed content while removing or neutralizing unsafe content.",
    "Storing sanitized content can simplify rendering, but policy changes may require re-sanitization or migration.",
    "A sanitized field may be safe for one page and unsafe if reused in another context.",
    "Browser parsing is complex, and simple replacements tend to miss contexts, encodings, malformed input, or future rendering changes.",
    "A durable approach defines allowed elements, allowed attributes, URL rules, and output handling rules in one maintainable policy."
  ]
};
