window.COURSE_CODE_MODULE = {
  "title": "Code Examples",
  "codeIntro": "These examples turn 'Uploads, Request Bodies, and Decompression Risk' into concrete defensive .NET review patterns.",
  "codeExamples": [
    {
      "title": "Account compressed and expanded bytes together",
      "language": "csharp",
      "blurb": "The budget owns application maxima for compressed bytes, expanded bytes, and expansion ratio, validates each positive chunk, uses subtraction-before-addition checks, and rejects expansion work as soon as any cumulative boundary is crossed.",
      "code": "public sealed class DecompressionBudget\n{\n    private const long MaximumCompressedBytes = 2 * 1024 * 1024;\n    private const long MaximumExpandedBytes = 16 * 1024 * 1024;\n    private const int MaximumExpansionRatio = 20;\n    private long _compressed;\n    private long _expanded;\n\n    public long CompressedBytes => _compressed;\n    public long ExpandedBytes => _expanded;\n\n    public void Account(int compressedBytes, int expandedBytes)\n    {\n        if (compressedBytes < 0 || expandedBytes < 0 ||\n            compressedBytes == 0 && expandedBytes != 0 ||\n            compressedBytes > MaximumCompressedBytes - _compressed ||\n            expandedBytes > MaximumExpandedBytes - _expanded)\n        {\n            throw new InvalidDataException(\"Decompression byte budget exceeded.\");\n        }\n        var nextCompressed = _compressed + compressedBytes;\n        var nextExpanded = _expanded + expandedBytes;\n        if (nextCompressed > 0 && nextExpanded > nextCompressed * MaximumExpansionRatio)\n            throw new InvalidDataException(\"Decompression ratio exceeded.\");\n        _compressed = nextCompressed;\n        _expanded = nextExpanded;\n    }\n}\n"
    },
    {
      "title": "Reserve upload quota before reading the body",
      "language": "csharp",
      "blurb": "The immutable reservation validates authenticated identity, object identifier, exact positive content length, per-file maximum, and remaining tenant quota before body processing starts, preventing an upload from choosing its own accounting size.",
      "code": "public sealed class UploadRateReservation\n{\n    private UploadRateReservation(\n        string tenantId,\n        string subjectId,\n        string objectId,\n        long contentLength,\n        long remainingAfterReservation)\n    {\n        TenantId = tenantId;\n        SubjectId = subjectId;\n        ObjectId = objectId;\n        ContentLength = contentLength;\n        RemainingAfterReservation = remainingAfterReservation;\n    }\n\n    public string TenantId { get; }\n    public string SubjectId { get; }\n    public string ObjectId { get; }\n    public long ContentLength { get; }\n    public long RemainingAfterReservation { get; }\n\n    public static UploadRateReservation Create(\n        string tenantId,\n        string subjectId,\n        string objectId,\n        long contentLength,\n        long tenantBytesRemaining)\n    {\n        const long maximumUpload = 10 * 1024 * 1024;\n        const long maximumTenantQuota = 1024L * 1024 * 1024;\n        if (!IsIdentifier(tenantId) || !IsIdentifier(subjectId) || !IsIdentifier(objectId) ||\n            contentLength is < 1 or > maximumUpload ||\n            tenantBytesRemaining is < 0 or > maximumTenantQuota ||\n            contentLength > tenantBytesRemaining)\n        {\n            throw new ArgumentException(\"Upload rate reservation rejected.\");\n        }\n        return new UploadRateReservation(\n            tenantId, subjectId, objectId, contentLength, tenantBytesRemaining - contentLength);\n    }\n\n    private static bool IsIdentifier(string value) =>\n        !string.IsNullOrEmpty(value) && value.Length <= 64 &&\n        value.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');\n}\n"
    }
  ]
};
