window.COURSE_MODULE = {
  "title": "ASP.NET Core Rate Limiting Fundamentals",
  "graphicAlt": "Bullet summary graphic for ASP.NET Core Rate Limiting Fundamentals.",
  "narration": "ASP.NET Core includes rate-limiting middleware for defining and applying request policies. At a high level, teams can configure global behavior, named policies, and endpoint-specific policy attachment. The important design question is not only whether rate limiting exists, but whether the policy matches the endpoint and the users who depend on it.\n\nGlobal policies can be useful when the entire application needs a basic safety floor. They can also become too blunt if the application has very different request types. An inexpensive read endpoint, authentication endpoint, expensive search, upload path, report generator, tenant API, and public API may all deserve different limits because they create different load and user experience expectations.\n\nNamed policies make intent easier to review. A policy name should describe the relationship it protects, such as an API client policy, an authenticated user policy, a report-generation policy, or an upload policy. Reviewers should be able to connect the policy to endpoint cost, expected traffic, and operational ownership.\n\nEndpoint-specific policy attachment is often helpful because the rate-limit decision appears near the route or endpoint group. Minimal APIs, controllers, and route groups can make policy scope visible. That visibility matters during code review because a future developer should understand why an endpoint has a stricter or looser policy than neighboring endpoints.\n\nConfiguration values should be reviewable and environment-aware. Local development limits may be relaxed for productivity. Staging may need test-friendly values. Production should reflect real capacity, user experience, tenant fairness, and infrastructure behavior. Limits should not be hidden constants that no one owns or understands.\n\nRate limiting is most useful when it is paired with observability. Teams should be able to see when a policy is triggered, which endpoint was involved, which partition was affected, and whether the limit is protecting the system or masking a deeper capacity problem.",
  "narrationPoints": [
    "ASP.NET Core includes rate-limiting middleware for defining and applying request policies.",
    "A policy name should describe the relationship it protects, such as an API client policy, an authenticated user policy, a report-generation policy, or an upload policy.",
    "Minimal APIs, controllers, and route groups can make policy scope visible.",
    "Limits should not be hidden constants that no one owns or understands.",
    "Rate limiting is most useful when it is paired with observability."
  ]
};
