window.COURSE_MODULE = {
  "title": "Operations, Testing, and Production Governance",
  "graphicAlt": "Bullet summary graphic for Operations, Testing, and Production Governance.",
  "narration": "Rate limits and request controls must be validated through safe load testing and operational review. Local development values should not silently become production limits. A limit that feels fine with a few test requests may be too strict for real users, too loose for expensive endpoints, or misaligned with upstream infrastructure.\n\nGateways, reverse proxies, CDNs, ingress controllers, web application firewalls, hosting platforms, and the ASP.NET Core app may all enforce limits. Teams should decide which layer owns each limit and why. The edge may be better for broad traffic shaping. The application may be better for user, tenant, route, or business-aware decisions. Both can be useful when they are aligned.\n\nMonitoring signals should include limit rejections, queue pressure, latency, request body rejection, timeout trends, endpoint hotspots, tenant hotspots, concurrency saturation, backend saturation, and downstream service errors. These signals help teams distinguish a useful control from a misconfigured one.\n\nTuning limits should not hide service reliability problems. If an endpoint constantly hits limits because it is too slow or too expensive, the answer may be optimization, caching, workflow redesign, capacity planning, or background processing rather than only stricter limits. Rate limiting should protect the system, not conceal poor service health.\n\nException governance matters. Some clients, tenants, routes, or environments may need special limits. Exceptions should have an owner, reason, duration, review date, and environment scope. Temporary exceptions should not become permanent policy because no one remembers why they exist.\n\nProduction governance turns request controls into an operating practice. Limits should be documented, reviewed during releases, tested safely, observed in dashboards, and revisited as user behavior, endpoint cost, and infrastructure change.",
  "narrationPoints": [
    "Rate limits and request controls must be validated through safe load testing and operational review.",
    "The application may be better for user, tenant, route, or business-aware decisions.",
    "Monitoring signals should include limit rejections, queue pressure, latency, request body rejection, timeout trends, endpoint hotspots, tenant hotspots, concurrency saturation, backend saturation, and downstream service errors.",
    "Rate limiting should protect the system, not conceal poor service health.",
    "Exceptions should have an owner, reason, duration, review date, and environment scope."
  ]
};
