window.COURSE_MODULE = {
  "title": "Parsing Without Unsafe Assumptions",
  "graphicAlt": "A cursor advances through bytes only after remaining-length checks, producing typed fields without casting the buffer to an aligned C++ structure.",
  "narration": "Safe binary parsing is explicit. A parser should avoid directly casting a byte buffer into a C++ struct and treating the result as a valid protocol object. That shortcut can depend on compiler layout, padding, alignment, object lifetime, and platform details that are not necessarily part of the protocol. It may also hide where validation should occur.\n\nA reviewable parser reads fields deliberately. Before reading each field, it checks that enough bytes remain inside the current frame. It advances a cursor in a visible way, converts raw bytes into fixed-width values with known endianness, and validates the result before using it for offsets, counts, allocation, or state changes. If a helper reads from the cursor, the helper should make failure and cursor movement obvious.\n\nSeparating raw input from trusted parsed objects keeps the design clearer. Raw bytes remain untrusted. Parsed fields are intermediate values. Trusted application objects are created only after required fields, lengths, ranges, versions, and state rules have been checked. This separation prevents partially parsed data from leaking into business logic as if it were complete.\n\nOffsets and derived ranges need the same discipline. A parser should prove that offset plus size stays within the current message, that nested records do not overlap unexpectedly, and that the cursor cannot move past the boundary. Hidden pointer arithmetic, unchecked indexing, and implicit cursor mutation make those proofs hard to review.\n\nThe best parsing code is often plain rather than clever. Each read says what it needs, what it produced, and what validation happened next. That makes binary protocol behavior testable and maintainable. It also gives reviewers a direct path through the code: frame validation, field extraction, range checks, state checks, and finally construction of a trusted object that application logic may use safely. Boring code is a strength here.",
  "narrationPoints": [
    "A parser should avoid directly casting a byte buffer into a C++ struct and treating the result as a valid protocol object.",
    "If a helper reads from the cursor, the helper should make failure and cursor movement obvious.",
    "Trusted application objects are created only after required fields, lengths, ranges, versions, and state rules have been checked.",
    "Offsets and derived ranges need the same discipline.",
    "Hidden pointer arithmetic, unchecked indexing, and implicit cursor mutation make those proofs hard to review.",
    "Each read says what it needs, what it produced, and what validation happened next."
  ]
};
