window.COURSE_MODULE = {
  "title": "Course Summary and Key Takeaways",
  "graphicAlt": "The randomness lifecycle spans entropy requirement, approved generator, encoding, unique storage, expiry, one-time use, collision handling, rotation, private telemetry, and incident response.",
  "narration": "Secure random number generation in Python is about using unpredictable values for security-sensitive purposes and keeping deterministic randomness out of secret generation. Values such as tokens, reset links, session identifiers, API keys, cryptographic keys, salts, and nonces may look like small implementation details, but they often carry access, identity, or cryptographic meaning. If they can be predicted, the larger control can fail.\n\nStrong designs use appropriate Python APIs, vetted cryptographic libraries, sufficient entropy, intentional length and encoding, safe token lifecycle controls, and careful logging. The general random module is useful for non-security work, simulations, and tests. Security-sensitive values should use interfaces intended for cryptographic unpredictability. API choice should be centralized and reviewed when values grant access or protect data.\n\nSalts, nonces, keys, initialization values, session identifiers, and tokens have different requirements. Salts usually need uniqueness rather than secrecy. Keys need strong secrecy and randomness. Nonces may need uniqueness or unpredictability depending on the protocol. Tokens need unpredictability, storage controls, expiration, revocation, and authorization-aware workflows. Understanding the purpose of each value is more important than making every string look complicated.\n\nThe goal is not to make values look random. The goal is to make security-sensitive values unpredictable, correctly scoped, safely stored, reviewable, and recoverable if exposed. Durable secure randomness comes from safe APIs, clear design decisions, deterministic testing boundaries, deployment discipline, privacy-aware logging, monitoring, and incident response planning.",
  "narrationPoints": [
    "Secure random number generation in Python is about using unpredictable values for security-sensitive purposes and keeping deterministic randomness out of secret generation.",
    "API choice should be centralized and reviewed when values grant access or protect data.",
    "Understanding the purpose of each value is more important than making every string look complicated.",
    "The goal is to make security-sensitive values unpredictable, correctly scoped, safely stored, reviewable, and recoverable if exposed.",
    "The general random module is useful for non-security work, simulations, and tests.",
    "Salts, nonces, keys, initialization values, session identifiers, and tokens have different requirements."
  ]
};
