window.COURSE_MODULE = {
  "title": "Choosing Algorithms and Libraries",
  "graphicAlt": "Hashing workflow for Choosing Algorithms and Libraries, tracing canonical input through an approved cryptographic provider to versioned digest metadata, bounded verification, and a documented acceptance or migration decision.",
  "narration": "C++ applications should not implement custom cryptographic hash algorithms. Correct cryptography depends on the algorithm design, the implementation, the library configuration, platform behavior, updates, side conditions, and review. A digest function may look simple from the outside, but reproducing a secure and maintainable implementation is not a good use of application engineering time.\n\nUse approved cryptographic libraries, platform APIs, or internal wrappers maintained by the organization. Algorithm selection should follow project policy, compliance needs, interoperability requirements, and the specific use case. A file integrity digest, a stored password verifier, and an authenticated message tag should not all be forced through the same helper just because they produce bytes. Good wrappers make the intended construction explicit and reduce accidental misuse. They also give maintainers one place to update defaults when policy changes.\n\nDependency versions and build configuration matter. A correct call site can still inherit risk from an outdated library, disabled provider, unsupported platform mode, or inconsistent encoding choice. Centralized wrappers can help by defining algorithm names, output formats, error handling, migration behavior, and test vectors in one place. The wrapper should stay thin and reviewable. It should guide teams toward approved use, not hide risky decisions behind a vague function named hash. Reviewers should be able to see which construction is being used and why it matches the security goal.",
  "narrationPoints": [
    "Correct cryptography depends on the algorithm design, the implementation, the library configuration, platform behavior, updates, side conditions, and review.",
    "A file integrity digest, a stored password verifier, and an authenticated message tag should not all be forced through the same helper just because they produce bytes.",
    "Use approved cryptographic libraries, platform APIs, or internal wrappers maintained by the organization.",
    "Algorithm selection should follow project policy, compliance needs, interoperability requirements, and the specific use case.",
    "Reviewers should be able to see which construction is being used and why it matches the security goal.",
    "A correct call site can still inherit risk from an outdated library, disabled provider, unsupported platform mode, or inconsistent encoding choice."
  ]
};
