window.COURSE_MODULE = {
  "title": "Migration, Compatibility, and Review Practices",
  "graphicAlt": "Hashing workflow for Migration, Compatibility, and Review Practices, tracing canonical input through an approved cryptographic provider to versioned digest metadata, bounded verification, and a documented acceptance or migration decision.",
  "narration": "Hash usage changes over time. Algorithms become deprecated, compliance requirements change, libraries are replaced, and stored digest formats need migration. A secure design should assume that today's approved choice may need to evolve. Versioned formats help systems recognize which algorithm and parameters were used without guessing from length or surrounding context. They also make failure cases clearer when a service encounters data it no longer supports.\n\nCompatibility windows should be intentional and time-bounded where possible. A system may need to read an old digest format while writing a new one, but that should not silently preserve weak policy forever. Migration behavior should be tested with old values, new values, invalid encodings, unsupported algorithms, wrong lengths, and failed upgrades. Operational teams should know how to measure migration progress and remove legacy support safely. Dashboards or reports can track remaining legacy records without exposing sensitive input data.\n\nCode review should flag deprecated algorithms, custom hash wrappers, unclear encoding, weak or unexplained digest lengths, unsafe truncation, password misuse, missing salts, and plain hashes used where authenticated integrity is required. Dependency review should confirm that cryptographic libraries are maintained and configured correctly. Governance keeps the same mistakes from returning under new helper names or compatibility flags. Architecture notes should record the approved patterns so new services do not need to rediscover the rules during a rushed integration.",
  "narrationPoints": [
    "Versioned formats help systems recognize which algorithm and parameters were used without guessing from length or surrounding context.",
    "Migration behavior should be tested with old values, new values, invalid encodings, unsupported algorithms, wrong lengths, and failed upgrades.",
    "A system may need to read an old digest format while writing a new one, but that should not silently preserve weak policy forever.",
    "Operational teams should know how to measure migration progress and remove legacy support safely.",
    "Code review should flag deprecated algorithms, custom hash wrappers, unclear encoding, weak or unexplained digest lengths, unsafe truncation, password misuse, missing salts, and plain hashes used where authenticated integrity is required.",
    "Dependency review should confirm that cryptographic libraries are maintained and configured correctly."
  ]
};
