window.COURSE_MODULE = {
  "title": "Understanding subprocess APIs and Execution Models",
  "graphicAlt": "Three execution models are compared: a structured argument list without a shell, a fixed application-owned shell script receiving stdin, and rejected caller-generated command text.",
  "narration": "Python provides multiple subprocess patterns because not every external program has the same lifecycle. A simple bounded command may fit a run-style helper that starts the program, waits for completion, and returns a result. A longer-lived interaction may require a lower-level process object. The secure choice is not about memorizing one favorite call. It is about matching the API to the task, output needs, timeout requirements, and failure behavior.\n\nReturn codes and check behavior matter because they determine how the parent application interprets success and failure. A child process may finish successfully, fail with a known validation problem, fail because a dependency is unavailable, or stop because the application timed it out. The Python code should translate those outcomes into safe application behavior instead of treating every failure as success or exposing raw diagnostic detail to users.\n\nStandard input, standard output, and standard error are also part of the security model. Input passed to a child process can influence behavior. Output may contain normal results, warnings, internal paths, sensitive values, or unexpectedly large data. Error streams may include details intended for operators, not external clients. Text and byte handling should be explicit enough that the application does not accidentally corrupt data, misread output, or log sensitive content.\n\nSubprocess code should be simple, explicit, and easy to review. Reviewers should be able to identify which executable runs, which arguments are passed, whether a shell is involved, which directory is used, which environment variables are inherited, how long the process may run, how output is handled, and what happens when it fails. If those answers are hidden in string assembly or scattered configuration, the design is harder to trust.",
  "narrationPoints": [
    "Python provides multiple subprocess patterns because not every external program has the same lifecycle.",
    "Return codes and check behavior matter because they determine how the parent application interprets success and failure.",
    "Standard input, standard output, and standard error are also part of the security model.",
    "Subprocess code should be simple, explicit, and easy to review.",
    "Output may contain normal results, warnings, internal paths, sensitive values, or unexpectedly large data.",
    "A simple bounded command may fit a run-style helper that starts the program, waits for completion, and returns a result."
  ]
};
