window.COURSE_MODULE = {
  "title": "Timeouts, Resource Controls, and Error Handling",
  "graphicAlt": "Nonblocking stdout draining and process waiting share one deadline and byte gauge; timeout or overflow kills and reaps the process group while CPU, memory, file, and descriptor limits constrain work.",
  "narration": "Timeouts are essential because child processes do not always finish quickly or predictably. A process may hang, wait for input, slow down under load, produce too much output, or depend on an unavailable service. Without a timeout, a web request, worker slot, or scheduled job can remain occupied indefinitely. Timeouts turn unbounded execution into an operational decision the application can handle.\n\nOutput management also affects availability. If a process produces more output than expected, captures are too large, or streams are not handled correctly, the parent process can consume memory, block, or lose useful diagnostic information. The application should decide whether output is captured, streamed, limited, stored, redacted, or discarded. Standard output and standard error should be treated as potentially sensitive until classified.\n\nExit codes and check behavior should be translated into safe application outcomes. Some failures are expected business problems, some are dependency failures, some are timeouts, and some are unexpected internal errors. User-facing responses should avoid raw command strings, sensitive arguments, full internal output, and unnecessary implementation detail. Internal logs can preserve safe diagnostic context, correlation IDs, operation names, durations, and reason codes.\n\nResource controls and retry behavior prevent subprocess failures from becoming denial-of-service conditions. Concurrency limits, queue limits, output limits, cancellation behavior, and process termination rules should be part of the design. Retrying a failed child process may be appropriate for transient failures, but repeated execution can duplicate work, amplify outages, or leave partial artifacts. Failure should be predictable, observable, and recoverable.",
  "narrationPoints": [
    "Without a timeout, a web request, worker slot, or scheduled job can remain occupied indefinitely.",
    "The application should decide whether output is captured, streamed, limited, stored, redacted, or discarded.",
    "User-facing responses should avoid raw command strings, sensitive arguments, full internal output, and unnecessary implementation detail.",
    "Concurrency limits, queue limits, output limits, cancellation behavior, and process termination rules should be part of the design.",
    "Internal logs can preserve safe diagnostic context, correlation IDs, operation names, durations, and reason codes.",
    "Timeouts are essential because child processes do not always finish quickly or predictably."
  ]
};
