window.COURSE_MODULE = {
  "title": "Least Privilege, Logging, Testing, and Monitoring",
  "graphicAlt": "A report worker runs as a dedicated user and group inside a fixed working directory with restrictive umask; telemetry records only approved operation, outcome, and bounded duration.",
  "narration": "Subprocesses should run with the least privilege needed for the approved task. They should not run as administrator or root-equivalent accounts simply because that is convenient. Service accounts, workload identities, containers, restricted runtimes, sandboxing concepts, read-only filesystems, constrained volumes, and limited network access can reduce damage if a child process behaves unexpectedly. The exact mechanism changes by platform, but the principle does not.\n\nLogging should support review without leaking secrets. Useful records include the approved operation name, component, environment, caller context at an appropriate level, correlation ID, duration, timeout status, exit category, and safe reason code. Logs should avoid raw sensitive arguments, credentials, tokens, private file contents, full environment dumps, full internal output, and unnecessary paths. High-impact subprocess activity may also need audit events.\n\nTesting should include more than the successful path. Tests can verify approved operations, rejected inputs, shell avoidance, path containment, environment minimization, timeout behavior, output limits, error translation, authorization checks, and logging redaction. Code review should ask who can influence the executable, arguments, working directory, files, environment, streams, privileges, and lifecycle. Those questions expose hidden trust boundaries.\n\nMonitoring should watch for unusual subprocess behavior: repeated failures, rejected attempts, unexpected operation names, long-running jobs, timeouts, high concurrency, large output, or execution from unexpected components. If unsafe behavior or leaked output is discovered, teams should contain the workflow, rotate exposed secrets when needed, review logs and artifacts, fix the design, and add regression tests. Secure subprocess usage must be maintained as systems evolve.",
  "narrationPoints": [
    "Subprocesses should run with the least privilege needed for the approved task.",
    "Logs should avoid raw sensitive arguments, credentials, tokens, private file contents, full environment dumps, full internal output, and unnecessary paths.",
    "Code review should ask who can influence the executable, arguments, working directory, files, environment, streams, privileges, and lifecycle.",
    "Secure subprocess usage must be maintained as systems evolve.",
    "The exact mechanism changes by platform, but the principle does not.",
    "High-impact subprocess activity may also need audit events."
  ]
};
